export const g3Unit2Questions = [
  {
    questionId: "g3_u2_q001",
    unitId: "g3_u2",
    type: "multiple_choice" as const,
    difficulty: 1 as const,
    question: {
      text: "スーパーマーケットで、野菜や果物の産地がわかるように書いてあるのは、なぜでしょう？",
      choices: [
        { id: "a", text: "お客さんがどこで作られたか知るため" },
        { id: "b", text: "値段を高く見せるため" },
        { id: "c", text: "店の名前を覚えてもらうため" },
        { id: "d", text: "包装紙を減らすため" },
      ],
    },
    answer: { correct_ids: ["a"] },
    explanation: {
      short: "産地表示は、お客さんがどこで作られた商品か選びやすくするための工夫です。",
    },
    curriculum_ref: { grade: 3, unit_number: 2, learning_point: "スーパーの工夫" },
    tags: ["スーパー", "産地"],
    hint: "お客さんが買い物をするときに役立つ情報を考えてみよう。",
  },
  {
    questionId: "g3_u2_q002",
    unitId: "g3_u2",
    type: "multiple_choice" as const,
    difficulty: 1 as const,
    question: {
      text: "スーパーマーケットが、朝早くから夜遅くまで開いているのは、どんな理由が考えられますか？",
      choices: [
        { id: "a", text: "働く人の生活に合わせて買い物しやすくするため" },
        { id: "b", text: "電気代を節約するため" },
        { id: "c", text: "商品を少なく並べるため" },
        { id: "d", text: "店員の数を減らすため" },
      ],
    },
    answer: { correct_ids: ["a"] },
    explanation: {
      short: "営業時間を長くすると、仕事のあとや朝早くなど、さまざまな時間に買い物できます。",
    },
    curriculum_ref: { grade: 3, unit_number: 2, learning_point: "営業時間" },
    tags: ["スーパー", "営業時間"],
    hint: "お父さんやお母さんがいつ買い物をするか考えてみよう。",
  },
  {
    questionId: "g3_u2_q003",
    unitId: "g3_u2",
    type: "multiple_choice" as const,
    difficulty: 1 as const,
    question: {
      text: "農家さんの仕事で、畑や田んぼで行う主な作業はどれですか？",
      choices: [
        { id: "a", text: "種をまいたり、水をやったり、野菜や米を収穫する" },
        { id: "b", text: "パンを焼いて店に並べる" },
        { id: "c", text: "お客さんにレジで会計する" },
        { id: "d", text: "トラックで荷物を運ぶ" },
      ],
    },
    answer: { correct_ids: ["a"] },
    explanation: {
      short: "農家さんは畑や田んぼで作物を育て、収穫する仕事をしています。",
    },
    curriculum_ref: { grade: 3, unit_number: 2, learning_point: "農業" },
    tags: ["農家", "生産"],
    hint: "米や野菜はどこで育つか思い出してみよう。",
  },
  {
    questionId: "g3_u2_q004",
    unitId: "g3_u2",
    type: "multiple_choice" as const,
    difficulty: 1 as const,
    question: {
      text: "工場で行われる仕事として正しいものはどれですか？",
      choices: [
        { id: "a", text: "機械を使って商品をたくさん作る" },
        { id: "b", text: "魚を海でとる" },
        { id: "c", text: "店の前でチラシを配る" },
        { id: "d", text: "畑でトマトを育てる" },
      ],
    },
    answer: { correct_ids: ["a"] },
    explanation: {
      short: "工場では機械や人の手で、同じ商品を効率よくたくさん作ります。",
    },
    curriculum_ref: { grade: 3, unit_number: 2, learning_point: "工業" },
    tags: ["工場", "生産"],
    hint: "パンやお菓子、自動車などはどこで作られるか考えてみよう。",
  },
  {
    questionId: "g3_u2_q005",
    unitId: "g3_u2",
    type: "multiple_choice" as const,
    difficulty: 1 as const,
    question: {
      text: "パン屋さんの仕事と、地域の人々の生活の関わりとして正しいものはどれですか？",
      choices: [
        { id: "a", text: "毎日食べるパンを近くで作って届ける" },
        { id: "b", text: "外国の法律を決める" },
        { id: "c", text: "山の木を切って家を建てる" },
        { id: "d", text: "天気予報を伝える" },
      ],
    },
    answer: { correct_ids: ["a"] },
    explanation: {
      short: "パン屋さんは地域の人々が毎日食べるパンを作り、生活を支えています。",
    },
    curriculum_ref: { grade: 3, unit_number: 2, learning_point: "仕事と生活" },
    tags: ["パン屋", "生活"],
    hint: "朝ごはんやおやつに使うものを考えてみよう。",
  },
  {
    questionId: "g3_u2_q006",
    unitId: "g3_u2",
    type: "multiple_choice" as const,
    difficulty: 2 as const,
    question: {
      text: "スーパーマーケットが、いろいろな種類の商品を並べる（品ぞろえ）理由として最も適切なものはどれですか？",
      choices: [
        { id: "a", text: "お客さんの好みや必要に合わせて選べるようにするため" },
        { id: "b", text: "店の床を広く見せるため" },
        { id: "c", text: "商品を値下げするため" },
        { id: "d", text: "店員の仕事を減らすため" },
      ],
    },
    answer: { correct_ids: ["a"] },
    explanation: {
      short: "品ぞろえは、お客さんが欲しいものを見つけやすくするための大切な工夫です。",
    },
    curriculum_ref: { grade: 3, unit_number: 2, learning_point: "品ぞろえ" },
    tags: ["スーパー", "販売"],
    hint: "大きい店ほど、いろいろな商品がある理由を考えてみよう。",
  },
  {
    questionId: "g3_u2_q007",
    unitId: "g3_u2",
    type: "multiple_choice" as const,
    difficulty: 2 as const,
    question: {
      text: "漁師さんの仕事の流れとして正しい順番に近いものはどれですか？",
      choices: [
        { id: "a", text: "海で魚をとる → 市場や店に届ける → 人々の食卓へ" },
        { id: "b", text: "店で売る → 海でとる → 畑で育てる" },
        { id: "c", text: "工場で加工する → 種をまく → 海でとる" },
        { id: "d", text: "外国から運ぶ → 畑で育てる → 海でとる" },
      ],
    },
    answer: { correct_ids: ["a"] },
    explanation: {
      short: "漁師さんがとった魚は、市場や店を通って私たちの食卓に届きます。",
    },
    curriculum_ref: { grade: 3, unit_number: 2, learning_point: "漁業の流れ" },
    tags: ["漁師", "工程"],
    hint: "魚が海から食卓に来るまでの道のりを想像してみよう。",
  },
  {
    questionId: "g3_u2_q008",
    unitId: "g3_u2",
    type: "multiple_choice" as const,
    difficulty: 2 as const,
    question: {
      text: "トラックや船、飛行機で商品を運ぶ仕事をする人は、地域の生活とどう関わっていますか？",
      choices: [
        { id: "a", text: "他の地域や外国で作られた商品を届けて生活を豊かにする" },
        { id: "b", text: "天気を調べて農家に教える" },
        { id: "c", text: "店のレジでお金を受け取る" },
        { id: "d", text: "畑で野菜の種をまく" },
      ],
    },
    answer: { correct_ids: ["a"] },
    explanation: {
      short: "運ぶ仕事があるから、遠くで作られた商品も私たちの手元に届きます。",
    },
    curriculum_ref: { grade: 3, unit_number: 2, learning_point: "流通" },
    tags: ["運送", "地域"],
    hint: "バナナやオレンジなど、日本であまり作られないものはどうやって来るか考えよう。",
  },
  {
    questionId: "g3_u2_q009",
    unitId: "g3_u2",
    type: "multiple_choice" as const,
    difficulty: 2 as const,
    question: {
      text: "地域の特産品（その土地で有名なもの）を売る店がある理由として正しいものはどれですか？",
      choices: [
        { id: "a", text: "その地域で作られた良い商品を広く知ってもらうため" },
        { id: "b", text: "外国の商品だけを売るため" },
        { id: "c", text: "店の電気代をなくすため" },
        { id: "d", text: "農家の仕事をやめさせるため" },
      ],
    },
    answer: { correct_ids: ["a"] },
    explanation: {
      short: "特産品を売ることで、その地域の生産の仕事が応援され、広まります。",
    },
    curriculum_ref: { grade: 3, unit_number: 2, learning_point: "特産品" },
    tags: ["特産品", "販売"],
    hint: "お土産屋さんで売っているものを思い出してみよう。",
  },
  {
    questionId: "g3_u2_q010",
    unitId: "g3_u2",
    type: "multiple_choice" as const,
    difficulty: 2 as const,
    question: {
      text: "米を作るまでの流れとして正しいものはどれですか？",
      choices: [
        { id: "a", text: "田んぼを準備する → 苗を植える → 水を管理する → 収穫する" },
        { id: "b", text: "収穫する → 苗を植える → 店で売る → 種をまく" },
        { id: "c", text: "工場で焼く → 海でとる → 畑で干す" },
        { id: "d", text: "外国から運ぶ → そのまま食べる → 種をまく" },
      ],
    },
    answer: { correct_ids: ["a"] },
    explanation: {
      short: "米は田んぼで長い時間をかけて育て、秋などに収穫します。",
    },
    curriculum_ref: { grade: 3, unit_number: 2, learning_point: "稲作" },
    tags: ["農家", "米"],
    hint: "田植えや稲刈りという言葉を思い出してみよう。",
  },
  {
    questionId: "g3_u2_q011",
    unitId: "g3_u2",
    type: "multiple_choice" as const,
    difficulty: 2 as const,
    question: {
      text: "コンビニエンスストアが地域の人々の生活に役立つ例として正しいものはどれですか？",
      choices: [
        { id: "a", text: "近くで必要なものを早朝や深夜でも買える" },
        { id: "b", text: "米を田んぼで育てる" },
        { id: "c", text: "外国の国の法律を作る" },
        { id: "d", text: "大きな工場で自動車を作る" },
      ],
    },
    answer: { correct_ids: ["a"] },
    explanation: {
      short: "コンビニは家の近くにあり、長い時間営業しているので便利です。",
    },
    curriculum_ref: { grade: 3, unit_number: 2, learning_point: "コンビニ" },
    tags: ["コンビニ", "生活"],
    hint: "急に必要なものを買うとき、どこに行くか考えてみよう。",
  },
  {
    questionId: "g3_u2_q012",
    unitId: "g3_u2",
    type: "multiple_choice" as const,
    difficulty: 2 as const,
    question: {
      text: "外国から日本に届く商品の例として正しいものはどれですか？",
      choices: [
        { id: "a", text: "コーヒー豆やバナナなど、温暖な国で作られるもの" },
        { id: "b", text: "すべてのお米" },
        { id: "c", text: "すべての魚" },
        { id: "d", text: "すべてのパン" },
      ],
    },
    answer: { correct_ids: ["a"] },
    explanation: {
      short: "コーヒー豆やバナナなど、日本の気候では育てにくいものは外国から輸入されます。",
    },
    curriculum_ref: { grade: 3, unit_number: 2, learning_point: "輸入" },
    tags: ["外国", "商品"],
    hint: "日本の気候で育てにくい食べ物はどこから来るか考えよう。",
  },
  {
    questionId: "g3_u2_q013",
    unitId: "g3_u2",
    type: "multiple_choice" as const,
    difficulty: 3 as const,
    question: {
      text: "農家で作った野菜がスーパーの店頭に並ぶまでに、関わる仕事の組み合わせとして最も適切なものはどれですか？",
      choices: [
        { id: "a", text: "農家 → 運ぶ人 → スーパーで並べる・売る人" },
        { id: "b", text: "スーパー → 農家 → 外国の政府" },
        { id: "c", text: "工場 → 漁師 → パン屋" },
        { id: "d", text: "レジ → 畑 → 天気予報" },
      ],
    },
    answer: { correct_ids: ["a"] },
    explanation: {
      short: "生産 → 運ぶ → 販売という流れで、野菜がお客さんの手に届きます。",
      detail: "それぞれの仕事がつながって、地域の生活を支えています。",
    },
    curriculum_ref: { grade: 3, unit_number: 2, learning_point: "生産と販売の流れ" },
    tags: ["工程", "スーパー"],
    hint: "野菜が畑から店に来るまで、何人の仕事が関わるか想像してみよう。",
  },
  {
    questionId: "g3_u2_q014",
    unitId: "g3_u2",
    type: "multiple_choice" as const,
    difficulty: 3 as const,
    question: {
      text: "「地元の新鮮な野菜を優先して並べる」スーパーの工夫が、地域全体に与える良い影響として最も適切なものはどれですか？",
      choices: [
        { id: "a", text: "地元の農家の仕事が支えられ、新鮮な野菜を食べやすくなる" },
        { id: "b", text: "外国との交流がなくなる" },
        { id: "c", text: "店の営業時間が短くなる" },
        { id: "d", text: "商品の種類が必ず減る" },
      ],
    },
    answer: { correct_ids: ["a"] },
    explanation: {
      short: "地元の農家を応援することで、地域の生産の仕事と生活がつながります。",
    },
    curriculum_ref: { grade: 3, unit_number: 2, learning_point: "地域と生産" },
    tags: ["スーパー", "農家", "地域"],
    hint: "近くの農家を応援すると、どんな良いことがあるか考えてみよう。",
  },
  {
    questionId: "g3_u2_q015",
    unitId: "g3_u2",
    type: "multiple_choice" as const,
    difficulty: 3 as const,
    question: {
      text: "次の説明のうち、生産と販売の仕事について最も正しいものはどれですか？",
      choices: [
        { id: "a", text: "生産の仕事で作られたものを、販売の仕事が届け、人々の生活を支える" },
        { id: "b", text: "生産と販売は関係なく、それぞれ別の国だけで行われる" },
        { id: "c", text: "販売の仕事だけがあれば、食べ物は自動的に生まれる" },
        { id: "d", text: "生産の仕事はスーパーのレジだけを指す" },
      ],
    },
    answer: { correct_ids: ["a"] },
    explanation: {
      short: "生産と販売の仕事がつながることで、私たちの生活に必要なものが届きます。",
      detail: "この単元のまとめとして、さまざまな仕事のつながりを考えましょう。",
    },
    curriculum_ref: { grade: 3, unit_number: 2, learning_point: "単元まとめ" },
    tags: ["まとめ", "生産", "販売"],
    hint: "この単元で学んだ「作る仕事」と「売る・届ける仕事」を思い出してみよう。",
  },
];
