/**
 * 問題用の 絵（16×16 の ドット絵）。英単語の picture-word などで使う。
 * 本番の絵（assets/questions/eigo/<word>.png）が できるまでの 仮の絵で、レンダラーが SVG にして 描く。
 *
 * 色は NQ-48 パレット（src/scenes/art/palette.ts）と同じ値。レンダラーは scenes を import できないので、
 * 使う色だけ ここに 写している（テストで パレットの中の色か 確かめる）。
 * 1 文字が 1 ドット。'.' は すけ、'k' は 輪郭（ink）。ほかの文字の 色は 絵ごとに 決める。
 */
const C = {
  ink: '#1a1428',
  gray: '#6b6f80',
  silver: '#a3aabb',
  cloud: '#d2d7e2',
  paper: '#f4f1e8',
  white: '#ffffff',
  brick: '#a8341f',
  red: '#e5484d',
  apricot: '#ff9e5e',
  ochre: '#c79a1a',
  yellow: '#ffd447',
  cream: '#fff3a3',
  forest: '#1f5a2e',
  green: '#2a7a36',
  leaf: '#4cbf4c',
  lime: '#8fe36f',
  sprout: '#e8f7a0',
  navy: '#1a2b5e',
  blue: '#1f4fa3',
  azure: '#3d8ef0',
  sky: '#80c6ff',
  ice: '#c8f4ff',
  indigo: '#3a2672',
  violet: '#6e4fc4',
  lavender: '#a28be6',
  brown: '#7a5230',
  tan: '#c08a55',
  blush: '#ff8fb1',
  berry: '#c2405a',
  orange: '#f2a93b',
  amber: '#b8741f',
} as const;

export interface Picture {
  rows: readonly string[];
  colors: Readonly<Record<string, string>>;
}

const pic = (colors: Record<string, string>, rows: string[]): Picture => ({
  rows,
  colors: { k: C.ink, ...colors },
});

export const PICTURES = {
  // ───── くだもの ─────
  apple: pic({ r: C.red, d: C.brick, w: C.white, b: C.brown, g: C.leaf, G: C.green }, [
    '................',
    '........k.kkk...',
    '.......kbkgggk..',
    '.......kbkGgk...',
    '...kkkkkbkkkk...',
    '..krwwrrrrrrrk..',
    '.krwwrrrrrrrrrk.',
    '.krwrrrrrrrrrrk.',
    '.krrrrrrrrrrrrk.',
    '.krrrrrrrrrrrdk.',
    '.krrrrrrrrrrrdk.',
    '.krrrrrrrrrrddk.',
    '..krrrrrrrrddk..',
    '...krrrrrrddk...',
    '....kkkkkkkk....',
    '................',
  ]),
  banana: pic({ y: C.yellow, o: C.ochre, c: C.cream, b: C.brown }, [
    '................',
    '............kk..',
    '...........kbbk.',
    '...........kyyk.',
    '..........kcyyk.',
    '..........kcyyok',
    '.........kcyyyok',
    '........kcyyyok.',
    '.......kcyyyyok.',
    '.....kkcyyyyok..',
    '...kkcyyyyyyok..',
    '.kkyyyyyyyook...',
    'kbyyyyyooook....',
    '.kkkkkkkkk......',
    '................',
    '................',
  ]),
  grapes: pic({ v: C.violet, i: C.indigo, l: C.lavender, b: C.brown, g: C.leaf }, [
    '................',
    '......kk.kkk....',
    '......kbkgggk...',
    '.kkkkkkbkkkkkk..',
    '.klvvklvvklvvk..',
    '.kvvvkvvvkvvvk..',
    '.kvvikvvikvvik..',
    '.kkklvvklvvkkk..',
    '...kvvvkvvvk....',
    '...kvvikvvik....',
    '...kkklvvkkk....',
    '.....kvvvk......',
    '.....kvvik......',
    '......kkk.......',
    '................',
    '................',
  ]),
  orange: pic({ o: C.orange, a: C.amber, p: C.apricot, g: C.leaf, G: C.green }, [
    '................',
    '.......kkkk.....',
    '......kggGGk....',
    '....kkkkkkkkk...',
    '...kppooooooak..',
    '..kppoooooooaak.',
    '.kpooooooooooak.',
    '.kpooooooooooak.',
    '.koooooooooooak.',
    '.koooooooooooak.',
    '.koooooooooooak.',
    '.koooooooooaaak.',
    '..koooooooaaak..',
    '...kooooaaaak...',
    '....kkkkkkkk....',
    '................',
  ]),
  peach: pic({ P: C.blush, B: C.berry, w: C.white, g: C.leaf, G: C.green }, [
    '................',
    '...kkk....kkk...',
    '..kgggk..kgggk..',
    '...kGgkkkkgGk...',
    '...kwwPPkPPPk...',
    '..kwwPPPBPPPPk..',
    '.kwwPPPPBPPPPPk.',
    '.kwPPPPPBPPPPPk.',
    '.kPPPPPPBPPPPBk.',
    '.kPPPPPPBPPPPBk.',
    '.kPPPPPPPPPPBBk.',
    '..kPPPPPPPPBBk..',
    '...kPPPPPPBBk...',
    '....kkPPPBkk....',
    '......kkkk......',
    '................',
  ]),
  strawberry: pic({ r: C.red, d: C.brick, w: C.white, y: C.yellow, g: C.leaf, G: C.green }, [
    '................',
    '......k..k......',
    '.....kgkkgk.....',
    '...kkgGggGgkk...',
    '..kgggGkkGgggk..',
    '.krrkkrrrrkkrrk.',
    '.krwryrrryrrrrk.',
    '.kwrrrrryrrryrk.',
    '.kryrrryrrrrrdk.',
    '..krrryrrryrdk..',
    '..kryrrrryrddk..',
    '...krrryrrddk...',
    '....kryrrddk....',
    '.....krrddk.....',
    '......kkkk......',
    '................',
  ]),
  lemon: pic({ y: C.yellow, o: C.ochre, c: C.cream, g: C.leaf }, [
    '................',
    '................',
    '...........k....',
    '..........kgk...',
    '.....kkkkkkgk...',
    '...kkccyyyykk...',
    '..kccyyyyyyyok..',
    '.kcyyyyyyyyyyok.',
    'kyyyyyyyyyyyyook',
    'kyyyyyyyyyyyyook',
    '.kyyyyyyyyyyook.',
    '..kyyyyyyyyook..',
    '...kkyyyyyookk..',
    '.....kkkkkk.....',
    '................',
    '................',
  ]),
  cherry: pic({ r: C.red, d: C.brick, w: C.white, g: C.leaf, G: C.green }, [
    '................',
    '.......kkk.kkk..',
    '......kGGkkgggk.',
    '.....kGk.kGkkk..',
    '....kGk...kGk...',
    '...kGk....kGk...',
    '..kGk.....kGk...',
    '..kkk.....kkk...',
    '.krwrk...krwrk..',
    'krwrrrk.krwrrrk.',
    'krrrrrk.krrrrrk.',
    'krrrrdk.krrrrdk.',
    '.krrdk...krrdk..',
    '..kkk.....kkk...',
    '................',
    '................',
  ]),
  melon: pic({ g: C.leaf, G: C.green, l: C.lime, s: C.sprout, b: C.brown }, [
    '................',
    '......kkkk......',
    '......kbbk......',
    '....kkkbbkkkk...',
    '...klsgggsgGGk..',
    '..klgsgsgsgsGGk.',
    '.klggsgggsggGGk.',
    '.kgsgggsgggsGGk.',
    '.kggsgsgsgsgGGk.',
    '.kgsgggsgggsGGk.',
    '.kggsgggsgggGGk.',
    '.kgsgsgsgsgGGGk.',
    '..kgggsgggsGGk..',
    '...kGsGGGsGGk...',
    '....kkkkkkkk....',
    '................',
  ]),

  // ───── どうぶつ ─────
  dog: pic({ b: C.brown, t: C.tan, w: C.paper, p: C.blush }, [
    '................',
    '................',
    '..kkk......kkk..',
    '.kbbbkkkkkkbbbk.',
    '.kbbkttttttkbbk.',
    '.kbbkttttttkbbk.',
    '.kbbtkttttktbbk.',
    '.kbbttttttttbbk.',
    '..kbttwwwwttbk..',
    '..kbtwwkkwwtbk..',
    '...kkwwwwwwkk...',
    '....kwwkkwwk....',
    '.....kwppwk.....',
    '......kkkk......',
    '................',
    '................',
  ]),
  cat: pic({ s: C.apricot, p: C.blush, w: C.paper }, [
    '................',
    '...k........k...',
    '..kpk......kpk..',
    '..kppkkkkkkppk..',
    '..kssssssssssk..',
    '.kssssssssssssk.',
    '.kssskssssksssk.',
    '.kssskssssksssk.',
    '.kssssssssssssk.',
    '.kswwwwppwwwwsk.',
    'kkswwwkwwkwwwskk',
    '..kswwwkkwwwsk..',
    '...kksssssskk...',
    '.....kkkkkk.....',
    '................',
    '................',
  ]),
  rabbit: pic({ w: C.white, c: C.cloud, p: C.blush }, [
    '....kk....kk....',
    '...kwwk..kwwk...',
    '...kwpk..kpwk...',
    '...kwpk..kpwk...',
    '...kwpk..kpwk...',
    '...kwpk..kpwk...',
    '..kkwwkkkkwwkk..',
    '.kwwwwwwwwwwwck.',
    '.kwwkwwwwwwkwck.',
    '.kwwkwwwwwwkwck.',
    '.kpwwwwppwwwwpk.',
    '.kwwwwkwwkwwwck.',
    '..kwwwwkkwwwck..',
    '...kkwwwwwcck...',
    '.....kkkkkk.....',
    '................',
  ]),
  bird: pic({ a: C.azure, b: C.blue, s: C.ice, o: C.orange }, [
    '................',
    '................',
    '........kkk.....',
    '.......kaaak....',
    '......kaaakak...',
    '......kaaaaakoo.',
    'kk...kaaaaaaak..',
    'kbbkkaabbbaaak..',
    '.kbbaaabbbbaaak.',
    '..kbaaaabbbassk.',
    '...kaaaaabbsssk.',
    '....kaaasssssk..',
    '.....kkkkkkkk...',
    '......o.o.......',
    '.....oo.oo......',
    '................',
  ]),
  pig: pic({ p: C.blush, B: C.berry }, [
    '................',
    '..kk........kk..',
    '..kpk......kpk..',
    '..kppkkkkkkppk..',
    '..kppppppppppk..',
    '.kppppppppppppk.',
    '.kppkppppppkppk.',
    '.kpppkkkkkkpppk.',
    '.kppkBBBBBBkppk.',
    '.kppkBkBBkBkppk.',
    '.kppkBBBBBBkppk.',
    '..kppkkkkkkppk..',
    '...kkppppppkk...',
    '.....kkkkkk.....',
    '................',
    '................',
  ]),
  bear: pic({ b: C.brown, t: C.tan }, [
    '................',
    '................',
    '..kkk......kkk..',
    '.kbtbk....kbtbk.',
    '.kbbbkkkkkkbbbk.',
    '..kbbbbbbbbbbk..',
    '.kbbbbbbbbbbbbk.',
    '.kbbkbbbbbbkbbk.',
    '.kbbbbttttbbbbk.',
    '.kbbbttkkttbbbk.',
    '.kbbbtkttktbbbk.',
    '..kbbbttttbbbk..',
    '...kbbbbbbbbk...',
    '....kkkkkkkk....',
    '................',
    '................',
  ]),
  elephant: pic({ s: C.silver, g: C.gray, p: C.blush, w: C.white }, [
    '................',
    '................',
    '.....kkkkkk.....',
    '.kkkksssssskkkk.',
    'kppgksssssskgppk',
    'kppgskssssksgppk',
    'kppgssssssssgppk',
    'kpggssssssssggpk',
    '.kggssssssssggk.',
    '..kkgssssssgkk..',
    '....kwsssswk....',
    '......kssk......',
    '......kssk......',
    '......ksskk.....',
    '.......kkk......',
    '................',
  ]),
  frog: pic({ g: C.leaf, G: C.green, l: C.sprout, w: C.white, p: C.blush }, [
    '................',
    '..kkk......kkk..',
    '.kwwwk....kwwwk.',
    '.kwkwkkkkkkwkwk.',
    '.kggggggggggggk.',
    'kggggggggggggggk',
    'kgpggggggggggpgk',
    'kgkggggggggggkgk',
    'kggkkkkkkkkkkggk',
    '.kggggggggggggk.',
    '..kGllllllllGk..',
    '..kGllllllllGk..',
    '.kGGkllllllkGGk.',
    'kgggkkkkkkkkgggk',
    'kkkkk......kkkkk',
    '................',
  ]),

  // ───── うみの いきもの ─────
  fish: pic({ a: C.azure, b: C.blue, s: C.ice, w: C.white }, [
    '................',
    '................',
    '................',
    '................',
    '.....kkkk.......',
    '...kkaaaakk..kk.',
    '..kaaaaaaaak.kak',
    '.kawkaaaaaaakaak',
    'kaaaaabaaaaaaaak',
    'kssssbsssssaaaak',
    '.kssssssssskbak.',
    '..kssssssssk.kbk',
    '...kkssssskk..kk',
    '.....kkkk.......',
    '................',
    '................',
  ]),
  crab: pic({ r: C.red, d: C.brick, w: C.white }, [
    '................',
    '................',
    '.kk..........kk.',
    'krrk.kk..kk.krrk',
    'k.rk.wk..kw.kr.k',
    '.krk.kk..kk.krk.',
    '..kkkkkkkkkkkk..',
    '.krrrrrrrrrrrrk.',
    'krrrrrrrrrrrrrdk',
    'krrrrrrrrrrrrrdk',
    '.krrrrrrrrrrrdk.',
    'k.kkrrrrrrrrkk.k',
    '.k.kkkkkkkkkk.k.',
    'k.k..........k.k',
    '................',
    '................',
  ]),
  octopus: pic({ r: C.red, d: C.brick, p: C.blush, w: C.white }, [
    '................',
    '.....kkkkkk.....',
    '...kkrrrrrrkk...',
    '..krpprrrrrrrk..',
    '.krpprrrrrrrrrk.',
    '.krrrrrrrrrrrdk.',
    '.krrwkrrrrwkrdk.',
    '.krrwkrrrrwkrdk.',
    '..krrrrkkrrrrk..',
    '.krrrrrrrrrrrrk.',
    'krrkrrkrrkrrkrrk',
    'krrkrrkrrkrrkrrk',
    'kr.kr.krrk.rk.rk',
    '.k..k..kk..k..k.',
    '................',
    '................',
  ]),
  whale: pic({ b: C.blue, n: C.navy, s: C.sky, w: C.white, a: C.ice }, [
    '................',
    '................',
    '..a..a..........',
    '...aa...........',
    '....a...........',
    '...kkkkkkk...kk.',
    '..kbbbbbbbkk.kbk',
    '.kbbbbbbbbbbkbk.',
    'kbbwkbbbbbbbbbk.',
    'kbbbbbbbbbbbbbk.',
    'knnnnbbbbbbbbk..',
    'kssssssssbbbk...',
    '.kssssssssbk....',
    '..kkkkkkkkk.....',
    '................',
    '................',
  ]),
  turtle: pic({ l: C.lime, G: C.green, F: C.forest }, [
    '................',
    '................',
    '......kkkk......',
    '.....kllllk.....',
    '.....klkklk.....',
    '..kk..kllk..kk..',
    '.kllkkkkkkkkllk.',
    '...kGGFGGFGGk...',
    '..kGGFlllFGGGk..',
    '..kFFFlllFFFFk..',
    '..kGGFlllFGGGk..',
    '...kGGFGGFGGk...',
    '.kllkkkkkkkkllk.',
    '..kk...kk...kk..',
    '................',
    '................',
  ]),
  starfish: pic({ o: C.orange, a: C.amber, y: C.yellow }, [
    '................',
    '.......kk.......',
    '......koak......',
    '......koak......',
    '.....kooaak.....',
    'kkkkkkooaakkkkkk',
    'kooooyooooyoooak',
    '.kaooooooooooak.',
    '..kaaooyoooaak..',
    '...kooooooook...',
    '..kooookkooook..',
    '..kooak..kaook..',
    '.kooak....kaook.',
    '.koak......kaok.',
    'kkk..........kkk',
    '................',
  ]),
} satisfies Record<string, Picture>;

export type PictureKey = keyof typeof PICTURES;
export const PICTURE_KEYS = Object.keys(PICTURES) as [PictureKey, ...PictureKey[]];

/** 絵を SVG の 文字列に（横に つづく 同じ色は 1 本の rect に まとめる） */
export function pictureSvg(key: PictureKey): string {
  const { rows, colors } = PICTURES[key];
  const rects: string[] = [];
  rows.forEach((row, y) => {
    for (let x = 0; x < row.length;) {
      const ch = row[x]!;
      let w = 1;
      while (row[x + w] === ch) w++;
      const fill = colors[ch];
      if (fill) rects.push(`<rect x="${x}" y="${y}" width="${w}" height="1" fill="${fill}"/>`);
      x += w;
    }
  });
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" shape-rendering="crispEdges">${rects.join('')}</svg>`;
}

/** <img src> に そのまま 入れられる形 */
export const pictureUrl = (key: PictureKey): string =>
  `data:image/svg+xml;charset=utf-8,${encodeURIComponent(pictureSvg(key))}`;
