/**
 * 名所の絵（32×32 の えはがき）。名所・特産品を 見つけた カットインの 左の 絵に つかう。
 * 本番の イラスト（assets/motifs/<県>/<id>.png）が できるまでの 仮素材。
 * 名所（landmark・nature・festival・history）ごとに「場面」（城・滝・花火…）と その えらび（v）を きめて かく。
 * 特産品（food・craft）は どうぐの アイコン（itemIcons）を つかうので ここには ない。
 * ※ 以前は 種類ごとの 8×8 アイコン（motif-landmark など）を 9 倍にしただけで、どの 名所も 同じ・意味が わからなかった
 */
import type { Motif } from '../../core/content/schemas';
import { existingAssetUrl } from '../assetCatalog';
import { makeGrid, toCanvas, type Grid } from '../grid';
import { BUILDINGS, type BuildingKey } from './buildings';
import { EVENTS, type EventKey } from './events';
import { frame, MA, type SceneFn } from './kit';
import { NATURE, type NatureKey } from './nature';

export type SceneKey = BuildingKey | NatureKey | EventKey;

export const SCENES: Readonly<Record<SceneKey, SceneFn>> = { ...BUILDINGS, ...NATURE, ...EVENTS };

/**
 * motif の id → 場面（'key' または 'key:v'）。名所は ぜんぶ ここに のせる（テストで たしかめる）。
 * 同じ id が ほかの 県に あっても 同じ 場面で よいものだけ（今は かさなりなし）
 */
export const MOTIF_SCENES: Readonly<Record<string, string>> = {
  // ── 名所（landmark）
  kakunodate: 'oldTown:sakura',
  osorezan: 'pinwheels',
  'hirosaki-jo': 'castle:sakura',
  naritasan: 'temple',
  inubosaki: 'lighthouse',
  'dogo-onsen': 'onsen:building',
  shimanami: 'bigBridge',
  eiheiji: 'mountainTemple',
  dazaifu: 'shrine:plum',
  mojiko: 'port:retro',
  yanagawa: 'riverBoat:canal',
  tsurugajo: 'castle:red',
  ouchijuku: 'thatched:street',
  shioyasaki: 'lighthouse',
  'gero-onsen': 'onsen',
  'kusatsu-onsen': 'onsen:yubatake',
  'ikaho-onsen': 'onsen:steps',
  itsukushima: 'toriiSea',
  onomichi: 'port:slope',
  'soya-misaki': 'capeCliff:north',
  'kobe-ko': 'port:tower',
  'arima-onsen': 'onsen',
  'kinosaki-onsen': 'onsen:willow',
  kairakuen: 'garden:plum',
  kenrokuen: 'garden:lantern',
  kotohiragu: 'shrine:steps',
  ritsurin: 'garden:pine',
  zenigata: 'sandArt',
  'kirishima-jingu': 'shrine',
  'ibusuki-sunamushi': 'sandBath',
  'yokohama-chukagai': 'chinaGate',
  tsujunkyo: 'archBridge:water',
  'kurokawa-onsen': 'onsen:forest',
  sakitsu: 'church:sea',
  kinkaku: 'goldPavilion',
  kiyomizu: 'cliffStage',
  'ise-jingu': 'shrine:ise',
  kesennuma: 'port',
  'udo-jingu': 'shrine:cave',
  zenkoji: 'temple',
  karuizawa: 'highland:forest',
  meganebashi: 'archBridge:double',
  'goto-kyokai': 'church',
  'takada-yozakura': 'castle:night',
  taraibune: 'tubBoat',
  'beppu-onsen': 'onsen:hell',
  yufuin: 'onsen:mist',
  korakuen: 'garden',
  'seto-ohashi': 'bigBridge',
  'banpaku-koen': 'sunTower',
  okawachiyama: 'kilnVillage',
  'takeo-onsen': 'onsen:gate',
  'gaikaku-hosuiro': 'undergroundHall',
  enryakuji: 'mountainTemple',
  'izumo-taisha': 'shrine:shimenawa',
  'kinugawa-onsen': 'onsen:river',
  oyaishi: 'quarry',
  'iya-kazurabashi': 'vineBridge',
  kaminarimon: 'lanternGate',
  'tokyo-tower': 'tokyoTower',
  nageiredo: 'cliffStage:cave',
  'kaike-onsen': 'onsen:sea',
  koyasan: 'pagoda:red',
  yamadera: 'mountainTemple:rock',
  'ginzan-onsen': 'onsen:snow',
  'haguro-gojunoto': 'pagoda:wood',
  kintaikyo: 'archBridge:five',
  'tsunoshima-ohashi': 'bigBridge:emerald',
  rurikoji: 'pagoda:wood',
  motonosumi: 'toriiRow',
  saruhashi: 'archBridge:gorge',

  // ── しぜん（nature）
  denshogiku: 'flowers:yellow',
  takeshima: 'island',
  korankei: 'gorge:autumn',
  tazawako: 'lake:statue',
  'akita-inu': 'dog',
  chokaisan: 'mountain:snow',
  'tsugaru-kaikyo': 'strait',
  'towada-ko': 'lake:autumn',
  shirakami: 'forest:beech',
  oirase: 'gorge:stream',
  kujukurihama: 'beach:long',
  nokogiriyama: 'mountain:cliff',
  'oyama-senmaida': 'riceTerrace',
  ishizuchisan: 'mountain:rock',
  sadamisaki: 'lighthouse',
  'echizen-suisen': 'flowers:white',
  'katsuyama-kyoryu': 'dinosaur',
  mikatagoko: 'lake:five',
  hiraodai: 'karst',
  inawashiroko: 'lake:mountain',
  goshikinuma: 'pond',
  'miharu-takizakura': 'sakura:big',
  oze: 'wetland:boardwalk',
  tanigawadake: 'mountain:snow',
  'fukiware-no-taki': 'waterfall:wide',
  taishakukyo: 'gorge:arch',
  sandankyo: 'gorge',
  shiretoko: 'forest:sea',
  mashuko: 'lake:deep',
  'kushiro-shitsugen': 'wetland:river',
  ryuhyo: 'driftIce',
  asahidake: 'volcano:snow',
  'furano-lavender': 'flowers:purple',
  toyako: 'lake:island',
  'fukuroda-no-taki': 'waterfall:steps',
  kasumigaura: 'lake:sail',
  tsukubasan: 'mountain:twin',
  nemophila: 'flowers:blue',
  'shiroyone-senmaida': 'riceTerrace:sea',
  chirihama: 'beach:car',
  hakusan: 'mountain:snow',
  ryusendo: 'cave:lake',
  'iwate-san': 'mountain:snow',
  jodogahama: 'rockyCoast:white',
  hachimantai: 'highland',
  geibikei: 'gorge:boat',
  kitayamazaki: 'capeCliff',
  chichibugahama: 'mirrorBeach',
  yashima: 'mesa',
  kaimondake: 'mountain:sea',
  'sogi-no-taki': 'waterfall:wide',
  'izumi-tsuru': 'crane',
  sakurajima: 'volcano:sea',
  jomonsugi: 'bigCedar',
  owakudani: 'volcanicVent',
  enoshima: 'island:tower',
  tanzawa: 'mountain',
  katsurahama: 'beach',
  shimantogawa: 'river:bridge',
  murotomisaki: 'capeCliff',
  ashizurimisaki: 'lighthouse',
  ryugado: 'cave',
  niyodogawa: 'river:blue',
  asosan: 'volcano:caldera',
  'kikuchi-keikoku': 'gorge:stream',
  'amakusa-iruka': 'dolphin',
  amanohashidate: 'sandbar',
  onigajo: 'rockyCoast',
  'akame-48taki': 'waterfall',
  gozaishodake: 'mountain:ropeway',
  matsushima: 'islands:pine',
  'naruko-kyo': 'gorge:autumn',
  izunuma: 'wetland:geese',
  takachiho: 'gorge:waterfall',
  aoshima: 'rockyCoast:washboard',
  toimisaki: 'horse',
  'ebino-kogen': 'highland',
  kamikochi: 'river:alps',
  suwako: 'lake',
  'onsen-zaru': 'monkey',
  unzen: 'volcanicVent',
  kujukushima: 'islands',
  'shimabara-yusui': 'spring:carp',
  'goto-takahama': 'beach:emerald',
  onidake: 'mountain:grass',
  'nara-shika': 'deer',
  yoshinoyama: 'sakura:mountain',
  odaigahara: 'forest:mist',
  shinanogawa: 'river',
  'sasagawa-nagare': 'rockyCoast',
  oyashirazu: 'capeCliff:waves',
  'itoigawa-hisui': 'jade',
  myokosan: 'mountain:snow',
  hyoko: 'wetland:swan',
  'sado-toki': 'ibis',
  yabakei: 'gorge:autumn',
  kuju: 'mountain:range',
  hiruzen: 'highland:cow',
  manzamo: 'capeCliff:elephant',
  kourijima: 'island:bridge',
  kabirawan: 'beach:emerald',
  yanbaru: 'forest',
  hirakubozaki: 'lighthouse',
  'minoo-no-taki': 'waterfall:autumn',
  mutsugoro: 'mudskipper',
  nagatoro: 'riverBoat',
  biwako: 'lake:big',
  ibukiyama: 'mountain:grass',
  sanbesan: 'mountain:grass',
  rosokujima: 'rockyCoast:candle',
  fujisan: 'snowPeak',
  'miho-matsubara': 'sandbar:fuji',
  jogasaki: 'capeCliff:bridge',
  kawazuzakura: 'sakura:river',
  'kegon-no-taki': 'waterfall:tall',
  'nasu-kogen': 'highland',
  'naruto-uzushio': 'whirlpool',
  tsurugisan: 'mountain',
  'hiwasa-umigame': 'seaTurtle',
  takaosan: 'mountain:forest',
  okutamako: 'lake:dam',
  mitakesan: 'mountain:forest',
  miharayama: 'volcano',
  'oshima-tsubaki': 'flowers:red',
  'tottori-sakyu': 'dunes',
  daisen: 'mountain:snow',
  uradome: 'rockyCoast',
  tateyama: 'snowPeak:wall',
  'kurobe-kyokoku': 'gorge:train',
  shomyodaki: 'waterfall:tall',
  'tonami-tulip': 'flowers:tulip',
  'nachi-no-taki': 'waterfall:pagoda',
  shirarahama: 'beach:white',
  shionomisaki: 'lighthouse',
  zao: 'icyTrees',
  mogamigawa: 'riverBoat',
  akiyoshidai: 'karst',
  fujigoko: 'snowPeak:lake',
  'oshino-hakkai': 'spring:fuji',
  shosenkyo: 'gorge',
  kitadake: 'mountain:snow',
  yatsugatake: 'mountain:range',

  // ── まつり（festival）
  namahage: 'namahageMask',
  'kanto-matsuri': 'kanto',
  'omagari-hanabi': 'fireworks',
  nebuta: 'nebutaFloat',
  'soma-nomaoi': 'horseSamurai',
  'gujo-odori': 'dance:yukata',
  'yuki-matsuri': 'snowStatue',
  'kiriko-matsuri': 'kiriko',
  yosakoi: 'dance:naruko',
  'yamaga-toro': 'lanternCrown',
  'sendai-tanabata': 'tanabata',
  'nagaoka-hanabi': 'fireworks:river',
  eisa: 'taikoDance',
  'kishiwada-danjiri': 'danjiri',
  'karatsu-kunchi': 'festivalFloat:red',
  'chichibu-yomatsuri': 'festivalFloat:night',
  'nagahama-hikiyama': 'festivalFloat',
  'iwami-kagura': 'kagura',
  'hamamatsu-tako': 'kite',
  'awa-odori': 'dance:awa',

  // ── れきし（history）
  'nagoya-jo': 'castle:gold',
  'inuyama-jo': 'castle:river',
  'sannai-maruyama': 'pitHouse:tower',
  sawara: 'oldTown:canal',
  uchiko: 'oldTown',
  'besshi-dozan': 'mine:copper',
  'maruoka-jo': 'castle:small',
  akizuki: 'oldTown:sakura',
  shirakawago: 'thatched:snow',
  takayama: 'oldTown',
  'nagaragawa-ukai': 'ukai',
  magomejuku: 'oldTown:slope',
  'tomioka-seishijo': 'brickFactory',
  tomonoura: 'fishingVillage:lantern',
  takehara: 'oldTown',
  goryokaku: 'starFort',
  upopoy: 'ainu',
  'himeji-jo': 'castle:white',
  'takeda-jo': 'castleRuins:clouds',
  'awaji-ningyo': 'puppet',
  chusonji: 'goldPavilion:hall',
  tono: 'kappa',
  'kamakura-daibutsu': 'daibutsu',
  'kumamoto-jo': 'castle:black',
  'ine-funaya': 'fishingVillage:boathouse',
  byodoin: 'temple:phoenix',
  'miyama-kayabuki': 'thatched',
  'iga-ninja': 'ninja',
  'sendai-jo': 'castleRuins:crescent',
  obi: 'oldTown',
  'matsumoto-jo': 'castle:black',
  tsumago: 'oldTown:slope',
  hirado: 'port:dutch',
  'todaiji-daibutsu': 'daibutsu:hall',
  horyuji: 'pagoda:wood',
  ishibutai: 'stoneTomb',
  'sado-kinzan': 'mine:gold',
  'usuki-sekibutsu': 'stoneBuddha',
  kunisaki: 'stoneBuddha:forest',
  kurashiki: 'oldTown:canal',
  'bitchu-matsuyama-jo': 'castleRuins:clouds',
  shurijo: 'castleRed',
  'sefa-utaki': 'sacredRock',
  'osaka-jo': 'castle:gold',
  'daisen-kofun': 'kofun',
  yoshinogari: 'pitHouse:fence',
  kawagoe: 'oldTown:bell',
  'sakitama-kofun': 'kofun',
  'hikone-jo': 'castle:white',
  omihachiman: 'oldTown:canal',
  'matsue-jo': 'castle:black',
  'iwami-ginzan': 'mine:silver',
  tsuwano: 'oldTown:carp',
  'toro-iseki': 'pitHouse',
  'nikko-toshogu': 'ornateGate',
  'ashikaga-gakko': 'school',
  udatsu: 'oldTown',
  'kurayoshi-shirakabe': 'warehouse:white',
  gokayama: 'thatched:snow',
  'kumano-kodo': 'stonePath',
  'wakayama-jo': 'castle:white',
  'sankyo-soko': 'warehouse:zelkova',
  hagi: 'oldTown:wall',
};

/** 名所の 場面（無ければ null）。'key:v' を わける */
export function motifScene(motif: Pick<Motif, 'id'>): { key: SceneKey; v?: string } | null {
  const s = MOTIF_SCENES[motif.id];
  if (!s) return null;
  const [key, v] = s.split(':') as [SceneKey, string | undefined];
  return key in SCENES ? { key, v } : null;
}

const seedOf = (s: string): number => [...s].reduce((a, ch) => (a * 31 + ch.charCodeAt(0)) % 997, 7);

/** 名所の絵（32×32、わく つき）。場面の 無い 名所は null（カットインは 種類の アイコンに なる） */
export function motifArtGrid(areaId: string, motif: Pick<Motif, 'id'>): Grid | null {
  const sc = motifScene(motif);
  if (!sc) return null;
  const g = makeGrid(MA, MA);
  SCENES[sc.key](g, { v: sc.v, seed: seedOf(`${areaId}.${motif.id}`) });
  frame(g);
  return g;
}

const urls = new Map<string, string>();

/** カットインの <img> 用（data URL。名所ごとに 1 回だけ 作る） */
export function motifArtUrl(areaId: string, motif: Pick<Motif, 'id'>): string | undefined {
  const asset = existingAssetUrl(`motifs/${areaId}/${motif.id}.png`);
  if (asset) return asset;
  const k = `${areaId}.${motif.id}`;
  let url = urls.get(k);
  if (url === undefined) {
    const g = motifArtGrid(areaId, motif);
    if (!g) return undefined;
    url = toCanvas(g).toDataURL();
    urls.set(k, url);
  }
  return url;
}
