/** 愛知県の モンスター（手描き。docs/06 §4・§6.3〜6.5 の 規格）。下書きは 図形で かいて 1 ドットずつ 手で なおした */
import { NQ } from '../palette';
import type { MonsterDesign } from './design';
import { BEARD_FACE, HELMET, lord } from './lastbosses';

/** ハッチョン：八丁味噌の 木おけ。ふたの 上に 石を 山もりに つみ、たがの 間に 顔（ツチ） */
const hatchon: MonsterDesign = {
  size: 32,
  colors: {
    S: NQ.sand,
    T: NQ.tan,
    B: NQ.brown,
    K: NQ.bark,
    g: NQ.gray,
    s: NQ.silver,
    l: NQ.slate,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.sand]: NQ.tan, [NQ.gray]: NQ.slate },
  layers: [
    {
      rows: [
        '................................',
        '...........gg..gg..gg...........',
        '..........gsggosggosgg..........',
        '..........ggggogggoggg..........',
        '........gsgggsoggsoggsgg........',
        '........ggggogggogggoggg........',
        '.......gggggogggogglogggg.......',
        '......gsggosggosggoslgosgg......',
        '......ggggogggogggogggoggg......',
        '....gsgggsoggsoggsoggsoggsgg....',
        '....ggggogggogggogggogggoggg....',
        '....ggggogggogggogggogggoggg....',
        '.....SSTSSTSSTSSTSSTSSTSSTS.....',
        '.....SSTSSTSSTSSTSSTSSTSSTS.....',
        '.....BBBBBBBBBBBBBBBBBBBBBB.....',
        '.....SSTSSTSSTSSTSSTSSTSSTS.....',
        '.....SSTSSSSSSSSSSSSSSTSSTS.....',
        '.....SSTSSSWWSSSSSSWWSTSST......',
        '......STSSSWoSSSSSSoWSTSST......',
        '......STSSSWoSSSSSSoWSTSST......',
        '......STSpSSSSSSSSSSSSpSST......',
        '......STSSSSSSoSSoSSSSTSST......',
        '......STSSTSSTSooSSTSSTSST......',
        '......STSSTSSTSSTSSTSSTSST......',
        '......STSSTSSTSSTSSTSSTSST......',
        '......BBBBBBBBBBBBBBBBBBBB......',
        '......STSSTSSTSSTSSTSSTSST......',
        '......STSSTSSTSSTSSTSSTSST......',
        '................................',
        '.........KKK........KKK.........',
        '................................',
        '................................',
      ],
    },
  ],
};

/** ミソヤグラ（ハッチョンの しんか）：木おけを 2 だん かさねた やぐら。石の 屋根、みそを まぜる 大きな かい（ツチ） */
const misoYagura: MonsterDesign = {
  size: 32,
  colors: {
    S: NQ.sand,
    T: NQ.tan,
    B: NQ.brown,
    K: NQ.bark,
    g: NQ.gray,
    s: NQ.silver,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.sand]: NQ.tan, [NQ.gray]: NQ.slate },
  layers: [
    {
      rows: [
        '................................',
        '............gsggosgg.....BBBBB..',
        '............ggggoggg.....BTTTB..',
        '..........gsggggoggggg...BTTTB..',
        '..........ggggogggoggg...BTTTB..',
        '.........gggggogggogggg..BBBBB..',
        '........gsggosggosggosgg...T....',
        '........ggggogggogggoggg...T....',
        '........SggSoggSoggToggS...T....',
        '........BBBBBBBBBBBBBBBB...B....',
        '........SSTSSTSSTSSTSSTS...T....',
        '.........STooSSSSSSooST....T....',
        '.........STSWoSSSSoWSST....T....',
        '.........STSWoSSSSoWSST....T....',
        '.........STSWoSSSSoWSST....T....',
        '.........SpSSSSSSSSSSpT....T....',
        '.........STSSSooooSSSST....T....',
        '.........BBBBBBBBBBBBBB....B....',
        '....TSSTSSTSSTSSTSSTSSTSSTSS....',
        '....TSSTSSTSSTSSTSSTSSTSSTSS....',
        '....BBBBBBBBBBBBBBBBBBBBBBBB....',
        '.BB.TSSTSSTSSTSSTSSTSSTSSBBB....',
        '.BBB.SSTSSTSSTSSTSSTSSTSSBBT....',
        '..BB.SSTSSTSSTSSTSSTSSTSSTST....',
        '.....SSTSSTSSTSSTSSTSSTSSTST....',
        '.....SSTSSTSSTSSTSSTSSTSSTST....',
        '.....SSTSSTSSTSSTSSTSSTSSTST....',
        '.....BBBBBBBBBBBBBBBBBBBBBBB....',
        '.....SSTSSTSSTSSTSSTSSTSSTS.....',
        '................................',
        '........KKK..........KKK........',
        '................................',
      ],
    },
  ],
};

/** デンキクン：夜に 光る 電照菊。黄色い 花びらの まん中に 顔、頭の 上に 金の わっか、光の つぶ（ヒカリ） */
const denkikun: MonsterDesign = {
  size: 32,
  colors: {
    Y: NQ.yellow,
    C: NQ.cream,
    O: NQ.orange,
    G: NQ.gold,
    L: NQ.leaf,
    g: NQ.green,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.orange]: NQ.amber, [NQ.gold]: NQ.ochre, [NQ.leaf]: NQ.green },
  layers: [
    {
      rows: [
        '................................',
        '.............GGGGGG.............',
        '............G......G............',
        '..C.............................',
        '.CWC..........CCCC..............',
        '..C........CCCCCCCCCC...........',
        '.........CCCYYYYYYYYCCC.........',
        '........CCYYYYYYYYYYYYCC........',
        '.......CCYYYYYYYYYYYYYYCC.......',
        '......CCYYYYYYYYYYYYYYYYCC......',
        '......CCYYYYYCOOOOOYYYYYCC......',
        '.....CCYYYYYCOOOOOOOYYYYYCC.....',
        '......CYYYYOWWOOOOWWOYYYYC......',
        '.....CCYYYYOWoOOOOoWOYYYYCC.....',
        '.....CCYYYOOWoOOOOoWOOYYYCC.....',
        '.....CCYYYYOOOOOOOOOOYYYYCC.....',
        '......CYYYYpOOoOOoOOpYYYYC......',
        '.....CCYYYYYOOOooOOOYYYYYCC.....',
        '......CCYYYYYOOOOOOYYYYYCC......',
        '......CCYYYYYYYYYYYYYYYYCC......',
        '.......CCYYYYYYYYYYYYYYCC.......',
        '........CCYYYYYYYYYYYYCC........',
        '......LLLCCCYYYYYYYYCCCLLL..C...',
        '.......LggLCCCCCCCCCCLggL..CWC..',
        '.......LLLgggLCCCCLgggLLL...C...',
        '........LLLLLggggggLLLLL........',
        '..........LLL..gg..LLL..........',
        '...............gg...............',
        '...............gg...............',
        '...............gg...............',
        '................................',
        '................................',
      ],
    },
  ],
};

/** デンコウギク（デンキクンの しんか）：2 じゅうの 花びら（外は 黄色、内は 金）、いなずまの 葉、光の つぶ（ヒカリ） */
const denkouGiku: MonsterDesign = {
  size: 32,
  colors: {
    Y: NQ.yellow,
    C: NQ.cream,
    O: NQ.orange,
    G: NQ.gold,
    L: NQ.leaf,
    g: NQ.green,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.orange]: NQ.amber, [NQ.gold]: NQ.ochre, [NQ.leaf]: NQ.green },
  layers: [
    {
      rows: [
        '................................',
        '..C..........................C..',
        '.CWC.......CCCCCCCCCC.......CWC.',
        '..C.......CCCCYYYYCCCC.......C..',
        '........CCCYYYYYYYYYYCCC........',
        '.......CCYYYYYYYYYYYYYYCC.......',
        '.....CCCYYYYGGGGGGGGYYYYCCC.....',
        '.....CCYYYGGGGGGGGGGGGYYYCC.....',
        '.....CYYYGGCGGGGGGGGGGGYYYC.....',
        '....CYYYYGCGGGOOOOGGGGGYYYYC....',
        '...CCYYYGGGGOOOOOOOOGGGGYYYCC...',
        '...CCYYGGGGooOOOOOOooGGGGYYCC...',
        '...CCYYGGGGOWoOOOOoWOGGGGYYCC...',
        '...CYYYGGGGOWoOOOOoWOGGGGYYYC...',
        '...CYYYGGGGOWoOOOOoWOGGGGYYYC...',
        '...CCYYGGGGOOOOOOOOOOGGGGYYCC...',
        '...CCYYGGGGpOoOOOOoOpGGGGYYCC...',
        '...CCYYYGGGGOOooooOOGGGGYYYCC...',
        '....CYYYYGGGGGOOOOGGGGGYYYYC....',
        '.....CYYYGGGGGGGGGGGGGGYYYC.....',
        '.....CCYYYGGGGGGGGGGGGYYYCC.....',
        '.....CCCYYYYGGGGGGGGYYYYCCC.....',
        '.......CCYYYYYYYYYYYYYYCC.......',
        '........CCCYYYYYYYYYYCCC....C...',
        '.........LCCCCYYYYCCCCL....CWC..',
        '..........LCCCCCCCCCCL......C...',
        '............L..gg..L............',
        '...............gg...............',
        '...............gg...............',
        '...............gg...............',
        '................................',
        '................................',
      ],
    },
  ],
};

/** テバサッキー：こんがり 手羽先の つばさで とぶ 子。ごまと こしょうの つぶ、赤い とさか、黄色い 足（カゼ） */
const tebasakky: MonsterDesign = {
  size: 32,
  colors: {
    O: NQ.orange,
    A: NQ.amber,
    C: NQ.cream,
    K: NQ.bark,
    R: NQ.red,
    Y: NQ.yellow,
    M: NQ.mint,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.orange]: NQ.amber, [NQ.amber]: NQ.brown },
  layers: [
    {
      rows: [
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '..AO........................OA..',
        '..AAO......................OAA..',
        '.AAAC......................CAAA.',
        '..AAAOO..................OOAAA..',
        '...AACO..................OCAA...',
        '...AAAAO................OAAAA...',
        '....AAKO.......RR.......OKAA....',
        '....AAACO.....RRRR.....OCAAA....',
        '.....AAAAO..OOOOOOOO..OAAAA.....',
        '......AAAAOOAOOOOOOOOOAAAA......',
        '......AACAOAOOOOOOOOOOACAA......',
        '.......AAOOOOOOOOOOOOOOAA.......',
        '........OOOOWWOOOOWWOOOO........',
        '........OOOOWoOOOOoWOOOO........',
        '........OOOOWoOOOOoWOOOO........',
        '........OOOOOOOYYOOOOOOO........',
        '........OOpOOOOYYOOOOpOO........',
        '..MM....OOOOOOOOOOOOOOOO....MM..',
        '.M.......OOOOOOOOOOOOOO.......M.',
        '..........OOOOOOOOOOOO..........',
        '...........OOOOOOOOOO...........',
        '............OOOOOOOO............',
        '............Y......Y............',
        '...........YYY....YYY...........',
        '................................',
        '................................',
        '................................',
      ],
    },
  ],
};

/** コケコッコーチン（テバサッキーの しんか）：名古屋コーチンの おんどり。大きな とさか、手羽先の つばさを ひろげる（カゼ） */
const kokekokkochin: MonsterDesign = {
  size: 32,
  colors: {
    S: NQ.sand,
    E: NQ.beige,
    A: NQ.amber,
    O: NQ.orange,
    C: NQ.cream,
    K: NQ.bark,
    R: NQ.red,
    Y: NQ.yellow,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.sand]: NQ.tan },
  layers: [
    {
      rows: [
        '................................',
        '...............RR...............',
        '..............RRRR..............',
        '.............RRRRRR.............',
        '..OA.........RRRRRR.........AO..',
        '.AAO........................OAA.',
        '.AAOA........SSSSSS........AOAA.',
        '.AACOA......SSSSSSSS......AOCAA.',
        '.AAAOO.....ooSSSSSSoo.....OOAAA.',
        '..AAAAO....SWoSSSSoWS....OAAAA..',
        '..AAACO....SWoSSSSoWS....OCAAA..',
        '...ACAAO...SWoSSSSoWS...OAACA...',
        '...AAAAAO..pSSSYYSSSp..OAAKKA...',
        '....AAAAO...SSSYYSSS...OAKKK....',
        '....AAACAOOSSSSRRSSSSOOAKKAA....',
        '.....AAAAASSSSSRRSSSSSAAAAA.....',
        '......AAASSESSSSSSSSSSSAAA......',
        '.......ASSESSSSSSSSSSSSSA.......',
        '........SSSSSEEEEEESSSSS........',
        '........SSSSEEEEEEEESSSS........',
        '........SSSSEEEEEEEESSSS........',
        '........SSSSEEEEEEEESSSS........',
        '........SSSSEEEEEEEESSSS........',
        '........SSSSEEEEEEEESSSS........',
        '.........SSSEEEEEEEESSS.........',
        '..........SSSEEEEEESSS..........',
        '...........SSSSSSSSSS...........',
        '............YSSSSSSY............',
        '............Y......Y............',
        '...........YYY....YYY...........',
        '................................',
        '................................',
      ],
    },
  ],
};

const shiborin: MonsterDesign = {
  size: 32,
  colors: {
    I: NQ.indigo,
    N: NQ.navy,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.indigo]: NQ.navy },
  layers: [
    {
      rows: [
        '',
        '',
        '',
        '',
        '',
        '..............IIIII',
        '...........IIIIIWIIIII',
        '........IIIIIIIWWWIIIIIII',
        '....IIIIIIIIIIWWIWWIIIIIIIIII',
        '.....IIIIIIIIIIWWWIIIIIIIIII',
        '.....IIIIIWIIIIIWIIIIIWIIIII',
        '.....IIIIWWWIIIIIIIIIWWWIIII',
        '.....IIIWWIWWIIIIIIIWWIWWIII',
        '.....IIIIWWWIIIIIIIIIWWWIIII',
        '...NNIIIIIWIIIIIIIIIIIWIIIINN',
        '...NNIIIIIIIIIIIIIIIIIIIIIINN',
        '...NNIIIIIIIIIIIIIIIIIIIIIINN',
        '...NNIIIIIIIoWIIIIWoIIIIIIINN',
        '...NNIIIIIIIoWIIIIWoIIIIIIINN',
        '...NNIIIIIIIWWIIIIWWIIIIIIINN',
        '...NNIIIIpIIIIIIIIIIIIpIIIINN',
        '.....IIIIIIIIIIoooIIIIIIIIII',
        '.....IIIIIWIIIIIIIIIIIWIIIII',
        '.....IIIIWWWIIIIIIIIIWWWIIII',
        '.....IIIWWIWWIIIWIIIWWIWWIII',
        '.....IIIIWWWIIIWWWIIIWWWIIII',
        '.....IIIIIWIIIWWIWWIIIWIIIII',
        '.....IIIIIIIIIIWWWIIIIIIIIII',
        '...........IIIIIWIIIII',
        '............NNNNNNNNN',
        '............NNNNNNNNN',
        '',
      ],
    },
  ],
};

const arimatsuZome: MonsterDesign = {
  size: 32,
  colors: {
    I: NQ.indigo,
    N: NQ.navy,
    W: NQ.white,
    A: NQ.azure,
  },
  rim: { [NQ.indigo]: NQ.navy, [NQ.azure]: NQ.blue },
  layers: [
    {
      rows: [
        '',
        '',
        '',
        '',
        '.............IIIIIII',
        '..........IIIIIIIIIIIII',
        '......WIIIIIWIIIIIWIIIIIWI',
        '...IIWWWIIIWWWIIIWWWIIIWWWIII',
        '...IWWIWWIWWIWWIWWIWWIWWIWWII',
        '...IIWWWIIIWWWIIIWWWIIIWWWIII',
        '.AAAIIWIIIIIWIIIIIWIIIIIWIIIAAA',
        '.AAAIIIIIIIIIIIIIIIIIIIIIIIIAAA',
        '.AAAIIWIIIIIWIIIIIWIIIIIWIIIAAA',
        '.AAAIWWWIIIWWWIIIWWWIIIWWWIIAAA',
        '.AAAWWIWWIoooooIWoooooWWIWWIAAA',
        '.AAAIWWWIIIWWWIIIWWWWIIWWWIIAAA',
        '.AAAIIWIIIIooWIIIIWooIIIWIIIAAA',
        '.AAAIIIIIIIooWIIIIWooIIIIIIIAAA',
        '.AAAIIWIIIIooWIIIIWooIIIWIIIAAA',
        '.AAAIWWWIIIWWWIIIWWWIIIWWWIIAAA',
        '.AAAWWIWWIWWIWWIWWIWWIWWIWWIAAA',
        '.AAAIWWWIIIWWWooooWWIIIWWWIIAAA',
        '.AAAIIWIIIIIWIIIIIWIIIIIWIIIAAA',
        '...IIIIIIIIIIIIIIIIIIIIIIIIII',
        '...IIIWIIIIIWIIIIIWIIIIIWIIII',
        '...IIWWWIIIWWWIIIWWWIIIWWWIII',
        '...IWWIWWIWWIWWIWWIWWIWWIWWIII',
        '.....WWWIIIWWWIIIWWWIIIWWW',
        '......W...IIWIIIIIWIIII.W',
        '.............IIIIIII',
        '...........NNNNNNNNNNN',
        '',
      ],
    },
  ],
};

const tokonameNeko: MonsterDesign = {
  size: 40,
  colors: {
    T: NQ.brick,
    S: NQ.vermilion,
    P: NQ.blush,
    W: NQ.white,
    R: NQ.red,
    G: NQ.gold,
    Q: NQ.ochre,
  },
  rim: { [NQ.brick]: NQ.ink, [NQ.vermilion]: NQ.brick },
  rimDepth: 2,
  layers: [
    {
      rows: [
        '',
        '',
        '................G.G.G.G.G',
        '................GGGGGGGGG.......T',
        '.........T......GGGRRGGGG......T',
        '.........TT.....GGGRRGGGG.....TT',
        '.........TTT....QQQQQQQQQ....TTP',
        '.........TPTTT.............TTTPT',
        '.........TPPTTT.....T.....TTTPPT',
        '..........PPPTTTTTTTTTTTTTTTPPP',
        '..........PPPPPTTTTTTTTTTTPPPPP',
        '..........TTTTTTTTTTTTTTTTTTTTT',
        '..........TToooooooTTToooooooTT',
        '...........ToooooooTTToooooooT',
        '...........TTWWWWWTTTTTWWWWWTT',
        '...........TTooWWWTTTTTWWWooTT',
        '..........TTTooWWWTTTTTWWWooTTT',
        '...........TTooWWWTTTTTWWWooTT',
        '...........TTTTTTTTTTTTTTTTTTT',
        '......TTTWWWWWTTTTToooTTTTTWWWWWW',
        '......TTTTT.TTTTTToTTToTTTTTT',
        '......TTTTT.TTTTTTTTTTTTTTTTT',
        '......TTTTTTTSTTTTTTTTTTTTTTTT',
        '......TTTTTTSSSSTTTTTTTTTTTTTTT',
        '......TTTTTRRRRRRRRRRRRRRRRRRRT',
        '......TTTTTRRRRRRRRRGRRRRRRRRRTT',
        '......TTTTTRRRRRRRRGGGRRRRRRRRTT',
        '.........TTSSSSSSSGGGGGTTTTTTTTT',
        '........TTTSSSSSSSSGGGTTTTTTGGGGGGG',
        '.........TTTSSSSSSSSGTTTTTTTGGGGGGG',
        '.........TTTTSSSSSSSTTTTTTTTGQQQQQG',
        '.........TTTTTTTSTTTTTTTTTTTGQQQQQG',
        '..........TTTTTTTTTTTTTTTTTTGGGGGGG',
        '..........TTTTTTTTTTTTTTTTTTGGGGGGG',
        '...........TTTTTTTTTTTTTTTTTTT',
        '............TTTTTTTTTTTTTTTTT',
        '..........TTTTTTTTTTTTTTTTTTTTT',
        '..........TTTTTTTTTTTTTTTTTTTTT',
        '..........TTTTTTTT..T..TTTTTTTT',
        '',
      ],
    },
  ],
};

const tokonameNekoField: MonsterDesign = {
  size: 32,
  colors: {
    T: NQ.brick,
    S: NQ.vermilion,
    P: NQ.blush,
    W: NQ.white,
    R: NQ.red,
    G: NQ.gold,
    Q: NQ.ochre,
  },
  rim: { [NQ.brick]: NQ.ink },
  rimDepth: 1,
  layers: [
    {
      rows: [
        '',
        '..............G.G.G',
        '.............GGGGGGG......T',
        '.......T.....GGRRGGG.....T',
        '.......TT....GGRRGGG....TT',
        '.......TTTT..QQQQQQQ..TTTP',
        '.......TPTTT.........TTTPT',
        '........PPTTTT..T..TTTTPP',
        '........PPPPTTTTTTTTTPPPP',
        '........TT.TTTTTTTTTTT.TT',
        '..........oooooTTTooooo',
        '.........TWWWWWTTTWWWWWT',
        '.........TooWWWTTTWWWooT',
        '........TTooWWWTTTWWWooTT',
        '.........TooWWWTTTWWWooT',
        '.....TTWWWWTTTToooTTTTWWWW',
        '.....TTTT.TTTToTTToTTTT',
        '.....TTTTTTTTTTTTTTTTTTT',
        '.....TTTTTSSTTTTTTTTTTTTT',
        '.....TTTTRRRRRRRRRRRRRRRTT',
        '.....TTTTRRRRRRRGRRRRRRRTT',
        '.....TTTTRRRRRRGGGRRRRRRTT',
        '......TTTSSSSSGGGGGTTTGGGGGG',
        '.......TTSSSSSSGGGTTTTGGGGGG',
        '.......TTTSSSSSSGTTTTTGQQQQG',
        '.......TTTTTTSTTTTTTTTGQQQQG',
        '........TTTTTTTTTTTTTTGGGGGG',
        '.........TTTTTTTTTTTTTTT',
        '..........TTTTTTTTTTTTT',
        '........TTTTTTTTTTTTTTTTT',
        '........TTTTTTT.T.TTTTTTT',
        '',
      ],
    },
  ],
};

const kinshachiOu: MonsterDesign = {
  size: 48,
  colors: {
    G: NQ.gold,
    Y: NQ.yellow,
    Q: NQ.ochre,
    C: NQ.cream,
    W: NQ.white,
    R: NQ.red,
    T: NQ.teal,
    A: NQ.sky,
  },
  rim: { [NQ.gold]: NQ.ochre, [NQ.yellow]: NQ.ochre, [NQ.teal]: NQ.navy },
  rimDepth: 2,
  layers: [
    {
      rows: [
        '',
        '',
        '',
        '....................G.G.G.G.G',
        '....................GGGGGGGGG',
        '....................GGGRRGGGG',
        '....................GGGRRGGGG',
        '....................QQQQQQQQQ',
        '........................G',
        '...................GGGGGGGGGGG',
        '.................GGGGGGGGGGGGGGG',
        '................GGGGYGGGGGGGGGGGG',
        '...............GYYYYYYYYYGGGGGGGGG',
        '..............GYYYYYYYYYYYGGGGGGGGG',
        '.............GYYYYYYYYYYYYYGGGGGGGGG',
        '.............ooooooooooYYYoooooooooo',
        '............GooooooooooYYYooooooooooG.........G',
        '...G........GGYWWWWWWYYYYYYGWWWWWWGGG........G',
        '...GGG......GGYoooWWWYYYYYYGWWWoooGGG......GGG',
        '...GGGG.....GGGoooWWWYYYYYGGWWWoooGGG.....GGGG',
        '...QGGGGG..GGGGoooWWWYYYYGGGWWWoooGGGG..GGGGGQ',
        '...GQQGGGGG.GGGoooWWWGGGGGGGWWWoooGGG.GGGGGQQG',
        '...GGGQQGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGQQGGG',
        '...GGGGGQQGGGGGGGGGGGGGGGGGGGGGGGGGGGGGQQGGGGG',
        '...GGGGGGGQGGGGGGGGGGGGGGGGGGGGGGGGGGGQGGGGGGG',
        '...GGGGGGGGG.GGGGGGGGGGGGGGGGGGGGGGG.GGGGGGGGG',
        '...GGGGGGGGG.GGGGGoWooWooWooWooGGGGG.GGGGGGGGG',
        '.......GGGGG..GGGGoWooWooWooWooGGGG..GGGGG',
        '...............GGGoooooooooooooGGG',
        '................GGoooooooooooooGG',
        '........G........GGGGGGGGGGGGGGG',
        '........G..........GGGGGGGGGGG..........G',
        '........G...............G...............G',
        '........GG.............GGG.............GG',
        '.......GGG............GGGGG............GGG',
        '.......GGG..........GGGGGGGGG..........GGG',
        '......QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ',
        '.......GGGG......GGGGGGGGGGGGGGG......GGGG',
        '......GGGGGG....GGGGGGGGGGGGGGGGG....GGGGGG',
        '......GGGGGG..GGGGGGGGGGGGGGGGGGGGG..GGGGGG',
        '..AAAAAAAQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQAAAAAAA',
        '..AAAAAAAGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAAAAAAA',
        '..AAAAAAAGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAAAAAAA',
        '.....GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        '..............TTTTTTTTTTTTTTTTTTTTT',
        '......TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
        '......TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
        '',
      ],
    },
  ],
};

const kinshachiOuP0: MonsterDesign = {
  size: 48,
  colors: {
    G: NQ.gold,
    Y: NQ.yellow,
    Q: NQ.ochre,
    C: NQ.cream,
    W: NQ.white,
    R: NQ.red,
    T: NQ.teal,
    A: NQ.sky,
  },
  rim: { [NQ.gold]: NQ.ochre, [NQ.yellow]: NQ.cream, [NQ.teal]: NQ.navy },
  rimDepth: 2,
  layers: [
    {
      rows: [
        '',
        '',
        '',
        '....................G.G.G.G.G',
        '....................GGGGGGGGG',
        '....................GGGRRGGGG',
        '....................GGGRRGGGG',
        '....................QQQQQQQQQ',
        '........................Y',
        '...................YYYYYYYYYYY',
        '.................YYYYYYYYYYYYYYY',
        '................YYYYCYYYYYYYYYYYY',
        '...............YCCCCCCCCCYYYYYYYYY',
        '.....C........YCCCCCCCCCCCYYYYYYYYY.......C',
        '....CCC......YCCCCCCCCCCCCCYYYYYYYYY.....CCC',
        '.....C.......ooooooooooCCCoooooooooo......C',
        '............YooooooooooCCCooooooooooY.........Y',
        '...Y........YYCWWWWWWCCCCCCYWWWWWWYYY........Y',
        '...YYY......YYCoooWWWCCCCCCYWWWoooYYY......YYY',
        '...YYYY.....YYYoooWWWCCCCCYYWWWoooYYY.....YYYY',
        '...QYYYYY..YYYYoooWWWCCCCYYYWWWoooYYYY..YYYYYQ',
        '...YQQYYYYY.YYYoooWWWYYYYYYYWWWoooYYY.YYYYYQQY',
        '...YYYQQYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYQQYYY',
        '...YYYYYQQYYYYYYYYYYYYYYYYYYYYYYYYYYYYYQQYYYYY',
        '...YYYYYYYQYYYYYYYYYYYYYYYYYYYYYYYYYYYQYYYYYYY',
        '...YYYYYYYYY.YYYYYYYYYYYYYYYYYYYYYYY.YYYYYYYYY',
        '...YYYYYYYYY.YYYYYoWooWooWooWooYYYYY.YYYYYYYYY',
        '.......YYYYY..YYYYoWooWooWooWooYYYY..YYYYY',
        '...............YYYoooooooooooooYYY',
        '.......C........YYoooooooooooooYY.......C',
        '......CCC........YYYYYYYYYYYYYYY.......CCC',
        '.......CY..........YYYYYYYYYYY..........C',
        '........Y...............Y...............Y',
        '........YY.............YYY.............YY',
        '.......YYY............YYYYY............YYY',
        '.......YYY..........YYYYYYYYY..........YYY',
        '......QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ',
        '.......YYYY......YYYYYYYYYYYYYYY......YYYY',
        '......YYYYYY....YYYYYYYYYYYYYYYYY....YYYYYY',
        '......YYYYYY..YYYYYYYYYYYYYYYYYYYYY..YYYYYY',
        '......QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ',
        '.....YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY',
        '.....YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY',
        '.....YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY',
        '..............TTTTTTTTTTTTTTTTTTTTT',
        '......TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
        '......TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
        '',
      ],
    },
  ],
};

const odaNobunaga = lord(
  [
    '.......................G',
    '.....................GGG',
    '....................GGGR',
    '....................GGRR',
    '...................GGRRR',
    '....................GGRR',
    '....................GGGG',
    '....................NGGG',
    ...HELMET,
    ...BEARD_FACE,
  ],
  {
    N: NQ.night,
    L: NQ.slate,
    G: NQ.gold,
    Y: NQ.cream,
    R: NQ.red,
    K: NQ.gray,
    S: NQ.silver,
    T: NQ.night,
    H: NQ.slate,
    C: NQ.brick,
    M: NQ.hairBlack,
  },
  { [NQ.gray]: NQ.slate, [NQ.silver]: NQ.gray, [NQ.brick]: NQ.ink },
);

export const AICHI: Readonly<Record<string, MonsterDesign>> = {
  'aichi-hatchon': hatchon,
  'aichi-miso-yagura': misoYagura,
  'aichi-denkikun': denkikun,
  'aichi-denkou-giku': denkouGiku,
  'aichi-tebasakky': tebasakky,
  'aichi-kokekokkochin': kokekokkochin,
  'aichi-shiborin': shiborin,
  'aichi-arimatsu-zome': arimatsuZome,
  'aichi-midboss-tokoname-neko': tokonameNeko,
  'aichi-midboss-tokoname-neko.field': tokonameNekoField,
  'aichi-boss-kinshachi-ou': kinshachiOu,
  'aichi-boss-kinshachi-ou.p0': kinshachiOuP0,
  'aichi-lastboss-oda-nobunaga': odaNobunaga,
};
