/** 愛媛県の モンスター（手描き。docs/06 §4・§6.3〜6.5 の 規格） */
import { NQ } from '../palette';
import type { MonsterDesign } from './design';
import { BEARD_FACE, HELMET, lord } from './lastbosses';

/** コミカン：だんだん畑の みかん。まるい だいだい色の 実に、みどりの ヘタと 葉っぱ（モリ） */
const komikan: MonsterDesign = {
  size: 32,
  colors: {
    O: NQ.orange,
    A: NQ.apricot,
    Q: NQ.amber,
    L: NQ.leaf,
    G: NQ.green,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.orange]: NQ.amber, [NQ.leaf]: NQ.green },
  layers: [
    // 葉っぱ（左上）
    { x: 5, y: 4, rows: ['....LL', '..LLLLL', '.LLGLLL', '..LLLLLLL'] },
    // ヘタ
    { mirror: true, y: 7, rows: ['..............GL', '.............LLL'] },
    {
      mirror: true,
      rows: [
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '............OOOO',
        '..........OOOOOO',
        '.........OOOOOOO',
        '........OOOOOOOO',
        '.......OOOOOOOOO',
        '.......OOOOOOOOO',
        '......OOOOOOOOOO',
        '......OOOOWWOOOO',
        '......OOOOWoOOOO',
        '......OOOOWoOOOO',
        '......OOppOOOOoO',
        '......OOOOOOOOOo',
        '.......OOOOOOOOO',
        '.......OOOOOOOOO',
        '........OOOOOOOO',
        '.........OOOOOOO',
        '..........OOOOOO',
        '............OOOO',
        '..........QQQ',
        '..........QQQ',
      ],
    },
    // つや（左上）
    { x: 9, y: 13, rows: ['.AA', 'AA.', 'A..'] },
  ],
};

/** イヨカンムシャ（コミカンの しんか）：かわの かぶとと 葉の かざり、葉の たて、きりっと まゆ（モリ） */
const iyokanMusha: MonsterDesign = {
  size: 32,
  colors: {
    O: NQ.orange,
    A: NQ.apricot,
    Q: NQ.amber,
    L: NQ.leaf,
    G: NQ.green,
    M: NQ.lime,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.orange]: NQ.amber, [NQ.leaf]: NQ.green },
  layers: [
    // 葉の かざり（かぶとの 前立て）
    {
      mirror: true,
      y: 4,
      rows: ['...............L', '..............LL', '.............LGL', '.............LLL'],
    },
    {
      mirror: true,
      rows: [
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '...........OOOOO',
        '.........QQQQQQQ',
        '........QQQQQQQQ',
        '.......QQQQQQQQQ',
        '......OOOOOOOOOO',
        '.....OOOOOOOOOOO',
        '.....OOOOOOOOOOO',
        '.....OOOooOOOOOO',
        '.....OOOOOoOOOOO',
        '.....OOOOOWWOOOO',
        '.....OOOOOWoOOOO',
        '.....OOOOOWoOOOO',
        '.....OOppOOOOoOO',
        '.....OOOOOOOOOoo',
        '.....OOOOOOOOOOO',
        '.....OOOOOOOOOOO',
        '......OOOOOOOOOO',
        '.......OOOOOOOOO',
        '........OOOOOOOO',
        '..........OOOOOO',
        '..........QQQ',
        '..........QQQ',
      ],
    },
    // 葉の かたあて
    { mirror: true, x: 3, y: 13, rows: ['LLL', 'LGLL', 'LLL'] },
    // 葉の たて（左手）
    { x: 1, y: 17, rows: ['..LLL', '.LLLLL', 'LLGLLL', 'LLLLLL', 'LLLLLL', '.LLLLL', '..LLL'] },
    // つや（左上）
    { x: 8, y: 13, rows: ['.AA', 'AA.'] },
  ],
};

/** モフタオル：今治の タオル。ふわふわの 白い ぬのに 青い しま、はしが 風で ひらひら（カゼ） */
const mofutaoru: MonsterDesign = {
  size: 32,
  colors: {
    P: NQ.paper,
    C: NQ.cloud,
    W: NQ.white,
    A: NQ.aqua,
    T: NQ.teal,
    M: NQ.mint,
    p: NQ.blush,
  },
  rim: { [NQ.paper]: NQ.cloud },
  layers: [
    // はしが ひらひら（つばさのように）
    { mirror: true, x: 1, y: 9, rows: ['....P', '..PPP', '.PPPP', 'PPPPP', '.PPPP', '..PPP', '....P'] },
    {
      mirror: true,
      rows: [
        '',
        '',
        '',
        '',
        '',
        '.........PPPPPPP',
        '.......PPPPPPPPP',
        '......PPPPPPPPPP',
        '.....PPPPPPPPPPP',
        '.....PPPPPPPPPPP',
        '.....PPPPPPPPPPP',
        '.....PPPPPPPPPPP',
        '.....PPPPPPPPPPP',
        '.....PPPPPWoPPPP',
        '.....PPPPPooPPPP',
        '.....PPPPPooPPPP',
        '.....PPppPPPPoPP',
        '.....PPPPPPPPPPo',
        '.....PPPPPPPPPPP',
        '.....PPPPPPPPPPP',
        '.....AAAAAAAAAAA',
        '.....PPPPPPPPPPP',
        '.....TTTTTTTTTTT',
        '.....PPPPPPPPPPP',
        '.....PPPPPPPPPPP',
        '.....PCPCPCPCPCP',
        '.....PCPCPCPCPCP',
        '.....PPPPPPPPPPP',
        '......PP..PP..PP',
        '......PP..PP..PP',
      ],
    },
    // 風
    { x: 1, y: 21, rows: ['.MM', 'M..', '.MM'] },
    { x: 27, y: 24, rows: ['MM.', '..M', 'MM.'] },
  ],
};

/** ソラトビタオル（モフタオルの しんか）：大きく ひろげた ぬのの つばさ、青い しま、きりっと まゆ（カゼ） */
const soratobiTaoru: MonsterDesign = {
  size: 32,
  colors: {
    P: NQ.paper,
    C: NQ.cloud,
    W: NQ.white,
    A: NQ.aqua,
    T: NQ.teal,
    M: NQ.mint,
    p: NQ.blush,
  },
  rim: { [NQ.paper]: NQ.cloud },
  layers: [
    // ひろげた つばさ
    {
      mirror: true,
      y: 10,
      rows: [
        '......PP',
        '....PPPP',
        '..PPPPPP',
        '.PPPPPPP',
        '.PAAAAAP',
        '.PPPPPPP',
        '.PTTTTTP',
        '.PPPPPPP',
        '..PPPPPP',
        '...PPPPP',
        '.....PPP',
      ],
    },
    {
      mirror: true,
      rows: [
        '',
        '',
        '',
        '',
        '',
        '',
        '...........PPPPP',
        '.........PPPPPPP',
        '........PPPPPPPP',
        '........PPPPPPPP',
        '........PPPPPPPP',
        '........PPPooPPP',
        '........PPPPPoPP',
        '........PPPWoPPP',
        '........PPPooPPP',
        '........PPPooPPP',
        '........PppPPPoP',
        '........PPPPPPPo',
        '........PPPPPPPP',
        '........AAAAAAAA',
        '........PPPPPPPP',
        '........TTTTTTTT',
        '........PPPPPPPP',
        '........PPPPPPPP',
        '........PPPPPPPP',
        '........PCPCPCPC',
        '........PCPCPCPC',
        '........PPPPPPPP',
        '.........PP..PP.',
        '.........PP..PP.',
      ],
    },
    // 風
    { x: 1, y: 24, rows: ['.MM', 'M..', '.MM'] },
    { x: 27, y: 26, rows: ['MM.', '..M', 'MM.'] },
  ],
};

/** ジャコテンギョ：宇和島の じゃこ天の 魚。きつね色の からだに つぶつぶ、青い ひれと 尾びれ（ミズ） */
const jakotengyo: MonsterDesign = {
  size: 32,
  colors: {
    T: NQ.tan,
    S: NQ.sand,
    B: NQ.brown,
    A: NQ.azure,
    b: NQ.blue,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.tan]: NQ.brown, [NQ.azure]: NQ.blue },
  layers: [
    // せびれ（とげの ある ひれ）
    { mirror: true, y: 8, rows: ['...........A.A.A', '..........AAAAAA', '...........AAAAA'] },
    // むなびれ
    { mirror: true, x: 2, y: 17, rows: ['...A', '.AAA', 'AAAA', 'AbAA', '.AAA', '...A'] },
    // 尾びれ
    {
      mirror: true,
      y: 26,
      rows: ['...........AAAAA', '.........AAAAAAA', '........AAAAAAAA', '........AAAAAAAA'],
    },
    {
      mirror: true,
      rows: [
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '............TTTT',
        '..........TTTTTT',
        '.........TTTTTTT',
        '........TTTTTTTT',
        '.......TTTTTTTTT',
        '.......TTTTWWTTT',
        '......TTTTTWoTTT',
        '......TTTTTWoTTT',
        '......TTppTTTToT',
        '......TTTTTTTTTo',
        '......TTTTTTTTTT',
        '.......TTTTTTTTT',
        '.......TTTTTTTTT',
        '........TTTTTTTT',
        '.........TTTTTTT',
        '...........TTTTT',
      ],
    },
    // あげた つぶつぶ と つや
    { x: 8, y: 21, rows: ['B..B', '..B.', 'B..B'] },
    { x: 19, y: 14, rows: ['.B.', 'B.B'] },
    { x: 9, y: 13, rows: ['.SS', 'SS.'] },
  ],
};

/** ジャコテンダイ（ジャコテンギョの しんか）：タイのように 大きな せびれと 尾びれ、きりっと まゆ（ミズ） */
const jakotendai: MonsterDesign = {
  size: 32,
  colors: {
    T: NQ.tan,
    S: NQ.sand,
    B: NQ.brown,
    A: NQ.azure,
    b: NQ.blue,
    I: NQ.ice,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.tan]: NQ.brown, [NQ.azure]: NQ.blue },
  layers: [
    // とがった せびれ
    {
      mirror: true,
      y: 3,
      rows: [
        '.........A.A.A.A',
        '........AAAAAAAA',
        '.......AAAIAAAAA',
        '.......AAAAAAAAA',
        '........AAAAAAAA',
      ],
    },
    // 大きな むなびれ
    {
      mirror: true,
      x: 1,
      y: 16,
      rows: ['....A', '..AAA', '.AAAA', 'AAbAA', 'AAAAA', '.AAAA', '..AAA', '....A'],
    },
    // 大きな 尾びれ
    {
      mirror: true,
      y: 25,
      rows: [
        '..........AAAAAA',
        '........AAAAAAAA',
        '.......AAAIAAAAA',
        '......AAAAAAAAAA',
        '......AAAAAAAAAA',
      ],
    },
    {
      mirror: true,
      rows: [
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '..........TTTTTT',
        '........TTTTTTTT',
        '.......TTTTTTTTT',
        '......TTTTTTTTTT',
        '......TTTooTTTTT',
        '......TTTTToTTTT',
        '......TTTTWWTTTT',
        '......TTTTWoTTTT',
        '......TTTTWoTTTT',
        '.....TTppTTTToTT',
        '.....TTTTTTTTToo',
        '.....TTTTTTTTTTT',
        '.....TTTTTTTTTTT',
        '......TTTTTTTTTT',
        '......TTTTTTTTTT',
        '.......TTTTTTTTT',
        '........TTTTTTTT',
        '..........TTTTTT',
      ],
    },
    // あげた つぶつぶ と つや
    { x: 7, y: 20, rows: ['B..B', '..B.', 'B..B'] },
    { x: 19, y: 17, rows: ['.B.', 'B.B'] },
    { x: 8, y: 11, rows: ['.SS', 'SS.'] },
  ],
};

/**
 * ユアミサギ（中ボス）：道後温泉の 湯に つかる 白い サギ。頭に 王冠、黄色い 長い くちばし、
 * ひろげた つばさ、足もとは 湯ぶねと ゆげ（カゼ）
 */
const yuamisagi: MonsterDesign = {
  size: 40,
  colors: {
    W: NQ.white,
    C: NQ.cloud,
    Y: NQ.yellow,
    G: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
    A: NQ.azure,
    S: NQ.sky,
    T: NQ.tan,
    B: NQ.brown,
  },
  rim: { [NQ.white]: NQ.cloud, [NQ.azure]: NQ.blue },
  rimDepth: 2,
  layers: [
    // ゆげ
    { mirror: true, x: 1, y: 4, rows: ['.WW.', 'WCCW', '.WW.'] },
    { mirror: true, x: 2, y: 13, rows: ['.WW.', 'WCCW', '.WW.'] },
    // つばさ
    {
      mirror: true,
      y: 16,
      rows: [
        '.......W',
        '.....WWW',
        '....WCWW',
        '...WWCWW',
        '...WCWWW',
        '..WWCWWW',
        '..WCWWWW',
        '..WWCWWW',
        '..WCWWWW',
        '..WWCWWW',
        '...WWCWW',
        '...WWWCW',
        '....WWWW',
        '.....WWW',
        '......WW',
      ],
    },
    {
      mirror: true,
      rows: [
        '',
        '...............G...G',
        '...............GG.GG',
        '...............GGGGR',
        '...............QQQQQ',
        '..............WWWWWW',
        '.............WWWWWWW',
        '............WWWWWWWW',
        '............WWWWWWWW',
        '............WWoooWWW',
        '............WWYYoWWW',
        '............WWYYoWWW',
        '............WWYYoWWW',
        '............WWYooWWW',
        '.............WWWWWYY',
        '.............WWWWWYY',
        '..............WWWWYY',
        '..............WWWWWY',
        '..............WWWWWY',
        '..............WWWWWW',
        '..............WWWWWW',
        '.............WWWWWWW',
        '...........WWWWWWWWW',
        '..........WWWWWWWWWW',
        '.........WWWWWWWWWWW',
        '.........WWWWWWWWWWW',
        '........WWWWWWWWWWWW',
        '........WWWWWWWWWWWW',
        '........WWWWWWWWWWWW',
        '........WWWWWWWWWWWW',
        '........WWWWWWWWWWWW',
        '.........WWWWWWWWWWW',
        '.........WWWWWWWWWWW',
        '..........WWWWWWWWWW',
        '...........WWWWWWWWW',
        '.............QQ',
        '.............QQ',
        '.............QQ',
      ],
    },
    // 湯ぶねと お湯
    {
      mirror: true,
      y: 36,
      rows: ['..ASAAAAAAAAAAAAAAAA', '..TTTTTTTTTTTTTTTTTT', '..BBBBBBBBBBBBBBBBBB'],
    },
  ],
};

/** ユアミサギ（フィールドに 立つ 32×32） */
const yuamisagiField: MonsterDesign = {
  size: 32,
  colors: {
    W: NQ.white,
    C: NQ.cloud,
    Y: NQ.yellow,
    G: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
    A: NQ.azure,
    T: NQ.tan,
    B: NQ.brown,
  },
  rim: { [NQ.white]: NQ.cloud },
  layers: [
    { mirror: true, y: 15, rows: ['.....W', '...WWW', '..WCWW', '..WWCW', '..WCWW', '...WWW', '....WW'] },
    {
      mirror: true,
      rows: [
        '',
        '',
        '',
        '............G..G',
        '............GGGR',
        '............QQQQ',
        '..........WWWWWW',
        '.........WWWWWWW',
        '.........WWWWWWW',
        '.........WWYYoWW',
        '.........WWYYoWW',
        '.........WWYooWW',
        '..........WWWWYY',
        '..........WWWWYY',
        '...........WWWWY',
        '...........WWWWW',
        '..........WWWWWW',
        '.........WWWWWWW',
        '........WWWWWWWW',
        '.......WWWWWWWWW',
        '.......WWWWWWWWW',
        '.......WWWWWWWWW',
        '.......WWWWWWWWW',
        '........WWWWWWWW',
        '.........WWWWWWW',
        '..........QQ',
        '..........QQ',
      ],
    },
    { mirror: true, y: 27, rows: ['..AAAAAAAAAAAAAA', '..TTTTTTTTTTTTTT', '..BBBBBBBBBBBBBB'] },
  ],
};

const ISHIZUCHI_BODY = [
  '',
  '...................G...G',
  '...................GG.GG',
  '...................GGGGR',
  '...................QQQQQ',
  '...................TTTTT',
  '.................TTTTTTT',
  '...............TTTTTTTTT',
  '..............TTTTTTTTTT',
  '.............TTTTTTTTTTT',
  '............TTTTTTTTTTTT',
  '............TTooooTTTTTT',
  '............TTTGGGoTTTTT',
  '............TTTGGGoTTTTT',
  '............TTTGGGoTTTTT',
  '............TTTGGooTTTTT',
  '............TTTTTTTTTTTT',
  '............TTTTTTTTTTTT',
  '............TTTTToooooooo'.slice(0, 24),
  '.............TTTTTTTTTTT',
  '............TTTTTTTTTTTT',
  '.....KKTTTTTTTTTTTTTTTTT',
  '....KTTTTTTTTTTTTTTTTTTT',
  '....TTTTTTTTTTTTTTTTTTTT',
  '....TTTTTTTTTTTTTTTTTTTT',
  '....TTTnnnnnnnnnnnTTTTTT',
  '....TTTTTTTTTTTTTTTTTTTT',
  '....TTTTTTTTSTTTTTTTTTTT',
  '....TTTTTTTTTTTTTTTTTTTT',
  '....TTTTTT..TTTTTTTTTTTT',
  '....TTTTTT..TTTTTTTTTTTT',
  '....TTTTTT..TTTTTTTTTTTT',
  '....TTTTTT..TTTTTTTTTTTT',
  '...TTTTTTT..TTTTTTTTTTTT',
  '...TTTTTTT..TTTTTTTTTTTT',
  '...TTTTTTT..TTTTTTTTTTTT',
  '...TTTTTTT...TTTTTTTTTTT',
  '...TTTTTTT...TTTTTTTTTTT',
  '..TTTTTTTT...TTTTTTTTTTT',
  '..TTTTTTTT...TTTTTTTTTTT',
  '..TTTTTTTT...TTTTTTTTTTT',
  '..TTTTTTTT..TTTTTTTTTTTT',
  '..TTTTTTTT..TTTTTTTTTTTT',
  '...TTTTTT...TTTTTTTTTTTT',
  '...KKKKKK...KKKKKKKKKKKK',
  '...KKKKKK...KKKKKKKKKKKK',
  '....KKKK.....KKKKKKKKKKK',
];

/**
 * イシヅチオウ（県ボス）：石鎚山の 岩から 生まれた 大おとこ。とがった 岩の つの、王冠、
 * 金色に 光る 目、むねに かけた くさり、体を 走る 銅の すじ（ツチ → 後半 ヒノ）
 */
const ishizuchiOu: MonsterDesign = {
  size: 48,
  colors: {
    T: NQ.tan,
    S: NQ.sand,
    B: NQ.brown,
    K: NQ.bark,
    E: NQ.beige,
    n: NQ.silver,
    G: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
    A: NQ.amber,
    W: NQ.white,
  },
  rim: { [NQ.tan]: NQ.brown, [NQ.gold]: NQ.ochre },
  rimDepth: 2,
  layers: [
    // 岩の つの（とがった 山の みね）
    {
      mirror: true,
      y: 1,
      rows: [
        '..............K',
        '.............KTK',
        '............KTTK',
        '...........KTTTK',
        '..........KTTTTK',
        '.........KTTTTTK',
      ],
    },
    { mirror: true, rows: ISHIZUCHI_BODY },
    // 銅の すじ（別子銅山）と 岩の ひび
    { x: 6, y: 27, rows: ['.A', 'A.', '.A', '..A', '.A'] },
    { x: 34, y: 30, rows: ['A.', '.A', 'A.', '.A'] },
    { x: 14, y: 35, rows: ['..A.', '.A..', 'A...', '.A..'] },
    { x: 17, y: 21, rows: ['B..B', '.BB.'] },
    // 岩の ひび
    { x: 9, y: 33, rows: ['..B', '.B.', 'B..', '.B.', '..B'] },
    { x: 30, y: 36, rows: ['B..', '.B.', '..B', '.B.'] },
    { x: 20, y: 29, rows: ['.B..B', 'B..B.'] },
    // 岩の つや（左上）
    { x: 14, y: 8, rows: ['.SS', 'SS.', 'S..'] },
    { x: 5, y: 23, rows: ['.SS', 'SS.', 'S..'] },
    { x: 13, y: 22, rows: ['SSSS'] },
  ],
};

/** イシヅチオウ 後半：体の 銅の すじが 赤く もえ、かたから 炎が 立ちのぼる（ヒノ） */
const ishizuchiOuP0: MonsterDesign = {
  ...ishizuchiOu,
  colors: { ...ishizuchiOu.colors, A: NQ.vermilion, S: NQ.apricot, E: NQ.gold },
  rim: { [NQ.tan]: NQ.brown, [NQ.gold]: NQ.ochre },
  layers: [
    // うしろの 炎
    {
      mirror: true,
      x: 1,
      y: 14,
      rows: [
        '.....G',
        '....AGA',
        '....AGA',
        '...AAGAA',
        '...AAAAA',
        '..G.AAAA',
        '.AGA.AAA',
        '.AGA..AA',
        'AAGAA',
        'AAAAA',
      ],
    },
    ...ishizuchiOu.layers,
    // もえる すじ
    { x: 10, y: 24, rows: ['.A.', 'A.A', '.A.'] },
    { x: 36, y: 26, rows: ['.A.', 'A.A', '.A.'] },
  ],
};

/** 村上武吉：金の 波の 前立てと 青い よろい、白い ひげ（ミズ → 後半 カゼ） */
const murakamiTakeyoshi = lord(
  [
    '........................',
    '........................',
    '.....GG.................',
    '....GYYG................',
    '....GYYG......GG........',
    '.....GGYG....GYYG.......',
    '......GGYGG..GYYGG......',
    '........GGYGGGGYYGGGGGG.',
    '..........GGGGGGGGGGGGGG',
    '...............NNNNNNNGG',
    ...HELMET,
    ...BEARD_FACE,
  ],
  {
    N: NQ.navy,
    L: NQ.blue,
    K: NQ.navy,
    S: NQ.azure,
    G: NQ.gold,
    Y: NQ.yellow,
    R: NQ.red,
    T: NQ.blue,
    H: NQ.teal,
    M: NQ.hairBlack,
  },
  { [NQ.azure]: NQ.blue },
);

export const EHIME: Readonly<Record<string, MonsterDesign>> = {
  'ehime-midboss-yuamisagi': yuamisagi,
  'ehime-midboss-yuamisagi.field': yuamisagiField,
  'ehime-boss-ishizuchi-ou': ishizuchiOu,
  'ehime-boss-ishizuchi-ou.p0': ishizuchiOuP0,
  'ehime-lastboss-murakami-takeyoshi': murakamiTakeyoshi,
  'ehime-komikan': komikan,
  'ehime-iyokan-musha': iyokanMusha,
  'ehime-mofutaoru': mofutaoru,
  'ehime-soratobi-taoru': soratobiTaoru,
  'ehime-jakotengyo': jakotengyo,
  'ehime-jakotendai': jakotendai,
};
