/** 福島のモンスター（docs/05 §2、docs/06 §6.3〜6.6） */
import { NQ } from '../palette';
import type { MonsterDesign } from './design';
import { LAST_BOSSES } from './lastbosses';

/** アカベコン：会津の赤べこ。大きくゆれる頭、まゆの もよう、むねに丸いもよう（ツチ） */
const akabekon: MonsterDesign = {
  size: 32,
  colors: {
    R: NQ.red,
    r: NQ.brick,
    A: NQ.apricot,
    H: NQ.beige,
    h: NQ.sand,
    M: NQ.beige,
    m: NQ.sand,
    W: NQ.white,
    p: NQ.blush,
    G: NQ.gold,
    K: NQ.night,
  },
  rim: { [NQ.red]: NQ.brick },
  rimDepth: 2,
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '.....H..........',
        '.....HH.........',
        '......Hh..RRRRRR',
        '.......hRRRRRRRR',
        '......RRRRRRRRRR',
        '.....RRRRRRRRRRR',
        '..RR.RRRRRRRRRRR',
        '.RRRRRRRRRRRRRRR',
        '.rrrrRRRRRRRRRRR',
        '.....RRRooRRRRRR',
        '.....RRoRRoRRRRR',
        '.....RRRWWRRRRRR',
        '.....RRRWoRRRRRR',
        '.....RRRWoRRRRRR',
        '.....RppRRMMMMMM',
        '.....RRRMMMoMMMM',
        '.....RRMMMMMMMMM',
        '......RMMMMMMoMM',
        '.......mmmmmmmoo',
        '......rrrrrrrrrr',
        '.....RRRRRRRRRRG',
        '.....RGRRRRRRRGo',
        '.....GoGRRRRRRGo',
        '.....RGRRRRRRRRG',
        '.....RRRRRRRRRRR',
        '......RRRRRRRRRR',
        '.......RRR......',
        '.......RRR......',
        '.......KKK......',
      ],
    },
    // つや（左上）
    { x: 8, y: 6, rows: ['AA', 'A.'] },
  ],
};

/** モモリン：もものようせい。先のとがった実、まん中のすじ、葉っぱ、小さなわっか（ヒカリ） */
const momorin: MonsterDesign = {
  size: 32,
  colors: {
    P: NQ.blush,
    C: NQ.red,
    W: NQ.white,
    G: NQ.gold,
    O: NQ.ochre,
    L: NQ.leaf,
    l: NQ.green,
    V: NQ.lime,
    x: NQ.berry,
    c: NQ.cream,
  },
  rim: { [NQ.blush]: NQ.berry },
  rimDepth: 2,
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '...........GGGGG',
        '..........G.....',
        '...........OOOOO',
        '................',
        '.........LL.....',
        '........LVLL....',
        '.......lLVLLL...',
        '........llLLLLlP',
        '..........lllPPP',
        '..........PPPPPP',
        '........PPPPPPPP',
        '......PPPPPPPPPP',
        '.....PPPPPPPPPPP',
        '....PPPPPPPPPPPP',
        '...PPPPPPPPPPPPP',
        '...PPPPPPPPPPPPP',
        '..PPPPPPPPPPPPPP',
        '..PPPPPPPWWPPPPP',
        '..PPPPPPPWoPPPPP',
        '..PPPPPPPWoPPPPP',
        '..PPPPPCCPPPPPPP',
        '..PPPPPPPPPPPPoP',
        '..PPPPPPPPPPPPPo',
        '...PPPPPPPPPPPPP',
        '...PPPPPPPPPPPPP',
        '....PPPPPPPPPPPP',
        '.....PPPPPPPPPPP',
        '.......PPPPPPPPP',
        '..........PPPPPP',
      ],
    },
    // もものすじ（先から少し右へまがる）
    { x: 16, y: 10, rows: ['x', 'x', 'x', '.x', '.x', '.x'] },
    // つや（左上）
    { x: 6, y: 13, rows: ['.c', 'cW', 'c.'] },
    // きらり
    { x: 26, y: 10, rows: ['.W.', 'WcW', '.W.'] },
  ],
};

/** コボシ：会津の起き上がり小法師。赤いきもの、たおれても おきあがる。まわりに風（カゼ） */
const koboshi: MonsterDesign = {
  size: 32,
  colors: {
    K: NQ.hairBlack,
    F: NQ.paper,
    R: NQ.red,
    W: NQ.white,
    p: NQ.blush,
    G: NQ.gold,
    O: NQ.ochre,
    M: NQ.mint,
    A: NQ.aqua,
  },
  rim: { [NQ.red]: NQ.brick, [NQ.paper]: NQ.cloud },
  rimDepth: 2,
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '................',
        '................',
        '............KKKK',
        '..........KKKKKK',
        '.........KKKKKKK',
        '........KKKKKKKK',
        '.......KKKKKKKKK',
        '.......KKKKKFFFF',
        '......KKKKFFFFFF',
        '......KKKFFFFFFF',
        '......KKFFFFFFFF',
        '.....RKFFFWoFFFF',
        '.....RKFFFooFFFF',
        '.....RKFFFooFFFF',
        '.....RRFFpFFFFFF',
        '.....RRFFFFFFFoF',
        '.....RRRFFFFFFFo',
        '....RRRRRRFFFFFF',
        '....RRRRRRFFRRRR',
        '....RRRRRRRFFRRR',
        '....RRRRRRRRFFRR',
        '....RRRRRRRRRFFR',
        '....RRRRRRRRRRFF',
        '....GGGGGGGGGGGG',
        '....OOOOOOOOOOOO',
        '....RRRRWRRRRRRR',
        '.....RRWGWRRRRRR',
        '......RRWRRRRRRR',
        '........RRRRRRRR',
      ],
    },
    // 風のうず（左上と右下）
    { x: 1, y: 9, rows: ['.MMM', 'M...', 'M.A.', '.AA.'] },
    { x: 27, y: 18, rows: ['MMM.', '...M', '.A.M', '.AA.'] },
    { x: 25, y: 4, rows: ['AMM'] },
  ],
};

/** ゴシキスライム：五色沼の色の帯をもつ大きなスライム。ハスの葉に王冠、まわりに水のしずく（ミズ → モリ） */
const goshikiSlime: MonsterDesign = {
  size: 40,
  colors: {
    S: NQ.sky,
    I: NQ.ice,
    Z: NQ.azure,
    B: NQ.blue,
    Q: NQ.aqua,
    E: NQ.leaf,
    L: NQ.leaf,
    l: NQ.green,
    W: NQ.white,
    G: NQ.gold,
    O: NQ.ochre,
    R: NQ.red,
  },
  rim: { [NQ.sky]: NQ.azure, [NQ.azure]: NQ.blue, [NQ.aqua]: NQ.teal, [NQ.leaf]: NQ.green },
  rimDepth: 2,
  layers: [
    // 水のうで（両わきに立ちあがる波。先が内がわへ くるりと まき、白いしぶき）
    {
      mirror: true,
      y: 3,
      rows: [
        '....W...',
        '...WWW..',
        '..WWWWWW',
        '.WSSSSWW',
        '.SQQQS.W',
        '..SQQQ.W',
        '..SQQ...',
        '..SQQ...',
        '..SQQ...',
        '..SQQ...',
        '..SQQ...',
        '.SQQQ...',
        '.SQQQ...',
        '.SQQQ...',
        '.SQQQ...',
        '.SQQQ...',
        '.SQQQ...',
        '.SQQQ...',
        '.SQQQ...',
        '.SQQQ...',
        '.SQQQ...',
        '.SQQQ...',
        '.SQQQ...',
        '.SQQQ...',
        '.SQQQQ..',
        '..SQQQQ.',
      ],
    },
    // しずく
    { mirror: true, x: 10, y: 1, rows: ['.S.', 'ISS', '.Z.'] },
    {
      mirror: true,
      rows: [
        '....................',
        '....................',
        '..............G....G',
        '..............GG..GG',
        '..............GGGGGG',
        '..............GRGGGR',
        '..............OOOOOO',
        '..........lLLLLLLLLL',
        '.........lLLLLLLLLLL',
        '..........llllllllll',
        '.............SSSSSSS',
        '...........SSSSSSSSS',
        '..........SSSSSSSSSS',
        '.........SSSSSSSSSSS',
        '.........SSSSZZZSSSS',
        '........SSooZZZSSZZZ',
        '........ZZZZooZZZZZZ',
        '........ZZZWWWZZZZZZ',
        '.......ZZZZWWoZZZZZZ',
        '.......ZZZZWooZZZZZZ',
        '.......ZZZZWooZZZZZZ',
        '.......ZZZZZZZZZZZZZ',
        '......QQQZZZZQQQQZZZ',
        '......QQQQQQQQQoQQQQ',
        '......QQQQQQQQQQoWBB',
        '......QQQQQQQQQQQooo',
        '.....QQQQQQQQQQQQQQQ',
        '.....QQQQQQQQQQQQQQQ',
        '.....QQQQQQQQQQQQQQQ',
        '.....EEQQQQEEEEQQQQE',
        '.....EEEEEEEEEEEEEEE',
        '....EEEEEEEEEEEEEEEE',
        '....EEEEEEEEEEEEEEEE',
        '....EEEEEEEEEEEEEEEE',
        '....EEEEEEEEEEEEEEEE',
        '....EEEEEEEEEEEEEEEE',
        '....EEEEEEEEEEEEEEEE',
        '.....EEEEEEEEEEEEEEE',
        '......EEEEEEEEEEEEEE',
      ],
    },
    // つや（左上）
    { x: 11, y: 11, rows: ['.II', 'IW.', 'I..'] },
    // あわ
    { x: 7, y: 27, rows: ['.I.', 'I.I', '.I.'] },
    { x: 30, y: 32, rows: ['.I.', 'I.I', '.I.'] },
  ],
};

/** 後半：ぬまの色がかわり、ほとんど みどりに（モリ） */
const goshikiSlimeP0: MonsterDesign = {
  ...goshikiSlime,
  colors: { ...goshikiSlime.colors, S: NQ.lime, Z: NQ.leaf, E: NQ.green, l: NQ.forest },
  rim: { [NQ.lime]: NQ.leaf, [NQ.leaf]: NQ.green, [NQ.aqua]: NQ.teal, [NQ.green]: NQ.forest },
};

/** フィールドに立つ版（32×32） */
const goshikiSlimeField: MonsterDesign = {
  size: 32,
  colors: {
    S: NQ.sky,
    Z: NQ.azure,
    Q: NQ.aqua,
    E: NQ.leaf,
    L: NQ.leaf,
    l: NQ.green,
    W: NQ.white,
    G: NQ.gold,
    O: NQ.ochre,
    R: NQ.red,
  },
  rim: { [NQ.sky]: NQ.azure, [NQ.azure]: NQ.blue, [NQ.aqua]: NQ.teal, [NQ.leaf]: NQ.green },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '...........G...G',
        '...........GG.GG',
        '...........GGGGR',
        '...........OOOOO',
        '........lLLLLLLL',
        '.......lLLLLLLLL',
        '........llllllll',
        '.........SSSSSSS',
        '.......SSSSSSSSS',
        '......SSSSSSSSSS',
        '.....SSSSSSSSSSS',
        '....SSSZZZZSSSZZ',
        '...ZZZZZZZZZZZZZ',
        '...ZZZZZZWWZZZZZ',
        '..ZZZZZZZWoZZZZZ',
        '..ZZZZZZZWoZZZZZ',
        '..QQQZZZQQQZZZQQ',
        '..QQQQQQQQQQQQoQ',
        '..QQQQQQQQQQQQQo',
        '..QQQQQQQQQQQQQQ',
        '..QQQQQQQQQQQQQQ',
        '..EEQQQQEEEQQQEE',
        '..EEEEEEEEEEEEEE',
        '.EEEEEEEEEEEEEEE',
        '.EEEEEEEEEEEEEEE',
        '.EEEEEEEEEEEEEEE',
        '.EEEEEEEEEEEEEEE',
        '..EEEEEEEEEEEEEE',
        '...EEEEEEEEEEEEE',
        '.....EEEEEEEEEEE',
      ],
    },
  ],
};

/**
 * ツルガジョウノヌシ：鶴ヶ城の赤がわらを よろいにした 白いツル。
 * 頭に城の屋根のかぶと（金のかざりと赤い宝石）、赤い頭のてっぺん、大きく広げたつばさ（カゼ → ヒカリ）
 */
const tsurugajoNoNushi: MonsterDesign = {
  size: 48,
  colors: {
    W: NQ.white,
    C: NQ.cloud,
    N: NQ.night,
    s: NQ.slate,
    R: NQ.red,
    r: NQ.brick,
    G: NQ.gold,
    O: NQ.ochre,
    Y: NQ.sand,
    y: NQ.tan,
    M: NQ.mint,
    A: NQ.aqua,
  },
  rim: { [NQ.white]: NQ.cloud },
  rimDepth: 2,
  layers: [
    // つばさ（赤がわらの肩あて・金のふち・黒い羽の先）と 胴のよろい・足
    {
      mirror: true,
      rows: [
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '.GG.....................',
        '.RRGG...................',
        '.RRrRGG.................',
        '.rrrRRrGG...............',
        '.WWrrRrRRGG.............',
        '.WWCWrrRRrRGG..WWWWWWWWW',
        '.WWCWWCrrrRRrGWWWWWWWWWW',
        '.CWCWWCWWrrRrRWWWWWWWWWW',
        '.CWCCWCWWCWrrRWWWWWWWWWW',
        '.CWWCWCWWCWWCrWWWWWWWWWW',
        '.CWWCWWCWCWWCWWWGGGGGGGG',
        '.CWWCWWCWCCWCWWWRrRrRrRr',
        '.CWWCWWCWWCWCWWWRrRrRrRr',
        '.CWWCWWCWWCWWCWWRrRrRrRr',
        '.CWWCWWCWWCWWCWWGGGGGGGG',
        '.CWWCWWCWWCWWCWWRrRrRrRr',
        '.sNNCWWCWWCWWCWWRrRrRrRr',
        '.sNNCWWCWWCWWCWWWGrRrRrR',
        '.sNNCWWCWWCWWCWWWGrRrRrR',
        '..N.sNNCWWCWWCWWWWGRrRrR',
        '....sNNCWWCWWCWWWWWGrRrR',
        '....sNNsNNCWWCWWWWWWGGGG',
        '.....N.sNNsNNCWWWWWWWWWW',
        '.......sNNsNNsNWWWWWWWWW',
        '........N.sNNsNNNNNssNNN',
        '...........N.sNNNsNsssNN',
        '..............N.NNNssNNN',
        '.................NNssNNN',
        '.................N.ss.NN',
        '..................NssN..',
        '...................ss...',
        '...................ss...',
        '...................ss...',
        '...................ss...',
        '...................ss...',
        '...................ss...',
        '................ssssss..',
      ],
    },
    // 足もとの風
    { mirror: true, x: 8, y: 40, rows: ['MMM.', '...M', '.AA.'] },
    // 横を向いた頭（右＝主人公のほうを見る）：城の屋根のかぶと、赤い頭のてっぺん、長いくちばし、黒い首
    {
      x: 16,
      y: 1,
      rows: [
        '..G...............G',
        '..GGOOOOOOOOOOOOOGG',
        '..RrRrRrRrGGrRrRrRr',
        'GRrRrRrRrGRRGrRrRrRrG',
        'GGGGGGGGGGGGGGGGGGGGG',
        '.....WRRRRRRRRRRN',
        '....WWWWWNNNNNNNNN',
        '....WWWWWNNNGGNNNN',
        '....WWWWWNNNGGoNNNYYYYYYYY',
        '....WWWWWNNNGGoNNNYYYYYYY',
        '....WWWWWNNNGooNNNyyyyy',
        '.....WWWWNNNNNNNN',
        '......WWWNNNNNNN',
        '......WWWNNNNNN',
        '.....WWWNNNN',
        '.....WWNNNN',
        '....WWNNNN',
        '....WWNNNN',
      ],
    },
  ],
};

/** 後半：つばさが金色にかがやき、光があふれる（ヒカリ） */
const tsurugajoNoNushiP0: MonsterDesign = {
  ...tsurugajoNoNushi,
  colors: { ...tsurugajoNoNushi.colors, C: NQ.yellow, M: NQ.cream, A: NQ.gold },
  rim: { [NQ.white]: NQ.cream },
  layers: [
    { mirror: true, x: 3, y: 5, rows: ['M', 'M', 'M'] },
    { mirror: true, x: 1, y: 1, rows: ['.M.', 'MAM', '.M.'] },
    { mirror: true, x: 8, y: 3, rows: ['.M.', 'MAM', '.M.'] },
    { mirror: true, x: 2, y: 30, rows: ['M', 'M', 'M'] },
    { mirror: true, x: 5, y: 33, rows: ['M', 'M', 'M'] },
    { mirror: true, x: 8, y: 35, rows: ['M', 'M', 'M'] },
    { mirror: true, x: 1, y: 35, rows: ['.M.', 'MAM', '.M.'] },
    { mirror: true, x: 4, y: 39, rows: ['.M.', 'MAM', '.M.'] },
    ...tsurugajoNoNushi.layers,
  ],
};

/** アカベコドン：アカベコンの しんか。大きな角、どっしりした体、金と黒の もよう、4本の足（ツチ） */
const akabekoDon: MonsterDesign = {
  size: 32,
  colors: {
    R: NQ.red,
    r: NQ.brick,
    A: NQ.apricot,
    H: NQ.beige,
    h: NQ.sand,
    M: NQ.beige,
    m: NQ.sand,
    W: NQ.white,
    p: NQ.blush,
    G: NQ.gold,
    O: NQ.ochre,
    K: NQ.night,
  },
  rim: { [NQ.red]: NQ.brick },
  rimDepth: 2,
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '.H..............',
        '.HH.............',
        '..HH............',
        '..HHh...........',
        '...HHh....RRRRRR',
        '....HhhRRRRRRRRR',
        '.....hRRRRRRRRRG',
        '..RRRRRRRRRRRRGG',
        '.RAARRRRRRRRRRRG',
        '.rrrrRRRRRRRRRRR',
        '....RRoooRRRRRRR',
        '....RoRRRoRRRRRR',
        '....RRRWWRRRRRRR',
        '....RRRWoRRRRRRR',
        '....RRRWoRRRRRRR',
        '....RpRRRMMMMMMM',
        '....RRRRMMMMoMMM',
        '....RRRMMMMMMMMM',
        '.....RRMMMMMMoMM',
        '......Rmmmmmmmoo',
        '.......rrrrrrrrr',
        '...GGGGGGGGGGGGG',
        '..OOOOOOOOOOOOOG',
        '.RRKRRRGRRRRRRGo',
        '.RKKRRGoGRRRRRGo',
        '.RRKRRRGRRRRRRRG',
        '.RRRRRRRRRRRRRRR',
        '..RRRRRRRRRRRRRR',
        '...RRRR...RRRR..',
        '...KKKK...KKKK..',
      ],
    },
    // つや（左上）
    { x: 10, y: 7, rows: ['AA', 'A.'] },
  ],
};

/** アカツキモモ：モモリンの しんか。夜明けの色に かがやく もも、葉っぱの はね、大きなわっか（ヒカリ） */
const akatsukiMomo: MonsterDesign = {
  size: 32,
  colors: {
    P: NQ.blush,
    C: NQ.red,
    A: NQ.apricot,
    W: NQ.white,
    G: NQ.gold,
    O: NQ.ochre,
    L: NQ.leaf,
    l: NQ.green,
    V: NQ.lime,
    x: NQ.berry,
    c: NQ.cream,
  },
  rim: { [NQ.blush]: NQ.berry, [NQ.apricot]: NQ.red },
  rimDepth: 2,
  layers: [
    // 葉っぱの はね（体の うしろ、横に ひろがる）
    {
      mirror: true,
      y: 8,
      rows: [
        '..ll............',
        '.lLLl...........',
        '.lVVLLl.........',
        '..lLVLLl........',
        '...llLLL........',
      ],
    },
    // ヘタのそばの 葉っぱ（モモリンと おなじ）
    {
      mirror: true,
      y: 4,
      rows: ['..........LL....', '.........LVLL...', '........lLVLL...', '.........lll....'],
    },
    {
      mirror: true,
      rows: [
        '................',
        '.........GGGGGGG',
        '........G.......',
        '.........OOOOOOO',
        '................',
        '...............P',
        '..............PP',
        '............PPPP',
        '..........PPPPPP',
        '........PPPPPPPP',
        '.......PPPPPPPPP',
        '......PPPPPPPPPP',
        '.....PPPPPPPPPPP',
        '....PPPPPPPPPPPP',
        '....PPPPPPPPPPPP',
        '...PPPPPPPPPPPPP',
        '...PPPPPPPPPPPPP',
        '...PPPPPPPWWPPPP',
        '...PPPPPPPWoPPPP',
        '...PPPPPPPWoPPPP',
        '...PPPPPCCPPPPPP',
        '...PPPPPPPPPPoCC',
        '...PPPPPPPPPPPoo',
        '...PPPPPPPPPPPPP',
        '...PPPPPPPPPPPPP',
        '....PPPPPPPPPPPP',
        '.....AAAPPPPPPPP',
        '......AAAAAAAAAA',
        '........AAAAAAAA',
        '..........AAAAAA',
      ],
    },
    // もものすじ
    { x: 16, y: 6, rows: ['x', 'x', 'x', '.x', '.x', '.x', '.x'] },
    // つや（左上）
    { x: 6, y: 13, rows: ['.c', 'cW', 'c.'] },
    // きらり
    { x: 26, y: 4, rows: ['.W.', 'WcW', '.W.'] },
    { x: 1, y: 26, rows: ['.c.', 'cWc', '.c.'] },
  ],
};

/** ヤオキコボシ：コボシの しんか。赤と金の きもの、きりっとした まゆ、せなかに 旗指物（はた。字は かかない）、風（カゼ） */
const yaokiKoboshi: MonsterDesign = {
  size: 32,
  colors: {
    K: NQ.hairBlack,
    F: NQ.paper,
    R: NQ.red,
    W: NQ.white,
    p: NQ.blush,
    G: NQ.gold,
    O: NQ.ochre,
    M: NQ.mint,
    A: NQ.aqua,
  },
  rim: { [NQ.red]: NQ.brick, [NQ.paper]: NQ.cloud },
  rimDepth: 2,
  layers: [
    // せなかの はた（頭の うしろから 右上に 立つ）
    {
      x: 21,
      y: 1,
      rows: [
        '......G.',
        '.RRRRRO.',
        '.RFFFFO.',
        '.RFFFFO.',
        '.RFFFFO.',
        '.RFFFFO.',
        '.RFFFFO.',
        '.RF.FFO.',
        '.R...FO.',
        '......O.',
        '......O.',
      ],
    },
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '................',
        '................',
        '...........KKKKK',
        '.........KKKKKKK',
        '.......KKKKKKKKK',
        '......KKKKKKKKKK',
        '.....KKKKKKKKFFF',
        '....KKKKKKFFFFFF',
        '....KKKKFFFFFFFF',
        '...RKKFFFooFFFFF',
        '...RKFFFFFooFFFF',
        '...RKFFFFWoFFFFF',
        '...RKFFFFooFFFFF',
        '..RRKFFFFooFFFFF',
        '..RRRFFpFFFFFFFF',
        '..RRRFFFFFFFFoFF',
        '..RRRRFFFFFFFFoo',
        '..RRRRRFFFFFFFFF',
        '..RRRRRRRRRFFRRR',
        '..RRRRRRRRRRFFRR',
        '..RRRRRRRRRRRFFR',
        '..RRRRRRRRRRRRFF',
        '..GGGGGGGGGGGGGG',
        '..OOOOOOOOOOOOOO',
        '..RRRRRRRRRRRRRR',
        '...RRRRRWRRRRRRR',
        '....RRRWGWRRRRRR',
        '.....RRRWRRRRRRR',
        '.......RRRRRRRRR',
      ],
    },
    // 風のうず
    { x: 1, y: 3, rows: ['MMM.', '...M', '.AAM'] },
    { x: 1, y: 28, rows: ['MM.', '..M', 'AA.'] },
    { x: 28, y: 28, rows: ['.MM', 'M..', '.AA'] },
  ],
};

/** チヂレメン：喜多方ラーメンの ふとくて ちぢれた めんの モンスター。ゆげを あげて はしる（ヒノ） */
const chijiremen: MonsterDesign = {
  size: 32,
  colors: {
    Y: NQ.yellow,
    C: NQ.cream,
    A: NQ.amber,
    W: NQ.white,
    p: NQ.blush,
    B: NQ.brown,
    V: NQ.vermilion,
    G: NQ.gold,
    S: NQ.cloud,
  },
  rim: { [NQ.yellow]: NQ.amber },
  rimDepth: 2,
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '..........YCY...',
        '........YCYYYCYY',
        '.......YYYCYYYYY',
        '......YCYYYYCYYY',
        '.....YYYYCYYYYYY',
        '.....YCYYYYYCYYY',
        '....YYYYYCYYYYYY',
        '....YYCYYYYYYCYY',
        '....YYYYYYYYYYYY',
        '....YCYYYYYYYCYY',
        '....YYYYYWWYYYYY',
        '....YYYYYWoYYYYY',
        '....YYYYYWoYYYYY',
        '....YppYYYYYYYYY',
        '....YYYYYYYYYoYY',
        '....YCYYYYYYYYYo',
        '....YYYYYCYYYYYY',
        '.....YYCYYYYYCYY',
        '.....YYYYYCYYYYY',
        '......YCYYYYYCYY',
        '.......YYYYCYYYY',
        '........YYYYYCYY',
        '..........YYYYYY',
        '..........AA....',
        '..........AA....',
        '..........AA....',
        '.........AAA....',
        '.........BBB....',
        '.........BBB....',
      ],
    },
    // ゆげ
    { x: 3, y: 2, rows: ['.S.', 'S.S', '.S.'] },
    { x: 26, y: 5, rows: ['.S.', 'S.S', '.S.'] },
    // かまの ほのお
    { x: 1, y: 22, rows: ['.V', 'VG', '.V'] },
    { x: 28, y: 20, rows: ['V.', 'GV', 'V.'] },
  ],
};

/** クラドンブリ：チヂレメンの しんか。喜多方の 蔵の ような どんぶりを せおう（ヒノ） */
const kuraDonburi: MonsterDesign = {
  size: 32,
  colors: {
    Y: NQ.yellow,
    C: NQ.cream,
    A: NQ.amber,
    W: NQ.white,
    p: NQ.blush,
    B: NQ.brown,
    K: NQ.bark,
    V: NQ.vermilion,
    G: NQ.gold,
    S: NQ.cloud,
  },
  rim: { [NQ.yellow]: NQ.amber, [NQ.white]: NQ.cloud },
  rimDepth: 2,
  layers: [
    // 蔵の どんぶり（からだの うしろ）
    {
      mirror: true,
      y: 12,
      rows: [
        '..WWWWWWWWWWWWWW',
        '..WKWWWWKWWWWKWW',
        '..WWWWWWWWWWWWWW',
        '..KKKKKKKKKKKKKK',
        '..WWWWWWWWWWWWWW',
        '..WKWWWWKWWWWKWW',
        '..WWWWWWWWWWWWWW',
        '...WWWWWWWWWWWWW',
        '...KKKKKKKKKKKKK',
        '....WWWWWWWWWWWW',
        '.....WWWWWWWWWWW',
        '.......WWWWWWWWW',
        '.........KKKKKKK',
      ],
    },
    {
      mirror: true,
      rows: [
        '................',
        '..........YCY...',
        '........YCYYYCYY',
        '.......YYYCYYYYY',
        '......YCYYYYCYYY',
        '.....YYYYCYYYYYY',
        '.....YCYYYYYCYYY',
        '....YYYYYCYYYYYY',
        '....YYCYYYYYYCYY',
        '....YYYoooYYYYYY',
        '....YCYYYYYoooYY',
        '....YYYYYWWYYYYY',
        '....YYYYYWoYYYYY',
        '....YYYYYWoYYYYY',
        '....YppYYYYYYYYY',
        '....YYYYYYYYYoYY',
        '....YCYYYYYYYYYo',
        '....YYYYYCYYYYYY',
        '.....YYCYYYYYCYY',
        '.....YYYYYCYYYYY',
        '......YCYYYYYCYY',
        '.......YYYYCYYYY',
        '........YYYYYCYY',
        '..........YYYYYY',
        '..........AA....',
        '..........AA....',
        '..........AA....',
        '.........AAA....',
        '.........BBB....',
        '.........BBB....',
        '................',
      ],
    },
    // ゆげと ほのお
    { x: 3, y: 1, rows: ['.S.', 'S.S', '.S.'] },
    { x: 26, y: 3, rows: ['.S.', 'S.S', '.S.'] },
    { x: 1, y: 24, rows: ['.V', 'VG', '.V'] },
    { x: 28, y: 22, rows: ['V.', 'GV', 'V.'] },
  ],
};

export const FUKUSHIMA: Readonly<Record<string, MonsterDesign>> = {
  'fukushima-lastboss-gamo-ujisato': LAST_BOSSES['fukushima-lastboss-gamo-ujisato']!,
  'fukushima-chijiremen': chijiremen,
  'fukushima-kura-donburi': kuraDonburi,
  'fukushima-akabekon': akabekon,
  'fukushima-momorin': momorin,
  'fukushima-koboshi': koboshi,
  'fukushima-akabeko-don': akabekoDon,
  'fukushima-akatsuki-momo': akatsukiMomo,
  'fukushima-yaoki-koboshi': yaokiKoboshi,
  'fukushima-midboss-goshiki-slime': goshikiSlime,
  'fukushima-midboss-goshiki-slime.p0': goshikiSlimeP0,
  'fukushima-midboss-goshiki-slime.field': goshikiSlimeField,
  'fukushima-boss-tsurugajo-no-nushi': tsurugajoNoNushi,
  'fukushima-boss-tsurugajo-no-nushi.p0': tsurugajoNoNushiP0,
};
