/** 群馬県の モンスター（手描き。docs/06 §4・§6.3〜6.5 の 規格） */
import { NQ } from '../palette';
import type { MonsterDesign } from './design';
import { FACE, HELMET, lord } from './lastbosses';

/** マユマル：まん中が くびれた カイコの まゆ。絹の 糸の わっかが 光り、桑の 葉に のる（ヒカリ） */
const mayumaru: MonsterDesign = {
  size: 32,
  colors: {
    P: NQ.paper,
    W: NQ.white,
    C: NQ.cloud,
    G: NQ.gold,
    Q: NQ.ochre,
    L: NQ.leaf,
    M: NQ.lime,
    p: NQ.blush,
  },
  rim: { [NQ.paper]: NQ.cloud, [NQ.leaf]: NQ.green },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '..........GGGGGG',
        '.........G......',
        '..........QQQQQQ',
        '................',
        '...........PPPPP',
        '.........PPPPPPP',
        '........PPPPPPPP',
        '.......PPPPPPPPP',
        '.......PPPPWWPPP',
        '.......PPPPWoPPP',
        '.......PPPPWoPPP',
        '.......PPpPPPPoP',
        '........PPPPPPPo',
        '........PPPPPPPP',
        '..........PPPPPP',
        '..........PCPPPP',
        '.........PPPPPPP',
        '........PPPPPPPP',
        '.......PPCPPPPPP',
        '.......PPPPPPPPP',
        '......PPPPPCPPPP',
        '......PPPPPPPPPP',
        '......PPPPPPPPPP',
        '.......PPPPPPPPP',
        '........PPPPPPPP',
        '.........PPPPPPP',
        '..........PPPPPP',
        '..LMLLLLLLLLLLLL',
        '...MLLLLLLLLLLLL',
      ],
    },
  ],
};

/** キヌハネヒメ（マユマルの しんか）：まゆから 出た 白い カイコガ。くしの ような 触角、まっ白な つばさ（ヒカリ） */
const kinuhaneHime: MonsterDesign = {
  size: 32,
  colors: {
    P: NQ.paper,
    W: NQ.white,
    C: NQ.cloud,
    G: NQ.gold,
    Q: NQ.ochre,
    p: NQ.blush,
  },
  rim: { [NQ.paper]: NQ.cloud, [NQ.white]: NQ.cloud },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '..........GGGGGG',
        '.........G......',
        '..........QQQQQQ',
        '................',
        '....W...........',
        '.....W..........',
        '..W..W..........',
        '...W..W.........',
        '....W..W........',
        '.....W..W.......',
        '......W..WPPPPPP',
        '.......W.PPPPPPP',
        '........PPPPWWPP',
        '.WWWW...PPPPWoPP',
        '.WWWWWWWPPPPWoPP',
        '.WWWWWWWPPPpPPPP',
        '.WWWWWWWWPPPPPPo',
        '.WWWWWWWWPPPPPPP',
        '.CWWWWWWWPPPPPPP',
        '..CWWWWWWPPPPPPP',
        '..CWWWWWWPPPPPPP',
        '...CWWWWWPPPPPPP',
        '....CWWWWPPPPPPP',
        '.....CWWWPPPPPPP',
        '......CWWPPPPPPP',
        '.......CPPPPPPPP',
        '.........PPPPPPP',
        '.........PPPPPPP',
        '..........PPPPPP',
      ],
    },
  ],
};

/** プルコン：ぷるぷるの こんにゃくの かたまり。黒い つぶつぶ、下に 小さな 足（ツチ） */
const purukon: MonsterDesign = {
  size: 32,
  colors: {
    G: NQ.gray,
    L: NQ.slate,
    C: NQ.silver,
    N: NQ.night,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.gray]: NQ.slate },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
        '.....GGGGGGGGGGG',
        '...GGGGGGGGGGGGG',
        '..GGGCCGGGGGGGGG',
        '..GGCGGGGGGGGGGG',
        '..GGGGGGGNGGGGGG',
        '..GGGGGGGGGGGGGG',
        '..GGGGGGGGWWGGGG',
        '..GGGNGGGGWoGGGG',
        '..GGGGGGGGWoGGGG',
        '..GGGGGGpGGGGGoG',
        '..GGGGGGGGGGGGGo',
        '..GGGGGGGGGNGGGG',
        '..GGGNGGGGGGGGGG',
        '..GGGGGGGGGGGGGG',
        '..GGGGGGGGGGNGGG',
        '..GGGGGGGGGGGGGG',
        '..GGGNGGGGGGGGGG',
        '..GGGGGGGGGGGGGG',
        '...GGGGGGGGGGGGG',
        '.....GGGGGGGGGGG',
        '.....LLLL.......',
        '.....LLLL.......',
      ],
    },
  ],
};

/** ドッシリコン（プルコンの しんか）：どっしり かたまった こんにゃく。白い しらたきの かみ、太い うで（ツチ） */
const dosshirikon: MonsterDesign = {
  size: 32,
  colors: {
    G: NQ.gray,
    L: NQ.slate,
    C: NQ.silver,
    N: NQ.night,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.gray]: NQ.slate },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '..........W...W.',
        '...........W..W.',
        '..........W...WW',
        '..........WWWWWW',
        '....GGGGGGGGGGGG',
        '..GGGGGGGGGGGGGG',
        '..GGGCCGGGGGGGGG',
        '..GGCGGGGGGGGGGG',
        '..GGGGGGGooGGGGG',
        '..GGGGGGGWWGGGGG',
        '..GGGNGGGWoGGGGG',
        '..GGGGGGGWoGGGGG',
        '..GGGGGpGGGGGooG',
        '..GGGGGGGGGGGGGo',
        '.GGGGGGGGGGNGGGG',
        '.GGGGGGGGGGGGGGG',
        '.GGGNGGGGGGGGGGG',
        '.GGGGGGGGGGGGGGG',
        '..GGGGGGGGGGNGGG',
        '..GGGGGGGGGGGGGG',
        '..GGGNGGGGGGGGGG',
        '..GGGGGGGGGGGGGG',
        '..GGGGGGGGGNGGGG',
        '..GGGGGGGGGGGGGG',
        '..GGGGGGGGGGGGGG',
        '..GGGGGGGGGGGGGG',
        '...GGGGGGGGGGGGG',
        '....LLLLL.......',
        '....LLLLL.......',
      ],
    },
  ],
};

/** キャベズキン：外の 葉を ずきんのように かぶった キャベツ。ふとい すじが 何本も はしり、下から 外の 葉が めくれる（モリ） */
const kyabezukin: MonsterDesign = {
  size: 32,
  colors: {
    L: NQ.leaf,
    G: NQ.green,
    M: NQ.lime,
    S: NQ.sprout,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.leaf]: NQ.green, [NQ.sprout]: NQ.lime },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '................',
        '..........LLLLLL',
        '........LLLLLLLL',
        '.......LLLLMLLLL',
        '......LLLLLMLLLL',
        '.....LLLLLLMLLLL',
        '.....LLLLLMSSSSS',
        '....LLLLLMSSSSSS',
        '....LLLLMSSSSSSS',
        '...LLLLMSSSSSSSS',
        '...LLLMSSSSSSSSS',
        '...LLLMSSSWWSSSS',
        '...LLMSSSSWoSSSS',
        '...LLMSSSSWoSSSS',
        '...LLMSSpSSSSSoS',
        '...LLMSSSSSSSSSo',
        '...LLLMSSSSSSSSS',
        '...LLLMSSSSSSSSS',
        '....LLLMSSSSSSSS',
        '....LLLLMSSSSSSS',
        '.....LLLLMSSSSSS',
        '.....LLLLLMSSSSS',
        '......LLLLLLLLLL',
        '.......LLLLLLLLL',
        '........LLLLLLLL',
        '..........LLLLLL',
        '................',
        '................',
      ],
    },
    // 下から めくれた 外の 葉（左右）
    {
      x: 1,
      y: 22,
      rows: ['..GG....', '.GGGG...', 'GGGGGG..', 'GGGGGG..', '.GGGGG..', '..GGGG..', '...GGG..', '....GG..'],
    },
  ],
};

/** キャベヨロイ（キャベズキンの しんか）：葉を 何まいも かさねた よろいと かぶと。まるい 葉の かたあて（モリ） */
const kyabeYoroi: MonsterDesign = {
  size: 32,
  colors: {
    L: NQ.leaf,
    G: NQ.green,
    M: NQ.lime,
    S: NQ.sprout,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.leaf]: NQ.green, [NQ.sprout]: NQ.lime },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '..............ML',
        '.............MLL',
        '..........LLLLLL',
        '........LLLLMLLL',
        '.......LLLLMLLLL',
        '......LLLLLMLLLL',
        '......LLLLMSSSSS',
        '.....LLLLMSSSSSS',
        '.....GGGGGGGGGGG',
        '.....LLMSSSooSSS',
        '.....LLMSSSWWSSS',
        '.....LLMSSSWoSSS',
        '.....LLMSpSSSSoo',
        '.....LLMSSSSSSSS',
        '.....LLLMSSSSSSS',
        '......LLLLLLLLLL',
        '...LLLLLLLLLLLLL',
        '..LLLLLLLLLLLLLL',
        '..LLMLLLLLLLMLLL',
        '..GGGGGGGGGGGGGG',
        '...LLLLLLLLLLLLL',
        '...LLLMLLLLLMLLL',
        '...GGGGGGGGGGGGG',
        '....LLLLLLLLLLLL',
        '....LLLMLLLLLLLL',
        '....GGGGGGGGGGGG',
        '.....LLLLLLLLLLL',
        '.....GGG...GGG..',
        '.....GGG...GGG..',
      ],
    },
    // まるい 葉の かたあて
    { x: 1, y: 16, rows: ['.LLLL.', 'LLMLLL', 'LMLLLL', 'LLLLLL', '.LLLL.'] },
  ],
};

// ───────────────────────── 中ボス ─────────────────────────

/** ユモミダイショウ（中ボス）：草津の 湯けむりの 大男。手ぬぐいを まき、長い 湯もみ板を かまえ、足もとは 湯畑の とい（ミズ → ヒノ） */
const yumomiDaisho: MonsterDesign = {
  size: 40,
  colors: {
    W: NQ.white,
    C: NQ.cloud,
    S: NQ.silver,
    A: NQ.azure,
    K: NQ.sky,
    I: NQ.ice,
    T: NQ.tan,
    B: NQ.brown,
    Y: NQ.cream,
    G: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
    p: NQ.blush,
  },
  rim: { [NQ.white]: NQ.cloud, [NQ.tan]: NQ.brown, [NQ.azure]: NQ.blue, [NQ.gold]: NQ.ochre },
  rimDepth: 2,
  layers: [
    {
      mirror: true,
      rows: [
        '....................',
        '................G..G',
        '................GGGR',
        '................QQQQ',
        '.............WWWWWWW',
        '...........WWWWWWWWW',
        '..........WWWWWWWWWW',
        '..........RRRRRRRRRR',
        '..........WWWWCWWWWW',
        '..........WWWWWWWWWW',
        '..........WWWoooWWWW',
        '..........WWWWWoWWWW',
        '..........WWWWWoWWWW',
        '..........WpWWWWWWWW',
        '...........WWWWWWWWW',
        '............WWWWWWWW',
        '.........WWWWWWWWWWW',
        '.......WWWWWWWWWWWWW',
        '......WWWWCWWWWWWWWW',
        '......WWWWWWWWWWWWWW',
        '.......WWWWWWWWWWWWW',
        '........WWWWWWWWWWWW',
        '..........WWWWWWWWWW',
        '...........WWWWWWWWW',
        '.....C......C.....C.',
        '....CWC....CWC...CWC',
        '.....C......C.....C.',
        '..TTTTTTTTTTTTTTTTTT',
        '..TBBTTBBTTBBTTBBTTB',
        '..AAAAAAAAAAAAAAAAAA',
        '..AKAAKAAAKAAKAAAKAA',
        '..AAAAAAAAAAAAAAAAAA',
        '..TTTTTTTTTTTTTTTTTT',
        '..YAYAAYAYAAYAYAAYAY',
        '..AAAAAAAAAAAAAAAAAA',
        '..IAAIAAAIAAIAAAIAAI',
        '..AAAAAAAAAAAAAAAAAA',
        '..TTTTTTTTTTTTTTTTTT',
        '..BTTBBTTBBTTBBTTBBT',
        '....................',
      ],
    },
    // 湯もみ板（ななめに かまえる）と にぎる 手
    {
      x: 3,
      y: 17,
      rows: [
        '.........TTTT',
        '........TTTTT',
        '.......TTTTT.',
        '......TTTTT..',
        '.....TTTTT...',
        '....TTTTT....',
        '...TTTTT.....',
        '..TTTTT......',
        '.TTTTT.......',
        'TTTTT........',
        'TTTT.........',
      ],
    },
    { x: 2, y: 25, rows: ['WWW', 'WWW'] },
    { x: 24, y: 17, rows: ['WWW', 'WWW'] },
  ],
};

/** ユモミダイショウ（フィールドに立つ 32×32） */
const yumomiDaishoField: MonsterDesign = {
  size: 32,
  colors: {
    W: NQ.white,
    C: NQ.cloud,
    A: NQ.azure,
    K: NQ.sky,
    T: NQ.tan,
    B: NQ.brown,
    Y: NQ.cream,
    G: NQ.gold,
    R: NQ.red,
    p: NQ.blush,
  },
  rim: { [NQ.white]: NQ.cloud, [NQ.tan]: NQ.brown, [NQ.azure]: NQ.blue },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '............G..G',
        '............GGGR',
        '............GGGG',
        '..........WWWWWW',
        '........WWWWWWWW',
        '........RRRRRRRR',
        '........WWWCWWWW',
        '........WWoooWWW',
        '........WWWWoWWW',
        '........WpWWoWWW',
        '.........WWWWWWW',
        '......WWWWWWWWWW',
        '....WWWWWWWWWWWW',
        '....WWWWCWWWWWWW',
        '.....WWWWWWWWWWW',
        '.......WWWWWWWWW',
        '...C.....C....C.',
        '..CWC...CWC..CWC',
        '...C.....C....C.',
        '..TTTTTTTTTTTTTT',
        '..TBBTTBBTTBBTTB',
        '..AAAAAAAAAAAAAA',
        '..AKAAKAAAKAAKAA',
        '..AAAAAAAAAAAAAA',
        '..TTTTTTTTTTTTTT',
        '..YAYAAYAYAAYAYA',
        '..AAAAAAAAAAAAAA',
        '..TTTTTTTTTTTTTT',
        '................',
      ],
    },
    {
      x: 2,
      y: 13,
      rows: ['......TTTT', '.....TTTT.', '....TTTT..', '...TTTT...', '..TTTT....', '.TTTT.....'],
    },
  ],
};

// ───────────────────────── 県ボス ─────────────────────────

const DARUMA_BODY = [
  '......................RR',
  '..................RRRRRR',
  '...............RRRRRRRRR',
  '.............RRRRRRRRRRR',
  '...........RRRRRRRRRRRRR',
  '..........RRRRRRRRRRRRRR',
  '.........RRRRRRRRRRRRRRR',
  '........RRRRRRRRRRRRRRRR',
  '.......RRRRRRRRRRRRRRRRR',
  '......RRRRRRCCCCCCCCCCCC',
  '.....RRRRRCCCCCCCCCCCCCC',
  '.....RRRRCCCCCCCCCCCCCCC',
  '....RRRRCCCCCCCCCCCCCCCC',
  '....RRRCCCCCCCCCCCCCCCCC',
  '...RRRRCCCCCCCCCCCCCCCCC',
  '...RRRCCCCCCCCCCCCCCCCCC',
  '...RRRCCCCCCCCCCCCCCCCCC',
  '..RRRRCCCCCCCCCCCCCCCCCC',
  '..RRRCCCCCCCCCCCCCCCCCCC',
  '..RRRCCCCCCCCCCCCCCCCCCC',
  '..RRRCCCCCCCCCCCCCCCCCCC',
  '..RRRCCCCCCCCCCCCCCCCCCC',
  '..RRRRCCCCCCCCCCCCCCCCCC',
  '..RRRRCCCCCCCCCCCCCCCCCC',
  '...RRRRCCCCCCCCCCCCCCCCC',
  '...RRRRRCCCCCCCCCCCCCCCC',
  '....RRRRRCCCCCCCCCCCCCCC',
  '....RRRRRRCCCCCCCCCCCCCC',
  '.....RRRRRRRCCCCCCCCCCCC',
  '......RRRRRRRRRRRRRRRRRR',
  '.......RRRRRRRRRRRRRRRRR',
  '........RRRRRRRRRRRRRRRR',
  '..........RRRRRRRRRRRRRR',
  '.............RRRRRRRRRRR',
  '................RRRRRRRR',
  '.....................RRR',
];

/** だるまの 顔：鶴の まゆげ、まるい 目、亀の ひげ */
const DARUMA_FACE = [
  '........oooo............',
  '.......oo..ooo..........',
  '......oo......oo........',
  '.......o........o.......',
  '........................',
  '..........ooooo.........',
  '.........oWWWWWo........',
  '........oWWWWWWWo.......',
  '........oWWWWWWWo.......',
  '........oWWWWWWWo.......',
  '.........oWWWWWo........',
  '..........ooooo.........',
  '........................',
  '........................',
  '.................ooo....',
  '..............ooo.......',
  '..........oooo..........',
  '.......ooo..............',
  '......oo................',
  '........................',
  '..............ooooooo...',
  '...............ooooo....',
];

/** ガンカケダルマ（県ボス）：高崎だるまの 大将。まゆげは 鶴、ひげは 亀。まだ 片目は 白いまま（ヒノ） */
const gankakeDaruma: MonsterDesign = {
  size: 48,
  colors: {
    R: NQ.red,
    K: NQ.brick,
    C: NQ.cream,
    Y: NQ.gold,
    Q: NQ.ochre,
    W: NQ.white,
    V: NQ.vermilion,
    A: NQ.apricot,
    G: NQ.gold,
    p: NQ.blush,
  },
  rim: { [NQ.red]: NQ.brick, [NQ.cream]: NQ.ochre, [NQ.gold]: NQ.ochre },
  rimDepth: 2,
  layers: [
    // うしろの 炎
    {
      mirror: true,
      y: 6,
      rows: [
        '.....A..................',
        '....AVA.................',
        '...AVVA.................',
        '....AV..................',
        '..AVVA..................',
        '..AVA...................',
        '.AVVA...................',
        '.AVA....................',
        '.AVVA...................',
        '.AVA....................',
        '.AVVA...................',
        '.AVA....................',
        '.AVVA...................',
        '.AVA....................',
        '.AVVA...................',
        '.AVA....................',
        '..AVVA..................',
        '..AVA...................',
        '...AVA..................',
      ],
    },
    { mirror: true, y: 10, rows: DARUMA_BODY },
    // 王冠
    {
      mirror: true,
      y: 6,
      rows: ['....................Y..Y', '....................YYYR', '....................QQQQ'],
    },
    { mirror: true, y: 20, rows: DARUMA_FACE },
    // 左目だけに 目を 入れる（ねがいごとを した しるし）
    { x: 13, y: 27, rows: ['ooooo', 'ooooo', 'ooooo'] },
  ],
};

/** ガンカケダルマ 後半：もう 片方の 目も 入り、炎が 大きく もえあがる */
const gankakeDarumaP0: MonsterDesign = {
  ...gankakeDaruma,
  layers: [
    ...gankakeDaruma.layers,
    { x: 30, y: 27, rows: ['ooooo', 'ooooo', 'ooooo'] },
    {
      mirror: true,
      y: 2,
      rows: [
        '..A.....................',
        '.AVA....................',
        '.AVVA...................',
        '.AVA....................',
      ],
    },
    { x: 20, y: 1, rows: ['.AA.', 'AVVA', '.AA.'] },
  ],
};

// ───────────────────────── 裏ステージの ラスボス ─────────────────────────

/** 新田義貞：新田の 家の しるし「大中黒」の 前立てと 金の くわがた、鉄色の よろい。うしろに 大中黒の 旗（カゼ） */
const nittaYoshisada = lord(
  [
    '....G...................',
    '....GG..................',
    '.....GG.................',
    '......GG................',
    '.......GG...............',
    '........GG........GGGGGG',
    '.........GG......GGGGGGG',
    '..........GG.....GNNNNNN',
    '...........GGG...GGGGGGG',
    '..............NNNGGGGGGG',
    ...HELMET,
    ...FACE,
  ],
  {
    N: NQ.night,
    L: NQ.slate,
    K: NQ.slate,
    S: NQ.silver,
    G: NQ.gold,
    Y: NQ.yellow,
    R: NQ.red,
    T: NQ.navy,
    H: NQ.denim,
    B: NQ.brown,
  },
  { [NQ.silver]: NQ.gray, [NQ.slate]: NQ.night },
  [
    {
      x: 39,
      y: 4,
      rows: [
        'BWWWWWW',
        'BWWWWWW',
        'BWWWWWW',
        'BWWWWWW',
        'BWWWWWW',
        'BNNNNNN',
        'BNNNNNN',
        'BNNNNNN',
        'BWWWWWW',
        'BWWWWWW',
        'BWWWWWW',
        'BWWWWWW',
        'BWWWWWW',
        'B......',
        'B......',
        'B......',
        'B......',
        'B......',
        'B......',
        'B......',
        'B......',
        'B......',
        'B......',
        'B......',
        'B......',
        'B......',
        'B......',
        'B......',
        'B......',
        'B......',
        'B......',
        'B......',
        'B......',
        'B......',
        'B......',
        'B......',
        'B......',
        'B......',
        'B......',
        'B......',
        'B......',
      ],
    },
  ],
);

export const GUNMA: Readonly<Record<string, MonsterDesign>> = {
  'gunma-mayumaru': mayumaru,
  'gunma-kinuhane-hime': kinuhaneHime,
  'gunma-purukon': purukon,
  'gunma-dosshirikon': dosshirikon,
  'gunma-kyabezukin': kyabezukin,
  'gunma-kyabe-yoroi': kyabeYoroi,
  'gunma-midboss-yumomi-daisho': yumomiDaisho,
  'gunma-midboss-yumomi-daisho.field': yumomiDaishoField,
  'gunma-boss-gankake-daruma': gankakeDaruma,
  'gunma-boss-gankake-daruma.p0': gankakeDarumaP0,
  'gunma-lastboss-nitta-yoshisada': nittaYoshisada,
};
