/** 茨城県の モンスター（手描き。docs/06 §4・§6.3〜6.5 の 規格） */
import { NQ } from '../palette';
import type { MonsterDesign } from './design';

/** ネモフィン：青い ネモフィラの 花を かぶった まるい 小鳥。花びらの つばさで ふわりと とぶ（カゼ） */
const nemofin: MonsterDesign = {
  size: 32,
  colors: {
    A: NQ.azure,
    S: NQ.sky,
    I: NQ.ice,
    W: NQ.white,
    C: NQ.cloud,
    Y: NQ.gold,
    Q: NQ.ochre,
    p: NQ.blush,
  },
  rim: { [NQ.azure]: NQ.blue, [NQ.white]: NQ.cloud, [NQ.sky]: NQ.azure },
  rimDepth: 1,
  layers: [
    // 本体
    {
      x: 5,
      y: 3,
      rows: [
        '.........oooo',
        '........oAAAAo',
        '.....oooAASSAAooo',
        '....oAAAAASSAAAAAo',
        '...oASSAAAWWAAASSAo',
        '..oAASSSAWYYWASSSAAo',
        '...oASSAWWYYWWASSAo',
        '....oAAAAWYYWAAAAo',
        '....oAASSAWWASSAAo',
        '....oASSSSAASSSSAo..o',
        '.oo..oASSAAAASSAo.ooAo',
        'oAAoo.oAAooooAAoooAAo',
        'oAAAAooooWWWWoooAASAo',
        'oAASAAoWWWWWWWWoASAAo',
        'oAASSSoWWWWWWWWoSSAAo',
        'oAASSoWWWWWWWWWWoSAAo',
        'oAASSoWWWWWWWWWWoSAAo',
        'oAAAoWWoWIIIIWoWWoAAo',
        '.ooopWWoIIIIIIoWWpoo',
        '....oWWWIIooIIWWWo',
        '....oWWWIIIIIIWWWo',
        '....oWWIIIIIIIIWWo',
        '.....oWWIIIIIIWWo',
        '.....oWWIIIIIIWWo',
        '......oWIIIIIIWo',
        '......oWWIIIIWWo',
        '.....oQooWWWWooQo',
        '.....oQQQooooQQQo',
      ],
    },
  ],
};

/** アオゾラヒメ（ネモフィンの しんか）：大きな 花びらの つばさと 花の かんむり。空の 色の かぜを おこす（カゼ） */
const aozoraHime: MonsterDesign = {
  size: 32,
  colors: {
    A: NQ.azure,
    S: NQ.sky,
    I: NQ.ice,
    W: NQ.white,
    C: NQ.cloud,
    Y: NQ.gold,
    Q: NQ.ochre,
    p: NQ.blush,
  },
  rim: { [NQ.azure]: NQ.blue, [NQ.white]: NQ.cloud, [NQ.sky]: NQ.azure },
  rimDepth: 1,
  layers: [
    // 本体
    {
      x: 1,
      y: 1,
      rows: [
        '............ooAAoo',
        '...........oAAAAAAo',
        '........oo.oAASSAAo.oo',
        '.......oAAooAASSAAooAAo',
        '......oAAAAAAAAAAAAAAAAo',
        '.....oAASSSAooWWooASSSAAo',
        '.....oAASSSAoWYYWoASSSAAo',
        '......oAAAAAWWYYWWAAAAAo....o',
        '.o.....oAAAAAWYYWAAAAAo....oAo',
        'oAoo....oAAAAAWWAAAAAo...ooAo',
        'oACAoo.oAASSSAAAASSSAAoooAAAo',
        'oAAAAAooAASSSAAAASSSAAoAAAAAo',
        'oAAAAAAAoAASAAooAASAAoAAASACo',
        'oAAASSAAAoAAAooooAAAoAASSAAAo',
        'oAAASSSSAAoooWWWWoooASSSSAAAo',
        'oAAASSSSSSoWWWWWWWWoSSSSSAAAo',
        'oAAASSSSSoWWWWWWWWWWoSSSSAAAo',
        'oAAASSSSoWWWWWWWWWWWWoSSSAAAo',
        'oAAASSSSoWWWWIIIIWWWWoSSSAAAo',
        'oAAAAASSoWWoIIIIIIoWWoSAAAAAo',
        '.ooooAAopWWoIIIIIIoWWpoAoooo',
        '.....oooWWWIIIooIIIWWWoo',
        '........oWWIIIIIIIIWWo',
        '........oWWIIIIIIIIWWo',
        '...C....oWWIIIIIIIIWWo',
        '........oWWIIIIIIIIWWo',
        '.........oWWIIIIIIWWo.....C',
        '..........oWIIIIIIWo',
        '.........oQoWIIIIWoQo',
        '.........oQQooooooQQo',
      ],
    },
  ],
};

/** ナットン：わらづとから ねばり糸を のばす 納豆の子（ツチ） */
const natton: MonsterDesign = {
  size: 32,
  colors: { S: NQ.cream, T: NQ.tan, B: NQ.brown, K: NQ.bark, W: NQ.white, p: NQ.blush },
  rim: { [NQ.cream]: NQ.tan, [NQ.brown]: NQ.bark },
  layers: [
    {
      mirror: true,
      y: 1,
      rows: [
        '.......SSS.....',
        '......SSSSS....',
        '.....SSSSSSS...',
        '....SSSSSSSS...',
        '...STSTSTSTS...',
        '...SSSSSSSSS...',
        '..SSSSSSSSSS...',
        '..SSSSSSSSSS...',
        '.SSSBBBBBBSS...',
        '.SSBBBBBBBBB...',
        '.SSBBBWWBBBB...',
        '.SSBBBWoBBBB...',
        '.SSBBBBBBBBB...',
        '.SSBBpBBBBBB...',
        '.SSBBBBBBBBB...',
        '.SSBBBBBBBBB...',
        '.SSSSSSSSSSS...',
        '..STSTSTSTS....',
        '..SSSSSSSSS....',
        '...SSSSSSS.....',
        '....SSSSS......',
        '.....SSS.......',
        '.....KKK.......',
        '.....KKK.......',
        '....KK.KK......',
        '...KK...KK.....',
        '..KK.....KK....',
        '..KK.....KK....',
        '..KK.....KK....',
      ],
    },
  ],
};

/** ワラヅトムシャ：わらの よろいと ねばり糸を まとう ナットンの進化（ツチ） */
const warazutoMusha: MonsterDesign = {
  ...natton,
  colors: { ...natton.colors, G: NQ.gold, R: NQ.red },
  layers: [
    ...natton.layers,
    {
      mirror: true,
      y: 4,
      rows: ['.......GGG.....', '......GGRGG....', '.....GGGRGGG...', '......SSSSS....'],
    },
    { mirror: true, y: 15, rows: ['.GSGSGSGSGSG...', '..GSGSGSGSG....', '...GG...GG.....'] },
    { x: 2, y: 20, rows: ['WW.', '.WW', '..W', '.WW'] },
  ],
};

/** レンコンタ：穴のあいた れんこんの からだと ハスの芽（モリ） */
const renkonta: MonsterDesign = {
  size: 32,
  colors: { C: NQ.cream, A: NQ.apricot, T: NQ.tan, G: NQ.green, L: NQ.leaf, W: NQ.white, p: NQ.blush },
  rim: { [NQ.cream]: NQ.apricot, [NQ.leaf]: NQ.green },
  layers: [
    {
      mirror: true,
      y: 1,
      rows: [
        '.........LL.....',
        '.......LLLL.....',
        '......LLGL......',
        '........G.......',
        '.......CCC......',
        '.....CCCCCCC....',
        '....CCCCCCCCC...',
        '...CCCCCCCCCC...',
        '..CCCCCCCCCCC...',
        '..CCCooCCooCC...',
        '.CCCCooCCooCCC..',
        '.CCCCCCCCCCCCC..',
        '.CCCooCCCCoCCC..',
        '.CCCooCCCCoCCC..',
        '.CCCCCCWWCCCCC..',
        '.CCCCCCWoCCCCC..',
        '.CCCCCpCCCCCCC..',
        '.CCCCCCCCCCCCC..',
        '..CCCCCCCCCCC...',
        '..CCCCCCCCCCC...',
        '...CCCCCCCCC....',
        '....CCCCCCC.....',
        '.....CCCC.......',
        '......TT........',
        '.....TTTT.......',
        '....TT..TT......',
        '...TT....TT.....',
        '...TT....TT.....',
        '...TT....TT.....',
      ],
    },
  ],
};

/** ハスカブト：大きな ハスの葉を かぶとにした レンコンタの進化（モリ） */
const hasuKabuto: MonsterDesign = {
  ...renkonta,
  colors: { ...renkonta.colors, Y: NQ.gold },
  layers: [
    ...renkonta.layers,
    {
      mirror: true,
      y: 2,
      rows: [
        '.....LLLLLLLL...',
        '...LLLLLLLLLLL..',
        '..LLLLLGLLLLLL..',
        '...LLLLLLLLLL...',
        '.....GGGGG......',
      ],
    },
    { mirror: true, y: 17, rows: ['..YLYLYLYLYL....', '...LLLLLLLL.....', '....LL..LL......'] },
  ],
};

/** ホビキン：白い帆の せびれをもつ わかさぎ（ミズ） */
const hobikin: MonsterDesign = {
  size: 32,
  colors: { S: NQ.sky, A: NQ.azure, I: NQ.ice, W: NQ.white, C: NQ.cloud, G: NQ.gold, p: NQ.blush },
  rim: { [NQ.sky]: NQ.azure, [NQ.white]: NQ.cloud },
  layers: [
    {
      mirror: true,
      y: 1,
      rows: [
        '........W.......',
        '.......WWW......',
        '......WWWWW.....',
        '.....WWWWWWW....',
        '....WWWWWWWW....',
        '.....WWWWWWW....',
        '......WWWWW.....',
        '.......WWW......',
        '........W.......',
        '................',
        '......SSSS......',
        '....SSSSSSSS....',
        '..SSSSSSSSSSS...',
        '.SSSSSSSSSSSS...',
        '.SSSSSWWSSSSS...',
        '.SSSSSWoSSSSS...',
        '.SSSSSSSSSSSS...',
        '..SSSSpSSSSSS...',
        '...SSSSSSSSS....',
        '....SSSSSSS.....',
        '.....SSSSS......',
        '......SSS.......',
        '.......A........',
        '......AAA.......',
        '.....AA.AA......',
        '....AA...AA.....',
        '...AA.....AA....',
        '..AA.......AA...',
        '..AA.......AA...',
      ],
    },
  ],
};

/** ホビキマル：帆引き船のような 大帆をひろげる ホビキンの進化（ミズ） */
const hobikiMaru: MonsterDesign = {
  ...hobikin,
  colors: { ...hobikin.colors, Y: NQ.gold, B: NQ.blue },
  layers: [
    ...hobikin.layers,
    {
      mirror: true,
      y: 1,
      rows: [
        '......WWWW.....',
        '....WWWWWWWW...',
        '..WWWWWWWWWWW...',
        '.WWWWWWWWWWWW...',
        '..WWWWWWWWWWW...',
        '....WWWWWWWW...',
        '......BBBB.....',
      ],
    },
    { mirror: true, y: 14, rows: ['..YYYYYYYYYYY...', '...Y.......Y....', '....Y.....Y.....'] },
  ],
};

// ───────────────────────── 中ボス ─────────────────────────

/** ハルツゲドリ（中ボス）：つばさを いっぱいに ひろげた 大きな ウグイス。金の 王冠と するどい くちばし、かぎづめで 梅の 枝を つかむ（カゼ） */
const harutsugeDori: MonsterDesign = {
  size: 40,
  colors: {
    L: NQ.leaf,
    M: NQ.lime,
    G: NQ.green,
    S: NQ.sprout,
    W: NQ.white,
    Q: NQ.ochre,
    Y: NQ.gold,
    R: NQ.red,
    p: NQ.blush,
    K: NQ.bark,
    T: NQ.brown,
  },
  rim: { [NQ.leaf]: NQ.green, [NQ.lime]: NQ.leaf, [NQ.sprout]: NQ.lime, [NQ.brown]: NQ.bark },
  rimDepth: 2,
  layers: [
    // 本体（つばさ・王冠・するどい 目・かぎづめ）
    {
      x: 1,
      y: 1,
      rows: [
        '.............oGGGGGoGGGo',
        '.............oGGGGGoGGGo',
        '.............oGGGGGoGGGo',
        '.............oGGGRRGGGGo',
        '.............oGGGRRGGGGo',
        'oo...........oQQQQQQQQQo...........o',
        'LLoo..........ooooooooo..........ooLo',
        'LLpLoo......ooWWWLLLWWWoo......ooLpLo',
        'LpppLLoo...oWWLLLLLLLLLWWo...ooLLpppo',
        'ppYppLLLo...oLLLLLLLLLLLo...oLLLppYpp',
        'LpppLLLLLoo.oWWLLLLLLLWWo.ooLLLLLpppo',
        'LLpMLLLLLLLoLWWWoLLLoWWWLoLLLLLLLMpLo',
        'LLLMMMLLLLLLoLLWoLLLoWLLoLLLLLLMMMLLo',
        'LLLMMMMMLLGLoLLLQQYQQLLLoLGLLMMMMMLLo',
        'LLLMMMMMMMGLoLLLQQYQQLLLoLGMMMMMMMLLo',
        'LLLMMMMGMGMMGoLLLQYQLLLoGMMGMGMMMMLLo',
        'LLLMMMMGMGMMGMoLLQQQLLoMGMMGMGMMpMLLo',
        'LLLMGMGMMGMMGMooooQooooMGMMGMMGMGMLLo',
        'LLLGMMGMMGMGMoLLLoQoLLLoMGMGMMGMMGLLo',
        'LLLGMGMMGMMGoLLLLoQoLLLLoGMMGMMGMGLLo',
        'LpGMMGMMGMMoLLLLLLoLLLLLLoMMGMMGMMGLLo',
        'oLGLMGMMGMMoLLLLSSSSSLLLLoMMGMMGMLGLo',
        'oGLLGMMMGMMoLLLLSSSSSLLLLoMMGMMMGLLGo',
        '.ooLGLMGMMGoLLLSSSSSSSLLLoGMMGMLGLop',
        '...oLLLGMMoLLLLSSSSSSSLLLLoMMGLLLo',
        '....oLLLMMGoLLLSSSSSSSLLLoGMMLLLo',
        '....poLLLMMoLLSSSSSSSSSLLoMMLLLo',
        '......oLLLLoLLLSSSSSSSLLLoLLLLo',
        '.......oLLLoLLLSSSSSSSLLLoLLLo',
        '.....p..oLLooLLSSSSSSSLLooLLo..p',
        '....ppp..oo.ooLLSSSSSLLoo.oo..ppp',
        '...ppYpp....oQoLSSSSSLoQo....ppYpp',
        '.ooopppoooooYQYoooSoooYQYooooopppoooo',
        'oKKKKpKKKKKoYoYoYoooYoYoYoKKKKKpKKKKKo',
        'oKKKKKKKKKKoYoYoYoKoYoYoYoKKKKKKKKKKKo',
        '.oTTTTTTTTTToToToTTToToToTTTTTTTTTTTo',
        '..oooooooooooooooooooooooooooooooooo',
      ],
    },
  ],
};

/** ハルツゲドリ（フィールドに 立つ 32×32） */
const harutsugeDoriField: MonsterDesign = {
  size: 32,
  colors: {
    L: NQ.leaf,
    M: NQ.lime,
    G: NQ.green,
    S: NQ.sprout,
    W: NQ.white,
    Q: NQ.ochre,
    Y: NQ.gold,
    R: NQ.red,
    p: NQ.blush,
    K: NQ.bark,
    T: NQ.brown,
  },
  rim: { [NQ.leaf]: NQ.green, [NQ.lime]: NQ.leaf, [NQ.sprout]: NQ.lime },
  rimDepth: 1,
  layers: [
    // 本体
    {
      x: 1,
      y: 1,
      rows: [
        '..........oGGGGGGGo',
        '..........oGGGGGGGo',
        '..........oGGGGGGGo',
        '..........oGGRRGGGo',
        'oo........oGGRRGGGo........o',
        'Lpoo.....ooQQQQQQQoo.....oopo',
        'pppLoo..oWLoooooooLWo..ooLppp',
        'pYppLLo..oLLLLLLLLLo..oLLppYpp',
        'pppLLLLoooWWLLLLLWWoooLLLLppp',
        'LpMLLLLLoLWWoLLLoWWLoLLLLLMpo',
        'LLMMMLLLLoLLQQYQQLLoLLLLMMMLo',
        'LLMMMMMLGoLLQQYQQLLoGLMMMMMLo',
        'LLMMMMMMGoLLLQQQLLLoGMMMMMMLo',
        'LLMMMMGGMGoLLQQQLLoGMGGMMpMLo',
        'LLMMMMGGMoLoooQoooLoMGGMMMMLo',
        'LLMMGGMGMoLLLoQoLLLoMGMGGMMLo',
        'LpMGMGMGoLLLLLoLLLLLoGMGMGMLLo',
        'oLGLGMGMoLLLSSSSSLLLoMGMGLGLo',
        '.oLLGMGMoLLSSSSSSSLLoMGMGLLop',
        '..oLLLGoLLLSSSSSSSLLLoGLLLo',
        '...oLLLMoLLSSSSSSSLLoMLLLo',
        '...poLLLoLSSSSSSSSSLoLLLo',
        '.....oLLoLLSSSSSSSLLoLLo',
        '....p.oLLoLSSSSSSSLoLLo.p',
        '...ppp.oooLSSSSSSSLooo.ppp',
        '.oppYppooYoLSSSSSLoYooppYppoo',
        'oKKpppKKoYooooSooooYoKKpppKKKo',
        'oKKKpKKKoYoYoYoYoYoYoKKKpKKKKo',
        '.oTTTTTTToToToToToToTTTTTTTTo',
        '..oooooooooooooooooooooooooo',
      ],
    },
  ],
};

/** ツクバガマオウ（県ボス）：筑波山の ふたつの 峰を せおった ガマの 王。細く するどい 目、白い きばの 大きな 口、金の 王冠と むねかざり（ツチ） */
const tsukubaGamaO: MonsterDesign = {
  size: 48,
  colors: {
    T: NQ.tan,
    E: NQ.beige,
    S: NQ.sand,
    V: NQ.violet,
    L: NQ.lavender,
    G: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
    W: NQ.white,
  },
  rim: { [NQ.tan]: NQ.brown, [NQ.beige]: NQ.sand, [NQ.violet]: NQ.indigo, [NQ.gold]: NQ.ochre },
  rimDepth: 2,
  layers: [
    // 本体（みね・王冠・するどい 目・大きな 手）
    {
      x: 1,
      y: 1,
      rows: [
        '..........ooo....................ooo',
        '.........oLLVo....ooooo.ooo.....oLLVo',
        '.........oLLVo...oGGGGGoGGGo....oLLVo',
        '.........oLLVo...oGGGGGoGGGo....oLLVo',
        '........oooooooo.oGGGGGoGGGo..ooooooVo',
        '........oooooTTTooGGGRRGGGGoooTToooooo',
        '.......oooooooooToGGGRRGGGGoToooooooToo',
        '.......oTTTTToooToQQQQQQQQQoToooTTTTTTo',
        '......ooTTWWTTTTTToooooooooTTTTTTWWTTToo',
        '......ooTTWWWWTTTTTooooooooTTTTWWWWTTToo',
        '.....oLoTTTTWWWoTTTTTTTTTTTTToWWWTTTTToVo',
        '.....oLoTTTTTTWoTTTTTTTTTTTTToWTTTTTTToVo',
        '.....oLoTTTTTTTTTTTTTTTTTTTTTTTTTTTTTToVS',
        '....oLLVoTTTTTTTTTTTTTTTTTTTTTTTTTTTToVSSS',
        '.....oooTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTooS',
        '.......oTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTo',
        '.......oTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTo',
        '.......oTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTo',
        '...S...oTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTo',
        '..SSS..ooooTTTTTTTTTTTTTTTTTTTTTTTToooo',
        '...S....oTTooooooooooooooooooooooooTTo',
        '.....ooo.ooSWWSSSSSSSSSSSSSSSSSSWWSoo.ooo',
        '....oTTTo..oWTTTTTTTTTTTTTTTTTTTTWo..oTTTo',
        '...oTTTTTo..oooTTTTTTTTTTTTTTTTooo..oTTTTTo',
        '..oTTTTTToooTTTooooooooooooooooTTToooTTTTTSo',
        '.oTTTTTToSSSTTTTTooooRRoooooTTTTTTSSSoTTTSSSo',
        '.oTTTTTToSSSTTTToGGGGRRGGGGGoTTTTTSSSoTTTTSTo',
        '.oTTTTTToSSSTTTToGGGGRRGGGGGoTTTTTSSSoTTTTTTo',
        '.oTTTTTToTTTTTTToQQQQRRQQQQQoETTTTTTToTTTTTTo',
        '.oTTTTTToTTTTTTEEoooooooooooEEETTTTTToTTTTTTo',
        'oTTTTTTooTTTTTEEEEEEEEEEEEEEEEEETTTTTooTTTTTTo',
        '.oTTTToSSSTTTTEEEEEEEEEEEEEEEEEETTTTSSSoTTTTo',
        '.oTTTSoSSSTTTEEEEEEEEEEEEEEEEEEEETTTSSSoTTTTo',
        '.oTTSSSSSSTTTEEEEEEEEEEEEEEEEEEEETTTSSSoTTTTo',
        '.oTTTSTooTTTTEEEEEEEEEEEEEEEEEEEETTTTooTTTTTo',
        '.oTTTTTToTTTTEEEEEEEEEEEEEEEEEEEETTTToTTTTTTo',
        '.oTTTTTTToTSSSEEEEEEEEEEEEEEEEEESSSToTTTTTTTo',
        'oTTTTTTTTToSSSEEEEEEEEEEEEEEEEEESSSoTTTTTTTTTo',
        'oTTTTTTTTToSSSTEEEEEEEEEEEEEEEETSSSoTTTTTTTTTo',
        'TTTTTTTTTTTooTTTEEEEEEEEEEEEEETTTooTTTTTTTTTTT',
        'oToTToTToTTooooTTEEEEEEEEEEEETTooooToTToTToTTo',
        'oToTToTToTToTTTooTTTEEEEEETTTooTTToToTToTToTTo',
        '.ooTToTToTooTTToToooooooooooooTTToTooTToTToTo',
        '.oooooooooToTTToTTTTo....oTTToTTToTooooooooo',
        '..ooToTooTToTTToTTTTo....oTTToTTToTTooToTTo',
        '....oTToTTToTTToTTTo......oTToTTToTTToTTTo',
      ],
    },
  ],
};

/** ツクバガマオウ 後半（ミズ）：峰が 霞ヶ浦の 水の 青に そまり、足もとに 水が うずまく */
const tsukubaGamaOWater: MonsterDesign = {
  size: 48,
  colors: {
    T: NQ.tan,
    E: NQ.beige,
    S: NQ.sand,
    V: NQ.azure,
    L: NQ.ice,
    G: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
    W: NQ.white,
    C: NQ.sky,
  },
  rim: { [NQ.tan]: NQ.brown, [NQ.beige]: NQ.sand, [NQ.azure]: NQ.blue, [NQ.gold]: NQ.ochre },
  rimDepth: 2,
  layers: [
    // 本体（青く そまった みね・水の うず）
    {
      x: 1,
      y: 1,
      rows: [
        '..........ooo....................ooo',
        '.........oLLVo....ooooo.ooo.....oLLVo',
        '.........oLLVo...oGGGGGoGGGo....oLLVo',
        '.........oLLVo...oGGGGGoGGGo....oLLVo',
        '........oooooooo.oGGGGGoGGGo..ooooooVo',
        '........oooooTTTooGGGRRGGGGoooTToooooo',
        '.......oooooooooToGGGRRGGGGoToooooooToo',
        '.......oTTTTToooToQQQQQQQQQoToooTTTTTTo',
        '......ooTTWWTTTTTToooooooooTTTTTTWWTTToo',
        '......ooTTWWWWTTTTTooooooooTTTTWWWWTTToo',
        '.....oLoTTTTWWWoTTTTTTTTTTTTToWWWTTTTToVo',
        '.....oLoTTTTTTWoTTTTTTTTTTTTToWTTTTTTToVo',
        '.....oLoTTTTTTTTTTTTTTTTTTTTTTTTTTTTTToVC',
        '....oLLVoTTTTTTTTTTTTTTTTTTTTTTTTTTTToVCLC',
        '.....oooTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTooC',
        '.......oTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTo',
        '.......oTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTo',
        '.......oTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTo',
        '...C...oTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTo',
        '..CLC..ooooTTTTTTTTTTTTTTTTTTTTTTTToooo',
        '...C....oTTooooooooooooooooooooooooTTo',
        '.....ooo.ooSWWSSSSSSSSSSSSSSSSSSWWSoo.ooo',
        '....oTTTo..oWTTTTTTTTTTTTTTTTTTTTWo..oTTTo',
        '...oTTTTTo..oooTTTTTTTTTTTTTTTTooo..oTTTTTo',
        '..oTTTTTToooTTTooooooooooooooooTTToooTTTTTCo',
        '.oTTTTTToSSSTTTTTooooRRoooooTTTTTTSSSoTTTCLCo',
        '.oTTTTTToSSSTTTToGGGGRRGGGGGoTTTTTSSSoTTTTCTo',
        '.oTTTTTToSSSTTTToGGGGRRGGGGGoTTTTTSSSoTTTTTTo',
        '.oTTTTTToTTTTTTToQQQQRRQQQQQoETTTTTTToTTTTTTo',
        '.oTTTTTToTTTTTTEEoooooooooooEEETTTTTToTTTTTTo',
        'oTTTTTTooTTTTTEEEEEEEEEEEEEEEEEETTTTTooTTTTTTo',
        '.oTTTToSSSTTTTEEEEEEEEEEEEEEEEEETTTTSSSoTTTTo',
        '.oTTTCoSSSTTTEEEEEEEEEEEEEEEEEEEETTTSSSoTTTTo',
        '.oTTCLCSSSTTTEEEEEEEEEEEEEEEEEEEETTTSSSoTTTTo',
        '.oTTTCTooTTTTEEEEEEEEEEEEEEEEEEEETTTTooTTTTTo',
        '.oTTTTTToTTTTEEEEEEEEEEEEEEEEEEEETTTToTTTTTTo',
        '.oTTTTTTToTSSSEEEEEEEEEEEEEEEEEESSSToTTTTTTTo',
        'oTTTTTTTTToSSSEEEEEEEEEEEEEEEEEESSSoTTTTTTTTTo',
        'oTTTTTTTTToSSSTEEEEEEEEEEEEEEEETSSSoTTTTTTTTTo',
        'TTTTTTTTTTTooTTTEEEEEEEEEEEEEETTTooTTTTTTTTTTT',
        'oToTToTToTTooooTTEEEEEEEEEEEETTooooToTToTToTTo',
        'oToTToTToTToTTTooTTTEEEEEETTTooTTToToTToTToTTo',
        '.oCCCCCCoTooTTToToooooooooooooTTToTooTCCCCCCo',
        'CCCCCCCCCCToTTToTTTTo....oTTToTTToToCCCCCCCCCC',
        'CLLLLLLLLCCoTTToTTTTo....oTTToTTToTCCLLLLLLLLC',
        'CCCCCCCCCCToTTToTTTo......oTToTTToTTCCCCCCCCCC',
      ],
    },
  ],
};

/** 徳川斉昭（ラスボス）：紅白の 梅の 枝と 金の 日輪の 前立て、大きな 肩よろいと マント。軍配を かまえて 立つ（ヒカリ） */
const tokugawaNariaki: MonsterDesign = {
  size: 48,
  colors: {
    N: NQ.indigo,
    K: NQ.violet,
    D: NQ.navy,
    G: NQ.gold,
    Y: NQ.yellow,
    R: NQ.red,
    F: NQ.skinLight,
    f: NQ.skinMid,
    W: NQ.white,
    M: NQ.hairBlack,
    B: NQ.bark,
    p: NQ.blush,
  },
  rim: { [NQ.violet]: NQ.indigo, [NQ.skinLight]: NQ.skinMid, [NQ.gold]: NQ.ochre },
  rimDepth: 2,
  layers: [
    // 本体（かぶと・前立ての 梅・肩よろい・軍配）
    {
      x: 1,
      y: 1,
      rows: [
        '...........oWo..................opo',
        '..........oWWWo...............oopppo',
        '.........oWWYWWo.....oooo....oBppYppo',
        '..........oWWWoBo...oYYYYo..oBoopppo',
        '...........oWooopoooYYYYYYooBWo.opo',
        '............ooBpppBoYYRRYYBBWWWo.o',
        '.............oppYppBYRRRRBYWWYWWo',
        '.............oopppooYYRRYYoBWWWoo',
        '............oNNopoBoYYYYYYBooWoNNo',
        '...........oNNNNoNoNoYYYYooNNoNNNNo',
        '...........oNNNNNNNNNooooNNNNNNNNNo',
        '...........oNNNNNNNNNNNNNNNNNNNNNNo......ooo',
        '..........ooNNNNNNNNNNNNNNNNNNNNNNoo....oGGGo',
        '.........oNNNNNNNNNNNNNNNNNNNNNNNNNNo..oGGGGGo',
        '........oNNNNGGGGGGGGGGGGGGGGGGGGNNNNooGGGRGGG',
        '.......oNNNNNNGGGGGGGGGGGGGGGGGGNNNNNNoGGRRRGG',
        '...Y...oNNNNNNoNoooNNNNNNNoooNNoNNNNNNoGRRRRRG',
        '..YWY..oNNNNNNoooooooNNNoooooFooNNNNNNoGRRRRRG',
        '...Y...oNNNNNNoFFWWooFFFooWWFFFoNNNNNNoGRRRRRG',
        '..oGo.ooNNNNNNooFWWWoFFFoWWWFFooNNNNNNoGRRRRRG',
        '.oGGGoGGoNNNNoooFFFWoFFFoWFFFFoooNNNNoGGRRRRRG',
        'oGGGGGGGGoNNoGooFFFMMMMMMMMFFFoGGoNNoGoGGRRRGG',
        'GGGGGGGGGGooGGGooFFFFFFFFFFFFoGGGGooGGoGGGRGGG',
        'GGGGGGGGGGGGGGGoKoFFFooooFFFooGGGGGGGGGoGGGGGo',
        'ooKKKKKKKKKKKKoKKRooFFFFFFooRKooKKKKKKKKoBBGo',
        'oKKKKKKKKKKKKKKoKKKKooooooKKKKoKKKKKKKKKoBBoKo',
        'KKKKKKKKKKKKKKKKoGGGGGGGGGGGGoKKKKKKKKKKoBBoKK',
        'KKKKKKKKKKKKKKKKoKKKKKKKKKKKKoKKKKKKKKKKoBBoKK',
        'KKKKKKKKKKKKKKKKoKKKKKKKKKKKKoKKKKKKKKKKoBBoKK',
        'KKKKKKKKKKKKKKKKoKKKKKKKKKKKKoKKKKKKKKKKoBBoKK',
        'KKKooYoKKKKKKKKKoGGGGGGGGGGGGoKKKKKKKKKooBBoKK',
        'oKoKYWYoKKKKKKKoKKKKKKKKKKKKKKoKKKKKKKoKoBBYKo',
        '.oKKKYKKoKKKKKoKKKKKKKKKKKKKKKKoKKKKKoKKoBYWY',
        '.oKKKKKKoKKKKoKKKKKKKKKKKKKKKKKKoKKKKoKKoBBYo',
        'oKKKKKKKKoKoooGGGGGGGGGGGGGGGGGGoooKoKKKoBBoKo',
        'oKKKKKKKKooDDoKKKKKKKKKKKKKKKKKKoDDooKKKoBBoKo',
        'oKKKKKKKKoDDDoKKKKKKKKKKKKKKKKKKoDDDoKKKoBBoKo',
        'oKKKKKKKKoDDDoKKKKKKKKKKKKKKKKKKoDDDoKKKoBBoKo',
        'oKKKKKKKKoooooGGGGGGGGGGGGGGGGGGoooooKKKoBBoKo',
        'oKKKKKKKKoGKKoKKKKKKKKKKKKKKKKKKoKGKoKKKoBBoKo',
        'oKKKKKKKKoGKKoKKKKKKKKKKKKKKKKKKoKGKoKKKoBBoKo',
        '.oKFFFFKooGKKKooooooooooooooooooKKGKooKFoBBoo',
        '.oFFFFFFooGKKKGKKKGKKKGKKKGKKKGKKKGKooFFFooFo',
        'oFFFFFFFFoGKKKNNNNNNKKGKKKNNNNNNKKGKoFFFFFFFFo',
        'ooFFFFFFooGKKKNNNNNNKKGKKKNNNNNNKKGKooFFFFFFoo',
        '.ooFFFFoooooooNNNNNNooooooNNNNNNoooooooFFFFoo',
      ],
    },
  ],
};

export const IBARAKI: Readonly<Record<string, MonsterDesign>> = {
  'ibaraki-nemofin': nemofin,
  'ibaraki-aozora-hime': aozoraHime,
  'ibaraki-natton': natton,
  'ibaraki-warazuto-musha': warazutoMusha,
  'ibaraki-renkonta': renkonta,
  'ibaraki-hasu-kabuto': hasuKabuto,
  'ibaraki-hobikin': hobikin,
  'ibaraki-hobiki-maru': hobikiMaru,
  'ibaraki-midboss-harutsuge-dori': harutsugeDori,
  'ibaraki-midboss-harutsuge-dori.field': harutsugeDoriField,
  'ibaraki-boss-tsukuba-gama-o': tsukubaGamaO,
  'ibaraki-boss-tsukuba-gama-o.p0': tsukubaGamaOWater,
  'ibaraki-lastboss-tokugawa-nariaki': tokugawaNariaki,
};
