/** 鹿児島県の モンスター（手描き。docs/06 §4・§6.3〜6.5 の 規格） */
import { NQ } from '../palette';
import type { MonsterDesign } from './design';

const one = (rows: string[]) => [{ rows }];
const half = (rows: string[]) => [{ mirror: true, rows }];

/** ロッパクブー：つやつやの 黒豚。鼻の 先と 4 本の 足が 白い「六白」。さつまいもを かかえる（ツチ） */
const roppakuBoo: MonsterDesign = {
  size: 32,
  colors: {
    N: NQ.night,
    L: NQ.slate,
    W: NQ.white,
    B: NQ.berry,
    C: NQ.cream,
    G: NQ.leaf,
    p: NQ.blush,
  },
  rim: { [NQ.white]: NQ.cloud },
  layers: one([
    '................................',
    '................................',
    '................................',
    '................................',
    '.......NN..............NN.......',
    '.......NLNN....NN....NNLN.......',
    '.......NLLNLLNNNNNNLLNLLN.......',
    '........NNLNNNNNNNNNNLNN........',
    '........NLNNNNNNNNNNNNLN........',
    '........NNNNNNNNNNNNNNNN........',
    '.......NNNWWNNNNNNNNWWNNN.......',
    '.......NNNWoNNNNNNNNoWNNN.......',
    '.......NNNWoNNNNNNNNoWNNN.......',
    '.......NNNNNNWWWWWWNNNNNN.......',
    '.......NNNNNWWWWWWWWNNNNN.......',
    '.......NppNNWWoWWoWWNNppN.......',
    '........NNNNWWoWWoWWNNNN........',
    '........NNNNNWWWWWWNNNNN........',
    '.......NNNNNNNNNNNNNNNNNN.......',
    '......NNLNNNNNNooNNNNNNLNN......',
    '......NLNNNNNNNNNNNNGGNNLN......',
    '.....NNLNNNNNNNNNNBBBBNNNNN.....',
    '.....NNNNNNNNNNNNBBpBBCNNNN.....',
    '.....NNNNNNNNNNNNNBBBBNNNNN.....',
    '......NNNNNNNNNNNNNNNNNNNN......',
    '......NNNNNNNNNNNNNNNNNNNN......',
    '.......NNNNNNNNNNNNNNNNNN.......',
    '........NNNNNNNNNNNNNNNN........',
    '........WWWWWNNNNNNWWWWW........',
    '........WWWWWNNNNNNWWWWW........',
    '................................',
    '................................',
  ]),
};

/** クロガネブー（ロッパクブーの しんか）：黒がねの かぶとと かたあてを つけた 大きな 黒豚。六白、きりっと まゆ（ツチ） */
const kuroganeBoo: MonsterDesign = {
  size: 32,
  colors: {
    N: NQ.night,
    S: NQ.silver,
    G: NQ.gray,
    W: NQ.white,
    B: NQ.brown,
    Y: NQ.gold,
    p: NQ.blush,
  },
  rim: { [NQ.white]: NQ.cloud, [NQ.silver]: NQ.gray },
  layers: one([
    '................................',
    '................................',
    '......N......SSSSSS......N......',
    '.......NN.WWSSSSSSSSWW.NN.......',
    '.......NNWSSSSSSSSSSSSWNN.......',
    '.......SWSSSSSSSSSSSSSSWS.......',
    '.......SSSGSSGSSSSGSSGSSS.......',
    '.......SSSSSSSSSSSSSSSSSS.......',
    '......GGGGGGGGGGGGGGGGGGGG......',
    '........NooNNNNNNNNNNooN........',
    '.......NNNWWNNNNNNNNWWNNN.......',
    '.......NNNWoNNNNNNNNoWNNN.......',
    '.......NNNWoNNNNNNNNoWNNN.......',
    '.......NNNNNNWWWWWWNNNNNN.......',
    '.......NNNNNWWWWWWWWNNNNN.......',
    '.....SSNpNNNWWoWWoWWNNNpNSS.....',
    '...SSSSSNNNNWWoWWoWWNNNNSSSSS...',
    '...SSWSSNNNNNWWWWWWNNNNNSSWSS...',
    '..SSSGGGSNNNNoNWWNoNNNNSGGGSSS..',
    '...SGSSSSSNNNNooooNNNNSSSSSGS...',
    '...SSSSSSSNNNNNNNNNNNNSSSSSSS...',
    '.....SSSNNNNNNNNNNNNNNNNSSS.....',
    '.....NNNNNNNNNNNNNNNNNNNNNN.....',
    '.....NNNBBBBBBBYYBBBBBBBNNN.....',
    '.....NNNBBBBBBBYYBBBBBBBNNN.....',
    '......NNNNNNNNNNNNNNNNNNNN......',
    '......NNNNNNNNNNNNNNNNNNNN......',
    '.......NNNNNNNNNNNNNNNNNN.......',
    '.......WWWWWWNNNNNNWWWWWW.......',
    '.......WWWWWWNNNNNNWWWWWW.......',
    '................................',
    '................................',
  ]),
};

/** マルダイコン：まんまるで 大きな 桜島大根。上は うすい みどり、3 まいの 葉（モリ） */
const maruDaikon: MonsterDesign = {
  size: 32,
  colors: {
    W: NQ.white,
    c: NQ.cloud,
    M: NQ.sprout,
    G: NQ.green,
    L: NQ.leaf,
    F: NQ.forest,
    p: NQ.blush,
  },
  rim: { [NQ.white]: NQ.cloud, [NQ.sprout]: NQ.lime },
  layers: one([
    '................................',
    '..............LLLL..............',
    '.........GGG..LLLL..GGG.........',
    '..........GFG.LLLL.GFG..........',
    '...........GFG.LL.GFG...........',
    '............FGGLLGGF............',
    '.............FGLLGF.............',
    '..............FLLF..............',
    '...............LL...............',
    '..............MMMM..............',
    '...........MMMMMMMMMM...........',
    '.........WMMMMMMMMMMMMW.........',
    '........WWMMMMMMMMMMMMWW........',
    '.......WWWWWWMMMMMMWWWWWW.......',
    '......WWWWWWWWWWWWWWWWWWWW......',
    '......WWWWWWWWWWWWWWWWWWWW......',
    '.....WWWWWWWWWWWWWWWWWWWWWW.....',
    '.....WWWWWWoWWWWWWWWoWWWWWW.....',
    '.....WWWWWWoWWWWWWWWoWWWWWW.....',
    '.....WWWppWWWWWWWWWWWWppWWW.....',
    '.....WWWWWWWWWoWWoWWWWWWWWW.....',
    '.....WWWWWWWWWWooWWWWWWWWWW.....',
    '.....WccWWWWWWWWWWWWWWWWccW.....',
    '......WWWWWWWWWWWWWWWWWWWW......',
    '......WWWWWWWWWWWWWWWWWWWW......',
    '......ccWWWWWWWWWWWWWWWWcc......',
    '........WWWWWWWWWWWWWWWW........',
    '.........WWWWWWWWWWWWWW.........',
    '...........WWWWWWWWWW...........',
    '..............WWWW..............',
    '...............WW...............',
    '................................',
  ]),
};

/** ダイコンショウグン（マルダイコンの しんか）：葉の くわがたの かぶとと 葉の じんばおり。どっしり うでぐみ（モリ） */
const daikonShogun: MonsterDesign = {
  size: 32,
  colors: {
    W: NQ.white,
    c: NQ.cloud,
    M: NQ.sprout,
    G: NQ.green,
    L: NQ.leaf,
    F: NQ.forest,
    p: NQ.blush,
  },
  rim: { [NQ.white]: NQ.cloud, [NQ.sprout]: NQ.lime, [NQ.green]: NQ.forest },
  layers: one([
    '................................',
    '......GGG.....LLLL.....GGG......',
    '......GFGG....LLLL....GGFG......',
    '.......GFFG...LLLL...GFFG.......',
    '.........GFGG..LL..GGFG.........',
    '..........GFFG.LL.GFFG..........',
    '............GFGLLGFG............',
    '.............GGLLGG.............',
    '.............MMMMMM.............',
    '..........MMMMMMMMMMMM..........',
    '.........MMMMMMMMMMMMMM.........',
    '........WWMMMMMMMMMMMMWW........',
    '.......WWWWWMMMMMMMMWWWWW.......',
    '......WWWWWWWWWWWWWWWWWWWW......',
    '.....WWWWooWWWWWWWWWWooWWWW.....',
    '..GGGWWWWWWWWWWWWWWWWWWWWWWGGG..',
    '.GGGGWWWWWWoWWWWWWWWoWWWWWWGGGG.',
    '.GGGWWWWWWWoWWWWWWWWoWWWWWWWGGG.',
    '.GFFWWWWpWWWWWWWWWWWWWWpWWWWFFG.',
    '.GGGWWWWGFWWWoWWWWoWWWWWWWWWGGG.',
    '.GGGGWWWGGFFWWooooWWWWWWWWWGGGG.',
    '.GGGFWWWWGGGFWWWWWWWWWWWWWWFGGG.',
    '.GFFGWWWWWWGGFFWWWWWWWWWWWWGFFG.',
    '.GGGGGWWWWWWWGGFWWWWWWWWWWGGGGG.',
    '.GGGGFWWWWWWWWGGFFWWWWWWWWFGGGG.',
    '..GGFGGWWWWWWWWWGGFFWWWWWGGFGG..',
    '..FFGGG.WWWWWWWWWGGGFWWW.GGGFF..',
    '..GG.....WWWWWWWWWWGGFF.....GG..',
    '...........WWWWWWWWWWGGF........',
    '..............WWWW..............',
    '...............WW...............',
    '................................',
  ]),
};

/** ナベヅルン：出水に わたって くる ナベヅル（左むき）。灰色の からだ、白い 首、頭の てっぺんが 赤い（カゼ） */
const nabezurun: MonsterDesign = {
  size: 32,
  colors: {
    g: NQ.gray,
    L: NQ.slate,
    N: NQ.night,
    W: NQ.white,
    c: NQ.cloud,
    K: NQ.hairBlack,
    R: NQ.red,
    E: NQ.sand,
    p: NQ.blush,
  },
  rim: { [NQ.gray]: NQ.slate, [NQ.white]: NQ.cloud },
  layers: one([
    '................................',
    '............R...................',
    '...........RRR..................',
    '..........KKKKK.................',
    '.........WWoWWWW................',
    '........EEWooWWW................',
    '.....EEEEEWWWWWW................',
    '...EEEE...WWWpW.................',
    '..........WWWWW.................',
    '..........WWWWW.................',
    '..........WWWWW.............LL..',
    '..........WWWWW.ggggggg...LLNN..',
    '...........WWWWggggccgggLNNNLL..',
    '...........WWWWWggcggggLLLLLNN..',
    '...........WWWWWgggggggLLLNNL...',
    '...........gWWWWgggggggLLLLLL...',
    '..........ggWWWLgggggggLLLLLL...',
    '..........ggWWggggggggggLLLLg...',
    '..........ggWgggggggggggLLLgg...',
    '...........gggggggggggggLggg....',
    '...........gggggLggggggggggg....',
    '............ggggggggggggggg.....',
    '..............gggggLggLgg.......',
    '................gNgggNg.........',
    '.................N...N..........',
    '.................N...N..........',
    '.................N...N..........',
    '.................N...N..........',
    '.................N...N..........',
    '.................N...N..........',
    '................NN..NN..........',
    '................................',
  ]),
};

/** ワタリヅル（ナベヅルンの しんか）：大きな つばさを ひろげて 海を こえる ナベヅル。まわりに 風（カゼ） */
const watariZuru: MonsterDesign = {
  size: 32,
  colors: {
    g: NQ.gray,
    L: NQ.slate,
    N: NQ.night,
    W: NQ.white,
    K: NQ.hairBlack,
    R: NQ.red,
    E: NQ.sand,
    A: NQ.aqua,
    M: NQ.mint,
    p: NQ.blush,
  },
  rim: { [NQ.gray]: NQ.slate, [NQ.white]: NQ.cloud },
  layers: one([
    '................................',
    '................................',
    '................................',
    '.......NN..................LN...',
    '....LNNLLNN...............LLLN..',
    '.....LLNNLLRWW............LNLLN.',
    '......LLLWRRRWW..........LLLNL..',
    '.......LWKKKKKWW........LLNLLN..',
    '........WWooWWWW........LLLNL...',
    '.......EEWWooWWWL......LLLLLN...',
    '.....EEEEWWWWWWWLLL...LLLLLL....',
    '...EEEE...WWWpWLLLLL.LLLLLL.....',
    '..........WWWWWLLgggggLLLLL.....',
    '..........WWWWWggggggggggL......',
    '..........WWWWWWgggggggggg......',
    '...........WWWWWggggggggggg.....',
    '...........WWWWWWggggggggggg....',
    '...........gWWWWgggggggggggg....',
    '...........gWWWggggggggggggg....',
    '....AA.....gWggggggggggggggg....',
    '...A..A....ggggggggggggggggg....',
    '............gggggggggggggggM....',
    '.............ggggggggggggg..MM..',
    '..A...........ggggggggggg.......',
    '...AA............gNgNg....M.....',
    '...................NNNN....MM...',
    '.....................N.N........',
    '......................NNNN......',
    '........................N.N.....',
    '................................',
    '................................',
    '................................',
  ]),
};

/** チャッパ：茶葉のからだに 小さな急須をのせた お茶の子（ミズ） */
const chappa: MonsterDesign = {
  size: 32,
  colors: { L: NQ.leaf, G: NQ.green, M: NQ.lime, B: NQ.brown, T: NQ.tan, W: NQ.white, p: NQ.blush },
  rim: { [NQ.leaf]: NQ.green, [NQ.brown]: NQ.bark },
  layers: [
    {
      mirror: true,
      y: 1,
      rows: [
        '.......BBB......',
        '.....BBBBBBB....',
        '....BBBBBBBBB...',
        '...BBBBBBBBBBB..',
        '...BBBTBBBBBBB..',
        '....BBBBBBBBB...',
        '.....BBBBBBB....',
        '.......BBB......',
        '........B.......',
        '......LLLLL.....',
        '....LLLLLLLLL...',
        '...LLLLLLLLLL...',
        '..LLLLLLLLLLLL..',
        '.LLLLLLWWLLLLLL.',
        '.LLLLLLWoLLLLLL.',
        '.LLLLLLLLLLLLLL.',
        '.LLLLLpLLLLLLLL.',
        '.LLLLLLLLLLLLLL.',
        '..LLLLLLLLLLLL..',
        '...LLLLLLLLLL...',
        '....LLLLLLLL....',
        '.....LLLLLL.....',
        '......LLLL......',
        '.......GG.......',
        '......GGGG......',
        '.....GG..GG.....',
        '....GG....GG....',
        '...GG......GG...',
        '...GG......GG...',
      ],
    },
  ],
};

/** シンチャドウ：大きな急須と 新茶の湯けむりをまとう チャッパの進化（ミズ） */
const shinchaDou: MonsterDesign = {
  ...chappa,
  colors: { ...chappa.colors, C: NQ.cloud, Y: NQ.gold },
  layers: [
    ...chappa.layers,
    {
      mirror: true,
      y: 1,
      rows: ['....C.....C.....', '...CCC...CCC....', '....C.....C.....', '......CC........'],
    },
    {
      mirror: true,
      y: 5,
      rows: ['....BBBBBBBB....', '..BBBBBBBBBBBB..', '.BBBYBBBBBYBBB..', '..BBBBBBBBBBBB..'],
    },
    { mirror: true, y: 18, rows: ['..YLYLYLYLYLY...', '...LLLLLLLLLL...', '....LL....LL....'] },
  ],
};

/**
 * ツボムシャ（中ボス）：薩摩焼の つぼが 武者に なった。黒もんの ふたの かぶと、白もんの つぼの からだ。
 * 金の ふちどりの 赤い 花と みどりの 葉の 絵つけ、こまかい ひび。頭に 王冠（ツチ → ヒノ）
 */
const tsuboMusha: MonsterDesign = {
  size: 40,
  colors: {
    C: NQ.cream,
    S: NQ.sand,
    t: NQ.tan,
    N: NQ.night,
    L: NQ.slate,
    Y: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
    G: NQ.green,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.cream]: NQ.sand },
  rimDepth: 2,
  layers: half([
    '....................',
    '................Y..Y',
    '................YY.Y',
    '................YYYY',
    '................YYYR',
    '................QQQQ',
    '................LLNN',
    '..............NLNNNN',
    '.............NNNNNNN',
    '.............NNNNNNN',
    '..............NNNNNN',
    '.............CCCNNNN',
    '.............YYYYYYY',
    '...............CCCCC',
    '...............CCCCC',
    '...............CCCCC',
    '...............CCCCC',
    '..........YYYYYYYYYY',
    '.............CNNNCCC',
    '..........WWCCCWWoCC',
    '........CWCCCCCWWoCC',
    '......CCWCCtCCCWWoCC',
    '....CCCCCCCCtCCWooCC',
    '....CCCCCCCCCpCCCCCC',
    '...CCCCCCCCCCCCCCooo',
    '...CtCCCCCCCCCCCCCCC',
    '...CtCCCCCCCCCCCCCCC',
    '...CCtCCCCYYCCCCCCCC',
    '...CCCCCCYRRYGCCCCCC',
    '..CCCCCCCYRRYGGCCCCC',
    '..CCCCCCCCYYCCCCYCCC',
    '...CCCC.CGGCCCCYRYCC',
    '........GGCCCCCCYCtC',
    '..........CCtCCCCtCC',
    '........YYYYYtYYYYYY',
    '.............CCCCCCC',
    '..............SSSSSS',
    '..............SSSSSS',
    '..............SSSSSS',
    '....................',
  ]),
};

/** ツボムシャ（フィールドに 立つ 32×32） */
const tsuboMushaField: MonsterDesign = {
  size: 32,
  colors: {
    C: NQ.cream,
    S: NQ.sand,
    N: NQ.night,
    Y: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
    G: NQ.green,
    W: NQ.white,
  },
  rim: { [NQ.cream]: NQ.sand },
  layers: half([
    '................',
    '.............Y..',
    '.............YY.',
    '.............YYY',
    '.............YYR',
    '.............QQQ',
    '...........NNNNN',
    '...........NNNNN',
    '............NNNN',
    '...........CCCNN',
    '...........YYYYY',
    '............CCCC',
    '............CCCC',
    '............CCCC',
    '........YYYYYYYY',
    '.........CCCCCCC',
    '........CCCCWWCC',
    '.......CCCCCWoCC',
    '......CCCCCCooCC',
    '......CCCCCCCCCC',
    '......CCCCCCCCoo',
    '.....CCCCYCCCCCC',
    '.....CCCYRYCCCCC',
    '......CCCYCGCCCC',
    '......CCCCCGGCCC',
    '.......CCCCCCCCC',
    '........CCCCCCCC',
    '.......YYYYYYYYY',
    '...........CCCCC',
    '...........SSSSS',
    '...........SSSSS',
    '................',
  ]),
};

/**
 * サクラジマグマ（県ボス）：桜島の 火山の 力から 生まれた 巨人。火口が 光る 山の 頭、もくもくの けむり、
 * マグマの ひびが 走る 岩の からだと 大きな こぶし。王冠は 火口の 上（ヒノ → ツチ）
 */
const sakurajimaguma: MonsterDesign = {
  size: 48,
  colors: {
    B: NQ.brown,
    K: NQ.bark,
    T: NQ.tan,
    V: NQ.vermilion,
    O: NQ.orange,
    C: NQ.cream,
    g: NQ.gray,
    s: NQ.silver,
    Y: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
    W: NQ.white,
  },
  rim: { [NQ.brown]: NQ.bark, [NQ.gray]: NQ.slate },
  rimDepth: 2,
  layers: half([
    '........................',
    '.....................ggg',
    '...................ggssg',
    '..................ggsggg',
    '..................gggggg',
    '.................gggYggY',
    '................ggsYYgYY',
    '................gggYYYYY',
    '................gggYYYYR',
    '...................QQQQQ',
    '.................BOCCCCC',
    '.................BOOOOOO',
    '.................TBBBBBB',
    '................KKKBBBBB',
    '......B.........TBBKKKKB',
    '.....BBT.......BBBWWoBBB',
    '.....BTBBBB....TBBWWoBBB',
    '...BBBBBBBBBB.BBBBWWoBBB',
    '..BBBTBBBBBBBBBBBBWooBBB',
    '..BBBBBBBVBBBBVBBBBBBBBB',
    '..BBBBBBBBOBBBBOBBBBBBBB',
    '..BBBBBBBBVBBBBVBBBBBBBB',
    '..BBBBBBBBBVBBBBVBBVVVVV',
    '..BBBBBBBBBBBBBBBBBBOOOO',
    '...BBBBBBBBBBBBBBBBBBBBB',
    '...BBBBBBBBBBBBBBBBBBBBB',
    '...BBBBB..BBBBBBBBBBBBBB',
    '...BBBVBB..BBBBBBBBBBBBB',
    '..BTBBVBBBBBBBBBBBBBVBBB',
    '..BTBVBBBBBBBBBBBBBBVBBB',
    '..BBBOBBBBBBBVBBBBBBVBBB',
    '..BBBVBBBBBBBBVBBBBBBVBB',
    '..BBVBBBBBBBBBBOBBBBBVBB',
    '..BBVBBBBBBBBBBBOBBBBBBB',
    '..BBBBBBBBBBBBBBBVBBBBBB',
    '..BBBBBBBBBBBBBBBVBBBBBB',
    '.BBVBBBBBBBBBBBBVBBBBBBB',
    '.BBBVVBBBBBBBBBBVBBBBBBB',
    '.BBBBBVBBB.BBBBVBBBBBBBB',
    '..BBBBBBB...BBBVBBBBBBBB',
    '...BBBBB......BBBBBBBBBB',
    '.............BBBBBBBBBBB',
    '.............BBBBBBBBBBB',
    '.............BBBBBBBB...',
    '............KKKKKKKKKK..',
    '............KKKKKKKKKK..',
    '........................',
    '........................',
  ]),
};

/** サクラジマグマ 後半（ツチ）：大きな 噴火で けむりが ふくらみ、体に 火山灰が つもって 灰色に。灰が ふりそそぐ */
const sakurajimagumaAsh: MonsterDesign = {
  ...sakurajimaguma,
  colors: { ...sakurajimaguma.colors, B: NQ.gray, T: NQ.silver, K: NQ.slate },
  rim: { [NQ.gray]: NQ.slate },
  layers: [
    ...sakurajimaguma.layers,
    { x: 2, y: 12, rows: ['s...s', '.....', '..s..', '.....', 's...s'] },
    { x: 41, y: 10, rows: ['s...s', '.....', '..s..', '.....', 's...s'] },
  ],
};

/** 西郷隆盛：大きな 目と ふとい まゆ、みじかい かみ、薩摩がすりの きものと 金の おび。右に 赤い ひもの 犬（ツチ） */
const saigo: MonsterDesign = {
  size: 48,
  colors: {
    F: NQ.skinLight,
    f: NQ.skinMid,
    H: NQ.hairBlack,
    D: NQ.navy,
    d: NQ.denim,
    W: NQ.white,
    Y: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
    C: NQ.cream,
    B: NQ.brown,
    p: NQ.blush,
  },
  rim: { [NQ.skinLight]: NQ.skinMid, [NQ.cream]: NQ.sand },
  rimDepth: 2,
  layers: one([
    '................................................',
    '................................................',
    '................................................',
    '....................HHHHHHHH....................',
    '.................HHHHHHHHHHHHHH.................',
    '................HHHHHHHHHHHHHHHH................',
    '...............HHHHHHHHHHHHHHHHHH...............',
    '...............HHHHHHHHHHHHHHHHHH...............',
    '...............HHHHHHHHHHHHHHHHHH...............',
    '...............HHHHHHHHHHHHHHHHHH...............',
    '...............HHHHHHHHHHHHHHHHHH...............',
    '...............HHFWWWHHHHHHWWWFHH...............',
    '...............HHWWooFHHHHFooWWHH...............',
    '..............FHHWWooFFFFFFooWWHHF..............',
    '..............FFFFWWWFFFFFFWWWFFFF..............',
    '..............fFFFFFFFFFFFFFFFFFFf..............',
    '...............FFpFFFFFffFFFFFpFF...............',
    '................FFFFFFfFFfFFFFFF................',
    '.................FFFFFFFFFFFFFF.................',
    '.................FFFooooooooFFF.................',
    '...................FFFFFFFFFF...................',
    '....................FFFFFFFF....................',
    '..............DDDWFDFFFFFFFFDFWDDD..............',
    '...........DDDDDDDWFDDDDDDDDFWDDDDDDD...........',
    '.........DDDDDDDDDDWFDDDDDDFWDDDDDDDDDD.........',
    '........DDdDDdDDdDDdFDdDDdDFdDDdDDdDDdDD........',
    '......DDDDDDDDDDDDDDWFDDDDFWDDDDDDDDDDDDDD......',
    '.....DDDDDDDDDDDDDDDDWFDDFWDDDDDDDDDDDDDDDD.....',
    '....DDDDDDdDDdDDdDDdDDWFFWDDdDDdDDdDDdDCDDDC....',
    '....DDDDDDDDDDDDDDDDDDDWWDDDDDDDDDDDDDDCCCCC....',
    '....DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCC....',
    '....DDDDDDYYYYYYYYYYYYYYYYYYYYYYYYYYYYCCCCCC....',
    '....DDDDDDYYYYYYYYYYYYYYYYYYYYYCCYYYYYCCoCoC....',
    '....DDDDDDQQQQQQQQQQQQQQQQQQQQQQCQQQQQCCCCCC....',
    '....DDDDDDdDDdDDdDDdDDdDDdDDdDDdCCdDCCCCCoCC....',
    '....DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCRRRRRD....',
    '....DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCCCRCCCCD....',
    '....DDDDDDdDDdDDdDDdDDdDDdDDdDDdDCCCCCRCCCCC....',
    '.....FFFFFFDDDDDDDDDDDDDDDDDDDDDDCCCCRCCCCCC....',
    '.....FFFFFFDDDDDDDDDDDDDDDDDDDDDDDCCCRCCCCC.....',
    '.....FFFFFFDDdDDdDDdDDdDDdDDdDDdDDdCCRCCCCF.....',
    '.........DDDDDDDDDDDDDDDDDDDDDDDDDDCCCCCCC......',
    '.........DDDDDDDDDDDDDDDDDDDDDDDDDDCCDD.CC......',
    '.........DdDDdDDdDDdDDdDDdDDdDDdDDdCCdD.CC......',
    '............FFFFFFF..........FFFFFFF............',
    '............FFFFFFF..........FFFFFFF............',
    '...........BBBBBBBBB........BBBBBBBBB...........',
    '................................................',
  ]),
};

export const KAGOSHIMA: Readonly<Record<string, MonsterDesign>> = {
  'kagoshima-roppaku-boo': roppakuBoo,
  'kagoshima-kurogane-boo': kuroganeBoo,
  'kagoshima-maru-daikon': maruDaikon,
  'kagoshima-daikon-shogun': daikonShogun,
  'kagoshima-nabezurun': nabezurun,
  'kagoshima-watari-zuru': watariZuru,
  'kagoshima-chappa': chappa,
  'kagoshima-shincha-dou': shinchaDou,
  'kagoshima-midboss-tsubo-musha': tsuboMusha,
  'kagoshima-midboss-tsubo-musha.field': tsuboMushaField,
  'kagoshima-boss-sakurajimaguma': sakurajimaguma,
  'kagoshima-boss-sakurajimaguma.p0': sakurajimagumaAsh,
  'kagoshima-lastboss-saigo-takamori': saigo,
};
