/** 京都府の モンスター（手描き。docs/06 §4・§6.3〜6.5 の 規格） */
import { NQ } from '../palette';
import type { MonsterDesign } from './design';

/** チャツミン：宇治茶の 若葉の せい。頭に 一芯二葉（芽と 2 まいの 葉）、赤い たすき、茶つみの かご（モリ） */
const chatsumin: MonsterDesign = {
  size: 32,
  colors: {
    L: NQ.leaf,
    G: NQ.green,
    M: NQ.lime,
    S: NQ.sprout,
    R: NQ.red,
    T: NQ.tan,
    B: NQ.brown,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.leaf]: NQ.green, [NQ.tan]: NQ.brown, [NQ.red]: NQ.brick },
  layers: [
    {
      x: 5,
      y: 4,
      rows: [
        '..GG......MM......GG',
        '...GLLG...MM...GLLG',
        '...GGGLL..MM..LLGGG',
        '....GGGGL.MM.LGGGG',
        '......GGGGMMGGGG',
        '',
        '.......LLLLLLLL',
        '.....SLLLLLLLLLLL',
        '...LSLLLLLLLLLLLLLL',
        '..LSLLLLLLLLLLLLLLLL',
        '..LLLWWLLLLLLLLWWLLL',
        '.RLLLWoLLLLLLLLoWLLLL',
        'LRRLLWoLLLLLLLLoWLLLLL',
        'LLRppLLLLLLLLLLLLppLLG.G',
        'LLLLRRLLLoLLoLLLLLLLGGGGG',
        'LLLLLRRMMMooMMMLLLLTTTTTT',
        'LLLLLMRRRMMMMMMMMLLTBTBTB',
        'LLLLLMMMRRMMMMMMMLLTTTTTT',
        'LLLLMMMMMRRMMMMMMMLTBTBTB',
        '.LLLMMMMMMRRRMMMMMLLTTTTT',
        '.LLLMMMMMMMMRRMMMMLLL',
        '..LLLMMMMMMMMRRMMLLL',
        '...LLLMMMMMMMMRRRLL',
        '....LLLLMMMMMMLLRR',
        '.....GLLLLLLLLLLG',
        '.....GGGG....GGGG',
      ],
    },
  ],
};

/** チャセンシ：チャツミンが しんか。一芯二葉の まえだてと 白い はちまき、X の たすき、抹茶の 茶わんの たてと 竹の 茶せん（モリ） */
const chasenshi: MonsterDesign = {
  size: 32,
  colors: {
    L: NQ.leaf,
    G: NQ.green,
    M: NQ.lime,
    K: NQ.bark,
    C: NQ.cream,
    T: NQ.tan,
    R: NQ.red,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.leaf]: NQ.green, [NQ.red]: NQ.brick, [NQ.white]: NQ.cloud },
  layers: [
    {
      x: 1,
      y: 2,
      rows: [
        '..........................C',
        '......G................G.CTC',
        '......GLG............GLGCTCTC',
        '......GGLGG...MM...GGLGGCTCTC',
        '.......GGLL...MM...LLGG.CTCTC',
        '........GGGL..MM..LGGG...CTC',
        '.........GGGL.MM.LGGG.....T',
        '...........GGGMMGGG.......T',
        'WW.........LLLLLLLL.......T',
        '.WWW.....WWWWWWWWWWWW.....T',
        'WW.....WWWWWWWWWWWWWWWW...T',
        '......LLoooLLLLLLLLoooLL..T',
        '......LLLWWoLLLLLLoWWLLL..T',
        '.....LLLLWoLLLLLLLLoWLLLL.T',
        '....LLLLLWoLLLLLLLLoWLLLLLT',
        '....LLLppLLLLLLLLLLLLppLLLLL',
        '.MMMMMMLLLLLoLLLLoLLLLLLLLLLL',
        'KMLMMLMKLLLLMooooMLLLLLLRLLLL',
        'KKKKKKKKLLMMMWMMMMMMLLRRLL',
        'KKKKKKKKRRMMMMMMMMMMRRLLLL',
        '.KKKKKKLMMRRMMMMMMRRMMLLLL',
        '..KKKKLLMMMMRRMMRRMMMMLLL',
        '.....LLLMMMMMMRRMMMMMMLLL',
        '......LLLMMMRRMMRRMMMLLL',
        '.......LLLRRMMMMMMRRLLL',
        '........RRLLMMMMMMLLRR',
        '.........LLLLLLLLLLLL',
        '.........GGGLLLLLLGGG',
      ],
    },
  ],
};

/** フナヤドカリ：伊根の 舟屋を せおった ヤドカリ。切妻の 屋根と 木の かべ、1かいの 船の 入口から 顔と はさみを 出す（ミズ） */
const funayadokari: MonsterDesign = {
  size: 32,
  colors: {
    N: NQ.slate,
    D: NQ.night,
    B: NQ.tan,
    K: NQ.brown,
    Y: NQ.yellow,
    V: NQ.vermilion,
    A: NQ.apricot,
    W: NQ.white,
    S: NQ.sky,
    p: NQ.blush,
  },
  rim: { [NQ.vermilion]: NQ.brick, [NQ.tan]: NQ.brown },
  layers: [
    {
      x: 1,
      y: 3,
      rows: [
        '..............NN',
        '.............NNNN',
        '............DDDDDD',
        '..........NNNNNNNNNN',
        '.........DDDDDDDDDDDD',
        '.......NNNNNNNNNNNNNNNN',
        '......DDDDDDDDDDDDDDDDDD',
        '.....NNNNNNNNNNNNNNNNNNNN',
        '.....BKBBKBBYYKKYYKBBKBBB',
        '.....BKBBKBBYYKKYYKBBKBBB',
        '.....KKKKKKKKKKKKKKKKKKKK',
        '.....BKBKKKKKKKKKKKKKKBBB',
        '.....BKBBDDDDDDDDDDDDKBBB',
        '.....BKBBDWWDDDDDDWWDKBBB',
        '.....BKBBDWoDDDDDDoWDKBBB',
        '.VVV.BKBBDWoDDDDDDoWDKBBB.VVV',
        'VVAVVBKBBDVVDVVVVDVVDKBBBVVAVV',
        'VV..VBKBBDVVVVVVVVVVDKBBBV..VV',
        'VVVVVVKBVVVVAAAAAAVVVVBBVVVVVV',
        '.VVVVVV.VpVAAAAAAAAVpV.VVVVVV',
        '...VVVVVVVVVAoAAoAVVVVVVVVV',
        '........VVVVVVooVVVVVV',
        '........VVVVVVVVVVVVVV',
        '.......V..VVVVVVVVVV..V',
        '......V..V...VVVV...V..V',
        '......V..V..........V..V',
        '.....V..V............V..V',
        'SSSSS......SSSSSSSS......SSSSS',
      ],
    },
  ],
};

/** フナヤドン：フナヤドカリが しんか。2かいだての 舟屋に 小さな 船、大きな はさみを ふりあげる（ミズ） */
const funayaDon: MonsterDesign = {
  size: 32,
  colors: {
    N: NQ.slate,
    D: NQ.night,
    B: NQ.tan,
    K: NQ.brown,
    Y: NQ.yellow,
    V: NQ.vermilion,
    A: NQ.apricot,
    W: NQ.white,
    S: NQ.sky,
    p: NQ.blush,
  },
  rim: { [NQ.vermilion]: NQ.brick, [NQ.tan]: NQ.brown },
  layers: [
    {
      x: 1,
      y: 2,
      rows: [
        '..............NN.......K',
        '............NNNNNNWWWWWK',
        '...........DDDDDDDVVVVV',
        '.........NNNNNNNNNNWWW',
        '.......DDDDDDDDDDDDDDDD',
        '......NNNNNNNNNNNNNNNNNN',
        '....NNNNNNNNNNNNNNNNNNNNNN',
        '.VVVBKBBKBBKBBKBBKBBKBBKBBVVV',
        'VVAVVKBBYYYYBYKYYKYYYYBKBVVAVV',
        'VV..VKBBYYYYBYYKYKYYYYBKBV..VV',
        'VV..VVBBKBBKBBKBBKBBKBBKVV..VV',
        'VVVVVVKKKKKKKKKKKKKKKKKKVVVVVV',
        '.VVVVKBBKKKKKKKKKKKKKKBKBVVVV',
        '..VVBKBBKooDDDDDDDDooBBKBBVV',
        '..VVBKBBKDWoDDDDDDoWDBBKBBVV',
        '...VVKBBKDWoDDDDDDoWDBBKBVV',
        '....VVBBKDWoDDDDDDoWDBBKVV',
        '....BKBBKDVVVVVVVVVVDBBKBB',
        '....BKBBKVVVVVVVVVVVVBBKBB',
        '....BKBBVVVAAAAAAAAVVVBKBB',
        '.......VpVVAAAAAAAAVVpV',
        '.......VVVVVoAAAAoVVVVV',
        '.......VVVVVVooooVVVVVV',
        '........VVVVVWVVVVVVVV',
        '.......V.VVVVVVVVVVVV.V',
        '......V..V..VVVVVV..V..V',
        '.....V..V............V..V',
        '....V..V..............V..V',
        'SSS.........SS..SS.........SSS',
      ],
    },
  ],
};

/** カラクナイン：万願寺とうがらし。下へ 細く なる みどりの 実、こい みどりの へたと くき、小さな 炎（ヒノ） */
const karakunain: MonsterDesign = {
  size: 32,
  colors: {
    L: NQ.leaf,
    G: NQ.green,
    S: NQ.sprout,
    C: NQ.cream,
    Y: NQ.gold,
    A: NQ.apricot,
    V: NQ.vermilion,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.leaf]: NQ.green },
  layers: [
    {
      x: 5,
      y: 1,
      rows: [
        '.....C..........C',
        '.....Y..........Y',
        '....AYA........AYA',
        '....VAV....GG..VAV',
        '..........GG',
        '..........GG',
        '.........GGGG',
        '.....GGGGGGGGGGGG',
        '.....GGGGGGGGGGGG',
        '....LGLGGGGGGGGGLL',
        '....LLLLLLLLLLLLLL',
        '....LSWWLLLLLLWWLL',
        '....LSWoLLLLLLoWLL',
        '....LSWoLLLLLLoWLL',
        '....LpLLLLLLLLLLpL',
        '.....SLLLoLLoLLLLL',
        'LLL..SLLLLooLLLLLL.LLL',
        'LLL..LSLLLLLLLLLLL.LLL',
        '.....LSLLLLLLLLLL',
        '......SLLLLLLLLLL',
        '......SLLLLLLLLLL',
        '......SLLLLLLLLLL',
        '.......LLLLLLLLLL',
        '.......LLLLLLLLLL',
        '........LLLLLLLLL',
        '........LLLLLLLL',
        '.........LLLLLLL',
        '.........LLLLLLL',
        '.........LLLLLLL',
        '...........LLLL',
      ],
    },
  ],
};

/** ホントハカライン：カラクナインが しんか。まっかに じゅくした 実、大きな 3 本の 炎、きりっと した まゆ（ヒノ） */
const hontohaKarain: MonsterDesign = {
  size: 32,
  colors: {
    R: NQ.red,
    G: NQ.green,
    A: NQ.apricot,
    C: NQ.cream,
    Y: NQ.gold,
    V: NQ.vermilion,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.red]: NQ.brick },
  layers: [
    {
      x: 3,
      y: 1,
      rows: [
        '.....C......C.......C',
        '.....CY.....YC.....YC',
        '....AYY....AYYA....YYA',
        '....AYYA.....GG...AYYA',
        '....VAYV....GG....VYAV',
        '....VVAV....GG....VAVV',
        '...........GGGG',
        '......GGGGGGGGGGGGGG',
        '......GGGGGGGGGGGGGG',
        '.....RGRRGGGGGGGGRGRR',
        '.....RRooRRRRRRRRooRR',
        '.....RARWoRRRRRRoWRRR',
        '.....RARWoRRRRRRoWRRR',
        'RR...RARWoRRRRRRoWRRR...RR',
        'RR....pRRRRRRRRRRRRpR...RR',
        '.RRR..ARRRoRRRRoRRRRR.RRR',
        '.RRR..ARRRRooooRRRRRR.RRR',
        '......RARRRWRRRRRRRR',
        '.......ARRRRRRRRRRRR',
        '.......ARRRRRRRRRRRR',
        '.......ARRRRRRRRRRRR',
        '........RRRRRRRRRRRR',
        '........RRRRRRRRRRRR',
        '.........RRRRRRRRRRR',
        '.........RRRRRRRRRR',
        '..........RRRRRRRRR',
        '..........RRRRRRRRR',
        '...........RRRRRRRR',
        '...........RRRRRRRR',
        '.............RRRRR',
      ],
    },
  ],
};

const chirimenko: MonsterDesign = {
  size: 32,
  colors: {
    P: NQ.blush,
    B: NQ.berry,
    C: NQ.cream,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.blush]: NQ.berry, [NQ.cream]: NQ.sand },
  layers: [
    {
      rows: [
        '',
        '',
        '',
        '',
        '..........................C',
        '.......C.................C',
        '........CC.............CC',
        '........CCCC.........CCCC',
        '.........CCCCC.....CCCCC',
        '.........CCCCCCCCCCCCCCC',
        '..........CCCCPPPPPCCCC',
        '......BBBBBBBBBBPPPPPPP',
        '.........PPPPPPPBBBBBBBBBBB',
        '........PPPPPPPPPPPPPPPPP',
        '......BBBBBBBBBBPPPPPPPPP',
        '.......PPPPPPPPPBBBBBBBBBBB',
        '.......PPPPPPPPPPPPPPPPPPP',
        '......BBBBBBoWBBPPPWoPPPPP',
        '.......PPPPPoWPPBBBWoBBBBBB',
        '......PPPPPPWWPPPPPWWPPPPPP',
        '......BBBBBBBBBBPPPPPPPPPP',
        '.......PPpPPPPPPBBBBBBBpBBB',
        '.......PPPPPPPPoooPPPPPPPP',
        '......BBBBBBBBBBPPPPPPPPPP',
        '........PPPPPPPPBBBBBBBBBBB',
        '........PPPPPPPPPPPPPPPPP',
        '......BBBBBBBBBBPPPPPPPP',
        '..........PPPPPPBBBBBBBBBBB',
        '............PPPPPPPPP',
        '............BBBBBBBBB',
        '............BBBBBBBBB',
        '',
      ],
    },
  ],
};

const chirimenMai: MonsterDesign = {
  size: 32,
  colors: {
    P: NQ.blush,
    B: NQ.berry,
    C: NQ.cream,
    W: NQ.white,
  },
  rim: { [NQ.blush]: NQ.berry, [NQ.cream]: NQ.sand },
  layers: [
    {
      rows: [
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '.C',
        '.CC...........................C',
        '.CCC............P............CC',
        '.CCCC.......PPPPPPPPP.......CCC',
        '.CCCCC.BBBBBBBBBPPPPPP.....CCCC',
        '..CCCCC...PPPPPPBBBBBBBBBBCCCCC',
        '...CCCCC.PPPPPPPPPPPPPPP.CCCCC',
        '....CCCCBBBBBBBBPPPPPPPPCCCCC',
        '.....CCCPPoooooPBBoooooBBCCC',
        '......CCPPPWWWPPPPPWWWPPPCC',
        '.......CBBBooWBBPPPWooPPPC',
        '.......PPPPooWPPBBBWooBBBB',
        '........PPPooWPPPPPWooPPP',
        '.......BBBBBBBBBPPPPPPPPP',
        '.CCCC...PPPPPPPPBBBBBBBBBB..CCC',
        '.CCCCCCCPPPPPPoooooPPPPPCCCCCCC',
        '.CCCCCCCBBBBBBBBPPPPPPPP.CCCCCC',
        '.CCCCCCC..PPPPPPBBBBBBBBBCCCCCC',
        '.CCCCCCC...PPPPPPPPPPP...CCCCCC',
        '.......BBBBBBBBBPPPPP',
        '................BBBBBBBBBB',
        '',
        '.............BBBBBBB',
        '.............BBBBBBB',
        '',
      ],
    },
  ],
};

const kayabukiMonban: MonsterDesign = {
  size: 40,
  colors: {
    T: NQ.tan,
    B: NQ.brown,
    S: NQ.beige,
    F: NQ.green,
    W: NQ.white,
    g: NQ.gray,
    G: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
  },
  rim: { [NQ.tan]: NQ.brown, [NQ.beige]: NQ.sand, [NQ.gray]: NQ.slate },
  rimDepth: 2,
  layers: [
    {
      rows: [
        '',
        '................G.G.G.G.G',
        '................GGGGGGGGG',
        '................GGGRRGGGG',
        '................GGGRRGGGG',
        '................QQQQQQQQQ',
        '...................TTT',
        '..................TTTTT',
        '.................TTTTTTT',
        '................TTTTTTTTT',
        '..............BBBBBBBBBBBBB',
        '..............TTTTTTTTTTTTT',
        '.............TTTTTTTTTTTTTTT',
        '............TTTTTTTTTTTTTTTTT',
        '..........BBBBBBBBBBBBBBBBBBBBB',
        '..........TTTTTTTTTTTTTTTTTTTTT',
        '.........TTTTTTTTTTTTTTTTTTTTTTT',
        '........TTTTTTTTTTTTTTTTTTTTTTTTT',
        '......BBBBBBBBBBFFFFFFFFFBBBBBBBBBB',
        '......TTTTTTTTTTFFFFFFFFFTTTTTTTTTT',
        '.....TTTTTTTTTTTFFFFFFFFFTTTTTTTTTTT',
        '....TTTTTTTTTTTTFFFFFFFFFTTTTTTTTTTTT',
        '.......SSoooooooooSBSSSoooooooooSS',
        '..BBBBBSSoooooooooSBSSSoooooooooSSBBBBB',
        '..BBBBBSSBSWWWWWWSSBSSSSWWWWWWSSSSBBBBB',
        '..BBBBBSSBSoooWWWSSBSSSSWWWoooSSSSBBBBB',
        '..BBBBBSSBSoooWWWSSBSSSSWWWoooSSSSBBBBB',
        '..BBBBBSSBSoooWWWSSBSSSSWWWoooSSSSBBBBB',
        '..BBBBBSSBSoooWWWSSBSSSSWWWoooSSSSBBBBB',
        '..BBBBBSSBSSSSBSSSSBSSSSBSSSSBSSSSBBBBB',
        '..BBBBBSSBSSSSBSSSSBSSSSBSSSSBSSSSBBBBB',
        '..BBBBBSSBSSSSBSoooooooooSSSSBSSSSBBBBB',
        '..BBBBBSSBSSSSBSoooooooooSSSSBSSSSBBBBB',
        '..BBBBBSSBSSSSBSoooooooooSSSSBSSSSBBBBB',
        '.......SSBSSSSBSSSSBSSSSBSSSSBSSSS',
        '........ggggggggg.......ggggggggg',
        '........ggggggggg.......ggggggggg',
        '........ggggggggg.......ggggggggg',
        '........ggggggggg.......ggggggggg',
        '',
      ],
    },
  ],
};

const kayabukiMonbanField: MonsterDesign = {
  size: 32,
  colors: {
    T: NQ.tan,
    B: NQ.brown,
    S: NQ.beige,
    F: NQ.green,
    W: NQ.white,
    g: NQ.gray,
    G: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
  },
  rim: { [NQ.tan]: NQ.brown, [NQ.beige]: NQ.sand },
  rimDepth: 1,
  layers: [
    {
      rows: [
        '',
        '..............G.G.G',
        '.............GGGGGGG',
        '.............GGRRGGG',
        '.............GGRRGGG',
        '.............QQQQQQQ',
        '..............TTTTT',
        '.............TTTTTTT',
        '...........BBBBBBBBBBB',
        '...........TTTTTTTTTTT',
        '..........TTTTTTTTTTTTT',
        '........BBBBBBBBBBBBBBBBB',
        '........TTTTTTTTTTTTTTTTT',
        '.......TTTTTTTTTTTTTTTTTTT',
        '.....BBBBBBBBFFFFFFFBBBBBBBB',
        '.....TTTTTTTTFFFFFFFTTTTTTTT',
        '....TTTTTTTTTFFFFFFFTTTTTTTTT',
        '..BBBBBBBBBBBFFFFFFFBBBBBBBBBBB',
        '..BBBBSooooooooBSSooooooooSBBBB',
        '..BBBBSBSWWWWWSBSSSWWWWWSSSBBBB',
        '..BBBBSBSooWWWSBSSSWWWooSSSBBBB',
        '..BBBBSBSooWWWSBSSSWWWooSSSBBBB',
        '..BBBBSBSooWWWSBSSSWWWooSSSBBBB',
        '..BBBBSBSSSBSSSBSSSBSSSBSSSBBBB',
        '..BBBBSBSSSBSSSBSSSBSSSBSSSBBBB',
        '..BBBBSBSSSBSoooooooSSSBSSSBBBB',
        '..BBBBSBSSSBSoooooooSSSBSSSBBBB',
        '......SBSSSBSSSBSSSBSSSBSSS',
        '......gggggggg.....gggggggg',
        '......gggggggg.....gggggggg',
        '......gggggggg.....gggggggg',
        '',
      ],
    },
  ],
};

const amanoHiryu: MonsterDesign = {
  size: 48,
  colors: {
    S: NQ.sand,
    T: NQ.tan,
    F: NQ.green,
    W: NQ.white,
    B: NQ.blue,
    G: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
    Y: NQ.yellow,
  },
  rim: { [NQ.sand]: NQ.tan, [NQ.green]: NQ.forest, [NQ.blue]: NQ.navy },
  rimDepth: 2,
  layers: [
    {
      rows: [
        '',
        '...........T',
        '...........T........G.G.G.G.G........T',
        '...........TT.......GGGGGGGGG.......TT.....T',
        '......TTT..TTT......GGGRRGGGG......TTT..TTT',
        '......TTTTTTTTT.....GGGRRGGGG.....TTTTTTTTT',
        '......TTTTTTTTTT....QQQQQQQQQ....TTTTTTTTTT',
        '......TTTTTTTTTTT..SSSSSSSSSSS..TTTTTTTTTTT',
        '.............TTTTSSSSSSSSSSSSSSTTTTT',
        '..............TTTSSSSSSSSSSSSSSSTTT',
        '..............SSSSSSSSSSSSSSSSSSSSS',
        '..............SSSSSSSSSSSSSSSSSSSSS',
        '.............ooooooooooSSSoooooooooo',
        '.....FFFF...SooooooooooSSSooooooooooS...FFF',
        '.....FFFFFFFFSSWWWWWWSSSSSSSWWWWWWSFFFFFFFF',
        '.....FFFFFFFFSSoooWWWSSSSSSSWWWoooSFFFFFFFF',
        '.....FFFFFFFFSSoooWWWSSSSSSSWWWoooSFFFFFFFFF',
        '...........SSSSoooWWWSSSSSSSWWWoooSSSS',
        '.....FFFF...SSSoooWWWSSSSSSSWWWoooSSS...FFF',
        '.....FFFFFFFFSSSSSSSSSSSSSSSSSSSSSSFFFFFFFF',
        '.....FFFFFFFFSSSSSSSSSSSSSSSSSSSSSSFFFFFFFF',
        '.....FFFFFFFFSSSSSSSSSSSSSSSSSSSSSSFFFFFFFFF',
        '.............SSSSSoooooooooooooSSSSS',
        '.....FFFF.....SSSSoooooooooooooSSSS.....FFF',
        '.....FFFFFFFF.SSSSoooooooooooooSSSSFFFFFFFF',
        '.....FFFFFFFF...SSSSSSSSSSSSSSSSS..FFFFFFFF',
        '.....FFFFFFFF....SSSSSSSSSSSSSSS...FFFFFFFFF',
        '...................SSSSSSSSSSS',
        '.....FFFF...............S...............FFF',
        '.....FFFFFFFF..........SSS.........FFFFFFFF',
        '.....FFFFFFFF........SSSSSSS.......FFFFFFFF',
        '.....FFFFFFFF......SSSSSSSSSSS.....FFFFFFFFF',
        '..................SSSSSSSSSSSSS',
        '.....FFFF.......SSSSSSSSSSSSSSSSS.......FFF',
        '.....FFFFFFFF.SSSSSSSSSSSSSSSSSSSSSFFFFFFFF',
        '.....FFFFFFFFSSSSSSSSSSSSSSSSSSSSSSFFFFFFFF',
        '.....FFFFFFFFSSSSSSSSSSSSSSSSSSSSSSFFFFFFFFF',
        '...........SSSSSSSSSSSSSSSSSSSSSSSSSSS',
        '...........SSSSSSSSSSSSSSSSSSSSSSSSSSS',
        '............SSSSSSSSSSSSSSSSSSSSSSSSS',
        '......W.....WSSSSSWSSSSSWSSSSSWSSSSSW.....W',
        '....WWWWW.WWWWWSWWWWWSWWWWWSWWWWWSWWWWW.WWWWW',
        '...WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
        '....WWWWWBWWWWWBWWWWWBWWWWWBWWWWWBWWWWWBWWWWW',
        '....BBWBBBBBWBBBBBWBBBBBWBBBBBWBBBBBWBBBBBWBB',
        '....BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
        '....BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
        '',
      ],
    },
  ],
};

const amanoHiryuP0: MonsterDesign = {
  size: 48,
  colors: {
    S: NQ.sand,
    T: NQ.tan,
    F: NQ.green,
    W: NQ.white,
    A: NQ.teal,
    M: NQ.mint,
    G: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
    Y: NQ.yellow,
  },
  rim: { [NQ.sand]: NQ.tan, [NQ.green]: NQ.forest, [NQ.teal]: NQ.navy },
  rimDepth: 2,
  layers: [
    {
      rows: [
        '',
        '...........T',
        '...........T........G.G.G.G.G........T',
        '...........TT.......GGGGGGGGG.......TT.....T',
        '......TTT..TTT......GGGRRGGGG......TTT..TTT',
        '......TTTTTTTTT.....GGGRRGGGG.....TTTTTTTTT',
        '......TTTTTTTTTT....QQQQQQQQQ....TTTTTTTTTT',
        '......TTTTTTTTTTT..SSSSSSSSSSS..TTTTTTTTTTT',
        '.............TTTTSSSSSSSSSSSSSSTTTTT',
        '..............TTTSSSSSSSSSSSSSSSTTT',
        '..............SSSSSSSSSSSSSSSSSSSSS',
        '..............SSSSSSSSSSSSSSSSSSSSS',
        '.............ooooooooooSSSoooooooooo',
        '.....FFFF...SooooooooooSSSooooooooooS...FFF',
        '.....FFFFFFFFSSWWWWWWSSSSSSSWWWWWWSFFFFFFFF',
        '.....MFFFFFFFSSoYYYYWSSSSSSSWYYYYoSFFFFFFFM',
        '....MMMFFFFFFSSoYYYYWSSSSSSSWYYYYoSFFFFFFMMM',
        '.....M.....SSSSoYYYYWSSSSSSSWYYYYoSSSS....M',
        '.....FFFF...SSSoooWWWSSSSSSSWWWoooSSS...FFF',
        '.....FFFFFFFFSSSSSSSSSSSSSSSSSSSSSSFFFFFFFF',
        '.....FFFFFFFFSSSSSSSSSSSSSSSSSSSSSSFFFFFFFF',
        '.....FFFFFFFFSSSSSSSSSSSSSSSSSSSSSSFFFFFFFFF',
        '.............SSSSSoooooooooooooSSSSS',
        '.....FFFF.....SSSSoooooooooooooSSSS.....FFF',
        '.....FFFFFFFF.SSSSoooooooooooooSSSSFFFFFFFF',
        '.....FFFFFFFF...SSSSSSSSSSSSSSSSS..FFFFFFFF',
        '.....FFFFFFFF....SSSSSSSSSSSSSSS...FFFFFFFFF',
        '...................SSSSSSSSSSS',
        '.....FFFF...............S...............FFF',
        '.....FFFMFFFF..........SSS.........FFFFMFFF',
        '.....FFMMMFFF........SSSSSSS.......FFFMMMFF',
        '.....FFFMFFFF......SSSSSSSSSSS.....FFFFMFFFF',
        '..................SSSSSSSSSSSSS',
        '.....FFFF.......SSSSSSSSSSSSSSSSS.......FFF',
        '.....FFFFFFFF.SSSSSSSSSSSSSSSSSSSSSFFFFFFFF',
        '.....FFFFFFFFSSSSSSSSSSSSSSSSSSSSSSFFFFFFFF',
        '.....FFFFFFFFSSSSSSSSSSSSSSSSSSSSSSFFFFFFFFF',
        '...........SSSSSSSSSSSSSSSSSSSSSSSSSSS',
        '...........SSSSSSSSSSSSSSSSSSSSSSSSSSS',
        '............SSSSSSSSSSSSSSSSSSSSSSSSS',
        '......M.....MSSSSSMSSSSSMSSSSSMSSSSSM.....M',
        '....MMMMM.MMMMMSMMMMMSMMMMMSMMMMMSMMMMM.MMMMM',
        '...MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM',
        '....MMMMMAMMMMMAMMMMMAMMMMMAMMMMMAMMMMMAMMMMM',
        '....AAMAAAAAMAAAAAMAAAAAMAAAAAMAAAAAMAAAAAMAA',
        '....AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
        '....AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
        '',
      ],
    },
  ],
};

const murasakiShikibu: MonsterDesign = {
  size: 48,
  colors: {
    V: NQ.violet,
    L: NQ.lavender,
    C: NQ.cream,
    R: NQ.red,
    F: NQ.skinLight,
    H: NQ.hairBlack,
    W: NQ.white,
    G: NQ.gold,
    B: NQ.brown,
    Y: NQ.yellow,
  },
  rim: { [NQ.violet]: NQ.indigo, [NQ.lavender]: NQ.violet, [NQ.skinLight]: NQ.skinMid, [NQ.cream]: NQ.gold },
  rimDepth: 2,
  layers: [
    {
      rows: [
        '',
        '.......................GGG',
        '....................GGGGGGGGG',
        '....................GGGGGGGGG',
        '....................GGGGGGGGG',
        '...................HHHHGGGHHHH',
        '..................HHHHHGGGHHHHH',
        '.................HHHHHHHHHHHHHHH',
        '................HHHHHHHHHHHHHHHHH',
        '......Y.........oooooooHHHooooooo........Y',
        '.....YYY........oooooooHHHooooooo.......YYY',
        '......Y..........WWWWWHHHHHWWWWW.........Y',
        '................FWWoooHHHHHoooWWF',
        '.................WWoooHHHHHoooWW',
        '................HHHHHHHHHHHHHHHHH',
        '................HHHHHHHHHHHHHHHHH',
        '........WWW....HHHHHHHHRRRHHHHHHHH',
        '........WWW...HHHHHHHHHHHHHHHHHHHHH',
        '........WWW..HHHHHHHHHHHHHHHHHHHHHHH',
        '........BBB..HHHHHHHHHHHHHHHHHHHHHHH',
        '........BBB.HHHHHHHHHHHHHHHHHHHHHHHHH...C',
        '........BBBHHHHHHHHHHHHHHHHHHHHHHHHHHH..C',
        '........BBBHHHHHHHHHHHHHHHHHHHHHHHHHHHHC.C',
        '........BBBHHHHHHHHHHHHHHHHHHHHHHHHHHH.C.C',
        '........BBBHHHHHHHHHHHHHHHHHHHHHHHHHHH.CC.C',
        '....Y...BBBHHHHHHHHHHHHHHHHHHHHHHHHHHH.CCC..Y',
        '...YYY..BBBHHHHHHHHHHHHHHHHHHHHHHHHHHHCCC..YYY',
        '....Y...BBBHHHHHHHHHHHHHHHHHHHHHHHHHHHCCCCC.Y',
        '........BBB.HHHHHHHHHHHHHHHHHHHHHHHHH.CCC..CC',
        '........BBB.HHHHHHHHHHHHHHHHHHHHHHHHRRRRCCC',
        '........BBB.HHHHHHHHHHHHHHHHHHHHHHHHRRRRCCCCCC',
        '........BBB.HHHHHHHHHHHHVHHHHHHHHHHHRRRR',
        '........BBB.HHHHHHHHHHHLLLHHHHHHHHHHRRRR',
        '........BBB.HHHHHHHHHHVVVVVHHHHHHHHHH',
        '........BBBVVHHHHHHHHHVVVVVHHHHHHHHHVV',
        '...........VVHHHHHHHHVVVVVVVHHHHHHHHVV',
        '..........VVVHHHHHHHVVVVVVVVVHHHHHHHVVV',
        '.........VVVVHHHHHHHVVVVVVVVVHHHHHHHVVVV',
        '........LLLLLHHHHHHLLLLLLLLLLLHHHHHHLLLLL',
        '........VVVVVVHHHHVVVVVVVVVVVVVHHHHVVVVVV',
        '.......VVVVVVVHHHVVVVVVVVVVVVVVVHHHVVVVVVV',
        '.......VVVVVVVHHHVVVVVVVVVVVVVVVHHHVVVVVVV',
        '......VVVVVVVVHHVVVVVVVVVVVVVVVVVHHVVVVVVVV',
        '.....VVVVVVVVVHVVVVVVVVVVVVVVVVVVVHVVVVVVVVV',
        '....CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
        '....CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
        '....CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
        '',
      ],
    },
  ],
};

export const KYOTO: Readonly<Record<string, MonsterDesign>> = {
  'kyoto-chatsumin': chatsumin,
  'kyoto-chasenshi': chasenshi,
  'kyoto-funayadokari': funayadokari,
  'kyoto-funaya-don': funayaDon,
  'kyoto-karakunain': karakunain,
  'kyoto-hontoha-karain': hontohaKarain,
  'kyoto-chirimenko': chirimenko,
  'kyoto-chirimen-mai': chirimenMai,
  'kyoto-midboss-kayabuki-monban': kayabukiMonban,
  'kyoto-midboss-kayabuki-monban.field': kayabukiMonbanField,
  'kyoto-boss-amano-hiryu': amanoHiryu,
  'kyoto-boss-amano-hiryu.p0': amanoHiryuP0,
  'kyoto-lastboss-murasaki-shikibu': murasakiShikibu,
};
