/** 三重県の モンスター（手描き。docs/06 §4・§6.3〜6.5 の 規格）。下書きは 図形で かいて 1 ドットずつ 手で なおした */
import { NQ } from '../palette';
import type { MonsterDesign } from './design';
import { FACE, HELMET, lord } from './lastbosses';

/** イガニン：伊賀の 小さな 忍者。ずきんの むすび目が とがった 耳、金の 目、口の 前に まきもの（ヤミ） */
const iganin: MonsterDesign = {
  size: 32,
  colors: {
    V: NQ.violet,
    I: NQ.indigo,
    L: NQ.lavender,
    K: NQ.skinLight,
    G: NQ.gold,
    S: NQ.paper,
    B: NQ.brown,
    R: NQ.red,
    p: NQ.blush,
  },
  rim: { [NQ.violet]: NQ.indigo, [NQ.paper]: NQ.cloud },
  layers: [
    {
      rows: [
        '................................',
        '................................',
        '........V..............V........',
        '.........V............V.........',
        '.........VVV........VVV.........',
        '.........VVVV......VVVV.........',
        '..........VVVV....VVVV..........',
        '..........VVVV....VVVV..........',
        '..........VVV......VVV..........',
        '...........V.VVVVVV.V...........',
        '...........VVVVVVVVVV...........',
        '..........LVVVVVVVVVVV..........',
        '.........LVVVVVVVVVVVVV.........',
        '........VVKKKKKKKKKKKKVV........',
        '........VVKGGKKKKKKGGKVV........',
        '.......VVVKGoKKKKKKoGKVVV.......',
        '.......VVVKGoKKKKKKoGKVVV.......',
        '.......VVVpKKKKKKKKKKpVVV.......',
        '.....BBVVVVVVVVVVVVVVVVVVBB.....',
        '.....BBSSSSSSSSRRSSSSSSSSBB.....',
        '.....BBSSSSSSSSRRSSSSSSSSBB.....',
        '.....BBVVVVVVVVVVVVVVVVVVBB.....',
        '.......VVVVVKKKVVKKKVVVVV.......',
        '.......VVVVVKKKVVKKKVVVVV.......',
        '.......VIIIIIIIIIIIIIIIIV.......',
        '........IIIIIIIIIIIIIIII........',
        '........VVVVVVVVVVVVVVVV........',
        '.........VVVVVVVVVVVVVV.........',
        '..........VVVVVVVVVVVV..........',
        '..........IIIIVVVVIIII..........',
        '.............VVVVVV.............',
        '................................',
      ],
    },
  ],
};

/** イガジョウニン（イガニンの しんか）：上忍の すがた。長い 耳、きりっと まゆ、赤い マフラー、足もとに けむり（ヤミ） */
const igaJonin: MonsterDesign = {
  size: 32,
  colors: {
    V: NQ.violet,
    I: NQ.indigo,
    L: NQ.lavender,
    K: NQ.skinLight,
    G: NQ.gold,
    S: NQ.paper,
    B: NQ.brown,
    R: NQ.red,
    c: NQ.cloud,
    p: NQ.blush,
  },
  rim: { [NQ.violet]: NQ.indigo, [NQ.paper]: NQ.cloud, [NQ.red]: NQ.brick },
  layers: [
    {
      rows: [
        '................................',
        '.......V................V.......',
        '........V..............V........',
        '........VV............VV........',
        '.........VVV........VVV.........',
        '.........VVVV......VVVV.........',
        '.........VVVVV....VVVVV.........',
        '..........VVV......VVV..........',
        '..........VV.VVVVVV.VV...RR.....',
        '...........VVVVVVVVVV...RRR.....',
        '..........LVVVVVVVVVVV.RRRR.....',
        '.........LVVVVVVVVVVVVVRRR......',
        '........VKooKKKKKKKKooKVRR......',
        '.......VVKKGoKKKKKKoGKKVVRR.....',
        '.......VVKKGoKKKKKKoGKKVV.R.....',
        '.......VVKKGoKKKKKKoGKKVV.......',
        '......VVVpKKKKKKKKKKKKpVVV......',
        '......BBVVVVVVVVVVVVVVVVBB......',
        '......BBSSSSSSSRRSSSSSSSBB......',
        '......BBSSSSSSSRRSSSSSSSBB......',
        '......BBVVVVVVVVVVVVVVVVBB......',
        '......VVVVVVKKKKKKKKVVVVVV......',
        '......VVVVVVKKKKKKKKVVVVVV......',
        '.......IIIIIIIIIIIIIIIIII.......',
        '.......IIIIIIIIIIIIIIIIII.......',
        '.......VVVVVVVVVVVVVVVVVV.......',
        '..cc....VVVVVVVVVVVVVVVV...cc...',
        '.cccc....VVVVVVVVVVVVVV...cccc..',
        '..cc......VVVVVVVVVVVV.....cc...',
        '.........IIIIVVVVVVIIII.........',
        '.............VVVVVV.............',
        '................................',
      ],
    },
  ],
};

/** クワナグリ：桑名の はまぐり。まるい 三角の 貝がら、成長の わ、下から 出た 足、よこに 水の ひれ（ミズ） */
const kuwanaguri: MonsterDesign = {
  size: 32,
  colors: { E: NQ.beige, T: NQ.tan, B: NQ.brown, C: NQ.cream, A: NQ.azure, W: NQ.white, p: NQ.blush },
  rim: { [NQ.beige]: NQ.sand, [NQ.azure]: NQ.blue },
  layers: [
    {
      rows: [
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '...............EE...............',
        '..............EEEE..............',
        '............EEEEEEEE............',
        '..........TEEEEEEEEEET..........',
        '.........EEEEEEEEEEEEEE.........',
        '........EEECEEEEEEEEEEEE........',
        '.......ETECEETEEEETEEEETE.......',
        '.......EETEEEEEEEEEEEETEE.......',
        '......TEEEETEEEEEEEETEEEET......',
        '......ETEBEEETTEETTEEEBETE......',
        '......EETEEEEEEEEEEEEEETEE......',
        '.....TEEEETWWEEEEEEWWTEEEET.....',
        '.....ETEEEEWoTTTTTToWEEEETE.....',
        '.A..EEEETEEWoEEEEEEoWEETEEEE..A.',
        '.AAAEEEEEpTEEEEEEEEEETpEEEEEAAA.',
        '.AAAAEEEEEEEEToTToTEEEEEEEEAAAA.',
        '.AAAAEEEBEEEEEEooEEEEEEBEEEAAAA.',
        '.AAAAEEEEEEEEBEEEEBEEEEEEEEAAAA.',
        '.....EEEEEEEEEEEEEEEEEEEEEE.....',
        '......EEEEEEEEEEEEEEEEEEEE......',
        '......EEEEEEEEEEEEEEEEEEEE......',
        '......oooooooooooooooooooo......',
        '.......CCCCCCCppppCCCCCCC.......',
        '.......CCCCCCppppppCCCCCC.......',
        '................................',
        '................................',
        '................................',
      ],
    },
  ],
};

/** シンキロウガイ（クワナグリの しんか）：大きな はまぐり。いきを はいて、上に しんきろうの おしろを うかべる（ミズ） */
const shinkirouGai: MonsterDesign = {
  size: 32,
  colors: {
    E: NQ.beige,
    T: NQ.tan,
    B: NQ.brown,
    C: NQ.cream,
    I: NQ.ice,
    l: NQ.lavender,
    S: NQ.sky,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.beige]: NQ.sand, [NQ.ice]: NQ.sky },
  layers: [
    {
      rows: [
        '................................',
        '..............IIII..............',
        '..............IIII..............',
        '..............IIII..............',
        '.............IIIIII.............',
        '...........IIIIIIIIII...........',
        '.............IIIIII.............',
        '.............llllll.............',
        '.............IIIIII.............',
        '.............llllll.............',
        '.............IIIIII.............',
        '.............llllll.............',
        '.............IIIIII.............',
        '...........S........S...........',
        '.............S....S.............',
        '...............EE...............',
        '.............EEEEEE.............',
        '..........ECEEEEEEEEEE..........',
        '........EECEEEEEEEEEETEE........',
        '.......TEEEEEEEEEEEEEEEET.......',
        '......EETEooTEEEEEETooETEE......',
        '.....TEEEEEWoETTTTEoWEEEEET.....',
        '.....EEEEETWoEEEEEEoWTEEEEE.....',
        '....EEEEEBEWoEEEEEEoWEBEEEEE....',
        '....EEEETpEEEEETTEEEEEpTEEEE....',
        '.....EEEETEEEEoEEoEEEETEEEE.....',
        '.....EEEEEEBTEEooEETBEEEEEE.....',
        '......EEEEEEEEEEEEEEEEEEEE......',
        '......oooooooooooooooooooo......',
        '.......CCCCCCCCCCCCCCCCCC.......',
        '.......CCCCCCCCCCCCCCCCCC.......',
        '................................',
      ],
    },
  ],
};

/** ドナベエ：萬古焼の 土なべ。ふたの つまみに 3 本の 炎、よこに 耳、ゆげ（ヒノ） */
const donabee: MonsterDesign = {
  size: 32,
  colors: {
    B: NQ.brown,
    K: NQ.bark,
    T: NQ.tan,
    E: NQ.beige,
    C: NQ.cream,
    V: NQ.vermilion,
    A: NQ.apricot,
    G: NQ.gold,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.brown]: NQ.bark, [NQ.beige]: NQ.sand },
  layers: [
    {
      rows: [
        '................................',
        '...............GG...............',
        '..............AGGA..............',
        '...........G..VAAV..G...........',
        '..........AG..VVVV..GA..........',
        '..........VA........AV..........',
        '...............KK...............',
        '...............KK...............',
        '...WW.....EEEEEEEEEEEE..........',
        '..WW....EEEEEEEEEEEEEEEE...WW...',
        '...W...ECEEEEEEEEEEEEEEEE...WW..',
        '......ECEEEEEEEEEEEEEEEEEE..W...',
        '......EEEEEEEEEEEEEEEEEEEE......',
        '......EEEEEEEEEEEEEEEEEEEE......',
        '......EEEEEEEEEEEEEEEEEEEE......',
        '....TTTTTTTTTTTTTTTTTTTTTTTT....',
        '....TTTTTTTTTTTTTTTTTTTTTTTT....',
        '.....BBBBBBBBBBBBBBBBBBBBBB.....',
        '..BB.BBBBBBBBBBBBBBBBBBBBBB.BB..',
        '..BB..BBBBBWWBBBBBBWWBBBBB..BB..',
        '..BB..BBBBBWoBBBBBBoWBBBBB..BB..',
        '......BBBBBWoBBBBBBoWBBBBB......',
        '.......BBpBBBBoBBoBBBBpBB.......',
        '.......BBBBBBBBooBBBBBBBB.......',
        '.......BBBBBBBBBBBBBBBBBB.......',
        '........BBBBBBBBBBBBBBBB........',
        '........BBBBBBBBBBBBBBBB........',
        '................................',
        '.........KKKK......KKKK.........',
        '.........KKKK......KKKK.........',
        '................................',
        '................................',
      ],
    },
  ],
};

/** グツグツドン（ドナベエの しんか）：ふたが もちあがり、あつい スープが ぐつぐつ。足もとに 大きな 炎（ヒノ） */
const gutsugutsuDon: MonsterDesign = {
  size: 32,
  colors: {
    B: NQ.brown,
    K: NQ.bark,
    T: NQ.tan,
    E: NQ.beige,
    C: NQ.cream,
    V: NQ.vermilion,
    A: NQ.apricot,
    G: NQ.gold,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.brown]: NQ.bark, [NQ.beige]: NQ.sand },
  layers: [
    {
      rows: [
        '................................',
        '..............GCCG..............',
        '.............AGGGGA.............',
        '.............VAGGAV.............',
        '.............VVAAVV.............',
        '.........EEEEEEEEEEEEEE.........',
        '.......ECEEEEEEEEEEEEEEEE.......',
        '......ECEEEEEEEEEEEEEEEEEE......',
        '.....EEEEEEEEEEEEEEEEEEEEEE.....',
        '.....EEEEEEEEEEEEEEEEEEEEEE.....',
        '......EEEEEEEEEEEEEEEEEEEE......',
        '...TTTTTTTTTTTTTTTTTTTTTTTTTT...',
        '...TTTTTTTTTTTTTTTTTTTTTTTTTT...',
        '.....CCCACCCACCCCCCACCCACCC.....',
        '.....CCCCCCCCCCCCCCCCCCCCCC.....',
        '....BBBBBBBBBBBBBBBBBBBBBBBB....',
        '....BBBBBBBBBBBBBBBBBBBBBBBB....',
        '.BB..BBBBBooBBBBBBBBooBBBBB..BB.',
        '.BB..BBBBBBWoBBBBBBoWBBBBBB..BB.',
        '.BB..BBBBBBWoBBBBBBoWBBBBBB..BB.',
        '.....BBBBBBWoBBBBBBoWBBBBBB.....',
        '.....BBBBpBBBoBBBBoBBBpBBBB.....',
        '......BBBBBBBBooooBBBBBBBB......',
        '......BBBBBBBBBBBBBBBBBBBB......',
        '......BBBBBBBBBBBBBBBBBBBB......',
        '......BBBBBBBBBBBBBBBBBBBB......',
        '.......BBBBBBBBBBBBBBBBBB.......',
        '.......BBBBBBBBBBBBBBBBBB.......',
        '..........V.V.V.V.V.V...........',
        '.........VAVAVAVAVAVAV..........',
        '.........AGAGAGAGAGAGA..........',
        '................................',
      ],
    },
  ],
};

const akoyan: MonsterDesign = {
  size: 32,
  colors: {
    S: NQ.sand,
    T: NQ.tan,
    C: NQ.ice,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.sand]: NQ.tan, [NQ.ice]: NQ.sky },
  layers: [
    {
      rows: [
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '.........SSSSSSSSSSSSSSS',
        '....C..TSSTSSTSSTSSTSSTSST.C',
        '...CCC..TSSTSTSSTSSTSTSST.CCC',
        '....C...STSTSSTSTSTSSTSTS..C',
        '.......SSSTSTSTSTSTSTSTSSS',
        '.......SSSSTTSTSTSTSTTSSSS',
        '.......SSSSSTTSTTTSTTSSSSS',
        '......SSSSSSTSTTWTTSTSSSSSS',
        '......SSSSSSSTCWWWCTSSSSSSS',
        '......SSSSSSSCWWWWWCSSSSSSS',
        '......SSSSSSCCCWWWCCCSSSSSS',
        '......SSSSSSSCCCWCCCSSSSSSS',
        '.....SSSSSSSSSCCCCCSSSSSSSSS',
        '......SSSSSoWSSSCSSSWoSSSSS',
        '......SSSSSoWSSSSSSSWoSSSSS',
        '......SSSSSWWSSSSSSSWWSSSSS',
        '.......SpSSSSSSSSSSSSSSSpS',
        '.......SSSSSSSSoooSSSSSSSS',
        '........SSSSSSSSSSSSSSSSS',
        '..........SSSSSSSSSSSSS',
        '...........SSSSSSSSSSS',
        '............TTTTTTTTT',
        '............TTTTTTTTT',
        '',
      ],
    },
  ],
};

const shinjuHime: MonsterDesign = {
  size: 32,
  colors: {
    S: NQ.sand,
    T: NQ.tan,
    C: NQ.ice,
    W: NQ.white,
  },
  rim: { [NQ.sand]: NQ.tan, [NQ.ice]: NQ.sky },
  layers: [
    {
      rows: [
        '',
        '',
        '.........SSSSSSSSSSSSSSS',
        '.......TSSTSSTSSTSSTSSTSST',
        '........TSSTSTSSTSSTSTSST',
        '.......SSTSSTSTSTSTSTSSTSS',
        '.......SSSTSTSTSTSTSTSTSSS',
        '...C...SSSSTTTSTTTSTTTSSSS..C',
        '..CCC.SSSSSSSTTTTTTTSSSSSSSCCC',
        '...C..SSSSSSSSTTCTTSSSSSSSS.C',
        '.....SSSSSSSSCCWCCCCSSSSSSSS',
        '.....SSSSSSSCCWWWCCCCSSSSSSS',
        '............CWWWWWCCC',
        '...........CCCWWWCCCCC',
        '.......SSSSSCCCWCCCCCSSSSS',
        '......SSSSSSCCCCCCCCCSSSSSS',
        '......SSSSSSSCCCCCCCSSSSSSS',
        '......SSSSSSSSTTCTTSSSSSSSS',
        '......SSSSSSSTTTTTTTSSSSSSS',
        '.....CSSSSSoWWTTTTTWWoSSSSCS',
        '....CCCSSSSoWWSTTTSWWoSSSCCC',
        '.....CSSSSSoWWTSTSTWWoSSSSCS',
        '.....SSSSSTSTSTSTSTSTSTSSSSS',
        '....SSSSSTSTSSoooooSSTSTSSSSS',
        '....SSSSTSSTSTSSTSSTSTSSTSSSS',
        '....SSSTSSTSSTSSTSSTSSTSSTSSS',
        '',
        '',
        '',
        '............TTTTTTTTT',
        '............TTTTTTTTT',
        '',
      ],
    },
  ],
};

const oosanshoOu: MonsterDesign = {
  size: 40,
  colors: {
    B: NQ.brown,
    T: NQ.tan,
    K: NQ.bark,
    W: NQ.white,
    A: NQ.sky,
    G: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
  },
  rim: { [NQ.brown]: NQ.bark, [NQ.tan]: NQ.brown, [NQ.sky]: NQ.azure },
  rimDepth: 2,
  layers: [
    {
      rows: [
        '',
        '',
        '................G.G.G.G.G',
        '................GGGGGGGGG',
        '................GGGRRGGGG',
        '................GGGRRGGGG',
        '...AAAA.AAAA....QQQQQQQQQ......AAAA.AAA',
        '...AAAA.AAAA...................AAAA.AAA',
        '...AAAA.AAAA........B..........AAAA.AAA',
        '...AAAA.AAAA..BBBBBBBBBBBBB....AAAA.AAA',
        '...AAAA.AAABBBBTBBBBBBBBBBBBBB.AAAA.AAA',
        '...AAAA.AAoooooooTTBBBBBoooooooAAAA.AAA',
        '...AAAA.BBoooooooTTTTBBBoooooooBBAA.AAA',
        '...AAAA.BBTWWWWWTTTTTBBBBWWWWWBBBAA.AAA',
        '...AAAABBTTooWWWTTTTTTBBBWWWooBBBBA.AAA',
        '...AAAABBBTooWWWTTTTTBBBBWWWooBBBBA.AAA',
        '...AAABBBBTooWWWTTTTTBBBBWWWooBBBBB.AAA',
        '...AAAABBBBBTTTTTTTBBBBBBBBBBBBBBBA.AAA',
        '...AAAABBBBBBBBTBBBBBBBBBBBBBBBBBBA.AAA',
        '...AAAA.BoooooooooooooooooooooooBAA.AAA',
        '...AAAA.BoooooooooooooooooooooooBAA.AAA',
        '...AAAA.AAKBBBBBBBBBBBBBBBBBBBKAAAA.AAA',
        '...AAAA.AKKKBBBBBBBBKBBBBBBBBKKKAAA.AAA',
        '...AAAA.BBKBBBBBBBBKKKBBBBBBBBKBBAA.AAA',
        '...AAAABBBBBBBKBBBBBKBBBBBKBBBBBBBA.AAA',
        '...AAABBBBBBBKKKBBBBBBBBBKKKBBBBBBB.AAA',
        '...AAABBBBBBBBKBBBBBBBBBBBKBBBBBBBB.AAA',
        '...AAABBBBBBBBBBBBBBBBBBBBBBBBBBBBB.AAA',
        '...AABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAAA',
        '...AAABBBBBBBBBBBBBBBBBBBBBBBBBBBBB.AAA',
        '...AAABBBBBBBBBBBBBBBBBBBBBBBBBBBBB.AAA',
        '...AAABBBBBBBBBBBBBBBBBBBBBBBBBBBBB.AAA',
        '...ABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBAA',
        '.BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
        '.BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
        '.BBBBBBBB..BBBBBBBBBBBBBBBBBBB.BBBBBBBB',
        '.TTTTT........BBBBBBBBBBBBB........TTTT',
        '.TTTTT..............B..............TTTT',
        '.TTTTT.............................TTTT',
        '',
      ],
    },
  ],
};

const oosanshoOuField: MonsterDesign = {
  size: 32,
  colors: {
    B: NQ.brown,
    T: NQ.tan,
    K: NQ.bark,
    W: NQ.white,
    A: NQ.sky,
    G: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
  },
  rim: { [NQ.brown]: NQ.bark, [NQ.tan]: NQ.brown },
  rimDepth: 1,
  layers: [
    {
      rows: [
        '',
        '',
        '..............G.G.G',
        '.............GGGGGGG',
        '.............GGRRGGG',
        '.............GGRRGGG',
        '.............QQQQQQQ',
        '................B',
        '..........BBTBBBBBBBBBB',
        '........ooooooTTBBBoooooo',
        '.......BooooooTTTBBooooooB',
        '......BTTooWWTTTTTBBWWooBBB',
        '......BBTooWWTTTTBBBWWooBBB',
        '.....BBBBooWWTTTBBBBWWooBBBB',
        '......BBBBBBTBBBBBBBBBBBBBB',
        '......BoooooooooooooooooooB',
        '.......ooooooooooooooooooo',
        '........KBBBBBBBKBBBBBBBK',
        '.......KKKBBBBBKKKBBBBBKKK',
        '......BBKBBKBBBBKBBBBKBBKBB',
        '.....BBBBBKKKBBBBBBBKKKBBBBB',
        '.....BBBBBBKBBBBBBBBBKBBBBBB',
        '....BBBBBBBBBBBBBBBBBBBBBBBBB',
        '.....BBBBBBBBBBBBBBBBBBBBBBB',
        '.....BBBBBBBBBBBBBBBBBBBBBBB',
        '....BBBBBBBBBBBBBBBBBBBBBBBBB',
        '.BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
        '.BBBBBB.BBBBBBBBBBBBBBBBB.BBBBB',
        '.BBBBBB...BBBBBBBBBBBBB..BBBBBB',
        '.TTTT...........B...........TTT',
        '.TTTT.......................TTT',
        '',
      ],
    },
  ],
};

const iseebiTaisho: MonsterDesign = {
  size: 48,
  colors: {
    R: NQ.red,
    B: NQ.brick,
    C: NQ.ice,
    W: NQ.white,
    G: NQ.gold,
    Q: NQ.ochre,
  },
  rim: { [NQ.red]: NQ.brick, [NQ.ice]: NQ.sky },
  rimDepth: 2,
  layers: [
    {
      rows: [
        '',
        '',
        '..B.................G.G.G.G.G.................B',
        '..BBB...............GGGGGGGGG...............BBB',
        '...BBBB.............GGGRRGGGG.............BBBB',
        '.....BBB............GGGRRGGGG............BBB',
        '.......BBB..........QQQQQQQQQ..........BBB',
        '........BBB...........CCWCC...........BBB',
        '..........BBB........CCWWWCC........BBB',
        '...........BBBB....RRRCCWCCRRR....BBBB',
        '.............BBB.RRRRRCCCCCRRRRR.BBB',
        '...............RRRRRRRRRCRRRRRRRRR',
        '..............RRRRRRRRRRRRRRRRRRRRR',
        '...........BBBoooooooooBBBoooooooooBBB',
        '.............RoooooooooRRRoooooooooR',
        '............RRRRWWWWWRRRRRRRWWWWWRRRR',
        '............RRRRooWWWRRRRRRRWWWooRRRR',
        '...........BBBBBooWWWBBBBBBBWWWooBBBBB',
        '...........RRRRRooWWWRRRRRRRWWWooRRRRR',
        '............RRRRRRRRRRRRRRRRRRRRRRRRR',
        '...R........RRRRRRRRRRRRRRRRRRRRRRRRR',
        '...RRR.....BBBBBBBBBBBBBBBBBBBBBBBBBBB.....RRR',
        '...RRRRR.....RRRRRRoooooooooooRRRRRR.....RRRRR',
        '...RRRRRRRR..RRRRRRoooooooooooRRRRRR..RRRRRRRR',
        '..RRRRRRRRRRR.RRRRRoooooooooooRRRRRRRRRRRRRRRRR',
        '..RRRRRRRRRRR..RRRRRRRRRRRRRRRRRRR..RRRRRRRRRRR',
        '.RRRRRRRRRRRR....RRRRRRRRRRRRRRR....RRRRRRRRRRR',
        '....RRRRRRRRR...RRRRRRRRRRRRRRRRR...RRRRRRRRR',
        '.......RRRRRRBBBBBBBBBBBBBBBBBBBBBBBRRRRRR',
        '..........RRR..RRRRRRRRRRRRRRRRRRR..RRR',
        '..............RRRRRRRRRRRRRRRRRRRRR',
        '..............RRRRRRRRRRRRRRRRRRRRR',
        '...........R.BBBBBBBBBBBBBBBBBBBBBBB',
        '.......RRRR..RRRRRRRRRRRRRRRRRRRRRRR.RRRRR',
        '..RRRRRRRRR...RRRRRRRRRRRRRRRRRRRRR..RRRRRRRRR',
        '..RRRRRRRRR...RRRRRRRRRRRRRRRRRRRRR..RRRRRRRRR',
        '..RRRRRRRRR..BBBBBBBBBBBBBBBBBBBBBBB.RRRRRRRRR',
        '..RRRRR........RRRRRRRRRRRRRRRRRRR........RRRR',
        '............R..RRRRRRRRRRRRRRRRRRR',
        '...........RR...RRRRRRRRRRRRRRRRR...RR',
        '.........RRRRBBBBBBBBBBBBBBBBBBBBBBBRRRR',
        '.......RRRRRR......RRRRRRRRRRR......RRRRRR',
        '....RRRRRRRRR...........R..........RRRRRRRRR',
        '....RRRRRRR...........................RRRRRR',
        '....RRRR..BBBBBBBBBBBBBBBBBBBBBBBBBBBBB..RRR',
        '..........BBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
        '..........BBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
        '',
      ],
    },
  ],
};

const iseebiTaishoP0: MonsterDesign = {
  size: 48,
  colors: {
    V: NQ.vermilion,
    B: NQ.brick,
    C: NQ.cream,
    W: NQ.white,
    G: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
  },
  rim: { [NQ.vermilion]: NQ.brick, [NQ.cream]: NQ.gold },
  rimDepth: 2,
  layers: [
    {
      rows: [
        '',
        '',
        '..B.................G.G.G.G.G.................B',
        '..BBB...............GGGGGGGGG...............BBB',
        '...BBBB.............GGGRRGGGG.............BBBB',
        '.....BBB............GGGRRGGGG............BBB',
        '.......BBB..........QQQQQQQQQ..........BBB',
        '........BBB...........CCWCC...........BBB',
        '..........BBB........CCWWWCC........BBB',
        '...........BBBB....VVVCCWCCVVV....BBBB',
        '.............BBB.VVVVVCCCCCVVVVV.BBB',
        '...............VVVVVVVVVCVVVVVVVVV',
        '..............VVVVVVVVVVVVVVVVVVVVV',
        '...........BBBoooooooooBBBoooooooooBBB',
        '.............VoooooooooVVVoooooooooV',
        '....C.......VVVVWWWWWVVVVVVVWWWWWVVVV......C',
        '...CCC......VVVVooWWWVVVVVVVWWWooVVVV.....CCC',
        '....C......BBBBBooWWWBBBBBBBWWWooBBBBB.....C',
        '...........VVVVVooWWWVVVVVVVWWWooVVVVV',
        '............VVVVVVVVVVVVVVVVVVVVVVVVV',
        '...V........VVVVVVVVVVVVVVVVVVVVVVVVV',
        '...VVV.....BBBBBBBBBBBBBBBBBBBBBBBBBBB.....VVV',
        '...VVVVV.....VVVVVVoooooooooooVVVVVV.....VVVVV',
        '...VVVVVVVV..VVVVVVoooooooooooVVVVVV..VVVVVVVV',
        '..VVVVVVVVVVV.VVVVVoooooooooooVVVVVVVVVVVVVVVVV',
        '..VVVVVVVVVVV..VVVVVVVVVVVVVVVVVVV..VVVVVVVVVVV',
        '.VVVVVVVVVVVV....VVVVVVVVVVVVVVV....VVVVVVVVVVV',
        '....VVVVVVVVV...VVVVVVVVVVVVVVVVV...VVVVVVVVV',
        '.......VVVVVVBBBBBBBBBBBBBBBBBBBBBBBVVVVVV',
        '..........VVV..VVVVVVVVVVVVVVVVVVV..VVV',
        '..............VVVVVVVVVVVVVVVVVVVVV',
        '.......C......VVVVVVVVVVVVVVVVVVVVV.....C',
        '......CCC..V.BBBBBBBBBBBBBBBBBBBBBBB...CCC',
        '.......CVVV..VVVVVVVVVVVVVVVVVVVVVVV.VVVCV',
        '..VVVVVVVVV...VVVVVVVVVVVVVVVVVVVVV..VVVVVVVVV',
        '..VVVVVVVVV...VVVVVVVVVVVVVVVVVVVVV..VVVVVVVVV',
        '..VVVVVVVVV..BBBBBBBBBBBBBBBBBBBBBBB.VVVVVVVVV',
        '..VVVVV........VVVVVVVVVVVVVVVVVVV........VVVV',
        '............V..VVVVVVVVVVVVVVVVVVV',
        '...........VV...VVVVVVVVVVVVVVVVV...VV',
        '.........VVVVBBBBBBBBBBBBBBBBBBBBBBBVVVV',
        '.......VVVVVV......VVVVVVVVVVV......VVVVVV',
        '....VVVVVVVVV...........V..........VVVVVVVVV',
        '....VVVVVVV...........................VVVVVV',
        '....VVVV..BBBBBBBBBBBBBBBBBBBBBBBBBBBBB..VVV',
        '..........BBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
        '..........BBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
        '',
      ],
    },
  ],
};

const todoTakatora = lord(
  [
    '.....................GGG',
    '..........G..........GGG',
    '..........GGGGGGG....GGG',
    '.........GGGGGGGGGGGGGGG',
    '........GGGGGGGGGGGGGGGG',
    '......GGGGGGGGGGGGGGGGGG',
    '...........GGGGGGGGGGGGG',
    '................GGGGGGGG',
    ...HELMET,
    ...FACE,
  ],
  {
    N: NQ.night,
    L: NQ.slate,
    G: NQ.gold,
    Y: NQ.cream,
    R: NQ.red,
    K: NQ.navy,
    S: NQ.denim,
    T: NQ.night,
    H: NQ.slate,
    C: NQ.bark,
    M: NQ.hairBlack,
  },
  { [NQ.navy]: NQ.ink, [NQ.denim]: NQ.navy },
);

export const MIE: Readonly<Record<string, MonsterDesign>> = {
  'mie-iganin': iganin,
  'mie-iga-jonin': igaJonin,
  'mie-kuwanaguri': kuwanaguri,
  'mie-shinkirou-gai': shinkirouGai,
  'mie-donabee': donabee,
  'mie-gutsugutsu-don': gutsugutsuDon,
  'mie-akoyan': akoyan,
  'mie-shinju-hime': shinjuHime,
  'mie-midboss-oosansho-ou': oosanshoOu,
  'mie-midboss-oosansho-ou.field': oosanshoOuField,
  'mie-boss-iseebi-taisho': iseebiTaisho,
  'mie-boss-iseebi-taisho.p0': iseebiTaishoP0,
  'mie-lastboss-todo-takatora': todoTakatora,
};
