/** 宮城のモンスター（docs/05 §2、docs/06 §6.3〜6.6） */
import { NQ } from '../palette';
import type { MonsterDesign } from './design';
import { LAST_BOSSES } from './lastbosses';

/** ササカマウオ：笹の葉の形の かまぼこの魚。こんがり焼き目と青いひれ（ミズ） */
const sasakamaUo: MonsterDesign = {
  size: 32,
  colors: {
    C: NQ.beige,
    T: NQ.tan,
    K: NQ.brown,
    F: NQ.azure,
    S: NQ.sky,
    W: NQ.white,
    p: NQ.blush,
    M: NQ.berry,
  },
  rim: { [NQ.beige]: NQ.sand, [NQ.azure]: NQ.blue },
  rimDepth: 1,
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '...............F',
        '..............FF',
        '..............CC',
        '.............CCC',
        '............CCCC',
        '...........CCCCC',
        '..........CCCCCC',
        '.........CCCCCCC',
        '........CCCCCCCC',
        '........CCCCCCCC',
        '.......CCCWWCCCC',
        '.......CCCWoCCCC',
        '......CCCCWoCCCC',
        '......CCCpCCCCCC',
        '......CCCCCCCCoo',
        '.....FCCCCCCCCoM',
        '....FFCCCCCCCCCo',
        '...FFFCCCCCCCCCC',
        '...FFFCCCCCCCCCC',
        '....FF.CCCCCCCCC',
        '.....F.CCCCCCCCC',
        '........CCCCCCCC',
        '.........CCCCCCC',
        '..........CCCCCC',
        '...........CCCCC',
        '............CCCC',
        '.............CCC',
        '...........FFFFF',
        '.........FFFFF..',
        '.......FFFF.....',
      ],
    },
    // 焼き目（ななめの 3 本）
    { x: 9, y: 20, rows: ['...TK...TK...TK', '..TK...TK...TK.', '.TK...TK...TK..', 'TK...TK...TK...'] },
    // つや
    { x: 9, y: 6, rows: ['.W', 'W.'] },
    { x: 3, y: 17, rows: ['..S', '.S.'] },
  ],
};

/** ズンダマル：ずんだ（えだまめのあん）を かぶった おもち。頭に えだまめ（モリ） */
const zundamaru: MonsterDesign = {
  size: 32,
  colors: {
    P: NQ.paper,
    G: NQ.leaf,
    g: NQ.green,
    L: NQ.lime,
    Y: NQ.sprout,
    W: NQ.white,
    p: NQ.blush,
    M: NQ.berry,
  },
  rim: { [NQ.paper]: NQ.cloud, [NQ.leaf]: NQ.green },
  rimDepth: 2,
  layers: [
    // おもち
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
        '..........PPPPPP',
        '.......PPPPPPPPP',
        '.....PPPPPPPPPPP',
        '....PPPPPPPPPPPP',
        '...PPPPPPPPPPPPP',
        '...PPPPPPPPPPPPP',
        '..PPPPPPPPPPPPPP',
        '..PPPPPPPPPPPPPP',
        '..PPPPPPPPPPPPPP',
        '..PPPPPPPPPPPPPP',
        '..PPPPPPPPPPPPPP',
        '..PPPPPPPPPPPPPP',
        '..PPPPPPPPPPPPPP',
        '..PPPPPPPPPPPPPP',
        '..PPPPPPPPPPPPPP',
        '..PPPPPPPPPPPPPP',
        '..PPPPPPPPPPPPPP',
        '..PPPPPPPPPPPPPP',
        '..PPPPPPPPPPPPPP',
        '...PPPPPPPPPPPPP',
        '....PPPPPPPPPPPP',
        '......PPPPPPPPPP',
        '.........PPPPPPP',
      ],
    },
    // ずんだ（たれている）
    {
      mirror: true,
      y: 8,
      rows: [
        '..........GGGGGG',
        '.......GGGGGGGGG',
        '.....GGGGGGGGGGG',
        '....GGGGGGGGGGGG',
        '...GGGGGGGGGGGGG',
        '...GGGGGGGGGGGGG',
        '..GGGGGGGGGGGGGG',
        '..GGGGGGGGGGGGGG',
        '..GGGGGGGGGGGGGG',
        '..GGGGGGGGGGGGGG',
        '..GGGGGGGGGGGGGG',
        '..GGGGGGGGGGGGGG',
        '..GGGGGGGGGGGGGG',
        '...GGGGGGGGGGGGG',
        '...GGG.GGGGG.GGG',
        '....G..GGGG...G.',
        '.......GGG......',
        '........G.......',
      ],
    },
    // まめのつぶつぶ
    {
      mirror: true,
      y: 9,
      rows: [
        '................',
        '..........LL....',
        '......LL..gg....',
        '......gg........',
        '................',
        '....LL..........',
        '....gg..........',
        '................',
        '................',
        '................',
        '...LL...........',
        '...gg...........',
        '................',
        '.....LL.........',
        '.....gg.........',
      ],
    },
    // かお
    {
      mirror: true,
      y: 15,
      rows: [
        '.........WW.....',
        '.........Wo.....',
        '.........Wo.....',
        '........p....o..',
        '..............oo',
      ],
    },
    // えだまめ（頭の上に ななめに のっている）
    {
      x: 9,
      y: 2,
      rows: ['..........ggg.', '.......GGGLLg.', '...GGGLLGGGGg.', 'GGGLLGGGGGgg..', 'gggggggggg....'],
    },
    // つや
    { x: 7, y: 10, rows: ['.Y', 'Y.'] },
  ],
};

/** コケシーナ：鳴子こけしの 人形兵。黒い おかっぱ、赤い かみかざり、菊の もよう（ツチ） */
const kokeshina: MonsterDesign = {
  size: 32,
  colors: {
    H: NQ.hairBlack,
    h: NQ.slate,
    S: NQ.skinLight,
    B: NQ.beige,
    R: NQ.red,
    r: NQ.brick,
    G: NQ.leaf,
    g: NQ.green,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.beige]: NQ.sand, [NQ.skinLight]: NQ.sand },
  rimDepth: 1,
  layers: [
    // あたま・かみ
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '..........HHHHHH',
        '.......HHHHHHHHH',
        '.....HHHHHHHHHHH',
        '....HHHHHHHHHHHH',
        '....HHHHHHHHHHHH',
        '...HHHHHHHHHHHHH',
        '...HHHHHHHHHHHHH',
        '...HHHHSSSSSSSSS',
        '...HHHSSSSSSSSSS',
        '..HHHHSSSSSSSSSS',
        '..HHHSSSSWWSSSSS',
        '..HHHSSSSWoSSSSS',
        '..HHHSSSSWoSSSSS',
        '..HHHSSSpSSSSSSS',
        '...HHSSSSSSSSSSR',
        '....HSSSSSSSSSSS',
        '......SSSSSSSSSS',
      ],
    },
    // かみの つや
    { mirror: true, y: 3, rows: ['................', '..........hhh...', '........hh......'] },
    // 赤い かみかざり
    { mirror: true, y: 2, rows: ['.....R', '....RRR', '...RrR', '....R'] },
    // からだ（こけしの どう）。まん中に 菊の花、両わきに 葉
    {
      mirror: true,
      y: 19,
      rows: [
        '........RRRRRRRR',
        '........rrrrrrrr',
        '........BBBBBBRB',
        '........BBBBBRRR',
        '........BBBBRRrR',
        '........BBGGRrRr',
        '........BGgGRrRr',
        '........BGGBRRrR',
        '........BBBBBRRR',
        '........BBBBBBRB',
        '........GGGGGGGG',
        '.......BBBBBBBBB',
      ],
    },
  ],
};

/** タナバタドリ：七夕の ふきながしを つばさと 尾に した 大きな鳥。胸に くす玉（カゼ・中ボス） */
const tanabataDori: MonsterDesign = {
  size: 40,
  colors: {
    A: NQ.aqua,
    m: NQ.mint,
    Y: NQ.gold,
    y: NQ.ochre,
    R: NQ.red,
    r: NQ.brick,
    B: NQ.azure,
    b: NQ.blue,
    G: NQ.leaf,
    g: NQ.green,
    V: NQ.violet,
    v: NQ.indigo,
    W: NQ.white,
  },
  rim: { [NQ.aqua]: NQ.teal },
  rimDepth: 2,
  layers: [
    // つばさの 上の はね（ぎざぎざ）
    { mirror: true, y: 3, rows: ['..m', '.....', '.....m', '', '........m', '', '', '...........m'] },
    // 頭の かざり羽（王冠の 両わきに はねあがる）
    { mirror: true, y: 1, rows: ['...........m', '............m', '............mA', '.............A'] },
    {
      mirror: true,
      rows: [
        '....................',
        '...............Y...Y',
        '...............YY.YY',
        '.m.............YYYYR',
        '.Am............yyyyy',
        '.AAmm.........AAAAAA',
        '.RAAAm.......AAooAAA',
        '.RrAAAm.....mAAWWoAA',
        '.RrYyAAmm..mmAAWWoAA',
        '.RrYyBAAAm..mAAWooAY',
        '.RrYyBbAAAm..AAAAAYY',
        '.RrYyBbGgAAm.AAAAAyY',
        '.RrYyBbGgVAAm.AAAAAy',
        '.RrYyBbGgVvAAAAAAmmm',
        '.RrYyBbGgVvRAAAAAmmy',
        '.RrYyBbGgVvRrAAAAYYY',
        '.RrYyBbGgVvRrAAAYWYR',
        '.RrYyBbGgVvRrAAAYYRY',
        '.RrYyBbGgVvRrAAARYYY',
        '.RrYyBbGgVvRrAAAYRYY',
        '.RrYyBbGgVvRrAAAyYYR',
        '.RrYyBbGgVvRrAAAAyyy',
        '.RrYyBbGgVvRrAAAAAAA',
        '.RrYyBbGgVvRrAAAAAAA',
        '.RrYyBbGgVvRrAAAAAAA',
        '.RrYyBbGgV.RrAAAAAAA',
        '.RrYyB.Gg..R.AAAAAAA',
        '.R.Yy..Gg.....AAAAAA',
        '...Yy..G.......AAAAA',
        '...Y..........YyVvRr',
        '..............YyVvRr',
        '..............YyVvRr',
        '..............YyVvRr',
        '..............YyVvRr',
        '..............YyVvRr',
        '..............YyVvRr',
        '..............YyVvRr',
        '............YYYYYvRr',
        '............y.y.y.R.',
      ],
    },
  ],
};

/** フィールドに立つ タナバタドリ（32×32。色を へらした 小さい版） */
const tanabataDoriField: MonsterDesign = {
  size: 32,
  colors: {
    A: NQ.aqua,
    m: NQ.mint,
    Y: NQ.gold,
    y: NQ.ochre,
    R: NQ.red,
    B: NQ.azure,
    G: NQ.leaf,
    V: NQ.violet,
    W: NQ.white,
  },
  rim: { [NQ.aqua]: NQ.teal },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '............Y..Y',
        '............YYYR',
        '.mm.........yyyy',
        '.AAmm......AAAAA',
        '.R.AAm....AAoAAA',
        '.R.Y.Amm..AWWAAA',
        '.R.Y.BAAm.AWoAAY',
        '.R.Y.B.GAmAWoAYY',
        '.R.Y.B.G.AAAAAAy',
        '.R.Y.B.G.VAAAmmy',
        '.R.Y.B.G.VAAAYYY',
        '.R.Y.B.G.VAAYRYY',
        '.R.Y.B.G.VAAYYYR',
        '.R.Y.B.G.VAARYYY',
        '.R.Y.B.G.VAAyYRY',
        '.R.Y.B.G.VAAAyyy',
        '.R.Y.B.G.VAAAAAA',
        '.R.Y.B.G.VAAAAAA',
        '.R.Y.B.G.VAAAAAA',
        '.R.Y.B.G..AAAAAA',
        '.R.Y...G...AAAAA',
        '...Y........AAAA',
        '...........YyVRR',
        '...........YyVRR',
        '...........YyVRR',
        '...........YyVRR',
        '...........YyVRR',
        '...........YyVRR',
        '.........YYYY.RR',
        '.........y.y...R',
      ],
    },
  ],
};

/** ミカヅキショウグン：仙台城あとで 目をさました、三日月の かぶとの 黒い よろい（中は からっぽ）。ヤミ・県ボス */
const mikazukiShogun: MonsterDesign = {
  size: 48,
  colors: {
    // 三日月（P0 で 月の光の色に かわる）
    M: NQ.gold,
    m: NQ.ochre,
    C: NQ.cream,
    // 黒うるしの よろいと 金の ふち
    K: NQ.night,
    k: NQ.slate,
    Y: NQ.gold,
    y: NQ.ochre,
    R: NQ.red,
    e: NQ.cream,
    // 刀
    E: NQ.silver,
    W: NQ.white,
    // じんばおり（うしろの マント）
    V: NQ.violet,
    i: NQ.indigo,
    L: NQ.lavender,
    // 仙台城の 石垣
    G: NQ.gray,
  },
  layers: [
    // じんばおり（よろいの うしろから のぞく むらさきの マント）
    {
      mirror: true,
      y: 21,
      rows: [
        '...LVVVV',
        '..LVVVVV',
        '..LVVVVV',
        '.LVVVVVV',
        '.LVVViVVVi',
        '.LVVViVVVi',
        '.LVVViVVVi',
        '.LVVViVVVi',
        '.LVVViVVVi',
        '.LVVViVVVi',
        '.LVVViVVVi',
        '.LVVViVVVi',
        '.LVVViVVVi',
        '.LVVViVVVi',
        '.LVVViVVVi',
        '.LVVViVVVi',
        '.LVVViVVVi',
        '.LVVViVVVi',
        '.LVViVVVVi',
        '.LV.VVViVi',
        '.L..VV.V.i',
        '.....V....',
      ],
    },
    // 仙台城の 石垣（足もと）
    {
      mirror: true,
      y: 43,
      rows: [
        '..EEEEEEEEEEEEEEEEEEEEEE',
        '..GGGGkGGGGGGkGGGGGGkGGG',
        '.kkkkkkkkkkkkkkkkkkkkkkk',
        '.GGkGGGGGGkGGGGGGkGGGGGG',
      ],
    },
    // かぶと・しころ・めんぼお・そで・どう・草ずり（黒うるし。ふちだけ 金）
    {
      mirror: true,
      rows: [
        '........................',
        '...................Y...Y',
        '...................YY.YY',
        '...................YYYYR',
        '..................yyyyyy',
        '.................KKKKKKK',
        '...............KkkKKkKKk',
        '..............KkKKKkKKkK',
        '.............KkKKKkKKkKK',
        '.............KkKKkKKkKKK',
        '............KkKKkKKkKKkK',
        '............KKKkKKkKKkKK',
        '............KKKkKKkKKkKK',
        '......YYYY..KKkKKkKKkKKK',
        '.....YKKKKY.KKkKKkKKkKKK',
        '....YKKKKKKYYYYYYYYYYYYY',
        '....YKKKKKKKKKyyyyyyyyyy',
        '...YKKKKKKKKKKoooooooooo',
        '...YkkkkkkkkkKooeeeooooo',
        '...YKKKKKKKKKKoooeeeoooo',
        '...YYYYYYYYYYKKkkkkkkkkk',
        '....YYYYYYYoKKkkkYYYkkKK',
        '....kKKKKKKoYYYYYYYYYYYY',
        '...kKKKKKKKoKKKKKKKKKKKK',
        '...kkkkkkkkoKKKKKKKKKKKK',
        '...kKKKKKKKoKKKKKKKKKKKK',
        '..kKKKKKKKKoKKKKKKKKKKKK',
        '..kkkkkkkkkoKKKKKKKKKKKK',
        '..kKKKKKKKKoKKKKKKKKKKKK',
        '.kKKKKKKKKKokkkkkkkkkkkk',
        '.YYYYYYYYYYoKKKKKKKKKKKK',
        '.yyyyyyyyyy.KKKKKoKKKKKK',
        '.......KKKKoKKKKKoKKKKKK',
        '.......kkkkokkkkkokkkkkk',
        '......KKKKKoKKKKKoKKKKKK',
        '......KKKKKoKKKKKoKKKKKK',
        '......kkkkkokkkkkokkkkkk',
        '.....KKKKKKoKKKKKoKKKKKK',
        '.....YYYYYYoYYYYYoYYYYYY',
        '.....yyyyyyoyyyyyoyyyyyy',
        '...........KKKKKKKK.....',
        '...........kYkkYkkK.....',
        '...........KYKKYKKK.....',
        '..........KKKKKKKKKK....',
      ],
    },
    // うでと こぶし（刀の つかを 両手で おさえる）
    {
      mirror: true,
      y: 24,
      rows: [
        '..................Ykkkk',
        '............kkkkkkYkkkk',
        '............KKKKKKYkKkK',
        '............KKKKKKYkKkK',
        '..................Ykkkk',
      ],
    },
    // 三日月の まえだて（かぶとの 前に 大きく ひろがる 金の 月）
    {
      mirror: true,
      rows: [
        '........................',
        '.C......................',
        '.mC.....................',
        '..MC....................',
        '..mMC...................',
        '...mMCC.................',
        '....mMMC................',
        '.....mMMCC..............',
        '......mmMMCC............',
        '........mMMMCCC.........',
        '.........mmMMMMCCC......',
        '...........mmMMMMMCCCCCC',
        '.............mmMMMMMMMMM',
        '...............mmmMMMMMM',
        '..................mmmMMM',
        '.....................mmm',
      ],
    },
    // 刀（つかを 両手で おさえ、石垣に つきたてる）
    {
      x: 20,
      y: 22,
      rows: [
        '...YY',
        '...Ek',
        '...kE',
        '...Ek',
        '...kE',
        '...Ek',
        '...kE',
        '...Ek',
        'YYYYYYYY',
        'yyyyyyyy',
        '...WE',
        '...WE',
        '...WE',
        '...WE',
        '...WE',
        '...WE',
        '...WE',
        '...WE',
        '...WE',
        '...WE',
        '...WE',
      ],
    },
  ],
};

/** 後半：三日月が 月の光で 白く かがやき、まわりに 光の つぶ（ヒカリ） */
const mikazukiShogunP0: MonsterDesign = {
  ...mikazukiShogun,
  colors: { ...mikazukiShogun.colors, M: NQ.cream, m: NQ.gold, C: NQ.white },
  layers: [
    ...mikazukiShogun.layers,
    // 月の光のつぶ
    { mirror: true, rows: ['', '......C', '.....CWC', '......C', '', '.........W', '', '', '..W'] },
  ],
};

/** ササカマブシ：ササカマウオが しんかした 笹かまの さむらい。はちまきと 笹の葉の かたな（ミズ） */
const sasakamaBushi: MonsterDesign = {
  size: 32,
  colors: {
    C: NQ.beige,
    T: NQ.tan,
    K: NQ.brown,
    F: NQ.azure,
    b: NQ.blue,
    S: NQ.sky,
    W: NQ.white,
    p: NQ.blush,
    G: NQ.leaf,
    g: NQ.green,
  },
  rim: { [NQ.beige]: NQ.sand, [NQ.azure]: NQ.blue },
  rimDepth: 1,
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '...............F',
        '..............FF',
        '..............CC',
        '.............CCC',
        '............CCCC',
        '...........CCCCC',
        '..........CCCCCC',
        '.........WWWWWWW',
        '........WWWWWWWW',
        '.......CCoCCCCCC',
        '......CCCCooCCCC',
        '......CCCCWWCCCC',
        '.....CCCCCWoCCCC',
        '.....CCCCCWoCCCC',
        '.....CCCCpCCCCCC',
        '....FCCCCCCCCoCC',
        '...FFCCCCCCCCCoo',
        '..FFFCCCCCCCCCCC',
        '..FFFCCCCCCCCCCC',
        '..FFSCCCCCCCCCCC',
        '...FFCCCCCCCCCCC',
        '....FTTTTTTTTTTT',
        '.....bbbbbbbbbbb',
        '.....bbbbbFbbbbb',
        '....bbbbbbFbbbFb',
        '....bbbbbbFbbbFb',
        '....bbbbbbFbbbFb',
        '...bbbbbbbFbbbFb',
        '...FFFFF........',
        '..FFFFFF........',
      ],
    },
    // 焼き目（おなかに ななめの 3 本）
    { x: 7, y: 18, rows: ['..TK...TK...TK.', '.TK...TK...TK..', 'TK...TK...TK...'] },
    // はちまきの むすび目（右に なびく）
    { x: 23, y: 7, rows: ['.WW', 'WW.W', '.W..W', '.....W'] },
    // 笹の葉の かたな（右手）
    {
      x: 26,
      y: 1,
      rows: [
        '...G',
        '..GG',
        '..GgG',
        '.GGgG',
        '.GGgG',
        'GGGgG',
        'GGGgG',
        '.GGgG',
        '.GGgG',
        '..Gg',
        '..Gg',
        '...g',
        '..TTT',
        '...K',
        '...K',
        '...K',
        '...K',
      ],
    },
    // つや
    { x: 10, y: 4, rows: ['.W', 'W.'] },
  ],
};

/** ズンダゴン：ズンダマルが しんかした 大きな ずんだもち。えだまめの つの、ずんだの たてがみ（モリ） */
const zundagon: MonsterDesign = {
  size: 32,
  colors: {
    P: NQ.paper,
    G: NQ.leaf,
    g: NQ.green,
    L: NQ.lime,
    Y: NQ.sprout,
    W: NQ.white,
    p: NQ.blush,
    M: NQ.berry,
  },
  rim: { [NQ.paper]: NQ.cloud, [NQ.leaf]: NQ.green },
  rimDepth: 2,
  layers: [
    // えだまめの つの（両がわ）
    {
      mirror: true,
      rows: ['', '.....gg', '.....GLg', '......GLg', '.......GLg', '........GGg', '.........Gg'],
    },
    // おもち（両わきに ずんぐりした うで）
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '..........PPPPPP',
        '.......PPPPPPPPP',
        '.....PPPPPPPPPPP',
        '....PPPPPPPPPPPP',
        '....PPPPPPPPPPPP',
        '...PPPPPPPPPPPPP',
        '...PPPPPPPPPPPPP',
        '...PPPPPPPPPPPPP',
        '...PPPPPPPPPPPPP',
        '...PPPPPPPPPPPPP',
        '...PPPPPPPPPPPPP',
        '...PPPPPPPPPPPPP',
        '.PPPPPPPPPPPPPPP',
        '.PPoPPPPPPPPPPPP',
        '.PPoPPPPPPPPPPPP',
        '.PPoPPPPPPPPPPPP',
        '..PPPPPPPPPPPPPP',
        '...PPPPPPPPPPPPP',
        '...PPPPPPPPPPPPP',
        '...PPPPPPPPPPPPP',
        '...PPPPPPPPPPPPP',
        '...PPPPPPPPPPPPP',
        '....PPPPPPPPPPPP',
        '.....PPPPPPPPPPP',
        '.....PPPPPPPPPPP',
        '.....PPPP.......',
      ],
    },
    // ずんだ（大きな たてがみの ように たれる）
    {
      mirror: true,
      y: 5,
      rows: [
        '..........GGGGGG',
        '.......GGGGGGGGG',
        '.....GGGGGGGGGGG',
        '....GGGGGGGGGGGG',
        '....GGGGGGGGGGGG',
        '...GGGGGGGGGGGGG',
        '...GGGGGGGGGGGGG',
        '...GGGGGGGGGGGGG',
        '...GGGGGGGGGGGGG',
        '...GGGGGGGGGGGGG',
        '...GGGGGGGGGGGGG',
        '...GGGGGGGGGGGGG',
        '.GGGGGGGGGGGGGGG',
        '...GGGGGGGGGGGGG',
        '...GGGGGGGGGGGGG',
        '...GGGG.GGGGGGGG',
        '...GGG..GGGGG.GG',
        '...GG....GGG...G',
        '...G......G.....',
        '...G............',
      ],
    },
    // まめの つぶつぶ
    {
      mirror: true,
      y: 6,
      rows: [
        '................',
        '..........LL....',
        '......LL..gg....',
        '......gg........',
        '................',
        '....LL..........',
        '....gg..........',
        '................',
        '................',
        '................',
        '................',
        '....LL..........',
        '....gg..........',
        '................',
        '......LL........',
        '......gg........',
      ],
    },
    // かお（きりっとした まゆ）
    {
      mirror: true,
      y: 12,
      rows: [
        '........o.......',
        '.........oo.....',
        '.........WW.....',
        '.........Wo.....',
        '.........Wo.....',
        '........p.......',
        '.............ooo',
        '..............MM',
      ],
    },
    // つや
    { x: 7, y: 8, rows: ['.Y', 'Y.'] },
  ],
};

/** コケシヒメ：コケシーナが しんかした こけしの おひめさま。花もようの きもの、大きな 菊の かんざし、せんす（ツチ） */
const kokeshiHime: MonsterDesign = {
  size: 32,
  colors: {
    H: NQ.hairBlack,
    h: NQ.slate,
    S: NQ.skinLight,
    R: NQ.red,
    r: NQ.brick,
    W: NQ.white,
    Y: NQ.gold,
    y: NQ.ochre,
    G: NQ.leaf,
    p: NQ.blush,
  },
  rim: { [NQ.skinLight]: NQ.sand, [NQ.red]: NQ.brick },
  rimDepth: 1,
  layers: [
    // あたま・かみ
    {
      mirror: true,
      rows: [
        '................',
        '..........HHHHHH',
        '.......HHHHHHHHH',
        '......HHHHHHHHHH',
        '.....HHHHHHHHHHH',
        '....HHHHHHHHHHHH',
        '....HHHHHHHHHHHH',
        '....HHHHHHHHHHHH',
        '....HHHSSSSSSSSS',
        '...HHHSSSSSSSSSS',
        '...HHHSSSSSSSSSS',
        '...HHHSSSWWSSSSS',
        '...HHHSSSWoSSSSS',
        '...HHHSSSWoSSSSS',
        '....HHSSpSSSSSSR',
        '.....HHSSSSSSSSS',
      ],
    },
    // かみの つや
    { mirror: true, y: 2, rows: ['', '..........hhh', '........hh'] },
    // きもの（ふりそでの そで・金の おび・花もよう・みどりの すそ）
    {
      mirror: true,
      y: 16,
      rows: [
        '.........RRRWWWW',
        '....RRRRRRRRRWWW',
        '...RRRRRRRRRRRWW',
        '..RRRWRRrRRRRRRR',
        '..RRRRRRrRRRRRRR',
        '..RRRRRRrYYYYYYY',
        '..RRRRRRryyyyyyy',
        '..RRRWRRrYYYYYYY',
        '..RRRRRRrRRRRRRR',
        '..RRRRRRrRRRWRRR',
        '..RRRRRR.RRRRRRR',
        '..RRWRR..RRRRRRR',
        '...RRR...RRRRRRR',
        '.........GGGGGGG',
        '..........HH....',
      ],
    },
    // 大きな 菊の かんざし（左）と たれかざり
    { x: 2, y: 1, rows: ['..WRW', '.WRRRW', 'WRRYRRW', '.WRRRW', '..WRW', '...Y', '...Y', '...Y'] },
    // 小さな かみかざり（右）
    { x: 24, y: 2, rows: ['.R', 'RRR', 'RrR', '.R'] },
    // ひらいた せんす（右手。白い 紙に 金の ふち）
    { x: 20, y: 18, rows: ['.YYYYYYY', 'YWyWWyWY', '.YWyyWY', '..YWWY', '...yy', '...SS'] },
  ],
};

/** シラトリン：伊豆沼に 来る 白鳥の 子。ふわふわの 白い からだ・長い 首・黄色と 黒の くちばし・足もとに 水の わ（ミズ） */
const shiratorin: MonsterDesign = {
  size: 32,
  colors: {
    W: NQ.white,
    c: NQ.cloud,
    Y: NQ.yellow,
    N: NQ.night,
    p: NQ.blush,
    S: NQ.sky,
    A: NQ.azure,
  },
  rim: { [NQ.white]: NQ.cloud },
  rimDepth: 2,
  layers: [
    {
      y: 5,
      rows: [
        '.......WWWW.....................',
        '......WWWWWW....................',
        '.....WWWWWWWW...................',
        '.....WWWWWWWW...................',
        '.....WWWWWWWW...................',
        '......WWWWWWW...................',
        '........WWWWW...................',
        '.........WWWW...................',
        '.........WWWW...................',
        '..........WWWW..................',
        '..........WWWW..................',
        '..........WWWW......WWW.........',
        '.........WWWWW....WWWWWWW.WW....',
        '........WWWWWW..WWWWWWWWWWWWW...',
        '.......WWWWWWWWWWWWWWWWWWWWWW...',
        '......WWWWWWWWWWWWWWWWWWWWWWW...',
        '.....WWWWWWWWWWWWWWWWWWWWWWWW...',
        '.....WWWWWWWWWWWWWWWWWWWWWWWW...',
        '.....WWWWWWWWWWWWWWWWWWWWWWWW...',
        '.....WWWWWWWWWWWWWWWWWWWWWWW....',
        '......WWWWWWWWWWWWWWWWWWWWWW....',
        '.......WWWWWWWWWWWWWWWWWWWW.....',
        '.........WWWWWWWWWWWWWWWW.......',
      ],
    },
    // つばさの はね
    { x: 15, y: 21, rows: ['.c..c..c..c.', 'c.cc.cc.cc.c'] },
    // くちばし（根もとは 黄色、先は 黒）
    { x: 1, y: 8, rows: ['...YYY.', 'NNYYYYY', '.NNYY..'] },
    // 頭の てっぺんの 毛・目・ほっぺ
    { x: 9, y: 4, rows: ['W'] },
    { x: 8, y: 7, rows: ['Wo', 'oo', 'oo'] },
    { x: 9, y: 10, rows: ['pp'] },
    // 水の わ
    {
      y: 27,
      rows: [
        '..SSSS...................SSSS...',
        '....SSSAAAAAAAAAAAAAAAAAASSS....',
        '........SSSS..........SSSS......',
      ],
    },
  ],
};

/** オオハクチョウ：シラトリンの しんか。大きく ひろげた つばさ・長い 首・氷の 小さな かんむり・雪の きらめき（ミズ） */
const oohakucho: MonsterDesign = {
  size: 32,
  colors: {
    W: NQ.white,
    c: NQ.cloud,
    I: NQ.ice,
    S: NQ.sky,
    A: NQ.azure,
    Y: NQ.yellow,
    N: NQ.night,
  },
  rim: { [NQ.white]: NQ.cloud, [NQ.ice]: NQ.sky },
  rimDepth: 1,
  layers: [
    // むこうの つばさ（てまえの つばさの 下から 羽の 先が のぞく）
    {
      x: 18,
      y: 6,
      rows: [
        '...........I.',
        '.........IIII',
        '........IIII.',
        '.......IIIIII',
        '......IIIIII.',
        '......IIIIIII',
        '.....IIIIIII.',
        '....IIIIIIII.',
        '....IIIIIII..',
        '...IIIIIIII..',
        '..IIIIIII....',
        '..IIIIII.....',
        '...IIII......',
      ],
    },
    // てまえの つばさ
    {
      y: 1,
      rows: [
        '........................WWW.....',
        '.....................WWWWWWW.W..',
        '...................WWWWWWWWWW...',
        '..................WWWWWWWWWWW.W.',
        '.................WWWWWWWWWWWWW..',
        '.................WWWWWWWWWWWW.W.',
        '................WWWWWWWWWWWWWW..',
        '................WWWWWWWWWWWW.W..',
        '................WWWWWWWWWWWWW...',
        '................WWWWWWWWWWW.W...',
        '................WWWWWWWWWWWW....',
        '................WWWWWWWWWW.W....',
        '................WWWWWWWWWWW.....',
        '................WWWWWWWWW.W.....',
        '................WWWWWWWWWW......',
        '................WWWWWWWWW.......',
        '................WWWWWWWW........',
        '................WWWWWWWW........',
        '................WWWWWWW.........',
        '.................WWWWW..........',
      ],
    },
    // はねの すじ
    {
      y: 3,
      rows: [
        '.........................ccc....',
        '......................ccc.......',
        '.....................c.....ccc..',
        '....................c...cc......',
        '...................c...c........',
        '...................c..c.........',
        '..................c..c..........',
        '..................c..c..........',
        '..................c..c..........',
        '..................c..c..........',
        '..................c..c..........',
        '..................c..c..........',
        '..................c.c...........',
        '..................cc............',
      ],
    },
    // からだ・しっぽ
    {
      x: 4,
      y: 20,
      rows: [
        '...WWWWWWWWWWWWWWWWWWWW.',
        '..WWWWWWWWWWWWWWWWWWWWWW',
        '.WWWWWWWWWWWWWWWWWWWWWWW',
        '.WWWWWWWWWWWWWWWWWWWWWW.',
        '.WWWWWWWWWWWWWWWWWWWWWW.',
        '..WWWWWWWWWWWWWWWWWWWW..',
        '...WWWWWWWWWWWWWWWWWW...',
        '.....WWWWWWWWWWWWWW.....',
      ],
    },
    { x: 25, y: 18, rows: ['...W', '..WW', '.WWW'] },
    // 首と 頭
    {
      y: 3,
      rows: [
        '......WWW.......................',
        '.....WWWWW......................',
        '....WWWWWWW.....................',
        '....WWWWWWW.....................',
        '.....WWWWWW.....................',
        '.......WWWW.....................',
        '........WWW.....................',
        '.........WWW....................',
        '.........WWW....................',
        '..........WWW...................',
        '..........WWW...................',
        '..........WWW...................',
        '..........WWW...................',
        '.........WWW....................',
        '........WWWW....................',
        '........WWWW....................',
        '.......WWWWW....................',
        '......WWWWWW....................',
      ],
    },
    // くちばし・目
    { x: 1, y: 5, rows: ['...YY', 'NNYYY', '.NYY.'] },
    { x: 6, y: 4, rows: ['oo', 'oo'] },
    // 氷の かんむり
    { x: 5, y: 1, rows: ['..I..', 'I.W.I', 'SISIS'] },
    // 水
    { x: 2, y: 28, rows: ['...SSSAAAAAAAAAAAAAASSS...', 'SSS....................SSS'] },
    // 雪の きらめき
    { x: 1, y: 12, rows: ['.I.', 'IWI', '.I.'] },
    { x: 2, y: 18, rows: ['W'] },
    { x: 12, y: 1, rows: ['.I.', 'IWI', '.I.'] },
  ],
};

/** タンヤッキー：炭火の あみの 上で はねる 牛タン。こんがりした やき目、頭に 小さな 炎（ヒノ） */
const tanyakki: MonsterDesign = {
  size: 32,
  colors: {
    M: NQ.blush,
    m: NQ.berry,
    T: NQ.brown,
    W: NQ.white,
    K: NQ.night,
    S: NQ.silver,
    V: NQ.vermilion,
    A: NQ.apricot,
    G: NQ.gold,
  },
  rim: { [NQ.blush]: NQ.berry },
  rimDepth: 2,
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '..............V.',
        '.............VAV',
        '..............V.',
        '.........MMMMMMM',
        '.......MMMMMMMMM',
        '......MMMMMMMMMM',
        '.....MMMMMMMMMMM',
        '.....MMTTMMMTTMM',
        '....MMMMMMMMMMMM',
        '....MMMMMMMMMMMM',
        '....MMMMMWWMMMMM',
        '....MMMMMWoMMMMM',
        '....MMMMMWoMMMMM',
        '....MmmMMMMMMMMM',
        '....MMMMMMMMMoMM',
        '....MMTTMMMTTMMo',
        '....MMMMMMMMMMMM',
        '.....MMMMMMMMMMM',
        '.....MMMMMMMMMMM',
        '......MMMMMMMMMM',
        '.......MMMMMMMMM',
        '.........MMMMMMM',
        '..........MM....',
        '..........MM....',
        '.....SSSSSSSSSSS',
        '.....KKKKKKKKKKK',
        '.....KVKKKVKKKVK',
        '.....KKKKKKKKKKK',
        '......SSSSSSSSSS',
      ],
    },
    // 炭火の ほのお
    { x: 1, y: 26, rows: ['.V', 'VA', '.V'] },
    { x: 28, y: 25, rows: ['V.', 'AV', 'V.'] },
    { x: 8, y: 9, rows: ['.G', 'G.'] },
  ],
};

/** オオスミビタン：タンヤッキーの しんか。せなかに 大きな 炭火の こんろを しょい、ほのおが 立ちのぼる（ヒノ） */
const ooSumibitan: MonsterDesign = {
  size: 32,
  colors: {
    M: NQ.blush,
    m: NQ.berry,
    T: NQ.brown,
    W: NQ.white,
    K: NQ.night,
    S: NQ.silver,
    V: NQ.vermilion,
    A: NQ.apricot,
    G: NQ.gold,
    C: NQ.cream,
  },
  rim: { [NQ.blush]: NQ.berry },
  rimDepth: 2,
  layers: [
    // せなかの こんろ（からだの うしろ）
    {
      mirror: true,
      x: 1,
      y: 8,
      rows: ['KKKKK', 'KSKSK', 'KKKKK', 'KSKSK', 'KKKKK', 'KSKSK', 'KKKKK', '.KKKK', '.KKKK'],
    },
    {
      mirror: true,
      rows: [
        '................',
        '.............V..',
        '............VAV.',
        '.........V...V..',
        '........VAV.....',
        '.........V..MMMM',
        '.......MMMMMMMMM',
        '......MMMMMMMMMM',
        '......MMMMMMMMMM',
        '.....MMTTMMMTTMM',
        '.....MMMMMMMMMMM',
        '.....MMMoooMMMMM',
        '.....MMMMMMoooMM',
        '.....MMMMMWWMMMM',
        '.....MMMMMWoMMMM',
        '.....MMMMMWoMMMM',
        '.....MmmMMMMMMMM',
        '.....MMMMMMMMMoM',
        '.....MMTTMMMTTMo',
        '.....MMMMMMMMMMM',
        '.....MMMMMMMMMMM',
        '......MMMMMMMMMM',
        '......MMMMMMMMMM',
        '.......MMMMMMMMM',
        '.........MMMMMMM',
        '..........MM....',
        '..........MM....',
        '....SSSSSSSSSSSS',
        '....KKKKKKKKKKKK',
        '....KVKKKVKKKVKK',
        '....SSSSSSSSSSSS',
      ],
    },
    // もえあがる ほのお
    { x: 1, y: 24, rows: ['.V.', 'VAV', 'VCV', '.V.'] },
    { x: 27, y: 23, rows: ['.V.', 'VAV', 'VCV', '.V.'] },
    { x: 9, y: 9, rows: ['.G', 'G.'] },
  ],
};

export const MIYAGI: Readonly<Record<string, MonsterDesign>> = {
  'miyagi-lastboss-date-masamune': LAST_BOSSES['miyagi-lastboss-date-masamune']!,
  'miyagi-tanyakki': tanyakki,
  'miyagi-oo-sumibitan': ooSumibitan,
  'miyagi-sasakama-uo': sasakamaUo,
  'miyagi-zundamaru': zundamaru,
  'miyagi-kokeshina': kokeshina,
  'miyagi-midboss-tanabata-dori': tanabataDori,
  'miyagi-midboss-tanabata-dori.field': tanabataDoriField,
  'miyagi-boss-mikazuki-shogun': mikazukiShogun,
  'miyagi-boss-mikazuki-shogun.p0': mikazukiShogunP0,
  'miyagi-sasakama-bushi': sasakamaBushi,
  'miyagi-zundagon': zundagon,
  'miyagi-kokeshi-hime': kokeshiHime,
  'miyagi-shiratorin': shiratorin,
  'miyagi-oohakucho': oohakucho,
};
