/** 大分県の モンスター（手描き。docs/06 §4・§6.3〜6.5 の 規格） */
import { NQ } from '../palette';
import type { MonsterDesign } from './design';

/**
 * 地図の まわり 1 ドットを ink にする（体の 上に 重ねる 部品を くっきり させる）。
 * 1 ドット 大きく なるので x-1, y-1 に 置く
 */
function ring(rows: readonly string[]): string[] {
  const w = Math.max(...rows.map((r) => r.length));
  const at = (x: number, y: number) => (rows[y]?.[x] ?? '.') !== '.';
  return Array.from({ length: rows.length + 2 }, (_, j) =>
    Array.from({ length: w + 2 }, (_, i) => {
      const x = i - 1;
      const y = j - 1;
      return !at(x, y) && (at(x - 1, y) || at(x + 1, y) || at(x, y - 1) || at(x, y + 1)) ? 'o' : '.';
    }).join(''),
  );
}

/** ユケムリン：湯おけの 温泉に つかって、頭に タオルを のせた ぽかぽかの 子。頭の 上に 3 本の 湯けむり（ヒノ） */
const yukemurin: MonsterDesign = {
  size: 32,
  colors: {
    W: NQ.white,
    c: NQ.cloud,
    S: NQ.sky,
    I: NQ.ice,
    A: NQ.apricot,
    C: NQ.cream,
    p: NQ.blush,
    T: NQ.tan,
    B: NQ.brown,
    K: NQ.bark,
  },
  rim: { [NQ.apricot]: NQ.vermilion, [NQ.tan]: NQ.brown },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '...............W',
        '.........W....W.',
        '........W.....W.',
        '........W......W',
        '.........W.....W',
        '.........W....W.',
        '..........WWWWWW',
        '........AWWWWWWW',
        '.......AAcSSSSSS',
        '......AAAAcccccc',
        '.....ACAAAAAAAAA',
        '.....CAAAAAAAAAA',
        '....AAAAAAWWAAAA',
        '....AAAAAAWoAAAA',
        '....AAAAAAWoAAAA',
        '....AAAAppAAAAoA',
        '....AAAAAAAAAAAo',
        '....AAAAAAAAAAAA',
        '.SSSISSSSSSSISSS',
        '.TTTTTTTTTTTTTTT',
        '.KKKKKKKKKKKKKKK',
        '..TTTBTTTBTTTBTT',
        '..TTTBTTTBTTTBTT',
        '..TTTBTTTBTTTBTT',
        '..KKKKKKKKKKKKKK',
        '...TTBTTTBTTTBTT',
        '...TTBTTTBTTTBTT',
        '...KKKKKKKKKKKKK',
        '....TTTTTTTTTTTT',
      ],
    },
  ],
};

/** ユブネドン（ユケムリンの しんか）：大きな 木の 湯ぶねに つかり、タオルの はちまき。ふとい 湯けむりと 大きな 口（ヒノ） */
const yubuneDon: MonsterDesign = {
  size: 32,
  colors: {
    W: NQ.white,
    S: NQ.sky,
    I: NQ.ice,
    A: NQ.apricot,
    C: NQ.cream,
    V: NQ.vermilion,
    p: NQ.blush,
    T: NQ.tan,
    B: NQ.brown,
    K: NQ.bark,
  },
  rim: { [NQ.apricot]: NQ.vermilion, [NQ.tan]: NQ.brown },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '.........W.....W',
        '........WW....WW',
        '........W.....W.',
        '.........W....WW',
        '.........WW....W',
        '..........W....W',
        '........AAAAAAAA',
        '......ACAAAAAAAA',
        '.....ACAAAAAAAAA',
        '....WWWWWWWWWWWW',
        '....SSSSSSSSSSSS',
        '....AAAAAAAAAAAA',
        '....AAAAAAooAAAA',
        '....AAAAAAWWAAAA',
        '....AAAAAAWoAAAA',
        '....AAAAAAWoAAAA',
        '....AAAAppAAAooo',
        '...AAAAAAAAAAoVV',
        '..AAAAAAAAAAAAoo',
        '.AASSSISSSSSSISS',
        '.KKKKKKKKKKKKKKK',
        '.KKTTTTTTTTTTTTT',
        '.KKTTTTTTTTTTTTT',
        '.KKBBBBBBBBBBBBB',
        '.KKTTTTTTTTTTTTT',
        '.KKTTTTTTTTTTTTT',
        '.KKBBBBBBBBBBBBB',
        '.KKTTTTTTTTTTTTT',
        '.KKKKKKKKKKKKKKK',
        '..KK............',
      ],
    },
    // はちまきの むすび目（左に なびく）
    { x: 1, y: 9, rows: ['WW.', '.WW', 'W..'] },
  ],
};

/** カボスッパ：まんまるの みどりの かぼす。ヘタと 2 まいの 葉、つぶつぶの 皮、すっぱくて すぼめた 口（モリ） */
const kabosuppa: MonsterDesign = {
  size: 32,
  colors: {
    F: NQ.forest,
    G: NQ.green,
    L: NQ.leaf,
    M: NQ.lime,
    Y: NQ.sprout,
    B: NQ.brown,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.leaf]: NQ.green },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '.........FF.....',
        '........FFGF....',
        '........FGFFF..B',
        '.........FFGFF.B',
        '...........FFFFB',
        '..........LLLLLL',
        '........LLLLLLLL',
        '......LLLLLLLLLL',
        '.....LLMYLLLLLLL',
        '....LLMMLLLLGLLL',
        '....LMMLLLLLLLLL',
        '...LLMLLLLLLLLLL',
        '...LLLLLGLLLLLLL',
        '...LLLLLLLLLLLLL',
        '...LLLLLLLWWLLLL',
        '...LGLLLLLWoLLLL',
        '...LLLLLLLWoLLLL',
        '...LLLLLppLLLLLL',
        '...LLLLLLLLLLLLo',
        '...LLLLLLLLLLLLo',
        '...LLLGLLLLLLLLL',
        '...LLLLLLLLLLLLL',
        '...LLLLLLLLLLGLL',
        '....LLLLLLLLLLLL',
        '....LLLLGLLLLLLL',
        '.....LLLLLLLLLLL',
        '......LLLLLLLLLL',
        '........LLLLLLLL',
        '..........LLLLGL',
      ],
    },
  ],
};

/** わぎりの かぼす（皮・白い わた・ふくろの すじ） */
const KABOSU_SLICE = [
  '...GGG...',
  '.GGWWWGG.',
  '.GYYWYYG.',
  'GYWYWYWYG',
  'GWWWWWWWG',
  'GYWYWYWYG',
  '.GYYWYYG.',
  '.GGWWWGG.',
  '...GGG...',
];
/** かぼすの 葉の ぐんばい */
const KABOSU_GUNBAI = ['.FFFF.', 'FFGFFF', 'FGFGFF', 'FFGFFF', '.FFFF.', '..BB..', '..BB..', '..B...'];

/** カボスダイショウ（カボスッパの しんか）：葉の くわがたの 大将。わぎりの かぼすの たてと、葉の ぐんばい（モリ） */
const kabosuDaisho: MonsterDesign = {
  size: 32,
  colors: {
    F: NQ.forest,
    G: NQ.green,
    L: NQ.leaf,
    M: NQ.lime,
    Y: NQ.sprout,
    B: NQ.brown,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.leaf]: NQ.green },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '......F.........',
        '......FF........',
        '.......FGF......',
        '.......FFGF.....',
        '........FFGF...B',
        '.........FFFF.BB',
        '...........FFFBB',
        '..........LLLLLL',
        '........LLLLLLLL',
        '......LLMYLLLLLL',
        '.....LMMLLLLLLLL',
        '....LMMLLLLGLLLL',
        '....LMLLLLLLLLLL',
        '...LLLLLLooLLLLL',
        '...LLLLLLLLoLLLL',
        '...LLLLLLLWWLLLL',
        '...LGLLLLLWoLLLL',
        '...LLLLLLLWoLLLL',
        '...LLLLLppLLLLLL',
        '...LLLLLLLLLoLLL',
        '...LLLLLLLLLLooo',
        '...LLLGLLLLLLLLL',
        '...LLLLLLLLLLGLL',
        '....LLLLLLLLLLLL',
        '....LLLLGLLLLLLL',
        '.....LLLLLLLLLLL',
        '......LLLLLLLLLL',
        '........BBB.LLLL',
        '.......BBBB.....',
      ],
    },
    { x: 1, y: 18, rows: ring(KABOSU_SLICE) },
    { x: 2, y: 19, rows: KABOSU_SLICE },
    { x: 24, y: 8, rows: ring(KABOSU_GUNBAI) },
    { x: 25, y: 9, rows: KABOSU_GUNBAI },
  ],
};

/** セキアジロー：波から はねる 関あじ（左むき）。青みどりの せなか・銀の はら・黄色い すじと ぜいご・ふたまたの 尾びれ（ミズ） */
const sekiajiro: MonsterDesign = {
  size: 32,
  colors: {
    T: NQ.teal,
    A: NQ.aqua,
    N: NQ.night,
    W: NQ.white,
    s: NQ.silver,
    g: NQ.gray,
    Y: NQ.yellow,
    S: NQ.sky,
    I: NQ.ice,
    p: NQ.blush,
  },
  rim: { [NQ.teal]: NQ.night, [NQ.silver]: NQ.gray, [NQ.white]: NQ.cloud },
  layers: [
    {
      rows: [
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '.........SS.SS..................',
        '.........SISSIS...............T.',
        '.........SISSIS..............TT.',
        '........SSISTISS.S..........TTT.',
        '......AAATTTTTTTTTT........TTTT.',
        '....TAATTTTTTTTTTTTTT.....TTTT..',
        '...TWWTTNTTTTTTTTTTTTT...TTTT...',
        '..TToWTTTNTTTTTTTTTTTTT..TTT....',
        '.TTToWTTTNTTTTTTTTTTTTTTTTTT....',
        '.YYYYYYYYNYYgYgYgYgYgYgYTT......',
        '.oossspsNsSSsgsgsgsgsgsgTTTT....',
        '..sosssssssIISSssssssss..TTT....',
        '...WWWWWWWWWSIWWWWWWWW...TTTT...',
        '....WWWWWWWWWWWWWWWWW.....TTTT..',
        '......WWWWWWWWWWWWWS.......TTTT.',
        '........SSS.W.SSSSSS........TTT.',
        '........SS........SS.........TT.',
        '.....W...................W....T.',
        '...W.......................W....',
        '...........WWWWW.........WWWW...',
        '...WW....WWSSSSSWW.....WWSSSS...',
        '...SSWWWWSSSSSSSSSWWWWWSSSSSS...',
        '...SSSIISSSSSSSSSSSSSSIISSSSS...',
        '...SSSSSSSSSSSSIISSSSSSSSSSSS...',
        '...SSSSSSSSSSSSSSSSSSSSSSSSSS...',
        '................................',
        '................................',
      ],
    },
  ],
};

/** オオゼキアジ（セキアジローの しんか）：しっぽで ふんばって 立つ 関あじの すもうとり。こい 紺の まわしと さがり、胸びれで つっぱり（ミズ） */
const oozekiAji: MonsterDesign = {
  size: 32,
  colors: {
    T: NQ.teal,
    A: NQ.aqua,
    W: NQ.white,
    s: NQ.silver,
    g: NQ.gray,
    Y: NQ.yellow,
    S: NQ.sky,
    I: NQ.ice,
    D: NQ.navy,
    p: NQ.blush,
  },
  rim: { [NQ.teal]: NQ.night, [NQ.silver]: NQ.gray },
  layers: [
    {
      rows: [
        '................................',
        '..........s.....................',
        '..........sssTTTTTA.............',
        '..........ossTooTTAA............',
        '.........ssosTWWTTTTA...........',
        '.........sssoToWTTTTTT...SSS....',
        '.........ssssToWTTTTTT.SSISI....',
        '........ssspsTTTTTTTTTTSSISI....',
        '........sssssTTTTTTTTTTSSISI....',
        '........WWWWsssYTTTTTTTSSISI....',
        '.SSSS..WWWWWsssYTTTTTTTTSIS.....',
        '.SIIISSWWWWWsssYTTTTTTTT........',
        '.SSSSIIIWWWWsssYTTTTTTTT........',
        '.SIIISSWWWWWsssgTTTTTTTTS.......',
        '.SSSSIIIWWWWsssYTTTTTTTTIIS.....',
        '.......WWWWWsssgTTTTTTTTSSIS....',
        '.......WWWWWsssYTTTTTTTTSS......',
        '......DDDDDDDDDDDDDDDDDSSD......',
        '......DDDDDDDDDDDDDDDDDDDD......',
        '......DDDDDDDDDDDDDDDDDDDD......',
        '......DDDDDDDDDDDDDDDDDDDD......',
        '........DWDWDTDTTTTTTT..........',
        '........D.DWDTDTTTTTT...........',
        '........D.DTDTDTTTTT............',
        '.........TTTTTTTTTTTTT..........',
        '.......TTTTTTTTTTTTTTTTT........',
        '.....TTTTTTTTTTTTTTTTTTTTT......',
        '...TTTTTTTTTTTT.TTTTTTTTTTTT....',
        '...TTTTTTT...........TTTTTTT....',
        '...TT.....................TT....',
        '................................',
        '................................',
      ],
    },
  ],
};

/** ヤバケイワ（中ボス）：耶馬渓の 岩山が 立ち上がった 巨人。両がわに そびえる 岩の とうと 松・もみじ、
 * ひびだらけの 大きな こぶし、するどい 目。頭に 王冠（ツチ） */
const yabakeiwa: MonsterDesign = {
  size: 40,
  colors: {
    T: NQ.tan,
    B: NQ.brown,
    K: NQ.bark,
    S: NQ.sand,
    G: NQ.green,
    F: NQ.forest,
    R: NQ.red,
    O: NQ.orange,
    Y: NQ.gold,
    W: NQ.white,
    Q: NQ.ochre,
  },
  rim: { [NQ.tan]: NQ.brown, [NQ.brown]: NQ.bark },
  rimDepth: 2,
  layers: [
    {
      mirror: true,
      rows: [
        '...................Y',
        '................Y..Y',
        '..GG............YY.Y',
        '..FG...........YYYYY',
        '..BBBB.......TTYYYYR',
        '..SBBBB......STQQQQQ',
        '..SBBBK......STTTTTT',
        '..SBBBK..GG.KKKKKKKK',
        '.RSBBBK..FG.KKKKKKKK',
        '..SBBBK.TTTT.WWoTTTT',
        '..SBBBK.STTTTWWoTTTT',
        '..SBBBK.STTTKWWoTTTT',
        '..SBBOK.STTTKWooTTTT',
        '..SBBBK.STTTKSKTKTKT',
        '..SBBBK.STTTBBKKKKKK',
        '..SBBBK.STTTBBBBBBBB',
        '..SBBBK.STTTBBBBBBBB',
        '..SBBBK.STTTTTTKKKKK',
        '..SBBBK.STTTTTTTTTTT',
        '.........BBBBBBBBBBB',
        '........BBBBBBBBBBBB',
        '.STTTTTT.BBBBBBBBBBB',
        '.STTTTTT.BBBBBBBBBBB',
        '.SKKKKKT...STSTTTTKT',
        '.STTTTTT...STSKTTTKT',
        '.STTTTTT...STSKTTTTK',
        '.STTTTTT...KTSTKTTTK',
        '.SKKKKKT...KTSTKTTTK',
        '.STTTTTT...KTSTKTTTT',
        '.STTTTTTT..TKSTKTTTT',
        '.SKKKKKKTT.TKSTTKTTT',
        '.STTTTTTTTTTKTTTKTTT',
        '.STTTTTTTTSTTTTKTTTT',
        '.STTTTTTTTSTTTTKTTTT',
        '.STTTTTTTTSTTTKTTTTT',
        '..TTTTTTT..BBBKBBBKK',
        '...TTTTT.KKKKKKKKKKK',
        '.....T...KKKKKKKKKKK',
        '.........KKKKKKKKKKK',
      ],
    },
  ],
};

/** ヤバケイワ（フィールドに 立つ 32×32） */
const yabakeiwaField: MonsterDesign = {
  size: 32,
  colors: {
    T: NQ.tan,
    B: NQ.brown,
    K: NQ.bark,
    S: NQ.sand,
    G: NQ.green,
    Y: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
    W: NQ.white,
  },
  rim: { [NQ.tan]: NQ.brown, [NQ.brown]: NQ.bark },
  layers: [
    {
      mirror: true,
      rows: [
        '..............Y',
        '............Y.Y',
        '.GG.........YYY',
        '..........TYYYYT',
        '.BBBB.....SYYYRT',
        '.SBBBB...KKQQQQK',
        '.SBBBK.GGKKKKKKK',
        '.SBBBK....WWoTTT',
        '.SBBBKTTTTWWoTTT',
        '.SBBBKSTTTWWoTTT',
        '.SBBBKSTTTSKKKKK',
        '.SBBBKSTTBBKKKKK',
        '.SBBBKSTTBBBBBBB',
        '.SBBBKSTTBBBBBBB',
        '.SBBBKSTTTTTKKKK',
        '.SBBBKSTTTTTTTTT',
        '.......BBBBBBBBB',
        '.TTTTT..BBBBBBBB',
        '.TTTTT..BBBBBBBB',
        '.KKKKT....TKTTKT',
        '.TTTTT....TKTTKT',
        '.TTTTT....TKTTTK',
        '.KKKKT....TTKTTK',
        '.TTTTTT...TTKTTK',
        '..TTTTT..TTTKTTT',
        '.TTTTTTT.TTTKTTT',
        '..TTTTT..TTTTTTT',
        '..TTTTT..TTTTTTT',
        '...TTT...BBBBBKK',
        '....T...KKKKKKKK',
        '........KKKKKKKK',
      ],
    },
  ],
};

/** ユケムリュウ（県ボス）：別府の 湯けむりから 立ちのぼる 竜。こおりの えだづの、湯けむりの たてがみ、
 * するどい 目と きば、岩の 湯つぼから のびる 太い からだ。王冠は つのの あいだ（ミズ → ヒノ） */
const yukemuryu: MonsterDesign = {
  size: 48,
  colors: {
    A: NQ.azure,
    B: NQ.blue,
    N: NQ.navy,
    S: NQ.sky,
    I: NQ.ice,
    W: NQ.white,
    Y: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
    g: NQ.gray,
    L: NQ.silver,
  },
  rim: { [NQ.azure]: NQ.blue, [NQ.white]: NQ.cloud, [NQ.gray]: NQ.slate, [NQ.sky]: NQ.azure },
  rimDepth: 2,
  layers: [
    {
      mirror: true,
      rows: [
        '.......................Y',
        '....III.............Y..Y',
        '.....WWI............YY.Y',
        '......III..........YYYYY',
        '.......III.........YYYYR',
        '........III........QQQQQ',
        '........IWII...........A',
        '.........IIII......AAAAA',
        '..........IIII...AAAAAAA',
        '...........IIIINNNNNNAAA',
        '..WWW......IIINNNNNNNAAA',
        '..WWW.......IIIWWoAAAAAA',
        '.WWWWW.........WWoAAAAAA',
        '..WWW....W....AWooAAAAAA',
        '..WWW..WWWWW...AAAAAAAAA',
        '......WWWWWWW..AAAAAAAAA',
        '...W.WWWWWWWWW.AAAAAAAAA',
        '..WWW.WWWWWWW...AAAooAAA',
        '..WWW.WWWWWW.....AAAAAAA',
        '..WWWWWWWW........AAAAAA',
        '...WWWWWWW........AAAAAA',
        '...WWWWWWW........NNNNNN',
        '...WWWWWWW........NWNNWN',
        '....WWWWWWWWWW....NWAAWA',
        '......W.WWWWWWW...NAAAAA',
        '.......WWWWWWWWW..NAAAAA',
        '...NNNAAWWWWWWW...NAAAAA',
        '....AANNNWWWWW...ANAAAAA',
        '....AAAAAAA......AAAAAAA',
        '....AAAAAAA.....AAAAAAA',
        '...AAAAAAAAA...AAAAAAAA',
        '....AAAAAAA...ISSSSSSSSS',
        '....AAAAAAA...SSSSSSSSSS',
        '..W.WAAAAAA..AAAAAAAAAA',
        '..WWWAAAAA..AAISSSSSSSSS',
        '.......A...AAASSSSSSSSSS',
        '..........AAAAAAAAAAAAA',
        '..........AAAAISSSSSSSSS',
        '.........AAAAASSSSSSSSSS',
        '........AAAAAAAAAAAAAAA',
        '.....IIAAAAAAAISSSSSSSSS',
        '.....SSSSSSSSSSSSSSSSSSS',
        '..LLLLLLLLLLLLLLLLLLLLLL',
        '..ggLggggLgggggLggggLggg',
        '..ggLggggLgggggLggggLggg',
        '..gggggggggggggggggggggg',
      ],
    },
  ],
};

/** ユケムリュウ 後半（ヒノ）：お湯が にえたち、うろこが まっ赤に 焼け、湯つぼに あわが ぼこぼこ */
const yukemuryuHot: MonsterDesign = {
  ...yukemuryu,
  colors: { ...yukemuryu.colors, A: NQ.vermilion, B: NQ.brick, N: NQ.bark, S: NQ.apricot, I: NQ.cream },
  rim: { [NQ.vermilion]: NQ.brick, [NQ.white]: NQ.cloud, [NQ.gray]: NQ.slate, [NQ.apricot]: NQ.vermilion },
  layers: [
    ...yukemuryu.layers,
    // にえたつ あわ
    { x: 9, y: 37, rows: ['.I.', 'I.I', '.I.'] },
    { x: 36, y: 38, rows: ['.I.', 'I.I', '.I.'] },
    { x: 29, y: 39, rows: ['II', 'II'] },
    { x: 16, y: 39, rows: ['II'] },
  ],
};

/** 福沢諭吉：かたを 広く はった 黒い 羽織と 金の 羽織ひも、するどい まなざし。
 * 右手に 学問の 本、左手に 地球ぎ。まわりに 学びの 光（ヒカリ） */
const fukuzawaYukichi: MonsterDesign = {
  size: 48,
  colors: {
    F: NQ.skinLight,
    f: NQ.skinMid,
    H: NQ.hairBlack,
    N: NQ.night,
    L: NQ.slate,
    g: NQ.gray,
    W: NQ.white,
    C: NQ.cream,
    Y: NQ.gold,
    R: NQ.red,
    r: NQ.brick,
    B: NQ.blue,
    G: NQ.leaf,
  },
  rim: { [NQ.skinLight]: NQ.skinMid, [NQ.gray]: NQ.slate, [NQ.red]: NQ.brick },
  rimDepth: 2,
  layers: [
    {
      x: 2,
      y: 2,
      rows: [
        '........C',
        '.........C............................C',
        '...C..................H................C',
        '....C.........HHHHHHHHHHHHHHHHH',
        '..............HHHHHHHHHHHHHHHHH',
        '..............HHHHHHHHHHHHHHHHH',
        '..............HHHHHHHHHHHHHHHHH...........C',
        'C............HHHHHHHHHHHHHHHHHHH...........C',
        '.C............HHHHHHHHHHHHHHHHH',
        '..............HHHHHHHHHHHHHHHHH',
        '..............HHHHHHHHHHHHHHHHH',
        '..............HHHHHHHHHHHHHHHHH............C',
        '..............HHFFFFFFHFFFFFFHH.............C',
        '..............HHWWoFFFFFFoWWFHH',
        '..............HHWWoFFFFFFoWWFHH',
        '...............FFFFFFFFFFFFFFF',
        '...............FFFFFFffFFFFFFF',
        '...............fFFFFFFFFFFFFfF',
        '................fFFooooooFFfF',
        '................fFFFFFFFFFFf',
        '..........LNNNNNNNFFFFFFFFFNNNNNNL',
        '.........LNNNNNNNWWffffffWWNNNNNNNL',
        '........LNNNNNNNNCWffffffWCNNNNNNNNL',
        '.....NNLNNNNNNNNNCWffffffWCNNNNNNNNNLN',
        '.....NLNNNNNNNNNNNCWWWWWWCNNNNNNNNNNNLN',
        '.....LLNNNNNNNNNNNCYYYYYYCNNNNNNNNNNNLL',
        '.....NBNNNNNNNNNYYYYYRRYYYYYNNNNNNNNNNNN',
        '...BBBBBBBNNNNNNYYYYYRRYYYYYNNNNNNNNNNNN',
        '..BGGBBBBBBNNNNNNNNYYRRYYNNNNNNNNNNNNNNN',
        '.BGGBBBBBBBBNNNNNNNYYYYYYNNNNNNYYYYYYYYYYYY',
        '.BBBGBBBBBBBNNNNNNNNCWWCNNNNNNNrrRCCCCrCCCR',
        '.BBBBBBBBBBBNNNNNNNNNCCNNNNNNNNrrRCCCCrCCCR',
        'BBBBBBBBBBBBBNNNNNNNNCCNNNNNNNNrrRCCCCrCCCR',
        '.BBBBBBGGBBBNNNNNNNNNNNNNNNNNNNrrRCCCCrCCCR',
        '.BBBBBGGBBBBNNNNNNNNNNNNNNNNNNNrrRCCCCrCCCR',
        '.BBBBBBBBBBBNNNNNNNNNNNNNNNNNNNrrRCCCCrCCCR',
        '..BBBBBBBBBNNNNNNNNNNNNNNNNNNNNrrRCCCCrCCCR',
        '...BBYYYBBFNNNNNNNNNNNNNNNNNNNNrrRCCCCrCCCR',
        '.YYYYYYYYYYYLgLLgLLgLLgLLgLLgLLrrRCCCCrCCCR',
        '.YYYYYYYYYYYgLLgLLgLLgLLgLLgLLgrrRCCCCrCCCR',
        '......gLLgLLgLLgLLgLLgLLgLLgLLgYYYYYYYYYYYY',
        '......gLLgLLgLLgLLgLLgLLgLLgLLgLLgLLLL',
        '......gLLgLLNNNNNNNLLgLLgNNNNNNNLgLLLL',
        '......g..g..NNNNNNN..g..gNNNNNNN.g',
        '............NNNNNNN......NNNNNNN',
      ],
    },
  ],
};

/** シイタケン：くぬぎの ほだ木に のった しいたけの 子。茶色の かさと 白い じく（ツチ） */
const shiitaken: MonsterDesign = {
  size: 32,
  colors: {
    B: NQ.brown,
    K: NQ.bark,
    S: NQ.sand,
    T: NQ.tan,
    E: NQ.beige,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.brown]: NQ.bark, [NQ.beige]: NQ.tan },
  layers: [
    {
      x: 6,
      y: 3,
      rows: [
        '..........B',
        '.....BBBBBBBBBBB',
        '...BBBBBEEBBBBBBBB',
        '..BBBBBBEBBBBEEBBBB',
        '.BBBEEBBBBBBBEBBBBBB',
        '.BBBEBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBBEEBBB',
        '.BBBBBEEBBBBBBBBEBBB',
        '.BTTBTTBTTBTTBTTBTTB',
        '.BTTBTTBTTBTTBTTBTTB',
        '',
        '...EE...........E',
        '...EEEEEEE.EEEEEE',
        '...EEEEEEEEEEEEEE',
        '...EEWWEEEEEEWWEE',
        '...EEWoEEEEEEoWEEE',
        '...EEWoEEEEEEoWEEE',
        '...EEEEEEEEEEEEEEE',
        '...ppEEEEEEEEEEppE',
        '...EEEEEEooEEEEEEE',
        '...EEEEEEEEEEEEEE',
        '...EEEEEEEEEEEEEE',
        '...EEEEEEEEEEEEEE',
        '...EEEEEEEEEEEEEE',
        '.TTTEEEEETEEEEEETTT',
        '.BBBEEEEEKBEEEEEBBB',
        '.BBBKBBBBKBBBBKBBBB',
      ],
    },
  ],
};

/** ホダギオー（シイタケンの しんか）：くぬぎの ほだ木を せおい、小さな しいたけを 育てる 森の 王（ツチ） */
const hodagiOh: MonsterDesign = {
  size: 32,
  colors: {
    B: NQ.brown,
    K: NQ.bark,
    S: NQ.sand,
    T: NQ.tan,
    E: NQ.beige,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.brown]: NQ.bark, [NQ.beige]: NQ.tan },
  layers: [
    {
      x: 1,
      y: 2,
      rows: [
        '...............B',
        '.........BBBBBBBBBBBBB',
        '.......BBBBBBEEBBBBBBBBB',
        '......BBBBBBBEBBBBBEEBBBB',
        '.....BBBEEBBBBBBBBBEBBBBBB',
        '....BBBBEBBBBBBBBBBBBBBBBBB',
        '....BBBBBBBBBBBBBBBBBBEEBBB',
        '...BBBBBBBEEBBBBBBEEBBEBBBBB',
        '....BBBBBBEBBBBBBBEBBBBBBBB',
        '....BBBBBBBBBBBBBBBBBBBBBBB',
        '....BTTBTTBTTBTTBTTBTTBTTBT',
        '....BTTBTTBTTBTTBTTBTTBTTBT',
        '',
        '',
        '...........EEEE.EEEE',
        '.B......EEEEEEEEEEEEEE......B',
        '.TTTTT..EEWWoEEEEoWWEE..TTTTT',
        '...E....EEWWoEEEEoWWEEE...E',
        '...E....EEEEEEEEEEEEEEE...E',
        'TTTTTTTTEEEEEEEEEEEEEEETTTTTTT',
        'BBKBBBKEppEEEEEEEEEEppEEBBBKBB',
        'BBKBBBKBEEEEEEooEEEEEEEKBBBKBB',
        'BBKBBBKBEEEEEEEEEEEEEEEKBBBKBB',
        'BBKBBBKBEEEEEEEEEEEEEEEKBBBKBB',
        'BBKBBBKBEEEEEEEEEEEEEEBKBBBKBB',
        '.........EEEEEEEEEEEE',
        '.........EEEEEEEEEEEE',
        '.........TTTTTEETTTTT',
      ],
    },
  ],
};
export const OITA: Readonly<Record<string, MonsterDesign>> = {
  'oita-yukemurin': yukemurin,
  'oita-yubune-don': yubuneDon,
  'oita-kabosuppa': kabosuppa,
  'oita-kabosu-daisho': kabosuDaisho,
  'oita-sekiajiro': sekiajiro,
  'oita-oozeki-aji': oozekiAji,
  'oita-midboss-yabakeiwa': yabakeiwa,
  'oita-midboss-yabakeiwa.field': yabakeiwaField,
  'oita-boss-yukemuryu': yukemuryu,
  'oita-boss-yukemuryu.p0': yukemuryuHot,
  'oita-lastboss-fukuzawa-yukichi': fukuzawaYukichi,
  'oita-shiitaken': shiitaken,
  'oita-hodagi-oh': hodagiOh,
};
