/** 大阪府の モンスター（手描き。docs/06 §4・§6.3〜6.5 の 規格） */
import { NQ } from '../palette';
import type { MonsterDesign } from './design';
import { BEARD_FACE, HELMET, lord } from './lastbosses';

/** ハフハフヤキ：アツアツの たこ焼き。ソース・マヨネーズ・青のり、炎の ように おどる かつおぶし、つまようじ、たこの あし（ヒノ） */
const hafuhafuYaki: MonsterDesign = {
  size: 32,
  colors: {
    T: NQ.tan,
    S: NQ.sand,
    K: NQ.bark,
    W: NQ.white,
    L: NQ.leaf,
    A: NQ.apricot,
    C: NQ.cream,
    R: NQ.red,
    Y: NQ.beige,
    p: NQ.blush,
  },
  rim: { [NQ.tan]: NQ.brown },
  layers: [
    {
      x: 1,
      y: 2,
      rows: [
        '..............C...........Y',
        '.............CA..........Y',
        '.........C....AC...C....Y',
        '........CA...AAA..CA...Y',
        '.........AC........AC.Y',
        '........AAA.......AAAY',
        '..........................W',
        '...........KKLKKKKK......W.W',
        '.........KKKKKKKKKKKK.....W',
        '........KLKKKKKKKLKKKK',
        '.......WWKKWWKKWWKKWWKK',
        '......WLKWWLKWWKKWWKLWWK',
        '.....TKKKKKKKKKKKKKKKKKKT',
        '.....TTKKKKKKKKKKKKKKKKTT',
        '.....TTTTKKKKKKKKKKKKTTTT',
        '..RR.TTTKTTTKTKKTKTTTKTTT',
        '.RRRTTTTKWWTKTTTTKTWWKTTTT',
        'RR..TTTTSWoTTTTTTTToWTTTTT',
        'RRp..TTTTWoTTTTTTTToWTTTT',
        '.RRp.TTppTTTTTTTTTTTTppTT',
        '..RRpTTTTTTTTTooTTTTTTTTT',
        '...RRRTTTTTTToRRoTTTTTTT',
        '....RRTTTTTTTTooTTTTTTTT',
        '.......TTTTTTTTTTTTTTTT',
        '........TTTTTTTTTTTTTT',
        '.........TTTTTTTTTTTT',
        '............TTTTTT',
      ],
    },
  ],
};

/** タコヤキセンチョウ：ハフハフヤキが しんか。舟の 入れものに のり、つまようじの ほばしらに 赤い 旗、大きな かつおぶしの 炎（ヒノ） */
const takoyakiSencho: MonsterDesign = {
  size: 32,
  colors: {
    T: NQ.tan,
    S: NQ.sand,
    K: NQ.bark,
    W: NQ.white,
    L: NQ.leaf,
    A: NQ.apricot,
    C: NQ.cream,
    R: NQ.red,
    Y: NQ.beige,
    p: NQ.blush,
  },
  rim: { [NQ.tan]: NQ.brown, [NQ.sand]: NQ.tan },
  layers: [
    {
      x: 3,
      y: 1,
      rows: [
        '.......C....C....C..YRRRR',
        '......CA...CAC...AC.YRRR',
        '.....CAA....AA...AACYRR',
        '......AAC..AAAA.CAA.Y',
        '.....AAAA...KK..AAAAY',
        '........KKKLKKKKKK..Y',
        '.......KKKKKKKKLKKK.Y',
        '......WLKWWKKWWKKWWKY',
        '.....KKWWLKWWKKWWKLWW',
        '.RR.KLKKKKKKKKKKKKKKKK',
        'R.RRTKKKKKKKKKKKKKKKKT',
        'Rp.TTTKKKKKKKKKKKKKKTTT',
        '.R.TTToooTKKKKKKToooTTT',
        '.RpTTTKWWoKTTTTKoWWKTTT',
        '..RTTTTWoTTTTTTTToWTTTT',
        '...TTTSWoTTTTTTTToWTTTT',
        '...TTppTTTTTTTTTTTTppTT',
        '...TTTTTTToTTTToTTTTTTT',
        '....TTTTTTTooooTTTTTTT',
        '.....TTTTTTWTTTTTTTTT',
        '.TTTTTTTTTTTTTTTTTTTTTTTT',
        'TTTTTTTTTTTTTTTTTTTTTTTTTTS',
        'SSSSSSSSTTTTTTTTTTSSSSSSSSS',
        '.SSSSSSSSSSTTTTSSSSSSSSSSS',
        '.TTTTTTTTTTTTTTTTTTTTTTTTS',
        '.SSSSSSSSSSSSSSSSSSSSSSSSS',
        '.SSSSSSSSSSSSSSSSSSSSSSSSS',
        '..TTTTTTTTTTTTTTTTTTTTTTT',
        '..SSSSSSSSSSSSSSSSSSSSSSS',
      ],
    },
  ],
};

/** ジュワナス：泉州の 水なす。まるく ふっくらした むらさきの 実、とげの ある へた、水の ひれと しずく（ミズ） */
const juwanasu: MonsterDesign = {
  size: 32,
  colors: {
    V: NQ.violet,
    L: NQ.lavender,
    G: NQ.green,
    S: NQ.sky,
    A: NQ.azure,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.violet]: NQ.indigo, [NQ.green]: NQ.forest, [NQ.sky]: NQ.azure },
  layers: [
    {
      x: 2,
      y: 4,
      rows: [
        '..............GG',
        '.............GG',
        '.............GG',
        '.............GG',
        '........GGGGGGGGGGGG',
        '.......GGGGGGGGGGGGGG',
        '.......GGGGGGGGGGGGGG....S',
        '.S....G.VGGGGGGGGGGVG.....S',
        '..S....VVVGVVVVVVGVVG',
        '......VVVVVVVVVVVVVVVV',
        '.....VVVVVVVVVVVVVVVVVV',
        '.....VVVVVVVVVVVVVVVVVV',
        '.....VVVWWVVVVVVVVWWVVV',
        '..S..VVLWoVVVVVVVVoWVVV..S',
        '.SS.VVLVWoVVVVVVVVoWVVVV.SS',
        'SSS.VVppVVVVVVVVVVVVppVV.SSS',
        '.SA.VVLVVVVVoVVoVVVVVVVV.AS',
        '....VVVLVVVVVooVVVVVVVVV',
        '....VVVVVVVVVVVVVVVVVVVV',
        '....VVVVVVVVVVVVVVVVVVVV',
        '.....VVVVVVVVVVVVVVVVVV',
        '.....VVVVVVVVVVVVVVVVVV',
        '......VVVVVVVVVVVVVVVV',
        '.......VVVVVVVVVVVVVV',
        '.........VVVVVVVVVV',
        '............VVVV.......SS',
      ],
    },
  ],
};

/** ジュワナスザムライ：ジュワナスが しんか。へたの かぶと、きりっと した まゆ、水を くむ ひしゃく（ミズ） */
const juwanasuZamurai: MonsterDesign = {
  size: 32,
  colors: {
    V: NQ.violet,
    L: NQ.lavender,
    G: NQ.green,
    M: NQ.leaf,
    S: NQ.sky,
    A: NQ.azure,
    W: NQ.white,
    T: NQ.tan,
    p: NQ.blush,
  },
  rim: { [NQ.violet]: NQ.indigo, [NQ.green]: NQ.forest, [NQ.sky]: NQ.azure },
  layers: [
    {
      x: 1,
      y: 2,
      rows: [
        '........................S..S',
        '.......................S.SS',
        '...............GG.......S..W',
        '...GG.........GG.........GG',
        '....GG........GG........GGTT',
        '.....GGG......GG......GGGSST',
        '.......GGGGGGGGGGGGGGGG..TT',
        '.......GGGGMGGGGGGMGGGG',
        '.......GGGGGGGGGGGGGGGG...T',
        '.......G.GGGGGGGGGGGGG....T',
        '.......GVVVGVVVVVVGVVGV..T',
        '.......VVVVVVVVVVVVVVVV..T',
        '......VVoooVVVVVVVVoooVVT',
        '..SS.VVVVWWoVVVVVVoWWVVVV',
        '.SSS.VVVVWoVVVVVVVVoWVVVV',
        'SSSS.VVVLWoVVVVVVVVoWVVVV',
        '.SSA.VVppVVVVVVVVVVVVppVV',
        '.....VVLVVVVoVVVVoVVVVVVV',
        '....VVVLVVVVVooooVVVVVVVVV',
        '....VVVVLVVVVWVVVVVVVVVVVV',
        '....VVVVVVVVVVVVVVVVVVVVVV',
        '....VVVVVVVVVVVVVVVVVVVVVV',
        '.....VVVVVVVVVVVVVVVVVVVV',
        '.....VVVVVVVVVVVVVVVVVVVV',
        '......VVVVVVVVVVVVVVVVVV',
        '.......VVVVVVVVVVVVVVVV',
        '........VVVVVVVVVVVVVV',
        '....S......VVVVVVVV......S',
        '..SS......................SS',
      ],
    },
  ],
};

/** サクサクモミジ：箕面の もみじの 天ぷら。赤い もみじの 葉に クリーム色の ころも、左右の 葉が つばさ、風の うず（カゼ） */
const sakusakuMomiji: MonsterDesign = {
  size: 32,
  colors: {
    V: NQ.vermilion,
    D: NQ.brick,
    A: NQ.apricot,
    C: NQ.cream,
    Y: NQ.gold,
    M: NQ.mint,
    B: NQ.brown,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.vermilion]: NQ.red, [NQ.mint]: NQ.aqua },
  layers: [
    {
      x: 1,
      y: 3,
      rows: [
        '..............DD',
        '..............DD',
        '....Y........CDDC........C',
        '....CDCCC....CDDC....CCCDY',
        '.....CDVVCCYCVDDVCCCCVVDC',
        '......CDVAVVVVDDVVVVVVDC',
        '......CDAVVVVVDDVVVVVVDY',
        '.......CDVVVVVDDVVVVVDC',
        '.......CVDVVVVDDVVVVDVC',
        '........CVDVVVVVVVVDVY',
        '......CYVVWWVVVVVVWWVVYC',
        '...YCCVVVVWoVVVVVVoWVVVVCCC',
        '.CDDDDVVVVWoVVVVVVoWVVVVDDDDC',
        '...CCVDDDpVVVVVVVVVVpDDDVYC',
        '.....CYVVVVVVoVVoVVVVVVCC',
        '.......YVVVVVVooVVVVVVY',
        '.......CVVVDVVVVVVDVVVC',
        '.......CVVDVVVVVVVVDVVC',
        '......CVVDVVVVVVVVVVDVVC',
        '.MM...YDDVCYCVVVVCCCVDDC...MM',
        'M..M..DVCC...CVVC...CCVD..M..M',
        '..MM.DCC......BB......CYD.MM',
        '.....C........BB........Y',
        '..............BB',
        '..............BB',
        '..............BB',
        '...............BB',
      ],
    },
  ],
};

/** モミジフブキ：サクサクモミジが しんか。大きく ひろげた もみじの つばさ、まいあがる 小さな もみじと 風（カゼ） */
const momijiFubuki: MonsterDesign = {
  size: 32,
  colors: {
    V: NQ.vermilion,
    D: NQ.brick,
    A: NQ.apricot,
    C: NQ.cream,
    Y: NQ.gold,
    M: NQ.mint,
    B: NQ.brown,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.vermilion]: NQ.red, [NQ.mint]: NQ.aqua },
  layers: [
    {
      x: 1,
      y: 3,
      rows: [
        '...Y..........DD',
        '..YYY.........DD...........A',
        '...Y..........DD..........AAA',
        '....DYC......CDDC......CCD.A',
        '.....DVCCCC..CDDY..CCYCVD',
        '.....CDVVVVCYVDDVYCVVVVDC',
        '......CDVVVVVVDDVVVVVVDY',
        '......CVDVVVVVDDVVVVVDVC',
        '.......CDVVVVVDDVVVVVDC',
        '........CoooVVVVVVoooY',
        '.......YVVWWoVVVVoWWVVY',
        '....CCCVVVWoVVVVVVoWVVVYCC',
        '..DDVVVVVVWoVVVVVVoWVVVVVVDD',
        '..CVDDDDDpVVVVVVVVVVpDDDDDVC',
        '.MMMCCVVVVVVoVVVVoVVVVVVCCMMM',
        'M.....CYVVVVVooooVVVVVYC.....M',
        'M.MM....YVVVVWVVVVVVVC....MM.M',
        '.MM....CVVDVVVVVVVVDVVC....MM',
        '.......CVDVVVVVVVVVVDVC',
        '......YVDVVYCVVVVCCVVDVC',
        '......CDVCC..CVVC..CCVDC',
        '.....DDCY.....CC.....CCDD...Y',
        '..A..CC................CY..YYY',
        '.AAA..........BB............Y',
        '..A..C........BB.........C',
        '....CVC.......BB........CVC',
        '.....C........BB.........C',
      ],
    },
  ],
};

const budomaru: MonsterDesign = {
  size: 32,
  colors: {
    V: NQ.violet,
    L: NQ.lavender,
    G: NQ.leaf,
    B: NQ.brown,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.violet]: NQ.indigo, [NQ.leaf]: NQ.green },
  layers: [
    {
      rows: [
        '',
        '',
        '',
        '',
        '',
        '.......................G',
        '...............BB',
        '...............BB',
        '.............G.BB..G',
        '..............GBB.G',
        '..........V....BB.....V',
        '........VVVVV.VBBVV.VVVVV',
        '........VLVVV.VLVVV.VLVVV',
        '.......VVVVVVVVVVVVVVVVVVV',
        '........VVVVV.VVVVV.VVVVV',
        '.......VVVVVVVVVVVVVVVVVVV',
        '.....VVVVVVVVVVVVVVVVVVVVVVV',
        '.....VLVVV.VoWVV.VLWoV.VLVVV',
        '....VVVVVVVVoWVVVVVWoVVVVVVVV',
        '.....VVVVV.VWWVV.VVWWV.VVVVV',
        '.....VVVVpVVVVVVVVVVVVVpVVVV',
        '.......VVVVVVVVoooVVVVVVVV',
        '........VLVVV.VLVVV.VLVVV',
        '.......VVVVVVVVVVVVVVVVVVV',
        '........VVVVVVVVVVVVVVVVV',
        '........VVVVVVVVVVVVVVVVV',
        '..........VVLVVVVVLVVVV',
        '..........VVVVVVVVVVVVV',
        '...........VVVVV.VVVVV',
        '...........VVVVV.VVVVV',
        '.............V.....V',
        '',
      ],
    },
  ],
};

const fusanariDon: MonsterDesign = {
  size: 32,
  colors: {
    V: NQ.violet,
    L: NQ.lavender,
    G: NQ.leaf,
    B: NQ.brown,
    W: NQ.white,
  },
  rim: { [NQ.violet]: NQ.indigo, [NQ.leaf]: NQ.green },
  layers: [
    {
      rows: [
        '',
        '',
        '',
        '..........................G',
        '...............BB',
        '.........G.....BB......G',
        '...B......G....BB.....G......B',
        '....B......GG..BB...GG......B',
        '....B.......GGGBB.GGG.......B',
        '.....B....V....BB.....V....B',
        '......B.VVVVV.VBBVV.VVVVV.B',
        '......B.VLVVV.VLVVV.VLVVV.B',
        '.......BVVVVVVVVVVVVVVVVVB',
        '........VVVVV.VVVVV.VVVVV',
        '....V...VVoooooVVVoooooVV...V',
        '..VVVVV.VVVWWWVVVVVWWWVVV.VVVVV',
        '..VLVVV.VLVooWVLVVVWooVVV.VLVVV',
        '.VVVVVVVVVVooWVVVVVWooVVVVVVVVV',
        '..VVVVV.VVVVV.VVVVV.VVVVV.VVVVV',
        '..VVVVV.VVVVVVVVVVVVVVVVV.VVVVV',
        '..VLVVV.VLVVVVoooooVVVVVV.VLVVV',
        '.VVVVVVVVVVVLVVV.VLVVVVVVVVVVVV',
        '..VVVVVVVVVVVVVVVVVVVVVVVVVVVVV',
        '..VVVVVVVVVVVVVVVVVVVVVVVVVVVVV',
        '....VVLVVVVVVVVVVVVVVVVVLVVVV',
        '....VVVVVVV..VVLVVVV..VVVVVVV',
        '.....VVVVV...VVVVVVV...VVVVV',
        '.....VVVVV....VVVVV....VVVVV',
        '.......V......VVVVV......V',
        '................V',
        '',
        '',
      ],
    },
  ],
};

const abareDanjiri: MonsterDesign = {
  size: 40,
  colors: {
    B: NQ.brown,
    K: NQ.bark,
    T: NQ.tan,
    S: NQ.beige,
    W: NQ.white,
    G: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
  },
  rim: { [NQ.brown]: NQ.bark, [NQ.tan]: NQ.brown, [NQ.beige]: NQ.sand },
  rimDepth: 2,
  layers: [
    {
      rows: [
        '',
        '................G.G.G.G.G',
        '................GGGGGGGGG',
        '................GGGRRGGGG',
        '................GGGRRGGGG',
        '................QQQQQQQQQ',
        '',
        '.......BBBBBBBBBBBBBBBBBBBBBBBBBB',
        '.......BBBBBBBBBBBBBBBBBBBBBBBBBBB',
        '......BBKKKKKKKKKKKKKKKKKKKKKKKKBBB',
        '......BBKKKKKKKKKKKKKKKKKKKKKKKKKBB',
        '.....BBBKKKKKKKKKKKKKKKKKKKKKKKKKBBB',
        '....BBBBKKKKKKKKKKKKKKKKKKKKKKKKKBBBB',
        '....BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
        '...BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
        '..BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
        '.BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
        '.......TTTTTTTTTTTTTTTTTTTTTTTTTTT',
        '.......TTTTTTTTTTTTTTTTTTTTTTTTTTT',
        '.......GGGGGGGGGGGGGGGGGGGGGGGGGGG',
        '.......GGoooooooooGGGGGoooooooooGG',
        '.......TToooooooooTTTTToooooooooTT',
        '.......TTTTWWWWWWTTTTTTTWWWWWWTTTT',
        '.......TTTToooWWWTTTTTTTWWWoooTTTT',
        '.......STTToooWWWTTTTTTTWWWoooTTTS',
        '......SSTTToooWWWTTTTTTTWWWoooTTTSS',
        '.....SSTTTToooWWWTTTTTTTWWWoooTTTTSS',
        '....SS.TTTTTTTToooooooooooTTTTTTTT.SS',
        '....S..TTTTTTTToooooooooooTTTTTTTT..S',
        '...SS..GGGGGGGGGGGGGGGGGGGGGGGGGGG..SS',
        '..SS...GGGGGGGGGGGGGGGGGGGGGGGGGGG...SS',
        '.SS....TTTTTKTTTTTTTTTTTTTTTKTTTTT....S',
        '.S.....TTTKKKKKTTTTTTTTTTTKKKKKTTT',
        '....S....KKKKKKK.........KKKKKKK...S',
        '...SSS...KKKSKKK.........KKKSKKK..SSS',
        '....S...KKKSSSKKK.......KKKSSSKKK..S',
        '.........KKKSKKK.........KKKSKKK',
        '.........KKKKKKK.........KKKKKKK',
        '..........KKKKK...........KKKKK',
        '',
      ],
    },
  ],
};

const abareDanjiriField: MonsterDesign = {
  size: 32,
  colors: {
    B: NQ.brown,
    K: NQ.bark,
    T: NQ.tan,
    S: NQ.beige,
    W: NQ.white,
    G: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
  },
  rim: { [NQ.brown]: NQ.bark, [NQ.tan]: NQ.brown },
  rimDepth: 1,
  layers: [
    {
      rows: [
        '',
        '..............G.G.G',
        '.............GGGGGGG',
        '.............GGRRGGG',
        '.............GGRRGGG',
        '.............QQQQQQQ',
        '......BBBBBBBBBBBBBBBBBBBB',
        '......KKKKKKKKKKKKKKKKKKKKB',
        '.....BKKKKKKKKKKKKKKKKKKKKBB',
        '....BBKKKKKKKKKKKKKKKKKKKKBBB',
        '....BBBBBBBBBBBBBBBBBBBBBBBBB',
        '...BBBBBBBBBBBBBBBBBBBBBBBBBBB',
        '..BBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
        '.BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
        '......TTTTTTTTTTTTTTTTTTTTT',
        '......GGGGGGGGGGGGGGGGGGGGG',
        '......GooooooooGGGooooooooG',
        '......TooooooooTTTooooooooT',
        '......TTTooWWWTTTTTWWWooTTT',
        '......STTooWWWTTTTTWWWooTTS',
        '.....SSTTooWWWTTTTTWWWooTTSS',
        '....SSTTTooWWWTTTTTWWWooTTTSS',
        '...SS.TTTTTToooooooooTTTTTT.SS',
        '...S..GGGGGGGGGGGGGGGGGGGGG..S',
        '..SS..GGGGGGGGGGGGGGGGGGGGG..SS',
        '.SS...TTTTKTTTTTTTTTTTKTTTT...S',
        '.S....TTKKKKKTTTTTTTKKKKKTT',
        '........KKSKK.......KKSKK',
        '.......KKSSSKK.....KKSSSKK',
        '........KKSKK.......KKSKK',
        '........KKKKK.......KKKKK',
        '',
      ],
    },
  ],
};

const takoishiDaio: MonsterDesign = {
  size: 48,
  colors: {
    g: NQ.gray,
    s: NQ.slate,
    T: NQ.teal,
    W: NQ.white,
    G: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
  },
  rim: { [NQ.gray]: NQ.slate, [NQ.teal]: NQ.navy },
  rimDepth: 2,
  layers: [
    {
      rows: [
        '',
        '....................G.G.G.G.G',
        '....................GGGGGGGGG',
        '....................GGGRRGGGG',
        '....................GGGRRGGGG',
        '....................QQQQQQQQQ',
        '..................TTTTGGGGGTTTT',
        '................TTTTTTTTTTTTTTTTT',
        '..........TTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
        '..........TTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
        '.........sTTTTTTTTTTTTTTTTTTTTTTTTTTTTTs',
        '............s.ggggsgggggsgggggsgggg.s',
        '............sgggggsgggggsgggggsgggggs',
        '............sgggggsgggggsgggggsgggggs',
        '...........gsoooooooooogsgoooooooooosg',
        '.........ssssoooooooooosssoooooooooossss',
        '..........ggsggWWWWWWgggsgggWWWWWWggsgg',
        '..........ggsggoooWWWgggsgggWWWoooggsgg',
        '..........ggsggoooWWWgggsgggWWWoooggsgg',
        '..........ggsggoooWWWgggsgggWWWoooggsgg',
        '.........ssssssoooWWWsssssssWWWooossssss',
        '..........ggsggoooWWWgggsgggWWWoooggsgg',
        '..........ggsgggggsgggggsgggggsgggggsgg',
        '..........ggsgggggsgggggsgggggsgggggsgg',
        '..........ggsgggggsgggggsgggggsgggggsgg',
        '.........ssssssssssooooooooooossssssssss',
        '...........gsgggggsooooooooooosgggggsg',
        '............sgggggsooooooooooosgggggs',
        '............sgggggsooooooooooosgggggs',
        '............s.ggggsgggggsgggggsgggg.s',
        '.gggggggggsssssgssssssssssssssssssssssggggggggg',
        '.ggggggggg..sgg..gsgggggsgggggsg..ggs..gggggggg',
        '.gggggggggggggg....ggggggggggg....ggggggggggggg',
        '.gggggggggggggg....g....g.........ggggggggggggg',
        '.gggggggggggggg...g...........g...ggggggggggggg',
        '....ggggggggggg.ggg...........ggg.ggggggggggg',
        '....gggggggggg.gggg...........ggggggggggggggg',
        '....ggggggg..gggggg...........gggggg..ggggggg',
        '....ggg.....ggggggg...........ggggggg.....ggg',
        '..........ggggggggg...........ggggggggg',
        '........gggggggggg............gggggggggg',
        '........ggggggggg...............gggggggg',
        '....ggggggggggg...................ggggggggggg',
        '....ggggggggg.......................ggggggggg',
        '....ggggggg...........................ggggggg',
        '....ggggggg...........................ggggggg',
        '',
        '',
      ],
    },
  ],
};

const takoishiDaioP0: MonsterDesign = {
  size: 48,
  colors: {
    g: NQ.gray,
    s: NQ.slate,
    T: NQ.teal,
    W: NQ.white,
    G: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
    B: NQ.blue,
    A: NQ.azure,
  },
  rim: { [NQ.gray]: NQ.slate, [NQ.teal]: NQ.navy, [NQ.blue]: NQ.navy },
  rimDepth: 2,
  layers: [
    {
      rows: [
        '',
        '....................G.G.G.G.G',
        '....................GGGGGGGGG',
        '....................GGGRRGGGG',
        '....................GGGRRGGGG',
        '....................QQQQQQQQQ',
        '..................TTTTGGGGGTTTT',
        '................TTTTTTTTTTTTTTTTT',
        '..........TTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
        '..........TTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
        '.........sTTTTTTTTTTTTTTTTTTTTTTTTTTTTTs',
        '............s.ggggsgggggsgggggsgggg.s',
        '............sgggggsgggggsgggggsgggggs',
        '.....W......sgggggsgggggsgggggsgggggs.....W',
        '....WWW....gsoooooooooogsgoooooooooosg...WWW',
        '.....W...ssssoooooooooosssoooooooooossss..W',
        '..........ggsggWWWWWWgggsgggWWWWWWggsgg',
        '..........ggsggoooWWWgggsgggWWWoooggsgg',
        '..........ggsggoooWWWgggsgggWWWoooggsgg',
        '..........ggsggoooWWWgggsgggWWWoooggsgg',
        '.........ssssssoooWWWsssssssWWWooossssss',
        '..........ggsggoooWWWgggsgggWWWoooggsgg',
        '..........ggsgggggsgggggsgggggsgggggsgg',
        '..........ggsgggggsgggggsgggggsgggggsgg',
        '..........ggsgggggsgggggsgggggsgggggsgg',
        '.........ssssssssssooooooooooossssssssss',
        '...........gsgggggsooooooooooosgggggsg',
        '............sgggggsooooooooooosgggggs',
        '............sgggggsooooooooooosgggggs',
        '............s.ggggsgggggsgggggsgggg.s',
        '.gggggggggsssssgssssssssssssssssssssssggggggggg',
        '.ggggggggg..sgg..gsgggggsgggggsg..ggs..gggggggg',
        '.gggggggggggggg....ggggggggggg....ggggggggggggg',
        '.gggggggggggggg....g....g.........ggggggggggggg',
        '.gggggggggggggg...g...........g...ggggggggggggg',
        '....ggggggggggg.ggg...........ggg.ggggggggggg',
        '....gggggggggg.gggg...........ggggggggggggggg',
        '....ggggggg..gggggg...........gggggg..ggggggg',
        '....Agg...A.ggggAgg...A.....A.ggggAgg...A.ggg',
        '..AAAAA.AAAAAgAAAAA.AAAAA.AAAAAgAAAAAgAAAAA',
        '.AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBB',
        '..AAAAABAAAAABAAAAABAAAAABAAAAABAAAAABAAAAABBBB',
        '..BBABBBBBABBBBBABBBBBABBBBBABBBBBABBBBBABBBBBB',
        '..BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
        '..BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
        '....ggggggg...........................ggggggg',
        '',
        '',
      ],
    },
  ],
};

const toyotomiHideyoshi = lord(
  [
    '....G...................',
    '.....GG................R',
    '.......GG.............RR',
    '........GGG..........RRR',
    '..........GGG.........RR',
    '...........GGGG.......GR',
    '.............GGGG.....GG',
    '...............GGGG.NNGG',
    ...HELMET,
    ...BEARD_FACE,
  ],
  {
    N: NQ.night,
    L: NQ.slate,
    G: NQ.gold,
    Y: NQ.cream,
    R: NQ.red,
    K: NQ.gold,
    S: NQ.cream,
    T: NQ.bark,
    H: NQ.slate,
    C: NQ.brick,
    M: NQ.hairBlack,
  },
  { [NQ.cream]: NQ.gold, [NQ.brick]: NQ.ink },
);

export const OSAKA: Readonly<Record<string, MonsterDesign>> = {
  'osaka-hafuhafu-yaki': hafuhafuYaki,
  'osaka-takoyaki-sencho': takoyakiSencho,
  'osaka-juwanasu': juwanasu,
  'osaka-juwanasu-zamurai': juwanasuZamurai,
  'osaka-sakusaku-momiji': sakusakuMomiji,
  'osaka-momiji-fubuki': momijiFubuki,
  'osaka-budomaru': budomaru,
  'osaka-fusanari-don': fusanariDon,
  'osaka-midboss-abare-danjiri': abareDanjiri,
  'osaka-midboss-abare-danjiri.field': abareDanjiriField,
  'osaka-boss-takoishi-daio': takoishiDaio,
  'osaka-boss-takoishi-daio.p0': takoishiDaioP0,
  'osaka-lastboss-toyotomi-hideyoshi': toyotomiHideyoshi,
};
