/** 佐賀県の モンスター（手描き。docs/06 §4・§6.3〜6.5 の 規格） */
import { NQ } from '../palette';
import type { MonsterDesign } from './design';
import { FACE, HELMET, lord } from './lastbosses';

/** ピョンゴロウ：有明海の ムツゴロウ。頭の 上に とび出た 大きな 目、横に 大きな 口、青い はんてん、むなびれで ひがたに ふんばる（ミズ） */
const pyongoro: MonsterDesign = {
  size: 32,
  colors: {
    g: NQ.gray,
    s: NQ.silver,
    W: NQ.white,
    p: NQ.blush,
    A: NQ.azure,
    K: NQ.sky,
    B: NQ.brown,
    T: NQ.tan,
  },
  rim: { [NQ.gray]: NQ.slate, [NQ.silver]: NQ.gray, [NQ.brown]: NQ.bark },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '................',
        '................',
        '...........ggg..',
        '..........gWWWg.',
        '..........gWWog.',
        '..........gWWog.',
        '......gggggggggg',
        '....gggggggggggg',
        '...ggggggggggggg',
        '...ggggggggggggg',
        '...ggggggggggggg',
        '...ggggggggggggg',
        '...gggggpggggggg',
        '...ggggggooooooo',
        '...ggggggggggggg',
        '...gggssssssssss',
        '...ggsssssssssss',
        '...ggsssssssssss',
        '...ggsssssssssss',
        '...ggsssssssssss',
        '....ggssssssssss',
        '.....gggssssssss',
        '.......ggggggggg',
        '.........ggggggg',
        '...TBBBBBBBBBBBB',
        '..BBBBBTBBBBBBBB',
        '.BBBBBBBBBBBBBBB',
        '..BBB.BBBBB.BBBB',
      ],
    },
    // むなびれ（ひがたに つく）
    { mirror: true, y: 17, rows: ['...K', '..KK', '.KKA', '.KKK', '.KKK', '.KK.'] },
    // 青い はんてん・つや
    {
      mirror: true,
      y: 9,
      rows: [
        '........A.......',
        '....A...........',
        '......A.........',
        '',
        '.....A..........',
        '',
        '',
        '....A...........',
      ],
    },
    { x: 11, y: 4, rows: ['s'] },
  ],
};

/** ソメツボン：有田焼の ふたつき つぼ。白い 磁器に 青い 染付の 花と なみの もよう、頭に 金の わっか（ヒカリ） */
const sometsubon: MonsterDesign = {
  size: 32,
  colors: {
    W: NQ.white,
    N: NQ.navy,
    B: NQ.blue,
    K: NQ.sky,
    G: NQ.gold,
    Q: NQ.ochre,
    p: NQ.blush,
  },
  rim: { [NQ.white]: NQ.cloud },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '...........GGGGG',
        '..........G.....',
        '...........QQQQQ',
        '..............BB',
        '...........WWWWW',
        '.........WWWWWWW',
        '........BBBBBBBB',
        '..........WWWWWW',
        '.........WWWWWWW',
        '.......WWWWWWWWW',
        '.....WBWBWBWBWBW',
        '....BBBBBBBBBBBB',
        '...WWWWWWWWWWWWW',
        '...WWWWWWWWWWWWW',
        '..WWWWWWWWoWWWWW',
        '..WWWWWWWWooWWWW',
        '..WWWWWWWWooWWWW',
        '..WWWWWWpWWWWWoW',
        '..WWWWWWWWWWWWWo',
        '..WWWWWWWWWWWWWW',
        '..WWWWWWWWWWWWWW',
        '...WWWWWWWWWWWWW',
        '...WBWWBWWBWWBWW',
        '....BWBBWBBWBBWB',
        '.....BBBBBBBBBBB',
        '.......WWWWWWWWW',
        '.........BBBBBBB',
        '.........WWWWWWW',
        '.........WWWWWWW',
      ],
    },
    // 染付の 花と つる（左右）
    {
      mirror: true,
      y: 14,
      rows: [
        '.....K..........',
        '....BNB.........',
        '.....B.K........',
        '......B.........',
        '.....K..........',
        '....B...........',
      ],
    },
    { x: 12, y: 5, rows: ['.K'] },
  ],
};

/** チャコロン：嬉野茶の くるんと まるまった 茶葉の 玉。頭に 1 つの 芽と 2 まいの 若葉（モリ） */
const chakoron: MonsterDesign = {
  size: 32,
  colors: {
    L: NQ.leaf,
    G: NQ.green,
    M: NQ.lime,
    S: NQ.sprout,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.leaf]: NQ.green, [NQ.lime]: NQ.leaf },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '...............M',
        '...............M',
        '...........MM..M',
        '..........MMMM.M',
        '..........MMSMMG',
        '............MMMG',
        '..........LLLLLL',
        '.......LLLLLLLLL',
        '.....LLLLLLLLLLL',
        '....LLLLLLLLLLLL',
        '...LLLLLLLLLLLLL',
        '...LLLLLLLLLLLLL',
        '..LLLLLLLLWWLLLL',
        '..LLLLLLLLWoLLLL',
        '..LLLLLLLLWoLLLL',
        '..LLLLLLpLLLLLoL',
        '..LLLLLLLLLLLLLo',
        '..LLLLLLLLLLLLLL',
        '..LLLLLLLLLLLLLL',
        '..LLLLLLLLLLLLLL',
        '...LLLLLLLLLLLLL',
        '...LLLLLLLLLLLLL',
        '....LLLLLLLLLLLL',
        '.....LLLLLLLLLLL',
        '.......LLLLLLLLL',
        '.........GGG....',
        '.........GGG....',
        '........GGGG....',
      ],
    },
    // くるんと まいた 茶葉の すじ
    {
      mirror: true,
      y: 11,
      rows: [
        '.....GGG........',
        '....G...G.......',
        '...G..G..G......',
        '...G.G.G.G......',
        '...G..GG.G......',
        '....G....G......',
        '.....GGGG.......',
      ],
    },
    { x: 5, y: 10, rows: ['SS', 'S.'] },
  ],
};

/**
 * トウメイカ（中ボス）：呼子の 海の からだが すきとおった 大イカ。剣先の ような 三角の ひれ、大きな 目、
 * 8 本の 足と 長い 2 本の うで。とがった 頭の 先に 王冠（ミズ）
 */
const toumeika: MonsterDesign = {
  size: 40,
  colors: {
    I: NQ.ice,
    A: NQ.azure,
    K: NQ.sky,
    W: NQ.white,
    b: NQ.berry,
    G: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
    p: NQ.blush,
  },
  rim: { [NQ.ice]: NQ.sky, [NQ.azure]: NQ.blue, [NQ.gold]: NQ.ochre },
  rimDepth: 2,
  layers: [
    // 長い 2 本の うで（先が ふくらむ）
    {
      mirror: true,
      x: 1,
      y: 18,
      rows: [
        '..AA.',
        '.AKKA',
        '.AKKA',
        '..AA.',
        '..A..',
        '..A..',
        '...A.',
        '...A.',
        '....A',
        '.....AA',
        '.......AAA',
      ],
    },
    {
      mirror: true,
      rows: [
        '....................',
        '................G..G',
        '................GGGR',
        '................QQQQ',
        '..................II',
        '.................III',
        '................IIII',
        '.........II....IIIII',
        '.......IIIIII..IIIII',
        '.....IIIIIIIIIIIIIII',
        '...IIIIIIIIIIIIIIIII',
        '..IIIIIIIIIIIIIIIIII',
        '...IIIIIIIIIIIIIIIII',
        '.....IIIIIIIIIIIIIII',
        '.......IIIIIIIIIIIII',
        '.........IIIIIIIIIII',
        '...........IIIIIIIII',
        '............IIIIIIII',
        '............IIIIIIII',
        '............IIIIIIII',
        '...........IIIIIIIII',
        '..........IIIIIIIIII',
        '.........IIIIIIIIIII',
        '.........IIWWWIIIIII',
        '.........IIWWoIIIIII',
        '.........IIWWoIIIIII',
        '.........IIWooIIIIII',
        '.........IIIpIIIIIoo',
        '..........IIIIIIIIII',
        '.........AAAAAAAAAAA',
        '........AA.AA.AAA.AA',
        '.......AA.AA..AA..AA',
        '......AA..AA..AA..AA',
        '.....AA..AA...AA...A',
        '....AA...AA...AA...A',
        '....A....A....A....A',
        '...AA...AA....AA....',
        '...A.....A.....A....',
      ],
    },
    // まゆ（きりっと）
    { mirror: true, y: 21, rows: ['..........oo........', '............oo......'] },
    // からだの はんてん・つや
    {
      mirror: true,
      y: 8,
      rows: [
        '..............b.....',
        '',
        '',
        '.......b....b.......',
        '',
        '',
        '...............b....',
        '',
        '',
        '.............b......',
        '',
        '',
        '...............b....',
      ],
    },
    { x: 16, y: 5, rows: ['.W', 'WW', 'W.'] },
    // 剣先の ような とがった ひれ（左右）
    {
      mirror: true,
      y: 7,
      rows: [
        '....A...............',
        '...AA...............',
        '..AAAA..............',
        '.AAAAA..............',
        '.AAAAA..............',
        '..AAAA..............',
        '...AAA..............',
        '....A...............',
      ],
    },
    // 大きな 王冠と するどい 目
    {
      mirror: true,
      y: 1,
      rows: [
        '..............G.G..G',
        '..............GGGGGG',
        '..............GGGGGR',
        '..............GGGGGR',
        '..............QQQQQQ',
      ],
    },
    {
      mirror: true,
      y: 21,
      rows: [
        '..........oooo......',
        '...........ooo......',
        '.........WWWWo......',
        '.........WWWoo......',
        '.........WWWoo......',
        '.........WWooo......',
      ],
    },
    // 海の しぶき
    { x: 2, y: 16, rows: ['.K.', 'KWK', '.K.'] },
    { x: 35, y: 30, rows: ['.K.', 'KWK', '.K.'] },
  ],
};

/** トウメイカ（フィールドに立つ 32×32） */
const toumeikaField: MonsterDesign = {
  size: 32,
  colors: {
    I: NQ.ice,
    A: NQ.azure,
    W: NQ.white,
    b: NQ.berry,
    G: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
    p: NQ.blush,
  },
  rim: { [NQ.ice]: NQ.sky, [NQ.azure]: NQ.blue },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '............G..G',
        '............GGGR',
        '............QQQQ',
        '..............II',
        '.............III',
        '.......I....IIII',
        '.....IIIII.IIIII',
        '...IIIIIIIIIIIII',
        '..IIIIIIIIIIIIII',
        '....IIIIIIIIIIII',
        '......IIIIIIIIII',
        '.........IIIIIII',
        '..........IIIIII',
        '..........IIIIII',
        '.........IIIIIII',
        '........IIIIIIII',
        '........IWWIIIII',
        '........IWoIIIII',
        '........IWoIIIoo',
        '........IIpIIIII',
        '.......AAAAAAAAA',
        '......AA.AA.AA.A',
        '.....AA.AA..AA.A',
        '....AA..AA..AA.A',
        '...AA..AA...AA..',
        '...A...AA...AA..',
        '..AA...A.....A..',
        '..A....A.....A..',
      ],
    },
    { mirror: true, y: 8, rows: ['..........b.....', '', '.....b.....b....', '', '', '...........b....'] },
    // とがった ひれと するどい 目
    {
      mirror: true,
      y: 6,
      rows: [
        '...A............',
        '..AAA...........',
        '.AAAA...........',
        '..AAA...........',
        '...A............',
      ],
    },
    {
      mirror: true,
      y: 16,
      rows: ['.......ooo......', '.......WWo......', '.......WWo......', '.......Woo......'],
    },
  ],
};

/** たてがみ（黒い 毛に 金の うずまき。左半分） */
const SHISHI_MANE = [
  '........................',
  '........................',
  '..........N...N.........',
  '.........NN..NN...N.....',
  '....N...NNN.NNN..NN.....',
  '....NN.NNNNNNNNNNNN.....',
  '.N..NNNNNNNNNNNNNNNN....',
  '.NN.NNNNNNNNNNNNNNNNN...',
  '..NNNNNNNNNNNNNNNNNNNN..',
  '.NNNNNNNNNNNNNNNNNNNNNN.',
  '..NNNNNNNNNNNNNNNNNNNNNN',
  '.NNNNNNNNNNNNNNNNNNNNNNN',
  '..NNNNNNNNNNNNNNNNNNNNNN',
  '.NNNNNNNNNNNNNNNNNNNNNNN',
  '..NNNNNNNNNNNNNNNNNNNNNN',
  '.NNNNNNNNNNNNNNNNNNNNNNN',
  '..NNNNNNNNNNNNNNNNNNNNNN',
  '.NNNNNNNNNNNNNNNNNNNNNNN',
  '..NNNNNNNNNNNNNNNNNNNNNN',
  '.NNNNNNNNNNNNNNNNNNNNNNN',
  '..NNNNNNNNNNNNNNNNNNNNNN',
  '.NNNNNNNNNNNNNNNNNNNNNNN',
  '..NNNNNNNNNNNNNNNNNNNNNN',
  '.NNNNNNNNNNNNNNNNNNNNNNN',
  '..NNNNNNNNNNNNNNNNNNNNNN',
  '.NNNNNNNNNNNNNNNNNNNNNNN',
  '..NNNNNNNNNNNNNNNNNNNNNN',
  '...NNNNNNNNNNNNNNNNNNNNN',
  '....NNNNNNNNNNNNNNNNNNNN',
  '...NNNNNNNNNNNNNNNNNNNNN',
  '.....NNNNNNNNNNNNNNNNNNN',
  '......NNNNNNNNNNNNNNNNNN',
];

/** 赤い 顔（左半分、y 7〜31） */
const SHISHI_FACE = [
  '..............RRRRRRRRRR',
  '...........RRRRRRRRRRRRR',
  '.........RRRRRRRRRRRRRRR',
  '........RRRRRRRRRRRRRRRR',
  '.......RRRRRRRRRRRRRRRRR',
  '......RRRRRRRRRRRRRRRRRR',
  '......RRRRRRRRRRRRRRRRRR',
  '......RRRRRRRRRRRRRRRRRR',
  '......RRRRRRRRRRRRRRRRRR',
  '......RRRRRRRRRRRRRRRRRR',
  '......RRRRRRRRRRRRRRRRRR',
  '......RRRRRRRRRRRRRRRRRR',
  '......RRRRRRRRRRRRRRRRRR',
  '......RRRRRRRRRRRRRRRRRR',
  '......RRRRRRRRRRRRRRRRRR',
  '......RRRRRRRRRRRRRRRRRR',
  '......RRRRRRRRRRRRRRRRRR',
  '......RRRRRRRRRRRRRRRRRR',
  '......RRRRRRRRRRRRRRRRRR',
  '......RRRRRRRRRRRRRRRRRR',
  '......RRRRRRRRRRRRRRRRRR',
  '......RRRRRRRRRRRRRRRRRR',
  '.......RRRRRRRRRRRRRRRRR',
  '........RRRRRRRRRRRRRRRR',
  '..........RRRRRRRRRRRRRR',
];

/** まゆ・金の 目・鼻・大きな 口（左半分、y 10〜28） */
const SHISHI_FEATURES = [
  '........GGG.............',
  '.......GGGGGG...........',
  '..........GGGGGG........',
  '............oooo.GG.....',
  '............GGGG........',
  '............GGoo........',
  '............GGoo.......V',
  '............GGGGVVVVVVVV',
  '..................VRRRRR',
  '..................RRRRRR',
  '..................RoRRRR',
  '...................RRRRR',
  '..........oooooooooooooo',
  '..........oWWWWWWWWWWWWW',
  '..........obbbbbbbbbbbbb',
  '...........obbbbbbbbbbVV',
  '...........oWbbbbbbbVVVV',
  '............oWWWWWWWWWWW',
  '.............ooooooooooo',
];

/** 曳山の 台と 大きな 車（左半分） */
const SHISHI_BASE = [
  '......GGGGGGGGGGGGGGGGGG',
  '.....NNNNNNNNNNNNNNNNNNN',
  '.....NRRRRRRRRRRRRRRRRRR',
  '.....NRRGRRRRGRRRRGRRRRR',
  '.....NRRRRRRRRRRRRRRRRRR',
  '.....NNNNNNNNNNNNNNNNNNN',
  '......GGGGGGGGGGGGGGGGGG',
];
const SHISHI_WHEEL = [
  '.....BBBB.....',
  '...BBTTTTBB...',
  '..BTTBTTBTTB..',
  '..BTTTBBTTTB..',
  '.BTBTTBBTTBTB.',
  '.BTTBBGGBBTTB.',
  '.BTTBBGGBBTTB.',
  '.BTBTTBBTTBTB.',
  '..BTTTBBTTTB..',
  '..BTTBTTBTTB..',
  '...BBTTTTBB...',
  '.....BBBB.....',
];

/**
 * アカジシオウ（県ボス）：唐津くんちの 曳山「赤獅子」が 動きだした 王。赤い 顔に 金の 目と まゆ、
 * 金の うずまきの 黒い たてがみ、大きく ひらいた 口。曳山の 台と 大きな 木の 車に のる（ヒノ）
 */
const akajishiOh: MonsterDesign = {
  size: 48,
  colors: {
    R: NQ.red,
    J: NQ.red,
    V: NQ.vermilion,
    G: NQ.gold,
    Q: NQ.ochre,
    W: NQ.white,
    b: NQ.berry,
    N: NQ.night,
    B: NQ.brown,
    T: NQ.tan,
  },
  rim: { [NQ.red]: NQ.brick, [NQ.gold]: NQ.ochre, [NQ.brown]: NQ.bark },
  rimDepth: 2,
  layers: [
    { mirror: true, rows: SHISHI_MANE },
    // たてがみの 金の うずまき
    {
      mirror: true,
      y: 5,
      rows: [
        '',
        '',
        '.....GG.........',
        '....G..G........',
        '....G.GG........',
        '',
        '',
        '',
        '..GG............',
        '.G..G...........',
        '.G.GG...........',
        '',
        '',
        '',
        '',
        '..GG............',
        '.G..G...........',
        '.G.GG...........',
        '',
        '',
        '',
        '..GG............',
        '.G..G...........',
        '.G.GG...........',
      ],
    },
    { mirror: true, y: 7, rows: SHISHI_FACE },
    { mirror: true, y: 10, rows: SHISHI_FEATURES },
    // ほおの 金の うず
    { mirror: true, y: 20, rows: ['........GG', '.......G..', '.......G.G', '........GG'] },
    { mirror: true, y: 32, rows: SHISHI_BASE },
    { mirror: true, y: 34, rows: SHISHI_WHEEL },
    // 金の つの
    {
      mirror: true,
      y: 2,
      rows: [
        '....G...................',
        '...GG...................',
        '...GG...................',
        '..GGG...................',
        '..GGGG..................',
        '...GGGG.................',
        '....GGGG................',
        '.....GGGG...............',
      ],
    },
    // 大きな 王冠
    {
      mirror: true,
      y: 1,
      rows: [
        '..................G.G..G',
        '..................GGGGGG',
        '..................GGGGGJ',
        '..................GGGGGJ',
        '..................QQQQQQ',
      ],
    },
  ],
};

/** アカジシオウ 後半（いかり）：顔が まっ赤に 燃え、たてがみの 上に 炎が 立ちのぼり、金の 目が 白く 光る */
const akajishiOhRage: MonsterDesign = {
  ...akajishiOh,
  colors: { ...akajishiOh.colors, R: NQ.vermilion, V: NQ.apricot, A: NQ.apricot, C: NQ.cream, E: NQ.cream },
  rim: { [NQ.vermilion]: NQ.brick, [NQ.gold]: NQ.ochre, [NQ.brown]: NQ.bark },
  layers: [
    // たてがみの 上の 炎
    {
      mirror: true,
      x: 2,
      rows: [
        '................',
        '.......C........',
        '.......G....C...',
        '......AGA...G...',
        '......AGA..AGA..',
        '.....RAGAR.AGA..',
        '.....RRARRRAGAR.',
        '...........RRARR',
      ],
    },
    ...akajishiOh.layers,
    // 白く 光る 目
    {
      mirror: true,
      y: 14,
      rows: ['............EEEE', '............EEoo', '............EEoo', '............EEEE'],
    },
  ],
};

/** 鍋島直正：鍋島家の しるし「杏葉（ぎょうよう）」の 金の 前立てと 紺の よろい（ヒノ） */
const nabeshimaNaomasaBase = lord(
  [
    '...........GG...........',
    '..........GYYG..........',
    '..........GYYYG.........',
    '...........GYYYG........',
    '............GYYYG.......',
    '.............GYYYG......',
    '..............GYYYGGGGGG',
    '...............GGYYYYYYY',
    '.................GGGGGGG',
    '...............NNNNNNNNN',
    ...HELMET,
    ...FACE,
  ],
  {
    N: NQ.night,
    L: NQ.slate,
    K: NQ.navy,
    S: NQ.blue,
    G: NQ.gold,
    Y: NQ.yellow,
    R: NQ.red,
    T: NQ.indigo,
    H: NQ.denim,
  },
  { [NQ.blue]: NQ.navy },
);

/** 鍋島直正：杏葉（ぎょうよう）の 大きな 金の 前立て、肩よろい、軍配（ぐんばい）（ヒノ） */
const nabeshimaNaomasa: MonsterDesign = {
  ...nabeshimaNaomasaBase,
  layers: [
    { x: 2, y: 6, rows: ['.G.', 'GYG', '.G.'] },
    { x: 4, y: 33, rows: ['.G.', 'GYG', '.G.'] },
    ...nabeshimaNaomasaBase.layers,
    // するどい まゆと 目
    { mirror: true, x: 18, y: 15, rows: ['o..', 'Foo', 'FWo'] },
    // 軍配（ぐんばい）
    {
      x: 34,
      y: 5,
      rows: [
        '.GGGGG.',
        'GYYYYYG',
        'GYRRRYG',
        'GYRRRYG',
        'GYYYYYG',
        '.GGGGG.',
        '..GTG..',
        '..GTG..',
        '...T...',
        '...T...',
        '...T...',
        '...T...',
        '...T...',
        '...T...',
        '...T...',
        '...T...',
        '...T...',
        '...T...',
        '...T...',
        '...T...',
        '...T...',
        '...T...',
        '...T...',
        '...T...',
        '...T...',
        '...T...',
        '...T...',
        '...T...',
        '...T...',
        '...T...',
        '...T...',
        '...T...',
        '...T...',
      ],
    },
  ],
};

// ───────────────────────── しんか ─────────────────────────

/** ヒガタタイショウ：ピョンゴロウの しんか。せなかに 大きな 帆の ような せびれ、きりっと した まゆ、力こぶの むなびれ（ミズ） */
const higataTaisho: MonsterDesign = {
  size: 32,
  colors: {
    g: NQ.gray,
    s: NQ.silver,
    W: NQ.white,
    p: NQ.blush,
    A: NQ.azure,
    K: NQ.sky,
    B: NQ.brown,
    T: NQ.tan,
  },
  rim: { [NQ.gray]: NQ.slate, [NQ.silver]: NQ.gray, [NQ.brown]: NQ.bark, [NQ.sky]: NQ.azure },
  layers: [
    // 帆の ような せびれ（うしろ）
    {
      mirror: true,
      rows: [
        '................',
        '.........K....K.',
        '.........KK..KKK',
        '........KAKKKKAK',
        '........KKKAKKKK',
        '.......KKKKKKAKK',
        '.......KAKKKKKKK',
        '......KKKKAKKKKK',
      ],
    },
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '................',
        '................',
        '...........ggg..',
        '..........gWWWg.',
        '..........gWWog.',
        '..........gWWog.',
        '.....ggggggggggg',
        '...ggggggggggggg',
        '..gggggggggggggg',
        '..gggggggggggggg',
        '..gggggggggggggg',
        '..gggggggggggggg',
        '..ggggggpggggggg',
        '..ggggggoooooooo',
        '..gggggggoWWWWWW',
        '..gggggggggooooo',
        '..gggsssssssssss',
        '..ggssssssssssss',
        '..ggssssssssssss',
        '..ggssssssssssss',
        '...ggsssssssssss',
        '....gggsssssssss',
        '......gggggggggg',
        '........gggggggg',
        '...TBBBBBBBBBBBB',
        '..BBBBBTBBBBBBBB',
        '.BBBBBBBBBBBBBBB',
        '..BBB.BBBBB.BBBB',
      ],
    },
    // まゆ
    { mirror: true, y: 3, rows: ['..........oo....', '............o...'] },
    // 力こぶの むなびれ（ぐっと 上げる）
    { mirror: true, y: 10, rows: ['..KK.', '.KKKK', '.KAKK', '.KKKK', '..KK.', '..Kg.', '...gg'] },
    {
      mirror: true,
      y: 9,
      rows: [
        '',
        '....A...........',
        '......A.........',
        '',
        '.....A..........',
        '',
        '',
        '',
        '',
        '....A...........',
      ],
    },
  ],
};

/** キンランツボ：ソメツボンの しんか。赤と 金で はなやかに 絵つけした 大きな つぼ。金の 玉の つまみ、左右に とって、大きな 金の わっか（ヒカリ） */
const kinranTsubo: MonsterDesign = {
  size: 32,
  colors: {
    W: NQ.white,
    N: NQ.navy,
    B: NQ.blue,
    R: NQ.red,
    G: NQ.gold,
    Q: NQ.ochre,
    Y: NQ.cream,
    p: NQ.blush,
  },
  rim: { [NQ.white]: NQ.cloud, [NQ.red]: NQ.brick },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '..........GGGGGG',
        '.........G......',
        '..........QQQQQQ',
        '..............GG',
        '.............GGG',
        '..........RRRRRR',
        '........RRRRRRRR',
        '.......GGGGGGGGG',
        '.........WWWWWWW',
        '........WWWWWWWW',
        '......WWWWWWWWWW',
        '....RRRRRRRRRRRR',
        '...RGRRGRRGRRGRR',
        '..WWWWWWWWWWWWWW',
        '..WWWWWWWWWWWWWW',
        '.WWWWWWWWoWWWWWW',
        '.WWWWWWWWWoWWWWW',
        '.WWWWWWWWooWWWWW',
        '.WWWWWWWWooWWWWW',
        '.WWWWWWpWWWWWWoo',
        '.WWWWWWWWWWWWWWW',
        '..WWWWWWWWWWWWWW',
        '..BWBBWBBWBBWBBW',
        '...BBBBBBBBBBBBB',
        '....RRRRRRRRRRRR',
        '......GGGGGGGGGG',
        '........WWWWWWWW',
        '........BBBBBBBB',
        '........WWWWWWWW',
        '........WWWWWWWW',
      ],
    },
    // 金の 花と 赤い 花びら・青い つる
    {
      mirror: true,
      y: 15,
      rows: [
        '....R.R.........',
        '.....G..........',
        '....RGR.B.......',
        '.....R...B......',
        '........B.......',
        '...B..B.........',
      ],
    },
    // とって（左右の かた）
    { mirror: true, y: 11, rows: ['..GG', '.G..', '.G..', '..GG'] },
    { x: 11, y: 9, rows: ['Y', 'Y'] },
  ],
};

/** チャバシラ：チャコロンの しんか。湯のみの 緑の お茶から すっくと 立つ 茶柱の 勇者。茶葉の うでを ひろげる（モリ） */
const chabashira: MonsterDesign = {
  size: 32,
  colors: {
    S: NQ.sprout,
    M: NQ.lime,
    L: NQ.leaf,
    G: NQ.green,
    E: NQ.paper,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.sprout]: NQ.lime, [NQ.leaf]: NQ.green, [NQ.paper]: NQ.cloud },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '...............S',
        '..............LS',
        '..............SS',
        '.............SSS',
        '............SSSS',
        '...........SSSSS',
        '...........SSSSS',
        '...........SWWSS',
        '...........SWoSS',
        '...........SWoSS',
        '...........pSSoS',
        '...........SSSSo',
        '............SSSS',
        '............SSSS',
        '............SSSS',
        '............SSSS',
        '.....EEEEEEEEEEE',
        '...EEMMMMMMMMSSS',
        '...EMMMMMMMMMMMM',
        '...EEMMMMMMMMMMM',
        '....EEEEEEEEEEEE',
        '....EEEEEEEEEEEE',
        '....LLLLLLLLLLLL',
        '....EEEEEEEEEEEE',
        '....EEEEEEEEEEEE',
        '.....EEEEEEEEEEE',
        '......EEEEEEEEEE',
        '........EEEEEEEE',
        '........EEEEEEEE',
      ],
    },
    // まゆ
    { mirror: true, y: 7, rows: ['............oo..'] },
    // 茶葉の うで（上へ ひろげる）
    {
      mirror: true,
      y: 8,
      rows: [
        '.....LL.........',
        '....LLLL........',
        '....LGLLL.......',
        '.....LLGLL......',
        '.......LLGL.....',
        '.........LLSS...',
      ],
    },
  ],
};

/** ユモンボウ：武雄温泉の 朱色の 楼門の 子。屋根の 上から いつも 湯けむりが 立つ（ヒノ） */
const yumonbou: MonsterDesign = {
  size: 32,
  colors: {
    V: NQ.vermilion,
    N: NQ.slate,
    g: NQ.gray,
    W: NQ.white,
    C: NQ.cloud,
    p: NQ.blush,
  },
  rim: { [NQ.vermilion]: NQ.brick, [NQ.white]: NQ.cloud, [NQ.slate]: NQ.night },
  layers: [
    // 湯けむり
    { x: 3, y: 0, rows: ['.CC.', 'CCCC', '.CC.'] },
    { x: 22, y: 1, rows: ['.CC.', 'CCCC', '.CC.'] },
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '................',
        '................',
        '.........NNNNNNN',
        '.......NNNNNNNNN',
        '.....NNNNNNNNNNN',
        '...NNNNNNNNNNNNN',
        '..NNNNNNNNNNNNNN',
        '..gggggggggggggg',
        '...VVVVVVVVVVVVV',
        '...VWWWWWWWWWWWW',
        '...VWWWWWWWWWWWW',
        '...VWWWWWWWWWWWW',
        '...VWWWWWWWWWWWW',
        '...VWWWWWWWWWWWW',
        '...VVVVVVVVVVVVV',
        '..VVVVVVVVVVVVVV',
        '..VVVVVVVVVVVVVV',
        '..VVVVV.........',
        '..VVVVV.........',
        '..VVVVV.........',
        '..VVVVV.........',
        '..VVVVV.........',
        '..VVVVV.........',
        '..VVVVV.........',
        '..VVVVV.........',
        '.NNNNNNN........',
        '.NNNNNNN........',
        '................',
      ],
    },
    // かお
    {
      mirror: true,
      y: 11,
      rows: [
        '................',
        '.........oo.....',
        '.........oo.....',
        '......p.........',
        '...........ooo..',
      ],
    },
  ],
};

/** ユモンドウジ：ユモンボウの しんか。二階建ての 楼門に なり、湯けむりが ほのおの ように もえる（ヒノ） */
const yumonDouji: MonsterDesign = {
  size: 32,
  colors: {
    V: NQ.vermilion,
    A: NQ.apricot,
    N: NQ.slate,
    g: NQ.gray,
    W: NQ.white,
    G: NQ.gold,
    C: NQ.cloud,
    p: NQ.blush,
  },
  rim: { [NQ.vermilion]: NQ.brick, [NQ.white]: NQ.cloud, [NQ.slate]: NQ.night },
  layers: [
    // ほのおの ような 湯けむり
    { mirror: true, rows: ['....C...........', '...CAC..........', '...CAC..........', '....A...........'] },
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '................',
        '................',
        '..........NNNNNN',
        '........NNNNNNNN',
        '......NNNNNNNNNN',
        '.....ggggggggggg',
        '.......VVVVVVVVV',
        '.......VWWWWWWWW',
        '.......VWWWWWWWW',
        '.......VVVVVVVVV',
        '.........NNNNNNN',
        '.......NNNNNNNNN',
        '.....NNNNNNNNNNN',
        '...NNNNNNNNNNNNN',
        '..NNNNNNNNNNNNNN',
        '..gggggggggggggg',
        '...VVVVVVVVVVVVV',
        '...VWWWWWWWWWWWW',
        '...VWWWWWWWWWWWW',
        '...VWWWWWWWWWWWW',
        '...VVVVVVVVVVVVV',
        '..VVVVVVVVVVVVVV',
        '..VVVVV.........',
        '..VVVVV.........',
        '..VVVVV.........',
        '..VVVVV.........',
        '.NNNNNNN........',
        '.NNNNNNN........',
      ],
    },
    // 金の かざりと かお
    { mirror: true, y: 8, rows: ['.......GGGGGGGGG'] },
    {
      mirror: true,
      y: 18,
      rows: [
        '................',
        '.......oo.......',
        '.........oo.....',
        '.........oo.....',
        '......p.........',
      ],
    },
    { mirror: true, y: 22, rows: ['...........oooo.'] },
  ],
};

export const SAGA: Readonly<Record<string, MonsterDesign>> = {
  'saga-yumonbou': yumonbou,
  'saga-yumon-douji': yumonDouji,
  'saga-midboss-toumeika': toumeika,
  'saga-midboss-toumeika.field': toumeikaField,
  'saga-boss-akajishi-oh': akajishiOh,
  'saga-boss-akajishi-oh.p0': akajishiOhRage,
  'saga-lastboss-nabeshima-naomasa': nabeshimaNaomasa,
  'saga-pyongoro': pyongoro,
  'saga-higata-taisho': higataTaisho,
  'saga-sometsubon': sometsubon,
  'saga-kinran-tsubo': kinranTsubo,
  'saga-chakoron': chakoron,
  'saga-chabashira': chabashira,
};
