/** 埼玉県の モンスター（手描き。docs/06 §4・§6.3〜6.5 の 規格） */
import { NQ } from '../palette';
import type { MonsterDesign } from './design';

/** ハニワルツ：さきたま古墳の おどる はにわ。まるい あなの 目と 口、つつの からだ、かたほうの 手を 上げる（ツチ） */
const haniwaltz: MonsterDesign = {
  size: 32,
  colors: {
    T: NQ.tan,
    S: NQ.sand,
    B: NQ.brown,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.tan]: NQ.brown },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '................',
        '..........TTTTTT',
        '.........TTTTTTT',
        '........TTTTTTTT',
        '........TSTTTTTT',
        '........TTTTTTTT',
        '........TTooTTTT',
        '........TTooTTTT',
        '........TpTTTTTT',
        '........TTTTTToo',
        '.........TTTTTTT',
        '..........TTTTTT',
        '...........TTTTT',
        '.........TTTTTTT',
        '........TTTTTTTT',
        '.......TTTTTTTTT',
        '.......TSTTTTTTT',
        '.......TTTTTTTTT',
        '.......TTTBBBBBB',
        '.......TTTTTTTTT',
        '.......TTTTTTTTT',
        '......TTTTTTTTTT',
        '......TTTBBBBBBB',
        '......TTTTTTTTTT',
        '.....TTTTTTTTTTT',
        '.....TTTTTTTTTTT',
        '....TTTTTTTTTTTT',
        '....TTTTTTTTTTTT',
      ],
    },
    // 上げた 左手
    {
      x: 2,
      y: 5,
      rows: ['TT......', 'TT......', '.TT.....', '.TT.....', '..TT....', '..TT....', '...TTT..', '....TTT.'],
    },
    // よこに のばした 右手
    { x: 22, y: 16, rows: ['TTTTT', '.TTTT', '..TTT'] },
  ],
};

/** ハニワムシャ（ハニワルツの しんか）：よろいを つけた 武人の はにわ。かぶとと 四角い たて（ツチ） */
const haniwaMusha: MonsterDesign = {
  size: 32,
  colors: {
    T: NQ.tan,
    S: NQ.sand,
    B: NQ.brown,
    K: NQ.bark,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.tan]: NQ.brown },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '..........TTTTTT',
        '.........TTTTTTT',
        '........TTTTTTTT',
        '........TSTTTTTT',
        '.......BBBBBBBBB',
        '........TTTTTTTT',
        '........TTooTTTT',
        '........TTooTTTT',
        '........TpTTTTTT',
        '........TTTTTToo',
        '.........TTTTTTT',
        '..........TTTTTT',
        '.......TTTTTTTTT',
        '......TTTTTTTTTT',
        '.....TTTTTTTTTTT',
        '.....TTBBBBBBBBB',
        '.....TTTTTTTTTTT',
        '.....TTTTTTTTTTT',
        '.....BBBBBBBBBBB',
        '.....TTTTTTTTTTT',
        '.....TTTTTTTTTTT',
        '....BBBBBBBBBBBB',
        '....TTTTTTTTTTTT',
        '....TTTTTTTTTTTT',
        '....BBBBBBBBBBBB',
        '....TTTTTTTTTTTT',
        '...TTTTTTTTTTTTT',
        '...TTTTTTTTTTTTT',
      ],
    },
    // 四角い たて（もようつき）
    {
      x: 1,
      y: 14,
      rows: ['SSSSSS', 'STTTTS', 'STBBTS', 'STBBTS', 'STTTTS', 'STBBTS', 'STBBTS', 'STTTTS', 'SSSSSS'],
    },
  ],
};

/** ネギボーヤ：白い ところが 長い 深谷ねぎ。上は みどりの 葉、下は 白い ね（モリ） */
const negiBoya: MonsterDesign = {
  size: 32,
  colors: {
    W: NQ.white,
    C: NQ.cloud,
    L: NQ.leaf,
    G: NQ.green,
    M: NQ.lime,
    p: NQ.blush,
  },
  rim: { [NQ.white]: NQ.cloud, [NQ.leaf]: NQ.green },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '...........LL...',
        '..........LLML..',
        '.........LLLMLL.',
        '........LLLLMLLL',
        '.......LLLLLMLLL',
        '......LLLLLLMLLL',
        '.....LLLLLLLMLLL',
        '.....LLLLLLLMLLL',
        '......LLLLLLMLLL',
        '.......LLLLLLLLL',
        '........WCWWWWWW',
        '........WWWWWWWW',
        '........WWWWWWWW',
        '........WWWWWWWW',
        '........WWWWWWWW',
        '........WWWWWWWW',
        '........WWWWWWWW',
        '........WWWWWWWW',
        '........WWWWWWWW',
        '........WWWWWWWW',
        '........WWWWWWWW',
        '........WWWWWWWW',
        '........WWWWWWWW',
        '........WWWWWWWW',
        '........WCWWWWWW',
        '........WWWWWWWW',
        '.......W.W.W.W.W',
        '......W...W...W.',
      ],
    },
    // かお（白い ところの まん中）
    { x: 10, y: 17, rows: ['WW..WW', 'Wo..Wo', 'Wo..Wo'] },
    { x: 9, y: 20, rows: ['p'] },
    { x: 15, y: 20, rows: ['o.', '.o'] },
  ],
};

/** ネギランサー（ネギボーヤの しんか）：葉の かぶとを かぶり、長い ねぎを やりのように かまえる（モリ） */
const negiLancer: MonsterDesign = {
  size: 32,
  colors: {
    W: NQ.white,
    C: NQ.cloud,
    L: NQ.leaf,
    G: NQ.green,
    M: NQ.lime,
    p: NQ.blush,
  },
  rim: { [NQ.white]: NQ.cloud, [NQ.leaf]: NQ.green },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '..........LL....',
        '.........LLML...',
        '........LLLMLL..',
        '.......LLLLMLLL.',
        '......LLLLLMLLLL',
        '.....LLLLLLMLLLL',
        '....LLLLLLLMLLLL',
        '....LLLLLLLMLLLL',
        '.....LLLLLLMLLLL',
        '......LLLLLLLLLL',
        '.....GGGGGGGGGGG',
        '.......WCWWWWWWW',
        '.......WWWWWWWWW',
        '.......WWWWWWWWW',
        '.......WWWWWWWWW',
        '.......WWWWWWWWW',
        '.......WWWWWWWWW',
        '.......WWWWWWWWW',
        '.......WWWWWWWWW',
        '.......WWWWWWWWW',
        '.......WWWWWWWWW',
        '.......WWWWWWWWW',
        '.......WWWWWWWWW',
        '.......WCWWWWWWW',
        '.......WWWWWWWWW',
        '.......WWWWWWWWW',
        '......W.W.W.W.W.',
        '.....W...W...W..',
      ],
    },
    { x: 9, y: 16, rows: ['oo..oo', 'WW..WW', 'Wo..Wo', 'Wo..Wo'] },
    { x: 8, y: 20, rows: ['p'] },
    { x: 14, y: 20, rows: ['oo', '..'] },
    // 右手の ねぎの やり
    {
      x: 24,
      y: 2,
      rows: [
        '..LL',
        '.LML',
        '.LLL',
        '..WW',
        '..WW',
        '..WW',
        '..WW',
        '..WW',
        '..WW',
        '..WW',
        '..WW',
        '..WW',
        '..WW',
        '..WW',
        '..WW',
        '..WW',
        '..WW',
        '..WW',
        '..WW',
        '..WW',
        '..WW',
        '..WW',
        '..WW',
        '..WW',
        '.W.W',
      ],
    },
  ],
};

/** パリッセン：こんがり やけた 草加せんべい。しょうゆの こげ目と のりの おび、頭に 炎（ヒノ） */
const parissen: MonsterDesign = {
  size: 32,
  colors: {
    A: NQ.amber,
    S: NQ.sand,
    B: NQ.brown,
    F: NQ.forest,
    V: NQ.vermilion,
    G: NQ.gold,
    C: NQ.cream,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.amber]: NQ.brown },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '...............C',
        '..............VG',
        '..........C...VG',
        '.........VGV.VVG',
        '.........VVV.VVV',
        '..........V...VV',
        '..........AAAAAA',
        '........AAAAAAAA',
        '.......AAAAAAAAA',
        '......AAABAAAAAA',
        '......AAAAAAAAAA',
        '.....AAAAAAAAAAA',
        '.....AAAAAWWAAAA',
        '.....AAAAAWoAAAA',
        '.....AAAAAWoAAAA',
        '.....AAApAAAAAoA',
        '.....AAAAAAAAAAo',
        '.....FFFFFFFFFFF',
        '.....FFFFFFFFFFF',
        '.....AAAAAAAAAAA',
        '.....AAAAABAAAAA',
        '......AAAAAAAAAA',
        '......AAAAAAAAAA',
        '.......AAABAAAAA',
        '........AAAAAAAA',
        '..........AAAAAA',
        '................',
        '.........BBB....',
        '........BBBB....',
      ],
    },
  ],
};

/** ダイバリッセン（パリッセンの しんか）：大きな せんべいの たてを かまえる。こげ目の もようと のりの おび（ヒノ） */
const daiBarissen: MonsterDesign = {
  size: 32,
  colors: {
    A: NQ.amber,
    S: NQ.sand,
    B: NQ.brown,
    F: NQ.forest,
    V: NQ.vermilion,
    G: NQ.gold,
    C: NQ.cream,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.amber]: NQ.brown },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '...............C',
        '..........C...VG',
        '.........VGV..VG',
        '.........VGV.VVG',
        '.........VVV.VVV',
        '..........V..VVV',
        '.........AAAAAAA',
        '.......AAAAAAAAA',
        '......AAAAAAAAAA',
        '.....AAAABAAAAAA',
        '.....AAAAAAAAAAA',
        '....AAAAAAooAAAA',
        '....AAAAAAWWAAAA',
        '....AAAAAAWoAAAA',
        '....AAAApAAAAAoo',
        '....AAAAAAAAAAAA',
        '....FFFFFFFFFFFF',
        '....FFFFFFFFFFFF',
        '....AAAAAAAAAAAA',
        '....AAAAABAAAAAA',
        '.....AAAAAAAAAAA',
        '.....AAAAAAAAAAA',
        '......AAABAAAAAA',
        '......AAAAAAAAAA',
        '.......AAAAAAAAA',
        '.........AAAAAAA',
        '................',
        '........BBB.....',
        '.......BBBB.....',
      ],
    },
    // 左手の 大きな せんべいの たて
    {
      x: 1,
      y: 12,
      rows: ['..AAAA..', '.AAAAAA.', 'AAABAAAA', 'AAAAAAAA', 'AABAAABA', 'AAAAAAAA', '.AAAAAA.', '..AAAA..'],
    },
  ],
};

// ───────────────────────── 中ボス ─────────────────────────

/** ゴーンヤグラ（中ボス）：川越の 時の鐘の やぐら。3 だんの 屋根の 下に 大きな 鐘。鐘の 音が 風に ひびく（カゼ） */
const gonYagura: MonsterDesign = {
  size: 40,
  colors: {
    K: NQ.bark,
    B: NQ.brown,
    T: NQ.tan,
    S: NQ.sand,
    Q: NQ.ochre,
    G: NQ.gold,
    R: NQ.red,
    W: NQ.white,
    C: NQ.cloud,
    p: NQ.blush,
  },
  rim: { [NQ.tan]: NQ.brown, [NQ.ochre]: NQ.brown, [NQ.gold]: NQ.ochre },
  rimDepth: 2,
  layers: [
    {
      mirror: true,
      rows: [
        '....................',
        '................G..G',
        '................GGGR',
        '................QQQQ',
        '.............KKKKKKK',
        '..........KKKKKKKKKK',
        '.......KKKKKKKKKKKKK',
        '.......TTTTTTTTTTTTT',
        '..........BBBBBBBBBB',
        '..........BTTTTTTTTT',
        '..........BTQQQQQQQQ',
        '.........BTQQQQQQQQQ',
        '.........BTQQQQQQQQQ',
        '.........BTQQoooQQQQ',
        '.........BTQQWWoQQQQ',
        '.........BTQQWWoQQQQ',
        '.........BTQQWWoQQQQ',
        '.........BTQpQWooQQQ',
        '.........BTQQQQQQQQQ',
        '.........BTQQQQQoooo',
        '.........BTQQQQQQQQQ',
        '.........BTQQQQQQQQQ',
        '.........BTQQQQQQQQQ',
        '.........BTTQQQQQQQQ',
        '.........BTTTTTTTTTT',
        '......KKKKKKKKKKKKKK',
        '....KKKKKKKKKKKKKKKK',
        '....TTTTTTTTTTTTTTTT',
        '.......BTTTTTTTTTTTT',
        '.......BTTTTTTTTTTTT',
        '.......BTTTTTTTTTTTT',
        '....KKKKKKKKKKKKKKKK',
        '..KKKKKKKKKKKKKKKKKK',
        '..TTTTTTTTTTTTTTTTTT',
        '.....BTTTTTTTTTTTTTT',
        '.....BTTTTTTTTTTTTTT',
        '.....BTTTTTTTTTTTTTT',
        '.....BTTTTTTTTTTTTTT',
        '.....KKKKKKKKKKKKKKK',
        '....................',
      ],
    },
    // 鐘の 音（左右に ひびく）
    { x: 1, y: 14, rows: ['C..W', '.C.W', '.C.W', '.C.W', 'C..W'] },
    { x: 35, y: 14, rows: ['W..C', 'W.C.', 'W.C.', 'W.C.', 'W..C'] },
  ],
};

/** ゴーンヤグラ（フィールドに立つ 32×32） */
const gonYaguraField: MonsterDesign = {
  size: 32,
  colors: {
    K: NQ.bark,
    B: NQ.brown,
    T: NQ.tan,
    Q: NQ.ochre,
    G: NQ.gold,
    R: NQ.red,
    W: NQ.white,
    C: NQ.cloud,
  },
  rim: { [NQ.tan]: NQ.brown, [NQ.ochre]: NQ.brown },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '............G..G',
        '............GGGR',
        '............QQQQ',
        '.........KKKKKKK',
        '......KKKKKKKKKK',
        '......TTTTTTTTTT',
        '........BTTTTTTT',
        '........BTQQQQQQ',
        '.......BTQQQQQQQ',
        '.......BTQQoooQQ',
        '.......BTQQWWoQQ',
        '.......BTQQWWoQQ',
        '.......BTQQQQQQQ',
        '.......BTQQQoooo',
        '.......BTQQQQQQQ',
        '.......BTQQQQQQQ',
        '.......BTTQQQQQQ',
        '.....KKKKKKKKKKK',
        '...KKKKKKKKKKKKK',
        '...TTTTTTTTTTTTT',
        '.....BTTTTTTTTTT',
        '.....BTTTTTTTTTT',
        '...KKKKKKKKKKKKK',
        '..KKKKKKKKKKKKKK',
        '..TTTTTTTTTTTTTT',
        '....BTTTTTTTTTTT',
        '....BTTTTTTTTTTT',
        '....KKKKKKKKKKKK',
        '................',
      ],
    },
    { x: 1, y: 11, rows: ['C.W', '.CW', 'C.W'] },
    { x: 28, y: 11, rows: ['W.C', 'WC.', 'W.C'] },
  ],
};

// ───────────────────────── 県ボス ─────────────────────────

/** ヨマツリダイオウ（県ボス）：秩父夜祭の 山車が 動きだした すがた。金の かざりの 屋根、赤い ほりもの、ちょうちん、木の 車輪、うしろに 花火（ヒノ） */
const yomatsuriDaio: MonsterDesign = {
  size: 48,
  colors: {
    R: NQ.red,
    K: NQ.brick,
    G: NQ.gold,
    Q: NQ.ochre,
    C: NQ.cream,
    W: NQ.white,
    B: NQ.brown,
    T: NQ.tan,
    N: NQ.night,
    V: NQ.vermilion,
    Y: NQ.yellow,
    p: NQ.blush,
  },
  rim: { [NQ.red]: NQ.brick, [NQ.tan]: NQ.brown, [NQ.gold]: NQ.ochre },
  rimDepth: 2,
  layers: [
    // うしろの 花火
    {
      mirror: true,
      y: 1,
      rows: [
        '..Y...Y.................',
        '...YCY..................',
        '..YCCCY.................',
        '...YCY..........Y...Y...',
        '..Y...Y..........YCY....',
        '................YCCCY...',
        '.................YCY....',
        '................Y...Y...',
      ],
    },
    // 屋根（唐破風）と 金の かざり
    {
      mirror: true,
      y: 6,
      rows: [
        '...................GGGGG',
        '..................GGGGGG',
        '...............NNNNNNNNN',
        '............NNNNNNNNNNNN',
        '.........NNNNNNNNNNNNNNN',
        '......NNNNNNNNNNNNNNNNNN',
        '....NNNNNNNNNNNNNNNNNNNN',
        '..GGGGGGGGGGGGGGGGGGGGGG',
        '..NNNNNNNNNNNNNNNNNNNNNN',
      ],
    },
    // 山車の 本体（赤い ほりものと 金の おび）
    {
      mirror: true,
      y: 15,
      rows: [
        '....GRRRRRRRRRRRRRRRRRRR',
        '....RRRRRRRRRRRRRRRRRRRR',
        '....RRRRRRRRRRoooRRRRRRR',
        '....RRRRRRRRRRWWoRRRRRRR',
        '....RRRRRRRRRRWWoRRRRRRR',
        '....RRRRRRRRRRWWoRRRRRRR',
        '....RRRRRRRRpRWooRRRRRRR',
        '....RRRRRRRRRRRRRRRRRRRR',
        '....RRRRRRRRRRRRRooooooo',
        '....GGGGGGGGGGGGGGGGGGGG',
        '....RRRRRRRRRRRRRRRRRRRR',
        '....RRRRGGGGRRRRGGGGRRRR',
        '....RRRRGRRGRRRRGRRGRRRR',
        '....RRRRGGGGRRRRGGGGRRRR',
        '....RRRRRRRRRRRRRRRRRRRR',
        '....GGGGGGGGGGGGGGGGGGGG',
        '....WWWWWWWWWWWWWWWWWWWW',
        '....WWWWWWWWWWWWWWWWWWWW',
        '....TTTTTTTTTTTTTTTTTTTT',
        '.....TTTTTTTTTTTTTTTTTTT',
        '.......TTTTTTTTTTTTTTTTT',
      ],
    },
    // ちょうちん（左右に つるす）
    {
      mirror: true,
      y: 16,
      rows: [
        '..CC....................',
        '.CCCC...................',
        '.CYCC...................',
        '.CCCC...................',
        '..CC....................',
      ],
    },
    // 木の 車輪
    {
      mirror: true,
      x: 1,
      y: 36,
      rows: [
        '...BBBBBB..............',
        '..BTTTTTTB.............',
        '.BTTBBBBTTB............',
        '.BTBTTTTBTB............',
        'BTTBTBBTBTTB...........',
        'BTTBTBBTBTTB...........',
        '.BTBTTTTBTB............',
        '.BTTBBBBTTB............',
        '..BTTTTTTB.............',
        '...BBBBBB..............',
      ],
    },
  ],
};

/** ヨマツリダイオウ 後半：花火が 大きく ひらき、ちょうちんが まぶしく 光る */
const yomatsuriDaioP0: MonsterDesign = {
  ...yomatsuriDaio,
  colors: { ...yomatsuriDaio.colors, C: NQ.white, Y: NQ.cream },
  layers: [
    ...yomatsuriDaio.layers,
    {
      mirror: true,
      y: 1,
      rows: [
        '.Y..Y..Y................',
        '..YCCCY.................',
        '.YCCCCCY................',
        '..YCCCY.................',
        '.Y..Y..Y................',
      ],
    },
    { x: 2, y: 28, rows: ['.Y.', 'YCY', '.Y.'] },
    { x: 43, y: 24, rows: ['.Y.', 'YCY', '.Y.'] },
  ],
};

// ───────────────────────── 裏ステージの ラスボス ─────────────────────────

/** 渋沢栄一：羽織はかまの 実業家。右手に そろばん、左手に 本（「論語と そろばん」）。金の とけいの くさりと 赤い ひも（モリ → ヒカリ） */
const shibusawaEiichi: MonsterDesign = {
  size: 48,
  colors: {
    F: NQ.skinLight,
    f: NQ.skinMid,
    W: NQ.white,
    H: NQ.silver,
    h: NQ.gray,
    N: NQ.night,
    D: NQ.denim,
    P: NQ.paper,
    G: NQ.gold,
    R: NQ.red,
    B: NQ.brown,
    T: NQ.tan,
    p: NQ.blush,
  },
  rim: { [NQ.skinLight]: NQ.skinMid, [NQ.paper]: NQ.cloud, [NQ.night]: NQ.ink },
  rimDepth: 2,
  layers: [
    // 頭（うすい かみ・白い もみあげ）
    {
      mirror: true,
      y: 4,
      rows: [
        '.................FFFFFFF',
        '..............FFFFFFFFFF',
        '.............FFFFFFFFFFF',
        '............FFFFFFFFFFFF',
        '...........HFFFFFFFFFFFF',
        '..........HHFFFooFFFFFFF',
        '..........HHFFFooFFFFFFF',
        '..........HHFFFFFFFFFFFF',
        '..........HHFFFFFFFFFFFF',
        '..........HhFFpFFFFFFFFF',
        '...........fFFFFFFFFFFoo',
        '............ffFFFFFFFFFF',
        '.............ffFFFFFFFFF',
        '..............ffffffffff',
      ],
    },
    // 羽織（黒）と 白い えり
    {
      mirror: true,
      y: 18,
      rows: [
        '..........NNNPPPPPPPPPPP',
        '........NNNNNNPPPPPPPPPP',
        '.......NNNNNNNNPPPPPPPPP',
        '......NNNNNNNNNNPPPPPPPP',
        '.....NNNNNNNNNNNNPPPPPPP',
        '.....NNNNNNNNNNNNNPPPPPP',
        '....NNNNNNNNNNNNNNNPPPPP',
        '....NNNNNNNNNNNNNNNNPPPP',
        '....NNNNNNNNNNNNNNNNNPPP',
        '....NNNNNNNNNNNNNNNNNNPP',
        '....NNNNNNNNNNNNNNNNNNNP',
        '....NNNNNNNNNNNNNNNNNNNN',
        '....NNNNNNNNNNNNNNNNNNNN',
        '....NNNNNNNNNNNNNNNNNNNN',
        '....NNNNNNNNNNNNNNNNNNNN',
        '....NNNNNNNNNNNNNNNNNNNN',
        '.....NNNNNNNNNNNNNNNNNNN',
        '.....DDDDDDDDDDDDDDDDDDD',
        '.....DDDDDDDDDDDDDDDDDDD',
        '.....DHDDDHDDDDHDDDDHDDD',
        '.....DDDDDDDDDDDDDDDDDDD',
        '.....DHDDDHDDDDHDDDDHDDD',
        '.....DDDDDDDDDDDDDDDDDDD',
        '......DDDDDDDDDDDDDDDDDD',
        '......NNNNNNNNNNNNNNNNNN',
        '.......NNNNNN.....NNNNNN',
        '.......NNNNNN.....NNNNNN',
        '.......NNNNNN.....NNNNNN',
      ],
    },
    // 金の とけいの くさりと 赤い ひも
    { x: 24, y: 26, rows: ['GG.', '..G', '..G', 'RG.'] },
    // 右手に そろばん
    {
      x: 32,
      y: 26,
      rows: [
        'BBBBBBBBB',
        'BTTTTTTTB',
        'BooooooB.',
        'BTTTTTTTB',
        'BoooooooB',
        'BooooooB.',
        'BTTTTTTTB',
        'BBBBBBBBB',
      ],
    },
    // 左手に 本（論語）
    {
      x: 5,
      y: 27,
      rows: ['RRRRRRR', 'RGGGGGR', 'RRRRRRR', 'RPPPPPR', 'RRRRRRR'],
    },
  ],
};

export const SAITAMA: Readonly<Record<string, MonsterDesign>> = {
  'saitama-haniwaltz': haniwaltz,
  'saitama-haniwa-musha': haniwaMusha,
  'saitama-negi-boya': negiBoya,
  'saitama-negi-lancer': negiLancer,
  'saitama-parissen': parissen,
  'saitama-dai-barissen': daiBarissen,
  'saitama-midboss-gon-yagura': gonYagura,
  'saitama-midboss-gon-yagura.field': gonYaguraField,
  'saitama-boss-yomatsuri-daio': yomatsuriDaio,
  'saitama-boss-yomatsuri-daio.p0': yomatsuriDaioP0,
  'saitama-lastboss-shibusawa-eiichi': shibusawaEiichi,
};
