/** 栃木県の モンスター（手描き。docs/06 §4・§6.3〜6.5 の 規格） */
import { NQ } from '../palette';
import type { MonsterDesign } from './design';
import { FACE, HELMET, lord } from './lastbosses';

/** イチゴロー：つぶつぶの たねの ついた 赤い いちご。頭に 星の 形の ヘタ（モリ） */
const ichigoro: MonsterDesign = {
  size: 32,
  colors: {
    R: NQ.red,
    Y: NQ.cream,
    C: NQ.white,
    L: NQ.leaf,
    G: NQ.green,
    M: NQ.lime,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.red]: NQ.brick, [NQ.leaf]: NQ.green },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '...............G',
        '..........L....G',
        '..........LL..LG',
        '...LL......LLLLL',
        '....LLLL..RLMLLL',
        '.....LLMLLLLLLLL',
        '...RRRLLLLRRLLLL',
        '..RRRRRGRRRRRGLR',
        '..RCCRRRRRRRRGRR',
        '..RCRRRYRRRRRRRR',
        '..RRRRRRRWWRRRYR',
        '..RRYRRRRWoRRRRR',
        '..RRRRRRRWoRRRRR',
        '...RRRRpRRRRRRoR',
        '...RYRRRRRRYRRRo',
        '....RRRRRRRRRRRR',
        '....RRRYRRRRRRYR',
        '.....RRRRRRYRRRR',
        '.....RYRRRRRRRRR',
        '......RRRRYRRRRR',
        '.......RRRRRRRYR',
        '........RRYRRRRR',
        '.........RRRRRRR',
        '..........RRRYRR',
        '...........RRRRR',
        '..........GG..RR',
        '.........GGG....',
      ],
    },
  ],
};

/** イチゴオウジ（イチゴローの しんか）：大きく なった いちごの 王子。葉の マント、頭に 白い いちごの 花、花の つえ（モリ） */
const ichigoOuji: MonsterDesign = {
  size: 32,
  colors: {
    R: NQ.red,
    Y: NQ.cream,
    C: NQ.white,
    L: NQ.leaf,
    G: NQ.green,
    M: NQ.lime,
    W: NQ.white,
    F: NQ.gold,
    p: NQ.blush,
  },
  rim: { [NQ.red]: NQ.brick, [NQ.leaf]: NQ.green, [NQ.white]: NQ.cloud },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '..............WW',
        '.............WWF',
        '..............WW',
        '....L.....L...LL',
        '....LL...LLL.LML',
        '..LLLLL.LLMLLLLL',
        '...LLMLLLLLLLLLL',
        '.LLLLLLLLRRLLGLL',
        '.GLRRRRGRRRRRGRR',
        '.GLRCCRRRRRRRRRR',
        '.GRRCRRRYRRRRRRR',
        '.GRRRRRRRooRRRYR',
        '.GRRRRRRRWWRRRRR',
        '.GRRYRRRRWoRRRRR',
        '.GRRRRRRRWoRRRRR',
        '.GRRRRRRpRRRRRoo',
        '.GRRRYRRRRRRYRRR',
        '..GRRRRRRRRRRRRR',
        '..GRRRRYRRRRRRYR',
        '..GGRRRRRRRYRRRR',
        '...GRRYRRRRRRRRR',
        '...GGRRRRRYRRRRR',
        '....GRRRRRRRRRYR',
        '.....GRRRYRRRRRR',
        '.......RRRRRRRRR',
        '.........RRRYRRR',
        '.........GGG..RR',
        '.........GGG....',
        '........GGGG....',
      ],
    },
    // 白い たすきと 金の ブローチ
    {
      y: 20,
      rows: [
        '...CC...........................',
        '...CCCCC........................',
        '.....CCCCC......................',
        '........CCCCC...................',
        '..........CCCCCCF...............',
        '.............CCFRFC.............',
        '...............FRFCCCC..........',
        '................F..CCCCC........',
        '......................CCCCC.....',
        '........................CCCCC...',
        '...........................CC...',
        '................................',
      ],
    },
    // 右手の 花の つえ
    {
      x: 26,
      y: 3,
      rows: [
        '.WW.',
        'WFFW',
        '.WW.',
        '..G.',
        '..G.',
        '..G.',
        '..G.',
        '..G.',
        '..G.',
        '..G.',
        '..G.',
        '..G.',
        '..G.',
        '..G.',
        '..G.',
        '..G.',
        '..G.',
        '..G.',
        '..G.',
        '..G.',
      ],
    },
  ],
};

/** ギョウザン：半月の 形の ぎょうざ。ふちに ひだ、下は こんがり、すその 羽根は パリパリ。頭に 3 本の 炎（ヒノ） */
const gyozan: MonsterDesign = {
  size: 32,
  colors: {
    E: NQ.beige,
    S: NQ.sand,
    T: NQ.tan,
    B: NQ.brown,
    V: NQ.vermilion,
    A: NQ.apricot,
    G: NQ.gold,
    C: NQ.cream,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.beige]: NQ.sand, [NQ.brown]: NQ.bark },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '...............C',
        '..............AG',
        '..........C...VG',
        '.........AGA.VAG',
        '.........VGV.VAA',
        '..........V..VVA',
        '...............E',
        '............EEES',
        '.........E.ESEEE',
        '.........SEEEEEE',
        '........EEEEEEEE',
        '......EEEEEEEEEE',
        '......SEEEEEEEEE',
        '......EEEEEEEEEE',
        '.....EEEEEWWEEEE',
        '....EEEEEEWoEEEE',
        '....EEEEEEWoEEEE',
        '...EEEEEpEEEEEoE',
        '...SEEEEEEEEEEEo',
        '...EEEEEEEEEEEEE',
        '...EEEEEEEEEEEEE',
        '...SSSSSSSSSSSSS',
        '..SSSSSSSSSSSSSS',
        '..TTTTTTTTTTTTTT',
        '..TTTTTTTTTTTTTT',
        '..BBBBBBBBBBBBBB',
        '...BBBBBBBBBBBBB',
        '....BBBBBBBBBBBB',
      ],
    },
  ],
};

/** ギョウザムライ（ギョウザンの しんか）：ひだの かぶとに 赤い はちまき、大きな 炎。ぎょうざの 入った 鉄の フライパンを たてに する（ヒノ） */
const gyozamurai: MonsterDesign = {
  size: 32,
  colors: {
    E: NQ.beige,
    S: NQ.sand,
    T: NQ.tan,
    B: NQ.brown,
    V: NQ.vermilion,
    G: NQ.gold,
    W: NQ.white,
    p: NQ.blush,
    R: NQ.red,
    N: NQ.night,
    K: NQ.slate,
  },
  rim: { [NQ.beige]: NQ.sand },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '...............G',
        '..........G...VG',
        '.........VGV..VG',
        '.........VGV.VGV',
        '..........VV.VVV',
        '..........V..VVV',
        '............E..S',
        '.........E.ESEEE',
        '.........SEEEEEE',
        '........EEEEEEEE',
        '......EEEEEEEEEE',
        '......SEEEEEEEEE',
        '.....RRRRRRRRRRR',
        '.....EEEEEooEEEE',
        '....EEEEEEWWEEEE',
        '...EEEEEEEWoEEEE',
        '...SEEEEEEWoEEEE',
        '...EEEEEpEEEEEoo',
        '...EEEEEEEEEEEEE',
        '..EEEEEEEEEEEEEE',
        '..EEEEEEEEEEEEEE',
        '..SSSSSSSSSSSSSS',
        '..SSSSSSSSSSSSSS',
        '..TTTTTTTTTTTTTT',
        '.TTTTTTTTTTTTTTT',
        '.BBBBBBBBBBBBBBB',
        '...BBBBBBBBBBBBB',
        '....BBBBBBBBBBBB',
      ],
    },
    // はちまきの むすび目
    { x: 1, y: 13, rows: ['RR.', '.RR', 'R..'] },
    // 左手の 鉄の フライパン（中に ぎょうざ）
    {
      x: 1,
      y: 19,
      rows: [
        '..NNNNNN..',
        '.NKKKKKKN.',
        'NKESEESEKN',
        'NKEEEEEEKN',
        '.NKKKKKKN.',
        '..NNNNNN..',
        '.BB.......',
        'BB........',
      ],
    },
  ],
};

/** ベルモー：那須の 牧場の 白黒の 牛。首に 金の カウベル、ピンクの 鼻づら（ツチ） */
const bellMoo: MonsterDesign = {
  size: 32,
  colors: {
    W: NQ.white,
    K: NQ.night,
    P: NQ.blush,
    E: NQ.beige,
    G: NQ.gold,
    B: NQ.brown,
    p: NQ.blush,
  },
  rim: { [NQ.white]: NQ.cloud, [NQ.gold]: NQ.ochre },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '................',
        '........E.......',
        '........EE......',
        '.........EWWWWWW',
        '........WWWWWWWW',
        '..WWW..WWWWWWWWW',
        '.WPPWWWKKKKKWWWW',
        '..WWWWWKKWWKWWWW',
        '......WKKWoKWWWW',
        '......WKKWoKWWWW',
        '......WWKKKKWWWW',
        '......WWWWPPPPPP',
        '......WpWPPPPPPP',
        '......WWPPPPoPPP',
        '.......WPPPPPPPP',
        '.......WWPPPPPPP',
        '........WWWWWWWW',
        '.......BBBBBBBBB',
        '......WWWWWWWGGG',
        '.....WWKKWWWGGGG',
        '.....WKKKWWWGGGG',
        '.....WWKWWWWGGGG',
        '.....WWWWWWWWWWo',
        '......WWWWWWWWWW',
        '......WWWWWWWWWW',
        '.......WWW..WWW.',
        '.......WWW..WWW.',
        '.......KKK..KKK.',
      ],
    },
  ],
};

/** ゴウベルモー（ベルモーの しんか）：長く そった つの、きりっと した まゆ、ひろい かた。大きな カウベル、口に 草（ツチ） */
const goBellMoo: MonsterDesign = {
  size: 32,
  colors: {
    W: NQ.white,
    K: NQ.night,
    P: NQ.blush,
    E: NQ.beige,
    G: NQ.gold,
    B: NQ.brown,
    L: NQ.leaf,
    p: NQ.blush,
  },
  rim: { [NQ.white]: NQ.cloud, [NQ.gold]: NQ.ochre },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '..EE............',
        '...EE...........',
        '....EE..........',
        '.....EEE........',
        '......EEEWWWWWWW',
        '.......WWWWWWWWW',
        '.WWWW.WWWWWWWWWW',
        '.WPPPWWWoooWWWWW',
        '..WWWWWKKKKKWWWW',
        '......WKKWWKWWWW',
        '......WKKWoKWWWW',
        '......WKKWoKWWWW',
        '......WWKKKKWWWW',
        '......WWWWPPPPPP',
        '......WpWPPPPPPP',
        '......WWPPPPoPPP',
        '.......WPPPPPPPP',
        '.......WWWWWWWWW',
        '..WWWWBBBBBBBBBB',
        '.WWWWWWWWWWWWGGG',
        '.WWKKWWWWWWWGGGG',
        '.WKKKKWWWWWGGGGG',
        '.WWKKWWWWWWGGGGG',
        '.WWWWWWWWWWGGGGG',
        '..WWWWWWWWWWWWWo',
        '..WWWWWWWWWWWWWW',
        '...WWWW...WWWWW.',
        '...WWWW...WWWWW.',
        '...KKKK...KKKK..',
      ],
    },
    // 口に くわえた 草
    { x: 20, y: 16, rows: ['..L', '.L.', 'L..'] },
  ],
};

// ───────────────────────── 中ボス ─────────────────────────

/** オオヤイシドン（中ボス）：大谷石の ブロックを つみあげた 大男。ミソ（茶色の つぶ）と つるはしの あと、大きな こぶし（ツチ） */
const oyaishiDon: MonsterDesign = {
  size: 40,
  colors: {
    V: NQ.silver,
    G: NQ.gray,
    C: NQ.cloud,
    L: NQ.slate,
    T: NQ.tan,
    Y: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.silver]: NQ.gray, [NQ.gold]: NQ.ochre },
  rimDepth: 2,
  layers: [
    {
      mirror: true,
      rows: [
        '....................',
        '................Y..Y',
        '................YYYR',
        '................QQQQ',
        '...........VVVVVVVVV',
        '..........VCCVVVVVVV',
        '..........VCVVVGVVVV',
        '..........VVVVGVVVVV',
        '..........VVoooVVVVV',
        '..........VVVWWoVVVV',
        '..........VTVWWoVVVV',
        '..........VVVWWoVVVV',
        '..VVVVVVV.VVVWooVVVV',
        '.VCCVVVVVVVVpVVVVVoo',
        '.VCVVVGVVVVVVVVVVVVV',
        '.VVVVGVVVGGGGGGGGGGG',
        '.VVVGVVVVVVVVVVGVVVV',
        '.VVVVVVTVVVVTVVGVVVV',
        '.GGGGGGGGVVVVVVGVVVV',
        '.VVVVVV.GGGGGGGGGGGG',
        '.VTVVVV.VVVVGVVVVVVV',
        '.VVVVVV.VVTVGVVVVTVV',
        '.VVVVGV.VVVVGVVVVVVV',
        '.GGGGGG.GGGGGGGGGGGG',
        '.VVVVVV.VVVVVVVGVVVV',
        '.VVGVVV.VVVVTVVGVVVV',
        '.VVVVVV.VVVVVVVGVVVV',
        '.VVVVVV.GGGGGGGGGGGG',
        '.VGVGVV.VVVVVVVVVVVV',
        '.VGVGVV.VVVTVVVVGVVV',
        '.VVVVVV.VVVVVVVVGVVV',
        '..GGGG..GGGGGGGGGGGG',
        '........VVVVVGVVVVVV',
        '........VVTVVGVVVVVV',
        '........GGGGGGGGGGGG',
        '.........VVVVVV.....',
        '.........VVVVVV.....',
        '.........LLLLLL.....',
        '....................',
        '....................',
      ],
    },
  ],
};

/** オオヤイシドン（フィールドに立つ 32×32） */
const oyaishiDonField: MonsterDesign = {
  size: 32,
  colors: {
    V: NQ.silver,
    G: NQ.gray,
    C: NQ.cloud,
    L: NQ.slate,
    T: NQ.tan,
    Y: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
    W: NQ.white,
  },
  rim: { [NQ.silver]: NQ.gray },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '............Y..Y',
        '............YYYR',
        '............QQQQ',
        '.........VVVVVVV',
        '........VCCVVVVV',
        '........VCVVGVVV',
        '........VVoooVVV',
        '........VVVWoVVV',
        '........VVVWoVVV',
        '..VVVVV.VVVVVVoo',
        '.VCCVVVVVVVVVVVV',
        '.VCVVGVVGGGGGGGG',
        '.VVVGVVVVVVVGVVV',
        '.GGGGGGGVVTVGVVV',
        '.VVVVV.GGGGGGGGG',
        '.VTVVV.VVVGVVVVV',
        '.VVVGV.VVVGVVTVV',
        '.GGGGG.GGGGGGGGG',
        '.VVVVV.VVVVVGVVV',
        '.VGVGV.VVTVVGVVV',
        '.VVVVV.VVVVVGVVV',
        '..GGG..GGGGGGGGG',
        '.......VVVVGVVVV',
        '.......VTVVGVVVV',
        '.......GGGGGGGGG',
        '........VVVVV...',
        '........VVVVV...',
        '........LLLLL...',
      ],
    },
  ],
};

// ───────────────────────── 県ボス ─────────────────────────

const KEGON_HORNS = [
  '......G...G.........G..G',
  '......GG.GG.........GGGG',
  '.......GGG..G.......GGGR',
  '........GG.GG.......GGGR',
  '.........GGG........QQQQ',
  '..........GG............',
  '...........GG...........',
  '............GG..........',
];
const KEGON_HEAD = [
  '................AAAAAAAA',
  '..............AAAAAAAAAA',
  '.............AAAAAAAAAAA',
  '...........IIAAAAAAAAAAA',
  '..........IWIAoooAAAAAAA',
  '.........IWIAAAWWoAAAAAA',
  '........IWWIAAAWWoAAAAAA',
  '........IWIAAAAWWoAAAAAA',
  '.......IWWIAAAAWooAAAAAA',
  '.......IWIAAAAAAAASSSSSS',
  '......IWWIAAAAAASSSSSSSS',
  '......IWIAAAAASSSSSSSoSS',
  '.....IWWIAAAAASSSSSSSSSS',
  '.....IWIAAAAAAoooooooooo',
  '......IIAAAAAAACCCCCCWCC',
  '.......IAAAAAAACCCCCCCCC',
  '.........AAAAAAACCCCCCCC',
  '...........AAAAAACCCCCCC',
  '.............AAAAACCCCCC',
  '.............AAAAACCCCCC',
  '.............AABAASSSSSS',
  '..............AAAACCCCCC',
  '..............AAAACCCCCC',
];
/** 竜の からだの 下は そのまま 滝に なって 落ちる */
const KEGON_FALL = [
  '...............IWISWIWSI',
  '...............WISWIWSIW',
  '...............IWISWIWSI',
  '...............WISWIWSIW',
  '..............IWISWIWSIW',
  '..............WISWIWSIWI',
  '..............IWISWIWSIW',
  '..............WISWIWSIWI',
  '.............IWISWIWSIWI',
  '.............WISWIWSIWIS',
  '.............IWISWIWSIWI',
  '.............WISWIWSIWIS',
  '............IWISWIWSIWIS',
];
const KEGON_ARM = [
  '..........AAA',
  '.........AAAA',
  '........AAAA.',
  '.......AAAA..',
  '......AAAA...',
  '.....AAAAA...',
  '....AAAAAA...',
  '....SAAAAS...',
  '....W.W.W....',
];
const KEGON_WHISKER = [
  '..........MMM',
  '........MM...',
  '......MM.....',
  '.....M.......',
  '....M........',
  '....M........',
  '.....M.......',
  '......MM.....',
];
const KEGON_SPLASH = [
  '...W........W.......W...',
  '..WIW......WIW.....WIW..',
  '.WIIIW....WIIIW...WIIIW.',
  '.WISSIWWWWISSSIWWWISSSIW',
  '.ISSSSIIIISSSSSIIISSSSSI',
  '.SSAASSSSSSAASSSSSAASSSS',
  '.SAAAASSSSAAAASSSAAAASSS',
];

/** ケゴンリュウオウ（県ボス）：華厳の 滝の 竜の 王。金の えだ角と 王冠、しぶきの ひれ、長い ひげ。からだの 下は 滝と なって 落ちる（ミズ） */
const kegonRyuo: MonsterDesign = {
  size: 48,
  colors: {
    B: NQ.blue,
    A: NQ.azure,
    S: NQ.sky,
    I: NQ.ice,
    W: NQ.white,
    G: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
    C: NQ.cream,
    M: NQ.mint,
  },
  rim: { [NQ.azure]: NQ.blue, [NQ.gold]: NQ.ochre, [NQ.cream]: NQ.sky },
  rimDepth: 2,
  layers: [
    { mirror: true, y: 28, rows: KEGON_FALL },
    { mirror: true, y: 23, rows: KEGON_ARM },
    { mirror: true, y: 6, rows: KEGON_HEAD },
    { mirror: true, y: 1, rows: KEGON_HORNS },
    { mirror: true, y: 18, rows: KEGON_WHISKER },
    { mirror: true, y: 40, rows: KEGON_SPLASH },
  ],
};

/** ケゴンリュウオウ 後半：滝が こおり つき、ふぶきの 雪が まう */
const kegonRyuoP0: MonsterDesign = {
  ...kegonRyuo,
  colors: { ...kegonRyuo.colors, S: NQ.ice, I: NQ.white, C: NQ.white, M: NQ.white },
  layers: [
    ...kegonRyuo.layers,
    { x: 2, y: 8, rows: ['.I.', 'IWI', '.I.'] },
    { x: 43, y: 12, rows: ['.I.', 'IWI', '.I.'] },
    { x: 3, y: 34, rows: ['.I.', 'IWI', '.I.'] },
    { x: 42, y: 32, rows: ['.I.', 'IWI', '.I.'] },
    { x: 7, y: 2, rows: ['I'] },
    { x: 40, y: 3, rows: ['I'] },
  ],
};

// ───────────────────────── 裏ステージの ラスボス ─────────────────────────

/** 弓（左手で たてに もつ）。B = 弓、Y = にぎり、W = つる */
const BOW = [
  '...BB.',
  '...B.W',
  '..BB.W',
  '..B..W',
  '.BB..W',
  '.B...W',
  '.B...W',
  '.B...W',
  'BB...W',
  'B....W',
  'B....W',
  'B....W',
  'B....W',
  'YY...W',
  'YY...W',
  'YY...W',
  'B....W',
  'B....W',
  'B....W',
  'BB...W',
  '.B...W',
  '.B...W',
  '.B...W',
  '.BB..W',
  '..B..W',
  '..BB.W',
  '...B.W',
  '...BB.',
];

/** 那須与一：「扇の 的」の 赤い 扇に 金の 日の丸の 前立て、萌黄（もえぎ）の よろい、左手に 弓（カゼ） */
const nasuNoYoichi = lord(
  [
    '........................',
    '...................GGGGG',
    '.................GGRRRRR',
    '................GRRRRRRR',
    '..............GGRRRRYYYY',
    '..............GRRRRRYYYY',
    '................GRRRYYYY',
    '..................GRRRRR',
    '....................GRRR',
    '...............NNNNGGGGG',
    ...HELMET,
    ...FACE,
  ],
  {
    N: NQ.night,
    L: NQ.slate,
    K: NQ.leaf,
    S: NQ.lime,
    G: NQ.gold,
    Y: NQ.yellow,
    R: NQ.red,
    T: NQ.green,
    H: NQ.forest,
    B: NQ.brown,
  },
  { [NQ.lime]: NQ.leaf },
  [{ x: 1, y: 17, rows: BOW }],
);

export const TOCHIGI: Readonly<Record<string, MonsterDesign>> = {
  'tochigi-ichigoro': ichigoro,
  'tochigi-ichigo-ouji': ichigoOuji,
  'tochigi-gyozan': gyozan,
  'tochigi-gyozamurai': gyozamurai,
  'tochigi-bellmoo': bellMoo,
  'tochigi-go-bellmoo': goBellMoo,
  'tochigi-midboss-oyaishi-don': oyaishiDon,
  'tochigi-midboss-oyaishi-don.field': oyaishiDonField,
  'tochigi-boss-kegon-ryuo': kegonRyuo,
  'tochigi-boss-kegon-ryuo.p0': kegonRyuoP0,
  'tochigi-lastboss-nasu-no-yoichi': nasuNoYoichi,
};
