/** 東北の地方ボス（docs/05 §3、docs/06 §6.6） */
import { NQ } from '../palette';
import type { MonsterDesign } from './design';

/**
 * ロクフユノオウ（六冬の王）：東北の 長い 冬 そのもの。雪と 氷の 大きな 王さま（ミズ）。
 * 雪の たてがみと つららの ひげ、6 本の 氷の とげの 王冠、むねに 6 つの 角の 雪の結晶、まわりに 雪。
 * 6 県の たからものを 1 つずつ 身につける：ねぶたの お面（青森）・わらの ケープ（秋田）・
 * 左手で ふりまわす 南部鉄びん（岩手）・三日月の 前立て（宮城）・こしの さくらんぼ（山形）・右手の 赤べこ（福島）
 */
const rokufuyuColors = {
  W: NQ.white,
  I: NQ.ice,
  S: NQ.sky,
  A: NQ.azure,
  B: NQ.blue,
  N: NQ.navy,
  G: NQ.gold,
  g: NQ.ochre,
  R: NQ.red,
  r: NQ.brick,
  P: NQ.paper,
  T: NQ.sand,
  K: NQ.night,
  L: NQ.slate,
  // むねの 雪の結晶（n：まるい 板、w：結晶）と 鉄びんの あられ（d）。第 2 形態で 色を かえる
  n: NQ.navy,
  w: NQ.white,
  d: NQ.slate,
};
const rokufuyu: MonsterDesign = {
  size: 56,
  colors: rokufuyuColors,
  rim: { [NQ.sky]: NQ.azure, [NQ.sand]: NQ.ochre },
  rimDepth: 2,
  layers: [
    // 三日月の 前立て・氷の とげの 王冠・雪の たてがみ・ねぶたの お面・氷の 大そで・わらの ケープ・雪の結晶の むね
    {
      mirror: true,
      rows: [
        '............................',
        '..............G.............',
        '..............GG...........I',
        '...............GG.........IS',
        '...............GGg....I...IS',
        '................GGg..IS..IIS',
        '.................GGgIIS..IIS',
        '..................GGgISS.IIS',
        '...................GGgSSIISS',
        '....................GGGgISSS',
        '.....................GGGGGGG',
        '.............WWIIIGGGGGGGGGR',
        '...I........WWWIIIgggggggggR',
        '...IS...I..WWWIIIIoooooooooo',
        '..IIS...IS.WWIIIIIoRPPPPPPPP',
        '..IISS..IISWWIIIIIoRRPPPPPPP',
        '..IISS.IIISWIIIIIIoPRRPPPPPP',
        '.IIISSSIIISSWIIIIIoPRooPPPPP',
        '.IIISSSIIISSSWIIIIoPPPoooooP',
        '.IIISSSSIISSSSWIIIoPPoWWWSoP',
        '..WWWWWWWWWWWWIIIIoPPoWWSSoP',
        '.WWIWWIWWIWWWWIIIIoBBPooooPP',
        '.SIIIIIIIIIIISIIIIoBBPPPoPPP',
        '.SIIIIIIIIIISSIIIIoPBPPooooo',
        '.SSIIIIIIIISSSWIIIoPPPoRRRRR',
        '.SSSIIIIIISSSSWWIIoPPPPooooo',
        '.ASSSSSSSSSSSAWWWWoooooooooo',
        '.NBBBBBBBBBBBNWWWWWWWIWWWWIW',
        '.TTgTTgTIISSSSoSSSSWWIWWWIWW',
        '.TTgTTgTISSSSAoSSSSSWWIWWIWW',
        '.TTgTTgTBBBBBBoSSSSSSIWSIWIW',
        '.TTgTTgTISSSSAoSSSSSSSSSnnnn',
        '.TTgTTgTISSSSAoSSSSSSSSnwnnw',
        '.TTgTTgTIISSAAoSSSSSSSnnnwnw',
        '.TTgTTgoIIISSSoSSSSSSSnnnnww',
        '.TTgTTgIIIISSSoSSSSSSSnnnnww',
        '.TTgTTgIIIIISSoSSSSSSSnnnnww',
        '.TTgTTgIIIISSAoSSSSSSSnnnwnw',
        '.TTgTTgoAAAAAooSSSSSSSSnwnnw',
        '.TTgTTg.......oSSSSSSSSSnnnn',
        '.TTgTTg.......GGGGGGGGGGGGGG',
        '.TTgTTg.......gggggggggggggg',
        '..gTTgT.......SSSSSSSSSSSSSS',
        '..g.Tg........BBBBBBBBBBBBBB',
        '.....g........ISSISSISSISSIS',
        '..............I.ISSSSSA.I..I',
        '................ISSSSSA.....',
        '................BBBBBBB.....',
        '................ISSSSSA.....',
        '................ISSSSSA.....',
        '...............IISSSSSAA....',
        '..............IIISSSSSAAA...',
        '.............IIIISSSSSAAAA..',
        '.............WWWWWWWWWWWWW..',
      ],
    },
    // まわりの 雪
    { mirror: true, x: 3, y: 2, rows: ['.I.I.', '..W..', 'IWWWI', '..W..', '.I.I.'] },
    { mirror: true, x: 9, y: 7, rows: ['.W.', 'WIW', '.W.'] },
    // 左手で ふりまわす 南部鉄びん（岩手）
    {
      x: 1,
      y: 39,
      rows: [
        '.........L...',
        '........L....',
        '...LLLLLLLL..',
        '..L........L.',
        '..L...KK...L.',
        '..L.KKKKKK.L.',
        'L.KKKKKKKKKK.',
        'LLKdKKdKKdKKK',
        '..KKKKKKKKKKK',
        '..KdKKdKKdKKK',
        '..KKKKKKKKKK.',
        '...KKdKKdKK..',
        '....KKKKKK...',
      ],
    },
    // こしの さくらんぼ（山形）
    {
      x: 16,
      y: 41,
      rows: [
        '....g....',
        '...g.g...',
        '..g...g..',
        '.ooo..g..',
        'oWRRo.ooo',
        'oRRro.WRRo',
        'oRrro.RRro',
        '.ooo.oRrro',
        '......ooo.',
      ],
    },
    // 右手に さげた 赤べこ（福島）
    { x: 45, y: 39, rows: ['R', 'R', 'R'] },
    {
      x: 41,
      y: 42,
      rows: [
        '...g.........',
        '.o.go........',
        'oRoRRo.......',
        'oRRRRRoooooo.',
        'oRoRRRRRRRRRo',
        'oWWRRRGRRGRRo',
        '.ooRRRRRRRRRo',
        '...ooRRoooRRo',
        '....oKo...oKo',
        '....oo....oo.',
      ],
    },
  ],
};

/** 第 2 形態（ヒノ）：氷が われて、右の 大そでから ほのお。むねの 雪の結晶が 火の 金に、目も 金に もえ、鉄びんの あられが 赤く 光る */
const rokufuyuBurning: MonsterDesign = {
  ...rokufuyu,
  colors: {
    ...rokufuyuColors,
    W: NQ.ice,
    w: NQ.gold,
    B: NQ.navy,
    n: NQ.brick,
    d: NQ.vermilion,
    V: NQ.vermilion,
    F: NQ.apricot,
  },
  rim: { [NQ.sky]: NQ.azure, [NQ.sand]: NQ.ochre, [NQ.vermilion]: NQ.brick },
  layers: [
    ...rokufuyu.layers,
    // 右の 大そでの 氷が ほのおに
    {
      x: 43,
      y: 11,
      rows: [
        '.....V......',
        '....VF...V..',
        '...VFV..VF..',
        '...VFFV.VFV.',
        '..VFGFV.VFFV',
        '..VFGGFVFGFV',
        '.VFGGGFVFGGV',
        '.VFGGGGFGGGV',
        'VFFGGGGGGGFV',
        'VVFFGGGGGFFV',
        '.VVFFFFFFFVV',
      ],
    },
    // よろいの われめ
    {
      x: 35,
      y: 27,
      rows: [
        'V....',
        'FV...',
        '.V...',
        '.FV..',
        '..VF.',
        '..V..',
        '.VF..',
        '.V...',
        'VF...',
        'V....',
        'FV...',
        '.V...',
      ],
    },
    // もえる 目と 火の粉
    { mirror: true, x: 22, y: 19, rows: ['GGGF', 'GGFF'] },
    { x: 49, y: 3, rows: ['.F.', 'FGF', '.F.'] },
    { x: 38, y: 9, rows: ['F'] },
    { x: 53, y: 23, rows: ['G'] },
  ],
};

/** 第 3 形態（むぞくせい）：氷が とけて 小さく まるくなった。にっこり すわって、春を まっていた */
const rokufuyuSpring: MonsterDesign = {
  size: 56,
  colors: {
    W: NQ.white,
    I: NQ.ice,
    S: NQ.sky,
    A: NQ.azure,
    G: NQ.gold,
    g: NQ.ochre,
    R: NQ.red,
    r: NQ.brick,
    P: NQ.paper,
    T: NQ.sand,
    K: NQ.night,
    L: NQ.slate,
    Z: NQ.leaf,
    p: NQ.blush,
  },
  rim: { [NQ.ice]: NQ.sky, [NQ.sand]: NQ.ochre },
  rimDepth: 2,
  layers: [
    // 雪の からだ・にっこり顔・小さな 三日月・頭の 若葉と さくら・わらの えりまき・地面の 鉄びん
    {
      rows: [
        '........................................................',
        '........................................................',
        '........................................................',
        '........................................................',
        '........................................................',
        '........................................................',
        '........................................................',
        '........................................................',
        '...........................p............................',
        '..........................pGp...........................',
        '...........................p............................',
        '...........................Z.ZZZ........................',
        '...........................ZZZZ.........................',
        '.......................ZZZ.Z............................',
        '........................ZZZZ............................',
        '...........................Z............................',
        '....................W......Z.......G....................',
        '....................GG.....Z......GG....................',
        '.....................GG....Z.....GG.....................',
        '......................GG...Z....GG......................',
        '.......................GGGIIIIGGG.......................',
        '.....................WWIIggggggIIII.....................',
        '....................WIIIIIIIIIIIIIII....................',
        '...................WIIIIIIIIIIIIIIIII...................',
        '..................IIIIIIIIIIIIIIIIIIII..................',
        '..................IIIIIIIIIIIIIIIIIIIS..................',
        '..................IIIIIIIIIIIIIIIIIISS..................',
        '..................IIIIIooIIIIIIooIISSS..................',
        '..................IIIIoIIoIIIIoIIoSSSS..................',
        '..................IIIIIIIIIIIIIISSSSSS..................',
        '..................IIIppIIIIIIIISSppSSS..................',
        '..................IIIIIIIIoIIoSSSSSSSS..................',
        '...................IIIIIIIIooSSSSSSSS...................',
        '....................IIIIIIIISSSSSSSS....................',
        '...................TTTTTTTTTTTTTTTTTT...................',
        '.................TgTTgTTgTTgTTgTTgTTgTT.................',
        '................TTgTTgTTgTTgTTgTTgTTgTTg................',
        '..............TgTTgTTgTTgTTgTTgTTgTTgTTgTT..............',
        '...............gTIgTIgTIgTIgTIgTIgTIgTIgT...............',
        '...............gIIgIIgIIgIIgIIgIIgIIgIIgS...............',
        '...............IWooIIIIIIIIIIIIIIIIIIooSS...............',
        '..W...........IIWIIoIIIIIIIIIIIIIIIIoSSSSS..............',
        '.WWW..........IIIIIoIIIIIIIIIIIIIIISoSSSSS..............',
        '..W...LLLLL...IIIIIIoIIIIIIIIIIIIISoSSSSSS..............',
        '.W...L.....L.IIIIIIoIIIIIIIIIIIISSSSoSSSSSS.............',
        '.W..L...L...L.IIIIIoIIIIIIIIIIISSSSSoSSSSS..............',
        '....L..KKK..L.AAAooAAAAAAAAAAAAAAAAAAooAAA..............',
        '.L...LLLKKKK..AAAAAAAAAAAAAAAAAAAAAAAAAAAA..............',
        '.K..KoooooooK..IIIIIIIIIIIISSSSSSSSSSSSSS...............',
        '..KLKKKKKKKKKK.IIIIIIIIIISSSSSSSSSSSSSSSS...............',
        '..KLKKLKKLKKLK..IIIIIIIISSSSSSSSSSSSSSSS................',
        '...LKKKKKKKKKK...IIIIISSSSSSSSSSSSSSSSS.................',
        '...KKLKKLKKLKK....oooooooSSSSSSooooooo..................',
        '....KKKKKKKKK.....WWWWWWWSSSSSSWWWWWWW..................',
        '......KKKKK........WWWWWSSSSSSSSWWWWW...................',
        '........................................................',
      ],
    },
    // 横に つけた ねぶたの お面
    {
      x: 11,
      y: 20,
      rows: ['.ooooo.', 'oPPRPPo', 'ooPPPoo', 'oWoPoWo', 'oRPPPRo', 'oPoooPo', '.oPPPo.', '..ooo..'],
    },
    // おびの さくらんぼ
    { x: 17, y: 47, rows: ['..g.g..', '.g...g.', 'ooo.ooo', 'WRo.WRo', 'Rro.Rro', 'oo..oo.'] },
    // となりに すわる 赤べこ
    {
      x: 43,
      y: 47,
      rows: [
        '.o.o........',
        'oRoRo.......',
        'oRRRRoooooo.',
        'oRoRRRRRRRRo',
        'oWWRRGRRGRRo',
        '.ooRRRRRRRRo',
        '...oRooooRo.',
        '...oKo..oKo.',
      ],
    },
  ],
};

export const TOHOKU: Readonly<Record<string, MonsterDesign>> = {
  'tohoku-boss-rokufuyu': rokufuyu,
  'tohoku-boss-rokufuyu.p0': rokufuyuBurning,
  'tohoku-boss-rokufuyu.p1': rokufuyuSpring,
};
