/** 山形のモンスター（docs/05 §2.4、docs/06 §6.3〜6.5） */
import { NQ } from '../palette';
import type { MonsterDesign } from './design';
import { LAST_BOSSES } from './lastbosses';

/** サクランボーイ：1 本の軸にふたごのさくらんぼ。頭が 2 つある 1 体のモンスター（モリ） */
const sakuranboy: MonsterDesign = {
  size: 32,
  colors: {
    R: NQ.red,
    r: NQ.brick,
    W: NQ.white,
    p: NQ.blush,
    e: NQ.berry,
    g: NQ.green,
    G: NQ.leaf,
    L: NQ.lime,
  },
  layers: [
    {
      rows: [
        '................................',
        '......................LLG.......',
        '....................LLGGGg......',
        '..................LLGGGGg.......',
        '...............gLLGGGggg........',
        '...............g.gggg...........',
        '...............g................',
        '..............ggg...............',
        '.............gg.gg..............',
        '............gg...gg.............',
        '...........gg.....gg............',
        '..........gg.......gg...........',
        '.........gg.........gg..........',
        '........gg...........gg.........',
        '.......gg.............gg........',
        '......RRRR...........RRRR.......',
        '....RRRRRRRR.......RRRRRRRR.....',
        '...RWRRRRRRRR.....RWRRRRRRRR....',
        '..RWRRRRRRRRRR...RWRRRRRRRRRR...',
        '..RRWWRRRRWWRR...RRWWRRRRWWRR...',
        '.RRRWoRRRRoWRRR.RRRWoRRRRoWRRR..',
        '.RRRWoRRRRoWRRR.RRRWoRRRRoWRRR..',
        '.RRpRRRRRRRRpRr.RRpRRRRRRRRpRr..',
        '.RRRRRoRRoRRRrr.RRRRRooooRRRrr..',
        '..RRRRRooRRrrr...RRRRoeeoRrrr...',
        '..RRRRRRRRrrrr...RRRRRooRrrrr...',
        '...RRRRRrrrrr.....RRRRRrrrrr....',
        '....RRRrrrrr.......RRRrrrrr.....',
        '.....Rrrrrr.........Rrrrrr......',
        '.....rr..rr.........rr..rr......',
        '.....rr..rr.........rr..rr......',
        '................................',
      ],
    },
  ],
};

/** ショウギコマンダー：天童の将棋の駒の兵隊。字のかわりに赤いしるし、軍配とやり（ツチ） */
const shogiCommander: MonsterDesign = {
  size: 32,
  colors: {
    B: NQ.beige,
    S: NQ.sand,
    P: NQ.paper,
    T: NQ.tan,
    N: NQ.brown,
    W: NQ.white,
    p: NQ.blush,
    R: NQ.red,
    r: NQ.brick,
    I: NQ.silver,
    Y: NQ.gold,
  },
  rim: { [NQ.beige]: NQ.sand },
  layers: [
    {
      rows: [
        '................................',
        '............................I...',
        '...........................IWI..',
        '...........................IWI..',
        '...............BB...........I...',
        '....R.........PBBB.........RNR..',
        '..RRRRR......PBBBBB.........N...',
        '..RRRRR.....PBBBBBBB........N...',
        '..RYYRR....PBBBBBBBBB.......N...',
        '..RYYRR...PBBBBBBBBBBB......N...',
        '..RRRrr..PBBBBBBBBBBBBB.....N...',
        '..RRrrr.PBBTTBBBBBBTTBBB....N...',
        '....r...BBBBBBBBBBBBBBSB....N...',
        '....N...BSBWWBBBBBBWWBSB....N...',
        '....N...BSBWoBBBBBBoWBSB....N...',
        '...BN...BSBWoBBBBBBoWBSB....N...',
        '..BBBB..BSpBBBBBBBBBBpSB....B...',
        '..BBBBBBBSBBBBoBBoBBBBSBBBBBBB..',
        '...BBBBBBSBBBBBooBBBBBSBBBBBBB..',
        '.......BBSBBBBBBBBBBBBSBB...B...',
        '.......BBSBBBBRRRRBBBBSBB...N...',
        '.......BBSBBBRRBBRRBBBSBB...N...',
        '.......BBSBBBRBRRBrBBBSBB...N...',
        '......BBBSBBBRRBBrrBBBSBBB..N...',
        '......BBBSBBBBrrrrBBBBSBBB..N...',
        '......BBBSBBBBBBBBBBBBBBBB..N...',
        '......BBBBBBBBBBBBBBBBBBBB..N...',
        '......BBBBBBBBBBBBBBBBBBBB..N...',
        '..........TTT......TTT......N...',
        '..........TTT......TTT..........',
        '..........NNN......NNN..........',
        '................................',
      ],
    },
  ],
};

/** イモニナベ：芋煮の大なべのモンスター。さといも・牛肉・ねぎ、ふたはぼうし（ヒノ） */
const imoniNabe: MonsterDesign = {
  size: 32,
  colors: {
    S: NQ.slate,
    K: NQ.night,
    g: NQ.gray,
    W: NQ.white,
    c: NQ.cloud,
    p: NQ.blush,
    b: NQ.brown,
    L: NQ.leaf,
    F: NQ.vermilion,
    Y: NQ.gold,
    e: NQ.berry,
  },
  layers: [
    {
      rows: [
        '................................',
        '...............Y................',
        '...............YF...........WW..',
        '..............FYYF.........WWcW.',
        '............ggSSSSSS........cc..',
        '..WW......ggSSSSSSSSKK..........',
        '.WWW....SSSSSSSSSSSSSSKK........',
        '..cW..KKKKKKKKKKKKKKKKKKKK......',
        '.....cWc....cWc.....cWc.........',
        '....cWWcbbLLcWWcLbbbcWWcLb......',
        '....ccccbbbLccccLLbbccccLL......',
        '...gggggggggggggggggggggggggg...',
        '...SSSSSSSSSSSSSSSSSSSKKKKKKK...',
        '....SSSSSSSSSSSSSSSSSSSSSSSS....',
        '.SSSSggSSSSSSSSSSSSSSSSSSSSSSKK.',
        '.S.SSgSSSSSSSSSSSSSSSSSSSSSSS.K.',
        '.SSSSgSSSSWWSSSSSSSSWWSSSSSSSKK.',
        '...SSgSSSSWoSSSSSSSSoWSSSSSSS...',
        '...SSSSSSSWoSSSSSSSSoWSSSSSSS...',
        '...SSSSSSpSSSSSSSSSSSSpSSSSSS...',
        '...SSSSSSSSSSSooooSSSSSSSSSSK...',
        '...SSSSSSSSSSSoeeoSSSSSSSKKKK...',
        '...SSSSSSSSSSSSooSSSSSSKKKKKK...',
        '....SSSSSSSSSSSSSSSSSKKKKKKK....',
        '....SSSSSSSSSSSSSSKKKKKKKKKK....',
        '.....SSSSSSSSSSSKKKKKKKKKKK.....',
        '......SSSSSSSSKKKKKKKKKKKK......',
        '.......SSSSKKKKKKKKKKKKKK.......',
        '.........KKKKKKKKKKKKKK.........',
        '.......KKK...F..F.F...KKK.......',
        '.......KKK..FYFFYFYF..KKK.......',
        '................................',
      ],
    },
  ],
};

/** ジュヒョウン：蔵王の樹氷から生まれた、もこもこの雪の大男。氷の枝のつめ（ミズ・中ボス） */
const juhyon: MonsterDesign = {
  size: 40,
  colors: {
    W: NQ.white,
    c: NQ.cloud,
    I: NQ.ice,
    k: NQ.sky,
    A: NQ.azure,
    B: NQ.blue,
    p: NQ.blush,
    Y: NQ.gold,
    O: NQ.ochre,
    R: NQ.red,
  },
  rim: { [NQ.white]: NQ.cloud },
  rimDepth: 2,
  layers: [
    {
      rows: [
        '........................................',
        '..I...I..........................I...I..',
        '..Ik.IkI........................IkI.kI..',
        '.IIk.Ik.I.....Y....YY....Y.....I.kI.kII.',
        '..IIkIkII.....YY..YYYY..YY.....IIkIkII..',
        '...IIIII......YYYYYYYYYYYY......IIIII...',
        '....WWW.......YYYYYRRYYYYY.......WWW....',
        '......W.......OOOOOOOOOOOO.......W......',
        '....WWWWW........WWWWWW........WWWWW....',
        '....WWWWW......WWWWWWWWWW......WWWWW....',
        '.WWWWWWWWW....WWWWWWWWWWWW....WWWWWWWWW.',
        '..WWWWWWWW...ooWWWWWWWWWWoo...WWWWWWWW..',
        '...WWWWWWW..WWoookkkkkkoooWW..WWWWWWW...',
        '...WWWWWWW..WWWWWkkkkkkWWWWW..WWWWWWW...',
        '..WWWWWWWWW.WWWWokkkkkkoWWWW.WWWWWWWWW..',
        '...WWWWWWW..WWWWokkkkkkoWWWW..WWWWWWW...',
        '.WWWWWWWWW..WkWookkkkkkooWkW..WWWWWWWWW.',
        '..WWWWWWWWWWWWkkkkkkkkkkkAWWWWWWWWWWWW..',
        '...WWWWWWWWWpWkkooooooooAAWpWWWWWWWWW...',
        '....WWWWWWWWWWWkoWBBBBWoAWWWWWWWWWWW....',
        '....WWWWWWWWWWWWAooooooAWWWWWWWWWWWW....',
        '.....WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW.....',
        '.....WWcWWWWWWWcWWWWWWWWcWWWWWWWcWW.....',
        '...WWWWWcccccccWWWWWWWWWWcccccccWWWWW...',
        '....W.WWWkkkkkcWWWWWWWWWWckkkkkWWW.W....',
        '......WWWWWWWWWccccccccccWWWWWWWWW......',
        '......WWWWWWWWWWkkkkkkkkWWWWWWWWcc......',
        '......WWWWWWWWWWWWWWWWWWWWWWWWcccc......',
        '....WWWWcWWWWWWWWcWWWWcWWWWWcccccccc....',
        '.....W.WWccccccccWWWWWWcccccccccc.c.....',
        '.......WWWkkkkkkWWWWWWWWkkkkkkccc.......',
        '........WWWWWWWcWWWWWWWcccccccck........',
        '.........WWWWWWWccccccccccccckk.........',
        '........WWWWWWWWWkkkkkkcccckkkkk........',
        '.........WWWWWWWWccccccccckkkkk.........',
        '..........WWWWWccccccccckkkkkk..........',
        '..........WWWccccccccckkkkkkkk..........',
        '........WWWWccccc......kkkkkkkkk........',
        '.........Wccccccc......kkkkkkkk.........',
        '........................................',
      ],
    },
  ],
};

/** ジュヒョウン（フィールドに立つ 32×32） */
const juhyonField: MonsterDesign = {
  size: 32,
  colors: {
    W: NQ.white,
    c: NQ.cloud,
    I: NQ.ice,
    k: NQ.sky,
    A: NQ.azure,
    Y: NQ.gold,
    O: NQ.ochre,
    R: NQ.red,
  },
  rim: { [NQ.white]: NQ.cloud },
  layers: [
    {
      rows: [
        '................................',
        '................................',
        '.I...I.....Y...YY...Y.....I...I.',
        '.Ik.IkI....YY.YYYY.YY....IkI.kI.',
        '..IIII.....YYYYRRYYYY.....IIII..',
        '...WW......OOOOOOOOOO......WW...',
        '....WW.......WWWWWW.......WW....',
        '...WWWW....WWWWWWWWWW....WWWW...',
        '..WWWWWW..WWWWWWWWWWWW..WWWWWW..',
        '.WWWWWWW..WooWkkkkWooW..WWWWWWW.',
        '..WWWWWW.WWWkokkkkokWWW.WWWWWW..',
        '..WWWWWW.WWkWWkkkkWWkWW.WWWWWW..',
        '..WWWWWW.WWkWokkkkoWkWW.WWWWWW..',
        '..WWWWWW.WWkWokkkkoWAWW.WWWWWW..',
        '.WWWWWWWWWWkkkooooAAAWWWWWWWWWW.',
        '..WWWWWWWWWWkkWooWAAWWWWWWWWWW..',
        '....WWWWWWWWWWAAAAWWWWWWWWWW....',
        '...WWWWWWWWWWWWWWWWWWWWWWWWWW...',
        '....WWWWWWWWWWWWWWWWWWWWWWWW....',
        '....WWWcWWWWcWWWWWWcWWWWcWWW....',
        '..WW.WWWccccWWWWWWWWccccWWW.cc..',
        '...W.WWWWAAWcWWWWcWWWAAWWWc.c...',
        '.....WWWWWWWWccccWWWWWWWWcc.....',
        '.....WWWWWWWWWAAWWWWWWWcccc.....',
        '......WWWWWWWWWWWWWWWccccc......',
        '......WWWcWWWWcWWcWccccccc......',
        '.....WWWWWccccWWWWccccccccc.....',
        '......W.WWWAAWWWcccAAccc.c......',
        '........WWWWWWcccccccccc........',
        '........WWWWcccccccccccc........',
        '........WWWccc....cccccc........',
        '................................',
      ],
    },
  ],
};

/** ジュヒョウノカミ：蔵王の樹氷の巨人。氷の枝の角と金のかんむり、雪のひげと雪のマント、氷のやり（ミズ・県ボス） */
const juhyoNoKami: MonsterDesign = {
  size: 48,
  colors: {
    N: NQ.navy,
    B: NQ.blue,
    A: NQ.azure,
    k: NQ.sky,
    I: NQ.ice,
    W: NQ.white,
    c: NQ.cloud,
    Y: NQ.gold,
    O: NQ.ochre,
    R: NQ.red,
  },
  rim: { [NQ.blue]: NQ.navy, [NQ.white]: NQ.cloud },
  layers: [
    {
      rows: [
        '................................................',
        '.......W...W........................W...W..W....',
        '........I..I..W..................W..I..I...WI...',
        '........I..I..I..W............W..I..I..I..IWIk..',
        '.........I.I...II..............II...I.I...IWIk..',
        '.........kIII..I.......YY.......I..IIIk..IIWIkk.',
        '..........kkI..I.......YY.......I..Ikk....IWIk..',
        '............kIII...Y..YYYY..Y...IIIk.......Ik...',
        '.............kkII..YYNYYYYNYY..IIkk.......YYYY..',
        '...............kkIYYYYYRRYYYYYIkk..........Ik...',
        '.................kOOOOOOOOOOOOk............Ik...',
        '..................ooIooNNooIoo.............Ik...',
        '..................oIWIoNNoIWIo.............Ik...',
        '..................ooIooNNooIoo.............Ik...',
        '.............WWWW.NNNNNNNNNNNN.WWWW........Ik...',
        '.........WWWWWWWWWNWWWWWWWWWWNWWWWWWWWW....Ik...',
        '......cWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWc.Ik...',
        '......AWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWB.Ik...',
        '......IccWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWccI.Ik...',
        '.......ABccccWWWWccccBWWWWBccccWWWWccccBB..Ik...',
        '....cWWWWBBBBccccBBBBIBWWBIBBBBccccBBBBWWWWIk...',
        '....AWWWWIWWIBBBBBIBBBIWIkBBBIBBBBBIWWIWWWWIk...',
        '.....ccWWWWWWWWIcBBBBBIIkkBBBBBcIWWWWWWWWccIk...',
        '.....ABccccccccBBBBBBBBkkBBBBBBBBccccccccBBIk...',
        '.....WIBBBBBBBBIYYYYYYYYYYYYYYYYIBBBBBBBBIWIk...',
        '.....WcWBBBBB..OOOOOOOOOOOOOOOOOO..BBBWWWWWWWW..',
        '.....WcWBBBBB...WWWWWWWWWWWWWWWW...BBBBBBBBBBB..',
        '....WWcWBBBBB...WWWWWWWWWWWWWWWW...BBBBBBBBBBB..',
        '....WWcWBBBBB..WccccccccccccccccW...WWBBBBBBBB..',
        '....WWcWWWWWW.WWBBBBBBBBBBBBBBBBWW..WWBBBBBBBB..',
        '...WWWcWBBBBBWWcBBBBBBBBBBBBBBBBcWW.WWcWWcWIk...',
        '......cBBBBBBBcNNNNNNNNNNNNNNNNNNcWW..c..c.Ik...',
        '...W.W.WBBBBBcNWWWWWWWWWWWWWWWWWWNcWW.W.W.WIk...',
        '........ABBBBNccccccccccccccccccccNN.......Ik...',
        '...........WWWAABBBBBBBBBBBBBBBNNNWWW......Ik...',
        '..........WWccAABBBBBBBBBBBBBBBNNNccWW.....Ik...',
        '.........WWcNNNBBBBBNNNNNNNNBBBBNNNNcWW....Ik...',
        '.........WcN..ABBBBB........BBBBNA..NcW....Ik...',
        '.........NN...ANNNNN........NNNNNA...NN....Ik...',
        '.............WWWWWWWW......WWWWWWWW........Ik...',
        '.............cccccccc......cccccccc........Ik...',
        '..............ABBBBB........BBBBBA.........Ik...',
        '..............ABBBBB........BBBBBA.........Ik...',
        '.............WWWWWWWW......WWWWWWWW........Ik...',
        '.............ANNNNNNN......NNNNNNNB........Ik...',
        '.............ANNNNNNN......NNNNNNNB........Ik...',
        '.............ANNNNNNN......NNNNNNNB........Ik...',
        '................................................',
      ],
    },
  ],
};

/** ジュヒョウノカミ 後半：ふぶきが まきおこり、目が白く光る */
const juhyoNoKamiP0: MonsterDesign = {
  ...juhyoNoKami,
  layers: [
    ...juhyoNoKami.layers,
    // ふぶき・光る目
    {
      x: 1,
      y: 4,
      rows: [
        '.WW...........................................',
        'W..W.W........................................',
        '....W.........................................',
        '..............................................',
        '..............................................',
        '..............................................',
        '..............................................',
        '..................kWk....kWk..................',
        '..................WWW....WWW..................',
        '..................kWk....kWk.................W',
        '..............................................',
        '...W..........................................',
        '..............................................',
        '..............................................',
        '..............................................',
        '.W............................................',
        '..............................................',
        '..............................................',
        '..............................................',
        '..............................................',
        '..............................................',
        '..............................................',
        '..............................................',
        '..............................................',
        '..............................................',
        '..............................................',
        '..............................................',
        '..............................................',
        '..............................................',
        '..............................................',
        '.WW..........................................W',
        'W..W.W........................................',
        '....W..................................W......',
        '..............................................',
        '..W...........................................',
        '..............................................',
        '..............................................',
        '.............................................W',
        '......W.......................................',
      ],
    },
  ],
};

/** さくらんぼ 2 つ（左右 14 ドットずつ、まんなかに 2 ドット）を 1 行にならべる。mid は ふたりが つなぐ 手 */
const twin = (l: string, r: string = l, mid = '..'): string => `.${l}${mid}${r}.`;

/** ダブルチェリー：サクランボーイの しんか。大きくなった ふたごが 手を つなぐ、葉っぱの かんむり、紅花（モリ） */
const doubleCherry: MonsterDesign = {
  size: 32,
  colors: {
    R: NQ.red,
    r: NQ.brick,
    W: NQ.white,
    p: NQ.blush,
    e: NQ.berry,
    g: NQ.green,
    G: NQ.leaf,
    L: NQ.lime,
    F: NQ.vermilion,
    A: NQ.apricot,
    Y: NQ.gold,
  },
  layers: [
    {
      rows: [
        '................................',
        '....LLLG................LLGG....',
        '....LGGGGGg..........LLGGGGg....',
        '......gGGGGGgg.gg.LGGGGGgg......',
        '.........gGGggggggggGGg.........',
        '.............AFAAFA.............',
        '............FAYYYYAF............',
        '.............gFAAFg.............',
        '............gggggggg............',
        '..........gg........gg..........',
        '.........gg..........gg.........',
        '........gg............gg........',
        twin('...RRRggRRR...'),
        twin('..RRRRRRRRRR..'),
        twin('.RRRRRRRRRRRR.'),
        twin('.RWWRRRRRRRRR.'),
        twin('RRWRRRRRRRRRRr'),
        twin('RRRRRRRRRRRRRr'),
        twin('RRRWWRRRRWWRRr'),
        twin('RRRWoRRRRoWRRr'),
        twin('RRRWoRRRRoWRRr'),
        twin('RRpRRRRRRRRpRr', 'RRpRRRRRRRRpRr', 'RR'),
        twin('RRRRRoRRoRRRrr', 'RRRRRooooRRRrr', 'rr'),
        twin('.RRRRRooRRRrr.', '.RRRRoeeoRRrr.'),
        twin('.RRRRRRRRRrrr.', '.RRRRRooRRrrr.'),
        twin('..RRRRRRRrrr..'),
        twin('...RRRRrrrr...'),
        twin('....RRrrrr....'),
        twin('...rrr..rrr...'),
        twin('...rrr..rrr...'),
        '................................',
        '................................',
      ],
    },
  ],
};

/** 左 7・駒 18・右 7 ドットで 1 行（リュウオウコマの からだの行） */
const koma = (left: string, body: string, right = '..N....'): string => left + body + right;

/** リュウオウコマ：ショウギコマンダーが 成った すがた。赤い うるしの しるし、竜の かぶと、やり（ツチ） */
const ryuoKoma: MonsterDesign = {
  size: 32,
  colors: {
    B: NQ.beige,
    P: NQ.paper,
    T: NQ.tan,
    N: NQ.brown,
    W: NQ.white,
    p: NQ.blush,
    R: NQ.red,
    r: NQ.brick,
    Y: NQ.gold,
    I: NQ.silver,
  },
  rim: { [NQ.beige]: NQ.sand },
  layers: [
    {
      rows: [
        '................................',
        '.......Y.Y............Y.Y..I....',
        '........YYY..........YYY..IWI...',
        '..........YY..RRRR..YY....IWI...',
        '...........YRRRRRRRRY......I....',
        '...........RRRRYYRRRR.....RNR...',
        '..........RRRRRYYRRRRr....RNR...',
        '.........YYYYYYYYYYYYYY....N....',
        '.......YYPBBBBBBBBBBBBBYY..N....',
        '......Y.PBBBBBBBBBBBBBBB.Y.N....',
        koma('.......', 'PBBoBBBBBBBBBBoBBB'),
        koma('..YYY..', 'PBBBooBBBBBBooBBBB'),
        koma('.YRRRY.', 'PBBBWWBBBBBBWWBBBB'),
        koma('.YRYRY.', 'PBBBWoBBBBBBoWBBBB'),
        koma('.YRRRY.', 'PBBBWoBBBBBBoWBBBB'),
        koma('..YYY..', 'PBBpBBBBBBBBBBpBBB'),
        koma('...N...', 'PBBBBBoBBBBoBBBBBB', 'BBNB...'),
        koma('...NBBB', 'PBBBBBBooooBBBBBBB', 'BBNB...'),
        koma('.......', 'PBBBBBBBBBBBBBBBBB'),
        koma('.......', 'PBBBBBBRRRRBBBBBBB'),
        koma('.......', 'PBBBBBRRYYRRBBBBBB'),
        koma('.......', 'PBBBBRRYRRYRRBBBBB'),
        koma('.......', 'PBBBBRRRYYRRRBBBBB'),
        koma('.......', 'PBBBBBrRRRRrBBBBBB'),
        koma('.......', 'PBBBBBBrrrrBBBBBBB'),
        koma('.......', 'PBBBBBBBBBBBBBBBBB'),
        koma('.......', 'PBBBBBBBBBBBBBBBBB'),
        koma('.......', 'PBBBBBBBBBBBBBBBBB'),
        '..........TTT......TTT..........',
        '..........NNN......NNN..........',
        '................................',
        '................................',
      ],
    },
  ],
};

/** ジャンボイモニ：イモニナベの しんか。あふれる 芋煮、ふたが とび、大きな おたまを かまえる（ヒノ） */
const jumboImoni: MonsterDesign = {
  size: 32,
  colors: {
    S: NQ.slate,
    K: NQ.night,
    g: NQ.gray,
    W: NQ.white,
    c: NQ.cloud,
    p: NQ.blush,
    b: NQ.brown,
    L: NQ.leaf,
    F: NQ.vermilion,
    Y: NQ.gold,
    e: NQ.berry,
  },
  layers: [
    {
      rows: [
        '................................',
        '..............Y.................',
        '.............FYF.....WW....Wgg..',
        '..........ggSSSSSKK.WWWc..WgggK.',
        '..WWc...gSSSSSSSSSSKKccc..gggKK.',
        '.WWWWWc....WcbLcWc.........gKK..',
        '..cccc...cWWcbbLcWWc.........g..',
        '.......LcWWWcbbLcWWWcL.......g..',
        '.....bcWWcLLcWWWcbbLcWWc.....g..',
        '....LcWWcbbLcWWWcLbcWWcbL....g..',
        '...bbcWcLLbcWWcbLLcWcbbLcb...g..',
        '...gggggggggggggggggggggKK...g..',
        '..SSSSSSSSSSSSSSSSSSSSSSSKK..g..',
        '.SSggSSSSSSSSSSSSSSSSSSSSSKK.g..',
        '.SSgSSSSoSSSSSSSSSSSoSSSSSKK.g..',
        '.SSgSSSSSooSSSSSSSooSSSSSSKK.g..',
        '.SSSSSSSSWWSSSSSSSWWSSSSSSKKSgK.',
        '.SSSSSSSSWoSSSSSSSoWSSSSSSKKSSK.',
        '.SSSSSSSSWoSSSSSSSoWSSSSSSKK.g..',
        '.SSSSSSSpSSSSSSSSSSSpSSSSSKK.g..',
        '.SSSSSSSSSSSoooooSSSSSSSSSKK....',
        '..SSSSSSSSSSoeeeoSSSSSSSKKK.....',
        '..SSSSSSSSSSSoooSSSSSSSSKKK.....',
        '..SSSSSSSSSSSSSSSSSSSSSKKKK.....',
        '...SSSSSSSSSSSSSSSSSSKKKKK......',
        '....SSSSSSSSSSSSSSSKKKKKK.......',
        '......SSSSSSSSSSSKKKKKK.........',
        '........SSSSSSSKKKKKK...........',
        '.......KKK..F.Y.F..KKK..........',
        '...........FYFYFYF..............',
        '..........FFYFFFYFF.............',
        '................................',
      ],
    },
  ],
};

/** ユケムリン：銀山温泉の 湯けむりの ようせい。木のおけに つかり、頭に 赤い 手ぬぐい（ミズ） */
const yukemurin: MonsterDesign = {
  size: 32,
  colors: {
    I: NQ.ice,
    S: NQ.sky,
    W: NQ.white,
    p: NQ.blush,
    R: NQ.red,
    r: NQ.brick,
    T: NQ.tan,
    B: NQ.brown,
    E: NQ.beige,
  },
  rim: { [NQ.ice]: NQ.sky, [NQ.tan]: NQ.brown },
  rimDepth: 2,
  layers: [
    // 湯けむりの からだ
    {
      mirror: true,
      y: 1,
      rows: [
        '..........WW....',
        '.........WWWWWWW',
        '.......WWWWWWWWW',
        '......RRRRRRRRRR',
        '......RWRRRWRRRR',
        '.....IIIIIIIIIII',
        '....IIIIIIIIIIII',
        '....IIIIIIIIIIII',
        '...IIIIIIIIIIIII',
        '...IIIIIIWWIIIII',
        '...IIIIIIWoIIIII',
        '...IIIIIIWoIIIII',
        '...IIIppIIIIIIII',
        '...IIIIIIIIIIoII',
        '...IIIIIIIIIIIIo',
        '...IIIIIIIIIIIII',
        '....IIIIIIIIIIII',
        '....IIIIIIIIIIII',
        '.....IIIIIIIIIII',
      ],
    },
    // 木の おけ（ひのきの たが）
    {
      mirror: true,
      y: 20,
      rows: [
        '...TTTTTTTTTTTTT',
        '...TETTTETTTETTT',
        '...BBBBBBBBBBBBB',
        '...TTTTTTTTTTTTT',
        '...TETTTETTTETTT',
        '...TTTTTTTTTTTTT',
        '...BBBBBBBBBBBBB',
        '....TTTTTTTTTTTT',
        '....TTTTTTTTTTTT',
        '.....BBBBBBBBBBB',
      ],
    },
    // 立ちのぼる 湯けむり
    { x: 3, y: 1, rows: ['.W.', 'W.W', '.W.'] },
    { x: 26, y: 3, rows: ['.W.', 'W.W', '.W.'] },
    { x: 1, y: 12, rows: ['S'] },
  ],
};

/** ユノハナリュウ：ユケムリンの しんか。湯けむりが 長い 竜に なった。金の ひげと 湯の花（ミズ） */
const yunohanaRyu: MonsterDesign = {
  size: 32,
  colors: {
    I: NQ.ice,
    S: NQ.sky,
    A: NQ.azure,
    W: NQ.white,
    p: NQ.blush,
    R: NQ.red,
    Y: NQ.gold,
    O: NQ.ochre,
    T: NQ.tan,
    B: NQ.brown,
  },
  rim: { [NQ.ice]: NQ.sky, [NQ.sky]: NQ.azure },
  rimDepth: 2,
  layers: [
    // うずまく 湯けむりの からだ（下から 上へ）
    {
      rows: [
        '................................',
        '..........IIIIIIIIII............',
        '........IIIIIIIIIIIIII..........',
        '.......IIIIIIIIIIIIIIII.........',
        '......IIIIIIIIIIIIIIIIII........',
        '......IIIIIIIIIIIIIIIIII........',
        '......IIIIIIIIIIIIIIIIII........',
        '.......IIIIIIIIIIIIIIIII........',
        '.........IIIIIIIIIIIIIII........',
        '..............IIIIIIIIII........',
        '...........IIIIIIIIIIII.........',
        '.........IIIIIIIIIII............',
        '........IIIIIIIII...............',
        '........IIIIIIII................',
        '.........IIIIIIIII..............',
        '...........IIIIIIIIII...........',
        '..............IIIIIIIIII........',
        '.................IIIIIIIII......',
        '..................IIIIIIIII.....',
        '.................IIIIIIIIII.....',
        '..............IIIIIIIIIIII......',
        '..........IIIIIIIIIIIII.........',
        '.......IIIIIIIIIIIII............',
        '.....IIIIIIIIIIII...............',
        '....IIIIIIIIII..................',
        '....IIIIIIIII...................',
        '.....IIIIIIIIII.................',
        '.......TTTTTTTTTTTTTTTTT........',
        '.......TBTTTTBTTTTBTTTTT........',
        '.......TTTTTTTTTTTTTTTTT........',
        '........BBBBBBBBBBBBBBB.........',
        '................................',
      ],
    },
    // 竜の 顔（上の うずの 中）
    { x: 9, y: 3, rows: ['SSSSSSSSSSSSSS'] },
    { x: 10, y: 5, rows: ['oo......oo'] },
    { x: 10, y: 6, rows: ['WW......WW'] },
    { x: 10, y: 7, rows: ['Wo......oW'] },
    { x: 8, y: 9, rows: ['pp'] },
    { x: 20, y: 9, rows: ['pp'] },
    { x: 13, y: 9, rows: ['oooo', '.oo.'] },
    // 金の ひげ
    { x: 4, y: 6, rows: ['..YY', '.YY.', 'YY..', 'O...'] },
    { x: 24, y: 6, rows: ['YY..', '.YY.', '..YY', '...O'] },
    // 湯の花（赤い つぶ）と あわ
    { x: 2, y: 14, rows: ['.R.', 'RAR', '.R.'] },
    { x: 27, y: 20, rows: ['.R.', 'RAR', '.R.'] },
    { x: 26, y: 12, rows: ['A'] },
  ],
};

export const YAMAGATA: Readonly<Record<string, MonsterDesign>> = {
  'yamagata-lastboss-matsuo-basho': LAST_BOSSES['yamagata-lastboss-matsuo-basho']!,
  'yamagata-yukemurin': yukemurin,
  'yamagata-yunohana-ryu': yunohanaRyu,
  'yamagata-sakuranboy': sakuranboy,
  'yamagata-shogi-commander': shogiCommander,
  'yamagata-imoni-nabe': imoniNabe,
  'yamagata-midboss-juhyon': juhyon,
  'yamagata-midboss-juhyon.field': juhyonField,
  'yamagata-boss-juhyo-no-kami': juhyoNoKami,
  'yamagata-boss-juhyo-no-kami.p0': juhyoNoKamiP0,
  'yamagata-double-cherry': doubleCherry,
  'yamagata-ryuo-koma': ryuoKoma,
  'yamagata-jumbo-imoni': jumboImoni,
};
