import { writeFileSync, mkdirSync } from "fs";
import { TOPICS } from "../src/data/topics";
import {
  PREFECTURE_CAPITAL_GROUPS,
  PREFECTURE_SHAPE_GROUPS,
  PREFECTURE_QUIZ_UNITS,
} from "../src/data/prefectureModes";
import { INDUSTRY_QUIZ_UNITS } from "../src/data/industryModes";
import { HISTORY_QUIZ_UNITS } from "../src/data/historyModes";
import { CIVICS_QUIZ_UNITS } from "../src/data/civicsModes";
import { getQuestionsByTopic } from "../src/data/questions/index";

mkdirSync("public/data/questions", { recursive: true });

const bankRows: Array<Record<string, unknown>> = [];
const bankQuestionIds = new Set<string>();

function exportUnit(unitId: string, options?: { includeInBank?: boolean }) {
  const includeInBank = options?.includeInBank ?? true;
  const questions = getQuestionsByTopic(unitId);
  writeFileSync(
    `public/data/questions/${unitId}.json`,
    JSON.stringify({ questions }, null, 2),
  );
  console.log(`public/data/questions/${unitId}.json: ${questions.length}`);

  if (!includeInBank) return;

  for (const q of questions) {
    if (bankQuestionIds.has(q.id)) continue;
    bankQuestionIds.add(q.id);

    bankRows.push({
      questionId: q.id,
      unitId: q.unit_id,
      type: q.type,
      difficulty: q.difficulty,
      question: q.question,
      answer: q.answer,
      explanation: q.explanation,
      curriculum_ref: q.curriculum_ref,
      tags: q.tags,
      hint: q.hint,
      srs_weight: q.srs_weight,
    });
  }
}

for (const topic of TOPICS) {
  // 都道府県・産業・歴史は分野別に export するため、集約トピックはバンクへ入れない
  exportUnit(topic.id, {
    includeInBank:
      topic.id !== "prefectures" &&
      topic.id !== "industry" &&
      topic.id !== "history" &&
      topic.id !== "civics",
  });
}

for (const unitId of PREFECTURE_QUIZ_UNITS) {
  exportUnit(unitId);
}

for (const unitId of INDUSTRY_QUIZ_UNITS) {
  exportUnit(unitId);
}

for (const unitId of HISTORY_QUIZ_UNITS) {
  exportUnit(unitId);
}

for (const unitId of CIVICS_QUIZ_UNITS) {
  exportUnit(unitId);
}

writeFileSync(
  "public/data/questions/prefectures-shape.json",
  JSON.stringify(
    {
      groups: PREFECTURE_SHAPE_GROUPS.map((g) => g.id),
      questions: getQuestionsByTopic("prefectures-shape"),
    },
    null,
    2,
  ),
);
console.log(
  `public/data/questions/prefectures-shape.json: ${getQuestionsByTopic("prefectures-shape").length} (combined)`,
);

writeFileSync(
  "public/data/questions/prefectures-capital.json",
  JSON.stringify(
    {
      groups: PREFECTURE_CAPITAL_GROUPS.map((g) => g.id),
      questions: getQuestionsByTopic("prefectures-capital"),
    },
    null,
    2,
  ),
);
console.log(
  `public/data/questions/prefectures-capital.json: ${getQuestionsByTopic("prefectures-capital").length} (combined)`,
);

const bankSource = `/** Auto-generated by scripts/export-questions.ts */\nexport const QUESTION_BANK = ${JSON.stringify(bankRows, null, 2)} as const;\n`;
writeFileSync("convex/questionBank.ts", bankSource);
console.log(`convex/questionBank.ts: ${bankRows.length} questions`);
console.log("Done.");
