/** 秋田のモンスター（docs/05 §2、docs/06 §6.3〜6.6） */
import { NQ } from '../palette';
import type { MonsterDesign } from './design';
import { LAST_BOSSES } from './lastbosses';

/** キリタンポン：杉の串に ついた、こんがり焼けた きりたんぽ。頭に 3 本の炎（ヒノ） */
const kiritanpon: MonsterDesign = {
  size: 32,
  colors: {
    E: NQ.beige,
    T: NQ.tan,
    B: NQ.brown,
    W: NQ.white,
    p: NQ.blush,
    C: NQ.cream,
    G: NQ.gold,
    A: NQ.apricot,
    V: NQ.vermilion,
  },
  rim: { [NQ.beige]: NQ.sand },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '...............C',
        '..............AG',
        '..............VG',
        '...........A.VAG',
        '..........VGVVAA',
        '..........VAAVVA',
        '...........EEEEE',
        '..........EEEEEE',
        '..........TTTBTT',
        '..........ETTTEE',
        '..........EEEEEE',
        '..........EEWWEE',
        '..........EEWoEE',
        '..........EEWoEE',
        '..........EpEEoE',
        '........EEEEEEEo',
        '.......EETTTBTTT',
        '..........TBTTTE',
        '..........EEEEEE',
        '..........TTBTTT',
        '..........ETTTBE',
        '..........EEEEEE',
        '..........TTTBTT',
        '...........TTTTT',
        '...............B',
        '...............B',
        '...............B',
        '...............B',
        '..............BB',
        '..............BB',
      ],
    },
  ],
};

/**
 * マゲワッパン：大館の 曲げわっぱの 兵隊。うすい 秋田杉を まげた だ円の はこ、まっすぐな 木目、
 * 桜の皮で たてに ぬった とじ目。ふたが 少し 大きく、ちょっと あけると 白い ごはんと 赤い うめぼし（モリ）
 */
const magewappan: MonsterDesign = {
  size: 32,
  colors: {
    S: NQ.sand,
    T: NQ.tan,
    E: NQ.beige,
    K: NQ.bark,
    B: NQ.brown,
    W: NQ.white,
    c: NQ.cloud,
    R: NQ.red,
    r: NQ.brick,
    p: NQ.blush,
  },
  rim: { [NQ.sand]: NQ.tan },
  layers: [
    {
      rows: [
        '................................',
        '................................',
        '........EEEEEEEEEEEEEEEE........',
        '....EEEESSSSSSEEEEEEEEEEEEEE....',
        '..EEEEEEEEEEEEEEESSSSSSSEEEEEE..',
        '..EESSSSSSEEEEEEEEEEEEEESSSSEE..',
        '..SEEEEEEEEEEEEEEEEEEEEEEEEEES..',
        '..SSSEEEEEEEEEEEEEEEEEEEEEESSS..',
        '..SSSESSSSESSSSSSSSSKKKKSSESSS..',
        '..SSSESSSSESSSSSSSSSKTTKSSESSS..',
        '..SSSESSSSESSSSSSSSSKKKKSSESSS..',
        '...BBBBBBBBBBBBBBBBBBBBBBBBBB...',
        '.....WWcWWWWWRRRWWWWWcWWWWW.....',
        '....WWWWcWWWRRRRrWWWWWWcWWWW....',
        '....EEEEEEEEEEEEEEEEKKKKEEEE....',
        '....SSESSSSSSSSSSSESKKKKSSST....',
        '....SSESSSSSSSSSSSESKTTKSEST....',
        '....SSESSWWSSSSWWSESKKKKSEST....',
        '..SSSSESSWoSSSSWoSSSKTTKSESTSS..',
        '.SSSSSESSWoSSSSWoSSSKKKKSESTSSS.',
        '.SS.SSESpSSoSSoSSpSSKTTKSEST.SS.',
        '....SSSSSSSSooSSSSSSKKKKSEST....',
        '....SSESSSSSSSSSSSESKTTKSEST....',
        '....SSESSSSSSESSSSESKKKKSEST....',
        '....SSESSSSSSESSSSESKTTKSEST....',
        '....SSESSSSSSESSSSSSKKKKSEST....',
        '.....SSSSSSSSSSSSSSSKTTKSSS.....',
        '.......TTTTTTSTTTTSTKKKKT.......',
        '.........TTT.......TTT..........',
        '.........BBB.......BBB..........',
      ],
    },
  ],
};

/** アキタイヌ：ふかふかの 秋田犬。白い ほお と むね、とがった耳、くるんと まいた しっぽ、金の わっか（ヒカリ） */
const akitainu: MonsterDesign = {
  size: 32,
  colors: {
    O: NQ.orange,
    P: NQ.paper,
    W: NQ.white,
    p: NQ.blush,
    G: NQ.gold,
    Q: NQ.ochre,
    C: NQ.cream,
  },
  rim: { [NQ.orange]: NQ.amber, [NQ.paper]: NQ.cloud },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '............GGGG',
        '...........G....',
        '............QQQQ',
        '.......O........',
        '.......OO.......',
        '.......OPO......',
        '......OOPPO.OOOO',
        '......OOPPOOOOOO',
        '......OOOOOOOOOO',
        '.....OOOOOOOOOOO',
        '.....OOOOOWWOOOO',
        '.....OOOOOWoOOOO',
        '.....OOOOOWoOOOO',
        '....POOOOOOOOPPP',
        '....PPOOpOOOPPPo',
        '....PPPOOOOPPPPo',
        '.....PPPPPPPPPoP',
        '.....PPPPPPPPPPo',
        '......PPPPPPPPPP',
        '.......OOOOPPPPP',
        '......OOOOOPPPPP',
        '......OOOOOPPPPP',
        '......OOOOOOPPPP',
        '......OOOOOOPPPP',
        '......OOOOOOOPPP',
        '......OOOOOOOOPP',
        '......OOOOPPPOOO',
        '......OOOPPPPOOO',
        '.......OOPPPPOOO',
      ],
    },
    // くるんと まいた しっぽ（右にだけ）
    { x: 25, y: 17, rows: ['.OOO', 'OPPPO', 'OPOPO', 'OOPPO', '.OOO'] },
    // おでこの つや
    { x: 9, y: 9, rows: ['CC'] },
  ],
};

/**
 * カントウマン（中ボス）：紺の はんてんに はちまき、ちょうちんが ずらりと 光る 竿燈を
 * 片手の ひらで ささえる 力もち。頭に 王冠（ヒカリ）
 */
const kantoManColors = {
  D: NQ.denim,
  N: NQ.navy,
  P: NQ.paper,
  K: NQ.skinMid,
  k: NQ.skinDark,
  G: NQ.gold,
  Q: NQ.ochre,
  R: NQ.red,
  C: NQ.cream,
  Y: NQ.yellow,
  S: NQ.sand,
  W: NQ.white,
  p: NQ.blush,
};

const kantoMan: MonsterDesign = {
  size: 40,
  colors: kantoManColors,
  rim: { [NQ.denim]: NQ.navy, [NQ.paper]: NQ.cloud },
  rimDepth: 2,
  layers: [
    // 竿燈：竹の さおに よこだけ 3 段、光る ちょうちんが ずらり
    {
      x: 26,
      y: 1,
      rows: [
        '......G......',
        'SSSSSSQSSSSSS',
        'CC.CC.S.CC.CC',
        'CC.CC.S.CC.CC',
        'CY.CY.S.CY.CY',
        '......S......',
        'SSSSSSQSSSSSS',
        'CC.CC.S.CC.CC',
        'CC.CC.S.CC.CC',
        'CY.CY.S.CY.CY',
        '......S......',
        'SSSSSSQSSSSSS',
        'CC.CC.S.CC.CC',
        'CC.CC.S.CC.CC',
        'CY.CY.S.CY.CY',
        '......S......',
        '......Q......',
        '......S......',
      ],
    },
    {
      mirror: true,
      rows: [
        '....................',
        '....................',
        '....................',
        '....................',
        '....................',
        '....................',
        '....................',
        '....................',
        '....................',
        '................G..G',
        '................GGGR',
        '................QQQQ',
        '...............NNNNN',
        '..............NNNNNN',
        '..............PPPPPP',
        '..............KKooKK',
        '..............KKWWoK',
        '..............KKWWoK',
        '..............KKWWoK',
        '..............KKWooK',
        '..............KpKKKK',
        '..............KKKoWW',
        '..............KKKKoo',
        '...............KKKKK',
        '............DDDPPKKK',
        '............DDDDPKKK',
        '............DDDDDPKK',
        '............DDDDDPKK',
        '............DDDDDDPK',
        '............DDDDDDDP',
        '............RRRRRRRR',
        '............RRRRRRRR',
        '............DPDPDPDD',
        '.............PPPPP..',
        '............PPPPP...',
        '............PPPPP...',
        '...........PPPPP....',
        '..........NNNNNN....',
        '..........NNNNNN....',
      ],
    },
    // 顔の右がわの かげ
    { x: 25, y: 15, rows: ['k', 'k', 'k', 'k', 'k', 'k', 'k', 'k'] },
    { x: 24, y: 23, rows: ['k'] },
    // はちまきの むすび目（左に なびく）
    { x: 10, y: 13, rows: ['PP..', '.PPP', 'P...'] },
    // 左うで：こしに 手を あてる
    {
      x: 7,
      y: 25,
      rows: ['.....DD', '....DDD', '...DDD.', '..DDD..', '.DDP...', 'KKKK...', '.KKKKK.', '...kKK.'],
    },
    // 右うで：手の ひらで 竿燈を ささえる
    {
      x: 26,
      y: 19,
      rows: ['.....KKK', '.....KKk', '....KKK.', '...KKk..', '..PPP...', '.DDD....', 'DDD.....'],
    },
  ],
};

/** カントウマン（フィールドに立つ 32×32）。12 色に へらす */
const kantoManField: MonsterDesign = {
  size: 32,
  colors: {
    D: NQ.denim,
    N: NQ.navy,
    P: NQ.paper,
    K: NQ.skinMid,
    G: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
    C: NQ.cream,
    Y: NQ.yellow,
    S: NQ.sand,
    W: NQ.white,
  },
  rim: { [NQ.denim]: NQ.navy },
  layers: [
    {
      x: 20,
      y: 1,
      rows: [
        '.....G.....',
        'SSSSSQSSSSS',
        'CC.CCSCC.CC',
        'CY.CYSCY.CY',
        '.....S.....',
        'SSSSSQSSSSS',
        'CC.CCSCC.CC',
        'CY.CYSCY.CY',
        '.....S.....',
        '.....S.....',
        '.....S.....',
      ],
    },
    {
      x: 5,
      y: 7,
      rows: [
        '.....G.GG.G.....',
        '.....GGRRGG.....',
        '.....QQQQQQ.....',
        '....NNNNNNNN....',
        '...PPPPPPPPPP...',
        '....KooKKooK....',
        '....KWoKKoWK....',
        '....KWoKKoWK....',
        '....KKoWWoKK....',
        '....KKKooKKK....',
        '.....KKKKKK.....',
        '...DDPKKKKPDD...',
        '..DDDDPKKPDDDD..',
        '..DDDDDPPDDDDD..',
        '..DDDDDDDDDDDD..',
        '..RRRRRRRRRRRR..',
        '..RRRRRRRRRRRR..',
        '..DPDPDPDPDPDD..',
        '...PPPP..PPPP...',
        '...PPPP..PPPP...',
        '..PPPP....PPPP..',
        '..PPPP....PPPP..',
        '.NNNNN....NNNNN.',
        '.NNNNN....NNNNN.',
      ],
    },
    { x: 5, y: 10, rows: ['PP.', '.PP', 'P..'] },
    { x: 3, y: 19, rows: ['...DD', '..DD.', '.DD..', 'KK...', '.KKK.'] },
    {
      x: 18,
      y: 12,
      rows: [
        '......KKK',
        '......KK.',
        '.....KK..',
        '....KK...',
        '...PP....',
        '..DDD....',
        '.DDD.....',
        'DDD......',
      ],
    },
  ],
};

/**
 * ナマハゲオウ（県ボス）：赤い 面に 金の 目、2 本の つの、白い たてがみ、すそが 広がる わらの ケデ、わらぐつ。
 * 片手で 手おけを 高く かかげ、もう片方の 手で「なまけものは いねがー！」と ゆびさす。王冠は つのの あいだ（ヒノ）
 */
const namahageOu: MonsterDesign = {
  size: 48,
  colors: {
    R: NQ.red,
    r: NQ.brick,
    J: NQ.red,
    A: NQ.apricot,
    G: NQ.gold,
    Q: NQ.ochre,
    P: NQ.paper,
    c: NQ.cloud,
    S: NQ.sand,
    T: NQ.tan,
    B: NQ.brown,
    W: NQ.white,
    E: NQ.beige,
  },
  rim: { [NQ.red]: NQ.brick, [NQ.paper]: NQ.cloud, [NQ.beige]: NQ.sand, [NQ.sand]: NQ.tan },
  rimDepth: 2,
  layers: [
    {
      mirror: true,
      rows: [
        '........................',
        '..............E.....G..G',
        '..............EE....GGGG',
        '...............EE...GGGJ',
        '...............EEEPPQQQQ',
        '..............PPEEPPPPPP',
        '.............P..EPPPPPPP',
        '............PP.PPPPPPPPP',
        '...........PPPPPPPPRRRRR',
        '............PPcPPPRRRRRR',
        '..........PPPcPPPooRRRRR',
        '............PPcPPRoooRRR',
        '...........PPcPPPGGGooRR',
        '..........PPPcPPPGWGoRRR',
        '............PPcPPGGooRrR',
        '...........PPcPPPRGGRrRR',
        '..........PPPcPPPRRRRrrr',
        '............PPcPPRoooooo',
        '...........PPcPPPoWWWWWW',
        '..........PPPcPPPoWooooo',
        '............PPcPPRoooooo',
        '............PPPcPPRRRRRR',
        '.........TSQSTPPPcPPPPPP',
        '........STSQSTSBPPcPPPPP',
        '........STSQSTSBSTPPPPPP',
        '.......BSTSQSTSBSTSQPPPP',
        '.......BBBBBBBBBBBBBBBBB',
        '.......BSTSQSTSBSTSQSTSB',
        '......SBSTSQSTSBSTSQSTSB',
        '......SBSTSQSTSBSTSQSTSB',
        '......SBSTSQSTSBSTSQSTSB',
        '.....TSBSTSQSTSBSTSQSTSB',
        '.....BBBBBBBBBBBBBBBBBBB',
        '.....TSBSTSQSTSBSTSQSTSB',
        '....STSBSTSQSTSBSTSQSTSB',
        '....STSBSTSQSTSBSTSQSTSB',
        '...QSTSBSTSQSTSBSTSQSTSB',
        '...QSTSBSTSQSTSBSTSQSTSB',
        '..SQSTSBSTSQSTSBSTSQSTSB',
        '..SQSTSBSTSQSTSBSTSQSTSB',
        '..S.T.S.Q.S.TTTTT.S.Q.S.',
        '...T...S....SSSSS..T....',
        '............BBBBB.......',
        '............SSSSS.......',
        '...........TSSSSS.......',
        '..........SSSSSSS.......',
        '..........BBBBBBB.......',
      ],
    },
    // おでこの つや
    { x: 19, y: 9, rows: ['AA'] },
    // たてがみと 手おけの すきまを うめる
    { x: 11, y: 6, rows: ['P'] },
    // 左うで：手おけを 高く かかげる
    {
      x: 1,
      y: 2,
      rows: [
        'TBTBTBTBTB',
        'GGGGGGGGGG',
        'TBTBTBTBTB',
        'TBTBTBTBTB',
        '.GGGGGGGG.',
        '.TBTBTBTB.',
        '.oooooooo.',
      ],
    },
    {
      x: 2,
      y: 9,
      rows: [
        '.RRRRRR....',
        '.RrRrRR....',
        '..RRRRr....',
        '..SSSSS....',
        '..RRRRr....',
        '..RRRRr....',
        '..RRRRr....',
        '..RRRRr....',
        '...RRRRr...',
        '....RRRRr..',
        '.....RRRRr.',
        '......RRRRr',
        '.......RRRR',
      ],
    },
    // 右うで：なまけものを ゆびさす
    {
      x: 34,
      y: 22,
      rows: [
        '.RRRR........',
        '..RRRR.......',
        '...RRRRRRR...',
        '....RRRRRRRRR',
        '....RRRRRrrrr',
        '....RRRRRoo..',
        '....RrRrRr...',
        '.....RRRRr...',
        '......rrr....',
      ],
    },
  ],
};

/** ナマハゲオウ 後半（いかり）：同じ ポーズ。顔が 明るく 燃え、たてがみが 逆立ち、りんかくに そって 炎が 立ちのぼる */
const namahageOuRage: MonsterDesign = {
  ...namahageOu,
  colors: { ...namahageOu.colors, R: NQ.vermilion, r: NQ.red, V: NQ.vermilion, C: NQ.cream },
  rim: { [NQ.vermilion]: NQ.brick, [NQ.paper]: NQ.cloud, [NQ.beige]: NQ.sand, [NQ.sand]: NQ.tan },
  layers: [
    // うしろの 炎（体の ふちから 少しだけ はみ出す）
    {
      mirror: true,
      y: 1,
      rows: [
        '............C..',
        '............G..',
        '...........AGA.',
        '...........AGA.',
        '..........VAGAV',
        '..........VVAVV',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '........C',
        '........G',
        '.......AGA',
        '.......AGA',
        '......VAGAV',
        '.....CVVAVV',
        '.....G',
        '....AGA',
        '....AGA',
        '...VAGAV',
        '...VVAVV',
        '...C',
        '...GA',
        '..AGA',
        '..AGA',
        '.VAGAV',
        '.VVAVV',
        '...C',
        '...GA',
        '..AGA',
        '..AGA',
        '.VAGAV',
        '.VVAVV',
      ],
    },
    ...namahageOu.layers,
    // 逆立った たてがみ
    {
      mirror: true,
      y: 2,
      rows: [
        '..................P',
        '..................PP',
        '...........P',
        '...........PP',
        '............PP',
        '',
        '',
        '..........PP',
        '',
        '',
        '.........PP',
        '',
        '',
        '.........PP',
      ],
    },
  ],
};

// ───────────────────────── しんか（なかまの 画面で どうぐを つかう） ─────────────────────────

/** キリタンポナベ（キリタンポンの しんか）：土なべの からだ、ふたの かぶと、やりの ような きりたんぽ、下に 炎（ヒノ） */
const kiritanpoNabe: MonsterDesign = {
  size: 32,
  colors: {
    E: NQ.beige,
    T: NQ.tan,
    S: NQ.sand,
    B: NQ.brown,
    K: NQ.bark,
    W: NQ.white,
    p: NQ.blush,
    C: NQ.cream,
    G: NQ.gold,
    A: NQ.apricot,
    V: NQ.vermilion,
  },
  rim: { [NQ.brown]: NQ.bark, [NQ.tan]: NQ.brown, [NQ.beige]: NQ.sand },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '.B..............',
        '.B............TT',
        '.EEE.........TTT',
        '.EEE......BBBBBB',
        '..TTT...BBBBBBBB',
        '..EEE..BBBBBBBBB',
        '...EEEBBBBBBBBBB',
        '...TTTBBBBBBBBBB',
        '....EEBBBBBBBBBB',
        '....EEEEEEEEEEEE',
        '...TTTTTTTTTTTTT',
        '.TTTTTTTTToTTTTT',
        '.TTTTTTTTTToTTTT',
        '..TTTTTTTTWWTTTT',
        '..TTTTTTTTWoTTTT',
        '..TTTTTTTTWoTTTT',
        '..TTTTTTTpTTTTTT',
        '..TTTTTTTTTTToTT',
        '..TTTTTTTTTTTToo',
        '..BBBBBBBBBBBBBB',
        '..BEBEBEBEBEBEBE',
        '..TTTTTTTTTTTTTT',
        '...TTTTTTTTTTTTT',
        '....TTTTTTTTTTTT',
        '.....TTTTTTTTTTT',
        '.......TTTTTTTTT',
        '........BBB...GC',
        '........BBB..AGC',
        '........BBB.VAGG',
        '.......BBBB.VVAA',
      ],
    },
    // ゆげ
    { x: 19, y: 1, rows: ['.WW.', 'WWWW', '.WW.'] },
    { x: 9, y: 1, rows: ['.W.', 'WWW'] },
    // つや（左上）
    { x: 8, y: 5, rows: ['.S', 'S.'] },
    { x: 3, y: 12, rows: ['E', 'E'] },
  ],
};

/** ワッパトリデ（マゲワッパンの しんか）：曲げわっぱを 3 だん かさねた 天守の とりで。どの だんにも 桜の皮の とじ目（モリ） */
const wappaToride: MonsterDesign = {
  size: 32,
  colors: {
    S: NQ.sand,
    T: NQ.tan,
    E: NQ.beige,
    K: NQ.bark,
    B: NQ.brown,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.sand]: NQ.tan },
  layers: [
    {
      rows: [
        '................................',
        '................................',
        '............EEEEEEEE............',
        '..........EEESSSEEEEEE..........',
        '.........SSESSESSKKKKSS.........',
        '.........SSESSESSKTTKSS.........',
        '..........BBBBBBBKKKKB..........',
        '..........SSESSESKKKKS..........',
        '..........SSESSESKTTKS..........',
        '........EEETTTTTTKKKKEEE........',
        '......EEESSSEEEESSSEEEEEEE......',
        '.....SSSESSSSESSSSSKKKKSESS.....',
        '.....SSSESSSSESSSSSKTTKSESS.....',
        '......BBBBBBBBBBBBBKKKKBBB......',
        '......SESWWSSSWWSESKKKKSES......',
        '......SESWoSSSWoSESKTTKSES......',
        '......SESWoSSSWoSESKKKKSES......',
        '......SEpSSoooSSpESKTTKSES......',
        '....EEETTTTTTTTTTTTKKKKTTEEE....',
        '..EEESSSEEEESSSEEEESSSEEEEEEEE..',
        '.SSESSSESSSESSSSESSSSKKKKSSESSS.',
        '.SSESSSESSSESSSSESSSSKTTKSSESSS.',
        '..BBBBBBBBBBBBBBBBBBBKKKKBBBBB..',
        '..SSESSSSESSSSESSSESSKKKKSSESS..',
        '..SSESSSSESSSSESSSESSKTTKSSESS..',
        '..SSESSSSESSSSSSSSESSKKKKSSESS..',
        '..SSSSSSSESSSSSSSSESSKTTKSSESS..',
        '..SSSSSSSESSSSESSSSSSKKKKSSSSS..',
        '...TTTTTTTTTTTTTTTTTTKKKKTTTT...',
        '......BBBB............BBBB......',
      ],
    },
  ],
};

/** チュウケンマル（アキタイヌの しんか）：赤い スカーフの 勇者の 秋田犬。ふかふかの むね、金の わっか（ヒカリ） */
const chukenMaru: MonsterDesign = {
  size: 32,
  colors: {
    O: NQ.orange,
    P: NQ.paper,
    W: NQ.white,
    p: NQ.blush,
    G: NQ.gold,
    Q: NQ.ochre,
    C: NQ.cream,
    R: NQ.red,
    r: NQ.brick,
  },
  rim: { [NQ.orange]: NQ.amber, [NQ.paper]: NQ.cloud, [NQ.red]: NQ.brick },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '..........GGGGGG',
        '.........G......',
        '..........QQQQQQ',
        '......O.........',
        '......OO........',
        '......OPO.......',
        '.....OOPPO..OOOO',
        '.....OOPPPOOOOOO',
        '.....OOOOoOOOOOO',
        '....OOOOOOooOOOO',
        '....OOOOOOWWOOOO',
        '....OOOOOOWoOOOO',
        '...POOOOOOWoOOOO',
        '...PPOOOpOOOPPPo',
        '...PPPOOOOOPPPPo',
        '....PPPOOOOPPooP',
        '....PPPPPPPPPPPP',
        '.....RRRRRRRRRRR',
        '.....rRRRRRRRRRG',
        '....OOOPPPPPPPPQ',
        '....OOOPPPPPPPPP',
        '...OOOOPPPPPPPPP',
        '...OOOOOPPPPPPPP',
        '...OOOOOOOOPPPPP',
        '...OOOOOOOOOPPPP',
        '...OOOOoOOOOPPPP',
        '...OOOOoOOOOPPPP',
        '...OOOOoOOOO....',
        '...PPPPoPPPP....',
        '...PPPP.PPPP....',
      ],
    },
    // くるんと まいた しっぽ（右にだけ）
    { x: 26, y: 19, rows: ['.OOO.', 'OPPPO', 'OPOPO', 'OOPPO', '.OOO.'] },
    // スカーフの はし（左にたなびく）
    { x: 1, y: 19, rows: ['..RRRr', '.RRRr.', 'RRRr..', 'RRr...', '.r....'] },
    // わっかと おでこの つや
    { x: 10, y: 1, rows: ['C'] },
    { x: 9, y: 8, rows: ['CC'] },
  ],
};

/** ハナビィ：大曲の 打ち上げ花火の 玉に 手足が 生えた 子。頭の どう火線が ぱちぱち 光る（カゼ） */
const hanabii: MonsterDesign = {
  size: 32,
  colors: {
    P: NQ.paper,
    S: NQ.sky,
    W: NQ.white,
    p: NQ.blush,
    B: NQ.bark,
    G: NQ.gold,
    Y: NQ.cream,
    V: NQ.vermilion,
    A: NQ.apricot,
  },
  rim: { [NQ.paper]: NQ.cloud },
  rimDepth: 2,
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '..........Y.....',
        '.........YGY....',
        '..........Y.....',
        '...........B....',
        '............B...',
        '.........PPPPPPP',
        '.......PPPPPPPPP',
        '......PPPPPPPPPP',
        '.....PPPPPPPPPPP',
        '....PPPPPPPPPPPP',
        '....PPPPPPPPPPPP',
        '...PPPPPPPPPPPPP',
        '...PPPPPPPPPPPPP',
        '...PPPPPPWWPPPPP',
        '...PPPPPPWoPPPPP',
        '...PPPPPPWoPPPPP',
        '...PppPPPPPPPPPP',
        '...PPPPPPPPPPoPP',
        '...PPPPPPPPPPPPo',
        '...PPPPPPPPPPPPP',
        '....PPPPPPPPPPPP',
        '....PPPPPPPPPPPP',
        '.....PPPPPPPPPPP',
        '......PPPPPPPPPP',
        '.......PPPPPPPPP',
        '.........PPPPPPP',
        '...........PP...',
        '...........BB...',
        '...........BB...',
      ],
    },
    // 玉の すじ（花火玉の つなぎめ）と つや
    { mirror: true, x: 4, y: 18, rows: ['SSSSSSSSSSSS'] },
    { x: 8, y: 11, rows: ['.W', 'W.'] },
    // まわりに ちる 火花
    { x: 1, y: 4, rows: ['.V.', 'VGV', '.V.'] },
    { x: 27, y: 8, rows: ['.A.', 'AGA', '.A.'] },
    { x: 2, y: 25, rows: ['.A.', 'AYA', '.A.'] },
  ],
};

/** オオダマハナビ：ハナビィの しんか。夜空いっぱいに ひらいた 大玉の 花火（カゼ） */
const oodamaHanabi: MonsterDesign = {
  size: 32,
  colors: {
    P: NQ.paper,
    S: NQ.sky,
    W: NQ.white,
    p: NQ.blush,
    B: NQ.bark,
    G: NQ.gold,
    Y: NQ.cream,
    V: NQ.vermilion,
    A: NQ.apricot,
    Z: NQ.azure,
  },
  rim: { [NQ.paper]: NQ.cloud },
  rimDepth: 2,
  layers: [
    // うしろに ひらく 大玉の 光（8 方向）
    {
      mirror: true,
      rows: [
        '................',
        '..A........A....',
        '...G......G.....',
        '....Y....Y......',
        '................',
        '.V....Y..Y......',
        '.A.....GG.......',
        '..G.............',
        '...Y............',
        '................',
        '................',
        '.VAGY...........',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
        '.VAGY...........',
        '................',
        '................',
        '................',
        '...Y............',
        '..G.............',
        '.A.....GG.......',
        '.V....Y..Y......',
        '................',
        '....Y....Y......',
        '...G......G.....',
        '..A........A....',
      ],
    },
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '..........Y.....',
        '.........YGY....',
        '..........Y.....',
        '...........B....',
        '..........ZB....',
        '........ZPPPPPPP',
        '......ZPPPPPPPPP',
        '.....ZPPPPPPPPPP',
        '....ZPPPPPPPPPPP',
        '...ZPPPPPPPPPPPP',
        '...ZPPPPPPPPPPPP',
        '..ZPPPPPoooPPPPP',
        '..ZPPPPPPPoooPPP',
        '..ZPPPPPPWWPPPPP',
        '..ZPPPPPPWoPPPPP',
        '..ZPPPPPPWoPPPPP',
        '..ZPppPPPPPPPPPP',
        '..ZPPPPPPPPPPoPP',
        '..ZPPPPPPPPPPPPo',
        '..ZPPPPPPPPPPPPP',
        '...ZPPPPPPPPPPPP',
        '...ZPPPPPPPPPPPP',
        '....ZPPPPPPPPPPP',
        '.....ZPPPPPPPPPP',
        '......ZPPPPPPPPP',
        '........ZPPPPPPP',
        '...........PP...',
        '...........BB...',
        '...........BB...',
      ],
    },
    // 玉の すじと つや
    { mirror: true, x: 4, y: 18, rows: ['SSSSSSSSSSSS'] },
    { x: 8, y: 11, rows: ['.W', 'W.'] },
  ],
};

export const AKITA: Readonly<Record<string, MonsterDesign>> = {
  'akita-lastboss-satake-yoshinobu': LAST_BOSSES['akita-lastboss-satake-yoshinobu']!,
  'akita-hanabii': hanabii,
  'akita-oodama-hanabi': oodamaHanabi,
  'akita-boss-namahage-ou': namahageOu,
  'akita-boss-namahage-ou.p0': namahageOuRage,
  'akita-midboss-kanto-man': kantoMan,
  'akita-midboss-kanto-man.field': kantoManField,
  'akita-kiritanpon': kiritanpon,
  'akita-magewappan': magewappan,
  'akita-akitainu': akitainu,
  'akita-kiritanpo-nabe': kiritanpoNabe,
  'akita-wappa-toride': wappaToride,
  'akita-chuken-maru': chukenMaru,
};
