/** 青森のモンスター（docs/05 §1.2、docs/06 §6.3〜6.5） */
import { NQ } from '../palette';
import type { MonsterDesign } from './design';
import { LAST_BOSSES } from './lastbosses';

/** リンゴロン：りんごのスライム。ヘタと葉っぱ、ちょこんとした足（モリ） */
const ringoron: MonsterDesign = {
  size: 32,
  colors: {
    R: NQ.red,
    r: NQ.brick,
    A: NQ.apricot,
    W: NQ.white,
    p: NQ.blush,
    B: NQ.bark,
    G: NQ.leaf,
    g: NQ.green,
    L: NQ.lime,
  },
  rim: { [NQ.red]: NQ.brick },
  rimDepth: 2,
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '................',
        '...............B',
        '...............B',
        '...............B',
        '........RRRR...B',
        '......RRRRRRR..B',
        '.....RRRRRRRRR.B',
        '....RRRRRRRRRRRR',
        '...RRRRRRRRRRRRR',
        '...RRRRRRRRRRRRR',
        '..RRRRRRRRRRRRRR',
        '..RRRRRRRRRRRRRR',
        '..RRRRRRRRRRRRRR',
        '..RRRRRRRWWRRRRR',
        '..RRRRRRRWoRRRRR',
        '..RRRRRRRWoRRRRR',
        '..RRRRRRpRRRRRRR',
        '..RRRRRRRRRRRRoR',
        '..RRRRRRRRRRRRRo',
        '..RRRRRRRRRRRRRR',
        '..RRRRRRRRRRRRRR',
        '..RRRRRRRRRRRRRR',
        '...RRRRRRRRRRRRR',
        '...RRRRRRRRRRRRR',
        '....RRRRRRRRRRRR',
        '.....RRRRRRRRRRR',
        '......RRRRRRRRRR',
        '........RRRRRRRR',
        '.........rrr....',
      ],
    },
    // 葉っぱ（右にだけ）
    { x: 17, y: 1, rows: ['....ggg', '..GGGGg', '.GLLGg.', 'GGGg...'] },
    // つや（左上）
    { x: 6, y: 10, rows: ['.A', 'AW', 'A.'] },
  ],
};

/** ネブタン：扇ねぷたの灯りをせおった小さな武者。頭に 3 本の炎（ヒノ） */
const nebutan: MonsterDesign = {
  size: 32,
  colors: {
    C: NQ.cream,
    G: NQ.gold,
    A: NQ.apricot,
    V: NQ.vermilion,
    b: NQ.brick,
    B: NQ.blue,
    P: NQ.paper,
    Z: NQ.azure,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.vermilion]: NQ.brick, [NQ.paper]: NQ.cloud },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '...............C',
        '..............GC',
        '...........C..GC',
        '..........GC.AGG',
        '..........AG.AAG',
        '.........BBBBBBB',
        '.....VVVBZZBBBBB',
        '...VVPPoBBBBBBBB',
        '..VPPPZGGGGGGGGG',
        '.VPPPZPoVVVVVVVV',
        '.VPPZPCoVVVWWVVV',
        '.VPZPCCoVVVWoVVV',
        '.VPZPCCoVVVWoVVV',
        '.VPZPCCoVVpVVVVV',
        '.VPZPCCoVVVVVVoV',
        '.VPZPCCoVVVVVVVo',
        '.VPPZPCobbGGGGGG',
        '..VPZPobbbVAAAAA',
        '..VPPZobbVVAAAAA',
        '...VPPobVVVAAAAA',
        '....VPobVVVAAAAA',
        '.....VoAAVVAAAAA',
        '......oAobbbbbbG',
        '.........VVVVVVV',
        '.........VVVVVVV',
        '.........VVVVVVV',
        '..........VVV...',
        '..........VVV...',
        '.........bbbb...',
        '.........bbbb...',
      ],
    },
  ],
};

/** マグロード：二本足で立つクロマグロの剣士。頭と両わきに小さなひれ（ミズ） */
const magurodo: MonsterDesign = {
  size: 32,
  colors: {
    N: NQ.navy,
    B: NQ.blue,
    Z: NQ.azure,
    S: NQ.sky,
    I: NQ.ice,
    L: NQ.silver,
    W: NQ.white,
    p: NQ.blush,
    G: NQ.gold,
  },
  rim: { [NQ.azure]: NQ.blue, [NQ.ice]: NQ.sky },
  layers: [
    // 三日月の尾びれ（うしろ）
    {
      mirror: true,
      y: 19,
      rows: [
        '..S.............',
        '..SN............',
        '..SBN...........',
        '..SBBN..........',
        '...SBBN.........',
        '...SBBBN........',
        '....SBBBNNNNNNNN',
        '.....SSBBBBBBBBB',
        '.......SSSSSSSSS',
      ],
    },
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '...............S',
        '..............SZ',
        '..............SZ',
        '.............NNZ',
        '...........NNNNN',
        '..........NNNNNN',
        '.........NNNZZZZ',
        '........NNZZZZZZ',
        '........NZZZZZZZ',
        '.......NNZWWZZZZ',
        '.......NZZWoZZZZ',
        '.......NZZWoZZZZ',
        '.......NZpZZZoZZ',
        '.......NZZZZZZoo',
        '.....SSNZZZZZZII',
        '....SSSNZZZZZIII',
        '.....SSNZZZZIIII',
        '.......NGZZZIIII',
        '.......NZZZZIIII',
        '.......NGZZZIIII',
        '........NGZZZIII',
        '........NZZZZZII',
        '.........NZZZZZZ',
        '..........NNNNNN',
        '...........NN...',
        '...........NN...',
        '...........NN...',
        '..........NNNN..',
        '..........NNNN..',
      ],
    },
    // 小さな刀（右手でかかげる）
    {
      x: 27,
      y: 4,
      rows: ['.W', '.WL', '.WL', '.WL', '.WL', '.WL', '.WL', '.WL', '.WL', '.WL', 'GGGG', '.NN', '.NN'],
    },
  ],
};

/** ドグウくん：遮光器土偶のゴーレム。コーヒー豆のような大きなゴーグルの目、縄の もよう（ツチ） */
const doguukun: MonsterDesign = {
  size: 32,
  colors: {
    T: NQ.tan,
    S: NQ.sand,
    B: NQ.brown,
    E: NQ.beige,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.tan]: NQ.brown },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '.........TT...TT',
        '........TTTTTTTT',
        '......TTTTTTTTTT',
        '....TTTTTTTTTTTT',
        '...TTToooooTTTTT',
        '...TToEWEEEoTTTT',
        '...ToEEEEEEEoTTT',
        '...ToooooooooTTT',
        '...TToEEEEEoTTTT',
        '...TTToooooTTTTT',
        '...TTpTTTTTTTTTT',
        '....TTTTTTTTTTTo',
        '.....TTTTTTTTTTo',
        '.......TTTTTTTTT',
        '...TTTTTTTTTTTTT',
        '..TTTTTTBTBTBTBT',
        '..TTTTTTTBTBTBTB',
        '.......TTTTTTTTT',
        '.......TBTBTBTBT',
        '.......TTBTBTBTB',
        '......TTTTTTTTTT',
        '.....TTTTTTTTTTT',
        '.....TTTTTTTTT..',
        '.....TTTTTTTTT..',
        '.....TTTTTTTTT..',
        '.....TTTTTTTTT..',
        '......TTTTTTT...',
        '.....BBBBBBBBB..',
        '.....BBBBBBBBB..',
      ],
    },
    // ひび（右の頭と左の足）
    { x: 24, y: 4, rows: ['B.', '.B', 'B.'] },
    { x: 7, y: 25, rows: ['B.', '.B', 'B.'] },
    // つや（左上）
    { x: 5, y: 5, rows: ['SS', 'S.'] },
  ],
};

/**
 * イタコドリ：恐山の かざぐるま（風車）の そばに いる 小さな 鳥（ヤミ）。
 * 頭に 大きな 4 色の かざぐるまを さして、右の はねでも 小さな かざぐるまを もつ。まるい からだ、金の 目
 */
const itakodori: MonsterDesign = {
  size: 32,
  colors: {
    I: NQ.indigo,
    V: NQ.violet,
    L: NQ.lavender,
    G: NQ.gold,
    Q: NQ.ochre,
    p: NQ.blush,
    R: NQ.red,
    Z: NQ.azure,
    E: NQ.leaf,
    W: NQ.white,
    K: NQ.brown,
  },
  rim: { [NQ.violet]: NQ.indigo },
  layers: [
    {
      mirror: true,
      y: 12,
      rows: [
        '.....I..........',
        '.....II.........',
        '.....IVI....VVVV',
        '.....IVVVVVVVVVV',
        '....VVVLLLLLLVVV',
        '....VVLLLGGLLLVV',
        '....VVLLGWoGLLVV',
        '....VVLLGooGLLVQ',
        '....VVLLLGGLLLVQ',
        '....VVpLLLLLLVVV',
        '...IVVVVVVVVVVVV',
        '...IIVVVVLLLLLLL',
        '...IIVVVLLLLVLLL',
        '...IIVVVLLLLLVLL',
        '...IIVVVLLLLLLVL',
        '....IVVVVLLLLLLV',
        '.....IVVVVVVVVVV',
        '........QQQQ....',
        '........Q..Q....',
      ],
    },
    // 頭の 大きな かざぐるま（赤・金・青・みどりの 4 まい）
    {
      x: 10,
      y: 1,
      rows: [
        'RRRRRR....G',
        '.RRRRR...GG',
        '..RRRR..GGG',
        '...RRR.GGGG',
        '....RRGGGGG',
        'EEEEEWGGGGG',
        'EEEEEZZ....',
        'EEEE.ZZZ...',
        'EEE..ZZZZ..',
        'EE...ZZZZZ.',
        'E....ZZZZZZ',
      ],
    },
    { x: 15, y: 12, rows: ['K', 'K'] },
    // 右の はねで もつ 小さな かざぐるま
    { x: 25, y: 20, rows: ['RRR.G', '.RRGG', 'EEWGG', 'EEZZ.', 'E.ZZZ', '..K..', '..K..', '..K..'] },
  ],
};

/** ネブタイショウ（中ボス）：ねぶたの山車からとびだした大きな武者。炎のオーラ、金のくわがた、かかげた大刀（ヒノ） */
const nebutaTaishoColors = {
  C: NQ.cream,
  A: NQ.apricot,
  V: NQ.vermilion,
  R: NQ.red,
  b: NQ.brick,
  G: NQ.gold,
  Q: NQ.ochre,
  B: NQ.blue,
  Z: NQ.azure,
  P: NQ.paper,
  c: NQ.cloud,
  W: NQ.white,
};
const nebutaTaisho: MonsterDesign = {
  size: 40,
  colors: nebutaTaishoColors,
  rim: { [NQ.vermilion]: NQ.brick, [NQ.paper]: NQ.cloud, [NQ.azure]: NQ.blue, [NQ.gold]: NQ.ochre },
  layers: [
    {
      mirror: true,
      rows: [
        '....................',
        '..........GGG.......',
        '...........GGG......',
        '...........oGG......',
        '...........VoGG.....',
        '.....V...C.VVoGGoBoG',
        '.....VVV....VVooZoGR',
        '......VAoGBBooBBBoGR',
        '......VAoGBBoBBBBBoG',
        '.......oGGBoGoooooGo',
        '.......VoGBooooooooo',
        '........oooCCRRPPPPP',
        '.VVVVVVVAGCCRoooPPPP',
        '..VAAAAAGCCCCRRoooPP',
        '...VAGGGCCCCCoRWWWoP',
        '....VAGCCCCCCoPWWoPP',
        '....VAGCCCCCCoPWWoPP',
        '.....VAGCCCCCCoWooPc',
        '.....VAGCCCCCCoPPPPP',
        '....VAooooooooGooooo',
        '...VAoGGGGGGGoGGoWRR',
        '..VooZZZZZZZZoPPPooo',
        '.VAoZRZRZRZRZRPPPPAR',
        '..VoZZZZZZZZZoPPPPRG',
        '...ZZZZZZZZZZoZZZZZZ',
        '...BBBRBRBRoRoZRZRZR',
        '...BooooooCCCCoZZZZZ',
        '....VAGGCCCCCCoZZZZZ',
        '....VAAAGCCCCCoooooR',
        '...VAVVVAGCCCoVVVVVV',
        '...VV...VAGGGoVVbVVV',
        '.........VAAbVVVbVVV',
        '.........VVobVVVbVVV',
        '..........oVbVVVbVVV',
        '.........VVVVVVVVVVV',
        '........GGGGGGGGGGGG',
        '.........oooooo.....',
        '.........ZZBBBB.....',
        '.........bbbbbb.....',
        '....................',
      ],
    },
    // 見得を切る左うでと、大刀をかかげる右うで
    {
      x: 1,
      y: 1,
      rows: [
        '....................................WW',
        '...................................WWW',
        '..................................WWWc',
        '..................................WWW.',
        '.................................WWWc.',
        '................................oWWc..',
        '................................oWW...',
        '.............................oGoGoo...',
        '.............................oG.GGG...',
        '...............................Po.....',
        '..............................PPP.....',
        '.............................oPPPo....',
        '.............................oooo.....',
        '............................oZZZo.....',
        '............................oZZo......',
        '............................oZZo......',
        '...........................oZZZo......',
        '...........................oZZo.......',
        '...........................ZZZZ.......',
        '..........................ZZZZo.......',
        '.............................o........',
        '.........................o.Zo.........',
        '........................oZ..o.........',
        'Poo.oooooooo...............o..........',
        'PPPo.BoVVVVV..............o...........',
        'PPP.B.VVVVVo..........................',
        'PPPoBoVVVVoo..........................',
        '....oooooo............................',
      ],
    },
  ],
};

/** ネブタイショウ（フィールドに立つ 32×32） */
const nebutaTaishoField: MonsterDesign = {
  size: 32,
  colors: nebutaTaishoColors,
  rim: { [NQ.vermilion]: NQ.brick, [NQ.paper]: NQ.cloud },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '........GGG.....',
        '.........oG.....',
        '.........VoG....',
        '....V....VoGGoGG',
        '....VVV..VAooZoR',
        '.....VoGBooBBBoG',
        '.....VoGBBooooBo',
        '......oooooooooo',
        '......VAGGGoPPPP',
        '.VVVVVAGGGRooPPP',
        '..VAAAGGGGoRoooP',
        '...VAGGGGGoRWWPP',
        '....VAGGGGGoWoPP',
        '....VAGGGGGoWoPP',
        '...VAooooooGoooo',
        '..VAoGGGGGGoGGoo',
        '.VooZZZZZZZoPPoR',
        '..ZZZZZZZZoPPPPP',
        '..ZZZZZZZZZoPPPR',
        '...BBooooooZZZRA',
        '...ooGGGGGGoZZZZ',
        '...VAAAGGGGGoooR',
        '...VVVVAGGGGoooo',
        '..VV...VAAooVVVV',
        '.......VVoVVVVVV',
        '........oVVVVVVV',
        '.......VVVVVVVVV',
        '........oooo....',
        '........ZBBB....',
        '........ZBBB....',
        '................',
      ],
    },
    {
      x: 1,
      y: 1,
      rows: [
        '............................WW',
        '...........................WWW',
        '...........................WWW',
        '..........................WWW.',
        '.........................oWW..',
        '.........................WWW..',
        '.......................oGooo..',
        '.........................P....',
        '.......................oPPo...',
        '.......................ooo....',
        '......................oZZo....',
        '......................oZZo....',
        '......................oZo.....',
        '.....................oZZo.....',
        '.....................ZZZ......',
        '....................ZZZo......',
        '.......................o......',
        '...................oZ.o.......',
        'Po..ooooo.............o.......',
        'PPoo.VVVV.....................',
        'PP.BoVVVo.....................',
        'PPooooooo.....................',
      ],
    },
  ],
};

/** ツガルのぬし（県ボス）：十和田湖と津軽海峡をまもる大きな水の竜。りんごの王冠、とげのひれ、縄文の縄もようのとぐろ（ミズ） */
const tsugaruNoNushi: MonsterDesign = {
  size: 48,
  colors: {
    W: NQ.white,
    I: NQ.ice,
    S: NQ.sky,
    Z: NQ.azure,
    B: NQ.blue,
    N: NQ.navy,
    T: NQ.teal,
    A: NQ.aqua,
    G: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
    r: NQ.brick,
    L: NQ.leaf,
  },
  rim: { [NQ.blue]: NQ.navy, [NQ.azure]: NQ.blue },
  rimDepth: 2,
  layers: [
    {
      mirror: true,
      rows: [
        '........................',
        '...........III.........G',
        '............II...L.G.G.G',
        '.......NS...III.RR.GGGGG',
        '........NSS..IIIrR.GGGGR',
        '.........NZS..II.ZZQQQQQ',
        '.........NNZSS.oZZZZZZBB',
        '.SSSSSSSSZNNZZNNZZZZZZBB',
        '..NNNZZZZZZNZZoNNZZZZZBB',
        '.....NNNZZZZNoBBBNNNBBBB',
        '......SZNNNZZoBBBWIINBBB',
        '.......SZZZNNoBBBIIoNBBB',
        '......SZZZZZZoBBBIIoBBBB',
        '....SSZZZZZZZZoBBIooBBBB',
        '...SSSNNNNNNNNoBBBBBBBZZ',
        '...NNN..SZZZZZSoBBBBBBBZ',
        '........SZZZNNS.BBBBBoBB',
        '.......SZNNNSSS.BBBBBBBB',
        '......SNN.......BBBBBBBB',
        '.....NN.........oBBBBBBB',
        '.................ooooooo',
        '.................oWooooo',
        '..................SSSSSS',
        '..................oooooo',
        '..................NBBZZZ',
        '..................BBNSSS',
        '..................BNBZZZ',
        '..................NBBSSS',
        '.................NBBNZZZ',
        '.................BBNBSSS',
        '........BBBZZZZZoBNBBZZZ',
        '........TBBBBBBBZooooooo',
        '........AATTABBBBBBBBBBB',
        '.........oBBATTAATTABBBB',
        '.....ZZZZZoooBBBBTAATTAA',
        '....BBBBBZZZZooooooooBBB',
        '....AABBBBBBBBBBBBZZZooo',
        '....ATTAATTBBBBBBBBBBBBB',
        '.....ooBBTAATTAATTAATTAA',
        '...ZZZZooooBBBBBBAATTAAT',
        '..BBBBBBBZZoooooooooBBBB',
        '.TTABBBBBBBBBBBBBBBZoooo',
        '..AATTAATTBBBBBBBBBBBBBB',
        '...BBBBTTAATTAATTAATTAAT',
        '.....NNBBBBBBBBTAATTAATT',
        '........NNNNNNNBBBBBBBBB',
        '................NNNNNNNN',
        '........................',
      ],
    },
    // しっぽの先（右から立ち上がる）
    {
      x: 40,
      y: 21,
      rows: [
        '.S.....',
        '.SoZ...',
        'SSoZB..',
        '.SoZB..',
        '...ZBB.',
        '...ZBB.',
        '....BB.',
        '....BBB',
        '....BBB',
        '....BBB',
        '....BBB',
        '...ZBBB',
        '...ZBB.',
        '..oNNN.',
        '..oNN..',
        '..oNN..',
        '.oNN...',
        '...o...',
      ],
    },
  ],
};

/** ツガルのぬし 第 2 形態：海峡の風をまとう（カゼ）。うろこが青緑に、縄もようが風のすじに、まわりに白い風のうず */
const tsugaruNoNushiP0: MonsterDesign = {
  ...tsugaruNoNushi,
  colors: { ...tsugaruNoNushi.colors, B: NQ.teal, Z: NQ.aqua, S: NQ.mint, T: NQ.mint, A: NQ.white },
  rim: { [NQ.teal]: NQ.navy, [NQ.aqua]: NQ.teal },
  layers: [
    ...tsugaruNoNushi.layers,
    {
      x: 1,
      y: 2,
      rows: [
        '..........................................W...',
        '........................................oWWW..',
        '........................................W.....',
        '........................................W....W',
        '.........................................oWWo.',
        '..........................................oo..',
        '..............................................',
        '..............................................',
        '..............................................',
        '..............................................',
        '..............................................',
        '..............................................',
        '..............................................',
        '..............................................',
        '..............................................',
        '..............................................',
        '..............................................',
        '..............................................',
        '..............................................',
        '..............................................',
        '..............................................',
        '..WWW.........................................',
        '..W..W........................................',
        '.....W........................................',
        'W....W........................................',
        'WWWWW.........................................',
        '..WW..........................................',
        '..............................................',
        '..............................................',
        '..WW..........................................',
        '..WWW.........................................',
        'W...W.........................................',
        'WW.Wo.........................................',
        '.WWo..........................................',
      ],
    },
  ],
};

/**
 * ネブタムシャ：ネブタンが「ねぶたの お守り」で しんかした すがた（ヒノ）。ネブタンより 大きく、よろいを きた ねぶた武者。
 * 金の くわがたの かぶと、ねぶた絵（赤・青・白に 黒の すじ）の 大そでと むねあて、せなかで 光る 扇ねぷたの 灯り、こしに 刀
 */
const nebutaMusha: MonsterDesign = {
  size: 32,
  colors: {
    C: NQ.cream,
    G: NQ.gold,
    V: NQ.vermilion,
    b: NQ.brick,
    R: NQ.red,
    B: NQ.blue,
    Z: NQ.azure,
    P: NQ.paper,
    W: NQ.white,
  },
  rim: { [NQ.vermilion]: NQ.brick, [NQ.paper]: NQ.cloud },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '...G............',
        '...GG.........GG',
        '....GG.......GCC',
        '.....GG......GCC',
        '...VVVGGG.....GG',
        '..VPPZoGGGGBBBBB',
        '.VPPZCoBBBBBBBBB',
        '.VPZCCoBBZZBBBBB',
        '.VPZCCoBZZBBBBBB',
        '.VPZCCoGGGGGGGGG',
        '.VPZCCoVVVVVVVVV',
        '.VPPZCoVVooVVVVV',
        '..VPZCoVVVVooVVV',
        '..VPPZoVVVWWoVVV',
        '...VPPoVVVWooVVV',
        '....VPoVVVVVVoVV',
        '.....VoVVVVVVVoo',
        '.ZZZZZZobbbbbbbb',
        '.ZBBBBBoPPPPPPPP',
        '.ZRRRRRoPPPPPPPR',
        '.ZBBBBBoPPPPPPRR',
        '.ZRRRRRoPPPPPRRG',
        '.ZBBBBBoPPPPPRGG',
        '..ZBBBoBBBBBBBRR',
        '...ZBoGGGGGGGGGG',
        '....oVVVGVVVGVVV',
        '.....VVVGVVVGVVV',
        '........bbbb....',
        '.......BBBBB....',
      ],
    },
    // こしの 刀（さやは 青、つばは 金、つかは れんが色）
    {
      x: 23,
      y: 22,
      rows: ['ob......', '.bb.....', '..GG....', '..GBB...', '....BB..', '.....BB.', '......BB', '.......B'],
    },
  ],
};

/** リンゴナイト：リンゴロンが しんか。りんごの よろいの 騎士。葉の つるぎと 葉の たて、りんごの 花の かざり（モリ） */
const ringoKnight: MonsterDesign = {
  size: 32,
  colors: {
    R: NQ.red,
    r: NQ.brick,
    A: NQ.apricot,
    W: NQ.white,
    p: NQ.blush,
    B: NQ.bark,
    G: NQ.leaf,
    g: NQ.green,
    L: NQ.lime,
    Y: NQ.gold,
  },
  rim: { [NQ.red]: NQ.brick },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '................',
        '...............B',
        '...............B',
        '.........RRRR..B',
        '.......RRRRRRR.B',
        '......RRRRRRRRRR',
        '.....RRRRRRRRRRR',
        '.....RRRRRRRRRRR',
        '....rrrrrrrrrrrY',
        '.....RRRRRooRRRR',
        '.....RRRRRWWRRRR',
        '.....RRRRRWoRRRR',
        '.....RRRRRWoRRRR',
        '..RR.RRRpRRRRRRR',
        '..RR.RRRRRRRRRoR',
        '..RR.RRRRRRRRRRo',
        '..rr.RRRRRRRRRRR',
        '....RRRRRRRRRRRR',
        '.....rrrrrrrrrYY',
        '.....RRRRRRRRRRR',
        '......RRRRRRRRRR',
        '.......RRRRRRRRR',
        '...........rrr..',
        '...........rrr..',
        '...........rrr..',
        '...........rrr..',
        '..........BBBB..',
        '..........BBBB..',
        '..........BBBB..',
      ],
    },
    // りんごの 花（ヘタの 左）と 葉っぱ（右）
    { x: 12, y: 2, rows: ['.W.', 'WYW', '.W.'] },
    { x: 17, y: 1, rows: ['....ggg', '..GGGGg', '.GLLGg.', 'GGGg...'] },
    // つや
    { x: 7, y: 7, rows: ['.A', 'AW', 'A.'] },
    // 葉の たて（左手）
    {
      x: 1,
      y: 12,
      rows: [
        '...GG...',
        '..GLLG..',
        '.GLLGGG.',
        '.GLGgGG.',
        'GLLGgGGg',
        'GLGRRGGg',
        'GLGRRGGg',
        'GLGGgGGg',
        'GGGGgGgg',
        '.GGGgGg.',
        '.GGGggg.',
        '..GGgg..',
        '...gg...',
      ],
    },
    // 葉の つるぎ（右手で かかげる）
    {
      x: 26,
      y: 2,
      rows: [
        '..L.',
        '.GL.',
        '.GL.',
        'GGL.',
        'GgL.',
        'GgL.',
        'GgL.',
        'GgL.',
        'GgL.',
        'GgL.',
        '.gL.',
        '.gG.',
        'YYYY',
        '.BB.',
        '.BB.',
      ],
    },
  ],
};

/** クロマグロード：マグロードが しんか。紺の せなか、銀の むねよろい、長い 刀、一本釣りの うき（ミズ） */
const kuroMagurodo: MonsterDesign = {
  size: 32,
  colors: {
    N: NQ.navy,
    B: NQ.blue,
    Z: NQ.azure,
    S: NQ.sky,
    I: NQ.ice,
    L: NQ.silver,
    W: NQ.white,
    p: NQ.blush,
    G: NQ.gold,
    R: NQ.red,
  },
  rim: { [NQ.azure]: NQ.blue, [NQ.silver]: NQ.blue },
  layers: [
    // 大きな 三日月の 尾びれ（うしろ）
    {
      mirror: true,
      y: 17,
      rows: [
        '.S..............',
        '.SN.............',
        '.SBN............',
        '.SBBN...........',
        '..SBBN..........',
        '..SBBBN.........',
        '...SBBBNN.......',
        '....SBBBBNNNNNNN',
        '.....SSBBBBBBBBB',
        '.......SSSSSSSSS',
      ],
    },
    {
      mirror: true,
      rows: [
        '................',
        '...............S',
        '..............SZ',
        '.............SZZ',
        '............NNZZ',
        '..........NNNNNN',
        '.........NNNNNNN',
        '........NNNNNNNN',
        '.......WWWWWWWWW',
        '......NNNZZZZZZZ',
        '......NNZZooZZZZ',
        '......NZZZWWZZZZ',
        '......NZZZWoZZZZ',
        '......NZZZWoZZZZ',
        '......NZZpZZZoZZ',
        '....SSNZZZZZZZoo',
        '...SSSNZZGGGGGGG',
        '..SSSSNZZLLLLLLL',
        '...SSSNZZLLLLLLL',
        '....SSNGZLBBBBBB',
        '......NZZLLLLLLL',
        '......NGZLLLLLLL',
        '......NZZLBBBBBB',
        '.......NZLLLLLLL',
        '........NLLLLLLL',
        '.........GGGGGGG',
        '..........NNNNNN',
        '..........NNN...',
        '..........NNN...',
        '.........NNNN...',
        '.........NNNN...',
      ],
    },
    // 長い 刀（右の ひれで かかげる）
    {
      x: 27,
      y: 1,
      rows: [
        '..W',
        '.WL',
        '.WL',
        '.WL',
        '.WL',
        '.WL',
        '.WL',
        '.WL',
        '.WL',
        '.WL',
        '.WL',
        '.WL',
        'GGGG',
        '.NN.',
        '.NN.',
      ],
    },
    // 一本釣りの うき（左の こし）
    { x: 8, y: 26, rows: ['.o', 'RR', 'WW', 'o.'] },
    // 胸板の つや（左だけ）と はちまきの むすび目
    { x: 10, y: 17, rows: ['I', 'I', '.', 'I', 'I', '.', 'I'] },
    { x: 4, y: 7, rows: ['WW.', '.WW', '..W'] },
  ],
};

/** ドグウジン：ドグウくんが しんか。大きな ゴーグルの 目、でこぼこの かざり、ひろい 肩、むねに ヒスイの まがたま（ツチ） */
const doguJin: MonsterDesign = {
  size: 32,
  colors: {
    T: NQ.tan,
    S: NQ.sand,
    B: NQ.brown,
    E: NQ.beige,
    W: NQ.white,
    p: NQ.blush,
    G: NQ.leaf,
    L: NQ.lime,
    g: NQ.green,
  },
  rim: { [NQ.tan]: NQ.brown },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '.......S...S...S',
        '......TTT.TTT.TT',
        '.....TTTTTTTTTTT',
        '....TTTTTTTTTTTT',
        '...TBTBTBTBTBTBT',
        '..TTooooooooTTTT',
        '..ToEEEEEEEEoTTT',
        '..ToEWEEEEEEoTTT',
        '..TooooooooooTTT',
        '..ToEEEEEEEEoTTT',
        '..ToEEEEEEEEoTTT',
        '..TTooooooooTTTT',
        '..TTpTTTTTTTTTTT',
        '...TTTTTTTTTTTTo',
        '....TTTTTTTTTTTo',
        '......TTTTTTTTTT',
        '.TTTTTTTTTTTTTTT',
        '.TTTBTBTBTTTTTTT',
        '.TTTTBTBTBTTTTTT',
        '.TTT.TTTTTTTTTTT',
        '.TTT.TBTBTBTBTBT',
        '.TTT.TTBTBTBTBTB',
        '.SSS.TTTTTTTTTTT',
        '.....TTTTTTTTTTT',
        '.....TTTTTTTTTTT',
        '......TTTTTT....',
        '......TTTTTT....',
        '......TTTTTT....',
        '.....BBBBBBB....',
        '.....BBBBBBB....',
      ],
    },
    // ヒスイの まがたまの 首かざり（ひもは こげ茶）と、左の 肩の つや
    { mirror: true, y: 16, rows: ['.........B......', '..........BB....', '............BBB.'] },
    { x: 14, y: 18, rows: ['.GGG', 'GLoG', 'GGGG', '..GG', '.gg.'] },
    { x: 1, y: 17, rows: ['SSSS'] },
    // ひび と つや
    { x: 24, y: 3, rows: ['B.', '.B', 'B.'] },
    { x: 5, y: 4, rows: ['SS', 'S.'] },
  ],
};

/**
 * カザミミズク：イタコドリが しんか（ヤミ）。かざぐるまの 風に のる ミミズク。
 * 高い 耳の 羽、頭に もっと 大きな かざぐるま、ひろげた つばさにも かざぐるまの もよう、足もとに 白い 風の うず、金の まゆ
 */
const kazaMimizuku: MonsterDesign = {
  size: 32,
  colors: {
    I: NQ.indigo,
    V: NQ.violet,
    L: NQ.lavender,
    G: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
    Z: NQ.azure,
    E: NQ.leaf,
    W: NQ.white,
  },
  rim: { [NQ.violet]: NQ.indigo },
  layers: [
    // ひろげた つばさ（からだの うしろ）
    {
      mirror: true,
      y: 11,
      rows: [
        '........VV',
        '......VVVV',
        '....VVVVVV',
        '..VVVVVVVV',
        '.VVVVVVVVV',
        '.VVVVVVVVV',
        '.VVVVVVVVV',
        '.VVVVVVVVV',
        '.VVVVVVVVV',
        '.VVVVVVVVV',
        '.VVVVVVVVV',
        '.VVVVVVVVV',
        '.IVVVVVVVV',
        '.I.IVVVVVV',
        '...I.IVVVV',
        '.....I.IVV',
      ],
    },
    {
      mirror: true,
      rows: [
        '................',
        '...I............',
        '...II...........',
        '....II..........',
        '....IVI.........',
        '.....IVI........',
        '.....IVVI.......',
        '......IVVI......',
        '......IVVVI.....',
        '......IVVVVVVVVV',
        '......VVVVVVVVVV',
        '......VVLLLLLLVV',
        '......VLQQLLLLLV',
        '......VLLLQQLLLV',
        '......VLLGGGGLLV',
        '......VLLGWoGLLQ',
        '......VLLGooGLLQ',
        '......VLLLGGLLLV',
        '......IVLLLLLLVV',
        '......IVVVVVVVVV',
        '......IIVVLLLLLL',
        '......IIVLLLVLLL',
        '......IIVLLLLVLL',
        '......IIVLLLLLVL',
        '......IIVLLLVLLV',
        '......IIVLLLLVLL',
        '......IIVVLLLLVL',
        '.......IVVVLLLLV',
        '........IVVVVVVV',
        '.........QQQ....',
        '.........Q.Q....',
      ],
    },
    // つばさの かざぐるま もよう
    {
      mirror: true,
      x: 1,
      y: 14,
      rows: ['RRRR..G', '.RRR.GG', '..RRGGG', 'EEEWGGG', 'EEEZZ..', 'EE.ZZZ.', 'E..ZZZZ'],
    },
    // 頭の 大きな かざぐるま
    {
      x: 10,
      y: 1,
      rows: [
        'RRRRRR....G',
        '.RRRRR...GG',
        '..RRRR..GGG',
        '...RRR.GGGG',
        '....RRGGGGG',
        'EEEEEWGGGGG',
        'EEEEEZZ....',
        'EEEE.ZZZ...',
        'EEE..ZZZZ..',
        'EE...ZZZZZ.',
        'E....ZZZZZZ',
      ],
    },
    // 足もとの 風の うず
    { x: 1, y: 27, rows: ['....WW.', '...W..W', '...W.W.', 'WWWW...'] },
    { x: 24, y: 27, rows: ['.WW....', 'W..W...', '.W.W...', '...WWWW'] },
  ],
};

/** ウミニャン：蕪島の ウミネコ（ネコのように ミャーと なく）。ネコの 耳の ような 羽、黄色い くちばしの 先に 赤と 黒（カゼ） */
const umiNyan: MonsterDesign = {
  size: 32,
  colors: {
    W: NQ.white,
    S: NQ.silver,
    G: NQ.gray,
    N: NQ.night,
    Y: NQ.yellow,
    R: NQ.red,
    F: NQ.orange,
    p: NQ.blush,
  },
  rim: { [NQ.white]: NQ.cloud, [NQ.silver]: NQ.gray },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '......W.........',
        '......WW........',
        '......WpW.......',
        '......WppWWWWWWW',
        '.....WWppWWWWWWW',
        '.....WWWWWWWWWWW',
        '....WWWWWWWWWWWW',
        '....WWWWWWWWWWWW',
        '....WWWWWWooWWWW',
        '....WWWWWWooWWWW',
        '....WWWWWWWWWYYY',
        '....GGWWpWWWYYYY',
        '.....GGWWWWWWWNN',
        '.....WWWWWWWWWWR',
        '......WWWWWWWWWW',
        '.....SSSWWWWWWWW',
        '....GSSSSWWWWWWW',
        '....GSSSSWWWWWWW',
        '...GSSSSSWWWWWWW',
        '...GSSSSSWWWWWWW',
        '...GSSSSSWWWWWWW',
        '...GGSSSSWWWWWWW',
        '...NGGSSSWWWWWWW',
        '...NNGGSWWWWWWWW',
        '...NWNGWWWWWWWWW',
        '...NNN..WWWWWWWW',
        '....N....WWWWWWW',
        '..........FF.NNN',
        '.........FFF....',
      ],
    },
  ],
};

/** ウミネコタイチョウ：ウミニャンが しんかした すがた。船長の ぼうしと 赤い スカーフ、つばさを ひろげる（カゼ） */
const uminekoTaicho: MonsterDesign = {
  size: 32,
  colors: {
    W: NQ.white,
    S: NQ.silver,
    G: NQ.gray,
    N: NQ.night,
    Y: NQ.yellow,
    R: NQ.red,
    F: NQ.orange,
    D: NQ.navy,
    A: NQ.gold,
    p: NQ.blush,
  },
  rim: { [NQ.white]: NQ.cloud, [NQ.silver]: NQ.gray },
  layers: [
    // なかば ひろげた つばさ（うしろ）。先は 黒に 白い 点
    {
      mirror: true,
      y: 19,
      rows: [
        '.N..............',
        '.NNSSS..........',
        '.NWNSSSS........',
        '..NNGSSSS.......',
        '...NGGSSS.......',
        '.....GGSS.......',
        '.......GS.......',
      ],
    },
    {
      mirror: true,
      rows: [
        '................',
        '....W...........',
        '....WW...DDDDDDD',
        '....WpW.DDDDDDDD',
        '....WppWDDDDDDAA',
        '....WppWDDDDDDAA',
        '...WWWWWDDDDDDDD',
        '...WWWWooooooooo',
        '...WWWWWWWWWWWWW',
        '..WWWWWWoooWWWWW',
        '..WWWWWWWooWWWWW',
        '..WWWWWWWWWWWYYY',
        '..GGWWWpWWWWYYYY',
        '...GGWWWWWWWWWNN',
        '...WWWWWWWWWWWWR',
        '....WWWWWWWWWWWW',
        '....RRRRRRRRRRRR',
        '....RRRRRRRRRRRR',
        '......WWWWWWWWWW',
        '......WWWWWWWWWW',
        '......WWWWWWWWWW',
        '......WWWWWWWWWW',
        '......WWWWWWWWWW',
        '......WWWWWWWWWW',
        '......WWWWWWWWWW',
        '......WWWWWWWWWW',
        '.......WWWWWWWWW',
        '........WWWWWWWW',
        '..........FF.NNN',
        '..........FF....',
        '.........FFF....',
      ],
    },
    // スカーフの はし（風で 右に なびく）
    { x: 24, y: 16, rows: ['RRRR...', '.RRRRRR', '...RR.R'] },
  ],
};

/** ブナッコ：白神山地の ブナの 森の 小さな せい。まるい 葉っぱの あたま、白い こけの もようの 灰色の みき、根っこの 足、ブナの 実（モリ） */
const bunakko: MonsterDesign = {
  size: 32,
  colors: {
    L: NQ.leaf,
    l: NQ.lime,
    g: NQ.green,
    S: NQ.silver,
    W: NQ.white,
    B: NQ.brown,
    T: NQ.tan,
    p: NQ.blush,
  },
  rim: { [NQ.leaf]: NQ.green, [NQ.silver]: NQ.gray },
  layers: [
    // みき（葉っぱの うしろから 出る）
    {
      mirror: true,
      y: 13,
      rows: [
        '..........SSSSSS',
        '..........SSSSSS',
        '..........SSSSSS',
        '..........SSSSSS',
        '..........SSWWSS',
        '..........SSWoSS',
        '..........SSWoSS',
        '..........SpSSSS',
        '..........SSSSoS',
        '..........SSSSSo',
        '..........SSSSSS',
        '.........SSSSSSS',
        '.........SSSSSSS',
        '........SSSSSSSS',
        '........SSSSSSSS',
        '.......BBBBBBBBB',
        '......BBB...BBBB',
        '.....BB.......BB',
      ],
    },
    // えだの うで
    { mirror: true, y: 20, rows: ['.......lL.......', '.......LBB......'] },
    // 白い こけの もよう
    { x: 11, y: 24, rows: ['WW', 'W.'] },
    { x: 19, y: 26, rows: ['.W', 'WW'] },
    // まるい 葉っぱの あたま（葉の かたまりが 重なる）と、ぶらさがる 三角の ブナの 実
    {
      mirror: true,
      rows: [
        '................',
        '............LLLL',
        '.......LL..LLlll',
        '.....LLllLLLllLL',
        '.....LlLLLLLlLLL',
        '....LlLLLLLLLLLL',
        '....LlLLLLLLLLLL',
        '....LLLLLLLLLLLL',
        '....LLLLLLLgLLLL',
        '....gLLLLLLggLLL',
        '....LgLLLLLLggLL',
        '....LggLLLLLgggg',
        '....lLLgggggLLLL',
        '....LLLLLLLLLLLL',
        '....gLLLLLLggLLL',
        '.....ggLLgg.gLLL',
        '.....lgggg..gggL',
        '....TBB.......gg',
        '.....B..........',
      ],
    },
  ],
};

/** ブナタイジュ：ブナッコが しんかした すがた。2 だんの 大きな 葉っぱ、太い みきに かしこい 顔、ひろがる 根っこ、小鳥（モリ） */
const bunaTaiju: MonsterDesign = {
  size: 32,
  colors: {
    L: NQ.leaf,
    l: NQ.lime,
    g: NQ.green,
    F: NQ.forest,
    S: NQ.silver,
    W: NQ.white,
    B: NQ.brown,
    T: NQ.tan,
    Z: NQ.azure,
  },
  rim: { [NQ.leaf]: NQ.green, [NQ.silver]: NQ.gray, [NQ.brown]: NQ.bark },
  layers: [
    // 太い みきと 根っこ。白い こけの まゆげ、きりっと した 目、にっこり 口
    {
      mirror: true,
      y: 12,
      rows: [
        '........SSSSSSSS',
        '........SSSSSSSS',
        '........SSSSSSSS',
        '........SSSSSSSS',
        '........SSSSSSSS',
        '........SSSSSSSS',
        '........SSSSSSSS',
        '........WWWSSSSS',
        '........SWWWSSSS',
        '........SSoooSSS',
        '........SSSooSSS',
        '........SSSSSSSS',
        '........SSSSoSSS',
        '........SSSSSooo',
        '.......SSSSSSSSS',
        '......SSSSSSSSSS',
        '....BBSSSSSSSSSS',
        '..BBBBBBBBSSSBBB',
        '.BBB..BBB.BBBBB.',
      ],
    },
    // 白い こけの もよう
    { x: 9, y: 27, rows: ['WW', 'W.'] },
    { x: 20, y: 26, rows: ['.WW', 'WW.'] },
    // 2 だんの 葉っぱ（上の だんの 下に こい かげ）と、ぶらさがる 三角の ブナの 実
    {
      mirror: true,
      y: 1,
      rows: [
        '...........LLLLL',
        '.........LLL.LlL',
        '.......LllLLLlLL',
        '.......llLLLlLLL',
        '......LlLLLLLLLL',
        '......LLLLLLLLLL',
        '......LLLLLFFLLL',
        '......FFLLLLFLLL',
        '.......FFLLLFFFL',
        '..LlLLLLFFFFFLFF',
        '.LlLLLLlLLLLLllL',
        '.lLLLLlLLLLLLlLL',
        '.LLLLLLLLLLLlLLL',
        '.gLLLLLLLLLLLLLL',
        '.gggLggLLLLLgLLL',
        '...gggggLLLgggLL',
        '....B..ggggg.ggg',
        '...TBB..........',
        '....B...........',
      ],
    },
    // 葉っぱの 上に とまる 小鳥
    { x: 20, y: 1, rows: ['.ZZ..Z', 'ToZZZZ', '.WWZZ.'] },
  ],
};

/** ツガルヌリン：津軽塗の おわんの モンスター。何十回も ぬりかさねた つやと、赤・金の ふぶきもよう（ヒカリ） */
const tsugaruNurin: MonsterDesign = {
  size: 32,
  colors: {
    K: NQ.bark,
    B: NQ.brown,
    R: NQ.red,
    G: NQ.gold,
    O: NQ.ochre,
    C: NQ.cream,
    W: NQ.white,
    p: NQ.blush,
    Y: NQ.yellow,
  },
  rim: { [NQ.bark]: NQ.ink },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '..........GGGGGG',
        '.......GGGGGGGGG',
        '.....GGGGGGGGGGG',
        '.....OOOOOOOOOOO',
        '....KKKKKKKKKKKK',
        '...KKRKKKGKKRKKK',
        '...KKKKKKKKKKKKK',
        '..KKKKKKKKKKKKKK',
        '..KKGKKRKKKKGKKK',
        '..KKKKKKKKKKKKKK',
        '..KKKKKKWWKKKKKK',
        '..KKKKKKWoKKKKKK',
        '..KKKKKKWoKKKKKK',
        '..KKppKKKKKKKKKK',
        '..KKKKKKKKKKKoKK',
        '..KKKRKKKKKKKKKo',
        '..KKKKKKKKKGKKKK',
        '..KKKKKKKKKKKKKK',
        '..GGGGGGGGGGGGGG',
        '..OOOOOOOOOOOOOO',
        '..KKKKKKKKKKKKKK',
        '..KKKKRKKKKKKRKK',
        '...KKKKKKKKKKKKK',
        '...KKKKKKKKKKKKK',
        '....KKKKKKKKKKKK',
        '.....KKKKKKKKKKK',
        '.......KKKKKKKKK',
        '..........BBB...',
        '..........BBB...',
      ],
    },
    // うるしの つやと きらり
    { x: 4, y: 8, rows: ['.C', 'C.'] },
    { x: 25, y: 4, rows: ['.Y.', 'YCY', '.Y.'] },
    { x: 2, y: 22, rows: ['.Y.', 'YCY', '.Y.'] },
  ],
};

/** ヌリカガヤキ：ツガルヌリンの しんか。みがきあげた ぬりが かがみの ように 光を はねかえす（ヒカリ） */
const nuriKagayaki: MonsterDesign = {
  size: 32,
  colors: {
    K: NQ.bark,
    B: NQ.brown,
    R: NQ.red,
    G: NQ.gold,
    O: NQ.ochre,
    C: NQ.cream,
    W: NQ.white,
    p: NQ.blush,
    Y: NQ.yellow,
    P: NQ.paper,
  },
  rim: { [NQ.bark]: NQ.ink },
  layers: [
    // うしろの 光
    {
      mirror: true,
      y: 1,
      rows: [
        '..Y.........Y...',
        '...C.......C....',
        '................',
        '................',
        '.Y..............',
        '.C..............',
        '................',
        '................',
        '................',
        '................',
        '.YC.............',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
        '.YC.............',
        '................',
        '................',
        '................',
        '................',
        '.C..............',
        '.Y..............',
        '................',
        '................',
        '...C.......C....',
        '..Y.........Y...',
        '................',
      ],
    },
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '..........GGGGGG',
        '.......GGGGGGGGG',
        '.....GGGGGGGGGGG',
        '.....OOOOOOOOOOO',
        '....GGGGGGGGGGGG',
        '....KKKKKKKKKKKK',
        '...KKRKKGGKKRKKK',
        '..KKKKKKKKKKKKKK',
        '..KKGKKRKKKKGKKK',
        '..KKKKKoooKKKKKK',
        '..KKKKKKWWKKKKKK',
        '..KKKKKKWoKKKKKK',
        '..KKKKKKWoKKKKKK',
        '..KKppKKKKKKKKKK',
        '..KKKKKKKKKKKoKK',
        '..KKKRKKKKKKKKKo',
        '..KKKKKKKKKGKKKK',
        '..GGGGGGGGGGGGGG',
        '..OOOOOOOOOOOOOO',
        '..KKKKKKKKKKKKKK',
        '..KKKKRKKKKKKRKK',
        '..KKKKKKKKKKKKKK',
        '..GGGGGGGGGGGGGG',
        '...OOOOOOOOOOOOO',
        '....KKKKKKKKKKKK',
        '.....KKKKKKKKKKK',
        '.......KKKKKKKKK',
        '..........BBB...',
        '..........BBB...',
      ],
    },
    // うるしの つや
    { x: 4, y: 9, rows: ['.P', 'P.'] },
    { x: 24, y: 13, rows: ['.C.', 'CPC', '.C.'] },
  ],
};

/** 仲間になった ネブタイショウ：フィールド版に 火の粉を 足した すがた */
const nebutaTaishoAlly: MonsterDesign = {
  ...nebutaTaishoField,
  layers: [
    ...nebutaTaishoField.layers,
    { x: 1, y: 2, rows: ['.V.', 'VCV', '.V.'] },
    { x: 27, y: 25, rows: ['.V.', 'VCV', '.V.'] },
  ],
};

// ───────────────────────── 2026-09 に ふやした モンスター（十和田湖・弘前城の さくら・奥入瀬・せんべい汁） ─────────────────────────

/** ヒメマッス：十和田湖の ヒメマスの 子ども。ぎんいろの 体に ピンクの おび、ひれの 足（ミズ） */
const himemassu: MonsterDesign = {
  size: 32,
  colors: { S: NQ.silver, C: NQ.cloud, W: NQ.white, P: NQ.blush, A: NQ.azure },
  rim: { [NQ.silver]: NQ.gray, [NQ.cloud]: NQ.silver },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '.............AAA',
        '............AAAA',
        '.........SSSSSSS',
        '.......SSSSSSSSS',
        '......SSSSSSSSSS',
        '.....SSSSSSSSSSS',
        '....SSSSSSSSSSSS',
        '....SSSSSWWSSSSS',
        '...SSSSSSWoSSSSS',
        '...SSSSSSWoSSSSS',
        '...SSSSSSSSSSSSS',
        '..ASPPPPSSSSSSSS',
        '.AASPPPPPPSSSSSS',
        '.AASSPPPPPPPPPPP',
        '..ASSSSPPPPPPPPP',
        '...SSSSSSSSSSSoo',
        '...SSSSSSSSSSSSS',
        '....CCCCCCCCCCCC',
        '....CCCCCCCCCCCC',
        '.....CCCCCCCCCCC',
        '......CCCCCCCCCC',
        '........CCCCCCCC',
        '..........AAA...',
        '.........AAAA...',
        '.........AAA....',
      ],
    },
  ],
};

/** ヒメマスロード：ヒメマッスが しんかした すがた。秋の ヒメマス（赤い 体に みどりの あたま、まがった あご）に 金の せびれ（ミズ） */
const himemasuLord: MonsterDesign = {
  size: 32,
  colors: { G: NQ.leaf, R: NQ.red, P: NQ.blush, C: NQ.cloud, W: NQ.white, Y: NQ.gold, A: NQ.azure },
  rim: { [NQ.leaf]: NQ.green, [NQ.red]: NQ.brick, [NQ.cloud]: NQ.silver },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '..............YY',
        '............YYYY',
        '...........YYYYY',
        '........GGGGGGGG',
        '......GGGGGGGGGG',
        '.....GGGGGGGGGGG',
        '....GGGGGWWGGGGG',
        '....GGGGGWoGGGGG',
        '....GGGGGWoGGGGG',
        '...GGGGGGGGGGGGG',
        '...GGGGGGGGGGGGG',
        '...GGGGGGGGGGooo',
        '...RRRRRRRRRRRRo',
        '..ARRRRRRRRRRRRR',
        '.AARRRRRRRRRRRRR',
        '.AARRRRPPRRRRRRR',
        '.AARRRRRPPRRRRRR',
        '..ARRRRRRRPPRRRR',
        '...RRRRRRRRRRRRR',
        '...RRRRRRRRRRRRR',
        '....RRRRRRRRRRRR',
        '....CCCCCCCCCCCC',
        '.....CCCCCCCCCCC',
        '......CCCCCCCCCC',
        '........CCCCCCCC',
        '.........AAAA...',
        '........AAAAA...',
        '........AAAA....',
      ],
    },
  ],
};

/** ハチロウリュウ：十和田湖に つたわる 八郎太郎の 竜。金の 大きな つの、ながい 白い ひげ、青緑の うろこ、口から のぞく きば、とぐろを まく 体（ミズ） */
const hachiroRyu: MonsterDesign = {
  size: 32,
  colors: { T: NQ.teal, A: NQ.aqua, N: NQ.navy, W: NQ.white, C: NQ.beige, Y: NQ.gold, R: NQ.red },
  rim: { [NQ.teal]: NQ.navy, [NQ.beige]: NQ.sand },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '...Y............',
        '...YY...........',
        '....YY..........',
        '....YYY.........',
        '.....YYY..NNNNNN',
        '......YYNNNNNNNN',
        '......NTTTTTTTTT',
        '.....NTTTTTTTTTT',
        '....NTTTTTTTTTTT',
        '....TTTTTTWWTTTT',
        '....TTTTTTRoTTTT',
        '....TTTTTTRoTTTT',
        '...TTTTTTTTTTTTT',
        '...TTTTTTTTTTTTT',
        '...TTTTCCCCCCCCC',
        '.W.TTTCCCCCCoCCC',
        '.WWTTTCCCCCCCCCC',
        '.W..TTCCWCCCCCWC',
        '.W..TTTCCCCCCCCC',
        '.....TTTTTTTTTTT',
        '...TT..TTTTTTTTT',
        '..TTTT.TTTTAATTT',
        '.TTAATTTTTTTTTTT',
        '.TTAATTTTTCCCCCC',
        '.TTTTTTTTTCCCCCC',
        '..TTTTTTTTCCCCCC',
        '...TTTTTTTTCCCCC',
        '....TTTTTTTTTTTT',
        '......YY...YY...',
        '.....YYY..YYY...',
      ],
    },
  ],
};

/** サクラポン：弘前城の さくらの つぼみの せい。さくらの 花びらの かたちの ピンクの 体、上に 小さな 葉っぱ（カゼ） */
const sakurapon: MonsterDesign = {
  size: 32,
  colors: { P: NQ.blush, W: NQ.white, R: NQ.berry, G: NQ.leaf, g: NQ.green, B: NQ.bark },
  rim: { [NQ.blush]: NQ.berry },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '..............gG',
        '.............gGG',
        '.........PPP.gPP',
        '.......PPPPPPPPP',
        '......PPPPPPPPPP',
        '..PP..PPPPPPPPPP',
        '.PPPPPPPPPPPPPPP',
        '.PPPPPPPPPPPPPPP',
        '..PPPPPPPPPPPPPP',
        '...PPPPPPWWPPPPP',
        '...PPPPPPWoPPPPP',
        '...PPPPPPWoPPPPP',
        '..PPPPPRRPPPPPPP',
        '.PPPPPPPPPPPPPoo',
        '.PPPPPPPPPPPPPPP',
        '..PPPPPPPPPPPPPP',
        '...PP.PPPPPPPPPP',
        '......PPPPPPPPPP',
        '.......PPPPP.PPP',
        '........PPP...PP',
        '..........BB....',
        '..........BB....',
        '.........BBB....',
        '........BBBB....',
        '................',
      ],
    },
  ],
};

/** ハナイカダ：サクラポンが しんかした すがた。お堀に ちった さくらの 花びらが あつまって、小さな いかだに のって ながれる（カゼ） */
const hanaikada: MonsterDesign = {
  size: 32,
  colors: {
    P: NQ.blush,
    p: NQ.berry,
    W: NQ.white,
    T: NQ.tan,
    B: NQ.brown,
    A: NQ.azure,
    K: NQ.sky,
    G: NQ.leaf,
  },
  rim: { [NQ.blush]: NQ.berry, [NQ.tan]: NQ.brown },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '..........P.....',
        '.........PPP..G.',
        '......P..PWPPGG.',
        '.....PPPPPPPPPPP',
        '....PPWPPPPPPPPP',
        '...PPPPPPPPpPPPP',
        '..PPPPPPPPPPPPPP',
        '..PPPPPPPPPPPPPP',
        '.PPpPPPPPWWPPPPP',
        '.PPPPPPPPWoPPPPP',
        '.PPPPPPPPWoPPPPP',
        '..PPPPPPPPPPPPPP',
        '..PPWPPPPPPPPPoo',
        '..PPPPPPpPPPPPPP',
        '...PPPPPPPPPPPPP',
        '...PP.PPPPPPPPPP',
        '..TTTTTTTTTTTTTT',
        '..TBTTTTBTTTTBTT',
        '..TTTTTTTTTTTTTT',
        '.KKKKKKKKKKKKKKK',
        '.WKKKWWKKKWKKKKW',
        '..AAAAAAAAAAAAAA',
        '...AAAAAAAAAAAAA',
        '.....AAAAAAAAAAA',
        '................',
      ],
    },
  ],
};

/** オウカムシャ：弘前城を まもる さくらの むしゃ。さくらの 金の まえだての かぶと、ふきかえし、ピンクの よろいの ひも、さくらの えだを もつ（カゼ） */
const okaMusha: MonsterDesign = {
  size: 32,
  colors: {
    N: NQ.navy,
    n: NQ.denim,
    Y: NQ.gold,
    P: NQ.blush,
    R: NQ.berry,
    K: NQ.skinLight,
    W: NQ.white,
    B: NQ.bark,
    G: NQ.leaf,
  },
  rim: { [NQ.navy]: NQ.ink, [NQ.blush]: NQ.berry },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '...........Y.Y..',
        '..........YWYWY.',
        '...........YYY.Y',
        '............Y.YY',
        '........NNNNNNNN',
        '......NNNNNNNNNN',
        '.....NNnNNNNNNNN',
        '..NNNNNNNNNNNNNN',
        '.NNNNNNNNNNNNNNN',
        '..NNNKKKKKKKKKKK',
        '...NNKKKKWWKKKKK',
        '....NKKKKWoKKKKK',
        '.....KKKKWoKKKKK',
        '.....KKKKKKKKKoo',
        '......KKKKKKKKKK',
        '...RRRRPPPPPPPPP',
        '..PPPPPPPPPPPPPP',
        '.PPRPPRPPRPPRPPR',
        '.PPPPPPPPPPPPPPP',
        '.KK.PPRPPRPPRPPR',
        '.KK.PPPPPPPPPPPP',
        '....PPRPPRPPRPPR',
        '....RRRRRRRRRRRR',
        '....PPPPPPPPPPPP',
        '.....PPPPPPPPPPP',
        '......NNNN..NNNN',
        '......NNNN..NNNN',
        '.....BBBBB..BBBB',
        '.....BBBBB......',
      ],
    },
    {
      x: 22,
      y: 10,
      rows: [
        '...W.W.',
        '..WPWPW',
        '...BWB.',
        '....B..',
        '....B..',
        '...B...',
        '...B...',
        '..B....',
        '..B....',
        '.KK....',
      ],
    },
  ],
};

/** コケッピ：奥入瀬渓流の 岩に はえる こけの せい。ふかふかの みどりの 玉に 水の しずく、下に 灰色の 岩（モリ） */
const kokeppi: MonsterDesign = {
  size: 32,
  colors: { G: NQ.leaf, g: NQ.green, L: NQ.lime, W: NQ.white, S: NQ.slate, s: NQ.gray, K: NQ.sky },
  rim: { [NQ.leaf]: NQ.green, [NQ.gray]: NQ.slate },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
        '..........K.....',
        '.........KK.....',
        '......G.GKG.G..G',
        '.....GGGGGGGGGGG',
        '....GGLGGGGGGLGG',
        '...GGGGGGGGGGGGG',
        '...GLGGGGGGGGGGG',
        '..GGGGGGGGGGGGGG',
        '..GGGGGGGWWGGGGG',
        '..GGGGGGGWoGGGGG',
        '..GGGGGGGWoGGGGG',
        '..GGGGGGGGGGGGGo',
        '..GGLGGGGGGGGGGG',
        '...GGGGGGGGGGGGG',
        '...G.GGGGGGGGGGG',
        '....ssssssssssss',
        '...sssssssssssss',
        '..sssssssssssss.',
        '..ssssSSsssssss.',
        '..ssssssssssssss',
        '...sssssssssssss',
        '....ssssssssssss',
        '................',
      ],
    },
  ],
};

/** オイラセコケジン：コケッピが しんかした すがた。こけに おおわれた 岩の 大男。むねから 小さな たきが ながれる（モリ） */
const oiraseKokejin: MonsterDesign = {
  size: 32,
  colors: {
    G: NQ.leaf,
    g: NQ.green,
    L: NQ.lime,
    S: NQ.gray,
    s: NQ.slate,
    W: NQ.white,
    K: NQ.sky,
    Y: NQ.yellow,
  },
  rim: { [NQ.leaf]: NQ.green, [NQ.gray]: NQ.slate },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '................',
        '.......G.G..G.G.',
        '......GGGGGGGGGG',
        '.....GGLGGGGGGGG',
        '....GGGGGGGGGGGG',
        '....GSSSSSSSSSSS',
        '....GSSSSSSSSSSS',
        '....SSSSYYSSSSSS',
        '....SSSSYYoSSSSS',
        '....SSSSSSSSSSSS',
        '....SSSSSSSSSooo',
        '.GGGGSSSSSSSSSSS',
        '.GLGGGGGGGGGGGGG',
        '.GGGGGGGGGGGGKKK',
        '.SSSGGGGGGGGGKWK',
        '.SSSSSGGGGGGGKKW',
        '.SSSS.SSSSSSSKWK',
        '.SSS..SSSSSSSKKK',
        '.GSS..SSSSSSSWKK',
        '.GGS..SSSSSSSKWK',
        '......SSSSSSSSSS',
        '......SSSSSSSSSS',
        '......SSSSGSSSSS',
        '.....SSSSSS..SSS',
        '.....SSSSSS..SSS',
        '....GGSSSSS..SSS',
        '....GGGGGGG..GGG',
        '................',
      ],
    },
  ],
};

/** センベイン：八戸の せんべい汁に 入れる 南部せんべいの せい。まるい きつね色の せんべいに ごまの つぶ、ふちは みみ（ヒノ） */
const senbein: MonsterDesign = {
  size: 32,
  colors: { T: NQ.tan, S: NQ.sand, B: NQ.brown, b: NQ.bark, W: NQ.white, R: NQ.berry },
  rim: { [NQ.tan]: NQ.brown },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
        '..........SSSSSS',
        '.......SSSSSSSSS',
        '.....SSTTTTTTTTT',
        '....SSTTTbTTTTTT',
        '...STTTTTTTTTbTT',
        '...STTbTTTTTTTTT',
        '..STTTTTTTTTTTTT',
        '..STTTTTTWWTTTTT',
        '..STTTTTTWoTTbTT',
        '..STbTTTTWoTTTTT',
        '..STTTTTTTTTTTTT',
        '..STTTTRRTTTTToo',
        '..STTTTTTTTTTTTT',
        '..STTbTTTTTTbTTT',
        '...STTTTTTTTTTTT',
        '...SSTTTTbTTTTTT',
        '....SSTTTTTTTTTT',
        '.....SSSSSSSSSSS',
        '.......SSSSSSSSS',
        '.........BB.....',
        '.........BB.....',
        '........BBB.....',
        '.......BBBB.....',
        '................',
      ],
    },
  ],
};

/** ナベショウグン：センベインが しんかした すがた。おなべの かぶとから ゆげ、あつあつの 汁の よろいに せんべいの たて（ヒノ） */
const nabeShogun: MonsterDesign = {
  size: 32,
  colors: {
    N: NQ.slate,
    n: NQ.gray,
    W: NQ.white,
    C: NQ.cloud,
    O: NQ.orange,
    T: NQ.tan,
    R: NQ.red,
    K: NQ.skinMid,
  },
  rim: { [NQ.slate]: NQ.night, [NQ.orange]: NQ.amber, [NQ.tan]: NQ.brown },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '........C.......',
        '.......C..C.....',
        '........C..C....',
        '.........C......',
        '......NNNNNNNNNN',
        '...nnNNNNNNNNNNN',
        '..nn.NNNNNNNNNNN',
        '.....NNNNNNNNNNN',
        '....NNNNNNNNNNNN',
        '.....KKKKKKKKKKK',
        '.....KKKKWWKKKKK',
        '.....KKKKWoKKKKK',
        '.....KKKKWoKKKKK',
        '.....KKKKKKKKooo',
        '......KKKKKKKKKK',
        '...OOOOOOOOOOOOO',
        '.TTTTOOOOOOOOOOO',
        '.TTTTTOOROOOOOOO',
        '.TTTTTOOOOOOOROO',
        '.TTTTTOOOOOOOOOO',
        '..TTTOOOROOOOOOO',
        '....OOOOOOOOOOOO',
        '....OOOOOOOOOOOO',
        '.....OOOOOOOOOOO',
        '......RRRR..RRRR',
        '......RRRR..RRRR',
        '.....NNNNN..NNNN',
        '.....NNNNN......',
        '................',
      ],
    },
  ],
};

export const AOMORI: Readonly<Record<string, MonsterDesign>> = {
  'aomori-himemassu': himemassu,
  'aomori-himemasu-lord': himemasuLord,
  'aomori-hachiro-ryu': hachiroRyu,
  'aomori-sakurapon': sakurapon,
  'aomori-hanaikada': hanaikada,
  'aomori-oka-musha': okaMusha,
  'aomori-kokeppi': kokeppi,
  'aomori-oirase-kokejin': oiraseKokejin,
  'aomori-senbein': senbein,
  'aomori-nabe-shogun': nabeShogun,
  'aomori-lastboss-tsugaru-tamenobu': LAST_BOSSES['aomori-lastboss-tsugaru-tamenobu']!,
  'aomori-tsugaru-nurin': tsugaruNurin,
  'aomori-nuri-kagayaki': nuriKagayaki,
  'aomori-umi-nyan': umiNyan,
  'aomori-umineko-taicho': uminekoTaicho,
  'aomori-bunakko': bunakko,
  'aomori-buna-taiju': bunaTaiju,
  'aomori-ringoron': ringoron,
  'aomori-ringo-knight': ringoKnight,
  'aomori-kuro-magurodo': kuroMagurodo,
  'aomori-dogu-jin': doguJin,
  'aomori-kaza-mimizuku': kazaMimizuku,
  'aomori-nebutan': nebutan,
  'aomori-nebuta-musha': nebutaMusha,
  'aomori-nebuta-taisho': nebutaTaishoAlly,
  'aomori-magurodo': magurodo,
  'aomori-doguukun': doguukun,
  'aomori-itakodori': itakodori,
  'aomori-midboss-nebuta-taisho': nebutaTaisho,
  'aomori-midboss-nebuta-taisho.field': nebutaTaishoField,
  'aomori-boss-tsugaru-no-nushi': tsugaruNoNushi,
  'aomori-boss-tsugaru-no-nushi.p0': tsugaruNoNushiP0,
};
