/** 福岡県の モンスター（手描き。docs/06 §4・§6.3〜6.5 の 規格） */
import { NQ } from '../palette';
import type { MonsterDesign } from './design';
import { FACE, lord } from './lastbosses';

/** バリカタン：博多ラーメンの どんぶり。白い とんこつスープに 細い めん・チャーシュー・ねぎ・紅しょうが。頭に 3 本の 炎（ヒノ） */
const barikatan: MonsterDesign = {
  size: 32,
  colors: {
    R: NQ.red,
    W: NQ.white,
    C: NQ.cream,
    Y: NQ.gold,
    A: NQ.apricot,
    V: NQ.vermilion,
    L: NQ.leaf,
    T: NQ.tan,
    B: NQ.brown,
    p: NQ.blush,
  },
  rim: { [NQ.red]: NQ.brick },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '...............C',
        '..............CY',
        '.........C....AY',
        '.........A...VAY',
        '........VA...VAY',
        '........VAV.VVAA',
        '......RRRRRRRRRR',
        '....RRWWWWWWWWWW',
        '...RWWWWWWWWWWWW',
        '..RWWWWWWWWWWWWW',
        '..RWWWWWWWWWWWWW',
        '..RRWWWWWWWWWWWW',
        '..RRRRWWWWWWWWWW',
        '..RRRRRRRRRRRRRR',
        '..WWWWWWWWWWWWWW',
        '..WRWWRWWRWWRWWR',
        '...RRRRRRRRRRRRR',
        '...RRRRRRRWWRRRR',
        '...RRRRRRRWoRRRR',
        '....RRRRRRWoRRRR',
        '....RRRpRRRRRRoR',
        '.....RRRRRRRRRRo',
        '.....RRRRRRRRRRR',
        '......RRRRRRRRRR',
        '.......RRRRRRRRR',
        '.........RRRRRRR',
        '..........RRRRRR',
        '..........RRRRRR',
      ],
    },
    // チャーシュー・めん・ねぎ・紅しょうが
    { x: 5, y: 9, rows: ['.BBBB.', 'BTTTTB', 'BTTBTB', '.BBBB.'] },
    { x: 12, y: 10, rows: ['..CCC.CCCC', '.CCCCCC.CCC', 'CCC.CCCCCC.', '...CCC.CC'] },
    { x: 14, y: 9, rows: ['L..L', '.LL.'] },
    { x: 22, y: 10, rows: ['.RR', 'RRR', 'RR.'] },
  ],
};

/** ストロベビー：まっ赤な いちごの 赤ちゃん。つぶつぶの たね、星の ような 緑の へた（モリ） */
const strobaby: MonsterDesign = {
  size: 32,
  colors: {
    R: NQ.red,
    W: NQ.white,
    Y: NQ.yellow,
    L: NQ.leaf,
    G: NQ.green,
    M: NQ.lime,
    p: NQ.blush,
  },
  rim: { [NQ.red]: NQ.brick, [NQ.leaf]: NQ.green },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
        '..........RRRRRR',
        '.......RRRRRRRRR',
        '.....RRRRRRRRRRR',
        '...RRRRRRRRRRRRR',
        '..RRRRRRRRRRRRRR',
        '..RRRRRRRRRRRRRR',
        '..RRRRRRRRRRRRRR',
        '..RRRRRRRRRRRRRR',
        '..RRRRRRRRRWWRRR',
        '..RRRRRRRRRWoRRR',
        '..RRRRRRRRRWoRRR',
        '...RRRRpRRRRRRoR',
        '...RRRRRRRRRRRRo',
        '...RRRRRRRRRRRRR',
        '....RRRRRRRRRRRR',
        '....RRRRRRRRRRRR',
        '.....RRRRRRRRRRR',
        '......RRRRRRRRRR',
        '.......RRRRRRRRR',
        '........RRRRRRRR',
        '..........RRRRRR',
        '..........RRR...',
        '.........RRRR...',
        '.........RRRR...',
      ],
    },
    // へた（星形の 葉が 上から たれる）と じく
    {
      mirror: true,
      y: 2,
      rows: [
        '...............G',
        '...............G',
        '..............GG',
        '..........LLLLLL',
        '.......LLLMLLLLL',
        '....LLLMLLLLLLLL',
        '...LLLLL.LLLL.LL',
        '...LLL...LLL...L',
        '....L.....L.....',
      ],
    },
    // たねの つぶつぶ・つや
    {
      mirror: true,
      y: 11,
      rows: [
        '.......Y....Y...',
        '....Y...........',
        '...............Y',
        '',
        '',
        '',
        '',
        '....Y...........',
        '',
        '',
        '.......Y.....Y..',
        '',
        '',
        '..........Y.....',
      ],
    },
    { x: 5, y: 10, rows: ['WW', 'W.'] },
  ],
};

/** 竹の さお（右上から 左下へ。G は ふし） */
const SAO = [
  '....L',
  '....L',
  '....L',
  '....G',
  '...L.',
  '...L.',
  '...L.',
  '...G.',
  '..L..',
  '..L..',
  '..L..',
  '..G..',
  '.L...',
  '.L...',
  '.L...',
  '.L...',
  '.G...',
  'L....',
  'L....',
  'L....',
  'L....',
  'L....',
  'G....',
  'L....',
  'L....',
  'L....',
];

/** ドンコマル：柳川の どんこ舟に のった 水の 子。すげがさを かぶり、竹の さおで 舟を すすめる（ミズ） */
const donkomaru: MonsterDesign = {
  size: 32,
  colors: {
    A: NQ.azure,
    S: NQ.sky,
    W: NQ.white,
    p: NQ.blush,
    E: NQ.sand,
    T: NQ.tan,
    B: NQ.brown,
    K: NQ.bark,
    L: NQ.leaf,
    G: NQ.green,
  },
  rim: { [NQ.azure]: NQ.blue, [NQ.sand]: NQ.tan, [NQ.brown]: NQ.bark },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '...............E',
        '.............EEE',
        '...........EEEEE',
        '.........EEEEEEE',
        '.......EEEEEEEEE',
        '.....EEEEEEEEEEE',
        '...EEEEEEEEEEEEE',
        '......AAAAAAAAAA',
        '.....AAAAAAAAAAA',
        '.....AAAAAWWAAAA',
        '....SAAAAAWoAAAA',
        '...SSAAAAAWoAAAA',
        '....SAAApAAAAAoA',
        '.....AAAAAAAAAAo',
        '......AAAAAAAAAA',
        '..TTTTTTTTTTTTTT',
        '..BBBBBBBBBBBBBB',
        '...BBBBBBBBBBBBB',
        '...KKKKKKKKKKKKK',
        '....BBBBBBBBBBBB',
        '.....BBBBBBBBBBB',
        '......BBBBBBBBBB',
        '..SSWSSSSSWSSSSS',
        '.SSSSSSSSSSSSSSS',
        '...SS..SSSS.SSSS',
      ],
    },
    // すげがさの すじ
    {
      mirror: true,
      y: 7,
      rows: ['..............T.', '............T...', '..........T.....', '........T.......'],
    },
    // 竹の さお（まえ。上は かさの よこを とおる）と にぎる 手
    { x: 23, y: 1, rows: [...SAO] },
    { x: 22, y: 18, rows: ['AA', 'AA'] },
  ],
};

/**
 * バナナタイショウ（中ボス）：門司港の バナナの たたき売りの 大将。5 本の バナナが 1 ふさに なった 大きな からだ、
 * まん中の バナナに 顔と ねじりはちまき、先っぽに 王冠。赤い はらまきに こん色の ももひき（モリ）
 */
const bananaTaisho: MonsterDesign = {
  size: 40,
  colors: {
    Y: NQ.yellow,
    C: NQ.cream,
    B: NQ.bark,
    G: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
    W: NQ.white,
    D: NQ.denim,
    V: NQ.vermilion,
    K: NQ.brown,
  },
  rim: {
    [NQ.yellow]: NQ.ochre,
    [NQ.denim]: NQ.navy,
    [NQ.vermilion]: NQ.brick,
    [NQ.white]: NQ.cloud,
    [NQ.brown]: NQ.bark,
  },
  rimDepth: 2,
  layers: [
    // うしろに 開く 4 本の 大きな バナナ
    {
      mirror: true,
      y: 6,
      rows: [
        '..BB................',
        '.BYYB...............',
        '.YYYY...............',
        '.YYYY...............',
        '.YYYY..BB...........',
        '..YYYY.BYYB.........',
        '..YYYY.YYYY.........',
        '..YYYY.YYYY.........',
        '...YYYYYYYY.........',
        '...YYYYYYYY.........',
        '....YYYYYYY.........',
        '....YYYYYYY.........',
        '.....YYYYYY.........',
        '.....YYYYYY.........',
        '......YYYYY.........',
        '......YYYYY.........',
        '.......YYYY.........',
      ],
    },
    // 大将の 頭（大きな バナナ）と 法被の からだ
    {
      mirror: true,
      rows: [
        '....................',
        '................G..G',
        '................GGGG',
        '................GGGR',
        '................GGGR',
        '................QQQQ',
        '....................',
        '...........YYYYYYYYY',
        '..........YYYYYYYYYY',
        '..........YYYYYYYYYY',
        '..........YYYYYYYYYY',
        '..........YYYYYYYYYY',
        '..........YYYYYYYYYY',
        '..........YYYYYYYYYY',
        '..........YYYYYYYYYY',
        '..........YYYYYYYYYY',
        '..........YYYYYYYYYY',
        '..........YYYYYYYYYY',
        '..........YYYYYYYYYY',
        '..........YYYYYYYYYY',
        '..........YYYYYYYYYY',
        '..........YYYYYYYYYY',
        '..........YYYYYYYYYY',
        '...........YYYYYYYYY',
        '............YYYYYYYY',
        '.......VVVVVVVVVVVVV',
        '......VVVVVVVVVVVVVV',
        '.....VVVVWWWWWWWWWWW',
        '.....VVVVWWWWWWWWWWW',
        '....VVVVVRRRRRRRRRRR',
        '....VVVVVRRRRRRRRRRR',
        '....VVVVVGGGGGGGGGGG',
        '....VVVVVRRRRRRRRRRR',
        '.....VVVVDDDDDDDDDDD',
        '.........DDDDDDDDDDD',
        '.........DDDDDDDDDDD',
        '.........DDDDDDDD...',
        '.........BBBBBBB....',
        '.........BBBBBBB....',
      ],
    },
    // ねじりはちまき・きりっと した まゆ・するどい 目・大きな 口
    {
      mirror: true,
      y: 10,
      rows: [
        '..........RWRWRWRWRW',
        '..........WRWRWRWRWR',
        '....................',
        '............oooo....',
        '.............ooo....',
        '...........WWWWo....',
        '...........WWWoo....',
        '...........WWWoo....',
        '...........WWooo....',
        '....................',
        '................oooo',
        '.................ooo',
      ],
    },
    // かかげた 竹の ぼう（たたき売りの ぼう）
    {
      x: 29,
      y: 5,
      rows: [
        '.....KK',
        '.....KK',
        '....KK.',
        '....KK.',
        '....KK.',
        '...KK..',
        '...KK..',
        '...GG..',
        '..KK...',
        '..KK...',
        '..KK...',
        '.KK....',
        '.KK....',
        '.GG....',
        'KK.....',
        'KK.....',
        'KK.....',
      ],
    },
    // 力の オーラ
    { x: 2, y: 3, rows: ['.C.', 'CGC', '.C.'] },
    { x: 35, y: 33, rows: ['.C.', 'CGC', '.C.'] },
  ],
};

/** バナナタイショウ（フィールドに立つ 32×32） */
const bananaTaishoField: MonsterDesign = {
  size: 32,
  colors: {
    Y: NQ.yellow,
    B: NQ.bark,
    G: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
    W: NQ.white,
    D: NQ.denim,
    V: NQ.vermilion,
  },
  rim: { [NQ.yellow]: NQ.ochre, [NQ.denim]: NQ.navy, [NQ.vermilion]: NQ.brick },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '............G..G',
        '............GGGG',
        '............GGGR',
        '.....BB.....QQQQ',
        '....BYYB....YYYY',
        '....YYYY...YYYYY',
        '....YYYY..YYYYYY',
        '.BB.YYYY..YYYYYY',
        '.BYYBYYY.YYYYYYY',
        '.YYYYYYYYYYYYYYY',
        '.YYYYYYYYYYYYYYY',
        '..YYYYYYYYYYYYYY',
        '..YYYYYYYYYYYYYY',
        '...YYYYYYYYYYYYY',
        '....YYYYYYYYYYYY',
        '.....YYYYYYYYYYY',
        '.....VVVVVVVVVVV',
        '....VVVVVVVVVVVV',
        '....VVVWWWWWWWWW',
        '....VVVWWWWWWWWW',
        '...VVVVRRRRRRRRR',
        '...VVVVRRRRRRRRR',
        '...VVVVGGGGGGGGG',
        '....VVVDDDDDDDDD',
        '.......DDDDDDDDD',
        '.......DDDDDDDD.',
        '........DDDDDD..',
        '.......BBBBBBB..',
        '.......BBBBBBB..',
      ],
    },
    {
      mirror: true,
      y: 9,
      rows: [
        '.........RWRWRWR',
        '.........WRWRWRW',
        '..........oo....',
        '...........WWo..',
        '...........WWo..',
        '...........Woo..',
        '................',
        '..............oo',
      ],
    },
  ],
};

/** 光の すじ（まん中から のびる とげとげ。C＝光、G＝先っぽ）。岩手の 後光と 同じ 作り方 */
function glow(size: number, cy: number, rIn: number, rOut: number, n: number, bottom: number): string[] {
  const cx = (size - 1) / 2;
  return Array.from({ length: size }, (_, y) =>
    Array.from({ length: size }, (_, x) => {
      const d = Math.hypot(x - cx, y - cy);
      const a = Math.abs(Math.atan2(x - cx, cy - y));
      const u = (a / ((2 * Math.PI) / n)) % 1;
      const r = rIn + (rOut - rIn) * (1 - 2 * Math.min(u, 1 - u));
      if (d > r || y > bottom || x < 1 || y < 1 || x > size - 2) return '.';
      return d > r - 2.5 ? 'G' : 'C';
    }).join(''),
  );
}

/** ぐるりと まいた 羊の つの（左半分。S＝石灰岩の 灰色、g＝ふしの すじ） */
const HIRAO_HORN = [
  '........................',
  '........................',
  '.......SSSSS............',
  '.....SSSgSSSSS..........',
  '....SSgSSSgSSSSS........',
  '...SSgSSSSSgSSSSS.......',
  '..SSgSSS....SgSSS.......',
  '..SgSS.......SSSS.......',
  '..SSSS........SS........',
  '.SSgS...................',
  '.SSSS.......SSS.........',
  '.SgSS......SSSS.........',
  '.SSSS.....SSgS..........',
  '..SgSS...SSSS...........',
  '..SSSSSSSgSS............',
  '...SSgSSSSS.............',
  '....SSSSSS..............',
];

/** ヒラオダイオウの からだ（白い 石灰岩の 岩が あつまった 羊の 毛。c＝岩の われめ） */
const HIRAO_WOOL = [
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '.................WWWWWWW',
  '................WWWWWWWW',
  '................WWWcWWWW',
  '...............WWWWWWWWW',
  '..............WWWWWWWWWW',
  '..............WWWWWWWWWW',
  '..............WWWWWWWWWW',
  '..............WWWWWWWWWW',
  '..............WWWWWWWWWW',
  '..............WWWWWWWWWW',
  '..............WWWWWWWWWW',
  '.....WWWWWWWWWWWWWWWWWWW',
  '...WWWWWWWWcWWWWWWWWWWWW',
  '..WWWWWWWWWWcWWWWWWWWWWW',
  '.WWWWcccWWWWWcWWWWWWWWWW',
  '.WWWWWWWccWWWWcWWWWWWWWW',
  '.WWWWWWWWWcWWWWWWWWWWWWW',
  '.WWcWWWWWWWcWWWWWWWWWWWW',
  '.WWWccWWWWWWcWWWWWWWWWWW',
  '.WWWWWcWWWWWWWWWWcccWWWW',
  '.WWWWWWcWWWWWWWWcWWWcWWW',
  '..WWWWWWcWWWWWWcWWWWWWWW',
  '..WWWWWWWcccWWcWWWWWWWWW',
  '.WWWWWWWWWWWccWWWWWWWWWW',
  '.WWWcccWWWWWWWWWWWcccWWW',
  '.WWWWWWccWWWWWWWWcWWWWWW',
  '..WWWWWWWcWWWWWWcWWWWWWW',
  '..WWWWWWWWcWWWWcWWWWWWWW',
  '...WWWWWWWWcWWcWWWWWWWWW',
  '....WWWWWWWWccWWWWWWWWWW',
  '......WWWWWWWWWWWWWWWWWW',
  '.........WWWWWWWWWWWWWWW',
  '..............WWWcWWcWWW',
  '...............W..W..W.W',
];

/** 顔（こい 灰色の 長い 顔、明るい 鼻づら）・まゆ・3×4 の 目 */
const HIRAO_FACE = [
  '...............NNNNNNNNN',
  '..............NNNNNNNNNN',
  '..............NoooooNNNN',
  '..............NNoooNNNNN',
  '..............NNEEEENNNN',
  '..............NNEEooNNNN',
  '..............NNEoooNNNN',
  '...............NNNNNNNNN',
  '...............NNNNNNNNN',
  '................NNNggggg',
  '.................Nggoggg',
  '.................Nggggoo',
  '..................Nggggg',
  '...................ggggg',
];

/**
 * ヒラオダイオウ（県ボス）：平尾台の 白い 石灰岩の むれを たばねる 羊の 王。ぐるりと まいた 大きな つの、
 * 岩が あつまった 白い 毛、こい 灰色の 顔、太い 足で 草原に ふんばる。王冠は つのの あいだ（ツチ）
 */
const hiraodaio: MonsterDesign = {
  size: 48,
  colors: {
    W: NQ.white,
    c: NQ.silver,
    E: NQ.gold,
    S: NQ.silver,
    g: NQ.gray,
    N: NQ.slate,
    K: NQ.night,
    G: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
    L: NQ.leaf,
    D: NQ.green,
  },
  rim: {
    [NQ.white]: NQ.cloud,
    [NQ.silver]: NQ.gray,
    [NQ.slate]: NQ.night,
    [NQ.leaf]: NQ.green,
    [NQ.gold]: NQ.ochre,
  },
  rimDepth: 2,
  layers: [
    // 太い 前足と ひづめ
    {
      mirror: true,
      y: 35,
      rows: [
        '.........NNNNNN.........',
        '.........NNNNNN.........',
        '.........NNNNNN.........',
        '.........NNNNNN.........',
        '.........NNNNNN.........',
        '.........NNNNNN.........',
        '.........NNNNNN.........',
        '........NNNNNNN.........',
        '........KKKKKKKK........',
        '........KKKKoKKK........',
      ],
    },
    { mirror: true, rows: HIRAO_WOOL },
    { mirror: true, rows: HIRAO_HORN },
    { mirror: true, y: 10, rows: HIRAO_FACE },
    // 大きな 王冠
    {
      mirror: true,
      y: 1,
      rows: [
        '..................G.G..G',
        '..................GGGGGG',
        '..................GGGGGR',
        '..................GGGGGR',
        '..................QQQQQQ',
      ],
    },
    // 平尾台の 草原
    {
      mirror: true,
      y: 40,
      rows: [
        '..........L.............',
        '.........LDL........L...',
        '........LLDLL......LDL..',
        '.......LLDLLLL....LLDLL.',
        '.......LLLLLLL....LLLLL.',
      ],
    },
    // カルストの 石灰岩の 岩ばしら（草原に 立つ 白い 石の はしら）
    {
      mirror: true,
      y: 33,
      rows: [
        '..S.....................',
        '.SSS....................',
        '.SSS....................',
        '.SSS....................',
        '.SSS.S..................',
        '.SSSSSS.................',
        '.SSSSSS.................',
        '.SSSSSS.................',
        '.SSSSSS.................',
        'SSSSSSS.................',
        'SSSSSSS.................',
        'SSSSSSS.................',
      ],
    },
  ],
};

/** ヒラオダイオウ 後半（ヒカリ）：地下の しょうにゅうどうの 光が あふれ、うしろに 光の すじ、かたに 光る 結晶 */
const hiraodaioP0: MonsterDesign = {
  ...hiraodaio,
  colors: { ...hiraodaio.colors, C: NQ.cream, c: NQ.cream, E: NQ.white, I: NQ.ice, B: NQ.sky },
  layers: [
    { rows: glow(48, 16, 17, 26, 14, 24) },
    ...hiraodaio.layers,
    // かたの 結晶
    { mirror: true, y: 15, rows: ['.....I..', '....IBI.', '...IIBI.', '..IBIIBI', '...IIII.'] },
    // きらきら
    { x: 2, y: 2, rows: ['.C.', 'CGC', '.C.'] },
    { x: 43, y: 2, rows: ['.C.', 'CGC', '.C.'] },
  ],
};

/** 黒田官兵衛：赤い うるしの おわんを ふせた 形の かぶと「赤合子（あかごうし）」に 金の わ、黒い よろい（ヒカリ） */
const kurodaKanbeiBase = lord(
  [
    '......................GG',
    '......................GG',
    '.....................GGG',
    '....................GGGG',
    '...................LGGGG',
    '.............LLLLLLLLLLL',
    '..........LLLLNNNNNNNNNN',
    '.........LNNNNNNNNNNNNNN',
    '........LNNNNNNNNNNNNNNN',
    '........NNNNNNNNNNNNNNNN',
    '.......GNNNNNNNNNNNNNNNN',
    '.......NNNNNNNNNNNNNNNNN',
    '.......GGNNNNNNNNNNNNNNN',
    ...FACE,
  ],
  {
    N: NQ.red,
    L: NQ.vermilion,
    K: NQ.night,
    S: NQ.slate,
    G: NQ.gold,
    C: NQ.cream,
    R: NQ.red,
    T: NQ.bark,
    H: NQ.navy,
  },
  { [NQ.red]: NQ.brick, [NQ.slate]: NQ.night },
);

/** 黒田官兵衛：赤い おわん形の かぶと「赤合子」に 高い 金の 立物、大きな 肩よろい、采配（さいはい）（ヒカリ） */
const kurodaKanbei: MonsterDesign = {
  ...kurodaKanbeiBase,
  layers: [
    // 知恵の 光の オーラ
    { x: 2, y: 5, rows: ['.C.', 'CGC', '.C.'] },
    { x: 4, y: 30, rows: ['.C.', 'CGC', '.C.'] },
    ...kurodaKanbeiBase.layers,
    // するどい まゆと 目
    { mirror: true, x: 18, y: 15, rows: ['o..', 'Foo', 'FWo'] },
    // 采配（さいはい）
    {
      x: 36,
      y: 6,
      rows: [
        '..C..',
        '.CCC.',
        'CCCCC',
        '.CCC.',
        '..T..',
        '..T..',
        '..T..',
        '..T..',
        '..T..',
        '..T..',
        '..T..',
        '..T..',
        '..T..',
        '..T..',
        '..T..',
        '..T..',
        '..T..',
        '..T..',
        '..T..',
        '..T..',
        '..T..',
        '..T..',
        '..T..',
        '..T..',
        '..T..',
        '..T..',
        '..T..',
        '..T..',
        '..T..',
        '..T..',
        '..T..',
        '..T..',
        '..T..',
      ],
    },
  ],
};

// ───────────────────────── しんか ─────────────────────────

/** カエダマオー：バリカタンの しんか。大きな どんぶりに めんの「替え玉」が 山もり。はしの つの・大きな 炎・金の もよう（ヒノ） */
const kaedamaOh: MonsterDesign = {
  size: 32,
  colors: {
    R: NQ.red,
    W: NQ.white,
    C: NQ.cream,
    Y: NQ.gold,
    A: NQ.apricot,
    V: NQ.vermilion,
    T: NQ.tan,
    p: NQ.blush,
  },
  rim: { [NQ.red]: NQ.brick, [NQ.cream]: NQ.sand },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '...............C',
        '..........C...CY',
        '..........Y...AY',
        '.........AY..VAY',
        '.........AY..VAY',
        '........VAYV.VAY',
        '........VAAV.VAA',
        '........VVACCCCC',
        '.......CCCCCWCCC',
        '.....CCCWCCCCCWC',
        '....CCCCCCWCCCCC',
        '..RRCCWCCCCCCCCC',
        '.RRRRRRRRRRRRRRR',
        '.YYYYYYYYYYYYYYY',
        '.YRYYYRYYYRYYYRY',
        '..RRRRRRRRRRRRRR',
        '..RRRRRRRooRRRRR',
        '..RRRRRRRRRoRRRR',
        '..RRRRRRRRWWRRRR',
        '...RRRRRRRWoRRRR',
        '...RRRRRRRWoRRRR',
        '...RRRpRRRRRoooo',
        '....RRRRRRRRRoWW',
        '....RRRRRRRRRRoo',
        '.....RRRRRRRRRRR',
        '......RRRRRRRRRR',
        '........RRRRRRRR',
        '.........RRRRRRR',
        '.........RRRRRRR',
      ],
    },
    // はしの つの（替え玉に さした 2 本の はし）
    { x: 3, y: 1, rows: ['T', '.T', '..T', '...T', '....T', '.....T', '......T', '.......T'] },
    {
      x: 21,
      y: 1,
      rows: ['.......T', '......T.', '.....T..', '....T...', '...T....', '..T.....', '.T......', 'T.......'],
    },
  ],
};

/** ストロベリオン：ストロベビーの しんか。へたの 葉が ライオンの たてがみに。頭に 白い いちごの 花、葉の ふさの しっぽ（モリ） */
const stroberion: MonsterDesign = {
  size: 32,
  colors: {
    R: NQ.red,
    W: NQ.white,
    Y: NQ.yellow,
    L: NQ.leaf,
    G: NQ.green,
    M: NQ.lime,
    p: NQ.blush,
  },
  rim: { [NQ.red]: NQ.brick, [NQ.leaf]: NQ.green },
  layers: [
    // 葉の たてがみ（うしろ）
    {
      mirror: true,
      rows: [
        '................',
        '.....L....L.....',
        '.....LL...LL....',
        '..L...LL..LLL...',
        '..LL..LLL.LLLL..',
        '...LLLLLLLLLLLLL',
        '.L..LLLLMLLLLLLL',
        '.LLLLLMLLLLLLLLL',
        '..LLMLLLLLLLLLLL',
        '.LLLLLLLLLLLLLLL',
        '..MLLLLLLLLLLLLL',
        '.LLLLLLLLLLLLLLL',
        '..LLLLLLLLLLLLLL',
        '.LMLLLLLLLLLLLLL',
        '..LLLLLLLLLLLLLL',
        '.LLLLLLLLLLLLLLL',
        '...LLLLLLLLLLLLL',
        '..LLLLLLLLLLLLLL',
        '....LLLLLLLLLLLL',
        '.....LL.LLLLLLLL',
      ],
    },
    // しっぽ（右だけ。先に 葉の ふさ）
    { x: 25, y: 15, rows: ['..LL.', '.LMLL', '..LLL', '...R.', '...R.', '..R..', '.R...', 'R....'] },
    // 足
    {
      mirror: true,
      y: 24,
      rows: [
        '........RRR.....',
        '.......RRRR.....',
        '.......RRRR.....',
        '.......RRRR.....',
        '......RRRRR.....',
        '......RRRRR.....',
      ],
    },
    // いちごの からだ
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
        '..........RRRRRR',
        '........RRRRRRRR',
        '.......RRRRRRRRR',
        '......RRRRRRRRRR',
        '.....RRRRRRRRRRR',
        '.....RRRRRRRRRRR',
        '....RRRRRRRRRRRR',
        '....RRRRRRRRRRWW',
        '....RRRRRRRRRRWo',
        '....RRRRRRRRRRWo',
        '....RRRRRRRRRRRR',
        '....RRRpRRRRRRRR',
        '.....RRRRRRRRRRR',
        '.....RRRRRRRRRRR',
        '.....RRRRRRRRRRR',
        '......RRRRRRRRRR',
        '......RRRRRRRRRR',
        '.......RRRRRRRRR',
        '........RRRRRRRR',
        '.........RRRRRRR',
        '...........RRRRR',
        '.............RRR',
      ],
    },
    // かお（まゆ・目・口）
    {
      mirror: true,
      y: 11,
      rows: [
        '.........o......',
        '..........oo....',
        '..........WW....',
        '..........Wo....',
        '..........Wo....',
        '................',
        '.............o..',
        '..............oW',
        '...............o',
      ],
    },
    // へた・花・じく
    {
      mirror: true,
      y: 5,
      rows: ['..........LLLLLL', '........LLLMLLLL', '.......LLL.LLL.L', '.......L....L...'],
    },
    {
      mirror: true,
      y: 1,
      rows: ['..............WW', '.............WWY', '..............WW', '...............G'],
    },
    // たね・つや
    {
      mirror: true,
      y: 10,
      rows: [
        '........Y.......',
        '',
        '.....Y..........',
        '',
        '',
        '',
        '',
        '......Y.........',
        '',
        '.........Y....Y.',
        '',
        '',
        '.........Y......',
      ],
    },
    { x: 7, y: 9, rows: ['WW', 'W.'] },
  ],
};

/** スイゴウマル：ドンコマルの しんか。大きな すげがさに 赤い ひも・柳の えだ、きりっと した まゆ、長い 舟と 白い なみ（ミズ） */
const suigoMaru: MonsterDesign = {
  size: 32,
  colors: {
    A: NQ.azure,
    S: NQ.sky,
    W: NQ.white,
    p: NQ.blush,
    E: NQ.sand,
    T: NQ.tan,
    B: NQ.brown,
    K: NQ.bark,
    L: NQ.leaf,
    // さおの ふしは こげ茶（12 色に おさめる）
    G: NQ.bark,
    R: NQ.red,
  },
  rim: { [NQ.azure]: NQ.blue, [NQ.sand]: NQ.tan, [NQ.brown]: NQ.bark },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '...............E',
        '.............EEE',
        '...........EEEEE',
        '.........EEEEEEE',
        '.......EEEEEEEEE',
        '.....EEEEEEEEEEE',
        '...EEEEEEEEEEEEE',
        '.EEEEEEEEEEEEEEE',
        '.....AAAAAAAAAAA',
        '.S..AAAAAAAAAAAA',
        '.SSSAAAAAooAAAAA',
        '.SSSSAAAAAAoAAAA',
        '..SSSAAAAAWWAAAA',
        '...SAAAAAAWoAAAA',
        '....AAAAAAWoAAAA',
        '....AAApAAAAAoAA',
        '.....AAAAAAAAAoo',
        '......AAAAAAAAAA',
        '.TTTTTTTTTTTTTTT',
        '.BBBBBBBBBBBBBBB',
        '..BBBBBBBBBBBBBB',
        '..KKKKKKKKKKKKKK',
        '...BBBBBBBBBBBBB',
        '....BBBBBBBBBBBB',
        '.....BBBBBBBBBBB',
        '.SSWSSSSWSSSSWSS',
        '.SSSSSSSSSSSSSSS',
        '..SS.SSSSS.SSSSS',
      ],
    },
    // すげがさの すじ・赤い あごひも
    {
      mirror: true,
      y: 5,
      rows: [
        '..............T.',
        '............T...',
        '..........T.....',
        '........T.......',
        '......T.........',
      ],
    },
    { mirror: true, y: 10, rows: ['....R', '....R', '.....R', '.....R', '......R', '......R'] },
    // 竹の さおと にぎる 手
    { x: 24, y: 1, rows: [...SAO] },
    { x: 23, y: 17, rows: ['AA', 'AA'] },
  ],
};

/** トビカンナ：小石原焼の まるい うつわの 子。白い「飛びかんな」の もようが ならぶ（ツチ） */
const tobikanna: MonsterDesign = {
  size: 32,
  colors: {
    T: NQ.tan,
    B: NQ.brown,
    K: NQ.bark,
    C: NQ.cream,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.tan]: NQ.brown, [NQ.brown]: NQ.bark },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '................',
        '................',
        '..........BBBBBB',
        '.......BBBBBBBBB',
        '.....TTTTTTTTTTT',
        '....TTTTTTTTTTTT',
        '...TTTTTTTTTTTTT',
        '..TTTTTTTTTTTTTT',
        '..TTTTTTTTTTTTTT',
        '..TTTTTTTTTTTTTT',
        '..TTTTTTTTTTTTTT',
        '..TTTTTTTTWWTTTT',
        '..TTTTTTTTWoTTTT',
        '..TTTTTTTTWoTTTT',
        '..TTTTpTTTTTTToT',
        '..TTTTTTTTTTTTTo',
        '..TTTTTTTTTTTTTT',
        '..TTTTTTTTTTTTTT',
        '...TTTTTTTTTTTTT',
        '...TTTTTTTTTTTTT',
        '....TTTTTTTTTTTT',
        '.....TTTTTTTTTTT',
        '.......TTTTTTTTT',
        '.........BBBBBBB',
        '........BBBBBBBB',
        '........KKKKKKKK',
        '........BBBBBBBB',
        '........BBBBBBBB',
      ],
    },
    // 飛びかんなの もよう
    {
      mirror: true,
      y: 7,
      rows: [
        '.....C..C..C..C.',
        '',
        '....C..C..C..C..',
        '',
        '...C..C..C..C..C',
        '',
        '',
        '',
        '',
        '',
        '...C..C..C..C..C',
        '',
        '....C..C..C..C..',
        '',
        '.....C..C..C..C.',
      ],
    },
    { x: 5, y: 9, rows: ['CC', 'C.'] },
  ],
};

/** ロクロカンナ：トビカンナの しんか。大きな つぼが まわる ろくろに のる。もようは 大きな うず（ツチ） */
const rokuroKanna: MonsterDesign = {
  size: 32,
  colors: {
    T: NQ.tan,
    B: NQ.brown,
    K: NQ.bark,
    C: NQ.cream,
    W: NQ.white,
    S: NQ.sand,
    p: NQ.blush,
  },
  rim: { [NQ.tan]: NQ.brown, [NQ.brown]: NQ.bark, [NQ.sand]: NQ.tan },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '..........BBBBBB',
        '.........BTTTTTT',
        '.........BBBBBBB',
        '..........TTTTTT',
        '........TTTTTTTT',
        '......TTTTTTTTTT',
        '.....TTTTTTTTTTT',
        '....TTTTTTTTTTTT',
        '...TTTTTTTTTTTTT',
        '...TTTTTTooTTTTT',
        '..TTTTTTTTTooTTT',
        '..TTTTTTTTWWTTTT',
        '..TTTTTTTTWoTTTT',
        '..TTTTTTTTWoTTTT',
        '..TTTTpTTTTTTToT',
        '..TTTTTTTTTTTTTo',
        '..TTTTTTTTTTTTTT',
        '..TTTTTTTTTTTTTT',
        '..TTTTTTTTTTTTTT',
        '...TTTTTTTTTTTTT',
        '....TTTTTTTTTTTT',
        '.....TTTTTTTTTTT',
        '.......TTTTTTTTT',
        '.........BBBBBBB',
        '........BBBBBBBB',
        '.....SSSSSSSSSSS',
        '....SSSSSSSSSSSS',
        '.....KKKKKKKKKKK',
        '.......KKKKKKKKK',
      ],
    },
    // 大きな うずの もよう
    {
      mirror: true,
      y: 12,
      rows: [
        '.....CCCC.......',
        '....C....C......',
        '...C..CCC.C.....',
        '...C.C...C.C....',
        '...C.C.CCC.C....',
        '...C.C.....C....',
        '....C.CCCCC.....',
        '.....CCC........',
      ],
    },
  ],
};

export const FUKUOKA: Readonly<Record<string, MonsterDesign>> = {
  'fukuoka-tobikanna': tobikanna,
  'fukuoka-rokuro-kanna': rokuroKanna,
  'fukuoka-midboss-banana-taisho': bananaTaisho,
  'fukuoka-midboss-banana-taisho.field': bananaTaishoField,
  'fukuoka-boss-hiraodaio': hiraodaio,
  'fukuoka-boss-hiraodaio.p0': hiraodaioP0,
  'fukuoka-lastboss-kuroda-kanbei': kurodaKanbei,
  'fukuoka-barikatan': barikatan,
  'fukuoka-kaedama-oh': kaedamaOh,
  'fukuoka-strobaby': strobaby,
  'fukuoka-stroberion': stroberion,
  'fukuoka-donkomaru': donkomaru,
  'fukuoka-suigo-maru': suigoMaru,
};
