/** 岐阜県の モンスター（手描き。docs/06 §4・§6.3〜6.5 の 規格） */
import { NQ } from '../palette';
import type { MonsterDesign } from './design';
import { BEARD_FACE, HELMET, lord } from './lastbosses';

/** フユウガキッド：ひらたく まるい 富有柿。頭に 4 まいの がく（へた）と 葉っぱ（モリ） */
const fuyugakid: MonsterDesign = {
  size: 32,
  colors: {
    O: NQ.orange,
    A: NQ.apricot,
    M: NQ.amber,
    G: NQ.green,
    L: NQ.leaf,
    B: NQ.brown,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.orange]: NQ.amber, [NQ.leaf]: NQ.green },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '................',
        '...............B',
        '...............B',
        '......GG.......B',
        '......GLG....GGB',
        '.......GLG..GLLG',
        '.....OOGLLGGLLGG',
        '...OOOOOGGGGGGGG',
        '..OAAOOOOOOGGLLG',
        '..OAOOOOOOOOGGGG',
        '.OAOOOOOOOOOOOGG',
        '.OOOOOOOOOOOOOOO',
        '.OOOOOOOOOOOOOOO',
        '.OOOOOOOOOWWOOOO',
        '.OOOOOOOOOWoOOOO',
        '.OOOOOOOOOWoOOOO',
        '.OOOOOOOpOOOOOOO',
        '.OOOOOOOOOOOOoOO',
        '.OOOOOOOOOOOOOoo',
        '.OOOOOOOOOOOOOOO',
        '..OOOOOOOOOOOOOO',
        '..OOOOOOOOOOOOOO',
        '...OOOOOOOOOOOOO',
        '....OOOOOOOOOOOO',
        '.....OOOOOOOOOOO',
        '.......OOOOOOOOO',
        '........MMM.....',
        '........MMM.....',
      ],
    },
    // 葉っぱ（じくの 右に 1 まい）
    { x: 17, y: 1, rows: ['..LLL.', '.LLLLL', 'LLLLL.', 'GLL...'] },
    // ひらたい 富有柿の みぞ（うすく 4 本）
    { x: 8, y: 12, rows: ['M', 'M', '.', '.', '.', '.', '.', '.', '.', 'M', 'M'] },
    { x: 23, y: 12, rows: ['M', 'M', '.', '.', '.', '.', '.', '.', '.', 'M', 'M'] },
  ],
};

/** カキノキドン（フユウガキッドの しんか）：大きな 柿。がくは つののように 反りかえり、じくから 実の なる えだ。きりっと まゆ（モリ） */
const kakinokiDon: MonsterDesign = {
  size: 32,
  colors: {
    O: NQ.orange,
    A: NQ.apricot,
    M: NQ.amber,
    G: NQ.green,
    L: NQ.leaf,
    B: NQ.brown,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.orange]: NQ.amber, [NQ.leaf]: NQ.green },
  layers: [
    // じくから のびる えだ（葉 2 まいと 小さな 柿）
    {
      x: 16,
      y: 1,
      rows: ['.....LLLL', '....BLLL.', '...B.....', '..BB.OOO.', '.B..OAOOO', 'B...OOOOM', '.....MMM.'],
    },
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '................',
        '................',
        '..G.............',
        '..GG............',
        '..GLG..........B',
        '...GLG......GG.B',
        '...GLLG....GLLGB',
        '....GLLGG.GLLLGG',
        '....OOGLLGGLLLGG',
        '..OOOOOGGGGGGGGG',
        '.OAAOOOOOOGGLLLG',
        '.OAOOOOOOOOGGGGG',
        '.AOOOOOOOOOOOOGG',
        '.OOOOOOOOoooOOOO',
        '.OOOOOOOOOOOoOOO',
        '.OOOOOOOOOWWOOOO',
        '.OOOOOOOOOWoOOOO',
        '.OOOOOOOOOWoOOOO',
        '.OOOOOOOpOOOOOOO',
        '.OOOOOOOOOOOoOOO',
        '.OOOOOOOOOOOOooo',
        '.OOOOOOOOOOOOOOO',
        '.OOOOOOOOOOOOOOO',
        '..OOOOOOOOOOOOOO',
        '...OOOOOOOOOOOOO',
        '....OOOOOOOOOOOO',
        '......MMMM.MMMM.',
        '......MMMM.MMMM.',
      ],
    },
    // みぞ
    { x: 7, y: 13, rows: ['M', 'M', '.', '.', '.', '.', '.', '.', '.', '.', 'M', 'M'] },
    { x: 24, y: 13, rows: ['M', 'M', '.', '.', '.', '.', '.', '.', '.', '.', 'M', 'M'] },
  ],
};

/**
 * オリベン：美濃焼の 織部の ちゃわん。左は こい 緑の うわぐすり、右は クリーム色の 地に 茶色の 梅と こうしの 絵。
 * 中の 見える ふち、高台（ツチ）
 */
const oriben: MonsterDesign = {
  size: 32,
  colors: {
    G: NQ.green,
    F: NQ.forest,
    H: NQ.leaf,
    C: NQ.beige,
    E: NQ.cream,
    B: NQ.brown,
    K: NQ.bark,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.beige]: NQ.sand, [NQ.green]: NQ.forest },
  layers: [
    {
      rows: [
        '................................',
        '................................',
        '................................',
        '................................',
        '....GGGGGGGGGGGGGGGGGGGGGGCC....',
        '...GGEEEEEEEEEEEEEEEEEEEEEECC...',
        '...GGEEEEEEEFFFFFFFFEEEEEEECC...',
        '...GGGEEEEEEEEEEEEEEEEEEEECCC...',
        '...GGGGGGGGGGGGGGGGGGGGCCCCCC...',
        '...GHGGGGGGGGGGGGGGGGGCCCCCCC...',
        '...GHGGGGGGGGGGGGGGGGCCCCBCCC...',
        '...GGGGGGGGGGGGGGGGGCCCCBBBCC...',
        '...GGGGGGGGGGGGGGGGCCCCCCBCCC...',
        '...GGGGGGGWWGGGGGCCCCWWCCCCCC...',
        '...GGGGGGGWoGGGGCCCCCoWCCCCCC...',
        '...GGGGGGGWoGGGCCCCCCoWCCCCCC...',
        '...GGGGGGpGGGCCCCCCCCCpCCCCCC...',
        '...GGGGGGGGCCCCooCCCCCCCCCCCC...',
        '....GGGGGGCCCCCCCCCCCCCCCCCC....',
        '....GGGGGCCCCCCCCCCCCBBBBBBC....',
        '....GGGGCCCCCCCCCCCCCBCBCBCC....',
        '.....GGCCCCCCCCCCCCCCBBBBBBC....',
        '.....GCCCBCCCCCCCCCCCBCBCBC.....',
        '......CCCCBCCCCCCCCCCBBBBBB.....',
        '.......CCCCCCCCCCCCCCCCCCC......',
        '........CCCCCCCCCCCCCCCCC.......',
        '..........CCCCCCCCCCCC..........',
        '...........KKKKKKKKKK...........',
        '...........KKKKKKKKKK...........',
      ],
    },
    // 手（左右に 小さく）
    { x: 1, y: 14, rows: ['.C', 'CC', 'CC'] },
    { x: 29, y: 14, rows: ['C.', 'CC', 'CC'] },
  ],
};

/**
 * オリベムシャ（オリベンの しんか）：ふせた 織部の ちゃわんの かぶと（てっぺんに 高台）、まるもようの よろい、
 * 左手に 織部の まるい 大ざら、右手に もようを かく 大きな 筆（ツチ）
 */
const oribeMusha: MonsterDesign = {
  size: 32,
  colors: {
    G: NQ.green,
    F: NQ.forest,
    H: NQ.leaf,
    C: NQ.beige,
    B: NQ.brown,
    K: NQ.bark,
    S: NQ.sand,
    E: NQ.cream,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.beige]: NQ.sand, [NQ.green]: NQ.forest },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '............KKKK',
        '............KKKK',
        '.........GGGGGGG',
        '.......GGGGGGGGG',
        '......GHGGGGGGGG',
        '.....GHGGGGGGGGG',
        '.....GHGGGGGGGGG',
        '....GGGGGGGGGGGG',
        '...GGGGGGGGGGGGG',
        '...GGGGCGGGGCGGG',
        '....GGCCCGGCCCGC',
        '.....GCCoooCCCCC',
        '.....CCCWWWCCCCC',
        '.....CCCWWoCCCCC',
        '.....CCCWWoCCCCC',
        '.....CCpCCCCCCCC',
        '......CCCCCCoooo',
        '...GGGGBBBBBBBBB',
        '..GGGGGGCCCCCCCC',
        '..GHGGGGCBBBCCBB',
        '..GGGGGGCBCBCCBC',
        '...GGGGGCBBBCCBB',
        '.....GGGCCCCCCCC',
        '.......GBBBBBBBB',
        '........KKKKKKKK',
        '........CCCC..CC',
        '........CCCC..CC',
        '.......KKKKK..KK',
      ],
    },
    // 左手：織部の まるい 大ざら（たて）
    {
      x: 1,
      y: 18,
      rows: ['..GGGG..', '.GGEEGG.', 'GGEBBEGG', 'GEBEEBEG', 'GEBEEBEG', 'GGEBBEGG', '.GGEEGG.', '..GGGG..'],
    },
    // 右手：もようを かく 大きな 筆（ほさきは 鉄の 茶色）
    {
      x: 25,
      y: 4,
      rows: [
        '..B..',
        '.BBB.',
        '.BBB.',
        'BBBBB',
        '.KKK.',
        '..S..',
        '..S..',
        '..S..',
        '..S..',
        '..S..',
        '.CC..',
        'CCC..',
      ],
    },
  ],
};

/** ウカイドリ：長良川の 鵜飼の 鵜。黒い からだ、白い ほお、黄色い はだの かぎの くちばしで あゆを くわえる。首に わらの なわ（ミズ） */
const ukaidori: MonsterDesign = {
  size: 32,
  colors: {
    n: NQ.slate,
    N: NQ.night,
    g: NQ.gray,
    T: NQ.teal,
    W: NQ.white,
    Y: NQ.yellow,
    S: NQ.silver,
    c: NQ.cloud,
    s: NQ.sand,
    p: NQ.blush,
  },
  rim: { [NQ.slate]: NQ.night, [NQ.silver]: NQ.gray },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '................',
        '.............W..',
        '............nWn.',
        '..........nnnnnn',
        '........nnnnnnnn',
        '.......nnnnnnnnn',
        '......nnnnnnnnnn',
        '......ngnnWWnnnn',
        '......ngnnWonnnn',
        '......nnnnWonnYY',
        '......WWWWnnnYYS',
        '......WWWWWnnYSS',
        '.......WWWWnnnSS',
        '.......ssssssnnn',
        '.....nnnnnnnnsss',
        '....nnnnnnnnnnnn',
        '...NnnnnnnnngggN',
        '...NnnnnnnnggggN',
        '..NNnnnnnnnggggg',
        '..NNnnnnnnnggggg',
        '..NNnnnnnnnggggg',
        '..NNnnnnnnnggggg',
        '...NNnnnnnnggggg',
        '....NNnnnnnngggg',
        '......nnnnnnnnnn',
        '.........NN..NN.',
        '........NNNN.NNN',
        '.......NNNNN....',
      ],
    },
    // くちばしの 先（かぎに まがる）
    { x: 15, y: 15, rows: ['SS', 'So'] },
    // くわえた あゆ（右へ。背は 青みどり、よこに 黄色い 点）
    {
      x: 16,
      y: 12,
      rows: ['..TTTTTTTTT..', '.SSSSSSSSSSS.T', 'SSYSSSSSSSSSTT', '.ccccccccccc.T', '..cccccccc....'],
    },
    { x: 17, y: 13, rows: ['o'] },
    // ほっぺ
    { x: 9, y: 12, rows: ['p'] },
    { x: 22, y: 12, rows: ['p'] },
  ],
};

/** ウショウドリ（ウカイドリの しんか）：鵜匠の 黒い ずきんと わらの こしみの。右の つばさで かがり火を かかげる（ミズ） */
const ushouDori: MonsterDesign = {
  size: 32,
  colors: {
    n: NQ.slate,
    N: NQ.night,
    W: NQ.white,
    Y: NQ.yellow,
    S: NQ.silver,
    s: NQ.sand,
    t: NQ.tan,
    V: NQ.vermilion,
    G: NQ.gold,
    p: NQ.blush,
    g: NQ.gray,
  },
  rim: { [NQ.slate]: NQ.night, [NQ.sand]: NQ.tan },
  layers: [
    // かがり火（鉄の かごに 火。右の つばさで 竿を もつ）
    {
      x: 23,
      y: 1,
      rows: [
        '..Y.Y..',
        '.YGYGY.',
        'VYGGGYV',
        'VVGGGVV',
        'ooooooo',
        '.o.o.o.',
        '..ooo..',
        '...t...',
        '...t...',
        '...t...',
        '...t...',
        '...t...',
        '...t...',
        '...t...',
        '...t...',
        '...t...',
        '...t...',
        '...t...',
        '...t...',
        '...t...',
        '...t...',
      ],
    },
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '............NNN.',
        '..........NNNNNN',
        '.........NNNNNNN',
        '........NNNNNNNN',
        '........NNNNNNNN',
        '.......nnnnnnnnn',
        '......nnnnnnnnnn',
        '......nnooonnnnn',
        '......nnnWWnnnnn',
        '......nnnWonnnYY',
        '......WWnWonnYYS',
        '......WWWWnnnYSS',
        '.......WWWWnnnSS',
        '.....nnnnnnnnnnS',
        '...nnnnnnnnnnnnn',
        '..nnnnnnnnnngggg',
        '.nnnnnnnnnnggggg',
        '.nnnnnnnnnnggggg',
        '..nnnnnnnnnggggg',
        '...ssssssssssss',
        '...stssstssstss',
        '..sstssstssstss',
        '..stssstssstsss',
        '.sstssstssstssst',
        '.stssstssstssst.',
        '.........NN..NN.',
        '........NNNN.NNN',
        '.......NNNNN....',
      ],
    },
    // くちばしの 先
    { x: 15, y: 15, rows: ['SS', 'oo'] },
    // ずきんの おりかえし（うしろへ たなびく）
    { x: 5, y: 4, rows: ['NNN.', '.NNN', '..NN'] },
    // 右の つばさ（かがり火の 竿を にぎる）
    { x: 22, y: 12, rows: ['....nn', '...nnn', '..nnn.', '.nnn..', 'nnn...'] },
    { x: 9, y: 13, rows: ['p'] },
    { x: 22, y: 13, rows: ['p'] },
  ],
};

const washigamin: MonsterDesign = {
  size: 32,
  colors: {
    W: NQ.paper,
    C: NQ.cloud,
    R: NQ.red,
    M: NQ.mint,
    p: NQ.blush,
  },
  rim: { [NQ.paper]: NQ.cloud, [NQ.cloud]: NQ.silver },
  layers: [
    {
      rows: [
        '',
        '',
        '',
        '',
        '',
        '.....M........CCCCC........M',
        '....MMM....CCCCCCCCCCC....MMM',
        '.....M...CCCCCCCCCCCCCCC...M',
        '......CCCCCCCCCCCCCCCCCCCCC',
        '...CCCCCCCCCCCCCCCCCCCCCCCCCCC',
        '...WWWCCCCCCCCCCCCCCCCCCCCCWW',
        '...WWWWWWWCCCCCCCCCCCCCWWWWWW',
        '...WWWWWWWWWWWCCCCCWWWWWWWWWW',
        '...WWWWWWWWWWWWWWWWWWWWWWWWWW',
        '...WWWWWWWWWWWWWWWWWWWWWWWWWW',
        '...WWWWWWWWWWWWWWWWWWWWWWWWWW',
        '...WWWWWWWWWWWWWWWWWWWWWWWWWW',
        '...WWWWWWWWWoWWWWWWoWWWWWWWWW',
        '...WWWWWCWWWoWWWWWWoWWWCCWWWW',
        '...WWWCCCWWWWWWWWWWWWWWCCCCWW',
        '...CCCCCCpWWWWoWWWoWWWpCCCCCC',
        '...CCCCCCWWWWWWoooWWWWWCCCCCC',
        '...CCCCCCWWWWWWWWWWWWWWCCCCCC',
        '...CCCCCCWWWWWWWRWWWWWWCCCCCC',
        '...CCCCCCWWWWWWRRRWWWWWCCCCCC',
        '...CCCCCCWWWWWRRRRRWWWWCCCCCC',
        '...CCCCCCCWWWWWRRRWWWWWCCCCCC',
        '...WWWWWWWWWWWWWRWWWWWWWWWWWWW',
        '..........WWWWWWWWWWWWW',
        '..............CCCCC',
        '..............CCCCC',
        '',
      ],
    },
  ],
};

const kamioriDori: MonsterDesign = {
  size: 32,
  colors: {
    W: NQ.paper,
    C: NQ.cloud,
    R: NQ.red,
    Y: NQ.gold,
    M: NQ.mint,
    p: NQ.blush,
  },
  rim: { [NQ.paper]: NQ.cloud, [NQ.cloud]: NQ.silver },
  layers: [
    {
      rows: [
        '',
        '',
        '',
        '',
        '................C',
        '...............WCW',
        '....M..........CCC..........M',
        '...MMM........WCCCW........MMM',
        '....M.......WWCCCCCWW.......M',
        '..........WWWWCCCCCWWWW',
        '.......WWWWWWCCCCCCCWWWWWW',
        '.....WWWWWWWCCCCCCCCCWWWWWWW',
        '..WWWWWWWWWWWoWCCCWoWWWWWWWWWW',
        '..WWWWWWWWCWWoWCCCWoWWCWWWWWWW',
        '..WWWWWWWCWWWWWWWWWWWWWCWWWWWW',
        '..WWWWWCCWWpWWWWWWWWpWWWCCWWWW',
        '..WWWCCWWWWWWWWYYYWWWWWWWWCCWW',
        '..WCCWWWW....WYYYYYW....WWWWCC',
        '..C..........WWWWWWW..........C',
        '.............WWWWWWW',
        '..............WWWWW',
        '..............WWWWW',
        '...............WRW',
        '......M........RRR........M',
        '.....MMM......RRRRR......MMM',
        '......M......WCRRRCW......M',
        '.............CWWRWWC',
        '............CWWWWWWWC',
        '...........CWWWWWWWWWC',
        '..............WWWWW',
        '',
        '',
      ],
    },
  ],
};

const karankoron: MonsterDesign = {
  size: 40,
  colors: {
    D: NQ.denim,
    N: NQ.navy,
    W: NQ.white,
    R: NQ.red,
    K: NQ.skinMid,
    T: NQ.tan,
    B: NQ.brown,
    G: NQ.gold,
    Q: NQ.ochre,
    M: NQ.mint,
  },
  rim: { [NQ.denim]: NQ.navy, [NQ.tan]: NQ.brown, [NQ.skinMid]: NQ.skinDark },
  rimDepth: 2,
  layers: [
    {
      rows: [
        '',
        '',
        '................G.G.G.G.G',
        '................GGGGGGGGG',
        '................GGGRRGGGG',
        '................GGGRRGGGG',
        '................QQQQQQQQQ',
        '...........TTBBBBBBBBBBBBBBBTT',
        '........TTTBBBBBBBBBBBBBBBBBBBTTT',
        '...D...TTTBBBBBBBBBBBBBBBBBBBBBTTT',
        '...D..TTTTTBBBBBBBBBBBBBBBBBBBTTTTT..D',
        '...DD..TTTTTTBBBBBBBBBBBBBBBTTTTTT..DD',
        '..DDDW..TTTTTTTTTTTTBTTTTTTTTTTTT..WDDD',
        '..DDWDD....TTTTTTTTTTTTTTTTTTT....DDWDD',
        '.NDDDDDD.....oooooooTooooooo.....DDDDDD',
        '.NDDDDDDD.....WWWWWKKKWWWWW.....DDDDDDD',
        '.NNDDDDDWD....ooWWWKKKWWWoo....DWDDDDDN',
        '.NNNDDDWDDD...ooWWWKKKWWWoo...DDDWDDDNN',
        '.NNNNDDDDDDD.KooWWWKKKWWWooK.DDDDDDDNNN',
        '..NNNDDDDDDDD.KKKKKKKKKKKKK.DDDDDDDDNNN',
        '...NNNDDDDDDWDKKKKKKKKKKKKKDWDDDDDDNNN',
        '....NNNDDDDWDDKKKKoooooKKKKDDWDDDDNNN',
        '....NNNNDDDDDDDKKKKKKKKKKKDDDDDDDNNNN',
        '.....NNNDDDDDDDDWKKKKKKKDDDDDDDDDNNN',
        '......NNNDDDDDDDDDDDKDDDDDDDDDDDNNN',
        '.......NNNDDDDDDDDDDDDDDDDDDDDDNNN',
        '.......NNNNDDDDDDDDDDDDWDDDDDDNNNN',
        '........NNNDDDDDDDDDDDDDDDDDDNNNN',
        '.........NND.DDDDDDDDDDDDDDD.DNN',
        '....M.....N.RRRRRRRRRRRRRRRRR.N....M',
        '...MMM......RRRRRRRRRRRRRRRRR.....MMM',
        '....M.......RRRRRRRRRRRRRRRRR......M',
        '............RRWRRRRRRRRRRRRRR',
        '............DDDDDDDDDDDDDDDDD',
        '........M...DDDDDDDWDDDDDDWDD..M',
        '.......MMM..DDDDDDDDDDDDDDDDD.MMM',
        '........M......................M',
        '.............TTTTTT...TTTTTT',
        '.............TTTTTT...TTTTTT',
        '',
      ],
    },
  ],
};

const karankoronField: MonsterDesign = {
  size: 32,
  colors: {
    D: NQ.denim,
    N: NQ.navy,
    W: NQ.white,
    R: NQ.red,
    K: NQ.skinMid,
    T: NQ.tan,
    B: NQ.brown,
    G: NQ.gold,
    Q: NQ.ochre,
  },
  rim: { [NQ.denim]: NQ.navy, [NQ.tan]: NQ.brown },
  rimDepth: 1,
  layers: [
    {
      rows: [
        '',
        '',
        '..............G.G.G',
        '.............GGGGGGG',
        '.............GGRRGGG',
        '.............GGRRGGG',
        '........TTBBBQQQQQQQBBBTT',
        '..D...TTBBBBBBBBBBBBBBBBBTT',
        '..D..TTTTTBBBBBBBBBBBBBTTTTT..D',
        '..DD..TTTTTTTTTTBTTTTTTTTTT..DD',
        '.DDWW...TTTTTTTTTTTTTTTTT...WWD',
        '.NDDDD....ooooooToooooo....DDDD',
        '.NDDDDD....WWWWKKKWWWW....DDDDD',
        '.NNDDDWD...ooWWKKKWWoo...DWDDDN',
        '.NNNDDWDD.KooWWKKKWWooK.DDWDDNN',
        '.NNNDDDDDD.KKKKKKKKKKK.DDDDDDNN',
        '..NNNDDDDDWKKKKKKKKKKKWDDDDDNNN',
        '...NNNDDDWDDKKoooooKKDDWDDDNNN',
        '....NNNDDDDDDKKKKKKKDDDDDDNNN',
        '....NNNDDDDDDDDDKDDDDDDDDDNNN',
        '.....NNNDDDDDDDDDDDDDDDDDNNN',
        '......NNNDDDDDDDDDWDDDDDNNN',
        '.......NND.DDDDDDDDDDD.NNN',
        '........N.RRRRRRRRRRRRR.N',
        '..........RRRRRRRRRRRRR',
        '..........RRRRRRRRRRRRR',
        '..........RWRRRRRRRRRRR',
        '..........DDDDDWDDDDDWD',
        '..........DDDDDDDDDDDDD',
        '',
        '..........TTTTT...TTTTT',
        '',
      ],
    },
  ],
};

const gasshoDaiou: MonsterDesign = {
  size: 48,
  colors: {
    T: NQ.tan,
    S: NQ.sand,
    B: NQ.brown,
    K: NQ.bark,
    E: NQ.beige,
    G: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
    g: NQ.gray,
    s: NQ.slate,
  },
  rim: { [NQ.tan]: NQ.brown, [NQ.beige]: NQ.sand, [NQ.gray]: NQ.slate },
  rimDepth: 2,
  layers: [
    {
      rows: [
        '',
        '',
        '....................G.G.G.G.G',
        '....................GGGGGGGGG',
        '....................GGGRRGGGG',
        '....................GGGRRGGGG',
        '....................QQQQQQQQQ',
        '......................TSSST',
        '......................SSSSS',
        '.....................TSSSSST',
        '....................BBBBBBBBB',
        '....................TSSSSSSST',
        '...................TSSSSSSSSST',
        '...................TTTTTTTTTTT',
        '..................BBBBBBBBBBBBB',
        '.................TTTTTTTTTTTTTTT',
        '.................TTTTTTTTTTTTTTT.....K',
        '...........KKK..TTTTTTTTTTTTTTTTT..KK',
        '...........KKKKKKBBBBBBBBBBBBBBBKKKKK',
        '...........KKKKKKKKKTTTTTTTTTKKKKKKKK',
        '..............TKKKKKKKTTTTKKKKKKKKT',
        '.............KKKKKKKKKTTTTKKKKKKKKKK',
        '.............KooooooKBBBBBBBKooooooK',
        '.............KooooooKTTTTTTTKooooooK',
        '...........BTKEEEEEEKTTTTTTTKEEEEEEKT',
        '...........BBKEEEEEEKTTTTTTTKEEEEEEKBB',
        '..........BBBKEEEEEEKBBBBBBBKEEEEEEKBBB',
        '.........BBBBKEEEEEEKTTTTTTTKEEEEEEKBBBB',
        '........BBBBBKKKKKKKKTTTTTTTKKKKKKKKBBBBB',
        '.......BBBBBTTTTTTTTTTTTTTTTTTTTTTTTTBBBBB',
        '......BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
        '.....BBBBBTTTTTTTKKKKKKKKKKKKKKKTTTTTTTBBBBB',
        '....BBBBBTTTTTTTTKEEKEEKEEKEEKEKTTTTTTTTBBBBB',
        '..BBBBBBBBTTTTTTTKEEKEEKEEKEEKEKTTTTTTTBBBBBBBB',
        '..BBBBBBBBBBBBBBBKKKKKKKKKKKKKKKBBBBBBBBBBBBBBB',
        '..BEEEEEEBTTTTTTTKEEKEEKEEKEEKEKTTTTTTTBEEEEEEB',
        '..BEEEEEEBTTTTTTTKEEKEEKEEKEEKEKTTTTTTTBEEEEEEB',
        '..BBBBBBBBTTTTTTTKKKKKKKKKKKKKKKTTTTTTTBBBBBBBB',
        '..BBBBBBggsgggggsgggggsgggggsgggggsggggggBBBBBB',
        '..BBBBBBggsgggggsgggggsgggggsgggggsggggggBBBBBB',
        '..KKKKKKggsgggggsgggggsgggggsgggggsggggggKKKKKK',
        '..KKKKKKggsgggggsgggggsgggggsgggggsggggggKKKKKK',
        '..KBBBBBggsgggggsgggggsgggggsgggggsggggggBBBBBK',
        '..KBBBBBggsgggggsgggggsgggggsgggggsggggggBBBBBK',
        '..KKKKKKggsgggggsgggggsgggggsgggggsggggggKKKKKK',
        '..KKKKKKKK..sssssssss.......sssssssss..KKKKKKKK',
        '............sssssssss.......sssssssss',
        '',
      ],
    },
  ],
};

const gasshoDaiouP0: MonsterDesign = {
  size: 48,
  colors: {
    T: NQ.tan,
    S: NQ.sand,
    B: NQ.brown,
    K: NQ.bark,
    E: NQ.beige,
    G: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
    g: NQ.gray,
    s: NQ.slate,
    W: NQ.white,
    Y: NQ.yellow,
    C: NQ.cream,
  },
  rim: { [NQ.tan]: NQ.brown, [NQ.beige]: NQ.sand, [NQ.gray]: NQ.slate, [NQ.white]: NQ.cloud },
  rimDepth: 2,
  layers: [
    {
      rows: [
        '',
        '',
        '....................G.G.G.G.G',
        '....................GGGGGGGGG',
        '....................GGGRRGGGG',
        '....................GGGRRGGGG',
        '....................QQQQQQQQQ',
        '......................TSSST',
        '.....................WWWSWWW',
        '.....................WWWSWWW',
        '....................WWWBBBWWW',
        '....................WWWSSSWWW',
        '...................WWWSSSSSWWW',
        '..................WWWTTTTTTTWWW',
        '.....C............WWWBBBBBBBWWW...........C',
        '....CCC..........WWWTTTTTTTTTWWW.........CCC',
        '.....C...........WWWTTTTTTTTTWWW.....K....C',
        '...........KKK..WWWTTTTTTTTTTTWWW..KK',
        '...........KKKKWWWBBBBBBBBBBBBBWWWKKK',
        '...........KKKKWWWKKTTTTTTTTTKKWWWKKK',
        '..............WWWKKKKKTTTTKKKKKKWWW',
        '.............KWWWKKKKKTTTTKKKKKKWWWK',
        '.............WYYYYYYKBBBBBBBKYYYYYYW',
        '............WWYYYYYYKTTTTTTTKYYYYYYWW',
        '...........BWWYYYYYYKTTTTTTTKYYYYYYWW',
        '.......C...WWWYYYYYYKTTTTTTTKYYYYYYWWW..C',
        '......CCC.BWWWYYYYYYKBBBBBBBKYYYYYYWWWBCCC',
        '.......C.BWWWKYYYYYYKTTTTTTTKYYYYYYKWWWBC',
        '........BWWWBKKKKKKKKTTTTTTTKKKKKKKKBWWWB',
        '.......BBWWWTTTTTTTTTTTTTTTTTTTTTTTTTWWWBB',
        '......BBWWWBBBBBBBBBBBBBBBBBBBBBBBBBBBWWWBB',
        '.....BBBWWWTTTTTTKKKKKKKKKKKKKKKTTTTTTWWWBBB',
        '....BBBWWWTTTTTTTKYYoYYoYYoYYoYKTTTTTTTWWWBBB',
        '..BBBBWWWBTTTTTTTKYYoYYoYYoYYoYKTTTTTTTBWWWBBBB',
        '..BBBBWWWBBBBBBBBKoooooooooooooKBBBBBBBBWWWBBBB',
        '..BEEWWWEBTTTTTTTKYYoYYoYYoYYoYKTTTTTTTBEWWWEEB',
        '..BEEWWWEBTTTTTTTKYYoYYoYYoYYoYKTTTTTTTBEWWWEEB',
        '..BBWWWBBBTTTTTTTKKKKKKKKKKKKKKKTTTTTTTBBBWWWBB',
        '..BBBBBBggWgggggWgggggsgggggsgggWgsgggWggBBBBBB',
        '..BBBBBBggWgggggWgggggsgggggsgggWgsgggWggBBBBBB',
        '..KKKKKKggWgggggWgggggsgggggsgggWgsgggWggKKKKKK',
        '..KKKKKKggsgggggsgggggsgggggsgggggsggggggKKKKKK',
        '..KBBBBBggsgggggsgggggsgggggsgggggsggggggBBBBBK',
        '..KBBBBBggsgggggsgggggsgggggsgggggsggggggBBBBBK',
        '..KKKKKKggsgggggsgggggsgggggsgggggsggggggKKKKKK',
        '..KKKKKKKK..sssssssss.......sssssssss..KKKKKKKK',
        '............sssssssss.......sssssssss',
        '',
      ],
    },
  ],
};

const saitoDosan = lord(
  [
    '......................GG',
    '....................AAGG',
    '..................AAAYGG',
    '.................AYYYAGG',
    '................YYAAAAGG',
    '..............YYAAAAAAGG',
    '................AAAAAAGG',
    '....................NNGG',
    ...HELMET,
    ...BEARD_FACE,
  ],
  {
    N: NQ.night,
    L: NQ.slate,
    G: NQ.gold,
    Y: NQ.cream,
    R: NQ.red,
    K: NQ.forest,
    S: NQ.green,
    T: NQ.night,
    H: NQ.slate,
    C: NQ.bark,
    M: NQ.silver,
    A: NQ.azure,
  },
  { [NQ.forest]: NQ.ink, [NQ.green]: NQ.forest },
);

export const GIFU: Readonly<Record<string, MonsterDesign>> = {
  'gifu-fuyugakid': fuyugakid,
  'gifu-kakinoki-don': kakinokiDon,
  'gifu-oriben': oriben,
  'gifu-oribe-musha': oribeMusha,
  'gifu-ukaidori': ukaidori,
  'gifu-ushou-dori': ushouDori,
  'gifu-washigamin': washigamin,
  'gifu-kamiori-dori': kamioriDori,
  'gifu-midboss-karankoron': karankoron,
  'gifu-midboss-karankoron.field': karankoronField,
  'gifu-boss-gassho-daiou': gasshoDaiou,
  'gifu-boss-gassho-daiou.p0': gasshoDaiouP0,
  'gifu-lastboss-saito-dosan': saitoDosan,
};
