/** 茨城県の モンスター（手描き。docs/06 §4・§6.3〜6.5 の 規格） */
import { NQ } from '../palette';
import type { MonsterDesign } from './design';
import { BEARD_FACE, HELMET, lord } from './lastbosses';

/** ネモフィン：青い ネモフィラの 花を かぶった まるい 小鳥。花びらの つばさで ふわりと とぶ（カゼ） */
const nemofin: MonsterDesign = {
  size: 32,
  colors: {
    A: NQ.azure,
    S: NQ.sky,
    I: NQ.ice,
    W: NQ.white,
    C: NQ.cloud,
    Y: NQ.gold,
    Q: NQ.ochre,
    p: NQ.blush,
  },
  rim: { [NQ.azure]: NQ.blue, [NQ.white]: NQ.cloud, [NQ.sky]: NQ.azure },
  rimDepth: 1,
  layers: [
    // 本体
    {
      x: 5,
      y: 3,
      rows: [
        '.........oooo',
        '........oAAAAo',
        '.....oooAASSAAooo',
        '....oAAAAASSAAAAAo',
        '...oASSAAAWWAAASSAo',
        '..oAASSSAWYYWASSSAAo',
        '...oASSAWWYYWWASSAo',
        '....oAAAAWYYWAAAAo',
        '....oAASSAWWASSAAo',
        '....oASSSSAASSSSAo..o',
        '.oo..oASSAAAASSAo.ooAo',
        'oAAoo.oAAooooAAoooAAo',
        'oAAAAooooWWWWoooAASAo',
        'oAASAAoWWWWWWWWoASAAo',
        'oAASSSoWWWWWWWWoSSAAo',
        'oAASSoWWWWWWWWWWoSAAo',
        'oAASSoWWWWWWWWWWoSAAo',
        'oAAAoWWoWIIIIWoWWoAAo',
        '.ooopWWoIIIIIIoWWpoo',
        '....oWWWIIooIIWWWo',
        '....oWWWIIIIIIWWWo',
        '....oWWIIIIIIIIWWo',
        '.....oWWIIIIIIWWo',
        '.....oWWIIIIIIWWo',
        '......oWIIIIIIWo',
        '......oWWIIIIWWo',
        '.....oQooWWWWooQo',
        '.....oQQQooooQQQo',
      ],
    },
  ],
};

/** アオゾラヒメ（ネモフィンの しんか）：大きな 花びらの つばさと 花の かんむり。空の 色の かぜを おこす（カゼ） */
const aozoraHime: MonsterDesign = {
  size: 32,
  colors: {
    A: NQ.azure,
    S: NQ.sky,
    I: NQ.ice,
    W: NQ.white,
    C: NQ.cloud,
    Y: NQ.gold,
    Q: NQ.ochre,
    p: NQ.blush,
  },
  rim: { [NQ.azure]: NQ.blue, [NQ.white]: NQ.cloud, [NQ.sky]: NQ.azure },
  rimDepth: 1,
  layers: [
    // 本体
    {
      x: 1,
      y: 1,
      rows: [
        '............ooAAoo',
        '...........oAAAAAAo',
        '........oo.oAASSAAo.oo',
        '.......oAAooAASSAAooAAo',
        '......oAAAAAAAAAAAAAAAAo',
        '.....oAASSSAooWWooASSSAAo',
        '.....oAASSSAoWYYWoASSSAAo',
        '......oAAAAAWWYYWWAAAAAo....o',
        '.o.....oAAAAAWYYWAAAAAo....oAo',
        'oAoo....oAAAAAWWAAAAAo...ooAo',
        'oACAoo.oAASSSAAAASSSAAoooAAAo',
        'oAAAAAooAASSSAAAASSSAAoAAAAAo',
        'oAAAAAAAoAASAAooAASAAoAAASACo',
        'oAAASSAAAoAAAooooAAAoAASSAAAo',
        'oAAASSSSAAoooWWWWoooASSSSAAAo',
        'oAAASSSSSSoWWWWWWWWoSSSSSAAAo',
        'oAAASSSSSoWWWWWWWWWWoSSSSAAAo',
        'oAAASSSSoWWWWWWWWWWWWoSSSAAAo',
        'oAAASSSSoWWWWIIIIWWWWoSSSAAAo',
        'oAAAAASSoWWoIIIIIIoWWoSAAAAAo',
        '.ooooAAopWWoIIIIIIoWWpoAoooo',
        '.....oooWWWIIIooIIIWWWoo',
        '........oWWIIIIIIIIWWo',
        '........oWWIIIIIIIIWWo',
        '...C....oWWIIIIIIIIWWo',
        '........oWWIIIIIIIIWWo',
        '.........oWWIIIIIIWWo.....C',
        '..........oWIIIIIIWo',
        '.........oQoWIIIIWoQo',
        '.........oQQooooooQQo',
      ],
    },
  ],
};

// ───────────────────────── 中ボス ─────────────────────────

/** ハルツゲドリ（中ボス）：つばさを いっぱいに ひろげた 大きな ウグイス。金の 王冠と するどい くちばし、かぎづめで 梅の 枝を つかむ（カゼ） */
const harutsugeDori: MonsterDesign = {
  size: 40,
  colors: {
    L: NQ.leaf,
    M: NQ.lime,
    G: NQ.green,
    S: NQ.sprout,
    W: NQ.white,
    Q: NQ.ochre,
    Y: NQ.gold,
    R: NQ.red,
    p: NQ.blush,
    K: NQ.bark,
    T: NQ.brown,
  },
  rim: { [NQ.leaf]: NQ.green, [NQ.lime]: NQ.leaf, [NQ.sprout]: NQ.lime, [NQ.brown]: NQ.bark },
  rimDepth: 2,
  layers: [
    // 本体（つばさ・王冠・するどい 目・かぎづめ）
    {
      x: 1,
      y: 1,
      rows: [
        '.............oGGGGGoGGGo',
        '.............oGGGGGoGGGo',
        '.............oGGGGGoGGGo',
        '.............oGGGRRGGGGo',
        '.............oGGGRRGGGGo',
        'oo...........oQQQQQQQQQo...........o',
        'LLoo..........ooooooooo..........ooLo',
        'LLpLoo......ooWWWLLLWWWoo......ooLpLo',
        'LpppLLoo...oWWLLLLLLLLLWWo...ooLLpppo',
        'ppYppLLLo...oLLLLLLLLLLLo...oLLLppYpp',
        'LpppLLLLLoo.oWWLLLLLLLWWo.ooLLLLLpppo',
        'LLpMLLLLLLLoLWWWoLLLoWWWLoLLLLLLLMpLo',
        'LLLMMMLLLLLLoLLWoLLLoWLLoLLLLLLMMMLLo',
        'LLLMMMMMLLGLoLLLQQYQQLLLoLGLLMMMMMLLo',
        'LLLMMMMMMMGLoLLLQQYQQLLLoLGMMMMMMMLLo',
        'LLLMMMMGMGMMGoLLLQYQLLLoGMMGMGMMMMLLo',
        'LLLMMMMGMGMMGMoLLQQQLLoMGMMGMGMMpMLLo',
        'LLLMGMGMMGMMGMooooQooooMGMMGMMGMGMLLo',
        'LLLGMMGMMGMGMoLLLoQoLLLoMGMGMMGMMGLLo',
        'LLLGMGMMGMMGoLLLLoQoLLLLoGMMGMMGMGLLo',
        'LpGMMGMMGMMoLLLLLLoLLLLLLoMMGMMGMMGLLo',
        'oLGLMGMMGMMoLLLLSSSSSLLLLoMMGMMGMLGLo',
        'oGLLGMMMGMMoLLLLSSSSSLLLLoMMGMMMGLLGo',
        '.ooLGLMGMMGoLLLSSSSSSSLLLoGMMGMLGLop',
        '...oLLLGMMoLLLLSSSSSSSLLLLoMMGLLLo',
        '....oLLLMMGoLLLSSSSSSSLLLoGMMLLLo',
        '....poLLLMMoLLSSSSSSSSSLLoMMLLLo',
        '......oLLLLoLLLSSSSSSSLLLoLLLLo',
        '.......oLLLoLLLSSSSSSSLLLoLLLo',
        '.....p..oLLooLLSSSSSSSLLooLLo..p',
        '....ppp..oo.ooLLSSSSSLLoo.oo..ppp',
        '...ppYpp....oQoLSSSSSLoQo....ppYpp',
        '.ooopppoooooYQYoooSoooYQYooooopppoooo',
        'oKKKKpKKKKKoYoYoYoooYoYoYoKKKKKpKKKKKo',
        'oKKKKKKKKKKoYoYoYoKoYoYoYoKKKKKKKKKKKo',
        '.oTTTTTTTTTToToToTTToToToTTTTTTTTTTTo',
        '..oooooooooooooooooooooooooooooooooo',
      ],
    },
  ],
};

/** ハルツゲドリ（フィールドに 立つ 32×32） */
const harutsugeDoriField: MonsterDesign = {
  size: 32,
  colors: {
    L: NQ.leaf,
    M: NQ.lime,
    G: NQ.green,
    S: NQ.sprout,
    W: NQ.white,
    Q: NQ.ochre,
    Y: NQ.gold,
    R: NQ.red,
    p: NQ.blush,
    K: NQ.bark,
    T: NQ.brown,
  },
  rim: { [NQ.leaf]: NQ.green, [NQ.lime]: NQ.leaf, [NQ.sprout]: NQ.lime },
  rimDepth: 1,
  layers: [
    // 本体
    {
      x: 1,
      y: 1,
      rows: [
        '..........oGGGGGGGo',
        '..........oGGGGGGGo',
        '..........oGGGGGGGo',
        '..........oGGRRGGGo',
        'oo........oGGRRGGGo........o',
        'Lpoo.....ooQQQQQQQoo.....oopo',
        'pppLoo..oWLoooooooLWo..ooLppp',
        'pYppLLo..oLLLLLLLLLo..oLLppYpp',
        'pppLLLLoooWWLLLLLWWoooLLLLppp',
        'LpMLLLLLoLWWoLLLoWWLoLLLLLMpo',
        'LLMMMLLLLoLLQQYQQLLoLLLLMMMLo',
        'LLMMMMMLGoLLQQYQQLLoGLMMMMMLo',
        'LLMMMMMMGoLLLQQQLLLoGMMMMMMLo',
        'LLMMMMGGMGoLLQQQLLoGMGGMMpMLo',
        'LLMMMMGGMoLoooQoooLoMGGMMMMLo',
        'LLMMGGMGMoLLLoQoLLLoMGMGGMMLo',
        'LpMGMGMGoLLLLLoLLLLLoGMGMGMLLo',
        'oLGLGMGMoLLLSSSSSLLLoMGMGLGLo',
        '.oLLGMGMoLLSSSSSSSLLoMGMGLLop',
        '..oLLLGoLLLSSSSSSSLLLoGLLLo',
        '...oLLLMoLLSSSSSSSLLoMLLLo',
        '...poLLLoLSSSSSSSSSLoLLLo',
        '.....oLLoLLSSSSSSSLLoLLo',
        '....p.oLLoLSSSSSSSLoLLo.p',
        '...ppp.oooLSSSSSSSLooo.ppp',
        '.oppYppooYoLSSSSSLoYooppYppoo',
        'oKKpppKKoYooooSooooYoKKpppKKKo',
        'oKKKpKKKoYoYoYoYoYoYoKKKpKKKKo',
        '.oTTTTTTToToToToToToTTTTTTTTo',
        '..oooooooooooooooooooooooooo',
      ],
    },
  ],
};

/** ツクバガマオウ（県ボス）：筑波山の ふたつの 峰を せおった ガマの 王。細く するどい 目、白い きばの 大きな 口、金の 王冠と むねかざり（ツチ） */
const tsukubaGamaO: MonsterDesign = {
  size: 48,
  colors: {
    T: NQ.tan,
    E: NQ.beige,
    S: NQ.sand,
    V: NQ.violet,
    L: NQ.lavender,
    G: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
    W: NQ.white,
  },
  rim: { [NQ.tan]: NQ.brown, [NQ.beige]: NQ.sand, [NQ.violet]: NQ.indigo, [NQ.gold]: NQ.ochre },
  rimDepth: 2,
  layers: [
    // 本体（みね・王冠・するどい 目・大きな 手）
    {
      x: 1,
      y: 1,
      rows: [
        '..........ooo....................ooo',
        '.........oLLVo....ooooo.ooo.....oLLVo',
        '.........oLLVo...oGGGGGoGGGo....oLLVo',
        '.........oLLVo...oGGGGGoGGGo....oLLVo',
        '........oooooooo.oGGGGGoGGGo..ooooooVo',
        '........oooooTTTooGGGRRGGGGoooTToooooo',
        '.......oooooooooToGGGRRGGGGoToooooooToo',
        '.......oTTTTToooToQQQQQQQQQoToooTTTTTTo',
        '......ooTTWWTTTTTToooooooooTTTTTTWWTTToo',
        '......ooTTWWWWTTTTTooooooooTTTTWWWWTTToo',
        '.....oLoTTTTWWWoTTTTTTTTTTTTToWWWTTTTToVo',
        '.....oLoTTTTTTWoTTTTTTTTTTTTToWTTTTTTToVo',
        '.....oLoTTTTTTTTTTTTTTTTTTTTTTTTTTTTTToVS',
        '....oLLVoTTTTTTTTTTTTTTTTTTTTTTTTTTTToVSSS',
        '.....oooTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTooS',
        '.......oTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTo',
        '.......oTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTo',
        '.......oTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTo',
        '...S...oTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTo',
        '..SSS..ooooTTTTTTTTTTTTTTTTTTTTTTTToooo',
        '...S....oTTooooooooooooooooooooooooTTo',
        '.....ooo.ooSWWSSSSSSSSSSSSSSSSSSWWSoo.ooo',
        '....oTTTo..oWTTTTTTTTTTTTTTTTTTTTWo..oTTTo',
        '...oTTTTTo..oooTTTTTTTTTTTTTTTTooo..oTTTTTo',
        '..oTTTTTToooTTTooooooooooooooooTTToooTTTTTSo',
        '.oTTTTTToSSSTTTTTooooRRoooooTTTTTTSSSoTTTSSSo',
        '.oTTTTTToSSSTTTToGGGGRRGGGGGoTTTTTSSSoTTTTSTo',
        '.oTTTTTToSSSTTTToGGGGRRGGGGGoTTTTTSSSoTTTTTTo',
        '.oTTTTTToTTTTTTToQQQQRRQQQQQoETTTTTTToTTTTTTo',
        '.oTTTTTToTTTTTTEEoooooooooooEEETTTTTToTTTTTTo',
        'oTTTTTTooTTTTTEEEEEEEEEEEEEEEEEETTTTTooTTTTTTo',
        '.oTTTToSSSTTTTEEEEEEEEEEEEEEEEEETTTTSSSoTTTTo',
        '.oTTTSoSSSTTTEEEEEEEEEEEEEEEEEEEETTTSSSoTTTTo',
        '.oTTSSSSSSTTTEEEEEEEEEEEEEEEEEEEETTTSSSoTTTTo',
        '.oTTTSTooTTTTEEEEEEEEEEEEEEEEEEEETTTTooTTTTTo',
        '.oTTTTTToTTTTEEEEEEEEEEEEEEEEEEEETTTToTTTTTTo',
        '.oTTTTTTToTSSSEEEEEEEEEEEEEEEEEESSSToTTTTTTTo',
        'oTTTTTTTTToSSSEEEEEEEEEEEEEEEEEESSSoTTTTTTTTTo',
        'oTTTTTTTTToSSSTEEEEEEEEEEEEEEEETSSSoTTTTTTTTTo',
        'TTTTTTTTTTTooTTTEEEEEEEEEEEEEETTTooTTTTTTTTTTT',
        'oToTToTToTTooooTTEEEEEEEEEEEETTooooToTToTToTTo',
        'oToTToTToTToTTTooTTTEEEEEETTTooTTToToTToTToTTo',
        '.ooTToTToTooTTToToooooooooooooTTToTooTToTToTo',
        '.oooooooooToTTToTTTTo....oTTToTTToTooooooooo',
        '..ooToTooTToTTToTTTTo....oTTToTTToTTooToTTo',
        '....oTToTTToTTToTTTo......oTToTTToTTToTTTo',
      ],
    },
  ],
};

/** ツクバガマオウ 後半（ミズ）：峰が 霞ヶ浦の 水の 青に そまり、足もとに 水が うずまく */
const tsukubaGamaOWater: MonsterDesign = {
  size: 48,
  colors: {
    T: NQ.tan,
    E: NQ.beige,
    S: NQ.sand,
    V: NQ.azure,
    L: NQ.ice,
    G: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
    W: NQ.white,
    C: NQ.sky,
  },
  rim: { [NQ.tan]: NQ.brown, [NQ.beige]: NQ.sand, [NQ.azure]: NQ.blue, [NQ.gold]: NQ.ochre },
  rimDepth: 2,
  layers: [
    // 本体（青く そまった みね・水の うず）
    {
      x: 1,
      y: 1,
      rows: [
        '..........ooo....................ooo',
        '.........oLLVo....ooooo.ooo.....oLLVo',
        '.........oLLVo...oGGGGGoGGGo....oLLVo',
        '.........oLLVo...oGGGGGoGGGo....oLLVo',
        '........oooooooo.oGGGGGoGGGo..ooooooVo',
        '........oooooTTTooGGGRRGGGGoooTToooooo',
        '.......oooooooooToGGGRRGGGGoToooooooToo',
        '.......oTTTTToooToQQQQQQQQQoToooTTTTTTo',
        '......ooTTWWTTTTTToooooooooTTTTTTWWTTToo',
        '......ooTTWWWWTTTTTooooooooTTTTWWWWTTToo',
        '.....oLoTTTTWWWoTTTTTTTTTTTTToWWWTTTTToVo',
        '.....oLoTTTTTTWoTTTTTTTTTTTTToWTTTTTTToVo',
        '.....oLoTTTTTTTTTTTTTTTTTTTTTTTTTTTTTToVC',
        '....oLLVoTTTTTTTTTTTTTTTTTTTTTTTTTTTToVCLC',
        '.....oooTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTooC',
        '.......oTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTo',
        '.......oTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTo',
        '.......oTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTo',
        '...C...oTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTo',
        '..CLC..ooooTTTTTTTTTTTTTTTTTTTTTTTToooo',
        '...C....oTTooooooooooooooooooooooooTTo',
        '.....ooo.ooSWWSSSSSSSSSSSSSSSSSSWWSoo.ooo',
        '....oTTTo..oWTTTTTTTTTTTTTTTTTTTTWo..oTTTo',
        '...oTTTTTo..oooTTTTTTTTTTTTTTTTooo..oTTTTTo',
        '..oTTTTTToooTTTooooooooooooooooTTToooTTTTTCo',
        '.oTTTTTToSSSTTTTTooooRRoooooTTTTTTSSSoTTTCLCo',
        '.oTTTTTToSSSTTTToGGGGRRGGGGGoTTTTTSSSoTTTTCTo',
        '.oTTTTTToSSSTTTToGGGGRRGGGGGoTTTTTSSSoTTTTTTo',
        '.oTTTTTToTTTTTTToQQQQRRQQQQQoETTTTTTToTTTTTTo',
        '.oTTTTTToTTTTTTEEoooooooooooEEETTTTTToTTTTTTo',
        'oTTTTTTooTTTTTEEEEEEEEEEEEEEEEEETTTTTooTTTTTTo',
        '.oTTTToSSSTTTTEEEEEEEEEEEEEEEEEETTTTSSSoTTTTo',
        '.oTTTCoSSSTTTEEEEEEEEEEEEEEEEEEEETTTSSSoTTTTo',
        '.oTTCLCSSSTTTEEEEEEEEEEEEEEEEEEEETTTSSSoTTTTo',
        '.oTTTCTooTTTTEEEEEEEEEEEEEEEEEEEETTTTooTTTTTo',
        '.oTTTTTToTTTTEEEEEEEEEEEEEEEEEEEETTTToTTTTTTo',
        '.oTTTTTTToTSSSEEEEEEEEEEEEEEEEEESSSToTTTTTTTo',
        'oTTTTTTTTToSSSEEEEEEEEEEEEEEEEEESSSoTTTTTTTTTo',
        'oTTTTTTTTToSSSTEEEEEEEEEEEEEEEETSSSoTTTTTTTTTo',
        'TTTTTTTTTTTooTTTEEEEEEEEEEEEEETTTooTTTTTTTTTTT',
        'oToTToTToTTooooTTEEEEEEEEEEEETTooooToTToTToTTo',
        'oToTToTToTToTTTooTTTEEEEEETTTooTTToToTToTToTTo',
        '.oCCCCCCoTooTTToToooooooooooooTTToTooTCCCCCCo',
        'CCCCCCCCCCToTTToTTTTo....oTTToTTToToCCCCCCCCCC',
        'CLLLLLLLLCCoTTToTTTTo....oTTToTTToTCCLLLLLLLLC',
        'CCCCCCCCCCToTTToTTTo......oTToTTToTTCCCCCCCCCC',
      ],
    },
  ],
};

/** 徳川斉昭（ラスボス）：紅白の 梅の 枝と 金の 日輪の 前立て、大きな 肩よろいと マント。軍配を かまえて 立つ（ヒカリ） */
const tokugawaNariaki = lord(
  [...HELMET, ...BEARD_FACE],
  {
    N: NQ.indigo,
    L: NQ.violet,
    K: NQ.violet,
    S: NQ.lavender,
    D: NQ.navy,
    G: NQ.gold,
    Y: NQ.yellow,
    R: NQ.red,
    T: NQ.indigo,
    H: NQ.navy,
    M: NQ.hairBlack,
    B: NQ.bark,
    p: NQ.blush,
  },
  { [NQ.violet]: NQ.indigo },
  [
    // 前立て：紅白の 梅の 枝と 金の 日輪（左右で ちがう）
    {
      x: 1,
      y: 2,
      rows: [
        '...........oWo..................opo',
        '..........oWWWo...............oopppo',
        '.........oWWYWWo.....oooo....oBppYppo',
        '..........oWWWoBo...oYYYYo..oBoopppo',
        '...........oWooopoooYYYYYYooBWo.opo',
        '............ooBpppBoYYRRYYBBWWWo.o',
        '.............oppYppBYRRRRBYWWYWWo',
        '.............oopppooYYRRYYoBWWWoo',
      ],
    },
    // 右手の 軍配
    {
      x: 33,
      y: 12,
      rows: [
        '...ooo',
        '..oGGGo',
        '.oGGGGGo',
        'oGGGRGGG',
        'oGGRRRGG',
        'oGRRRRRG',
        'oGRRRRRG',
        'oGRRRRRG',
        'oGRRRRRG',
        'GGRRRRRG',
        'oGGRRRGG',
        'oGGGRGGG',
        'GoGGGGGo',
        'KKoBBGo',
        'KKoBBoKo',
        'KKoBBoKK',
        'KKoBBoKK',
        'KKoBBoKK',
        'KKoBBoKK',
        'KooBBoKK',
        'oKoBBYKo',
        'KKoBYWY',
        'KKoBBYo',
      ],
    },
  ],
);

export const IBARAKI: Readonly<Record<string, MonsterDesign>> = {
  'ibaraki-nemofin': nemofin,
  'ibaraki-aozora-hime': aozoraHime,
  'ibaraki-midboss-harutsuge-dori': harutsugeDori,
  'ibaraki-midboss-harutsuge-dori.field': harutsugeDoriField,
  'ibaraki-boss-tsukuba-gama-o': tsukubaGamaO,
  'ibaraki-boss-tsukuba-gama-o.p0': tsukubaGamaOWater,
  'ibaraki-lastboss-tokugawa-nariaki': tokugawaNariaki,
};
