/** 石川県の モンスター（手描き。docs/06 §4・§6.3〜6.5 の 規格） */
import { NQ } from '../palette';
import type { MonsterDesign } from './design';
import { FACE, HELMET, lord } from './lastbosses';

// ───────────────────────── 通常 ─────────────────────────

/** ゴサイボン：九谷焼の つぼ。ふたの ぼうし、赤い 耳、五彩（緑・黄・紫・紺青・赤）の 絵（ツチ） */
const gosaiBon: MonsterDesign = {
  size: 32,
  colors: {
    E: NQ.beige,
    T: NQ.tan,
    G: NQ.green,
    Y: NQ.gold,
    V: NQ.violet,
    N: NQ.navy,
    R: NQ.red,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.beige]: NQ.sand, [NQ.tan]: NQ.brown },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '................',
        '..............EE',
        '..............EE',
        '.........EEEEEEE',
        '........EEEEEEEE',
        '........RRRRRRRR',
        '..........EEEEEE',
        '.........EEEEEEE',
        '.......EEEEEEEEE',
        '......EEEEEEEEEE',
        '.....EEEEEEEEEEE',
        '.....EEEEEEEEEEE',
        '....EEEEEEEEEEEE',
        '....EEEEEEEEEEEE',
        '....EEEEEEEEEEEE',
        '....EEEEEEEEEEEE',
        '....EEEEEEEEEEEE',
        '....EEEEEEEEEEEE',
        '....EEEEEEEEEEEE',
        '.....EEEEEEEEEEE',
        '.....EEEEEEEEEEE',
        '......EEEEEEEEEE',
        '.......EEEEEEEEE',
        '........EEEEEEEE',
        '.........EEEEEEE',
        '.........EEEEEEE',
        '.........TTTTTTT',
        '.........TTTTTTT',
        '................',
      ],
    },
    // 赤い 耳（つぼの とって）
    { mirror: true, y: 12, rows: ['....RR..........', '...RRR..........', '....RR..........'] },
    // 五彩の 絵（下の ほう）
    {
      rows: [
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '.......G..V.....N...G....V......',
        '......GGG.VV...NNN..GGG.VV......',
        '.......G.Y.V....N..Y.G...V......',
        '......Y..YYY.......YYY..Y.......',
        '.......V..Y...G...N..Y..N.......',
        '......VVV....GGG.NNN.......G....',
        '.......V......G...N.......GGG...',
        '..........Y.....................',
      ],
    },
    // かお
    {
      mirror: true,
      y: 13,
      rows: [
        '.........WW.....',
        '.........Wo.....',
        '.........Wo.....',
        '.......pp....o..',
        '..............oo',
      ],
    },
    // つや（左上）
    { x: 8, y: 11, rows: ['.W', 'W.'] },
  ],
};

/** キンパクチョウ：金沢の 金箔の はねを もつ チョウ。頭の 上に 金の わ（ヒカリ） */
const kinpakuCho: MonsterDesign = {
  size: 32,
  colors: {
    Y: NQ.gold,
    C: NQ.cream,
    Q: NQ.ochre,
    W: NQ.white,
    K: NQ.bark,
    p: NQ.blush,
  },
  rim: { [NQ.gold]: NQ.ochre },
  layers: [
    // はね（上）
    {
      mirror: true,
      y: 6,
      rows: [
        '..YYY...........',
        '.YYYYYY.........',
        '.YCYYYYYY.......',
        '.CCYYYYYYY......',
        '.YCYYYYQYYY.....',
        '.YYYYYYQYYY.....',
        '.YYYYYYQYYY.....',
        '..YYYYYYYYY.....',
      ],
    },
    // はね（下）
    {
      mirror: true,
      y: 15,
      rows: [
        '...YYYYYYYY.....',
        '..YYYYYYYYY.....',
        '..YCYYYQYYY.....',
        '...YYYYQYYY.....',
        '....YYYYYY......',
        '.....YYYY.......',
      ],
    },
    // からだ・しょっ角・金の わ
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '..........YYYYYY',
        '.........Y......',
        '..........QQQQQQ',
        '.............K..',
        '..............KK',
        '.............KKK',
        '.............KKK',
        '.............KKK',
        '.............KKK',
        '.............KKK',
        '.............KKK',
        '.............KKK',
        '.............KKK',
        '.............KKK',
        '.............KKK',
        '..............KK',
        '..............KK',
        '..............KK',
        '..............KK',
        '..............KK',
        '..............KK',
        '..............KK',
        '..............KK',
        '..............KK',
        '..............KK',
        '..............KK',
        '..............KK',
        '...............K',
      ],
    },
    // しょっ角
    { x: 11, y: 5, rows: ['K...', '.K..', '..KK'] },
    { x: 18, y: 5, rows: ['...K', '..K.', 'KK..'] },
    // かお
    { mirror: true, y: 8, rows: ['.............WW.', '.............Wo.', '...........pp...'] },
  ],
};

/** ハマシオン：珠洲の 浜の 塩の 山。まわりに 海の しずく、頭に 塩の つぶ（ミズ） */
const hamashion: MonsterDesign = {
  size: 32,
  colors: {
    W: NQ.white,
    c: NQ.cloud,
    I: NQ.ice,
    S: NQ.sky,
    A: NQ.azure,
    T: NQ.tan,
    B: NQ.brown,
    p: NQ.blush,
  },
  rim: { [NQ.white]: NQ.cloud, [NQ.tan]: NQ.brown },
  layers: [
    // 塩の つぶ（頭の 上）
    { x: 13, y: 3, rows: ['.II.', 'IWWI', 'IWWI', '.II.'] },
    { x: 9, y: 6, rows: ['II', 'II'] },
    { x: 21, y: 6, rows: ['II', 'II'] },
    // 塩の 山
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
        '..............WW',
        '.............WWW',
        '............WWWW',
        '...........WWWWW',
        '..........WWWWWW',
        '.........WWWWWWW',
        '........WWWWWWWW',
        '........WWWWWWWW',
        '.......WWWWWWWWW',
        '......WWWWWWWWWW',
        '.....WWWWWWWWWWW',
        '.....WWWWWWWWWWW',
        '....WWWWWWWWWWWW',
        '...WWWWWWWWWWWWW',
        '...WWWWWWWWWWWWW',
        '..WWWWWWWWWWWWWW',
        '..WWWWWWWWWWWWWW',
        '.WWWWWWWWWWWWWWW',
        '.WWWWWWWWWWWWWWW',
        '.WWWWWWWWWWWWWWW',
        '.WWWWWWWWWWWWWWW',
        '.SSSSSSSSSSSSSSS',
        '..AAAAAAAAAAAAAA',
      ],
    },
    // 波の おび
    { mirror: true, y: 21, rows: ['...SISISISISISIS', '....ISISISISISIS'] },
    // かお
    {
      mirror: true,
      y: 14,
      rows: [
        '..........WW....',
        '..........oo....',
        '..........oo....',
        '........pp......',
        '..............oo',
      ],
    },
    // 海の しずく
    { x: 2, y: 12, rows: ['.I.', 'ISI', '.I.'] },
    { x: 27, y: 15, rows: ['.I.', 'ISI', '.I.'] },
    // おけ（右手）
    { x: 24, y: 22, rows: ['TBTBT', 'TTTTT', 'TBTBT', '.TTT.'] },
  ],
};

/** ワジマヌリン：輪島塗の 赤い おわん。黒い 高台の 足、金の ふちと まき絵（ヒノ） */
const wajimanurin: MonsterDesign = {
  size: 32,
  colors: {
    R: NQ.red,
    b: NQ.brick,
    A: NQ.apricot,
    K: NQ.bark,
    N: NQ.night,
    Y: NQ.gold,
    Q: NQ.ochre,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.red]: NQ.brick, [NQ.bark]: NQ.ink },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '....YYYYYYYYYYYY',
        '...YYYYYYYYYYYYY',
        '...RRRRRRRRRRRRR',
        '...RRRRRRRRRRRRR',
        '...RRRRRRRRRRRRR',
        '...RRRRRRRRRRRRR',
        '....RRRRRRRRRRRR',
        '....RRRRRRRRRRRR',
        '.....RRRRRRRRRRR',
        '.....RRRRRRRRRRR',
        '......RRRRRRRRRR',
        '......RRRRRRRRRR',
        '.......RRRRRRRRR',
        '.......RRRRRRRRR',
        '........RRRRRRRR',
        '.........RRRRRRR',
        '..........RRRRRR',
        '..........KKKKKK',
        '..........KKKKKK',
        '..........KKKKKK',
        '..........KKKKKK',
        '.........KKKKKKK',
        '.........KKKKKKK',
        '........KKKKKKKK',
        '........KKKKKKKK',
        '........NNNNNNNN',
      ],
    },
    // 金の まき絵
    { x: 5, y: 12, rows: ['Y.Y', '.Y.', 'Y.Y'] },
    { x: 22, y: 14, rows: ['.Y.', 'Y.Y', '.Y.'] },
    // 小さな 手
    { x: 2, y: 16, rows: ['RR', 'RR'] },
    { x: 28, y: 16, rows: ['RR', 'RR'] },
    // かお
    {
      mirror: true,
      y: 12,
      rows: ['..........WW....', '..........Wo....', '..........Wo....', '........pp......', '.............ooo'],
    },
    { x: 6, y: 9, rows: ['.A', 'A.'] },
  ],
};

/** カガヌリマル（ワジマヌリンの しんか）：金の まき絵を まとった うるしの むしゃ。ふたの かぶと（ヒノ） */
const kagaNurimaru: MonsterDesign = {
  size: 32,
  colors: {
    R: NQ.red,
    b: NQ.brick,
    A: NQ.apricot,
    K: NQ.bark,
    N: NQ.night,
    Y: NQ.gold,
    Q: NQ.ochre,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.red]: NQ.brick, [NQ.bark]: NQ.ink },
  layers: [
    // ふたの かぶと
    { mirror: true, y: 1, rows: ['.........Y..Y...', '.........YYYY...', '......KKKKKKKKKK', '.....KKKKKKKKKKK', '.....YYYYYYYYYYY'] },
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
        '...YYYYYYYYYYYYY',
        '..YYYYYYYYYYYYYY',
        '..RRRRRRRRRRRRRR',
        '..RRRRRRRRRRRRRR',
        '..RRRRRRRRRRRRRR',
        '..RRRRRRRRRRRRRR',
        '...RRRRRRRRRRRRR',
        '...RRRRRRRRRRRRR',
        '....RRRRRRRRRRRR',
        '....RRRRRRRRRRRR',
        '.....RRRRRRRRRRR',
        '.....RRRRRRRRRRR',
        '......RRRRRRRRRR',
        '......RRRRRRRRRR',
        '.......RRRRRRRRR',
        '........RRRRRRRR',
        '.........RRRRRRR',
        '.........KKKKKKK',
        '.........KKKKKKK',
        '.........KKKKKKK',
        '........KKKKKKKK',
        '........KKKKKKKK',
        '.......KKKKKKKKK',
        '.......KKKKKKKKK',
        '.......NNNNNNNNN',
      ],
    },
    // 金の まき絵（ちらし）
    { x: 3, y: 14, rows: ['Y.Y', '.Y.', 'Y.Y'] },
    { x: 24, y: 12, rows: ['.Y.', 'Y.Y', '.Y.'] },
    { x: 14, y: 22, rows: ['Y.Y', '.Y.'] },
    // うで（こぶしを かまえる）
    { x: 1, y: 15, rows: ['RRR', 'RRR', '.bb'] },
    { x: 28, y: 15, rows: ['RRR', 'RRR', 'bb.'] },
    // かお（きりっと）
    {
      mirror: true,
      y: 11,
      rows: [
        '.........o......',
        '..........oo....',
        '..........WW....',
        '..........Wo....',
        '..........Wo....',
        '........pp......',
        '............oooo',
      ],
    },
    { x: 4, y: 10, rows: ['.A', 'A.'] },
  ],
};

// ───────────────────────── しんか ─────────────────────────

/** ゴサイムシャ（ゴサイボンの しんか）：九谷焼の 大ざらを たてに した むしゃ。ふたの かぶと、絵つけの 筆（ツチ） */
const gosaiMusha: MonsterDesign = {
  size: 32,
  colors: {
    E: NQ.beige,
    T: NQ.tan,
    G: NQ.green,
    Y: NQ.gold,
    V: NQ.violet,
    R: NQ.red,
    W: NQ.white,
    p: NQ.blush,
    K: NQ.bark,
  },
  rim: { [NQ.beige]: NQ.sand, [NQ.tan]: NQ.brown },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '..............EE',
        '..............EE',
        '.......EEEEEEEEE',
        '......EEEEEEEEEE',
        '......RRRRRRRRRR',
        '........EEEEEEEE',
        '.......EEEEEEEEE',
        '......EEEEEEEEEE',
        '.....EEEEEEEEEEE',
        '.....EEEEEEEEEEE',
        '....EEEEEEEEEEEE',
        '....EEEEEEEEEEEE',
        '....EEEEEEEEEEEE',
        '....EEEEEEEEEEEE',
        '....EEEEEEEEEEEE',
        '....EEEEEEEEEEEE',
        '....EEEEEEEEEEEE',
        '....EEEEEEEEEEEE',
        '....EEEEEEEEEEEE',
        '.....EEEEEEEEEEE',
        '.....EEEEEEEEEEE',
        '......EEEEEEEEEE',
        '.......EEEEEEEEE',
        '........EEEEEEEE',
        '........EEEEEEEE',
        '........TTTTTTTT',
        '........TTTTTTTT',
        '.........TTTTTTT',
        '................',
      ],
    },
    // 大ざらの たて（左手）
    {
      x: 1,
      y: 13,
      rows: ['..EEEE..', '.EEEEEE.', 'EEVEEGEE', 'EEEYYEEE', 'EEGEEVEE', 'EEEEEEEE', '.EEVEEE.', '..EEEE..'],
    },
    // 絵つけの 筆（右手）
    { x: 26, y: 8, rows: ['.WW', '.WW', '.KK', '.KK', '.KK', '.KK', '.KK', 'RKK', '.KK'] },
    // 五彩の 絵
    {
      rows: [
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '..............V...G....V........',
        '.............VVV..GGG.VV........',
        '..............V..Y.G...V........',
        '.................YYY..Y.........',
        '..............G...V..Y..........',
        '.............GGG.VVV............',
        '..............G...V.............',
      ],
    },
    // かお（きりっと）
    {
      mirror: true,
      y: 11,
      rows: [
        '........o.......',
        '.........oo.....',
        '.........WW.....',
        '.........Wo.....',
        '.........Wo.....',
        '.......pp.......',
        '..............oo',
      ],
    },
    { x: 8, y: 9, rows: ['.W', 'W.'] },
  ],
};

/** キンランアゲハ（キンパクチョウの しんか）：大きな 金色の アゲハ。はねの 先が 長く のび、金の わが 大きい（ヒカリ） */
const kinranAgeha: MonsterDesign = {
  size: 32,
  colors: {
    Y: NQ.gold,
    C: NQ.cream,
    Q: NQ.ochre,
    W: NQ.white,
    K: NQ.bark,
    p: NQ.blush,
  },
  rim: { [NQ.gold]: NQ.ochre },
  layers: [
    // はね（上。大きく ひろげる）
    {
      mirror: true,
      y: 4,
      rows: [
        '.YY.............',
        '.YYYY...........',
        '.CYYYYY.........',
        '.CCYYYYYY.......',
        '.CCYYYYYYYY.....',
        '.YCYYYYQYYYY....',
        '.YYYYYYQYYYY....',
        '.YYYYYYQYYYY....',
        '.YYYYYYQYYYY....',
        '..YYYYYYYYYY....',
      ],
    },
    // はね（下。先が しっぽの ように のびる）
    {
      mirror: true,
      y: 14,
      rows: [
        '...YYYYYYYYY....',
        '..YYYYYYYYYY....',
        '..YCYYYQYYYY....',
        '..YYYYYQYYYY....',
        '...YYYYYYYYY....',
        '....YYYYYYYY....',
        '.....YYYYYYY....',
        '......YYYYYY....',
        '.....YYYYYY.....',
        '....YY..YY......',
        '...YY....Y......',
        '..YY............',
      ],
    },
    // からだ・しょっ角・金の わ
    {
      mirror: true,
      rows: [
        '................',
        '.........YYYYYYY',
        '........Y.......',
        '.........QQQQQQQ',
        '............K...',
        '.............KK.',
        '............KKK.',
        '............KKK.',
        '............KKK.',
        '............KKK.',
        '............KKK.',
        '............KKK.',
        '............KKK.',
        '............KKK.',
        '............KKK.',
        '............KKK.',
        '............KKK.',
        '............KKK.',
        '.............KK.',
        '.............KK.',
        '.............KK.',
        '.............KK.',
        '.............KK.',
        '.............KK.',
        '.............KK.',
        '.............KK.',
        '.............KK.',
        '.............KK.',
        '.............KK.',
        '.............KK.',
        '..............K.',
      ],
    },
    { x: 10, y: 4, rows: ['K...', '.K..', '..KK'] },
    { x: 19, y: 4, rows: ['...K', '..K.', 'KK..'] },
    // かお（きりっと）
    {
      mirror: true,
      y: 7,
      rows: ['...........oo...', '............WW..', '............Wo..', '..........pp....'],
    },
    // きらり
    { x: 1, y: 2, rows: ['.C.', 'CWC', '.C.'] },
    { x: 28, y: 20, rows: ['.C.', 'CWC', '.C.'] },
  ],
};

/** オオハマシオン（ハマシオンの しんか）：大きな 塩の 山。かたに 塩の つぶ、足もとに 海の 水（ミズ） */
const ooHamashion: MonsterDesign = {
  size: 32,
  colors: {
    W: NQ.white,
    c: NQ.cloud,
    I: NQ.ice,
    S: NQ.sky,
    A: NQ.azure,
    T: NQ.tan,
    B: NQ.brown,
    p: NQ.blush,
  },
  rim: { [NQ.white]: NQ.cloud, [NQ.tan]: NQ.brown },
  layers: [
    // 塩の つぶ（頭と かた）
    { x: 12, y: 1, rows: ['.IIII.', 'IWWWWI', 'IWWWWI', '.IIII.'] },
    { x: 5, y: 8, rows: ['.II.', 'IWWI', '.II.'] },
    { x: 23, y: 8, rows: ['.II.', 'IWWI', '.II.'] },
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '..............WW',
        '.............WWW',
        '............WWWW',
        '...........WWWWW',
        '..........WWWWWW',
        '..........WWWWWW',
        '.........WWWWWWW',
        '........WWWWWWWW',
        '.......WWWWWWWWW',
        '.......WWWWWWWWW',
        '......WWWWWWWWWW',
        '.....WWWWWWWWWWW',
        '.....WWWWWWWWWWW',
        '....WWWWWWWWWWWW',
        '....WWWWWWWWWWWW',
        '...WWWWWWWWWWWWW',
        '...WWWWWWWWWWWWW',
        '..WWWWWWWWWWWWWW',
        '..WWWWWWWWWWWWWW',
        '.WWWWWWWWWWWWWWW',
        '.WWWWWWWWWWWWWWW',
        '.WWWWWWWWWWWWWWW',
        '.WWWWWWWWWWWWWWW',
        '.WWWWWWWWWWWWWWW',
        '.SSSSSSSSSSSSSSS',
        '..AAAAAAAAAAAAAA',
      ],
    },
    // 波の おび
    { mirror: true, y: 20, rows: ['..SISISISISISISI', '...ISISISISISISI'] },
    // かお（きりっと）
    {
      mirror: true,
      y: 11,
      rows: [
        '........o.......',
        '.........oo.....',
        '.........oo.....',
        '.........oo.....',
        '.......pp.......',
        '..............oo',
      ],
    },
    // おけ（右手）と しずく
    { x: 23, y: 19, rows: ['TBTBTB', 'TTTTTT', 'TBTBTB', '.TTTT.'] },
    { x: 1, y: 12, rows: ['.I.', 'ISI', '.I.'] },
    { x: 2, y: 22, rows: ['I.'] },
  ],
};

// ───────────────────────── 中ボス ─────────────────────────

const kirikoColors = {
  C: NQ.cream,
  Y: NQ.gold,
  Q: NQ.ochre,
  R: NQ.red,
  b: NQ.brick,
  K: NQ.bark,
  T: NQ.tan,
  W: NQ.white,
  V: NQ.vermilion,
  A: NQ.apricot,
  p: NQ.blush,
};

/** キリコダイショウ（中ボス）：能登の キリコ祭りの 大きな あかり。屋根の 上に 王冠、下に かつぎ棒（ヒノ） */
const kirikoTaisho: MonsterDesign = {
  size: 40,
  colors: kirikoColors,
  rim: { [NQ.cream]: NQ.ochre, [NQ.red]: NQ.brick, [NQ.tan]: NQ.brown },
  rimDepth: 2,
  layers: [
    // ほのお（あかりの まわりで もえあがる）
    {
      mirror: true,
      y: 4,
      rows: ['..V.................', '.VA.................', '.VA.................', '.VA.................', '..V.................'],
    },
    { x: 33, y: 6, rows: ['.V.', 'AV.', 'AV.', '.V.'] },
    // 大きな 王冠
    {
      mirror: true,
      y: 0,
      rows: [
        '...................Y',
        '...............Y...Y',
        '...............YY.YY',
        '...............YYYYY',
        '...............YYYYR',
        '...............QQQQQ',
      ],
    },
    // そりあがった 屋根と キリコの 本体
    {
      mirror: true,
      y: 6,
      rows: [
        '.......RRRRRRRRRRRRR',
        '.....RRRRRRRRRRRRRRR',
        '...RRRRRRRRRRRRRRRRR',
        '..bbbbbbbbbbbbbbbbbb',
        '....YYYYYYYYYYYYYYYY',
        '.....CCCCCCCCCCCCCCC',
        '.....CCCCCCCCCCCCCCC',
        '.....CCCCCCCCCCCCCCC',
        '.....CCCCCCCCCCCCCCC',
        '.....CCCCCCCCCCCCCCC',
        '.....CCCCCCCCCCCCCCC',
        '.....CCCCCCCCCCCCCCC',
        '.....CCCCCCCCCCCCCCC',
        '.....CCCCCCCCCCCCCCC',
        '.....CCCCCCCCCCCCCCC',
        '.....CCCCCCCCCCCCCCC',
        '.....CCCCCCCCCCCCCCC',
        '.....CCCCCCCCCCCCCCC',
        '.....CCCCCCCCCCCCCCC',
        '.....CCCCCCCCCCCCCCC',
        '.....CCCCCCCCCCCCCCC',
        '.....CCCCCCCCCCCCCCC',
        '.....CCCCCCCCCCCCCCC',
        '.....YYYYYYYYYYYYYYY',
        '.....bbbbbbbbbbbbbbb',
        '.....KKKKKKKKKKKKKKK',
        '.......KK.....KKKKKK',
        '.......KK.....KKKKKK',
        '.......TT.....TTTTTT',
        '.......TT.....TTTTTT',
        '.......TT.....TTTTTT',
        '.......TT.....TTTTTT',
        '.......TT.....TTTTTT',
      ],
    },
    // かつぎ棒（左右に 長く）
    { y: 31, rows: ['.KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK.', '.TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT.'] },
    // 赤い もよう
    { mirror: true, y: 14, rows: ['.....R.R.R.R.R.R.R.R'] },
    { mirror: true, y: 27, rows: ['.....R.R.R.R.R.R.R.R'] },
    // かお（するどい 目・まゆ・口）
    {
      mirror: true,
      y: 17,
      rows: [
        '.........oo.........',
        '...........oo.......',
        '.........WWWo.......',
        '.........WWWo.......',
        '.........WWoo.......',
        '.........Wooo.......',
        '....................',
        '...........ooooooo..',
      ],
    },
  ],
};

/** キリコダイショウ（フィールドに立つ 32×32） */
const kirikoTaishoField: MonsterDesign = {
  size: 32,
  colors: {
    C: NQ.cream,
    Y: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
    b: NQ.brick,
    K: NQ.bark,
    T: NQ.tan,
    W: NQ.white,
    V: NQ.vermilion,
  },
  rim: { [NQ.cream]: NQ.ochre, [NQ.red]: NQ.brick },
  layers: [
    // ほのお
    { mirror: true, y: 3, rows: ['.V..............', 'VV..............', 'VV..............', '.V..............'] },
    // 王冠
    {
      mirror: true,
      y: 0,
      rows: ['...........Y...Y', '...........YY.YY', '...........YYYYY', '...........QQQQR'],
    },
    {
      mirror: true,
      y: 4,
      rows: [
        '.....RRRRRRRRRRR',
        '...RRRRRRRRRRRRR',
        '..bbbbbbbbbbbbbb',
        '...YYYYYYYYYYYYY',
        '....CCCCCCCCCCCC',
        '....CCCCCCCCCCCC',
        '....CCCCCCCCCCCC',
        '....CCCCCCCCCCCC',
        '....CCCCCCCCCCCC',
        '....CCCCCCCCCCCC',
        '....CCCCCCCCCCCC',
        '....CCCCCCCCCCCC',
        '....CCCCCCCCCCCC',
        '....CCCCCCCCCCCC',
        '....CCCCCCCCCCCC',
        '....CCCCCCCCCCCC',
        '....CCCCCCCCCCCC',
        '....CCCCCCCCCCCC',
        '....YYYYYYYYYYYY',
        '....bbbbbbbbbbbb',
        '....KKKKKKKKKKKK',
        '......KK....KKKK',
        '......KK....KKKK',
        '......TT....TTTT',
        '......TT....TTTT',
        '......TT....TTTT',
        '......TT....TTTT',
      ],
    },
    { y: 24, rows: ['.KKKKKKKKKKKKKKKKKKKKKKKKKKKKK.', '.TTTTTTTTTTTTTTTTTTTTTTTTTTTTT.'] },
    { mirror: true, y: 11, rows: ['....R.R.R.R.R.R.'] },
    { mirror: true, y: 20, rows: ['....R.R.R.R.R.R.'] },
    {
      mirror: true,
      y: 13,
      rows: ['.......oo.......', '........WWo.....', '........WWo.....', '........Woo.....', '................', '.........ooooo..'],
    },
  ],
};

// ───────────────────────── 県ボス ─────────────────────────

/** 雪つりの なわ（まん中の ぼうから 左右へ。左半分） */
const YUKITSURI = [
  '.......................S',
  '......................S.',
  '.....................S..',
  '....................S...',
  '...................S....',
  '..................S.....',
  '.................S......',
  '................S.......',
  '...............S........',
  '..............S.........',
  '.............S..........',
  '............S...........',
  '...........S............',
  '..........S.............',
  '.........S..............',
  '........S...............',
];

/** ユキツリオオマツ（県ボス）：兼六園の 大きな 松。まん中の ぼうから なわを つった「雪つり」、雪の のった 松の 葉（モリ） */
const yukitsuriOomatsuColors = {
  F: NQ.forest,
  G: NQ.green,
  L: NQ.leaf,
  W: NQ.white,
  c: NQ.cloud,
  K: NQ.bark,
  B: NQ.brown,
  T: NQ.tan,
  S: NQ.sand,
  Y: NQ.gold,
  Q: NQ.ochre,
  R: NQ.red,
  p: NQ.blush,
};

const yukitsuriOomatsu: MonsterDesign = {
  size: 48,
  colors: yukitsuriOomatsuColors,
  rim: { [NQ.green]: NQ.forest, [NQ.brown]: NQ.bark },
  rimDepth: 2,
  layers: [
    // まん中の ぼうと なわ
    { mirror: true, y: 8, rows: YUKITSURI },
    {
      mirror: true,
      y: 6,
      rows: [
        '.......................T',
        '.......................T',
        '.......................T',
        '.......................T',
      ],
    },
    // 王冠（ぼうの てっぺん）
    {
      mirror: true,
      y: 1,
      rows: [
        '.......................Y',
        '...................Y...Y',
        '...................YY.YY',
        '...................YYYYY',
        '...................YYYYR',
        '...................QQQQQ',
      ],
    },
    // 松の 葉（3 だん）
    {
      mirror: true,
      y: 14,
      rows: [
        '..............GGGGGGGGGG',
        '...........GGGGGGGGGGGGG',
        '.........GGGGGGGGGGGGGGG',
        '........GGGGGGGGGGGGGGGG',
        '.......GGGGGGGGGGGGGGGGG',
        '......GGGGGGGGGGGGGGGGGG',
        '.....GGGGGGGGGGGGGGGGGGG',
        '....GGGGGGGGGGGGGGGGGGGG',
        '...GGGGGGGGGGGGGGGGGGGGG',
        '..GGGGGGGGGGGGGGGGGGGGGG',
        '..GGGGGGGGGGGGGGGGGGGGGG',
        '.GGGGGGGGGGGGGGGGGGGGGGG',
        '.GGGGGGGGGGGGGGGGGGGGGGG',
        '.GGGGGGGGGGGGGGGGGGGGGGG',
        '.GGGGGGGGGGGGGGGGGGGGGGG',
        '.GGGGGGGGGGGGGGGGGGGGGGG',
        '..GGGGGGGGGGGGGGGGGGGGGG',
        '...GGGGGGGGGGG..GGGGGGGG',
        '.....GGGGGGG......GGGGGG',
      ],
    },
    // 葉の 明るい ところ と 雪
    {
      mirror: true,
      y: 14,
      rows: [
        '..............LLLLLWWWWW',
        '...........LLLLLWWWWWWWW',
        '.........LLLLWWWWWWWGGGG',
        '........LLLWWWWWGGGGGGGG',
        '.......LLWWWWGGGGGGGGGGG',
        '......LWWWGGGGGGGGGGGGGG',
        '.....WWGGGGGGGGGGGGGGGGG',
        '....WGGGGGGGGGGGGGGGGGGG',
        '...LGGGGGGGGGGGGGGGGGGGG',
        '..LGGGGGGGGGGGGGGGGGGGGG',
        '..GGGGGGGGGGGGGGGGGGGGGG',
        '.LGGGGGGGGGGGGGGGGGGGGGG',
        '.GGGGGGGGGGGGGGGGGGGGGGG',
        '.GGGGGGGGGGGGGGGGGGGGGGG',
        '.GGGGGGGGGGGGGGGGGGGGGGG',
      ],
    },
    // 雪つりの なわ（葉の 手前に もう 一度）
    { mirror: true, y: 8, rows: YUKITSURI },
    // みきと ねっこ（顔つき）
    {
      mirror: true,
      y: 30,
      rows: [
        '..............BBBBBBBBBB',
        '.............BBBBBBBBBBB',
        '............BBBBBBBBBBBB',
        '............BBBBBBBBBBBB',
        '...........BBBBBBBBBBBBB',
        '...........BBBBBBBBBBBBB',
        '..........BBBBBBBBBBBBBB',
        '.........BBBBBBBBBBBBBBB',
        '........BBBBBBBBBBBBBBBB',
        '......BBBBBBBBBBBBBBBBBB',
        '...BBBBBBBBBBBBBBBBBBBBB',
        '..BBBBBBBBBBBBBBBBBBBBBB',
        '.BBBBBBBBBBBBBBBBBBBBBBB',
        '.BBBBBBBBBBBBBBBBBBBBBBB',
        '.BBBBBBBBBBBBBBBBBBBBBBB',
        '.BBB..BBBBB..BBBBBBBBBBB',
        '.BB....BBB....BBBBBBBBBB',
      ],
    },
    // みきの かげ
    {
      mirror: true,
      y: 33,
      rows: [
        '............K...........',
        '...........K............',
        '..........K.............',
        '.........K..............',
        '........K...............',
      ],
    },
    // かお（みきに ある 3×4 の 目・まゆ・口）
    {
      mirror: true,
      y: 33,
      rows: [
        '...............ooo......',
        '..................ooo...',
        '.................WWo....',
        '.................WWo....',
        '.................WWo....',
        '.................Woo....',
        '........................',
        '..............pp........',
        '.................oooooo.',
      ],
    },
  ],
};

/** ユキツリオオマツ 後半：金沢の 金箔を まとい、松の 葉と なわが 金色に かがやく */
const yukitsuriOomatsuP0: MonsterDesign = {
  ...yukitsuriOomatsu,
  colors: { ...yukitsuriOomatsuColors, L: NQ.gold, W: NQ.cream, S: NQ.gold, c: NQ.yellow },
  rim: { [NQ.green]: NQ.forest, [NQ.brown]: NQ.bark, [NQ.gold]: NQ.ochre },
  layers: [
    ...yukitsuriOomatsu.layers,
    // 金箔の きらめき
    { x: 3, y: 12, rows: ['.Y.', 'YWY', '.Y.'] },
    { x: 41, y: 18, rows: ['.Y.', 'YWY', '.Y.'] },
    { x: 20, y: 10, rows: ['.Y.', 'YWY', '.Y.'] },
    { x: 8, y: 26, rows: ['Y'] },
    { x: 38, y: 30, rows: ['Y'] },
  ],
};

// ───────────────────────── ラスボス ─────────────────────────

/** 前田利家：金の 長い 烏帽子形の かぶと、白糸おどしの よろい、右手に やり（カゼ） */
const toshiieBody = lord(
  [
    '..................GGGGGG',
    '.................GGYGGGG',
    '.................GGYGGGG',
    '................GGGYGGGG',
    '................GGGYGGGG',
    '...............GGGGYGGGG',
    '...............GGGGYGGGG',
    '..............GGGGGGGGGG',
    '.............GGGGGGGGGGG',
    '...........NNNNNGGGGGGGG',
    ...HELMET,
    ...FACE,
  ],
  {
    N: NQ.night,
    L: NQ.slate,
    K: NQ.paper,
    S: NQ.cloud,
    G: NQ.gold,
    Y: NQ.yellow,
    R: NQ.red,
    T: NQ.paper,
    H: NQ.slate,
    E: NQ.silver,
    B: NQ.bark,
  },
  { [NQ.paper]: NQ.cloud },
  [
    // やり（右手。ななめに 立てる。赤い ふさ）
    { x: 38, y: 4, rows: ['.E.', 'EEE', '.E.', '.B.', 'RB.', 'RB.', '.B.'] },
    {
      x: 39,
      y: 11,
      rows: [
        'B',
        'B',
        'B',
        'B',
        'B',
        'B',
        'B',
        'B',
        'B',
        'B',
        'B',
        'B',
        'B',
        'B',
        'B',
        'B',
        'B',
        'B',
        'B',
        'B',
        'B',
        'B',
        'B',
        'B',
        'B',
        'B',
        'B',
        'B',
        'B',
        'B',
        'B',
        'B',
      ],
    },
  ],
);

const maedaToshiie: MonsterDesign = toshiieBody;

export const ISHIKAWA: Readonly<Record<string, MonsterDesign>> = {
  'ishikawa-gosai-bon': gosaiBon,
  'ishikawa-gosai-musha': gosaiMusha,
  'ishikawa-kinpaku-cho': kinpakuCho,
  'ishikawa-kinran-ageha': kinranAgeha,
  'ishikawa-hamashion': hamashion,
  'ishikawa-oo-hamashion': ooHamashion,
  'ishikawa-wajimanurin': wajimanurin,
  'ishikawa-kaga-nurimaru': kagaNurimaru,
  'ishikawa-midboss-kiriko-taisho': kirikoTaisho,
  'ishikawa-midboss-kiriko-taisho.field': kirikoTaishoField,
  'ishikawa-boss-yukitsuri-oomatsu': yukitsuriOomatsu,
  'ishikawa-boss-yukitsuri-oomatsu.p0': yukitsuriOomatsuP0,
  'ishikawa-lastboss-maeda-toshiie': maedaToshiie,
};
