/** 岩手のモンスター（docs/05 §2、docs/06 §6.3〜6.6） */
import { NQ } from '../palette';
import type { MonsterDesign } from './design';
import { LAST_BOSSES } from './lastbosses';

/** ワンコソバット：わんこそばの 小さな おわん（外は黒、中は赤い うるし）を つみかさねた コウモリ。上の おわんから そばが のぞく（カゼ） */
const wankosobat: MonsterDesign = {
  size: 32,
  colors: {
    A: NQ.aqua,
    T: NQ.teal,
    M: NQ.mint,
    N: NQ.night,
    n: NQ.slate,
    R: NQ.red,
    E: NQ.beige,
    S: NQ.sand,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.aqua]: NQ.teal },
  layers: [
    // つばさ（いちばん上の おわんの よこ）
    {
      mirror: true,
      y: 8,
      rows: [
        '.T......',
        '.AT.....',
        '.AAT....',
        '.AMAT...',
        '.AMAAT..',
        '.AMAAAA.',
        '.AAMAAAA',
        '.AAAMAAA',
        '.AAAAAAA',
        '.AA..AAA',
        '.A....A.',
      ],
    },
    // 耳・そば・いちばん上の おわん（顔）・つみかさねた おわん
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '.......A........',
        '.......AA.......',
        '.......ApA...EEE',
        '.......AAA..ESSS',
        '......RRRRRESEEE',
        '......RRRESEESSS',
        '......RRSEESSEEE',
        '......NRRRRRRRRR',
        '......NNNNNNNNNN',
        '......NNNNNWWNNN',
        '......NNNNWNNWNN',
        '.......NNNNNNNNN',
        '.......NNppNNWRR',
        '........NNNNNNRR',
        '..........NNNNNN',
        '........RRRRRRRR',
        '........NNNNNNNN',
        '.........NNNNNNN',
        '...........NNNNN',
        '.........RRRRRRR',
        '.........NNNNNNN',
        '..........NNNNNN',
        '............NNNN',
        '............TT..',
        '............TT..',
      ],
    },
    // そばが 1 本 ふちから たれる
    { x: 8, y: 11, rows: ['E', 'E', 'E'] },
    // うるしの つや（左上）
    { x: 7, y: 13, rows: ['n', 'n'] },
    { x: 9, y: 21, rows: ['nn'] },
    { x: 10, y: 25, rows: ['nn'] },
  ],
};

/** リュウセンウオ：龍泉洞の 地底湖の すきとおった 魚。小さな つのと ひげ（ミズ） */
const ryusenUo: MonsterDesign = {
  size: 32,
  colors: {
    A: NQ.azure,
    S: NQ.sky,
    I: NQ.ice,
    W: NQ.white,
    Y: NQ.gold,
    m: NQ.mint,
    p: NQ.blush,
  },
  rim: { [NQ.azure]: NQ.blue, [NQ.ice]: NQ.sky, [NQ.gold]: NQ.ochre },
  layers: [
    {
      mirror: true,
      y: 1,
      rows: [
        '..............II',
        '..........Y..ISI',
        '..........YY.ISI',
        '...........YISII',
        '...........YAAAA',
        '..........AAAAAA',
        '.........AAAAAAA',
        '........AAAAAAAA',
        '.......AAAAAAAAA',
        '.......AAAWWAAAA',
        '.......AAAWoAAAA',
        '...II..AAAWoAAAA',
        '..ISII.AApAAAAAA',
        '..IISIIAAAAAAAAo',
        '...ISIIAAAAIIIIo',
        '....IIIAAIIAAAAA',
        '.....IIAIAAASSSS',
        '.......AAmAASSSS',
        '.......AAAAASSSS',
        '........AAmAASSS',
        '........AAAAASSS',
        '.........AAAASSS',
        '..........AAASSS',
        '...........AAASS',
        '............AAAA',
        '.........IIIIAAA',
        '.......IIISIIA..',
        '.....IIISII.....',
        '....IISII.......',
        '....III.........',
      ],
    },
    // つや（左上）
    { x: 9, y: 7, rows: ['.SS', 'SW.', 'S..'] },
  ],
};

/** トオノカッパ：遠野の むかしばなしの カッパ。頭に おさら、せなかに こうら、手に きゅうり（ミズ） */
const tonoKappa: MonsterDesign = {
  size: 32,
  colors: {
    L: NQ.leaf,
    G: NQ.green,
    M: NQ.lime,
    E: NQ.sprout,
    Y: NQ.yellow,
    S: NQ.sky,
    W: NQ.white,
    p: NQ.blush,
    B: NQ.brown,
    T: NQ.tan,
  },
  rim: { [NQ.leaf]: NQ.green, [NQ.brown]: NQ.bark },
  layers: [
    // こうら（うしろ）
    {
      mirror: true,
      y: 18,
      rows: [
        '.....BBBBBBBBBBB',
        '....BTBBBBBBBBBB',
        '...BTBBBBBBBBBBB',
        '...BTBBBBBBBBBBB',
        '...BTBBBBBBBBBBB',
        '...BBBBBBBBBBBBB',
        '....BBBBBBBBBBBB',
        '.....BBBBBBBBBBB',
      ],
    },
    {
      mirror: true,
      y: 2,
      rows: [
        '...........WWWWW',
        '.........WWSSSSS',
        '........GWSSSSSS',
        '.......GGWWWWWWW',
        '......GGGGGGGGGG',
        '.....GGGGGGGGGGG',
        '.....GGGLLLLLLLL',
        '.....GGLLLLLLLLL',
        '.....GGLLWWLLLLL',
        '.....GGLLWoLLLLL',
        '.....GLLLWoLLLLL',
        '......LLpLLLLYYY',
        '......LLLLLLYYYY',
        '......LLLLLLYooo',
        '.......LLLLLLYYY',
        '........LLLLLLLL',
        '.......LLLLLLLLL',
        '......LLLLLLEEEE',
        '......LLLLLEEEEE',
        '......LLLLLEEEEE',
        '......LLLLLEEEEE',
        '......LLLLLEEEEE',
        '.......LLLLLEEEE',
        '.......LLLLLLEEE',
        '........LLLLLLLL',
        '..........LLL...',
        '..........LLL...',
        '.........LLLL...',
        '.........GGGG...',
      ],
    },
    // おさらの 水の ひかり
    { x: 12, y: 3, rows: ['WW'] },
    // 左うで（下ろす）
    { x: 4, y: 19, rows: ['.LL', 'LLL', 'LL.', 'LL.', 'GG.'] },
    // 右うで（きゅうりを かかげる）
    {
      x: 23,
      y: 2,
      rows: [
        '......Y.',
        '.....GMG',
        '.....GGG',
        '.....MGG',
        '.....GGM',
        '.....GGG',
        '.....GMG',
        '.....MGG',
        '.....GGG',
        '.....GMG',
        '.....LLL',
        '.....LLL',
        '....LL..',
        '....LL..',
        '...LL...',
        '...LL...',
        '..LL....',
        '.LL.....',
      ],
    },
  ],
};

/** テツビンガメ：南部鉄器の 鉄びんを こうらに した カメ。あられの ぽつぽつ・つる・注ぎ口（ツチ） */
const tetsubinGame: MonsterDesign = {
  size: 40,
  colors: {
    N: NQ.slate,
    n: NQ.gray,
    g: NQ.silver,
    T: NQ.tan,
    B: NQ.brown,
    S: NQ.sand,
    E: NQ.beige,
    Y: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.tan]: NQ.brown, [NQ.gold]: NQ.ochre, [NQ.slate]: NQ.night },
  rimDepth: 2,
  layers: [
    // 鉄びん（つる・ふた・どう）
    {
      mirror: true,
      y: 1,
      rows: [
        '...........ggggggggg',
        '.........NNNNNNNNNNN',
        '........NN..........',
        '.......NN...........',
        '.......NN.........NN',
        '......NN.........NNN',
        '......NN....NNNNNNNN',
        '......NN..NNNNNNNNNN',
        '.......NNNNNNNNNNNNN',
        '......NNNNNNNNNNNNNN',
        '.....NNnNNnNNnNNnNNn',
        '....NNNNNNNNNNNNNNNN',
        '....NNNNNNNNNNNNNNNN',
        '....NnNNnNNnNNNNNNNN',
        '....NNNNNNNNNNNNNNNN',
        '....NNNNNNNNNNNNNNNN',
        '....NNnNNnNNNNNNNNNN',
        '....NNNNNNNNNNNNNNNN',
        '....NNNNNNNNNNNNNNNN',
        '....NnNNnNNnNNNNNNNN',
        '....NNNNNNNNNNNNNNNN',
        '....NNNNNNNNNNNNNNNN',
        '....NNnNNnNNNNNNNNNN',
        '....NNNNNNNNNNNNNNNN',
        '.....NNNNNNNNNNNNNNN',
        '......NNNNNNNNNNNNNN',
      ],
    },
    // 注ぎ口（右）
    { x: 33, y: 7, rows: ['....gN', '...gNN', '...NNN', '..NNN.', '.NNN..', 'NNN...', 'NN....'] },
    // 前足
    {
      mirror: true,
      y: 24,
      rows: [
        '.....TTTTTT.........',
        '....TTTTTTTT........',
        '...TTTTTTTTT........',
        '...TTTTTTTTT........',
        '...TTBTTTTTT........',
        '...TTTTTTTTT........',
        '...TTTTTBTTT........',
        '...TTTTTTTTT........',
        '...TTBTTTTTT........',
        '...TTTTTTTTT........',
        '...TTTTTTBTT........',
        '..TTTTTTTTTT........',
        '..TTTTTTTTTT........',
        '..TTTTTTTTTT........',
        '..EETEETEETT........',
      ],
    },
    // 王冠・頭・首・おなか
    {
      mirror: true,
      y: 8,
      rows: [
        '...............Y..Y.',
        '...............YY.YY',
        '...............YYYYR',
        '...............YYYYR',
        '...............QQQQQ',
        '..............TTTTTT',
        '.............TTTTTTT',
        '............oTTTTTTT',
        '...........TToooTTTT',
        '...........TTWWWTTTT',
        '...........TTWWoTTTT',
        '...........TTWWoTTTT',
        '...........TTWooTTTT',
        '...........TpTTTTTSS',
        '............TTTTSSSS',
        '............TTTSSoSS',
        '.............TTSSSSS',
        '.............TTooooo',
        '..............TTTTSS',
        '...............TTTTT',
        '..............TBTTTT',
        '............EEEEEEEE',
        '............EEEEEEEE',
        '............EEEEEEEE',
        '............SSSSSSSS',
        '............EEEEEEEE',
        '............EEEEEEEE',
        '............SSSSSSSS',
        '.............EEEEEEE',
        '..............EEEEEE',
      ],
    },
    // 鉄の つや（左上）・頭の つや
    { x: 5, y: 10, rows: ['...gg', '.gg..', 'g....', 'g....'] },
    { x: 13, y: 14, rows: ['.S', 'S.'] },
  ],
};

/** テツビンガメ 後半（ヒノ）：鉄びんが まっ赤に 焼けて、ひびが 光り、注ぎ口から ゆげ */
const tetsubinGameHot: MonsterDesign = {
  ...tetsubinGame,
  colors: { ...tetsubinGame.colors, N: NQ.brick, n: NQ.vermilion, g: NQ.apricot, H: NQ.white, C: NQ.cloud },
  rim: { [NQ.tan]: NQ.brown, [NQ.gold]: NQ.ochre, [NQ.brick]: NQ.bark },
  layers: [
    ...tetsubinGame.layers,
    // 光る ひび
    { x: 6, y: 12, rows: ['..Y', '...Y', '..Y.', '.Y..', '..Y.', '...Y', '..Y.'] },
    { x: 29, y: 13, rows: ['.Y', 'Y.', '.Y', '..Y', '.Y', 'Y.'] },
    { x: 13, y: 9, rows: ['Y...', '.YY.', '...Y'] },
    // ゆげ
    { x: 32, y: 1, rows: ['..HHC', '.HHHH', 'HHCHH', '.HHC.', '..HH.', '...H.'] },
  ],
};

/** テツビンガメ（フィールドに立つ 32×32） */
const tetsubinGameField: MonsterDesign = {
  size: 32,
  colors: {
    N: NQ.slate,
    n: NQ.gray,
    T: NQ.tan,
    B: NQ.brown,
    S: NQ.sand,
    E: NQ.beige,
    Y: NQ.gold,
    R: NQ.red,
    W: NQ.white,
  },
  rim: { [NQ.tan]: NQ.brown, [NQ.gold]: NQ.ochre, [NQ.slate]: NQ.night },
  layers: [
    {
      mirror: true,
      y: 1,
      rows: [
        '.........nnnnnnn',
        '........NNNNNNNN',
        '.......NN.......',
        '......NN.....NNN',
        '......NN..NNNNNN',
        '......NNNNNNNNNN',
        '.....NNnNNnNNNNN',
        '....NNNNNNNNNNNN',
        '....NNNNNNNNNNNN',
        '....NnNNnNNNNNNN',
        '....NNNNNNNNNNNN',
        '....NNNNNNNNNNNN',
        '....NnNNnNNNNNNN',
        '....NNNNNNNNNNNN',
        '....NNNNNNNNNNNN',
        '.....NNNNNNNNNNN',
        '.....NNNNNNNNNNN',
        '......NNNNNNNNNN',
      ],
    },
    { x: 26, y: 3, rows: ['...nN', '..nNN', '..NN.', '.NN..', 'NN...'] },
    {
      mirror: true,
      y: 18,
      rows: [
        '....TTTTT.......',
        '...TTTTTT.......',
        '...TTTTTT.......',
        '...TTBTTT.......',
        '...TTTTTT.......',
        '...TTTTBT.......',
        '...TTTTTT.......',
        '...TTBTTT.......',
        '...TTTTTT.......',
        '..TTTTTTT.......',
        '..TTTTTTT.......',
        '..EETEETT.......',
      ],
    },
    {
      mirror: true,
      y: 6,
      rows: [
        '............Y..Y',
        '............YYYY',
        '............YYYR',
        '...........TTTTT',
        '..........TTTTTT',
        '.........TooTTTT',
        '.........TWWTTTT',
        '.........TWoTTTT',
        '.........TWoTTTT',
        '.........TTTTTSS',
        '.........TTTTSSS',
        '..........TTTooo',
        '...........TTTTS',
        '...........TTTTT',
        '.........EEEEEEE',
        '.........EEEEEEE',
        '.........SSSSSSS',
        '.........EEEEEEE',
        '.........EEEEEEE',
        '.........SSSSSSS',
        '.........EEEEEEE',
        '..........EEEEEE',
        '...........EEEEE',
      ],
    },
  ],
};

/** 光の 後光：まん中から のびる とげとげの 光（左右対称）。C = 光、L = 先っぽ。squash で たてに つぶす */
function rays(
  size: number,
  cy: number,
  rIn: number,
  rOut: number,
  n: number,
  bottom: number,
  gap = 0,
  squash = 1,
): string[] {
  const cx = (size - 1) / 2;
  return Array.from({ length: size }, (_, y) =>
    Array.from({ length: size }, (_, x) => {
      const d = Math.hypot(x - cx, (y - cy) * squash);
      const a = Math.abs(Math.atan2(x - cx, cy - y));
      const u = (a / ((2 * Math.PI) / n)) % 1;
      // 真上（gap より内側）は とげを 出さない：王冠を 見せる
      const r = a < gap ? 0 : rIn + (rOut - rIn) * (1 - 2 * Math.min(u, 1 - u));
      if (d > r || y > bottom || x < 1 || y < 1 || x > size - 2) return '.';
      return d > r - 2.5 ? 'L' : 'C';
    }).join(''),
  );
}

/**
 * 地図の まわり 1 ドットを ink にする（後光の上に 重ねる部品を くっきり させる）。
 * 1 ドット 大きく なるので x-1, y-1 に 置く。half = mirror 用の左半分（まん中の はしには 足さない）
 */
function ring(rows: readonly string[], half = false): string[] {
  const w = Math.max(...rows.map((r) => r.length));
  const at = (x: number, y: number) => (rows[y]?.[x] ?? '.') !== '.';
  return Array.from({ length: rows.length + 2 }, (_, j) =>
    Array.from({ length: w + (half ? 1 : 2) }, (_, i) => {
      const x = i - 1;
      const y = j - 1;
      return !at(x, y) && (at(x - 1, y) || at(x + 1, y) || at(x, y - 1) || at(x, y + 1)) ? 'o' : '.';
    }).join(''),
  );
}

const TORA_TAIL = [
  '.oo...',
  'oOOO..',
  '.OoOO.',
  '...OOO',
  '...OoO',
  '...OOO',
  '...OOO',
  '...oOO',
  '...OOO',
  '...OOO',
  '...OoO',
  '...OOO',
];
/** 肩あて・むね当て・前足（左半分、y 19〜） */
const TORA_BODY = [
  '......OOOOOOO...........',
  '....OOOOOOOOOOO.........',
  '...GGGGGOOOOOOOO........',
  '..GGGGGGGGOOOOOOOO......',
  '.GGGGGGGGGGOOOOOOOOO....',
  '.GGGGRRGGGGGOOOOOOOOGGGG',
  '.GGGGGGGGGGGOOOOOOOGGGGG',
  '.QGGGGGGGGGQOOOOOOGGGGRR',
  '..QQGGGGGQQOOOOOOGGGGGRR',
  '....QQQQQOOOOOOOOGGGGGGG',
  '...OOOOOOOOOOOOOOQGGGGGG',
  '...ooooOOOOOOOOOOOQGGGGG',
  '...OooOOOOOOOOOOOOOQQQQQ',
  '...OOOOOOOOOOOoOOOOOWWWW',
  '...OOOOOOOoooooOOOOOWWWW',
  '...OOOOOOOOooOoOOOOOWWWW',
  '..OOOOOOOOOOOOoOOOOOWWWW',
  '..ooooOOOOOOOOoOOOOWWWWW',
  '..OooOOOOOOOOOoOOOOWWWWW',
  '..OOOOOOOOOOOOoOOOOOWWWW',
  '..OOOOOOOOoooooOOOOOOWWW',
  '..OOOOOOOOOooOoOOOOOOO..',
  '.OOOOOOOOOOOOOOo........',
  '.OOOOOOOOOOOOOOO........',
  '.OOOOoOOOOoOOOOO........',
  '.OOOOoOOOOoOOOOO........',
  '...W....W....W..........',
  '...W....W....W..........',
];
/** 耳・頭（光る目・白い ほおの毛・小さく ほえる 口）（左半分、y 4〜） */
const TORA_HEAD = [
  '..............OO........',
  '.............OOOO.......',
  '.............OWWO.......',
  '.............OWWOOOOOOOO',
  '............OOOOOOOOoOoO',
  '...........OoOOOOOOOoOoo',
  '...........OoOOOOOOOOOOo',
  '..........WOOOOOOOOOOOOO',
  '.........WWOooOOOOOOOOOO',
  '.........WOOEEooOOOOOOOO',
  '........WWOOEEeeooOOOOOO',
  '........WOOOOoeWeoOOOOOO',
  '........WWOOOOOoooOOOOOO',
  '........WOoooOOOOOOWWooo',
  '.........WOOOOOOOOWWWWoo',
  '.........WWOOOOOOWWWWWWo',
  '..........WOOOOOOWWWWooo',
  '..........WWOOOOOWWWoWbb',
  '...........WOOOOOOWWoooo',
  '............OOOOOOOWWWWW',
];
/** 王冠（耳の あいだ、左半分、y 1〜） */
const TORA_CROWN = [
  '.......................G',
  '...................G...G',
  '...................GG.GG',
  '...................GGGGG',
  '...................GGGGR',
  '...................GGGGR',
  '...................QQQQQ',
];

/** コンジキノトラ：平泉の 金色の 光を 背負った トラ。広い 肩・金の よろい・太い しま・大きな 前足（ヒカリ） */
const konjikiNoTora: MonsterDesign = {
  size: 48,
  colors: {
    O: NQ.orange,
    Y: NQ.yellow,
    C: NQ.cream,
    L: NQ.white,
    W: NQ.white,
    E: NQ.cream,
    e: NQ.yellow,
    G: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
    b: NQ.berry,
  },
  rim: { [NQ.orange]: NQ.amber, [NQ.gold]: NQ.ochre },
  rimDepth: 2,
  layers: [
    // 金色の 後光（頭と肩の うしろ）
    { rows: rays(48, 15, 13, 25, 12, 26, 0.3, 1.35) },
    // しっぽ（右の肩の うしろで まきあがる）
    { x: 40, y: 8, rows: ring(TORA_TAIL) },
    { x: 41, y: 9, rows: TORA_TAIL },
    { mirror: true, x: -1, y: 18, rows: ring(TORA_BODY, true) },
    { mirror: true, y: 19, rows: TORA_BODY },
    { mirror: true, x: -1, y: 3, rows: ring(TORA_HEAD, true) },
    { mirror: true, y: 4, rows: TORA_HEAD },
    { mirror: true, x: -1, y: 0, rows: ring(TORA_CROWN, true) },
    { mirror: true, y: 1, rows: TORA_CROWN },
    // 毛の つや（左上）
    { x: 14, y: 8, rows: ['YY', 'Y.'] },
  ],
};

/** コンジキノトラ 後半：後光が 大きく まぶしく なり、目が 白く 光る */
const konjikiNoToraP0: MonsterDesign = {
  ...konjikiNoTora,
  colors: { ...konjikiNoTora.colors, C: NQ.white, L: NQ.cream, E: NQ.white, e: NQ.white },
  layers: [
    { rows: rays(48, 15, 14, 26, 16, 28, 0.25, 1.3) },
    ...konjikiNoTora.layers.slice(1),
    // きらきら
    { x: 2, y: 2, rows: ['.L.', 'LCL', '.L.'] },
    { x: 43, y: 2, rows: ['.L.', 'LCL', '.L.'] },
    { x: 8, y: 1, rows: ['C'] },
  ],
};

// ───────────────────────── しんか ─────────────────────────

/** はし 2 本（左上が 先）と、はしで すくった そば */
const HASHI = [
  '.HH.HH.......',
  'E.HH.HH......',
  'E..HH.HH.....',
  'E...HH.HH....',
  '.....HH.HH...',
  '......HH.HH..',
  '.......HH.HH.',
  '........HH.HH',
];

/** オカワリバット：ワンコソバットの しんか。おわんの 塔が 高く なり、そばが 山もり。はしで そばを すくって「おかわり！」（カゼ） */
const okawariBat: MonsterDesign = {
  size: 32,
  colors: {
    A: NQ.aqua,
    T: NQ.teal,
    M: NQ.mint,
    N: NQ.night,
    n: NQ.slate,
    R: NQ.red,
    E: NQ.beige,
    S: NQ.sand,
    W: NQ.white,
    p: NQ.blush,
    H: NQ.tan,
  },
  rim: { [NQ.aqua]: NQ.teal },
  layers: [
    // 大きな つばさ（頭の上から ひろげる）
    {
      mirror: true,
      y: 1,
      rows: [
        '.T.......',
        '.TT......',
        '.TMT.....',
        '.AMMT....',
        '.AAMMT...',
        '.AAAMMT..',
        '.AAAAMMT.',
        '.AAAAAMMT',
        '.AAAATTAA',
        '.AAATTAAA',
        '.AATTAAAA',
        '.ATTAAAAA',
        '.TAAAAAAA',
        '.AAAAAAAA',
        '.AAAAAAAA',
        '.AA..AAAA',
        '.A....AAA',
        '.......AA',
      ],
    },
    // 耳・山もりの そば・いちばん上の おわん（顔）・4 だんの おわん
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '................',
        '.......A........',
        '.......AA...EEEE',
        '.......ApA.EESSS',
        '.......AAAEESEEE',
        '.........ESEESSS',
        '......RRRESEESEE',
        '.....RRRSEESSEEE',
        '.....RRSEESEEESS',
        '.....NRRRRRRRRRR',
        '.....NNNNNNNNNNN',
        '.....NNNWWWNNNNN',
        '.....NNNWoWNNNNN',
        '.....NNNWWWNNNNN',
        '......NppNNNRRRR',
        '......NNNNNNRWpp',
        '.......NNNNNNRRR',
        '.........NNNNNNN',
        '.......RRRRRRRRR',
        '.......NNNNNNNNN',
        '.........NNNNNNN',
        '........RRRRRRRR',
        '........NNNNNNNN',
        '..........NNNNNN',
        '.........RRRRRRR',
        '.........NNNNNNN',
        '...........NNNNN',
        '............TT..',
        '............TT..',
      ],
    },
    // そばが ふちから たれる
    { x: 7, y: 11, rows: ['E', 'E', 'E'] },
    { x: 25, y: 11, rows: ['E', 'E'] },
    // はし（右の つばさで もって、そばを すくう）と すくった そば
    { x: 15, y: 0, rows: ring(HASHI) },
    { x: 16, y: 1, rows: HASHI },
    // うるしの つや（左上）
    { x: 6, y: 12, rows: ['n', 'n'] },
    { x: 8, y: 21, rows: ['nn'] },
    { x: 9, y: 24, rows: ['nn'] },
    { x: 10, y: 27, rows: ['nn'] },
  ],
};

/** ドラゴンブルー：リュウセンウオの しんか。金の えだ角・たてがみ・ひげ・つめの ある 青い 竜（ミズ） */
const dragonBlue: MonsterDesign = {
  size: 32,
  colors: {
    A: NQ.azure,
    S: NQ.sky,
    I: NQ.ice,
    W: NQ.white,
    Y: NQ.gold,
    m: NQ.mint,
    p: NQ.blush,
  },
  rim: { [NQ.azure]: NQ.blue, [NQ.ice]: NQ.sky, [NQ.gold]: NQ.ochre },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '....Y...........',
        '....YY.Y......I.',
        '.....YYY.....ISI',
        '......YY....ISSI',
        '.......YY..ISSII',
        '.....I..YAAAAAAA',
        '....IIIAAooAAAAA',
        '.....IAAAAAAAAAA',
        '....IIAAAWWAAAAA',
        '.....IAAAWoAAAAA',
        '....IIAAAWoAAAAA',
        '.....IAApAAASSSS',
        '..mmmAAAAASSSSSS',
        '.m....AAASSSSoSS',
        '.m.....AAASSSSSS',
        '..m.....AAASSSSS',
        '.........AAAAAAA',
        '.....II..AAAAAAA',
        '....ISSI.AAAASSS',
        '...WISSIAAASSSSS',
        '....WIIAAAASSSSS',
        '.......AAAAISSSS',
        '........AAASSSSS',
        '........AAAISSSS',
        '.........AAASSSS',
        '.........AAAAAAA',
        '.......IIIIIAAAA',
        '.....IIISSSIIA..',
        '...IIISSSII.....',
        '...IIII.........',
      ],
    },
    // つや（左上）・光る つぶ
    { x: 10, y: 6, rows: ['SS', 'W.'] },
    { x: 10, y: 20, rows: ['m'] },
    { x: 20, y: 23, rows: ['m'] },
  ],
};

/** オオカッパ：トオノカッパの しんか。大きな こうら・光る おさら・力こぶ・きゅうりの こんぼう（ミズ） */
const ooKappa: MonsterDesign = {
  size: 32,
  colors: {
    L: NQ.leaf,
    G: NQ.green,
    M: NQ.lime,
    E: NQ.sprout,
    Y: NQ.yellow,
    S: NQ.sky,
    W: NQ.white,
    p: NQ.blush,
    B: NQ.brown,
    T: NQ.tan,
  },
  rim: { [NQ.leaf]: NQ.green, [NQ.brown]: NQ.bark },
  layers: [
    // こうら（うしろ）
    {
      mirror: true,
      y: 12,
      rows: [
        '.....BBBBBBBBBBB',
        '...BBTBBBBBBBBBB',
        '..BTBBBBBBBBBBBB',
        '..BTBBBBBBBBBBBB',
        '.BTBBBBBBBBBBBBB',
        '.BTBBBBBBBBBBBBB',
        '.BBTBBBBBBBBBBBB',
        '.BTBBBBBBBBBBBBB',
        '.BBBBBBBBBBBBBBB',
        '.BTBBBBBBBBBBBBB',
        '..BBBBBBBBBBBBBB',
        '..BBBBBBBBBBBBBB',
        '...BBBBBBBBBBBBB',
        '....BBBBBBBBBBBB',
        '......BBBBBBBBBB',
      ],
    },
    // おさら・かみの とげ・大きな くちばし・ひろい かた・6 つに われた おなか
    // （頭は かたより せまく して、力こぶの うでや こんぼうとの あいだに すきまを あける）
    {
      mirror: true,
      rows: [
        '................',
        '...........WWWWW',
        '.........WWSSSSS',
        '........GWSSSSSS',
        '......G.GWWWWWWW',
        '......GGGGGGGGGG',
        '.....G.GGGGGGGGG',
        '......GGLLLLLLLL',
        '......GLLLWWLLLL',
        '......GLLLWoLLLL',
        '......GLLLWoLLLL',
        '......LLLpLLYYYY',
        '......LLLLLYYYYY',
        '......LLLLLYoooo',
        '.......LLLLLYYYY',
        '....LLLLLLLLLLLL',
        '...LLLLLLLLLLLLL',
        '...LLLLLLLLLLLLL',
        '....LLLLLLLEEEEE',
        '....LLLLLLEEEEEE',
        '.....LLLLLEEMMEE',
        '.....LLLLLEEEEEE',
        '.....LLLLLEEMMEE',
        '......LLLLEEEEEE',
        '......LLLLLEEEEE',
        '.......LLLLLLLLL',
        '.......LLLLLLLLL',
        '........LLLL....',
        '.......LLLLL....',
        '......LLLLLL....',
        '......GGGGGG....',
      ],
    },
    // おさらの 水の ひかり
    { x: 11, y: 2, rows: ['WW', 'W.'] },
    // 左うで（力こぶ。こぶしと 前うでは 頭から 1 マス はなす）
    {
      x: 1,
      y: 6,
      rows: [
        '.LL.....',
        'LLLL....',
        'LMLL....',
        'GLLG....',
        '.LL.....',
        '.LL.....',
        '.LLL....',
        '.LLLL...',
        '.LLLLL..',
        'LLMMLLLL',
        'LLLLLLLL',
        '.LLLLLLL',
      ],
    },
    // 右うで（先に 黄色い 花の ついた きゅうりの こんぼうを かかげる。手も 頭から 1 マス はなす）
    {
      x: 24,
      y: 1,
      rows: [
        '....YY.',
        '...GGGG',
        '...GMGG',
        '...GGMG',
        '...MGGG',
        '...GGMG',
        '...GMGG',
        '...GGGM',
        '...MGGG',
        '...GGMG',
        '...GGGG',
        '...LLLL',
        '...LLLL',
        '..LLL..',
        '.LLL...',
        'LL.....',
      ],
    },
  ],
};

/** イワカモシカ：岩手の県獣 カモシカ。もこもこの 灰茶の毛・白っぽい ほおひげ・うしろへ 反った 黒い つの（ツチ） */
const iwaKamoshika: MonsterDesign = {
  size: 32,
  colors: {
    C: NQ.gray,
    c: NQ.slate,
    S: NQ.silver,
    F: NQ.cloud,
    H: NQ.night,
    B: NQ.bark,
    T: NQ.tan,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.gray]: NQ.slate, [NQ.cloud]: NQ.silver },
  rimDepth: 1,
  layers: [
    // つの（細く、先が 外へ 反る。ふしの しま）
    {
      mirror: true,
      y: 2,
      rows: [
        '.......H........',
        '........H.......',
        '........cH......',
        '.........H......',
        '.........cH.....',
        '..........H.....',
      ],
    },
    // 耳（横に ぴんと）
    {
      mirror: true,
      y: 9,
      rows: ['..CCCC..........', '.CTTTCC.........', '.CCTTCC.........', '...CCC..........'],
    },
    // 頭と からだ
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
        '...........CCCCC',
        '.........CCCCCCC',
        '........CCCCCCCC',
        '.......CCCCCCCCC',
        '......CCCCCCCCCC',
        '.....CCCCCCCCCCC',
        '.....CCCCCCCCCCC',
        '.....CCCCCCCCCCC',
        '.....CCCCCCCCCCC',
        '.....CCCCCCCCCCC',
        '......CCCCCCCCCC',
        '......CCCCCCCCCC',
        '.......CCCCCCCCC',
        '......CCCCCCCCCC',
        '.....CCCCCCCCCCC',
        '....CCCCCCCCCCCC',
        '.....CCCCCCCCCCC',
        '....CCCCCCCCCCCC',
        '.....CCCCCCCCCCC',
        '.....CCCCCCCCCCC',
        '......CCCCCCCCCC',
        '.....CcC.CCCc...',
        '.....BBB.CCCc...',
        '........BBBBB...',
        '................',
        '................',
      ],
    },
    // ほおひげと のどの 毛（白っぽい もこもこ）
    {
      mirror: true,
      y: 13,
      rows: [
        '....F...........',
        '...FFF..........',
        '..FFFFF.........',
        '...FFFFF........',
        '..FFFFFFF.......',
        '...FFFFFFFFFFFFF',
        '....FFFFFFFFFFFF',
        '......FFFFFFFFFF',
        '.........FFFFFFF',
        '............FFFF',
      ],
    },
    // 鼻づら
    {
      mirror: true,
      y: 14,
      rows: ['............FFFF', '...........FFFFF', '...........FFFFF', '...........FFFFF'],
    },
    // おでこの もじゃもじゃ・からだの 毛なみ
    {
      mirror: true,
      y: 6,
      rows: [
        '...............S',
        '.............SSS',
        '............SSCS',
        '............S.SS',
        '..............S.',
      ],
    },
    { mirror: true, y: 21, rows: ['.....S..........', '......S.........', '.....S..........'] },
    // かお
    {
      mirror: true,
      y: 11,
      rows: [
        '.........WWo....',
        '.........Woo....',
        '.........ooo....',
        '........pp......',
        '.............BBB',
        '..............BB',
        '...............o',
        '.............oo.',
      ],
    },
    // つや・ひづめの 割れめ
    { x: 9, y: 8, rows: ['SS', 'S.'] },
    { mirror: true, y: 29, rows: ['..........o.....'] },
  ],
};

/** ハヤテカモシカ：イワカモシカの しんか。なびく 白い たてがみ・とがった つの・しめなわの マフラー・足もとに 風（ツチ） */
const hayateKamoshika: MonsterDesign = {
  size: 32,
  colors: {
    C: NQ.gray,
    c: NQ.slate,
    S: NQ.silver,
    F: NQ.cloud,
    W: NQ.white,
    H: NQ.night,
    B: NQ.bark,
    R: NQ.sand,
    r: NQ.tan,
    K: NQ.sky,
  },
  rim: { [NQ.gray]: NQ.slate, [NQ.cloud]: NQ.silver, [NQ.sand]: NQ.tan },
  rimDepth: 1,
  layers: [
    // たてがみ（左右へ 長く 流れる。毛先は とがって 外へ はねる）
    {
      mirror: true,
      y: 5,
      rows: [
        '..........FF....',
        '........FFFF....',
        '......WFFFFF....',
        '....WWFFFFF.....',
        '..WWFFFFFFF.....',
        '.WFFFFFFFFF.....',
        '..FFFFFFFFF.....',
        '....FFFFFFF.....',
        '..FFFFFFFFF.....',
        '.FFFFFFFFFF.....',
        '..FFFFFFFFFF....',
        '....FFFFFFFF....',
        '..FFFFFFFFFF....',
        '.FFFFFFFFFFFF...',
        '..FFFFFFFFFFFF..',
        '...FFFFFFFFFFFFF',
        '.....FFFFFFFFFFF',
        '.......FFFFF....',
        '.........FF.....',
      ],
    },
    {
      mirror: true,
      y: 9,
      rows: [
        '.......S........',
        '......S..S......',
        '.....S..S.......',
        '.......S........',
        '......S..S......',
        '.....S..S.......',
        '....S..S........',
        '......S..S......',
        '.....S..S.......',
        '....S..S........',
        '......S.........',
      ],
    },
    // つの（長く とがる。ふしの しま）
    {
      mirror: true,
      y: 1,
      rows: [
        '......H.........',
        '......cH........',
        '.......H........',
        '.......cH.......',
        '........H.......',
        '........cH......',
        '.........HH.....',
      ],
    },
    // 耳
    { mirror: true, y: 10, rows: ['...CCCC.........', '..CRRRCC........', '...CCCC.........'] },
    // 頭・からだ・足
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
        '...........CCCCC',
        '..........CCCCCC',
        '.........CCCCCCC',
        '........CCCCCCCC',
        '........CCCCCCCC',
        '........CCCCCCCC',
        '........CCCCCCCC',
        '........CCCCCCCC',
        '.........CCCCCCC',
        '.........CCCCCCC',
        '..........CCCCCC',
        '........CCCCCCCC',
        '.......CCCCCCCCC',
        '......CCCCCCCCCC',
        '......CCCCCCCCCC',
        '......CCCCCCCCCC',
        '......CCCCCCCCCC',
        '......CCCCCCCCCC',
        '......CCCCCCC...',
        '......CcC.CCC...',
        '......CcC.CCC...',
        '......BBB.CCC...',
        '..........BBB...',
      ],
    },
    // 鼻づら
    {
      mirror: true,
      y: 14,
      rows: ['............FFFF', '...........FFFFF', '...........FFFFF', '............FFFF'],
    },
    // かお（きりっと）
    {
      mirror: true,
      y: 10,
      rows: [
        '.........oo.....',
        '...........oo...',
        '.........WWo....',
        '.........Woo....',
        '................',
        '..............BB',
        '...............B',
        '..............oo',
      ],
    },
    // しめなわの マフラー（ねじった わら）
    {
      y: 18,
      rows: [
        '........RrRR........RrRR........',
        '........rRRrRR....RRrRRr........',
        '.........RrRRrRRrRRrRRr.........',
        '...........RrRRrRRrRR...........',
      ],
    },
    // むねの 白い 毛
    { x: 12, y: 22, rows: ['FFFFFFFF', '.FFFFFF.', '..FFFF..'] },
    // マフラーの はし（右へ なびく。先は ほつれた わら）
    { x: 23, y: 19, rows: ['RrR.....', '.RRrRR..', '...RrRRR', '....R.R.'] },
    // 足もとの 風
    { x: 1, y: 24, rows: ['KKWW..', '......', '......', '..KKWW'] },
    { x: 26, y: 25, rows: ['.WWKK', '.....', '.....', 'WWKK.'] },
  ],
};

/** ワカメッコ：三陸の わかめの 子。波に あわせて ゆれる ひらひらの 葉、あわ（モリ） */
const wakamekko: MonsterDesign = {
  size: 32,
  colors: {
    G: NQ.green,
    F: NQ.forest,
    L: NQ.leaf,
    l: NQ.lime,
    W: NQ.white,
    p: NQ.blush,
    S: NQ.sky,
    A: NQ.azure,
  },
  rim: { [NQ.green]: NQ.forest },
  layers: [
    // ひらひらの うで
    { mirror: true, x: 1, y: 14, rows: ['..lL', '.lLL', 'lLLG', '.lLL', '..lL'] },
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '.............FFF',
        '...........FFGGG',
        '.........FFGGGGG',
        '........FGGGGGGG',
        '.......FGGGGGGGG',
        '......FGGGGGGGGG',
        '.....FGGGGGGGGGG',
        '.....FGGGGGGGGGG',
        '....FGGGGGGGGGGG',
        '....FGGGGGGGGGGG',
        '....FGGGGWWGGGGG',
        '....FGGGGWoGGGGG',
        '....FGGGGWoGGGGG',
        '....FGppGGGGGGGG',
        '....FGGGGGGGGGoG',
        '....FGGGGGGGGGGo',
        '....FGGGGGGGGGGG',
        '.....FGGGGGGGGGG',
        '.....FFGGGGGGGGG',
        '......FGGGGGGGGG',
        '.......FGGGGGGGG',
        '........FGGGGGGG',
        '.........FFGGGGG',
        '...........FGGGG',
        '............FGGG',
        '.............FGG',
        '..........LLL...',
        '..........LLL...',
        '..........LLL...',
      ],
    },
    // 葉の すじ・あわ
    { x: 12, y: 20, rows: ['l', 'l', 'l', 'l'] },
    { x: 2, y: 5, rows: ['.S.', 'SAS', '.S.'] },
    { x: 27, y: 20, rows: ['.S.', 'SAS', '.S.'] },
  ],
};

/** ワカメリュウ：ワカメッコの しんか。長い 葉を 竜の ように うねらせ、金の 目で 海を はしる（モリ） */
const wakameRyu: MonsterDesign = {
  size: 32,
  colors: {
    G: NQ.green,
    F: NQ.forest,
    L: NQ.leaf,
    l: NQ.lime,
    W: NQ.white,
    p: NQ.blush,
    S: NQ.sky,
    A: NQ.azure,
    Y: NQ.gold,
  },
  rim: { [NQ.green]: NQ.forest, [NQ.leaf]: NQ.green },
  layers: [
    // うねる 長い 葉（りょうがわ）
    {
      mirror: true,
      x: 1,
      y: 6,
      rows: [
        '...lL',
        '..lLL',
        '.lLLG',
        'lLLGG',
        'lLGG.',
        '.lLG.',
        '..lLG',
        '...lL',
        '..lLL',
        '.lLLG',
        'lLLGG',
        'lLGG.',
      ],
    },
    {
      mirror: true,
      rows: [
        '................',
        '............FFFF',
        '..........FFGGGG',
        '........FFGGGGGG',
        '.......FGGGGGGGG',
        '......FGGGGGGGGG',
        '......FGGGGGGGGG',
        '.....FGGGGGGGGGG',
        '.....FGGGooGGGGG',
        '.....FGGGGGoooGG',
        '.....FGGGGWWGGGG',
        '.....FGGGGWYGGGG',
        '.....FGGGGWYGGGG',
        '.....FGppGGGGGGG',
        '.....FGGGGGGGGoG',
        '.....FGGGGGGGGGo',
        '.....FGGGGGGGGGG',
        '.....FFGGGGGGGGG',
        '......FGGGGGGGGG',
        '......FGGGGGGGGG',
        '.......FGGGGGGGG',
        '.......FGGGGGGGG',
        '........FGGGGGGG',
        '........FGGGGGGG',
        '.........FGGGGGG',
        '.........FGGGGGG',
        '..........FGGGGG',
        '..........LLLLLL',
        '..........LLL...',
        '..........LLL...',
        '..........LLL...',
      ],
    },
    // 葉の すじ・あわ
    { x: 12, y: 22, rows: ['l', 'l', 'l', 'l'] },
    { x: 1, y: 3, rows: ['.S.', 'SAS', '.S.'] },
    { x: 27, y: 24, rows: ['.S.', 'SAS', '.S.'] },
  ],
};

export const IWATE: Readonly<Record<string, MonsterDesign>> = {
  'iwate-lastboss-minamoto-yoshitsune': LAST_BOSSES['iwate-lastboss-minamoto-yoshitsune']!,
  'iwate-wakamekko': wakamekko,
  'iwate-wakame-ryu': wakameRyu,
  'iwate-okawari-bat': okawariBat,
  'iwate-dragon-blue': dragonBlue,
  'iwate-oo-kappa': ooKappa,
  'iwate-boss-konjiki-no-tora': konjikiNoTora,
  'iwate-boss-konjiki-no-tora.p0': konjikiNoToraP0,
  'iwate-wankosobat': wankosobat,
  'iwate-ryusen-uo': ryusenUo,
  'iwate-tono-kappa': tonoKappa,
  'iwate-midboss-tetsubin-game': tetsubinGame,
  'iwate-midboss-tetsubin-game.p0': tetsubinGameHot,
  'iwate-midboss-tetsubin-game.field': tetsubinGameField,
  'iwate-iwa-kamoshika': iwaKamoshika,
  'iwate-hayate-kamoshika': hayateKamoshika,
};
