/** 香川県の モンスター（手描き。docs/06 §4・§6.3〜6.5 の 規格） */
import { NQ } from '../palette';
import type { MonsterDesign } from './design';

/** コロリーブ：小豆島の オリーブの 実。たて長の みどりの 実に、銀色の すじの ある 細長い 葉（モリ） */
const kororibu: MonsterDesign = {
  size: 32,
  colors: {
    L: NQ.leaf,
    G: NQ.green,
    M: NQ.lime,
    K: NQ.forest,
    s: NQ.silver,
    B: NQ.brown,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.leaf]: NQ.green },
  layers: [
    // 細長い オリーブの 葉（左は 大きく、右は 小さく）
    { x: 5, y: 1, rows: ['.KK', 'KKKK', 'KssKK', '.KKssKK', '...KKsKKK', '.....KKsKK', '........KK'] },
    { x: 17, y: 3, rows: ['.......KK', '....KKsKK', '.KKssKKK', 'KKKKK'] },
    {
      mirror: true,
      rows: [
        '',
        '',
        '',
        '',
        '',
        '...............B',
        '...............B',
        '...............B',
        '.............LLL',
        '...........LLLLL',
        '..........LLLLLL',
        '.........LLLLLLL',
        '........LLLLLLLL',
        '........LLLLLLLL',
        '.......LLLLLLLLL',
        '.......LLLLLLLLL',
        '.......LLLWWLLLL',
        '.......LLLWoLLLL',
        '.......LLLWoLLLL',
        '.......LppLLLLoL',
        '.......LLLLLLLLo',
        '.......LLLLLLLLL',
        '.......LLLLLLLLL',
        '.......LLLLLLLLL',
        '........LLLLLLLL',
        '........LLLLLLLL',
        '.........LLLLLLL',
        '..........LLLLLL',
        '............LLLL',
        '...........GGG',
        '...........GGG',
      ],
    },
    // つや（左上）
    { x: 9, y: 10, rows: ['.MM', 'MM.', 'M..'] },
  ],
};

/** ミノリーブ（コロリーブの しんか）：3 まいの 葉の かざり、両わきに じゅくした むらさきの 実、きりっと まゆ（モリ） */
const minoribu: MonsterDesign = {
  size: 32,
  colors: {
    L: NQ.leaf,
    G: NQ.green,
    M: NQ.lime,
    K: NQ.forest,
    s: NQ.silver,
    B: NQ.brown,
    V: NQ.violet,
    I: NQ.indigo,
    l: NQ.lavender,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.leaf]: NQ.green, [NQ.violet]: NQ.indigo },
  layers: [
    // 葉の かざり（まん中と ななめ 2 まい）
    {
      mirror: true,
      rows: [
        '',
        '...............K',
        '.....KK.......KK',
        '....KKKK......KG',
        '....KssKK.....KG',
        '.....KKssKK...KG',
        '.......KKKssK.KK',
        '.........KKKKK.K',
      ],
    },
    // じゅくした むらさきの 実（両わきに ぶらさがる）
    { mirror: true, x: 1, y: 5, rows: ['...B', '..B', '.lV', '.VVI', '.VII', '..I'] },
    {
      mirror: true,
      rows: [
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '.............LLL',
        '...........LLLLL',
        '.........LLLLLLL',
        '........LLLLLLLL',
        '.......LLLLLLLLL',
        '.......LLLLLLLLL',
        '......LLLLLLLLLL',
        '......LLLooLLLLL',
        '......LLLLLoLLLL',
        '......LLLLWWLLLL',
        '......LLLLWoLLLL',
        '......LLLLWoLLLL',
        '......LLppLLLoLL',
        '......LLLLLLLLoo',
        '......LLLLLLLLLL',
        '......LLLLLLLLLL',
        '......LLLLLLLLLL',
        '.......LLLLLLLLL',
        '.......LLLLLLLLL',
        '........LLLLLLLL',
        '.........LLLLLLL',
        '...........LLLLL',
        '..........GGG',
        '.........GGGG',
      ],
    },
    // うで
    { mirror: true, x: 3, y: 19, rows: ['.LL', 'LLL', 'LL.'] },
    // つや（左上）
    { x: 8, y: 9, rows: ['.MM', 'MM.', 'M..'] },
  ],
};

/** アオギン：丸亀うちわ。まるい 紙に 青い 波の もよう、竹の え が 1 本足、小さな 風の つばさ（カゼ） */
const aogin: MonsterDesign = {
  size: 32,
  colors: {
    T: NQ.teal,
    A: NQ.aqua,
    M: NQ.mint,
    W: NQ.white,
    P: NQ.paper,
    S: NQ.sand,
    B: NQ.brown,
    p: NQ.blush,
  },
  rim: { [NQ.sand]: NQ.tan, [NQ.aqua]: NQ.teal },
  layers: [
    // 風の つばさ
    { mirror: true, y: 9, rows: ['...TT', '..TAA', '.TAMA', '.TAAM', '.TAMA', '..TAA', '...TA'] },
    {
      mirror: true,
      rows: [
        '',
        '............TTTT',
        '..........TTPPPP',
        '.........TPPPPPP',
        '........TPPPPPPP',
        '.......TPPPPPPPP',
        '......TPPPPPPPPP',
        '......TPPPPPPPPP',
        '.....TPPPPPPPPPP',
        '.....TPPPPPPPPPP',
        '.....TPPPPPWoPPP',
        '.....TPPPPPooPPP',
        '.....TPPPPPooPPP',
        '.....TPPppPPPPoP',
        '.....TPPPPPPPPPo',
        '.....TPPPPPPPPPP',
        '.....TPPPPPPPPPP',
        '......TPMMPPPMMP',
        '......TMAAMPMAAM',
        '.......TAAAAAAAA',
        '........TAAMAAAA',
        '.........TAAAAAA',
        '...........TAAAA',
        '.............TTS',
        '...............S',
        '...............S',
        '...............S',
        '...............B',
        '...............S',
        '..............SS',
        '..............SS',
      ],
    },
    // 紙の つや
    { x: 8, y: 4, rows: ['.W', 'W.'] },
    // 風
    { x: 1, y: 22, rows: ['.MMW', 'M...', '.MM.'] },
    { x: 26, y: 25, rows: ['WMM.', '...M', '.MM.'] },
  ],
};

/** ツムジウチワ（アオギンの しんか）：大きく なった 風の つばさ、はちまき、きりっと まゆ、足もとに つむじ風（カゼ） */
const tsumujiUchiwa: MonsterDesign = {
  size: 32,
  colors: {
    T: NQ.teal,
    A: NQ.aqua,
    M: NQ.mint,
    W: NQ.white,
    P: NQ.paper,
    S: NQ.sand,
    B: NQ.brown,
    p: NQ.blush,
  },
  rim: { [NQ.sand]: NQ.tan, [NQ.aqua]: NQ.teal },
  layers: [
    // 大きな 風の つばさ（うしろから）
    {
      mirror: true,
      y: 3,
      rows: [
        '.T',
        '.TT',
        '.TAT',
        '.TAAT',
        '.TAMAT',
        '.TAAMAT',
        '.TAAAMAT',
        '..TAAAMA',
        '.TTAAAAA',
        '.TAMAAAA',
        '..TAMAAA',
        '.TTAAMAA',
        '.TAAAAMA',
        '..TTAAAA',
        '....TTAA',
      ],
    },
    {
      mirror: true,
      rows: [
        '',
        '',
        '',
        '',
        '',
        '............TTTT',
        '..........TTPPPP',
        '.........TPPPPPP',
        '........TAAAAAAA',
        '.......TPPPPPPPP',
        '.......TPPPPPPPP',
        '......TPPPooPPPP',
        '......TPPPPPoPPP',
        '......TPPPPWoPPP',
        '......TPPPPooPPP',
        '......TPPPPooPPP',
        '......TPppPPPPPP',
        '......TPPPPPPoPP',
        '......TPPPPPPPoo',
        '......TPMMPPPMMP',
        '.......TAAMPMAAM',
        '.......TAAAAAAAA',
        '........TAAMAAAA',
        '.........TAAAAAA',
        '..........TTAAAA',
        '............TTTS',
        '...............S',
        '...............S',
        '...............B',
        '..............SS',
        '..............SS',
      ],
    },
    // はちまきの むすび目（右へ なびく）
    { x: 24, y: 6, rows: ['..AA', '.AAA.A', 'AA..AA', '.....A'] },
    // 紙の つや
    { x: 10, y: 9, rows: ['W'] },
    // 足もとの 風
    { x: 1, y: 25, rows: ['.MMW', 'M...', '.MM.'] },
    { x: 26, y: 26, rows: ['WMM.', '...M', '.MM.'] },
  ],
};

const ZENI_COLORS = {
  S: NQ.sand,
  T: NQ.tan,
  B: NQ.brown,
  E: NQ.beige,
  R: NQ.red,
  A: NQ.apricot,
  W: NQ.white,
  p: NQ.blush,
};

/** ゼニガニ：銭形砂絵の 砂の カニ。こうらは 四角い あなの あいた まるい お金、目は 2 本の 柄の 先、赤い はさみ（ツチ） */
const zenigani: MonsterDesign = {
  size: 32,
  colors: ZENI_COLORS,
  rim: { [NQ.red]: NQ.brick },
  layers: [
    {
      mirror: true,
      rows: [
        '',
        '',
        '',
        '..R..R.....WW',
        '.RR..RR....Wo',
        '.ARRRRR....Wo',
        '.RRRRRR.....B',
        '..RRRR......B',
        '...RR.......B',
        '....RR......TTTT',
        '.....RR...TTSSSS',
        '......RR.TSSSSSS',
        '.......RTSSSSSoS',
        '.......TSSppSSSo',
        '.......TSSSSSTTT',
        '......TSSSSSST..',
        '......TSSBSSST..',
        '......TSSBSSST..',
        '......TSSSSSST..',
        '......TSSSSSSTTT',
        '......RTSSSSSSSS',
        '.....R.TSSSSSSSB',
        '....R...TSSSSSSB',
        '....R...RTSSSSSS',
        '...R...R..TTSSSS',
        '......R....RTTTT',
        '......R...R',
        '.....R....R',
        '.........R',
        '.........R',
      ],
    },
    // こうらの つや（左上）
    { x: 9, y: 11, rows: ['.E', 'E.'] },
  ],
};

/** オオゼニガニ（ゼニガニの しんか）：大きな お金の こうら、ふとい はさみを 高く、まゆの ついた 目、4 本ずつの 足（ツチ） */
const oozenigani: MonsterDesign = {
  size: 32,
  colors: ZENI_COLORS,
  rim: { [NQ.red]: NQ.brick },
  layers: [
    {
      mirror: true,
      rows: [
        '',
        '..RR..RR..oo',
        '.RRR..RR....o',
        '.RARRRRR...WW',
        '.RRRRRRR...Wo',
        '..RRRRR....Wo',
        '...RRR......B',
        '....RRR.....B',
        '.....RRR....B',
        '......RR...TTTTT',
        '.......RRTTSSSSS',
        '........TSSSSSSS',
        '.......TSSSSSSSS',
        '......TSSSSSoSSS',
        '......TSSSppSooo',
        '.....TSSSSSSSSSS',
        '.....TSSSSSSSTTT',
        '.....TSSSSSSST..',
        '.....TSSSBSSST..',
        '.....TSSSBSSST..',
        '....RTSSSSSSST..',
        '...R.TSSSSSSSTTT',
        '..R..RTSSSSSSSSS',
        '..R.R..TSSSSSSBB',
        '..R.R..RTSSSSSSS',
        '...R..R..TTSSSSS',
        '...R..R...RTTTTT',
        '.....R...R',
        '.....R...R',
        '........R',
      ],
    },
    // こうらの つや（左上）と ふちの 光
    { x: 8, y: 12, rows: ['.EE', 'EE.', 'E..'] },
  ],
};

/**
 * リツリンノヌシ（中ボス）：栗林公園の 池の ぬしの 大きな 錦鯉（紅白）。尾びれで 立ち、池から 水しぶきを あげる。
 * 頭の 赤い もように 王冠、まるく ひらいた 口、ひろげた むなびれ（ミズ）
 */
const ritsurinNoNushi: MonsterDesign = {
  size: 40,
  colors: {
    P: NQ.paper,
    C: NQ.cloud,
    W: NQ.white,
    R: NQ.red,
    r: NQ.brick,
    G: NQ.gold,
    Q: NQ.ochre,
    A: NQ.azure,
    S: NQ.sky,
    I: NQ.ice,
    B: NQ.blue,
    p: NQ.blush,
  },
  rim: { [NQ.paper]: NQ.cloud, [NQ.red]: NQ.brick, [NQ.azure]: NQ.blue },
  rimDepth: 2,
  layers: [
    // 池の 水しぶき（うしろ）
    {
      mirror: true,
      y: 29,
      rows: [
        '..I',
        '.ISI',
        '.SAS..I',
        '.AAAS.SI',
        '.AAAAAAS',
        '.BAAAAAAS',
        '..BAAAAAAAS',
        '..BBAAAAAAAAAAAAAAAA',
        '...BBBBBBBBBBBBBBBBB',
      ],
    },
    // むなびれ
    {
      mirror: true,
      y: 17,
      rows: [
        '.....PP',
        '...PPPP',
        '..PCPPP',
        '.PPPCPP',
        '.PCPPCP',
        '.PPCPPP',
        '..PPPCP',
        '...PPPP',
        '.....PP',
      ],
    },
    {
      mirror: true,
      rows: [
        '',
        '...............G...G',
        '...............GG.GG',
        '...............GGGGR',
        '...............QQQQQ',
        '...........RRRRRRRRR',
        '.........oRRRRRRRRRR',
        '........RRoooRRRRRRR',
        '.......RRRWWoRRRRRRR',
        '.......RRRWWoRRRRRRR',
        '.......RRRWWoRRRRRRR',
        '.......PRRWooRRRRRRR',
        '.......PPppPPPPPPPPP',
        '.......PPPPPPPPPPPoo',
        '.......PPPPPPPPPPorr',
        '........PPPPPPPPPorr',
        '........PPPPPPPPPPoo',
        '.......RRRPPPPCPPPPP',
        '.......RRRRPPPCPPPPP',
        '.......RRRRRPCPPCPPC',
        '.......RRRRRPPPPPPPP',
        '.......RRRRPPPCPPCPP',
        '.......PRRPPPPPPPPPP',
        '.......PPPPPCPPCPPCP',
        '.......PPPPPPPPPPPPP',
        '.......PPPPPPCPPPPPP',
        '.......PPPPPPPPPPPPP',
        '........PPPPPPPPPPPP',
        '.........PPPPPPPPPPP',
        '..........PPPPPPPPPP',
        '...........PPPPPPPPP',
        '............PPPPPPPP',
        '..........PPPPPPPPPP',
        '........PPCPPPPPPPPP',
        '......PPCPPPCPPPPPPP',
        '.....PPCPPPCPPPPPP',
        '....PPCPPPCPPPP',
        '...PPPPPPPPP',
        '....PPPPP',
      ],
    },
    // 口ひげ（2 本）
    { mirror: true, y: 16, rows: ['...............p', '..............p', '.............pp'] },
    // 水の しずく
    { x: 2, y: 8, rows: ['.I.', 'ISI', '.A.'] },
    { x: 35, y: 12, rows: ['.I.', 'ISI', '.A.'] },
    { x: 5, y: 2, rows: ['I.', 'SI'] },
  ],
};

/** リツリンノヌシ（フィールドに 立つ 32×32） */
const ritsurinNoNushiField: MonsterDesign = {
  size: 32,
  colors: {
    P: NQ.paper,
    C: NQ.cloud,
    W: NQ.white,
    R: NQ.red,
    r: NQ.brick,
    G: NQ.gold,
    Q: NQ.ochre,
    A: NQ.azure,
    S: NQ.sky,
    B: NQ.blue,
    p: NQ.blush,
  },
  rim: { [NQ.paper]: NQ.cloud, [NQ.red]: NQ.brick },
  layers: [
    { mirror: true, y: 25, rows: ['..S', '.SAS', '.AAAS', '..BAAAAAAAAAAAAA', '...BBBBBBBBBBBBB'] },
    { mirror: true, y: 13, rows: ['......P', '....PPP', '...PCPP', '...PPCP', '....PPP'] },
    {
      mirror: true,
      rows: [
        '',
        '............G..G',
        '............GGGR',
        '............QQQQ',
        '.........RRRRRRR',
        '........RRRRRRRR',
        '.......RRRWWRRRR',
        '.......RRRWoRRRR',
        '.......PRRWoRRRR',
        '.......PPpPPPooo',
        '.......PPPPPPorr',
        '........PPPPPorr',
        '........PPPPPPoo',
        '.......RRPPPPPPP',
        '.......RRRPCPPCP',
        '.......RRPPPPPPP',
        '.......PPPCPPCPP',
        '.......PPPPPPPPP',
        '........PPPPPPPP',
        '.........PPPPPPP',
        '..........PPPPPP',
        '...........PPPPP',
        '.........PPPPPPP',
        '.......PPCPPPPPP',
        '.....PPCPPPCPP',
        '....PPCPPPPP',
        '...PPPPPPP',
        '....PPPP',
      ],
    },
  ],
};

const UDON_COLORS = {
  P: NQ.paper,
  C: NQ.cloud,
  W: NQ.white,
  V: NQ.vermilion,
  A: NQ.apricot,
  Y: NQ.gold,
  G: NQ.gold,
  Q: NQ.ochre,
  J: NQ.red,
  D: NQ.red,
  r: NQ.brick,
  T: NQ.tan,
  L: NQ.lime,
  l: NQ.leaf,
};

/** オウドンリュウ（県ボス）：讃岐うどんの 大がまから 立ちのぼる 竜。白い めんの からだ、金の つのと 王冠、ねぎ、うしろに 炎（ヒノ） */
const oudonRyuLayers = [
  // うしろの 炎
  {
    mirror: true,
    y: 3,
    rows: [
      '.........Y',
      '........AYA',
      '........AYA',
      '.......VAYAV',
      '.....Y.VVAVV',
      '....AYA.VVVV',
      '....AYA.VVVVV',
      '...VAYAVVVVVV',
      '...VVAVVVVVVV',
      '..Y.VVVVVVVVV',
      '.AYA.VVVVVVVVV',
      '.AYA.VVVVVVVVV',
      '.VAYAVVVVVVVVV',
      '.VVAVVVVVVVVVV',
      '..VVVVVVVVVVVV',
      '...VVVVVVVVVVV',
      '....VVVVVVVVVV',
      '.....VVVVVVVVV',
      '......VVVVVVVV',
      '.......VVVVVVV',
      '........VVVVVV',
      '.........VVVVV',
      '..........VVVV',
      '...........VVV',
      '............VV',
    ],
  },
  {
    mirror: true,
    rows: [
      '',
      '...................G...G',
      '...................GG.GG',
      '...................GGGGJ',
      '...................GGGGJ',
      '...................QQQQQ',
      '................PPPPPPPP',
      '..............PPPPPPPPPP',
      '.............PPPPCPPPPPP',
      '............PPPPPCPPPPPP',
      '............PPPooPPPPPPP',
      '............PPPPooPPPPPP',
      '............PPPGGoPPPPPP',
      '............PPPGGoPPPPPP',
      '............PPPGGoPPPPPP',
      '............PPPGooPPPPPP',
      '............PPPPPPPPPPPP',
      '............PPPPPPPPPoPP',
      '.............PPPPPPPPPPP',
      '.............PPPPPoooooo',
      '.............PPPPoWrrrrr',
      '.............PPPPorrrrrr',
      '..............PPPPoooooo',
      '..............PPCPPCPPCP',
      '.............PPPCPPCPPCP',
      '.............PPCPPCPPCPP',
      '.............PPPCPPLLPPP',
      '.............PPCPPPllPPP',
      '.............PPPCPPCPPCP',
      '.............PPCPPCPPCPP',
      '....TTLLTTTTTPPPPPPPPPPP',
      '...GGGGGGGGGGGGGGGGGGGGG',
      '...DDDDDDDDDDDDDDDDDDDDD',
      '....DDDDDDDDDDDDDDDDDDDD',
      '....DDDDDDDDDDDDDDDDDDDD',
      '.....DDDDDDDDDDDDDDDDDDD',
      '.....DDDDDDDDDDDDDDDDDDD',
      '......GGGGGGGGGGGGGGGGGG',
      '.......DDDDDDDDDDDDDDDDD',
      '........DDDDDDDDDDDDDDDD',
      '.........DDDDDDDDDDDDDDD',
      '..........DDDDDDDDDDDDDD',
      '............DDDDDDDDDDDD',
      '..............GGGGGGGGGG',
      '..............DDDDDDDDDD',
      '.............DDDDDDDDDDD',
      '.............DDDDDDDDDDD',
    ],
  },
  // ひげの めん
  {
    mirror: true,
    y: 18,
    rows: [
      '.........PPPP',
      '.....PPPPPC',
      '...PPPPC',
      '..PPPC',
      '..PPC',
      '..PPC',
      '...PPC',
      '....PPC',
      '.....PP',
    ],
  },
  // どんぶりの ふちに たれる めん
  {
    mirror: true,
    y: 29,
    rows: ['....PP...PP', '...PPC..PPC', '...PC...PC', '...PC...PC', '...PC...PC', '...PC', '...PC', '...PC'],
  },
  // ゆげ
  { mirror: true, x: 1, y: 25, rows: ['.WW.', 'WCCW', '.WW.'] },
];

const oudonRyu: MonsterDesign = {
  size: 48,
  colors: UDON_COLORS,
  rim: { [NQ.red]: NQ.brick, [NQ.paper]: NQ.cloud, [NQ.vermilion]: NQ.brick },
  rimDepth: 2,
  layers: oudonRyuLayers,
};

/** オウドンリュウ 後半：つめたい 水で しめた すがた。炎が 水に、どんぶりが 青に かわる（ミズ） */
const oudonRyuP0: MonsterDesign = {
  size: 48,
  colors: { ...UDON_COLORS, V: NQ.azure, A: NQ.sky, Y: NQ.ice, D: NQ.blue, r: NQ.navy, T: NQ.ice },
  rim: { [NQ.blue]: NQ.navy, [NQ.paper]: NQ.cloud, [NQ.azure]: NQ.blue },
  rimDepth: 2,
  layers: [
    ...oudonRyuLayers,
    // 水の つぶ
    { x: 3, y: 12, rows: ['.Y.', 'YWY', '.Y.'] },
    { x: 42, y: 16, rows: ['.Y.', 'YWY', '.Y.'] },
  ],
};

/**
 * 平賀源内（裏ステージの ラスボス）：江戸時代の 発明家。ちょんまげに 羽織はかま、
 * 両手で エレキテルの はこを かかえ、上の どう線から 金色の 火花が とぶ（ヒカリ）
 */
const hiragaGennai: MonsterDesign = {
  size: 48,
  colors: {
    F: NQ.skinLight,
    f: NQ.skinMid,
    W: NQ.white,
    H: NQ.hairBlack,
    D: NQ.denim,
    N: NQ.navy,
    P: NQ.paper,
    S: NQ.slate,
    s: NQ.gray,
    b: NQ.bark,
    G: NQ.gold,
    Y: NQ.cream,
    R: NQ.red,
  },
  rim: { [NQ.denim]: NQ.navy, [NQ.skinLight]: NQ.skinMid, [NQ.slate]: NQ.gray },
  rimDepth: 2,
  layers: [
    {
      mirror: true,
      rows: [
        '',
        '......................HH',
        '.....................HHH',
        '....................HHHH',
        '.....................HHH',
        '................FFFFFFFF',
        '..............FFFFFFFFFF',
        '............HHFFFFFFFFFF',
        '...........HHHFFFFFFFFFF',
        '...........HHFFoooFFFFFF',
        '...........HHFFWoFFFFFFF',
        '...........HHFFFFFFFFfFF',
        '...........HHFFFFFFFFoFF',
        '...........HHfFFFFFFFFoo',
        '............HffFFFFFFFFF',
        '.............fffffffffff',
        '................ffffffff',
        '..........DDDDDDDDPPFFFF',
        '........DDDDDDDDDDDPPFFF',
        '.......DDDDDDDDDDDDDPPFF',
        '......DDDDDDDDDDDDDDDPPF',
        '......DDDDDGGDDDDDDDDDPP',
        '......DDDDDGGDDDDDDDDRRR',
        '......DDDDDDDDDDDDDDDRRR',
        '......DDDDDDDDDDDDDDDDDD',
        '......DDDDDDDDDDDDDDDDDD',
        '......DDDDDDDDDDDDDDDDDD',
        '......DDDDDDDDDDDDDDDDDD',
        '......DDDDDDDDDDDDDDDDDD',
        '......DDDDDDDDDDDDDDDDDD',
        '......DDDDDDDDDDDDDDDDDD',
        '......DDDDDDDDDDDDDDDDDD',
        '......DDDDDDDDDDDDDDDDDD',
        '.......SSSSSSSSSSSSSSSSS',
        '.......SsSSSSsSSSSsSSSSS',
        '.......SSSSSSSSSSSSSSSSS',
        '......SsSSSSsSSSSsSSSSSS',
        '......SSSSSSSSSSSSSSSSSS',
        '......SsSSSSsSSSSsSSSSSS',
        '.....SSSSSSSSSSSSSSSSSSS',
        '.....SsSSSSsSSSSsSSSSSSS',
        '.....SSSSSSSSSSSSSSSSSSS',
        '....SsSSSSsSSSSsSSSSSSSS',
        '....SSSSSSSSSSSSSSSSSSSS',
        '....SSSSSSSSSSSSSSSSSSSS',
        '.....WWWWW',
        '.....WWWWW',
      ],
    },
    // 羽織の そで（たもと）
    {
      mirror: true,
      y: 19,
      rows: [
        '.....DDN',
        '....DDDN',
        '...DDDDN',
        '..DDDDDN',
        '..DDDDDN',
        '..DDDDDN',
        '..DDDDDN',
        '..DDDDDN',
        '..DDDDDN',
        '..DDDDDN',
        '..DDDDDN',
        '..DDDDDN',
        '..DDDDDN',
        '..DDDDDN',
        '...DDDDN',
        '....DDDN',
      ],
    },
    // うでと 手
    { mirror: true, x: 8, y: 30, rows: ['FFFFFF', 'FFFFFF', 'FffFFF'] },
    // エレキテル（木の はこ・金の かざり）
    {
      x: 14,
      y: 28,
      rows: [
        'GGbbbbbbbbbbbbbbbbGG',
        'bbbbbbbbbbbbbbbbbbbb',
        'bbbGGGGGGGGGGGGGGbbb',
        'bbbbbbbbbbbbbbbbbbbb',
        'bbbbbbbbbbbbbbbbbbbb',
        'bbbGGGGGGGGGGGGGGbbb',
        'bbbbbbbbbbbbbbbbbbbb',
        'GGbbbbbbbbbbbbbbbbGG',
      ],
    },
    // ハンドル
    { x: 34, y: 30, rows: ['ss', '.ss', '..ss', '..ss'] },
    // どう線
    { x: 23, y: 23, rows: ['GG', 'GG', 'GG', 'GG', 'GG'] },
    // 火花
    { x: 25, y: 13, rows: ['....YW', '...WY.', '..YW..', '.WY...', 'YW....', 'W.....'] },
    { x: 33, y: 11, rows: ['.Y.', 'YWY', '.Y.'] },
    { x: 8, y: 14, rows: ['.Y.', 'YWY', '.Y.'] },
  ],
};

export const KAGAWA: Readonly<Record<string, MonsterDesign>> = {
  'kagawa-boss-oudon-ryu': oudonRyu,
  'kagawa-boss-oudon-ryu.p0': oudonRyuP0,
  'kagawa-lastboss-hiraga-gennai': hiragaGennai,
  'kagawa-midboss-ritsurin-no-nushi': ritsurinNoNushi,
  'kagawa-midboss-ritsurin-no-nushi.field': ritsurinNoNushiField,
  'kagawa-kororibu': kororibu,
  'kagawa-minoribu': minoribu,
  'kagawa-aogin': aogin,
  'kagawa-tsumuji-uchiwa': tsumujiUchiwa,
  'kagawa-zenigani': zenigani,
  'kagawa-oozenigani': oozenigani,
};
