/** 高知県の モンスター（手描き。docs/06 §4・§6.3〜6.5 の 規格） */
import { NQ } from '../palette';
import type { MonsterDesign } from './design';

/** アブリカツオ：わらの 火で あぶった かつお。青い せなかと 白い おなか、頭に わらの 炎（ヒノ） */
const aburikatsuo: MonsterDesign = {
  size: 32,
  colors: {
    N: NQ.navy,
    B: NQ.blue,
    C: NQ.cloud,
    W: NQ.white,
    V: NQ.vermilion,
    A: NQ.apricot,
    G: NQ.gold,
    p: NQ.blush,
  },
  rim: { [NQ.navy]: NQ.ink, [NQ.cloud]: NQ.silver },
  layers: [
    // わらの 炎
    {
      mirror: true,
      y: 1,
      rows: [
        '...............G',
        '..............AG',
        '..............VA',
        '...........A.VVA',
        '..........VGVVAA',
        '..........VAAVVA',
      ],
    },
    // むなびれ
    { mirror: true, x: 3, y: 17, rows: ['....B', '..BBB', '.BBBB', '..BBB', '....B'] },
    {
      mirror: true,
      rows: [
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '...........NNNNN',
        '.........NNNNNNN',
        '........NNNNNNNN',
        '........NNNNNNNN',
        '.......NNNNNNNNN',
        '.......NNNNNNNNN',
        '.......NNNWWNNNN',
        '.......NNNWoNNNN',
        '.......NNNWoNNNN',
        '.......NNppNNNoN',
        '.......NNNNNNNNo',
        '.......BBBBBBBBB',
        '.......CCCCCCCCC',
        '.......NNNNNNNNN',
        '.......CCCCCCCCC',
        '.......NNNNNNNNN',
        '........CCCCCCCC',
        '........CCCCCCCC',
        '.........CCCCCCC',
        '..........NNNNNN',
        '.........NNNNNNN',
        '........NNNNNNNN',
        '.......NNNNN',
      ],
    },
  ],
};

/** ホムラカツオ（アブリカツオの しんか）：せなかに わらの 炎の たてがみ、きりっと まゆ、大きな 尾びれ（ヒノ） */
const homuraKatsuo: MonsterDesign = {
  size: 32,
  colors: {
    N: NQ.navy,
    B: NQ.blue,
    C: NQ.cloud,
    W: NQ.white,
    V: NQ.vermilion,
    A: NQ.apricot,
    G: NQ.gold,
    p: NQ.blush,
  },
  rim: { [NQ.navy]: NQ.ink, [NQ.cloud]: NQ.silver },
  layers: [
    // わらの 炎（頭と せなか）
    {
      mirror: true,
      y: 1,
      rows: [
        '...............G',
        '..............AG',
        '.........G....VA',
        '........AGA..VVA',
        '.......VAGAVVAAG',
        '.......VVAVVVAVA',
        '.....G..VVVVVVVV',
        '....AGA..VVVVVVV',
        '....VAGA',
        '....VVAV',
      ],
    },
    // むなびれ
    { mirror: true, x: 2, y: 18, rows: ['....B', '..BBB', '.BBBB', 'BBBBB', '.BBBB', '..BBB'] },
    {
      mirror: true,
      rows: [
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '.........NNNNNNN',
        '........NNNNNNNN',
        '.......NNNNNNNNN',
        '.......NNNNNNNNN',
        '......NNNooNNNNN',
        '......NNNNNoNNNN',
        '......NNNNWWNNNN',
        '......NNNNWoNNNN',
        '......NNNNWoNNNN',
        '......NNppNNNNoN',
        '......NNNNNNNNNo',
        '......BBBBBBBBBB',
        '......CCCCCCCCCC',
        '......NNNNNNNNNN',
        '......CCCCCCCCCC',
        '......NNNNNNNNNN',
        '.......CCCCCCCCC',
        '.......CCCCCCCCC',
        '........CCCCCCCC',
        '.........NNNNNNN',
        '........NNNNNNNN',
        '.......NNNNNNNNN',
        '.......NNNNN',
      ],
    },
  ],
};

/** ユズピカ：でこぼこの ゆず。金の わっかが うかび、まわりが ぱっと 明るい（ヒカリ） */
const yuzupika: MonsterDesign = {
  size: 32,
  colors: {
    Y: NQ.yellow,
    G: NQ.gold,
    Q: NQ.ochre,
    C: NQ.cream,
    L: NQ.leaf,
    g: NQ.green,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.yellow]: NQ.ochre, [NQ.leaf]: NQ.green },
  layers: [
    // 金の わっか
    { mirror: true, y: 3, rows: ['..........GGGGGG', '.........G......', '..........QQQQQQ'] },
    // 葉と ヘタ
    { x: 8, y: 8, rows: ['.LLL', 'LLgLL', '.LLLL'] },
    { mirror: true, y: 10, rows: ['..............gL', '.............LLL'] },
    {
      mirror: true,
      rows: [
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '...........YYYYY',
        '.........YYYYYYY',
        '........YYYYYYYY',
        '.......YYYYYYYYY',
        '.......YYYYYYYYY',
        '......YYYYYYYYYY',
        '......YYYYWWYYYY',
        '......YYYYWoYYYY',
        '......YYYYWoYYYY',
        '......YYppYYYYoY',
        '......YYYYYYYYYo',
        '......YYYYYYYYYY',
        '.......YYYYYYYYY',
        '.......YYYYYYYYY',
        '........YYYYYYYY',
        '.........YYYYYYY',
        '...........YYYYY',
        '..........QQQ',
        '..........QQQ',
      ],
    },
    // でこぼこの かわ
    { x: 8, y: 16, rows: ['.Q..Q', 'Q..Q.'] },
    { x: 19, y: 24, rows: ['Q..Q.', '.Q..Q'] },
    { x: 9, y: 26, rows: ['..Q.Q'] },
    // つや（左上）
    { x: 9, y: 15, rows: ['.CC', 'CC.', 'C..'] },
  ],
};

/** カガヤキユズ（ユズピカの しんか）：大きな 金の わっかと 光の すじ、きりっと まゆ（ヒカリ） */
const kagayakiYuzu: MonsterDesign = {
  size: 32,
  colors: {
    Y: NQ.yellow,
    G: NQ.gold,
    Q: NQ.ochre,
    C: NQ.cream,
    L: NQ.leaf,
    g: NQ.green,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.yellow]: NQ.ochre, [NQ.leaf]: NQ.green },
  layers: [
    // 大きな 金の わっか（2 じゅう）
    { mirror: true, y: 1, rows: ['........GGGGGGGG', '.......G........', '........QQQQQQQQ'] },
    { mirror: true, y: 5, rows: ['..........GGGGGG', '.........G......', '..........QQQQQQ'] },
    // 葉と ヘタ
    { x: 7, y: 9, rows: ['.LLL', 'LLgLL', '.LLLL'] },
    { mirror: true, y: 10, rows: ['..............gL', '.............LLL'] },
    {
      mirror: true,
      rows: [
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '..........YYYYYY',
        '........YYYYYYYY',
        '.......YYYYYYYYY',
        '......YYYYYYYYYY',
        '......YYYooYYYYY',
        '......YYYYYoYYYY',
        '.....YYYYYWWYYYY',
        '.....YYYYYWoYYYY',
        '.....YYYYYWoYYYY',
        '.....YYppYYYYoYY',
        '.....YYYYYYYYYoo',
        '.....YYYYYYYYYYY',
        '.....YYYYYYYYYYY',
        '......YYYYYYYYYY',
        '.......YYYYYYYYY',
        '........YYYYYYYY',
        '..........YYYYYY',
        '..........QQQ',
        '..........QQQ',
      ],
    },
    // でこぼこの かわ
    { x: 7, y: 15, rows: ['.Q..Q', 'Q..Q.'] },
    { x: 19, y: 23, rows: ['Q..Q.', '.Q..Q'] },
    // 光の すじ
    { x: 1, y: 18, rows: ['CC.', '..C'] },
    { x: 28, y: 21, rows: ['.CC', 'C..'] },
    // つや（左上）
    { x: 8, y: 14, rows: ['.CC', 'CC.', 'C..'] },
  ],
};

/** カミワシ：土佐和紙が おれて できた ワシ。とがった 紙の つばさ、おり目の すじ（カゼ） */
const kamiwashi: MonsterDesign = {
  size: 32,
  colors: {
    P: NQ.paper,
    C: NQ.cloud,
    W: NQ.white,
    S: NQ.sand,
    M: NQ.mint,
    p: NQ.blush,
  },
  rim: { [NQ.paper]: NQ.cloud },
  layers: [
    // 紙の つばさ
    {
      mirror: true,
      y: 12,
      rows: [
        '........PP',
        '......PPPP',
        '....PPPPPP',
        '..PPPPPPPP',
        '.PPCPPPPPP',
        '.PPPCPPPPP',
        '..PPPCPPPP',
        '...PPPCPPP',
        '....PPPCPP',
        '.....PPPCP',
        '......PPPP',
      ],
    },
    {
      mirror: true,
      rows: [
        '',
        '',
        '',
        '',
        '.............PPP',
        '............PPPP',
        '...........PPPPP',
        '...........PWoPP',
        '...........PooPP',
        '...........PppSS',
        '...........PPSSS',
        '...........PPPSS',
        '..........PPPPPP',
        '.........PPPPPPP',
        '.........PPPPPPP',
        '.........PPPPPPP',
        '.........PPPPPPP',
        '.........PPPPPPP',
        '..........PPPPPP',
        '..........PPPPPP',
        '..........PPPPPP',
        '...........PPPPP',
        '...........PPPPP',
        '............PPPP',
        '............PPPP',
        '.............PPP',
        '.............PPP',
        '..............PP',
        '..............PP',
      ],
    },
    // おり目
    { x: 14, y: 20, rows: ['C', 'C', 'C', 'C', 'C'] },
    // 風
    { x: 1, y: 24, rows: ['.MM', 'M..', '.MM'] },
    { x: 27, y: 9, rows: ['MM.', '..M', 'MM.'] },
  ],
};

/** オオワシガミ（カミワシの しんか）：大きく ひろげた 紙の つばさ、きりっと まゆ、風の すじ（カゼ） */
const oowashigami: MonsterDesign = {
  size: 32,
  colors: {
    P: NQ.paper,
    C: NQ.cloud,
    W: NQ.white,
    S: NQ.sand,
    M: NQ.mint,
    p: NQ.blush,
  },
  rim: { [NQ.paper]: NQ.cloud },
  layers: [
    // 大きな 紙の つばさ
    {
      mirror: true,
      y: 7,
      rows: [
        '.........PP',
        '........PPP',
        '.......PPPP',
        '.....PPPPPP',
        '...PPPPPPPP',
        '.PPPPPPPPPP',
        '.PPCPPPPPPP',
        '.PPPCPPPPPP',
        '.PPPPCPPPPP',
        '..PPPPCPPPP',
        '...PPPPCPPP',
        '....PPPPCPP',
        '.....PPPPCP',
        '......PPPPP',
        '.......PPPP',
      ],
    },
    {
      mirror: true,
      rows: [
        '',
        '',
        '',
        '.............PPP',
        '............PPPP',
        '...........PPPPP',
        '..........PPoPPP',
        '..........PPPoPP',
        '..........PWoPPP',
        '..........PooPPP',
        '..........PppPSS',
        '..........PPPSSS',
        '..........PPPPSS',
        '.........PPPPPPP',
        '........PPPPPPPP',
        '........PPPPPPPP',
        '........PPPPPPPP',
        '........PPPPPPPP',
        '........PPPPPPPP',
        '.........PPPPPPP',
        '.........PPPPPPP',
        '.........PPPPPPP',
        '..........PPPPPP',
        '..........PPPPPP',
        '...........PPPPP',
        '...........PPPPP',
        '............PPPP',
        '.............PPP',
        '.............PPP',
        '..............PP',
      ],
    },
    // おり目
    { x: 14, y: 22, rows: ['C', 'C', 'C', 'C', 'C'] },
    // 風
    { x: 1, y: 26, rows: ['.MM', 'M..', '.MM'] },
    { x: 27, y: 5, rows: ['MM.', '..M', 'MM.'] },
  ],
};

/**
 * ナルコマイ（中ボス）：よさこい祭りの おどり手。はちまきと 赤い はっぴ、
 * 両手を 高く あげて なるこを かちかち ならす。頭に 王冠（ヒノ）
 */
const narukomai: MonsterDesign = {
  size: 40,
  colors: {
    B: NQ.bark,
    P: NQ.paper,
    K: NQ.skinMid,
    W: NQ.white,
    R: NQ.red,
    r: NQ.brick,
    G: NQ.gold,
    Q: NQ.ochre,
    Y: NQ.yellow,
    N: NQ.navy,
  },
  rim: { [NQ.red]: NQ.brick, [NQ.paper]: NQ.cloud, [NQ.navy]: NQ.ink },
  rimDepth: 2,
  layers: [
    // なるこ（両手に かかげる）
    {
      mirror: true,
      x: 1,
      y: 2,
      rows: ['.YYYYY', '.YoYoY', '.YYYYY', '.YoYoY', '.YYYYY', '.YoYoY', '.YYYYY', '...RR'],
    },
    // あげた うで
    {
      mirror: true,
      y: 10,
      rows: ['...KK', '...KK', '....KK', '....KK', '.....KK', '.....KK', '......KK', '......KK', '.......KK'],
    },
    {
      mirror: true,
      rows: [
        '',
        '...............G...G',
        '...............GG.GG',
        '...............GGGGR',
        '...............QQQQQ',
        '............BBBBBBBB',
        '...........BBBBBBBBB',
        '..........PPPPPPPPPP',
        '..........KKKKKKKKKK',
        '..........KKKKKKKKKK',
        '..........KKoooKKKKK',
        '..........KKWWoKKKKK',
        '..........KKWWoKKKKK',
        '..........KKWWoKKKKK',
        '..........KKWooKKKKK',
        '..........KKKKKKKKKK',
        '..........KKKKoooooo',
        '..........KKKKKKKKKK',
        '...........KKKKKKKKK',
        '........RRRRPPPPKKKK',
        '.......RRRRRRPPPPKKK',
        '......RRRRRRRRPPPPKK',
        '......RRRRRRRRRPPPPK',
        '......RRRRRRRRRRPPPP',
        '......RRRRRRRRRRRPPP',
        '......RRRRRRRRRRRRPP',
        '......GGGGGGGGGGGGGG',
        '......QQQQQQQQQQQQQQ',
        '......RRRRRRRRRRRRRR',
        '......RRRRRRRRRRRRRR',
        '......RrRrRrRrRrRrRr',
        '.......RRRRRRRRRRRRR',
        '.......NNNNNNNNNNNNN',
        '.......NNNNNNNNNNNNN',
        '........NNNNNN.NNNNN',
        '........NNNNNN.NNNNN',
        '........NNNNNN.NNNNN',
        '........PPPPPP.PPPPP',
        '........PPPPPP.PPPPP',
      ],
    },
  ],
};

/** ナルコマイ（フィールドに 立つ 32×32） */
const narukomaiField: MonsterDesign = {
  size: 32,
  colors: {
    B: NQ.bark,
    P: NQ.paper,
    K: NQ.skinMid,
    W: NQ.white,
    R: NQ.red,
    G: NQ.gold,
    Q: NQ.ochre,
    Y: NQ.yellow,
    N: NQ.navy,
  },
  rim: { [NQ.red]: NQ.brick, [NQ.navy]: NQ.ink },
  layers: [
    { mirror: true, x: 1, y: 4, rows: ['.YYYY', '.YoYo', '.YYYY', '.YoYo', '.YYYY', '...RR'] },
    { mirror: true, y: 10, rows: ['...KK', '....KK', '....KK', '.....KK', '.....KK', '......KK'] },
    {
      mirror: true,
      rows: [
        '',
        '...........G...G',
        '...........GG.GG',
        '...........GGGGR',
        '...........QQQQQ',
        '.........BBBBBBB',
        '........PPPPPPPP',
        '........KKKKKKKK',
        '........KKoooKKK',
        '........KKWWoKKK',
        '........KKWWoKKK',
        '........KKWooKKK',
        '........KKKKKKKK',
        '........KKKoooooo'.slice(0, 16),
        '.........KKKKKKK',
        '......RRRRPPPKKK',
        '.....RRRRRRPPPPK',
        '.....RRRRRRRRPPP',
        '.....GGGGGGGGGGG',
        '.....QQQQQQQQQQQ',
        '.....RRRRRRRRRRR',
        '.....RRRRRRRRRRR',
        '......NNNNNNNNNN',
        '......NNNNN.NNNN',
        '......NNNNN.NNNN',
        '......NNNNN.NNNN',
        '......NNNNN.NNNN',
        '......PPPPP.PPPP',
        '......PPPPP.PPPP',
      ],
    },
  ],
};

const KUJIRA_COLORS = {
  N: NQ.navy,
  B: NQ.blue,
  S: NQ.sky,
  A: NQ.azure,
  I: NQ.ice,
  W: NQ.white,
  G: NQ.gold,
  Q: NQ.ochre,
  R: NQ.red,
};

const KUJIRA_LAYERS = [
  // しおふき
  { mirror: true, x: 13, y: 1, rows: ['..W', '.WI', 'WI.', 'W..'] },
  // むなびれ
  {
    mirror: true,
    y: 25,
    rows: [
      '......BB',
      '....BBBB',
      '..BBBBBB',
      '.BBBBBBB',
      '.BBBBBBB',
      '.BBBBBBB',
      '..BBBBBB',
      '...BBBBB',
      '.....BBB',
    ],
  },
  {
    mirror: true,
    rows: [
      '',
      '...................G...G',
      '...................GG.GG',
      '...................GGGGR',
      '...................QQQQQ',
      '................NNNNNNNN',
      '..............NNNNNNNNNN',
      '............NNNNNNNNNNNN',
      '...........NNNNNNNNNNNNN',
      '..........NNNNNNNNNNNNNN',
      '.........NNNNNNNNNNNNNNN',
      '.........NNNNNNNNNNNNNNN',
      '........NNNNNNNNNNNNNNNN',
      '........NNNNNNNNNNNNNNNN',
      '........NNNNNNNNNNNNNNNN',
      '........NNNNNNNNNNNNNNNN',
      '........NNWWWoNNNNNNNNNN',
      '........NNWWWoNNNNNNNNNN',
      '........NNWWWoNNNNNNNNNN',
      '........NNWWooNNNNNNNNNN',
      '........NNNNNNNNNNNNNNNN',
      '.......BBBBBBBBBBBBBBBBB',
      '.......ooooooooooooooooo',
      '.......SBSSBSSBSSBSSBSSB',
      '.......SBSSBSSBSSBSSBSSB',
      '.......SBSSBSSBSSBSSBSSB',
      '.......SBSSBSSBSSBSSBSSB',
      '.......SBSSBSSBSSBSSBSSB',
      '.......SBSSBSSBSSBSSBSSB',
      '........SBSSBSSBSSBSSBSS',
      '........SBSSBSSBSSBSSBSS',
      '.........SBSSBSSBSSBSSBS',
      '.........SBSSBSSBSSBSSBS',
      '..........SSSSSSSSSSSSSS',
      '...........SSSSSSSSSSSSS',
      '............SSSSSSSSSSSS',
    ],
  },
  // 黒潮の 波
  {
    mirror: true,
    y: 36,
    rows: [
      '...WW..WW....WW...WW....',
      '..AAAAAAAAAAAAAAAAAAAAAA',
      '.AAAAAAAAAAAAAAAAAAAAAAA',
      '.AAAAAAAAAAAAAAAAAAAAAAA',
      '.ABAAABAAAABAAAABAAAABAA',
      '.AAAAAAAAAAAAAAAAAAAAAAA',
      '.BBAAABBAAABBAAABBAAABBA',
      '.BBBBBBBBBBBBBBBBBBBBBBB',
      '.BBBBBBBBBBBBBBBBBBBBBBB',
      '.BBBBBBBBBBBBBBBBBBBBBBB',
      '.BBBBBBBBBBBBBBBBBBBBBBB',
    ],
  },
];

/**
 * クロシオクジラ（県ボス）：室戸岬の 沖の 黒潮から とび出す 大きな クジラ。
 * 頭に 王冠、のどの すじ、ひろげた むなびれ、足もとは 波（ミズ）
 */
const kuroshioKujira: MonsterDesign = {
  size: 48,
  colors: KUJIRA_COLORS,
  rim: { [NQ.navy]: NQ.ink, [NQ.azure]: NQ.blue, [NQ.sky]: NQ.azure },
  rimDepth: 2,
  layers: KUJIRA_LAYERS,
};

/** クロシオクジラ 後半：からだが 明るい 青に なり、波と しぶきが 大きく なる */
const kuroshioKujiraP0: MonsterDesign = {
  size: 48,
  colors: { ...KUJIRA_COLORS, N: NQ.blue, B: NQ.azure, S: NQ.ice },
  rim: { [NQ.blue]: NQ.navy, [NQ.azure]: NQ.blue },
  rimDepth: 2,
  layers: [
    ...KUJIRA_LAYERS,
    // 大きな しぶき
    { x: 2, y: 20, rows: ['.W.', 'WIW', '.W.'] },
    { x: 43, y: 24, rows: ['.W.', 'WIW', '.W.'] },
    { x: 8, y: 33, rows: ['.WW.', 'W..W'] },
    { x: 36, y: 31, rows: ['.WW.', 'W..W'] },
  ],
};

/**
 * 坂本龍馬（裏ステージの ラスボス）：黒い きものに はかま、ブーツ。
 * ふところに 右手を 入れ、左手に 巻物。むねに 金の 家紋、こしに 赤い ひも（カゼ → ヒカリ）
 */
const sakamotoRyoma: MonsterDesign = {
  size: 48,
  colors: {
    F: NQ.skinLight,
    f: NQ.skinMid,
    W: NQ.white,
    H: NQ.hairBlack,
    K: NQ.night,
    P: NQ.paper,
    S: NQ.slate,
    s: NQ.gray,
    b: NQ.bark,
    G: NQ.gold,
    R: NQ.red,
    Y: NQ.cream,
  },
  rim: { [NQ.night]: NQ.ink, [NQ.skinLight]: NQ.skinMid, [NQ.slate]: NQ.gray },
  rimDepth: 2,
  layers: [
    {
      mirror: true,
      rows: [
        '',
        '.....................HHH',
        '....................HHHH',
        '..................HHHHHH',
        '...............HHHHHHHHH',
        '.............HHHHHHHHHHH',
        '............HHHHHHHHHHHH',
        '...........HHHHHHHHHHHHH',
        '...........HHHHFFFFFFFFF',
        '...........HHHFFFFFFFFFF',
        '...........HHFFoooFFFFFF',
        '...........HHFFWoFFFFFFF',
        '...........HHFFFFFFFFfFF',
        '...........HHFFFFFFFFoFF',
        '...........HHfFFFFFFFFoo',
        '............HffFFFFFFFFF',
        '.............fffffffffff',
        '................ffffffff',
        '..........KKKKKKKKPPFFFF',
        '........KKKKKKKKKKKPPFFF',
        '.......KKKKKKKKKKKKKPPFF',
        '......KKKKKKKKKKKKKKKPPF',
        '......KKKKKGGKKKKKKKKKPP',
        '......KKKKKGGKKKKKKKKRRR',
        '......KKKKKKKKKKKKKKKRRR',
        '......KKKKKKKKKKKKKKKKKK',
        '......KKKKKKKKKKKKKKKKKK',
        '......KKKKKKKKKKKKKKKKKK',
        '......KKKKKKKKKKKKKKKKKK',
        '......KKKKKKKKKKKKKKKKKK',
        '......KKKKKKKKKKKKKKKKKK',
        '......KKKKKKKKKKKKKKKKKK',
        '.......SSSSSSSSSSSSSSSSS',
        '.......SsSSSSsSSSSsSSSSS',
        '.......SSSSSSSSSSSSSSSSS',
        '......SsSSSSsSSSSsSSSSSS',
        '......SSSSSSSSSSSSSSSSSS',
        '......SsSSSSsSSSSsSSSSSS',
        '.....SSSSSSSSSSSSSSSSSSS',
        '.....SsSSSSsSSSSsSSSSSSS',
        '.....SSSSSSSSSSSSSSSSSSS',
        '....SsSSSSsSSSSsSSSSSSSS',
        '....SSSSSSSSSSSSSSSSSSSS',
        '....SSSSSSSSSSSSSSSSSSSS',
        '.....bbbbbb',
        '.....bbbbbb',
      ],
    },
    // きものの そで
    {
      mirror: true,
      y: 20,
      rows: [
        '.....KKK',
        '....KKKK',
        '...KKKKK',
        '..KKKKKK',
        '..KKKKKK',
        '..KKKKKK',
        '..KKKKKK',
        '..KKKKKK',
        '..KKKKKK',
        '..KKKKKK',
        '..KKKKKK',
        '...KKKKK',
        '....KKKK',
      ],
    },
    // ふところに 入れた 右手（画面の 右）
    { x: 26, y: 28, rows: ['FFFF', 'FFFF', 'FffF'] },
    // 左手に もつ 巻物
    { x: 8, y: 30, rows: ['FFFF', 'FFFF'] },
    { x: 4, y: 28, rows: ['PPPPPP', 'PRRRRP', 'PPPPPP'] },
    // 光の つぶ
    { x: 38, y: 12, rows: ['.Y.', 'YWY', '.Y.'] },
    { x: 6, y: 16, rows: ['.Y.', 'YWY', '.Y.'] },
  ],
};

export const KOCHI: Readonly<Record<string, MonsterDesign>> = {
  'kochi-midboss-narukomai': narukomai,
  'kochi-midboss-narukomai.field': narukomaiField,
  'kochi-boss-kuroshio-kujira': kuroshioKujira,
  'kochi-boss-kuroshio-kujira.p0': kuroshioKujiraP0,
  'kochi-lastboss-sakamoto-ryoma': sakamotoRyoma,
  'kochi-aburikatsuo': aburikatsuo,
  'kochi-homura-katsuo': homuraKatsuo,
  'kochi-yuzupika': yuzupika,
  'kochi-kagayaki-yuzu': kagayakiYuzu,
  'kochi-kamiwashi': kamiwashi,
  'kochi-oowashigami': oowashigami,
};
