/** 熊本県の モンスター（手描き。docs/06 §4・§6.3〜6.5 の 規格） */
import { NQ } from '../palette';
import type { MonsterDesign } from './design';
import { BEARD_FACE, HELMET, lord } from './lastbosses';

/** シマダマ：まんまるの スイカ。こい みどりの しまもよう、上に つるの ヘタと 葉っぱ（モリ） */
const shimadama: MonsterDesign = {
  size: 32,
  colors: {
    L: NQ.leaf,
    G: NQ.green,
    M: NQ.lime,
    B: NQ.bark,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.leaf]: NQ.green },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '...........MM..B',
        '..........MMMM.B',
        '..........MMMMMB',
        '..........LLLLLL',
        '.......LLLLLLLLL',
        '.....LLLLLLLLLLL',
        '....LLLLLLLLLLLL',
        '...LLLLLLLLLLLLL',
        '..LLLLLLLLLLLLLL',
        '..LLLLLLLLLLLLLL',
        '..LLLLLLLLLLLLLL',
        '..LLLLLLLLLLLLLL',
        '..LLLLLLLLWWLLLL',
        '..LLLLLLLLWoLLLL',
        '..LLLLLLLLWoLLLL',
        '..LLLLpLLLLLLLoL',
        '..LLLLLLLLLLLLLo',
        '..LLLLLLLLLLLLLL',
        '..LLLLLLLLLLLLLL',
        '..LLLLLLLLLLLLLL',
        '...LLLLLLLLLLLLL',
        '....LLLLLLLLLLLL',
        '.....LLLLLLLLLLL',
        '.......LLLLLLLLL',
        '..........LLLLLL',
        '..........LLL...',
        '.........GGGG...',
        '.........GGGG...',
      ],
    },
    // こい みどりの しまもよう
    {
      mirror: true,
      y: 5,
      rows: [
        '..........G....G',
        '.........G.....G',
        '.....G...G.....G',
        '....G....G.....G',
        '....G...G......G',
        '...G....G......G',
        '...G....G......G',
        '...G....G......G',
        '...G....G......G',
        '...G....G......G',
        '...G....G......G',
        '...G....G......G',
        '...G....G......G',
        '...G....G......G',
        '...G....G......G',
        '....G...G......G',
        '....G....G.....G',
        '.....G...G.....G',
        '......G..G.....G',
        '.........G.....G',
        '..........G....G',
      ],
    },
  ],
};

/** カルデラン：阿蘇山の 火口が 頭に なった 小さな 山。草原の すそ、火口から けむりと 炎（ヒノ） */
const karuderan: MonsterDesign = {
  size: 32,
  colors: {
    L: NQ.leaf,
    G: NQ.green,
    g: NQ.gray,
    N: NQ.slate,
    W: NQ.white,
    c: NQ.cloud,
    V: NQ.vermilion,
    A: NQ.apricot,
    Y: NQ.gold,
    p: NQ.blush,
  },
  rim: { [NQ.leaf]: NQ.green, [NQ.gray]: NQ.slate },
  layers: [
    // けむりと 炎
    { x: 8, y: 1, rows: ['.cW.', 'WWWc', '.WW.'] },
    {
      mirror: true,
      y: 2,
      rows: ['..............Y.', '.............AYA', '.............AYA', '...........VAYAV'],
    },
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '..........gggggg',
        '.........gNooooN',
        '........gggggggg',
        '.......ggggggggg',
        '......ggLLLLLLLL',
        '.....gLLLLLLLLLL',
        '.....LLLLLLLLLLL',
        '....LLLLLLLLLLLL',
        '....LLLLLLLLLLLL',
        '...LLLLLLLWWLLLL',
        '...LLLLLLLWoLLLL',
        '...LLLLLLLWoLLLL',
        '...LLLpLLLLLLLoL',
        '..LLLLLLLLLLLLLo',
        '..LLLLLLLLLLLLLL',
        '..LLLLLLLLLLLLLL',
        '.LLLLLLLLLLLLLLL',
        '.LLLLLLLLLLLLLLL',
        '.LLLLLLLLLLLLLLL',
        '.LLLLLLLLLLLLLLL',
        '.LLLLLLLLLLLLLLL',
        '.LLLLLLLLLLLLLLL',
        '.GGGGGGGGGGGGGGG',
        '....GGG.........',
        '....GGG.........',
      ],
    },
  ],
};

/** エビグルマ：天草の 車えび。しまもようの からだ、長い ひげ、下に ひろがる 尾びれ（ミズ） */
const ebiguruma: MonsterDesign = {
  size: 32,
  colors: {
    C: NQ.cream,
    E: NQ.beige,
    V: NQ.vermilion,
    R: NQ.brick,
    A: NQ.azure,
    S: NQ.sky,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.cream]: NQ.beige, [NQ.vermilion]: NQ.brick },
  layers: [
    // 長い ひげ
    {
      mirror: true,
      y: 1,
      rows: [
        '....V...........',
        '.....V..........',
        '.....V..........',
        '......V.........',
        '......V.........',
        '.......V........',
        '.......V........',
      ],
    },
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
        '...........CCCCC',
        '.........CCCCCCC',
        '........CCCCCCCC',
        '.......CCCCCCCCC',
        '......CCCCCCCCCC',
        '......CCCCCCCCCC',
        '.....CCCCCCCCCCC',
        '.....CCCCCWWCCCC',
        '.....CCCCCWoCCCC',
        '.....CCCCCWoCCCC',
        '.....CCCpCCCCCoC',
        '.....CCCCCCCCCCo',
        '.....CCCCCCCCCCC',
        '.....CCCCCCCCCCC',
        '......CCCCCCCCCC',
        '......CCCCCCCCCC',
        '.......CCCCCCCCC',
        '.......CCCCCCCCC',
        '........CCCCCCCC',
        '........CCCCCCCC',
        '.........CCCCCCC',
        '.....VVVVVVVVVVV',
        '...VVVVSVVVVSVVV',
        '..VVVVVVVVVVVVVV',
      ],
    },
    // しまもよう
    {
      mirror: true,
      y: 10,
      rows: [
        '......VVV.......',
        '',
        '.....V..........',
        '',
        '',
        '',
        '',
        '.....VV.........',
        '',
        '',
        '......VV........',
        '',
        '',
        '.......VV.......',
      ],
    },
    // 足
    {
      mirror: true,
      y: 22,
      rows: ['....A...........', '....A...........', '...A............', '...A............'],
    },
  ],
};

/**
 * キンドウロウ（中ボス）：山鹿灯籠まつりの 金色の 灯籠が 動きだした すがた。六角の 屋根、
 * ぼんやり 光る まど、紙の うで。てっぺんに 王冠（ヒカリ）
 */
const kindouro: MonsterDesign = {
  size: 40,
  colors: {
    G: NQ.gold,
    Q: NQ.ochre,
    Y: NQ.cream,
    W: NQ.paper,
    c: NQ.cloud,
    R: NQ.red,
    B: NQ.bark,
    p: NQ.blush,
  },
  rim: { [NQ.gold]: NQ.ochre, [NQ.paper]: NQ.cloud },
  rimDepth: 2,
  layers: [
    {
      mirror: true,
      rows: [
        '....................',
        '................G..G',
        '................GGGR',
        '................QQQQ',
        '..............GGGGGG',
        '...........GGGGGGGGG',
        '........GGGGGGGGGGGG',
        '......GGGGGGGGGGGGGG',
        '.....GQGGQGGQGGQGGQG',
        '.....GGGGGGGGGGGGGGG',
        '........GGGGGGGGGGGG',
        '........GYYYYYYYYYYY',
        '........GYYYBBBYYYYY',
        '........GYYYBBBYYYYY',
        '........GYYYYYYYYYYY',
        '........GGGGGGGGGGGG',
        '........GGGGGGGGGGGG',
        '........GYYYYYYYYYYY',
        '........GYYYYYYYYYYY',
        '........GYYYYYYYYYYY',
        '........GGGGGGGGGGGG',
        '.......GGGGGGGGGGGGG',
        '......GGGGGGGGGGGGGG',
        '......GQGGQGGQGGQGGQ',
        '......GGGGGGGGGGGGGG',
        '........WWWWWWWWWWWW',
        '.......WWWWWWWWWWWWW',
        '......WWWWWWWWWWWWWW',
        '......RRRRRRRRRRRRRR',
        '.....WWWWWWWWWWWWWWW',
        '.....WWWWWWWWWWWWWWW',
        '....WWWWWWWWWWWWWWWW',
        '....WWWWWWWWWWWWWWWW',
        '...WWWWWWWWWWWWWWWWW',
        '...WWWWWWWWWWWWWWWWW',
        '...WWWWWWWWWWWWWWWWW',
        '....cccccccccccccccc',
        '......GGGG..........',
      ],
    },
    // かお（まゆ・3×4 の 目・ほっぺ・口）
    {
      mirror: true,
      y: 11,
      rows: [
        '..........oo........',
        '............oo......',
        '............WWW.....',
        '............WWo.....',
        '............WWo.....',
        '............Woo.....',
        '..........pp........',
        '................oooo',
        '.................ooo',
      ],
    },
    // 紙の うで（ひらひら）
    {
      mirror: true,
      y: 17,
      rows: [
        '...WWW..............',
        '..WWW...............',
        '.WWW................',
        '.WW.................',
        '.WWW................',
        '.WW.................',
      ],
    },
  ],
};

/** キンドウロウ（フィールドに立つ 32×32） */
const kindouroField: MonsterDesign = {
  size: 32,
  colors: {
    G: NQ.gold,
    Q: NQ.ochre,
    Y: NQ.cream,
    W: NQ.paper,
    c: NQ.cloud,
    R: NQ.red,
    B: NQ.bark,
    p: NQ.blush,
  },
  rim: { [NQ.gold]: NQ.ochre, [NQ.paper]: NQ.cloud },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '............G..G',
        '............GGGR',
        '............QQQQ',
        '..........GGGGGG',
        '.......GGGGGGGGG',
        '.....GGGGGGGGGGG',
        '.....GQGGQGGQGGQ',
        '.....GGGGGGGGGGG',
        '......GYYYYYYYYY',
        '......GYYBBBYYYY',
        '......GYYBBBYYYY',
        '......GYYYYYYYYY',
        '......GGGGGGGGGG',
        '......GYYYYYYYYY',
        '......GYYYYYYYYY',
        '......GGGGGGGGGG',
        '.....GGGGGGGGGGG',
        '.....GQGGQGGQGGQ',
        '.....GGGGGGGGGGG',
        '......WWWWWWWWWW',
        '.....WWWWWWWWWWW',
        '.....RRRRRRRRRRR',
        '....WWWWWWWWWWWW',
        '....WWWWWWWWWWWW',
        '...WWWWWWWWWWWWW',
        '...WWWWWWWWWWWWW',
        '...WWWWWWWWWWWWW',
        '....cccccccccccc',
        '.....GGGG.......',
      ],
    },
    {
      mirror: true,
      y: 9,
      rows: [
        '........oo......',
        '.........WW.....',
        '.........Wo.....',
        '.......pWWo.....',
        '..............oo',
        '...............o',
      ],
    },
    {
      mirror: true,
      y: 14,
      rows: ['..WWW...........', '.WWW............', '.WWW............', '.WW.............'],
    },
  ],
};

/** 天守（黒い 屋根と 白い かべ、金の しゃちほこ）と 武者返しの 石垣（左半分） */
const MUSHA_KEEP = [
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '.............G..........',
  '............GGG.....NNNN',
  '............GGG..NNNNNNN',
  '...........GGG.NNNNNNNNN',
  '..............NNNNNNNNNN',
  '..............WWWWWWWWWW',
  '..............WWWWWWWWWW',
  '..............WWWWWWWWWW',
  '..............WWWWWWWWWW',
  '..............WWWWWWWWWW',
  '..............WWWWWWWWWW',
  '..............WWWWWWWWWW',
  '..............WWWWWWWWWW',
  '...........NNNNNNNNNNNNN',
  '..........NNNNNNNNNNNNNN',
  '.........NNNNNNNNNNNNNNN',
  '........NNNNNNNNNNNNNNNN',
  '.........WWWWWWWWWWWWWWW',
  '.........WWWWWWWWWWWWWWW',
  '.........WWWWWWWWWWWWWWW',
];

const MUSHA_WALL = [
  '........ssssssssssssssss',
  '........gggggggggggggggg',
  '.......gggsgggsgggsgggsg',
  '.......gggggggggggggggg',
  '......gggggggggggggggggg',
  '......ssssssssssssssssss',
  '.....gggggggggggggggggss',
  '.....gggsgggsgggsgggsggg',
  '....gggggggggggggggggggg',
  '....ssssssssssssssssssss',
  '...gggggggggggggggggggss',
  '...gggsgggsgggsgggsggggg',
  '..gggggggggggggggggggggg',
  '..ssssssssssssssssssssss',
  '.ggggggggggggggggggggggg',
  '.gggsgggsgggsgggsgggsggg',
  '.gggggggggggggggggggggss',
  '.ssssssssssssssssssssss',
  '.gggggggggggggggggggggg',
  '.gggsgggsgggsgggsgggsgg',
  '.gggggggggggggggggggggg',
];

/**
 * ムシャガエシ（県ボス）：熊本城の 石垣から 生まれた 岩の 巨人。頭は 黒い 屋根と 白い かべの 天守、
 * 金の しゃちほこと 王冠、からだは 下ほど 広がる「武者返し」の 石垣（ツチ）
 */
const mushagaeshi: MonsterDesign = {
  size: 48,
  colors: {
    N: NQ.night,
    W: NQ.paper,
    c: NQ.cloud,
    g: NQ.gray,
    s: NQ.silver,
    S: NQ.slate,
    G: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
  },
  rim: { [NQ.gray]: NQ.slate, [NQ.paper]: NQ.cloud, [NQ.gold]: NQ.ochre },
  rimDepth: 2,
  layers: [
    { mirror: true, rows: MUSHA_KEEP },
    { mirror: true, y: 25, rows: MUSHA_WALL },
    // 石の うで
    {
      mirror: true,
      y: 26,
      rows: [
        '..ggg',
        '.gggg',
        '.gggg',
        '.gsgg',
        '.gggg',
        '.gggg',
        '.gsgg',
        '.gggg',
        '.gggg',
        '.gggg',
        '.gssg',
        '.gggg',
      ],
    },
    // 天守の まどの 目・口
    {
      mirror: true,
      y: 11,
      rows: [
        '...............ooo......',
        '...............GGG......',
        '...............GGo......',
        '...............GGo......',
        '...............Goo......',
        '........................',
        '.....................ooo',
      ],
    },
    // 王冠
    {
      mirror: true,
      y: 1,
      rows: [
        '....................G..G',
        '....................GGGG',
        '....................GGGR',
        '....................QQQQ',
      ],
    },
  ],
};

/** ムシャガエシ 後半（ヒノ）：阿蘇の 火が 石垣の すきまから もえあがり、目が 白く 光る */
const mushagaeshiHot: MonsterDesign = {
  ...mushagaeshi,
  colors: { ...mushagaeshi.colors, s: NQ.vermilion, V: NQ.vermilion, A: NQ.apricot, C: NQ.cream },
  layers: [
    ...mushagaeshi.layers,
    // 石垣の わきの 炎
    {
      mirror: true,
      x: 1,
      y: 33,
      rows: ['..C.', '..A.', '.VAV', 'VVAV', '.C..', '.A..', 'VAV.', 'VAV.'],
    },
    // 白く 光る 目
    {
      mirror: true,
      y: 12,
      rows: [
        '...............CCC......',
        '...............CCo......',
        '...............CCo......',
        '...............Coo......',
      ],
    },
  ],
};

/** 加藤清正：銀色の 長い 烏帽子形の かぶとと ひげ、黒い よろい（ミズ） */
const katoKiyomasa = lord(
  [
    '......................SS',
    '.....................SSS',
    '.....................SSS',
    '....................SSSS',
    '....................SGGG',
    '...................SGSSG',
    '..................SSGGGS',
    '.................SSSSSSS',
    '...............NNSSSSSSS',
    '..............NNNNNNNNNN',
    ...HELMET,
    ...BEARD_FACE,
  ],
  {
    N: NQ.night,
    L: NQ.slate,
    K: NQ.night,
    S: NQ.silver,
    G: NQ.gold,
    Y: NQ.yellow,
    R: NQ.red,
    T: NQ.slate,
    H: NQ.gray,
    M: NQ.hairBlack,
  },
  { [NQ.silver]: NQ.gray },
);

// ───────────────────────── しんか ─────────────────────────

/** スイカブト：シマダマの しんか。スイカの かわの かぶとと、赤い 実の むね当て。たねの つぶてを にぎる（モリ） */
const suikabuto: MonsterDesign = {
  size: 32,
  colors: {
    L: NQ.leaf,
    G: NQ.green,
    M: NQ.lime,
    R: NQ.red,
    r: NQ.brick,
    W: NQ.white,
    B: NQ.bark,
    p: NQ.blush,
  },
  rim: { [NQ.leaf]: NQ.green, [NQ.red]: NQ.brick },
  layers: [
    // スイカの ひと切れの かぶと
    {
      mirror: true,
      rows: [
        '................',
        '..............BB',
        '.............MMB',
        '...........MMMMM',
        '.........GGGGGGG',
        '........GWWWWWWW',
        '.......GWRRRRRRR',
        '......GWRRRoRRRR',
        '.....GWRRRRRRRRR',
        '.....GWRRoRRRRRR',
        '....GWRRRRRRRRRR',
        '....LLLLLLLLLLLL',
        '...LLLLLLLLLLLLL',
        '...LLLLLLLLLLLLL',
        '..LLLLLLLLooLLLL',
        '..LLLLLLLLWWLLLL',
        '..LLLLLLLLWoLLLL',
        '..LLLLpLLLWoLLLL',
        '..LLLLLLLLLLLooo',
        '..LLLLLLLLLLLoWW',
        '..LLLLLLLLLLLLoo',
        '..LLLLLLLLLLLLLL',
        '...LLLLLLLLLLLLL',
        '....LLLLLLLLLLLL',
        '.....LLLLLLLLLLL',
        '.......LLLLLLLLL',
        '..........LLLLLL',
        '..........LLL...',
        '.........GGGG...',
        '.........GGGG...',
      ],
    },
    // しまもよう
    {
      mirror: true,
      y: 12,
      rows: [
        '.....G...G......',
        '....G....G......',
        '...G....G.......',
        '...G....G.......',
        '...G....G.......',
        '...G....G.......',
        '...G....G.......',
        '...G....G.......',
        '....G...G.......',
        '.....G...G......',
        '......G..G......',
        '.........G......',
      ],
    },
    // たねの つぶて
    { x: 1, y: 18, rows: ['.LL', 'LLL', 'LoL', 'LLL'] },
  ],
};

/** ダイカルデラ：カルデランの しんか。二重の 火口と 広い 草原、もくもくの けむりと 大きな 炎（ヒノ） */
const daiKarudera: MonsterDesign = {
  size: 32,
  colors: {
    L: NQ.leaf,
    G: NQ.green,
    g: NQ.gray,
    N: NQ.slate,
    W: NQ.white,
    c: NQ.cloud,
    V: NQ.vermilion,
    A: NQ.apricot,
    Y: NQ.gold,
    p: NQ.blush,
  },
  rim: { [NQ.leaf]: NQ.green, [NQ.gray]: NQ.slate },
  layers: [
    { x: 6, y: 1, rows: ['.cWW.', 'WWWWc', 'cWWW.'] },
    {
      mirror: true,
      y: 1,
      rows: [
        '.............Y..',
        '............AYA.',
        '...........AAYAA',
        '...........VAYAV',
        '...........VVAVV',
      ],
    },
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
        '.........ggggggg',
        '........gNVVVVVN',
        '........gNooooVN',
        '.......ggggggggg',
        '......gggggggggg',
        '.....ggLLLLLLLLL',
        '....gLLLLLLLLLLL',
        '....LLLLLLooLLLL',
        '...LLLLLLLWWLLLL',
        '...LLLLLLLWoLLLL',
        '...LLLLLLLWoLLLL',
        '...LLLpLLLLLLLoL',
        '..LLLLLLLLLLLLLo',
        '..LLLLLLLLLLLLLL',
        '.LLLLLLLLLLLLLLL',
        '.LLLLLLLLLLLLLLL',
        '.LLLLLLLLLLLLLLL',
        '.LLLLLLLLLLLLLLL',
        '.LLLLLLLLLLLLLLL',
        '.LLLLLLLLLLLLLLL',
        '.LLLLLLLLLLLLLLL',
        '.GGGGGGGGGGGGGGG',
        '.GGGGGGGGGGGGGGG',
        '....GGG.........',
      ],
    },
  ],
};

/** エビムシャ：エビグルマの しんか。ひげを かぶとの かざりのように なびかせ、大きな はさみを かまえる（ミズ） */
const ebiMusha: MonsterDesign = {
  size: 32,
  colors: {
    C: NQ.cream,
    E: NQ.beige,
    V: NQ.vermilion,
    R: NQ.brick,
    A: NQ.azure,
    S: NQ.sky,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.cream]: NQ.beige, [NQ.vermilion]: NQ.brick },
  layers: [
    // 長い ひげ（かぶとの かざりの ように 外へ そる）
    {
      mirror: true,
      y: 1,
      rows: [
        '..V.............',
        '..V.............',
        '...V............',
        '...V............',
        '....V...........',
        '.....V..........',
        '......V.........',
        '.......V........',
      ],
    },
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '..........VVVVVV',
        '........VVVVVVVV',
        '.......VCCCCCCCC',
        '......CCCCCCCCCC',
        '.....CCCCCCCCCCC',
        '.....CCCCCCCCCCC',
        '....CCCCCCooCCCC',
        '....CCCCCCWWCCCC',
        '....CCCCCCWoCCCC',
        '....CCCCCCWoCCCC',
        '....CCCpCCCCCCoC',
        '....CCCCCCCCCCCo',
        '....VVVVVVVVVVVV',
        '.....CCCCCCCCCCC',
        '.....CCCCCCCCCCC',
        '.....VVVVVVVVVVV',
        '......CCCCCCCCCC',
        '......CCCCCCCCCC',
        '......VVVVVVVVVV',
        '.......CCCCCCCCC',
        '.......CCCCCCCCC',
        '........CCCCCCCC',
        '.....VVVVVVVVVVV',
        '...VVVVSVVVVSVVV',
        '..VVVVVVVVVVVVVV',
      ],
    },
    // かまえた はさみ
    { mirror: true, y: 13, rows: ['..CCC', '.CCCC', '.CCoC', '.CCCC', '..CCC', '..AA.'] },
  ],
};

/** タタミン：八代のい草で おられた 小さな畳の子（ツチ） */
const tatamin: MonsterDesign = {
  size: 32,
  colors: { L: NQ.leaf, G: NQ.green, M: NQ.lime, T: NQ.tan, B: NQ.brown, W: NQ.white, p: NQ.blush },
  rim: { [NQ.leaf]: NQ.green, [NQ.tan]: NQ.brown },
  layers: [
    {
      mirror: true,
      y: 1,
      rows: [
        '....TTTTTTTT....',
        '...TBBBBBBBBT...',
        '..TBBLLLLLLBBT..',
        '.TBBLMLMLMLLBBT.',
        '.TBBLLMLMLMLBBT.',
        '.TBBLMLMLMLLBBT.',
        '.TBBLLMLMLMLBBT.',
        '.TBBLMLMLMLLBBT.',
        '.TBBLLWWLLLLBBT.',
        '.TBBLLWoLLLLBBT.',
        '.TBBLLLLLLLLBBT.',
        '.TBBLLpLLLLLBBT.',
        '.TBBLMLMLMLLBBT.',
        '.TBBLLMLMLMLBBT.',
        '.TBBLMLMLMLLBBT.',
        '.TBBLLMLMLMLBBT.',
        '.TBBLMLMLMLLBBT.',
        '.TBBLLMLMLMLBBT.',
        '.TBBLMLMLMLLBBT.',
        '.TBBLLMLMLMLBBT.',
        '.TBBLLLLLLLLBBT.',
        '..TBBBBBBBBBBT..',
        '...TTTTTTTTTT...',
        '......BBBB......',
        '.....BB..BB.....',
        '....BB....BB....',
        '...BB......BB...',
        '...BB......BB...',
        '...BB......BB...',
      ],
    },
  ],
};

/** オリタタミン：何枚もの畳を折り重ねた タタミンの進化（ツチ） */
const oritatamin: MonsterDesign = {
  ...tatamin,
  colors: { ...tatamin.colors, Y: NQ.gold },
  layers: [
    ...tatamin.layers,
    { mirror: true, y: 4, rows: ['..YYYYYYYYYYYY..', '...Y........Y...', '..YYYYYYYYYYYY..'] },
    { mirror: true, y: 14, rows: ['..BBBBBBBBBBBB..', '.BLLLLLLLLLLLLB.', '..BBBBBBBBBBBB..'] },
    { mirror: true, y: 20, rows: ['...YYYYYYYYYY...', '....Y......Y....'] },
  ],
};

export const KUMAMOTO: Readonly<Record<string, MonsterDesign>> = {
  'kumamoto-midboss-kindouro': kindouro,
  'kumamoto-midboss-kindouro.field': kindouroField,
  'kumamoto-boss-mushagaeshi': mushagaeshi,
  'kumamoto-boss-mushagaeshi.p0': mushagaeshiHot,
  'kumamoto-lastboss-kato-kiyomasa': katoKiyomasa,
  'kumamoto-shimadama': shimadama,
  'kumamoto-suikabuto': suikabuto,
  'kumamoto-karuderan': karuderan,
  'kumamoto-dai-karudera': daiKarudera,
  'kumamoto-ebiguruma': ebiguruma,
  'kumamoto-ebi-musha': ebiMusha,
  'kumamoto-tatamin': tatamin,
  'kumamoto-oritatamin': oritatamin,
};
