/** 宮崎県の モンスター（手描き。docs/06 §4・§6.3〜6.5 の 規格） */
import { NQ } from '../palette';
import type { MonsterDesign } from './design';

const one = (rows: string[]) => [{ rows }];

/** マンゴッチ：お日さまを あびた まっ赤な マンゴー。上は 赤く 下は だいだい、ヘタと 葉、金の わっか（ヒカリ） */
const mangocchi: MonsterDesign = {
  size: 32,
  colors: {
    R: NQ.red,
    V: NQ.vermilion,
    O: NQ.orange,
    A: NQ.apricot,
    Y: NQ.gold,
    Q: NQ.ochre,
    B: NQ.brown,
    G: NQ.green,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.red]: NQ.brick, [NQ.vermilion]: NQ.brick, [NQ.orange]: NQ.brick },
  layers: one([
    '................................',
    '..........YYYYYYYYYYYY..........',
    '.........Y............Y.........',
    '..........QQQQQQQQQQQGGG........',
    '...............BB...GGGG........',
    '...............BB.GGGG..........',
    '...............BBGGGG...........',
    '...............BB..G............',
    '............RRRBBRRR............',
    '..........RRRRRRRRRRRR..........',
    '.........RAARRRRRRRRAAR.........',
    '........RARRRRRRRRRRRRAR........',
    '.......RARRRRRRRRRRRRRRAR.......',
    '.......RARRRRRRRRRRRRRRAR.......',
    '......RRRRRRRRRRRRRRRRRRRR......',
    '......RRRRRRRRRRRRRRRRRRRR......',
    '......RRRRWWRRRRRRRRWWRRRR......',
    '......RRRRWoRRRRRRRRoWRRRR......',
    '......RRRRWoRRRRRRRRoWRRRR......',
    '......RRppRRRRRRRRRRRRppRR......',
    '......RRRRRRRRoRRoRRRRRRRR......',
    '......RRRRRRRRRooRRRRRRRRR......',
    '......RRRRRRRRRRRRRRRRRRRR......',
    '.......RRRRRRRRRRRRRRRRRR.......',
    '.......RRRRRRRVRRVRRRRRRR.......',
    '........VVRVVVVVVVVVVRVV........',
    '........VVVVVVOVVOVVVVVV........',
    '.........OVOOOOOOOOOOVO.........',
    '...........OOOOOOOOOO...........',
    '.............OOOOOO.............',
    '................................',
    '................................',
  ]),
};

/** カンジュクマンゴ（マンゴッチの しんか）：大きく じゅくした マンゴー。白い あみに つつまれ、葉の つばさと 大きな 金の わっか（ヒカリ） */
const kanjukuMango: MonsterDesign = {
  size: 32,
  colors: {
    R: NQ.red,
    V: NQ.vermilion,
    O: NQ.orange,
    Y: NQ.gold,
    Q: NQ.ochre,
    B: NQ.brown,
    G: NQ.green,
    F: NQ.forest,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.red]: NQ.brick, [NQ.vermilion]: NQ.brick, [NQ.orange]: NQ.brick },
  layers: one([
    '................................',
    '.........YYYYYYYYYYYYYY.........',
    '........Y..............Y........',
    '...Y.....QQQQQQQQQQQQQQ.........',
    '...............BB...........Y...',
    '...............BB..........Y.Y..',
    '..............RBBR..........Y...',
    '...........RRRRBBRRRR...........',
    '.G.......RRRRRRRRRRRRRR.......G.',
    '.GF.....RWWRRRRRRRRRRWWR.....FG.',
    '.GFG...RWRRRRRRRRRRRRRRWR...GFG.',
    '.GGFG.RWRRRRRRRRRRRRRRRRWR.GFGG.',
    '.GGGF.RRRRRRRRRRRRRRRRRRRR.FGGG.',
    '..GGFRRRRooRRRRRRRRRRooRRRRFGG..',
    '...GGRRRRRRoRRRRRRRRoRRRRRRGG...',
    '....GRRRRRWWRRRRRRRRWWRRRRRG....',
    '.....RRRRRWoRRRRRRRRoWRRRRR.....',
    '....RRRRRRWoRRRRRRRRoWRRRRRR....',
    '....RRRRppRRRRRRRRRRRRppRRRR....',
    '....RRRRRRRRRoRRRRoRRRRRRRRR....',
    '.....RRRRRRRRRooooRRRRRRRRR.....',
    '.....RRRRRRRRRRRRRRRRRRRRRR.....',
    '.....RRRRRRRRRRRRRRRRRRRRRR.....',
    '......RRRRRRRRRRRRRRRRRRRR......',
    '......VRRRRRRRVRRVRRRRRRRV......',
    '.......WVWRWVWVWWVWVWRWVW.......',
    '........VVWVVVWVVWVVVWVV........',
    '.........WVWOWOWWOWOWVW.........',
    '..........OOWOOOOOOWOO..........',
    '.............WOWWOW.............',
    '................................',
    '................................',
  ]),
};

/** タルタルコッコ：こんがり あげた ころもの 色の ニワトリ。頭に タルタルソース（ピクルスと たまご）、赤い とさか、小さな つばさ（カゼ） */
const tarutaruKokko: MonsterDesign = {
  size: 32,
  colors: {
    O: NQ.orange,
    M: NQ.amber,
    C: NQ.cream,
    W: NQ.white,
    G: NQ.green,
    Y: NQ.yellow,
    R: NQ.red,
    p: NQ.blush,
  },
  rim: { [NQ.orange]: NQ.amber, [NQ.white]: NQ.cloud },
  layers: one([
    '................................',
    '................................',
    '...............RR...............',
    '.............RRRRRR.............',
    '............RRRRRRRR............',
    '............RRRRRRRR............',
    '..........WWWWWWWWWWWW..........',
    '.........WWWWWYWWYWWWWW.........',
    '........WWGWYWWWWWWYWGWW........',
    '........WWWWWWWWWWWWWWWW........',
    '........WYWWWGWWWWGWWWYW........',
    '........WWWGWWWWWWWWGWWW........',
    '........W.WWWWWWWWWWWW.W........',
    '........WOOOWWWWWWWWOOOW........',
    '........WOOOOOWOOWOOOOOW........',
    '.......OWOOWWOOOOOOWWOOWO.......',
    '......OOOCOWoOOOOOOoWOCOOO......',
    '......OOCOOWoOOOOOOoWOOCOO......',
    '.....OOCOppOOOYYYYOOOppOCOO.....',
    '....OOOOOOOOOOOYYOOOOOOOOOOO....',
    '..OOOOOMOOOOOOOOOOOOOOOOMOOOOO..',
    '..OOCOOOOOOOOOOOOOOOOOOOOOOCOO..',
    '..CCOOOOOOOOOOOOOOOOOOOOOOOOCC..',
    '..OOCCOOOOOOOOOOOOOOOOOOOOCCOO..',
    '..CCOOMOOOOOOOOOOOOOOOOOOMOOCC..',
    '.......OOOOOOOOOOOOOOOOOO.......',
    '........OOMOOOOOOOOOOMOO........',
    '.........OOOOOOOOOOOOOO.........',
    '..........OOOMOOOOMOOO..........',
    '...........YYYOOOOYYY...........',
    '...........YYY....YYY...........',
    '................................',
  ]),
};

/** ナンバンオンドリ（タルタルコッコの しんか）：大きな とさかの オンドリ。タルタルの マント、みどりの 尾ばね、ひろげた つばさ（カゼ） */
const nanbanOndori: MonsterDesign = {
  size: 32,
  colors: {
    O: NQ.orange,
    C: NQ.cream,
    W: NQ.white,
    G: NQ.green,
    Y: NQ.yellow,
    R: NQ.red,
    F: NQ.forest,
    T: NQ.teal,
    p: NQ.blush,
  },
  rim: { [NQ.orange]: NQ.amber, [NQ.white]: NQ.cloud },
  layers: one([
    '................................',
    '...............RR...............',
    '.............RRRRRR.............',
    '............RRRRRRRR............',
    '............RRRRRRRR............',
    '...........RRRRRRRRRR...........',
    '...........RCOOOOOOCR...........',
    '.FFF......OCOOOOOOOOCO......FFF.',
    '..TFF....OCooOOOOOOooCO....FFT..',
    '..FTFF...OOOWWOOOOWWOOO...FFTF..',
    '...TFF...OOOWoOOOOoWOOO...FFT...',
    '...FTFF..OOOWoOOOOoWOOO..FFTF...',
    '....TFF..OpOOOYYYYOOOpO..FFT....',
    '....FTFF..OOOOOYYOOOOO..FFTF....',
    '.....FTFF.OOOOORROOOOO.FFTF.....',
    '.....FTFFWWWOOORROOOWWWFFTF.....',
    '......FWWYWWWWWRRWWWWWYWWF......',
    '......FWWWWWWWWWWWWWWWWWWF......',
    '.......WWWGWWWWWWWWWWGWWW.......',
    '......OWWWWWWGWWWWGWWWWWWO......',
    '......OWWWWWWWWWWWWWWWWWWO......',
    '......OOWOOOWOOOOOOWOOOWOO......',
    '....OOOOWOOOWOOOOOOWOOOWOOOO....',
    '..OOOOOOWOOOOOOOOOOOOOOWOOOOOO..',
    '.OOCCCOOOOOOOOOOOOOOOOOOOOCCCOO.',
    '..COOOOOOOOOOOOOOOOOOOOOOOOOOC..',
    '..OOCCC.OOOOOOOOOOOOOOOO.CCCOO..',
    '..OC.....OOOOOOOOOOOOOO.....CO..',
    '..........OOOOOOOOOOOO..........',
    '..........YYYOOOOOOYYY..........',
    '..........YYY......YYY..........',
    '................................',
  ]),
};

/** ミサキポニー：都井岬の 小さな 馬（御崎馬）。茶色の 毛、黒い たてがみと 前がみ、やさしい 目、足もとに 草（ツチ） */
const misakiPony: MonsterDesign = {
  size: 32,
  colors: {
    B: NQ.brown,
    T: NQ.tan,
    S: NQ.sand,
    K: NQ.hairBlack,
    W: NQ.white,
    G: NQ.leaf,
    p: NQ.blush,
  },
  rim: { [NQ.brown]: NQ.bark, [NQ.tan]: NQ.brown },
  layers: one([
    '................................',
    '................................',
    '..........B..........B..........',
    '.........BB...KKKK...BB.........',
    '.........BTB.KKKKKK.BTB.........',
    '.........BTKKKKKKKKKKTB.........',
    '...........BKKKKKKKKB...........',
    '..........BBSKKKKKKSBB..........',
    '.........BBSBBBKKBBBSBB.........',
    '.........BSBBBBBBBBBBSB.........',
    '........BBBWWBBBBBBWWBBB........',
    '........BBBWoBBBBBBoWBBB........',
    '........BBBWoBBBBBBoWBBB........',
    '........KBppBTTTTTTBppBK........',
    '........KBBBTTTTTTTTBBBK........',
    '........KKBTTTTTTTTTTBKK........',
    '........KK.TTToTToTTT.KK........',
    '........KK..TTTTTTTT..KK........',
    '........KKBBBTTooTTBBBKK........',
    '........KKBBBBBBBBBBBBKK........',
    '........BBBBBSSSSSSBBBBB........',
    '.......BBBBBBSSSSSSBBBBBB.......',
    '.......BBBBBBSSSSSSBBBBBB.......',
    '.......BBBBBBSSSSSSBBBBBB.......',
    '.......BBBBBBBBBBBBBBBBBB.......',
    '.......BBBBBBBBBBBBBBBBBB.......',
    '........BBBBBBBBBBBBBBBB........',
    '...G.G..BBBBBBBBBBBBBBBB........',
    '..GGGG..BBBBBBBBBBBBBBBB........',
    '........KKK.KKKBBKKK.KKK........',
    '................................',
    '................................',
  ]),
};

/** ミサキテンバ（ミサキポニーの しんか）：岬の 風に 長い たてがみを なびかせる 馬。きりっと した 目、ひづめの 土けむり（ツチ） */
const misakiTenba: MonsterDesign = {
  size: 32,
  colors: {
    B: NQ.brown,
    T: NQ.tan,
    S: NQ.sand,
    K: NQ.hairBlack,
    W: NQ.white,
    E: NQ.beige,
    I: NQ.sky,
    L: NQ.slate,
    p: NQ.blush,
  },
  rim: { [NQ.brown]: NQ.bark, [NQ.tan]: NQ.brown },
  layers: one([
    '................................',
    '................................',
    '..........B....KK....B..........',
    '.........BTB.KKKKKK.BTB.........',
    '.........BTBKKKKKKKKBTB.........',
    '.......KKBBKKKKKKKKKKBBKK.......',
    '....KKKKKKBKKKKKKKKKKBKKKKKK....',
    '...KKKKLLBBKSKKWWKKSKBBLLKKKK...',
    '...KLLLKKBBSKBBWWBBKSBBKKLLLK...',
    '..KKKKKKBBSooBBWWBBooSBBKKKKKK..',
    '..K..KKKBBBWWoBWWBoWWBBBKKK..K..',
    '....KKKLBBBWoBBWWBBoWBBBLKKK....',
    '...KLLLKBBBWoBBWWBBoWBBBKLLLK...',
    '..KLKKKKKBpBTTTWWTTTBpBKKKKKLK..',
    '..KKKKKKKBBTTTTWWTTTTBBKKKKKKK..',
    '..KK.KKLKKBTTTTTTTTTTBKKLKK.KK..',
    '.K..KKLKKK.TTToTToTTT.KKKLKK..K.',
    '...KKLKKKKBBTTTTTTTTBBKKKKLKK...',
    '...KLKK.KKBBBTooooTBBBKK.KKLK...',
    '...KK...KKBBBSSSSSSBBBKK...KK...',
    '...K...BBBBBBSSSSSSBBBBBB...K...',
    '..K...BBBBBBBSSSSSSBBBBBBB...K..',
    '.III..BBBBBBBSSSSSSBBBBBBB......',
    '......BBBBBBBSSSSSSBBBBBBB..III.',
    '......BBBBBBBBBBBBBBBBBBBB......',
    '.......BBBBBBBBBBBBBBBBBB.......',
    '.......BBBBBBBBBBBBBBBBBB.......',
    '.......BBBBBBBBBBBBBBBBBB.......',
    '...EE..KKKKBKKKBBKKKBKKKK..EE...',
    '....EE.KKKK.KKKBBKKK.KKKK.EE....',
    '................................',
    '................................',
  ]),
};

const half = (rows: string[]) => [{ mirror: true, rows }];

/**
 * センタクオニ（中ボス）：青島の 岩で せんたくを する 青い 鬼。黒い まきげ、白い つの、とらの こしまき、
 * なみなみの 岩の せんたく板（鬼の 洗濯板）を かかえ、足もとに 波。頭に 王冠（ツチ → ミズ）
 */
const sentakuOni: MonsterDesign = {
  size: 40,
  colors: {
    A: NQ.azure,
    B: NQ.blue,
    S: NQ.sky,
    K: NQ.hairBlack,
    C: NQ.cream,
    W: NQ.white,
    O: NQ.orange,
    E: NQ.beige,
    T: NQ.tan,
    N: NQ.brown,
    Y: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
  },
  rim: { [NQ.azure]: NQ.blue },
  rimDepth: 2,
  layers: half([
    '....................',
    '....................',
    '............C...Y..Y',
    '..........CWC...YY.Y',
    '...........CCC..YYYY',
    '...........CCC.KYYYR',
    '...........CCCKKQQQQ',
    '............CCKKKKKK',
    '...........KCKKKKKKA',
    '............KKKKKAAA',
    '...........KKKKKKAAA',
    '..........KKKKKKAAAA',
    '..........KKKKKAKKKA',
    '...........KKKAWWoAA',
    '............KAAWWoAA',
    '............AAAWWoAA',
    '.............AAWooAA',
    '.............AAAAAAB',
    '..............AAAAAA',
    '.............AAAoAAA',
    '............AAAAAooo',
    '.........A.AAAAAAWAA',
    '.......AAAAASAAAAAAA',
    '.....AAAAAASAAAAAAAA',
    '....AAAAAETTTEENNEET',
    '....AAAAAAANNTTEETTN',
    '....AAAAAAAEENNTTNNE',
    '....AAAAAAATTEENNEET',
    '....AAAANTNNNTTEETTN',
    '....AAAANNEEENNTTNNE',
    '....AAAANETTTEENNEET',
    '....AAAANTNNNTTEETTN',
    '....AAAAANEEENNTTNNE',
    '......A.....OKOOKOAA',
    '............OKOOKOAA',
    '............KOOKOO..',
    '.....WW.....KOOKOO..',
    '...WWSSW..WWAAAAAA..',
    '..WSSSSSWWSSAAAAAA..',
    '....................',
  ]),
};

/** センタクオニ（フィールドに 立つ 32×32） */
const sentakuOniField: MonsterDesign = {
  size: 32,
  colors: {
    A: NQ.azure,
    K: NQ.hairBlack,
    C: NQ.cream,
    W: NQ.white,
    O: NQ.orange,
    E: NQ.cream,
    T: NQ.tan,
    N: NQ.brown,
    Y: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
  },
  rim: { [NQ.azure]: NQ.blue },
  layers: half([
    '................',
    '................',
    '..........C..Y..',
    '.........CC..YY.',
    '.........CC..YYY',
    '.........CCCKYYR',
    '..........CCKQQQ',
    '.........KCKKKKK',
    '.........KKKKKAA',
    '.........KKKKKAA',
    '.........AAKKAAA',
    '.........AAAWWAA',
    '.........AAAWoAA',
    '.........AAAooAA',
    '..........AAAAAA',
    '..........AAAAAA',
    '..........AAAAoo',
    '.........AAAAAAo',
    '........AAAAAAAA',
    '.......AAAAAAAAA',
    '.......NNETTTEEN',
    '.......EETNNNTTE',
    '.......TTNEEENNT',
    '.......NNETTTEEN',
    '.......EETNNNTTE',
    '.......TTNEEENNT',
    '.......NNETTTEEN',
    '..........OOKOOA',
    '..........OOKOOA',
    '..........OKOOO.',
    '..........AAAAA.',
    '................',
  ]),
};

/**
 * タカチホノヌシ（県ボス）：高千穂峡の 柱状節理の 岩の 柱で できた 巨人。かたから せなかへ 真名井の 滝の マント、
 * かたに 苔と 木。頭の 上に 王冠（ミズ。後半は 2 回 行動）
 */
const takachiho: MonsterDesign = {
  size: 48,
  colors: {
    S: NQ.sky,
    W: NQ.white,
    I: NQ.ice,
    L: NQ.gray,
    N: NQ.slate,
    i: NQ.silver,
    g: NQ.slate,
    G: NQ.green,
    M: NQ.leaf,
    Y: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
  },
  rim: { [NQ.gray]: NQ.slate, [NQ.sky]: NQ.azure },
  rimDepth: 2,
  layers: half([
    '........................',
    '...................Y..Y.',
    '..................YY.YY.',
    '..................YYYYY.',
    '..................YYYYR.',
    '.................MQQQQQ.',
    '................GGGGGGGG',
    '................iiLLLLLL',
    '.....G..........LLNiLNLL',
    '.....G..........LLNLLNLL',
    '.....G.......iiLLLNLLNLL',
    '....GMG......LLNNNNLLNLL',
    '....GMGM.....LLNLLNNNNNL',
    '....GGGMMGGG.LLNLLWWoNLL',
    '.....MMMMMGGGLLNLLWWoNLL',
    '.....GMMMGGGGLLNLLWWoNLL',
    '.....SGGGGGGGLLNLLWooNLL',
    '...WSSWLGGGLLLLNLLNLLNLL',
    '..SISSINLLNLLLLNLLNoLNLL',
    '..SISSINLLNLLLLNLLNLoooo',
    '..SISSINLLNLLLLNLLNLLNLL',
    '..SWSSWNLLNLLNLNLLNLLNLL',
    '..SWSSWNLLNMGNLNLLNLLNLL',
    '..SLiLLLLLNLLNLLNLLNLLNL',
    '..SLLNLLLLNLLNLLNLLNLLNL',
    '..SLLNLLLLNLLNLLNLLNMGNL',
    '..SLLNLLggNggNggNggNggNg',
    '..SLLNLLLLNLLNLLNLLNLLNL',
    '..SLLNLLLLNLLNMGNLLNLLNL',
    '..SLLNLLLLNLLNLLNLLNLLNL',
    '..SLLNLLLMGLLNLLNLLNLLNL',
    '..SLLNLLLLNLLNLLNLLNLLNL',
    '..SLLNLLLLNLLNLLNLLNLLNL',
    '..SLLNLLggNggNggNggNggNg',
    '..SLLNLLLLNLLNLLNLLNLLNL',
    '..gggggggLNLLNLLNMGNLLNL',
    '..gggggggLNLLNLLNLLNLLNL',
    '..gggggggLNLLNLLNLLNLLNL',
    '..ggggggggNggNggNggNggNg',
    '..SWSSWNLLNLLNLLNLLNLLNL',
    '..SWSSWNLLNLLNLLNLLNLLNL',
    '..SWSSWNLLNLLNLLNLLNLLNL',
    '..SISSINLLNLLNLLNLLNLLNL',
    '..SISSISSISS.ggggggg....',
    '.............ggggggg....',
    '............NNNNNNNNN...',
    '........................',
    '........................',
  ]),
};

/** タカチホノヌシ 後半：滝の いきおいが ましし、こい 青の 水と 白い しぶきが とびちる */
const takachihoSurge: MonsterDesign = {
  ...takachiho,
  colors: { ...takachiho.colors, S: NQ.azure },
  rim: { [NQ.gray]: NQ.slate, [NQ.azure]: NQ.blue },
  layers: [
    ...takachiho.layers,
    { mirror: true, x: 1, y: 11, rows: ['..W.', '.WIW', 'W.I.', '..W.'] },
    { mirror: true, x: 1, y: 40, rows: ['.W..W..', 'WIW.WIW', '.W..I..'] },
    { mirror: true, x: 10, y: 3, rows: ['.W.', 'W.W', '.I.'] },
  ],
};

/** 小村寿太郎：シルクハット・口ひげ・黒い フロックコート、金の ボタンと 時計の くさり。右手に 赤い ひもの 条約の まきもの（カゼ） */
const komura: MonsterDesign = {
  size: 48,
  colors: {
    F: NQ.skinLight,
    f: NQ.skinMid,
    H: NQ.hairBlack,
    W: NQ.white,
    N: NQ.night,
    L: NQ.slate,
    g: NQ.gray,
    Y: NQ.gold,
    R: NQ.red,
    C: NQ.cream,
    T: NQ.brown,
    c: NQ.tan,
  },
  rim: { [NQ.skinLight]: NQ.skinMid, [NQ.gray]: NQ.slate },
  rimDepth: 2,
  layers: one([
    '................................................',
    '...............HHHHHHHHHHHHHHHHHH...............',
    '...............HLHHHHHHHHHHHHHHLH...............',
    '...............HLHHHHHHHHHHHHHHLH...............',
    '...............HHHHHHHHHHHHHHHHHH...............',
    '...............HHHHHHHHHHHHHHHHHH...............',
    '...............LLLLLLLLLLLLLLLLLL...............',
    '...............HHHHHHHHHHHHHHHHHH...............',
    '............HHHHHHHHHHHHHHHHHHHHHHHH............',
    '............HHHHHHHHHHHHHHHHHHHHHHHH............',
    '.................HHHHHHHHHHHHHH.................',
    '..................FFFFFFFFFFFF..................',
    '.................FFHHHFFFFHHHFF.................',
    '.................FFFFFFFFFFFFFF.................',
    '................FFFFooFFFFooFFFF................',
    '................FFFFWoFFFFoWFFFF................',
    '................fFFFFFFFFFFFFFFf................',
    '.................FFFFFFffFFFFFF.................',
    '..................FFHHHHHHHHFF..................',
    '...................HHFFFFFFHH...................',
    '....................FFFooFFF....................',
    '.....................FFFFFF.....................',
    '...............LLLLWWFFFFFFWWLLLL...............',
    '............NNNNLLLWWHHHHHHWWLLLNNNN............',
    '.........NNNNNNNLLLLWWHHHHWWLLLLNNNNNNN.........',
    '........NNNNNNNNNLLLWWWWWWWWLLLNNNNNNNNN........',
    '.......NNNNNNNNNNLLLWWWWWWWWLLLNNNNNNNNNN.......',
    '......NNNNNNNNNNNNLLLWWWWWWLLLNNNNNNNNNNNN......',
    '.....NNNNNNNNNNNNNLLLWWYYWWLLLNNNNNNNNNNNNN.....',
    '.....NNNNNNNNNNNNNNLLLWWWWLLLNNNNNNNNTTTTTTTT...',
    '.....NNNNNNNNNNNNNNYYLWWWWLYYNNNNNNNNCCCCCCC....',
    '.....NNNNNNNNNNNNNNNLYYYYYYLNNNNNNNNNCcccccC....',
    '.....NNNNNNNNNNNNNNNLWWWWWWLNNNNNNNRRCCCCCCC....',
    '.....NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNRRCcccccC....',
    '.....NNNNNNNNNNNNNNNNNNYYNNNNNNNNNNRRCCCCCCC....',
    '.....NNNNNNNNNNNNNNNNNNNNNNNNNNNNNRNNCcccccC....',
    '.....NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNCCCCCCC....',
    '.....NNNNNNNNNNNNNNNNNNYYNNNNNNNNNNNNTTTTTTTT...',
    '.....NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN.....',
    '......FFFF.NNNNNNNNNNNNNNNNNNNNNNNNFFFFFFF......',
    '......FFFF.NNNNNNNNNNNNNNNNNNNNNNNNFFFFFFF......',
    '......FFFF...ggLggLggLggggLggLggLggFFFFFFF......',
    '.............ggLggLggLggggLggLggLgg.............',
    '.............ggLggLggLggggLggLggLgg.............',
    '.............ggLggLggLggggLggLggLgg.............',
    '............HHHHHHHHH......HHHHHHHHH............',
    '............HHHHHHHHH......HHHHHHHHH............',
    '................................................',
  ]),
};

export const MIYAZAKI: Readonly<Record<string, MonsterDesign>> = {
  'miyazaki-mangocchi': mangocchi,
  'miyazaki-kanjuku-mango': kanjukuMango,
  'miyazaki-tarutaru-kokko': tarutaruKokko,
  'miyazaki-nanban-ondori': nanbanOndori,
  'miyazaki-misaki-pony': misakiPony,
  'miyazaki-misaki-tenba': misakiTenba,
  'miyazaki-midboss-sentaku-oni': sentakuOni,
  'miyazaki-midboss-sentaku-oni.field': sentakuOniField,
  'miyazaki-boss-takachiho-no-nushi': takachiho,
  'miyazaki-boss-takachiho-no-nushi.p0': takachihoSurge,
  'miyazaki-lastboss-komura-jutaro': komura,
};
