/** 長崎県の モンスター（手描き。docs/06 §4・§6.3〜6.5 の 規格） */
import { NQ } from '../palette';
import type { MonsterDesign } from './design';

/** フワテラ：ふわふわの カステラ。こんがりの 上下、そこには ざらめの つぶ、頭に 金の わっか（ヒカリ） */
const fuwatera: MonsterDesign = {
  size: 32,
  colors: {
    Y: NQ.yellow,
    C: NQ.cream,
    B: NQ.amber,
    T: NQ.tan,
    W: NQ.white,
    G: NQ.gold,
    Q: NQ.ochre,
    p: NQ.blush,
  },
  rim: { [NQ.yellow]: NQ.ochre },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '..........GGGGGG',
        '.........G......',
        '..........QQQQQQ',
        '................',
        '....BBBBBBBBBBBB',
        '...BBBBBBBBBBBBB',
        '...CYYYYYYYYYYYY',
        '...YYYYYYCYYYYYY',
        '...YYYYYYYYYYYYY',
        '...YYCYYYYYYYYYY',
        '...YYYYYYYYYYYYY',
        '...YYYYYYYYYYYYC',
        '...YYYYYYYYYYYYY',
        '...YYYYYYYWWYYYY',
        '...YYYYYYYWoYYYY',
        '...YYYYYYYWoYYYY',
        '...YYYpYYYYYYYoY',
        '...YYYYYYYYYYYYo',
        '...YYYYYYYYYYYYY',
        '...YYYYYCYYYYYYY',
        '...YYYYYYYYYYYYY',
        '...CYYYYYYYYYYYY',
        '...YYYYYYYYYYYYY',
        '...YYYYYYYYYYYYY',
        '...BBBBBBBBBBBBB',
        '...BBBBBBBBBBBBB',
        '...WBWWBWWBWWBWW',
        '.....TTTT.......',
        '.....TTTT.......',
      ],
    },
  ],
};

/** モギッコ：長崎の びわ。だいだい色の 実に、ぎざぎざの 大きな 葉っぱ、そこに 茶色の へた（モリ） */
const mogikko: MonsterDesign = {
  size: 32,
  colors: {
    A: NQ.apricot,
    O: NQ.orange,
    B: NQ.brown,
    L: NQ.leaf,
    G: NQ.green,
    M: NQ.lime,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.apricot]: NQ.orange, [NQ.leaf]: NQ.green },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '..............BB',
        '..............BB',
        '.......LL...LLLL',
        '......LLLLLLLLLL',
        '.....LLLMLLLLLLL',
        '.....LLLLLMLLLLL',
        '......LLLLLLLLLL',
        '.........AAAAAAA',
        '.......AAAAAAAAA',
        '......AAAAAAAAAA',
        '.....AAAAAAAAAAA',
        '.....AAAAAAAAAAA',
        '....AAAAAAAAAAAA',
        '....AAAAAAWWAAAA',
        '....AAAAAAWoAAAA',
        '....AAAAAAWoAAAA',
        '....AAApAAAAAAoA',
        '....AAAAAAAAAAAo',
        '....AAAAAAAAAAAA',
        '....AAAAAAAAAAAA',
        '.....AAAAAAAAAAA',
        '.....AAAAAAAAAAA',
        '......AAAAAAAAAA',
        '.......AAAAAAAAA',
        '........AAAAAAAA',
        '.........AAAAAAA',
        '..........BBBBBB',
        '..........AAA...',
        '..........AAA...',
      ],
    },
    { x: 7, y: 10, rows: ['WW', 'W.'] },
  ],
};

/** ヤドシマ：小さな 島を せおった ヤドカリ。島の 上には 草と 小さな 松、下から 青い はさみと 足（ミズ） */
const yadoshima: MonsterDesign = {
  size: 32,
  colors: {
    A: NQ.azure,
    S: NQ.sky,
    W: NQ.white,
    p: NQ.blush,
    B: NQ.brown,
    T: NQ.tan,
    E: NQ.sand,
    L: NQ.leaf,
    G: NQ.green,
  },
  rim: { [NQ.azure]: NQ.blue, [NQ.brown]: NQ.bark, [NQ.leaf]: NQ.green },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '...............G',
        '..............GG',
        '.............GGG',
        '............GLLL',
        '..........LLLLLL',
        '........TBBBBBBB',
        '.......TTBBBBBBB',
        '......TTBBBBBBBB',
        '.....TBBBBBBBBBB',
        '....TBBBBBBBBBBB',
        '....BBBBBBBBBBBB',
        '...BBBBBBBBBBBBB',
        '...BBBBBBBBBBBBB',
        '...EEEEEEEEEEEEE',
        '....BBBBBBBBBBBB',
        '......AAAAAAAAAA',
        '.....AAAAAAAAAAA',
        '.....AAAAAAWWAAA',
        '.....AAAAAAWoAAA',
        '.....AAApAAWoAAA',
        '......AAAAAAAAoA',
        '......AAAAAAAAAo',
        '.......AAAAAAAAA',
        '.......AAAAAAAAA',
        '........AAAAAAAA',
        '.........AAAAAAA',
        '.........AAA.AAA',
        '.........AAA.AAA',
        '........SAAA.AAA',
      ],
    },
    // 大きな はさみ
    { mirror: true, y: 17, rows: ['..AAA', '.AAAA', '.AAoA', '.AAAA', '..AAA', '...AA'] },
    // 松の みきと 島の つや
    { x: 15, y: 4, rows: ['BB'] },
    { x: 5, y: 12, rows: ['TT', 'T.'] },
  ],
};

/**
 * メガネゴーレム（中ボス）：眼鏡橋の 石が あつまった ゴーレム。金ぶちの まるい めがね、下は アーチの 足、
 * 足もとには 川の 水。頭に 王冠（ツチ）
 */
const meganeGolem: MonsterDesign = {
  size: 40,
  colors: {
    N: NQ.slate,
    g: NQ.gray,
    G: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
    K: NQ.sky,
    A: NQ.azure,
    W: NQ.white,
  },
  rim: { [NQ.slate]: NQ.night, [NQ.gold]: NQ.ochre, [NQ.sky]: NQ.azure },
  rimDepth: 2,
  layers: [
    {
      mirror: true,
      rows: [
        '....................',
        '................G..G',
        '................GGGR',
        '................QQQQ',
        '.......NNNNNNNNNNNNN',
        '.....NNNNNNNNNNNNNNN',
        '....NNNNNNNNNNNNNNNN',
        '...NNNNNNNNNNNNNNNNN',
        '...NgNNNNNNgNNNNNNNN',
        '...NNNNNNNNNNNNNNNNN',
        '...NNNNNNNNNNNNNNNNN',
        '...ggggggggggggggggg',
        '...NNNNNNNNNNNNNNNNN',
        '...NNNNNNNNNNNNNNNNN',
        '...NNNNNNNNNNNNNNNNN',
        '...NNNNNNNNNNNNNNNNN',
        '...NNNNNNNNNNNNNNNNN',
        '...NNNNNNNNNNNNNNNNN',
        '...NNNNNNNNNNNNNNNNN',
        '...NNNNNNNNNNNNNNNNN',
        '...NNNNNNNNNNNNNNNNN',
        '...NgNNNNNNgNNNNNNNN',
        '...NNNNNNNNNNNNNNNNN',
        '...NNNNNNNNNNNNNNNNN',
        '...NNNNNNNNNNNNNoooo',
        '...NNNNNNNNNNNNNNNNN',
        '...ggggggggggggggggg',
        '...NNNNNNNNNNNNNNNNN',
        '...NNNNNNNNNNNNNNNNN',
        '...NNNNNNNNNNNNNNNNN',
        '...NNNNNNNNN........',
        '...NNNNNNN..........',
        '...NNNNNN...........',
        '...NNNNN............',
        '...NNNN.............',
        '...NNNN.............',
        '...NNNN.............',
        '...NNNN.............',
      ],
    },
    // うで（石の ブロック）
    {
      mirror: true,
      y: 14,
      rows: ['..NN', '.NNN', '.NNN', '.NNN', '.NNN', '.NNN', '.NNN', '.NNg', '.NNN', '.NNN', '..NN'],
    },
    // 金ぶちの まるい めがね
    {
      mirror: true,
      y: 13,
      rows: [
        '.......GGGGG........',
        '.....GGKKKKKGG......',
        '....GGKKKKKKKGG.....',
        '....GKKKKKKKKKG.....',
        '....GKKKKKKKKKG..GGG',
        '....GKKKKKKKKKG.....',
        '....GGKKKKKKKGG.....',
        '.....GGKKKKKGG......',
        '.......GGGGG........',
      ],
    },
    { mirror: true, y: 16, rows: ['........oo..........', '........oo..........', '........oo..........'] },
    { mirror: true, y: 15, rows: ['......W.............'] },
    // 川の 水
    {
      x: 2,
      y: 36,
      rows: [
        'KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
        'KAAKAAAAKAAAAKAAAAKAAAAKAAAAKAAAAKAA',
      ],
    },
  ],
};

/** メガネゴーレム（フィールドに立つ 32×32） */
const meganeGolemField: MonsterDesign = {
  size: 32,
  colors: {
    N: NQ.slate,
    g: NQ.gray,
    G: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
    K: NQ.sky,
    A: NQ.azure,
  },
  rim: { [NQ.slate]: NQ.night, [NQ.sky]: NQ.azure },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '............G..G',
        '............GGGR',
        '............QQQQ',
        '.....NNNNNNNNNNN',
        '...NNNNNNNNNNNNN',
        '..NNNNNNNNNNNNNN',
        '..NgNNNNNgNNNNNN',
        '..NNNNNNNNNNNNNN',
        '..gggggggggggggg',
        '..NNNNNNNNNNNNNN',
        '..NNNNNNNNNNNNNN',
        '..NNNNNNNNNNNNNN',
        '..NNNNNNNNNNNNNN',
        '..NNNNNNNNNNNNNN',
        '..NNNNNNNNNNNNNN',
        '..NNNNNNNNNNNNNN',
        '..NNNNNNNNNNNNNN',
        '..NNNNNNNNNNNooo',
        '..NNNNNNNNNNNNNN',
        '..gggggggggggggg',
        '..NNNNNNNNNNNNNN',
        '..NNNNNNNNNNNNNN',
        '..NNNNNNN.......',
        '..NNNNN.........',
        '..NNNN..........',
        '..NNNN..........',
        '..NNNN..........',
        '.KKKKKKKKKKKKKKK',
        '.AAAAAAAAAAAAAAA',
      ],
    },
    {
      mirror: true,
      y: 11,
      rows: [
        '.....GGGG.......',
        '...GGKKKKGG.....',
        '..GKKKKKKKG.....',
        '..GKKooKKKG..GGG',
        '..GKKooKKKG.....',
        '...GGKKKKGG.....',
        '.....GGGG.......',
      ],
    },
  ],
};

/** 湯けむりの 竜の 頭・からだ（左半分） */
const UNZEN_BODY = [
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '.................AAAAAAA',
  '...............AAAAAAAAA',
  '..............AAAAAAAAAA',
  '.............AAAAAAAAAAA',
  '............AAAAAAAAAAAA',
  '...........AAAAAAAAAAAAA',
  '...........AAAAAAAAAAAAA',
  '..........AAAAAAAAAAAAAA',
  '..........AAANNNAAAAAAAA',
  '..........AAAWWWAAAAAAAA',
  '..........AAAWWoAAAAAAAA',
  '..........AAAWWoAAAAAAAA',
  '..........AAAWooAAAAAAAA',
  '..........AAAAAAAAAAAAAA',
  '..........AAAAAAoooooooo',
  '...........AAAAoIIIIIIII',
  '...........AAAAoIIoIIIII',
  '............AAAoIIIIIIII',
  '............AAAoIIIIIIII',
  '.............AAoooooooII',
  '.............AAAWIIIIIII',
  '..............AAAIIIIIII',
  '...............AAAAAAAAA',
  '..............AAAAAAAAAA',
  '.............AAAAIIIIIII',
  '............AAAAIIIIIIII',
  '...........AAAAAIIIIIIII',
  '..........AAAAAAIIIIIIII',
  '.........AAAAAAAIIIIIIII',
  '........AAAAAAAAIIIIIIII',
  '.......AAAAAAAAAIIIIIIII',
  '......AAAAAAAAAAIIIIIIII',
  '......AAAAAAAAAAIIIIIIII',
];

/** 湯けむりの 雲（左半分、y 39〜45） */
const UNZEN_STEAM = [
  '...WWWWWWWWWWWWWWWWWWWWW',
  '..WWWcWWWWWWcWWWWWWWWWWW',
  '.WWWWWWWWcWWWWWWWWWcWWWW',
  '.WWWWWWWWWWWWWWWWWWWWWWW',
  '..WWWWWWWWWWWWWWWWWWWWWW',
  '...WWWWWWWWWWWWWWWWWWWWW',
  '.....WWWWWWWWWWWWWWWWWWW',
];

/**
 * ウンゼンリュウ（県ボス）：雲仙の 湯けむりから 生まれた 竜。太い 金の つのの あいだに 王冠、
 * とがった 氷色の たてがみ、長い ひげ、金の つめ、足もとは もくもくの 湯けむり（ミズ）
 */
const unzenRyu: MonsterDesign = {
  size: 48,
  colors: {
    A: NQ.azure,
    I: NQ.ice,
    S: NQ.sky,
    N: NQ.navy,
    W: NQ.white,
    c: NQ.cloud,
    m: NQ.mint,
    G: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
  },
  rim: { [NQ.azure]: NQ.blue, [NQ.ice]: NQ.sky, [NQ.gold]: NQ.ochre, [NQ.white]: NQ.cloud },
  rimDepth: 2,
  layers: [
    // 太い 金の つの
    {
      mirror: true,
      y: 2,
      rows: [
        '....GG..................',
        '....GG..................',
        '.....GG.................',
        '......GG................',
        '.......GG...............',
        '........GGG.............',
        '..........GGG...........',
        '............GGG.........',
        '..............GGG.......',
      ],
    },
    // とがった 氷色の たてがみ
    {
      mirror: true,
      y: 9,
      rows: [
        '.........III............',
        '........IIII............',
        '.......III..............',
        '........................',
        '.......IIII.............',
        '......IIII..............',
        '.....III................',
        '........................',
        '.....IIII...............',
        '....IIII................',
        '...III..................',
      ],
    },
    { mirror: true, rows: UNZEN_BODY },
    // 金の つめの ある 前足
    {
      mirror: true,
      y: 34,
      rows: ['....AAAAA...............', '...AAAAAA...............', '...AGAGAG...............'],
    },
    // 長い ひげ（ミント）
    {
      mirror: true,
      y: 23,
      rows: [
        '..........mm............',
        '........mm..............',
        '......mm................',
        '....mm..................',
        '...m....................',
        '..mm....................',
      ],
    },
    { mirror: true, y: 39, rows: UNZEN_STEAM },
    // 王冠
    {
      mirror: true,
      y: 1,
      rows: [
        '....................G..G',
        '....................GGGG',
        '....................GGGR',
        '....................QQQQ',
      ],
    },
  ],
};

/** ウンゼンリュウ 後半（ヒノ）：湯けむりが あつく なって だいだい色に かがやき、目が 金色に 光る */
const unzenRyuHot: MonsterDesign = {
  ...unzenRyu,
  colors: { ...unzenRyu.colors, W: NQ.cream, c: NQ.apricot, V: NQ.vermilion, E: NQ.gold },
  rim: { [NQ.azure]: NQ.blue, [NQ.ice]: NQ.sky, [NQ.gold]: NQ.ochre, [NQ.cream]: NQ.apricot },
  layers: [
    ...unzenRyu.layers,
    // 光る 目
    {
      mirror: true,
      y: 15,
      rows: [
        '..........AAAEEEAAA.....',
        '..........AAAEEoAAA.....',
        '..........AAAEEoAAA.....',
        '..........AAAEooAAA.....',
      ],
    },
    // 湯けむりの 中の 火の こ
    {
      mirror: true,
      y: 38,
      rows: ['......V.....V...........', '', '...V......V.........V...', '', '.....V.......V..........'],
    },
  ],
};

/**
 * シーボルト先生：出島の オランダ商館の 医者。こん色の 上着に 金の ボタン、赤い タイ、
 * 手には 日本で しらべた アジサイの 花（モリ）
 */
const siebold: MonsterDesign = {
  size: 48,
  colors: {
    N: NQ.night,
    S: NQ.slate,
    W: NQ.white,
    c: NQ.cloud,
    F: NQ.skinLight,
    f: NQ.skinMid,
    H: NQ.hairBrown,
    G: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
    L: NQ.lavender,
    V: NQ.violet,
    E: NQ.leaf,
  },
  rim: { [NQ.skinLight]: NQ.skinMid, [NQ.gold]: NQ.ochre, [NQ.slate]: NQ.night, [NQ.lavender]: NQ.violet },
  rimDepth: 2,
  layers: [
    {
      mirror: true,
      rows: [
        '........................',
        '........................',
        '........................',
        '........................',
        '........................',
        '..................HHHHHH',
        '...............HHHHHHHHH',
        '..............HHHHHHHHHH',
        '.............HHHHHHHHHHH',
        '.............HHHFFFFFFFF',
        '............HHHFFFFFFFFF',
        '...........HHHFFoooFFFFF',
        '...........HHHFFFWoFFFFF',
        '...........HHHFFFFFFFFFF',
        '...........HHHFFFFFFFfFF',
        '...........HHHfFFFFFFFoo',
        '............HHffFFFFFFFF',
        '.............H..ffffffff',
        '................WWWWWWWW',
        '...............WWWRRWWWW',
        '..............NNWWRRRWWW',
        '.............NNNNNRRRNNN',
        '...........NNNNNNNRRNNNN',
        '..........NNNNNNNNWWWNNN',
        '.........NNNNNNNNNWWWNNN',
        '.........NNNNNNNNNWWGNNN',
        '........NNNNNNNNNNWWWNNN',
        '........NNNNNNNNNNWWGNNN',
        '........NNNNNNNNNNWWWNNN',
        '........NNNNNNNNNNWWGNNN',
        '........NNNNNNNNNNWWWNNN',
        '........NNNNNNNNNNWWGNNN',
        '........NNNNNNNNNNNNNNNN',
        '........NNNNNNNNNNNNNNNN',
        '........NNNNNNNNNNNNNNNN',
        '........NNNNNNNNNNNNNNNN',
        '.........NNNNNNNNNNNNNNN',
        '.........NNNNNNNNNNNNNNN',
        '..........NNNNNNNNNNNNNN',
        '..........NNNNNNNNNNNNNN',
        '.............SSSSSSSS...',
        '.............SSSSSSSS...',
        '.............SSSSSSSS...',
        '.............SSSSSSSS...',
        '.............SSSSSSSS...',
        '............NNNNNNNNN...',
        '............NNNNNNNNN...',
      ],
    },
    // 右手と アジサイの 花
    { x: 32, y: 22, rows: ['NNNN', 'NNNN', 'NNFF', '..FF'] },
    {
      x: 33,
      y: 14,
      rows: ['..LLLL..', '.LLVLLL.', 'LLLLLLLL', 'LVLLLLVL', 'LLLLLLLL', '.LLLVLL.', '..LLLL..', '...EE...'],
    },
  ],
};

// ───────────────────────── しんか ─────────────────────────

/** カステルナイト：フワテラの しんか。こんがりの かぶとと 金の おび、木わくの たて（ヒカリ） */
const castelKnight: MonsterDesign = {
  size: 32,
  colors: {
    Y: NQ.yellow,
    C: NQ.cream,
    B: NQ.amber,
    T: NQ.tan,
    W: NQ.white,
    G: NQ.gold,
    Q: NQ.ochre,
    p: NQ.blush,
  },
  rim: { [NQ.yellow]: NQ.ochre, [NQ.tan]: NQ.brown },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '.........GGGGGGG',
        '........G.......',
        '.........QQQQQQQ',
        '.......BBBBBBBBB',
        '......BBBBBBBBBB',
        '......BBBBBBBBBB',
        '.....GGGGGGGGGGG',
        '....BBBBBBBBBBBB',
        '....BBBBBBBBBBBB',
        '....YYYYYYYYYYYY',
        '....YYYYYYYYYYYY',
        '....YYYYYooYYYYY',
        '....YYYYYYYoYYYY',
        '....YYYYYYWWYYYY',
        '....YYYYYYWoYYYY',
        '....YYYYYYWoYYYY',
        '....YYpYYYYYYooo',
        '....YYYYYYYYYoWW',
        '....GGGGGGGGGGGG',
        '....GQGQGQGQGQGQ',
        '....YYYYYYYYYYYY',
        '....YYYYYYCYYYYY',
        '....YYYYYYYYYYYY',
        '....YYYYYYYYYYYY',
        '....BBBBBBBBBBBB',
        '....BBBBBBBBBBBB',
        '....WBWWBWWBWWBW',
        '.....TTTT.......',
        '.....TTTT.......',
      ],
    },
    // 木わくの たて（左手）
    { x: 1, y: 15, rows: ['BBBBB', 'BTTTB', 'BTTTB', 'BTTTB', 'BTTTB', 'BBBBB'] },
    // 右の こぶし
    { x: 27, y: 15, rows: ['YYY', 'YYY', 'YYY'] },
  ],
};

/** モギタワワ：モギッコの しんか。えだに 実が たわわ。大きな 葉を 広げ、きりっと した まゆ（モリ） */
const mogiTawawa: MonsterDesign = {
  size: 32,
  colors: {
    A: NQ.apricot,
    O: NQ.orange,
    B: NQ.brown,
    L: NQ.leaf,
    G: NQ.green,
    M: NQ.lime,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.apricot]: NQ.orange, [NQ.leaf]: NQ.green, [NQ.brown]: NQ.bark },
  layers: [
    // えだと 小さな 実（左右）
    {
      mirror: true,
      y: 1,
      rows: [
        '......BBBBBBBBBB',
        '......B....B....',
        '.....AAA..AAA...',
        '.....AAA..AAA...',
        '......A....A....',
      ],
    },
    {
      mirror: true,
      rows: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
        '....LL......LLLL',
        '...LLLLLLLLLLLLL',
        '..LLLMLLLLLLLLLL',
        '..LLLLLLMLLLLLLL',
        '...LLLLLLLLLLLLL',
        '.......AAAAAAAAA',
        '.....AAAAAAAAAAA',
        '....AAAAAAAAAAAA',
        '...AAAAAAAAAAAAA',
        '...AAAAAoo.AAAAA',
        '...AAAAAAAoWWAAA',
        '...AAAAAAAAWoAAA',
        '...AAAAAAAAWoAAA',
        '...AAApAAAAAAAoA',
        '...AAAAAAAAAAAAo',
        '...AAAAAAAAAAAAA',
        '...AAAAAAAAAAAAA',
        '....AAAAAAAAAAAA',
        '.....AAAAAAAAAAA',
        '......AAAAAAAAAA',
        '.......AAAAAAAAA',
        '.........BBBBBBB',
        '.........AAAA...',
        '.........AAAA...',
      ],
    },
    { x: 6, y: 13, rows: ['WW', 'W.'] },
  ],
};

/** ヤドレットウ：ヤドシマの しんか。せなかの 島が ふえて 小さな 列島に。大きな はさみを かかげる（ミズ） */
const yadoRetto: MonsterDesign = {
  size: 32,
  colors: {
    A: NQ.azure,
    S: NQ.sky,
    W: NQ.white,
    p: NQ.blush,
    B: NQ.brown,
    T: NQ.tan,
    E: NQ.sand,
    L: NQ.leaf,
    G: NQ.green,
  },
  rim: { [NQ.azure]: NQ.blue, [NQ.brown]: NQ.bark, [NQ.leaf]: NQ.green },
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '...............G',
        '..............GG',
        '.............GGG',
        '.....G......GLLL',
        '....GG....LLLLLL',
        '...GLL..TBBBBBBB',
        '..TBBBBTTBBBBBBB',
        '..TBBBBTBBBBBBBB',
        '..EEEEEBBBBBBBBB',
        '...BBBBBBBBBBBBB',
        '...BBBBBBBBBBBBB',
        '..BBBBBBBBBBBBBB',
        '..BBBBBBBBBBBBBB',
        '..EEEEEEEEEEEEEE',
        '...BBBBBBBBBBBBB',
        '.....AAAAAAAAAAA',
        '....AAAAAAAAAAAA',
        '....AAAAAoo.AAAA',
        '....AAAAAAAWWAAA',
        '....AAAAAAAWoAAA',
        '....AAApAAAWoAAA',
        '.....AAAAAAAAAoA',
        '.....AAAAAAAAAAo',
        '......AAAAAAAAAA',
        '.......AAAAAAAAA',
        '........AAAAAAAA',
        '........AAA.AAAA',
        '........AAA.AAAA',
        '.......SAAA.AAAA',
      ],
    },
    // かかげた 大きな はさみ
    { x: 1, y: 12, rows: ['.AAAA', 'AAAAA', 'AAoAA', 'AAAAA', '.AAAA', '..AAA', '...AA', '...AA'] },
    { x: 25, y: 16, rows: ['AAAA', 'AAAA', 'AAoA', 'AAAA', '.AAA'] },
    { x: 15, y: 4, rows: ['BB'] },
  ],
};

/** クラワンボウ：青い呉須もようの 丈夫なおわんの子（ツチ） */
const kurawanbou: MonsterDesign = {
  size: 32,
  colors: { W: NQ.white, C: NQ.cloud, A: NQ.azure, B: NQ.blue, T: NQ.tan, p: NQ.blush },
  rim: { [NQ.white]: NQ.cloud, [NQ.azure]: NQ.blue },
  layers: [
    {
      mirror: true,
      y: 1,
      rows: [
        '...WWWWWWWWWW...',
        '..WWWWWWWWWWWW..',
        '.WWWWWWWWWWWWWW.',
        '.WWAAAAAAAAAAWW.',
        '.WWABABABABAWW..',
        '.WWAAAAAAAAAAWW.',
        '.WWWWWWWWWWWWWW.',
        '.WWWWWAAWWWWWWW.',
        '.WWWWWWWWWWWWWW.',
        '.WWWWWAAWWWWWWW.',
        '.WWWWWAAWWWWWWW.',
        '.WWWWWWWWWWWWWW.',
        '.WWWWWooWWWWWWW.',
        '.WWWWWWWooWWWWW.',
        '.WWWWWWWWWWWWWW.',
        '.WWWWWpWWWWWWWW.',
        '..WWWWWWWWWWWW..',
        '..WWWWWWWWWWWW..',
        '...WWWWWWWWWW...',
        '....WWWWWWWW....',
        '.....WWWWWW.....',
        '......WWWW......',
        '......CCCC......',
        '.....CC..CC.....',
        '....CC....CC....',
        '...CC......CC...',
        '...CC......CC...',
        '...CC......CC...',
        '...CC......CC...',
      ],
    },
  ],
};

/** クラワンヌシ：背いっぱいに呉須もようが広がった クラワンボウの進化（ツチ） */
const kurawanNushi: MonsterDesign = {
  ...kurawanbou,
  colors: { ...kurawanbou.colors, G: NQ.gold },
  layers: [
    ...kurawanbou.layers,
    {
      mirror: true,
      y: 4,
      rows: ['..AAAAAAAAAAAA..', '.AABBAABBAABBAA.', '..AAAAAAAAAAAA..', '...AABBAABBAA...'],
    },
    { mirror: true, y: 17, rows: ['...GGGGGGGGGG...', '....G......G....'] },
  ],
};

export const NAGASAKI: Readonly<Record<string, MonsterDesign>> = {
  'nagasaki-midboss-megane-golem': meganeGolem,
  'nagasaki-midboss-megane-golem.field': meganeGolemField,
  'nagasaki-boss-unzen-ryu': unzenRyu,
  'nagasaki-boss-unzen-ryu.p0': unzenRyuHot,
  'nagasaki-lastboss-siebold': siebold,
  'nagasaki-fuwatera': fuwatera,
  'nagasaki-castel-knight': castelKnight,
  'nagasaki-mogikko': mogikko,
  'nagasaki-mogi-tawawa': mogiTawawa,
  'nagasaki-yadoshima': yadoshima,
  'nagasaki-yado-retto': yadoRetto,
  'nagasaki-kurawanbou': kurawanbou,
  'nagasaki-kurawan-nushi': kurawanNushi,
};
