/** 岡山県の モンスター（手描き。docs/06 §4・§6.3〜6.5 の 規格） */
import { NQ } from '../palette';
import type { MonsterDesign } from './design';
import { FACE, HELMET, lord } from './lastbosses';

/** フクロモモ：紙の ふくろから 顔を 出した 岡山の 白桃。うすい もも色の 実に すじ、じくと 葉っぱ（モリ） */
const fukuromomo: MonsterDesign = {
  size: 32,
  colors: {
    F: NQ.skinLight,
    f: NQ.skinMid,
    P: NQ.blush,
    K: NQ.sand,
    S: NQ.beige,
    T: NQ.tan,
    W: NQ.white,
    L: NQ.leaf,
    G: NQ.green,
    B: NQ.brown,
  },
  rim: { [NQ.skinLight]: NQ.skinMid, [NQ.sand]: NQ.tan },
  layers: [
    {
      rows: [
        '................................',
        '..........GGG...................',
        '.........GLLLG.BB..GGG..........',
        '........GLLLLGBBB.GLLG..........',
        '.........GGGG.FBBBLLG...........',
        '.............FFFFGG.............',
        '...........FFFFFPfPPP...........',
        '.........FFFFFFPPfPPPPP.........',
        '........FFWWFFPPPPfPPPPP........',
        '.......FFWFFFFPPPPfPPPPPP.......',
        '.......FFFFFFFPPPPfPPPPPP.......',
        '......FFFFFFFFFPPPPPPPPPFF......',
        '......FFFFFWWFFFPPPWWPPFFF......',
        '......FFFFFWoFFFFFFoWFFFFF......',
        '......FFFFFWoFFFFFFoWFFFFF......',
        '......FFPPFFFFoFFoFFFFPPFF......',
        '......FFFFFFFFFooFFFFFFFFF......',
        '....FFFFKFKFFKFKFFKFKFFKFKFF....',
        '....FFSSSSSSSSSSSSSSSSSSSSFF....',
        '.....KKKKKKKKKKKKKKKKKKKKKK.....',
        '.....KKKKKKKKKKKKKKKKKKTKKK.....',
        '.....KKKTKKKKKKKKKKKKKTKKKK.....',
        '.....KKKKTKKKKKKKKKKKKTKKKK.....',
        '.....KKKKTKKKKKKKKKKKKTKKKK.....',
        '.....KKKKKTKKKKKKKKKKTKKKKK.....',
        '.....KKKKKTKKKKKTKKKKKKKKKK.....',
        '.....KKKKKKTKKKKKTKKKKKKKKK.....',
        '.....KKKKKKKKKKKKTKKKKKKKKK.....',
        '.....KKKKKKKKKKKKKTKKKKKKKK.....',
        '.....KKKKKKKKKKKKKKKKKKKKKK.....',
        '................................',
        '................................',
      ],
    },
  ],
};

/** ハクトウヒメ：フクロモモの しんか。紙の ふくろを ベールに して、ももの 花を かざった ももの おひめさま（モリ） */
const hakutoHime: MonsterDesign = {
  size: 32,
  colors: {
    F: NQ.skinLight,
    P: NQ.blush,
    E: NQ.paper,
    c: NQ.cloud,
    W: NQ.white,
    L: NQ.leaf,
    G: NQ.green,
    Y: NQ.yellow,
  },
  rim: { [NQ.skinLight]: NQ.skinMid, [NQ.paper]: NQ.cloud },
  layers: [
    {
      rows: [
        '................................',
        '..............GG.GG.............',
        '..............GLGLG.............',
        '..............PGGG..............',
        '.........EEEEPYPEEEEEPE.........',
        '.......PEEEEEEPEEEEEPYPEE.......',
        '.....EPYPEEEEEEEEEEEEPEEEEE.....',
        '....EEEPEEEEEEEEEEEEEEEEEPEE....',
        '....EEEEEEEEEEEEEEEEEEEEPYPE....',
        '...EEEEEEEEEEEEEEEEEEEEEEPEEE...',
        '...EEEEEEEEEFFFFFFFFEEEEEEEE....',
        '...EEEEEEEFFFFFFFFFFFFEEEEEE....',
        '...EEEEEEFFFFFFFFFFFFFFEEEEE....',
        '...EEEEEFooFFFFFFFFFFooFEEEE....',
        '...EEcEEFFFoFFFFFFFFoFFFEEcE....',
        '...EEEEEFFFWWFFFPPPWWPPFEEEE....',
        '...EEEEFFFFWoFFFFFPoWPPFFEEE....',
        '...EEEEEFFFWoFFFFFFoWFFFEEEE....',
        '...EEEEEPPFFFFFFFFFFFFPPEEEE....',
        '...EEEEFFFFFFoFFFFoFFFFFEEEE....',
        '...EEEcFFFFFFFooooFFFFFFEcEE....',
        '...EEEEFFFFFFFFFFFFFFFFFEEEE....',
        '...EEEEFFFFFFFFFFFFFFFFFEEEE....',
        '...EEEEFFFFFFFFFFFFFFFFFEEEE....',
        '..EEEEEFFFFFFFFFFFFFFFFFEEEEE...',
        '..EEEEE.FFFFFFFFFFFFFFFFEEEEE...',
        '..EEcEE..FFFFFFFFFFFFFF.EEEcE...',
        '..EEEEE...FFFFFFFFFFFF..EEEEE...',
        '..EEEEE...FFFFFFFFFFFF..EEEEE...',
        '..EEEEE.................EEEEE...',
        '................................',
        '................................',
      ],
    },
  ],
};

/** マスカットン：みどりに かがやく マスカットの ふさ。いちばん上の 大きな つぶに 顔、じくと ぶどうの 葉、金の わっか（ヒカリ） */
const muscatton: MonsterDesign = {
  size: 32,
  colors: {
    L: NQ.lime,
    E: NQ.leaf,
    G: NQ.green,
    S: NQ.sprout,
    W: NQ.white,
    p: NQ.blush,
    B: NQ.brown,
    Y: NQ.gold,
    Q: NQ.ochre,
  },
  rim: { [NQ.lime]: NQ.leaf },
  layers: [
    {
      rows: [
        '................................',
        '............YYYYYYYY............',
        '...........Y........Y...........',
        '............QQQQQQQQ............',
        '.........GGG...BB..G.G..........',
        '........GEEEG..BB.G.G...........',
        '........GEEEB..BB..GG...........',
        '.........GGG...BB...............',
        '..............LLLL..............',
        '....SLLL....SSLLLLLL....SLLL....',
        '....LLLLE...SLLLLLLL...LLLLE....',
        '....LLLLE..LWWLLLLWWE..LLLLE....',
        '....LLLLE..LWoLLLLoWE..LLLLE....',
        '.....EEE...LWoLLLLoWE...EEE.....',
        '...LSLL...pLLLLLLLLLEp...SLLL...',
        '...LLLLE...LLLoLLoLLE...LLLLE...',
        '...LLLLE....LLLooLLE....LLLLE...',
        '...LLEE.LL..LELLLLEE..LL.LEEE...',
        '......LSLLL...EEEE...SLLLL......',
        '......LLLLEE.LLLLLE.LLLLLE......',
        '......LLLLLE.LLLLLE.LLLLLE......',
        '......LLLLE..LLLLEE..LLLLE......',
        '.......EEEELLLLEEELLLLEEE.......',
        '..........SLLLL..LSLLL..........',
        '.........LLLLLE..LLLLLE.........',
        '.........LLLLLE..LLLLLE.........',
        '..........LLLLELLLLLLE..........',
        '..........LEEESLLLEEEE..........',
        '.............LLLLEE.............',
        '..............LLLE..............',
        '..............LEEE..............',
        '................................',
      ],
    },
  ],
};

/** エメラルドウ：マスカットンの しんか。宝石の ように 光る つぶ、大きな 金の わっかと きらめき、両がわに ぶどうの 葉（ヒカリ） */
const emeraldou: MonsterDesign = {
  size: 32,
  colors: {
    L: NQ.lime,
    E: NQ.leaf,
    G: NQ.green,
    S: NQ.sprout,
    W: NQ.white,
    p: NQ.blush,
    B: NQ.brown,
    Y: NQ.gold,
    Q: NQ.ochre,
  },
  rim: { [NQ.lime]: NQ.leaf },
  layers: [
    {
      rows: [
        '................................',
        '...........YYYYYYYYYY...........',
        '..........Y..........Y..........',
        '........GGGQQQQQQQQQQGGG........',
        '.......GEEEG...BB...GEEEG.......',
        '.......GEEEB...BB...BEEEG.......',
        '........GGG....BB....GGG........',
        '..............LLLL..............',
        '...WLLL.....SSLLLLLL....WLLLL...',
        '..LSLLLE..oSWLLLLLLLoo..LSLLLE..',
        '..LLLLLE..LSoLLLLLLoEE..LLLLLE..',
        '..LLLLLE..LLWWLLLLWWLE..LLLLEE..',
        '...LEEE...LLWoLLLLoWLE...LEEE...',
        '...LLL....LLWoLLLLoWLE....LLL...',
        '..SLLLE...pLLLLLLLLLLp...LSLLE..',
        '..LLLLE...LLLoLLLLoLLE...LLLLE..',
        '..LLLEE....LLLooooLLE....LLLLE..',
        '...EEELLL..LLLLLLLLEE..LLLEEE...',
        '.....WLLLL...EWEEEE...WLLLL.....',
        '.....LLLLE...LSLLLE...LLLLE.....',
        '....LLLLLEE..LLLLLE..LLLLLEE....',
        '.....LLLLE...LLLLLE...LLLLE.....',
        '.....LEEEELLLLLLLEELLLLEEEE.....',
        '.........LWLLLEEEEWLLLL.........',
        '.........LLLLLE..LLLLLE.........',
        '.........LLLLLE..LLLLLE......W..',
        '..W......LLLLEELLLLLLLE.....WYW.',
        '.WYW......EEEESLLLLEEE.......W..',
        '..W..........LLLLEE.............',
        '.............LLLLEE.............',
        '..............LEEE..............',
        '................................',
      ],
    },
  ],
};

/** ビゼンツボン：備前焼の つぼ。うわぐすりの ない 土の 色に、わらの あとの 赤い すじ「緋襷」と ごまの つぶ。口から 炎（ヒノ） */
const bizentsubon: MonsterDesign = {
  size: 32,
  colors: {
    E: NQ.sand,
    r: NQ.brick,
    B: NQ.brown,
    Q: NQ.ochre,
    W: NQ.white,
    p: NQ.blush,
    C: NQ.cream,
    Y: NQ.gold,
    A: NQ.apricot,
    V: NQ.vermilion,
  },
  rim: { [NQ.sand]: NQ.tan },
  rimDepth: 2,
  layers: [
    {
      rows: [
        '................................',
        '...............CC...............',
        '...............Y................',
        '..............AYA...............',
        '...........Y..AYA..Y............',
        '..........AYA.VAV.AYA...........',
        '..........VAV.VVV.VAV...........',
        '..........VVV.VVV.VVV...........',
        '..........BBBBBBBBBBBB..........',
        '..........BBBBBBBBBBBB..........',
        '............EEEEEEEE............',
        '............QEEErEEQ............',
        '.........QEEEEEErrEEEEQ.........',
        '.......EECEEEEEEEErEEEEEE.......',
        '......EQCEEEEEEEEErrEEEEQE......',
        '......EEEEEWWEEEEEEWWEEEEE......',
        '.....rEEEEEWoEEEEEEoWrEEEEE.....',
        '.....rrEEEEWoEEEEEEoWrrEEEE.....',
        '.....EErppEEEEEEEEEEEEppEEE.....',
        '.....EErEEEEEEoEEoEEEEErEEE.....',
        '.....EEErEEEEEEooEEEEEEErEE.....',
        '......EErrEEEEEEEEEEEEEErr......',
        '......EEErrEEEEEEEEEEEEEEE......',
        '.......EEEErEEEEEEEEEEEEE.......',
        '........EEErrEEEEEEEEEE.........',
        '........EEEEErEEEEEEEEE.........',
        '........EEEEErrEEEEEEEE.........',
        '.........EEEEEErEEEEEE..........',
        '.........EBBBBBBBBBBBB..........',
        '..........BB........BB..........',
        '................................',
        '................................',
      ],
    },
  ],
};

/** ビゼンオオツボ：ビゼンツボンの しんか。登り窯の 炎を たくわえた 大がめ。太い 緋襷、大きな 炎、土の うで（ヒノ） */
const bizenOotsubo: MonsterDesign = {
  size: 32,
  colors: {
    E: NQ.sand,
    r: NQ.brick,
    B: NQ.brown,
    Q: NQ.ochre,
    W: NQ.white,
    p: NQ.blush,
    C: NQ.cream,
    Y: NQ.gold,
    A: NQ.apricot,
    V: NQ.vermilion,
  },
  rim: { [NQ.sand]: NQ.tan },
  rimDepth: 2,
  layers: [
    {
      rows: [
        '................................',
        '...............C................',
        '...........C...Y....C...........',
        '...........Y..AYA...Y...........',
        '..........AYA.AYA..AYA..........',
        '.......Y..AYA.VAV..AYA.Y........',
        '......AYA.VAV.VVV..VAVAYA.......',
        '......VAV.VVV.VVV..VVVVAV.......',
        '......VVBBBBBBBBBBBBBBBBV.......',
        '........BBBBBBBBBBBBBBBB........',
        '..........EEEEEEEEEEEE..........',
        '.........EQErEQEEEEErQE.........',
        '.......CEEEErrEEEEEErrEEQ.......',
        '......CEEEEEEErEEEEEEErEEE......',
        '.....QEEEEEEEErrrEEEEErrrEQ.....',
        '....EEEEEEooEEEErrEEooEErrEE....',
        '....EEEEEEEWWEEEEErWWEEEEErE....',
        '...rrEEEEEEWoEEEEEroWEEEEErEE...',
        '..EEErEEEEEWoEEEEEEoWEEEEEEEEE..',
        '.EEEErrEppEEEEEEEEEEErppEEEEEEE.',
        '.EEEEErEEEEEEoEEEEoEErrEEEEEEEE.',
        '...EEErrEEEEEEooooEEEEErEEEEE...',
        '....EEEErEEEEEEEEEEEEEErrEEE....',
        '....EEEErrEEEEEEEEEEEEEErrEE....',
        '.....EEEEErEEEEEEEEEEEEEEEr.....',
        '......EEEErrEEEEEEEEEEEEEE......',
        '......EEEEEErEEEEEEEEEEEE.......',
        '.......EEEEErrEEEEEEEEEE........',
        '.......EEEEEErrEEEEEEEEE........',
        '.......EBBBBBBBBBBBBBBBB........',
        '................................',
        '................................',
      ],
    },
  ],
};

/** モウレツジャージー（中ボス）：蒜山高原の 大きな ジャージー牛。茶色の 毛、目の まわりが こく、白い わの 口もと、赤い くびわに 金の カウベル、はなから ゆげ（ツチ） */
const mouretsuJersey: MonsterDesign = {
  size: 40,
  colors: {
    T: NQ.tan,
    B: NQ.brown,
    S: NQ.sand,
    E: NQ.beige,
    W: NQ.white,
    c: NQ.cloud,
    N: NQ.night,
    G: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
    p: NQ.blush,
  },
  rim: { [NQ.tan]: NQ.brown, [NQ.beige]: NQ.sand },
  rimDepth: 2,
  layers: [
    {
      rows: [
        '........................................',
        '........................................',
        '................G..GG..G................',
        '.........E......GGGRRGGG.....E..........',
        '........EEE.....QQQQQQQQ....EEE.........',
        '........EEE.................EEE.........',
        '.........EEE.....BBBBBB....EEE..........',
        '..........EEE.....BBBB....EEE...........',
        '..........EEEE...TTTTTT..EEEE...........',
        '...........E...TTTTTTTTTT.EE............',
        '.............TTTTTTTTTTTTTT.............',
        '............TTTTTTTTTTTTTTTT............',
        '...TTTTTTT.oooTTTTTTTTTTTTooo.TTTTTTT...',
        '..TTTpppTTTTTBoBBTTTTTTBBoBTTTTTpppTTT..',
        '..TTTppppTTTWWWBBBTTTTBBBWWWTTTppppTTT..',
        '...TTTTTTTTBWWoBBBTTTTBBBoWWBTTTTTTTT...',
        '..........TBWooBBBTTTTBBBooWBT..........',
        '..........TBWooBBBTTTTBBBooWBT..........',
        '..........TTBBBBBBTTTTBBBBBBTT..........',
        '..........TTTBBBBTTTTTTBBBBTTT..........',
        '.........TTTTTTTTWWWWWWTTTTTTTT.........',
        '.......TTTTTTTTWWWNNNNWWWTTTTTTTT.......',
        '...cc.TTTTTTTTWWNNNNNNNNWWTTTTTTTT.cc...',
        '..cWcTTTTTTTTWWNNoNNNNoNNWWTTTTTTTTcWc..',
        '..ccTTTTTTTTTTWNNNNNNNNNNWTTTTTTTTTTcc..',
        '...cTTTTTTTTTTWNNNooooNNNWTTTTTTTTTTc...',
        '...TTTTTTTTTTTTWWNNNNNNWWTTTTTTTTTTTT...',
        '...TTTTTTTTTTTTTTTWWWWTTTTTTTTTTTTTTT...',
        '...TTTTTTSSTRRRRRRRRRRRRRRRRRTTTTTTTT...',
        '...TTTTTTSTTRRRRRRRRRRRRRRRRRTTTTTTTT...',
        '...TTTTTTTTTTTTTTTGGGGTTTTTTTTTTTTTTT...',
        '....TTTTTTTTTTTTTGGGGGGTTTTTTTTTTTTT....',
        '.....TTTTTTTTTTTTGGooGGTTTTTTTTTTTT.....',
        '......TTTTTTTTTTTGGGGGGTTTTTTTTTTT......',
        '.......TTTTTTTTTQQQQQQQTTTTTTTTTT.......',
        '.........TTTTTTTTTTTTTTTTTTTTTT.........',
        '.........TTTTTTTTTTTTTTTTTTTTTT.........',
        '.........NNNNNNN..TTTT..NNNNNNN.........',
        '.........NNNNNNN........NNNNNNN.........',
        '........................................',
      ],
    },
  ],
};

/** モウレツジャージー（フィールドに 立つ 32×32） */
const mouretsuJerseyField: MonsterDesign = {
  size: 32,
  colors: {
    T: NQ.tan,
    B: NQ.brown,
    E: NQ.beige,
    W: NQ.white,
    N: NQ.night,
    G: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
    p: NQ.blush,
  },
  rim: { [NQ.tan]: NQ.brown },
  layers: [
    {
      rows: [
        '................................',
        '............G..GG..G............',
        '............GGGRRGGG............',
        '......EE....QQQQQQQQ...EE.......',
        '.......EE.............EE........',
        '.......EEE...........EEE........',
        '........EEE.........EEE.........',
        '.........E..TTTTTTTT.E..........',
        '..........TTTTTTTTTTTT..........',
        '.........TTTTTTTTTTTTTT.........',
        '..TTTTTTTooBBTTTTTTBBooTTTTTTT..',
        '..TTpppTTTWWBBTTTTBBWWTTTpppTT..',
        '...TTTTTTBWoBBBTTBBBoWBTTTTTT...',
        '........TBWoBBBTTBBBoWBT........',
        '........TBBBBBTTTTBBBBBT........',
        '........TTBBBBTTTTBBBBTT........',
        '.......TTTTTTWWWWWWTTTTTT.......',
        '......TTTTTTWWNNNNWWTTTTTT......',
        '....TTTTTTTWNNNNNNNNWTTTTTTT....',
        '...TTTTTTTTWNNNNNNNNWTTTTTTTT...',
        '...TTTTTTTTWNNoNNoNNWTTTTTTTT...',
        '..TTTTTTTTTTTWWNNWWTTTTTTTTTTT..',
        '..TTTTTTTRRRRRRRRRRRRRRTTTTTTT..',
        '..TTTTTTTRRRRRRRRRRRRRRTTTTTTT..',
        '...TTTTTTTTTTTGGGGTTTTTTTTTTT...',
        '...TTTTTTTTTTTGGGGTTTTTTTTTTT...',
        '....TTTTTTTTTTGGGGTTTTTTTTTT....',
        '......TTTTTTTQQQQQQTTTTTTT......',
        '.......TTTTTTTTTTTTTTTTTT.......',
        '.......TTTTTTTTTTTTTTTTTT.......',
        '.......NNNNNN......NNNNNN.......',
        '................................',
      ],
    },
  ],
};

/** キビノオニオウ（県ボス）：桃太郎の 話の 鬼の 王。青い はだ、黒い かみと 2 本の つの、金の 目、とらの しまの こしまき、とげの 金棒。おびに 白桃の かざり（ヤミ） */
const kibiNoOnio: MonsterDesign = {
  size: 48,
  colors: {
    A: NQ.azure,
    B: NQ.blue,
    H: NQ.hairBlack,
    E: NQ.beige,
    G: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
    O: NQ.orange,
    W: NQ.white,
    g: NQ.gray,
    s: NQ.silver,
    P: NQ.blush,
  },
  rim: { [NQ.azure]: NQ.blue, [NQ.gold]: NQ.ochre, [NQ.orange]: NQ.amber, [NQ.gray]: NQ.slate },
  rimDepth: 2,
  layers: [
    {
      rows: [
        '................................................',
        '....................G..GG..G....................',
        '..............EE....GGGRRGGG...EE...............',
        '..gggggg......EEE...QQQQQQQQ..EEE...............',
        '..gggggg.......EEE...........EEE................',
        '..gggggg.......EEE..HHHHHHHH.EEE................',
        '..gsgggg.......EEEEHHHHHHHHHEEEE................',
        '..ggggsg........EEEEHHHHHHHEEEEH................',
        '..gggggg.......HEEEHAAAAAAAAEEEHH...............',
        '..gggggg...HH.HHHEHAAAAAAAAAAEHHHHHH............',
        '..ggsggg...HH.HHHHHHHAAAAAAHHHHHHHHH............',
        '..gggggg......HAAAAAAHAAAAHAAAAAAH..............',
        '..gggggs.....HHAAAAGGGAAAAGGGAAAAHH.............',
        '..gggggg......HAAAAGGoAAAAoGGAAAAH..............',
        '..gsgggg..HH..HHHAAGooAAAAooGAAHHH.HH...........',
        '..gggggg..HH..HHHAAGooAAAAooGAAHHH.HH...........',
        '..ggggsg.......HHAAAAABBBBAAAAAHH...............',
        '.gggggggg.......HHAAAAAAAAAAAAHH................',
        '.gggsgggg..HH.....AAooooooooAA....HH............',
        '....gg.....HH......AoWooooWoA.....HH............',
        '....gg...AAAAAA......oooooo......AAAAAA.........',
        '....gg..AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA........',
        '....gg..AAAAAAAAAAAAAABAABAAAAAAAAAAAAAA........',
        '....gg.AAAAAAAAAAAAAAABAABAAAAAAAAAAAAAAA.......',
        '....gg.AAGGGGAAAAAAAAABAABAAAAAAAAAGGGGA........',
        '....gg.AAGGGGAABBBBBBBBAABBBBBBBBAAGGGGAA.......',
        '....ggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA......',
        '....ggAAAA..AAAAAAAAAAAAAAAAAAAAAAA..AAAAA......',
        '....ggAAAA..AAAAAAAAAAAAAAAAAAAAAAA...AAA.......',
        '....AAAAAA...AAAAAABBAAAAAABBAAAAA....AAA.......',
        '...AAAAAA....AAAAAAAAAAAAAAAAAAAAA...AAA........',
        '...AAAAAA....AAAAAAAAAAAAAAAAAAAAA..AAAA........',
        '...AAAAAA.....AAAAAAAAAPPAAAAAAAA..AAAA.........',
        '....AAAA.....RRRRRRRRRPPPPRRRRRRRRR.AAA.........',
        '....gg.......RRRRRRRRRPPPWRRRRRRRRR..A..........',
        '....gg......HOOOHOOOHOOPPOOOHOOOHO..............',
        '....gg......HOOOHOOOHOOOHOOOHOOOHO..............',
        '....gg......HOOOHOOOHOOOHOOOHOOOHOO.............',
        '....gg......OHOOOHOOOHOOOHOOOHOOOHO.............',
        '....gg......OHOOOHOOOHOOOHOOOHOOOHO.............',
        '....gg.........AAAAAAA....AAAAAAA...............',
        '....gg.........AAAAAAA....AAAAAAA...............',
        '....gg.........AAAAAAA....AAAAAAA...............',
        '....gg.........GGGGGGG....GGGGGGG...............',
        '....gg.........AAAAAAA....AAAAAAA...............',
        '..............AAAAAAAA....AAAAAAAA..............',
        '..............AAAAAAAA....AAAAAAAA..............',
        '................................................',
      ],
    },
  ],
};

/** 後半の 炎（からだの うしろに 重ねる） */
const ONI_FIRE = [
  '................................................',
  '................G..............G................',
  '...............VG..............GV...............',
  '..............VVV..............VVV..............',
  '...........G....................................',
  '..........VGV...................................',
  '..........VVV...........................G.......',
  '...........V...........................VGV......',
  '.......................................VVV......',
  '........................................V.......',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '..........................................G.....',
  '.........................................VGV....',
  '.............G...........................VVV....',
  '............VGV...........................V.....',
  '............VVV.................................',
  '.............V..................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '........................................G.......',
  '.......................................VGV......',
  '.........G.............................VVV......',
  '........VGV.............................V.......',
  '........VVV.....................................',
  '.........V......................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
];

/** キビノオニオウ 後半（ヒノ）：いかって 赤鬼に なり、まわりに 炎が あがる */
const kibiNoOnioP0: MonsterDesign = {
  ...kibiNoOnio,
  colors: { ...kibiNoOnio.colors, A: NQ.red, B: NQ.brick, V: NQ.vermilion },
  rim: { [NQ.red]: NQ.brick, [NQ.gold]: NQ.ochre, [NQ.orange]: NQ.amber, [NQ.gray]: NQ.slate },
  layers: [{ rows: ONI_FIRE }, ...kibiNoOnio.layers],
};

/** 池田光政：池田家の しるし「あげは蝶」の 前立て、むらさきの よろい（ヒカリ） */
const ikedaMitsumasa = lord(
  [
    '...........GG.......N...',
    '..........GYYGG......N..',
    '.........GYYYYYGG.....N.',
    '.........GYYRRYYYGG....N',
    '..........GYYYYYYYYGG..N',
    '...........GGYYYYYYYGGGN',
    '............GYYGGGYYYGGN',
    '...........GYYYG..GYYGGN',
    '...........GRYG....GGG.N',
    '............GG.........N',
    ...HELMET,
    ...FACE,
  ],
  {
    N: NQ.night,
    L: NQ.slate,
    K: NQ.indigo,
    S: NQ.violet,
    G: NQ.gold,
    Y: NQ.yellow,
    R: NQ.red,
    T: NQ.navy,
    H: NQ.denim,
  },
  { [NQ.violet]: NQ.indigo },
);

const aizomen: MonsterDesign = {
  size: 32,
  colors: { D: NQ.denim, N: NQ.navy, A: NQ.azure, W: NQ.white, C: NQ.cloud, T: NQ.tan, p: NQ.blush },
  rim: { [NQ.denim]: NQ.navy, [NQ.azure]: NQ.blue },
  layers: [
    {
      mirror: true,
      y: 1,
      rows: [
        '.......AAA......',
        '.....AAAAAAA....',
        '....AAAAAAAAA...',
        '...AAAAAAAAAAA..',
        '..AAAADDDDAAAA..',
        '..AAADDDDDDAAA..',
        '.AAADDDDDDDDAAA.',
        '.AADDDDDDDDDDAA.',
        '.AADDDDWWDDDDAA.',
        '.AADDDDWoDDDDAA.',
        '.AADDDDDDDDDDAA.',
        '.AADDDpDDDDDDAA.',
        '.AADDDDDDDDDDAA.',
        '..ADDDDDDDDDDA..',
        '..AADDDDDDDDAA..',
        '...AADDDDDDDA...',
        '....AADDDDDA....',
        '.....AAAAAA.....',
        '......AAAA......',
        '.......TT.......',
        '......TTTT......',
        '.....TT..TT.....',
        '....TT....TT....',
        '...TT......TT...',
        '...TT......TT...',
        '...TT......TT...',
        '...TT......TT...',
        '...TT......TT...',
        '...TT......TT...',
      ],
    },
  ],
};

const denimBushi: MonsterDesign = {
  ...aizomen,
  colors: { ...aizomen.colors, G: NQ.gold, R: NQ.red },
  layers: [
    ...aizomen.layers,
    { mirror: true, y: 2, rows: ['....GGGGGGGG....', '...GGRRGGRRGG...', '....DDDDDDDD....'] },
    { mirror: true, y: 14, rows: ['.DGDGDGDGDGDGDG.', '..DDDDDDDDDDDD..', '...DD......DD...'] },
  ],
};

export const OKAYAMA: Readonly<Record<string, MonsterDesign>> = {
  'okayama-fukuromomo': fukuromomo,
  'okayama-hakuto-hime': hakutoHime,
  'okayama-muscatton': muscatton,
  'okayama-emeraldou': emeraldou,
  'okayama-bizentsubon': bizentsubon,
  'okayama-bizen-ootsubo': bizenOotsubo,
  'okayama-aizomen': aizomen,
  'okayama-denim-bushi': denimBushi,
  'okayama-midboss-mouretsu-jersey': mouretsuJersey,
  'okayama-midboss-mouretsu-jersey.field': mouretsuJerseyField,
  'okayama-boss-kibi-no-onio': kibiNoOnio,
  'okayama-boss-kibi-no-onio.p0': kibiNoOnioP0,
  'okayama-lastboss-ikeda-mitsumasa': ikedaMitsumasa,
};
