/** 沖縄県の モンスター（手描き。docs/06 §4・§6.3〜6.5 の 規格） */
import { NQ } from '../palette';
import type { MonsterDesign } from './design';

const one = (rows: string[]) => [{ rows }];
const half = (rows: string[]) => [{ mirror: true, rows }];

/** ゴーヤマル：いぼいぼの ゴーヤー。上に ヘタと つるの 葉（モリ） */
const goyamaru: MonsterDesign = {
  size: 32,
  colors: {
    G: NQ.green,
    M: NQ.lime,
    L: NQ.leaf,
    B: NQ.brown,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.green]: NQ.forest },
  layers: one([
    '................................',
    '................................',
    '................................',
    '.........L............L.........',
    '.........LLL...BB...LLL.........',
    '...........LL..BB..LL...........',
    '...............BB...............',
    '..............GBBG..............',
    '............GGGGGGGG............',
    '.........M.MGGGGGGGGM.M.........',
    '..........MGMGGGGGGMGM..........',
    '.........MMGGGGGGGGGGMM.........',
    '.........MGGGGGGGGGGGGM.........',
    '........GGGGMGGGGGGMGGGG........',
    '........GGGGGMGGGGMGGGGG........',
    '........GMGGGGGGGGGGGGMG........',
    '........GGWWMGGGGGGMWWGG........',
    '.......GGGWoGGGGGGGGoWGGG.......',
    '.......GGMWoGGGGGGGGoWMGG.......',
    '.......GppGGMGGGGGGMGGppG.......',
    '.......GGGGMGGGGGGGGMGGGG.......',
    '........GMGGGGoGGoGGGGMG........',
    '........GGGGMGGooGGMGGGG........',
    '........GGGGGGGGGGGGGGGG........',
    '........GMGGGGMGGMGGGGMG........',
    '.........GGGMGGGGGGMGGG.........',
    '.........MGGGGGGGGGGGGM.........',
    '.........MGGGGGGGGGGGGM.........',
    '...........GMGGGGGGMG...........',
    '............GGGGGGGG............',
    '..............GGGG..............',
    '................................',
  ]),
};

/** ゴーヤムシャ（ゴーヤマルの しんか）：いぼいぼの 皮を よろいに した 武者。葉の かぶと、つるの むち（モリ） */
const goyaMusha: MonsterDesign = {
  size: 32,
  colors: {
    G: NQ.green,
    M: NQ.lime,
    L: NQ.leaf,
    B: NQ.brown,
    E: NQ.sand,
    F: NQ.forest,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.green]: NQ.forest },
  layers: one([
    '................................',
    '................................',
    '.......LL..............LL.......',
    '.......LLLL....BB....LLLLLEE....',
    '.........LLL...BB...LLL.L...EE..',
    '...........L...BB...L........E..',
    '..............GGGG............E.',
    '............GGGGGGGG..........E.',
    '..........MGGMGGGGMGGM........E.',
    '........MMGGGGGGGGGGGGMM.....E..',
    '........MMGMGGGGGGGGMGMM...EE...',
    '........MGGGGMGGGGMGGGGM..E.....',
    '........MGGGGGGGGGGGGGGM.E......',
    '.......GGooMMGGGGGGMMooGG.......',
    '.......GGGGoGMGGGGMGoGGGG.......',
    '.......GMGWWGGGGGGGGWWGMG.......',
    '.......GGGWoGGGGGGGGoWGGG.......',
    '.......GGGWoGMGGGGMGoWGGG.......',
    '.......GpGGGGGGGGGGGGGGpG.......',
    '.......GGGMMGoGGGGoGMMGGG.......',
    '.......GGGGGGMooooMGGGGGG.......',
    '.......GEEEEEEEEEEEEEEEEG.......',
    '.......GFFFFFFFFFFFFFFFFG.......',
    '.......GGGGGGMGGGGMGGGGGG.......',
    '........MGGGGGGGGGGGGGGM........',
    '........MGGMGGGGGGGGMGGM........',
    '.........GGGGMGGGGMGGGG.........',
    '........M.GMGGGGGGGGMG.M........',
    '..........GMGGGGGGGGMG..........',
    '............GGMGGMGG............',
    '..............GGGG..............',
    '................................',
  ]),
};

/** パイナポン：あみ目の 皮の パイナップル。上に とがった 葉（ヒカリ） */
const painapon: MonsterDesign = {
  size: 32,
  colors: {
    O: NQ.orange,
    M: NQ.amber,
    G: NQ.green,
    F: NQ.forest,
    L: NQ.leaf,
    C: NQ.cream,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.orange]: NQ.amber },
  layers: one([
    '................................',
    '................................',
    '.............GG..GG.............',
    '.............GG..GG.............',
    '..............G..G..............',
    '..............G..G..............',
    '........G.....GGGG.....G........',
    '........GGF...GGGG...FGG........',
    '.........GGF...GG...FGG.........',
    '..........GGF..GG..FGG..........',
    '...........GGF.GG.FGG...........',
    '............GG.GG.GG............',
    '.......LLL.OMGOOOOGMO.LLL.......',
    '.......LLLLLLLOMMOLLLLLLL.......',
    '.........OCLLOMOOMOLLCO.........',
    '........OCOMOMOMMOMOMOCO........',
    '.......OCOOOMOOOOOOMOOOCO.......',
    '.......MOMOMOMOMMOMOMOMOM.......',
    '......MOOOWWOOMOOMOOWWOOOM......',
    '......OMOMWoOMOMMOMOoWMOMO......',
    '......OOMOWoMOOOOOOMoWOMOO......',
    '......OMppOMOMOMMOMOMOppMO......',
    '......MOOOMOOOMOOMOOOMOOOM......',
    '......OMOMOMOMoMMoMOMOMOMO......',
    '.......OMOOOMOOooOOMOOOMO.......',
    '.......MOMOMOMOMMOMOMOMOM.......',
    '........OOMOOOMOOMOOOMOO........',
    '.........MOMOMOMMOMOMOM.........',
    '..........OOMOOOOOOMOO..........',
    '...........MOMOMMOMOM...........',
    '...............OO...............',
    '................................',
  ]),
};

/** オウゴンパイン（パイナポンの しんか）：こがね色に かがやく 大きな パイナップル。まわりに 光の つぶ（ヒカリ） */
const ougonPine: MonsterDesign = {
  size: 32,
  colors: {
    Y: NQ.gold,
    O: NQ.orange,
    G: NQ.green,
    F: NQ.forest,
    L: NQ.leaf,
    C: NQ.cream,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.gold]: NQ.ochre },
  layers: one([
    '................................',
    '............GGG..GGG............',
    '.............GG..GG.............',
    '.............GG..GG.............',
    '.............GG..GG.............',
    '.......GG.....G..G.....GG....C..',
    '.......GGF....GGGG....FGG...C...',
    '...C.....GF...GGGG...FG......C..',
    '..C.......GFF..GG..FFG..........',
    '...C.......GGF.GG.FGG...........',
    '............GGOGGOGG............',
    '......LLLL.OYGYOOYGYO.LLLL......',
    '......LLLLLLLLYYYYLLLLLLLL......',
    '........YOCLLOYOOYOLLCOY........',
    '.......YYCOYYYOYYOYYYOCYY.......',
    '.......OCOYOYOYOOYOYOYOCO.......',
    '......YYOooYOYYYYYYOYooOYY......',
    '......YOYOYoYOYOOYOYoYOYOY......',
    '.....YOYYYWWYYOYYOYYWWYYYOY.....',
    '.....OYOYOWoYOYOOYOYoWOYOYO.....',
    '.....YYYOYWoOYYYYYYOoWYOYYY.....',
    '.....OYOpOYOYOYOOYOYOYOpOYO.....',
    '.....YOYYYOYYYOYYOYYYOYYYOY.....',
    '......YOYOYOYoYOOYoYOYOYOY......',
    '......YYOYYYOYooooYOYYYOYY......',
    '.......OYOYOYOYOOYOYOYOYO.......',
    '....C..YYYOYYYOYYOYYYOYYY.......',
    '........YOYOYOYOOYOYOYOY...C....',
    '.........YYYOYYYYYYOYYY.........',
    '...........OYOYOOYOYO...........',
    '.............YOYYOY.............',
    '................................',
  ]),
};

/** ガラスクラゲ：琉球ガラスの クラゲ。中に あわの つぶ、ゆらゆらの あし（ミズ） */
const garasuKurage: MonsterDesign = {
  size: 32,
  colors: {
    A: NQ.aqua,
    I: NQ.ice,
    S: NQ.sky,
    M: NQ.mint,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.aqua]: NQ.teal },
  layers: one([
    '................................',
    '................................',
    '................................',
    '................................',
    '................................',
    '..............AAAA..............',
    '...........AAAAAAAAAA...........',
    '.........AAMAAAAAAAAMAA.........',
    '........AMMAAAAAAAAAAMMA........',
    '.......AMAAAWAAAAAAWAAAMA.......',
    '......AAAAAAAAAAAAAAAAAAAA......',
    '.....AAAAAAAAAAAAAAAAAAAAAA.....',
    '.....AAAAWAWWWAAAAWWWAWAAAA.....',
    '.....AAAAAAWoAAAAAAoWAAAAAA.....',
    '.....AAAAIIWoIIIIIIoWIIAAAA.....',
    '.....AAIIppIIIWIIWIIIppIIAA.....',
    '.....AIIIIWIIIIIIIIIIWIIIIA.....',
    '......IIIIIIIIoIIoIIIIIIII......',
    '.......IIIIIIIIooIIIIIIII.......',
    '........AIIIIIIIIIIIIIIA.I......',
    '........SAAASAAASAAASAA.S.......',
    '........S..ASAAASAAAS...S.......',
    '.........I...IAAAI...I...I......',
    '.........S...S...S...S...S......',
    '........S...S...S...S...S.......',
    '........I...I...I...I...I.......',
    '.........S...S...S...S...S......',
    '.........S...S...S...S...S......',
    '........I...I...I...I...I.......',
    '........S...S...S...S...S.......',
    '................................',
    '................................',
  ]),
};

/** ニジイロクラゲ（ガラスクラゲの しんか）：大きな かさが 虹色に かがやく クラゲ。長い あし（ミズ） */
const nijiKurage: MonsterDesign = {
  size: 32,
  colors: {
    A: NQ.aqua,
    I: NQ.ice,
    S: NQ.sky,
    M: NQ.mint,
    V: NQ.violet,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.aqua]: NQ.teal },
  layers: one([
    '................................',
    '................................',
    '................................',
    '................................',
    '...........AAAAAAAAAA...........',
    '.........AAAAAAAAAAAAAA.........',
    '.......AAAAAAAAAAAAAAAAAA.......',
    '......SSSSSSSSSSSSSSSSSSSS......',
    '.....SSSSSSSWSSSSSSWSSSSSSS.....',
    '....SSSSSooSSSSSSSSSSooSSSSS....',
    '....VVVVVVVoVVVVVVVVoVVVVVVV....',
    '....VVVVVWVWWVVVVVVWWVWVVVVV....',
    '....VVVVVVVWoVVVVVVoWVVVVVVV....',
    '....MMMWMMMWoIIIIIIoWMMMWMMM....',
    '....MMIIIpIIIIWIIWIIIIpIIIMM....',
    '....IIIIIIIIIIIIIIIIIIIIIIII....',
    '....IIIIIIIIIoIIIIoIIIIIIIII....',
    '.....IIIIIIIIIooooIIIIIIIII.....',
    '......AVIIIVIIIVIIIVIIIVIA.V....',
    '.......SAAASAIISIIISAAASA..S....',
    '......S..ASAAASAAASAAAS...S.....',
    '......V...VAAAVAAAVAA.V...V.....',
    '.......S...S...S...S...S...S....',
    '.......S...S...S...S...S...S....',
    '......V...V...V...V...V...V.....',
    '......S...S...S...S...S...S.....',
    '.......S...S...S...S...S...S....',
    '.......V...V...V...V...V...V....',
    '......S...S...S...S...S...S.....',
    '......S...S...S...S...S...S.....',
    '.......V...V...V...V...V...V....',
    '................................',
  ]),
};

/**
 * エイサーダイコ（中ボス）：エイサーの 大太鼓が おどりだした すがた。赤い ふちと 金の はちまき、
 * 木の うでで ばちを かまえ、足で リズムを とる。頭に 王冠（カゼ）
 */
const eisaDaiko: MonsterDesign = {
  size: 40,
  colors: {
    C: NQ.cream,
    S: NQ.sand,
    R: NQ.red,
    B: NQ.brown,
    K: NQ.bark,
    T: NQ.tan,
    Y: NQ.gold,
    Q: NQ.ochre,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.cream]: NQ.sand, [NQ.red]: NQ.brick },
  rimDepth: 2,
  layers: half([
    '....................',
    '................Y..Y',
    '................YY.Y',
    '................YYYY',
    '................YYYR',
    '...RRRR.........QQQQ',
    '.TTRRRRRRRRRRRRRRRRR',
    '..TTRRRRYYYYYYYYYYYY',
    '..TT....RRRRRRRRRRRR',
    '...TT...............',
    '...TT...............',
    '....TT..............',
    '....BBB........RRRRR',
    '....BBBB.....RRRRKRR',
    '.....BBB...RRRRRCCCC',
    '......BBB.RRSKCCCCCC',
    '......BBBRRSCKKCCCCC',
    '.......BRRSCCCCKKKCC',
    '.......BRKSCCCWWoCCC',
    '.......RRCCCCCWWoCCC',
    '......BRRCCCCCWWoCCC',
    '......BRRCCCCCWooCCC',
    '......BRKCCCCCCCCCCC',
    '......BRRCCCCCCCCCCC',
    '......BRRCCCpCCCCCCC',
    '......BRRCCCCCCCCooo',
    '......BRKCCCCCCCCCoo',
    '.......BRRCCCCCCCCCC',
    '.......BRRRCCCCCCCCC',
    '........BRRRCCCCCCCC',
    '.........BRKRCCCCCCC',
    '..........BRRRRRCCCC',
    '...........BBRRKRRRR',
    '.............BBRRRRR',
    '.............BBBBBBB',
    '.............BBBB...',
    '.............BBBB...',
    '............WWWWWW..',
    '............WWWWWW..',
    '....................',
  ]),
};

/** エイサーダイコ（フィールドに 立つ 32×32） */
const eisaDaikoField: MonsterDesign = {
  size: 32,
  colors: {
    C: NQ.cream,
    S: NQ.sand,
    R: NQ.red,
    B: NQ.brown,
    K: NQ.bark,
    T: NQ.tan,
    Y: NQ.gold,
    Q: NQ.ochre,
    W: NQ.white,
  },
  rim: { [NQ.cream]: NQ.sand, [NQ.red]: NQ.brick },
  layers: half([
    '................',
    '.............Y..',
    '.............YY.',
    '.............YYY',
    '.............YYR',
    '.............QQQ',
    '.T.....RRRRRRRRR',
    '..T....YYYYYYYYY',
    '..T.............',
    '..T.............',
    '...TB...........',
    '...BBB.....RRRRR',
    '....BB...BRRRRRC',
    '.....BB.RRKKCCCC',
    '.....BBBRRCCCCCC',
    '......BRRCCWWCCC',
    '.....BRRCCCWoCCC',
    '.....BRRCCCooCCC',
    '.....BRRCCCCCCCC',
    '.....BRCCCCCCCCC',
    '.....BRCCCCCCCCC',
    '.....BRRCCCCCooC',
    '.....BRRCCCCCCCC',
    '.....BBRRCCCCCCC',
    '......BRRRCCCCCC',
    '.......BRRRCCCCC',
    '........BRRRRRCC',
    '.........BBRRRRR',
    '...........BBBRR',
    '...........BBB..',
    '..........WWWWW.',
    '................',
  ]),
};

/**
 * ダイリュウチュウ（県ボス）：首里城の 正殿の 前に 立つ 石の 龍柱が 動きだした すがた。
 * 石の うろこの からだが 柱に まきつき、朱と 金の かざり。頭に 王冠（ツチ。後半は 2 回 行動）
 */
const dairyuchu: MonsterDesign = {
  size: 48,
  colors: {
    g: NQ.gray,
    L: NQ.slate,
    i: NQ.silver,
    R: NQ.red,
    Y: NQ.gold,
    Q: NQ.ochre,
    W: NQ.white,
  },
  rim: { [NQ.gray]: NQ.slate },
  rimDepth: 2,
  layers: one([
    '................................................',
    '...........ig.......Y..YY..Y.......gi...........',
    '..........ig.g.....YY.YYYY.YY.....g.gi..........',
    '..........ggggg....YYYYYYYYYY....ggggg..........',
    '.............g.g...YYYYRRYYYY...g.g.............',
    '..............g.g.iQQQQQQQQQQi.g.g..............',
    '...............LLLggggggggggggLLL...............',
    '................ggLLLLggggLLLLgg................',
    '...............ggWWoggggggggoWWgg...............',
    '...............LgWWoggggggggoWWgL...............',
    '............LLLLgWWoggggggggoWWgLLLL............',
    '...........LLLLggWooggggggggooWggLLLL...........',
    '..........LLLLLggggggggggggggggggLLLLL..........',
    '..........LL...ggggggiiiiiigggggg...LL..........',
    '................gggiiiiiiiiiiggg................',
    '.................giiiioiioiiiig.................',
    '.......i..........iiiiiiiiiiii..........i.......',
    '........i.......iiiiiiiiiiiiiiii.......i........',
    '.........i..iiii..giiiiiiiiiig..iiii..i.........',
    '..........ii......goooooooooog......ii..........',
    '...........LLLL...ggWggWWggWgg..................',
    '...........gggLLLLLLLggiiggLgg..................',
    '...........igggggggggLLLLLLLgg..................',
    '........W..ggggigggiggggggggLLLLLLL.............',
    '.........i.ggggggggggggigggiggggggLLLL..........',
    '........i..ggggggggggggggggggggigggggg..........',
    '...........LLLgggggggggggggggggggggigg..........',
    '..............LLLLLLLggggggggggggggggg..........',
    '..................ggLLLLLLLLggggggLLLL..........',
    '..................ggLggiiggLLLLLLLLggi..........',
    '..................ggLggiiggLgi.ggigggg..........',
    '..............LLL.ggLigiiigLgg.ggggggg..........',
    '...........LLLLggiggLggiiggLgg.ggggLLL..........',
    '...........ggiggg.ggLggiiggLgg.LLLL.............',
    '...........LLLLgg.ggLggiiggLgg..................',
    '...........gggLLLLLLLggiiggLgg..................',
    '...........igggggggggLLLLLLLgg..................',
    '...........ggggigggiggggggggLLLLLLL.............',
    '...........ggggggggggggigggiggggggLLLL.W........',
    '...........ggggggggggggggggggggiggggggi.........',
    '...........LLLgggggggggggggggggggggigg.i........',
    '..............LLLLLLLggggggggggggggggg..........',
    '..................ggLLLLLLLLgggggggggg..........',
    '..............YYYYYYYYYYYYYYLLLLLLgggg..........',
    '..............ggggggggggggggggggggLLLL..........',
    '..............gggggggggggggggggggg..............',
    '................RRRRRRRRRRRRRRRR................',
    '................................................',
  ]),
};

/** ダイリュウチュウ 後半：石が 朱と 金に 光りだし、まわりに きらめき */
const dairyuchuShine: MonsterDesign = {
  ...dairyuchu,
  colors: { ...dairyuchu.colors, g: NQ.red, L: NQ.brick, i: NQ.vermilion },
  rim: { [NQ.red]: NQ.brick },
  layers: [
    ...dairyuchu.layers,
    { mirror: true, x: 2, y: 6, rows: ['.Y.', 'YQY', '.Y.'] },
    { mirror: true, x: 5, y: 24, rows: ['.Y.', 'YQY', '.Y.'] },
    { mirror: true, x: 9, y: 2, rows: ['Y'] },
  ],
};

/** 尚巴志：琉球の 王。金の 玉冠と 朱の ころも、金の 帯、手に 金の おうぎ（ヒカリ） */
const shoHashi: MonsterDesign = {
  size: 48,
  colors: {
    F: NQ.skinLight,
    f: NQ.skinMid,
    H: NQ.hairBlack,
    W: NQ.white,
    R: NQ.red,
    Y: NQ.gold,
    Q: NQ.ochre,
    A: NQ.azure,
    C: NQ.cream,
    K: NQ.bark,
  },
  rim: { [NQ.skinLight]: NQ.skinMid, [NQ.red]: NQ.brick },
  rimDepth: 2,
  layers: one([
    '................................................',
    '.....................YYYYYY.....................',
    '...................YYYAYYAYYY...................',
    '.................YYRYCYYYYCYRYY.................',
    '.................YYYCYYYYYYCYYY.................',
    '.................RYYYYYYYYYYYYR.................',
    '.................YYYYYYYYYYYYYY.................',
    '................HQQQQQQQQQQQQQQH................',
    '................HHYYYYYYYYYYYYHH................',
    '................HHHHYYYYYYYYHHHH................',
    '................FHHHHHHHHHHHHHHF................',
    '................FHHHHHHHHHHHHHHF................',
    '................FFFWWHHHHHHWWFFF................',
    '................FFWooFFFFFFooWFF................',
    '...............FFFWooFFFFFFooWFFF...............',
    '...............FFFFFFFFFFFFFFFFFF...............',
    '...............fFFFFFFFffFFFFFFFf...............',
    '................FFFFFFFFFFFFFFFF................',
    '.................FFFHHHHHHHHFFF.................',
    '..................FHHFFooFFHHF..................',
    '...................FFFFFFFFFF...................',
    '...................HHHHHHHHHH...................',
    '...................HHHHHHHHHH...................',
    '................RRWWWFFFFFFWWWRR................',
    '..............RRRRWWWWWWWWWWWWRRRR..............',
    '............RRRRRRRWWWWWWWWWWRRRRRRR............',
    '..........RRRRRRRRRWWWWWWWWWWRRRRRRRRR..........',
    '.........RRRRRYRRRRWWYWWWWYWWRRRRYRRRRR.........',
    '.......RRRRRRYQYRRRRYQYWWYQYRRRRYQYRRRRRR.......',
    '......RRRRRRRRYRRRRRWYWWWWYWRRRRRYRRRRRRRR......',
    '.....RRRRRRRRRRRRRRRWWWWWWWWRRRRRRRRRRRRRRR.....',
    '.....RRRRRYYYYYYYYYYYYYYYYYYYYYYYYYYYYRRRRR.....',
    '.....RRRRRYYYYYYYYYYYYYYYYYYYYYYYYYYYYRRRRR.....',
    '.....RRRRRQQQQQQQQFFFQQQQQQFFFQQQQQQQQRRRRR.....',
    '.....RRRRRRRRRRRRRFFFYYYYYYFFFRRRRRRRRRRRRR.....',
    '.....RRRRRRRRRRRRRFFFYYYYYYFFFRRRRRRRRRRRRR.....',
    '.....RRRRRRRRRRRRRFFFQQQQQQFFFRRRRRRRRRRRRR.....',
    '.....RRRRRRRRRRRRYFFFQQQQQQFFFYRRRRRRRRRRRR.....',
    '.....RRRRRRRRRRRYQYRYRRRRRRYRYQYRRRRRRRRRRR.....',
    '.....RRRRRRRRRRRRYRYQYRRRRYQYRYRRRRRRRRRRRR.....',
    '......FFFFFRRYRRRRRRYRRRRRRYRRRRRRYRRFFFFF......',
    '......FFFFFRYQYRRRRRRRRRRRRRRRRRRYQYRFFFFF......',
    '......FFFFFRRYRRRRRRRRRRRRRRRRRRRRYRRFFFFF......',
    '..........RRRRRRRRRRRRRRRRRRRRRRRRRRRR..........',
    '............WWWWWWWW........WWWWWWWW............',
    '............WWWWWWWW........WWWWWWWW............',
    '...........KKKKKKKKKK......KKKKKKKKKK...........',
    '................................................',
  ]),
};

export const OKINAWA: Readonly<Record<string, MonsterDesign>> = {
  'okinawa-goyamaru': goyamaru,
  'okinawa-goya-musha': goyaMusha,
  'okinawa-painapon': painapon,
  'okinawa-ougon-pine': ougonPine,
  'okinawa-garasu-kurage': garasuKurage,
  'okinawa-niji-kurage': nijiKurage,
  'okinawa-midboss-eisa-daiko': eisaDaiko,
  'okinawa-midboss-eisa-daiko.field': eisaDaikoField,
  'okinawa-boss-dairyuchu': dairyuchu,
  'okinawa-boss-dairyuchu.p0': dairyuchuShine,
  'okinawa-lastboss-sho-hashi': shoHashi,
};
