/** 滋賀県の モンスター（手描き。docs/06 §4・§6.3〜6.5 の 規格） */
import { NQ } from '../palette';
import type { MonsterDesign } from './design';
import { FACE, HELMET, lord } from './lastbosses';

/** ニゴロン：琵琶湖の ニゴロブナ（ふなずしの ふな）。しっぽで 立つ 金茶の 魚、うろこ・えら・水色の ひれ、すぼめた 口（ミズ） */
const nigoron: MonsterDesign = {
  size: 32,
  colors: {
    B: NQ.sand,
    D: NQ.tan,
    E: NQ.beige,
    F: NQ.sky,
    A: NQ.azure,
    W: NQ.white,
    p: NQ.blush,
    C: NQ.cream,
  },
  rim: { [NQ.sand]: NQ.tan, [NQ.sky]: NQ.azure },
  layers: [
    {
      x: 2,
      y: 1,
      rows: [
        '.............FF',
        '............FAAF',
        '...........FAFFAF',
        '.............DD',
        '..........C.DDDD',
        '.........C.DDDDDD',
        '..........DDDDDDDD',
        '........BBDDDDDDDDBB',
        '......CBWWBDDDDDDBWWB',
        '.....DBBWoBBBBBBBBoWBBD',
        '....DBBBWoBBBBBBBBoWBBBD',
        '....DBppBBBBBBBBBBBBppBD',
        '....DDBBDDBBDooBDDBBDDBD',
        '....BDDDBBDDoppoBBDDBBDD',
        '....BBDDBBDDBooDBBDDBBDB',
        '...BDDBBDDBBDDBBDDBBDDBBB',
        '.FFBBDBBDBEEEEEEEEBBBDBBDFF',
        'FFABBBDDBEEEEEEEEEEBBBDDBAFF',
        'FAFFBBDBEEEEEEEEEEEEBBBBFFAF',
        'AFFFDDBEEEEEEEEEEEEEEBBBFFFA',
        'FFF.BBBEEEEEEEEEEEEEEDBB.FFF',
        '.....BBEEEEEEEEEEEEEEBDD',
        '.....BBEEEEEEEEEEEEEEBB',
        '......BBEEEEEEEEEEEEBB',
        '.......BBEEEEEEEEEEBB',
        '........BBEEEEEEEEBB',
        '........FFBBBBBBBBFF',
        '.......FFFFAA..AAFFFF',
        '......FFFAAF....FAAFFF',
        '....FFFAAF........FAAFFF',
      ],
    },
  ],
};

/** フナズシマル：ニゴロンが しんか。ごはんの よろいに オレンジの たまごの むね当て、V の 背びれの かぶと、おけの ふたの たて（ミズ） */
const funazushiMaru: MonsterDesign = {
  size: 32,
  colors: {
    B: NQ.sand,
    D: NQ.tan,
    F: NQ.sky,
    A: NQ.azure,
    P: NQ.paper,
    c: NQ.cloud,
    O: NQ.orange,
    Y: NQ.apricot,
    K: NQ.brown,
    T: NQ.tan,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.sand]: NQ.tan, [NQ.sky]: NQ.azure, [NQ.paper]: NQ.cloud },
  layers: [
    {
      x: 1,
      y: 1,
      rows: [
        '......F..............F',
        '......FA............AF',
        '.......FA....FF....AF',
        '.......FAF.WFADD..FAF',
        '........FAWFADDDDFAF',
        '........ooDDDDDDDDDDoo',
        '.........BoDDDDDDDDoB',
        '.......BBWWDDDDDDDDWWBB',
        '.....DBBBWoBBBBBBBBoWBBBD',
        '....D.BBBWoBBBBBBBBoWBBB.D',
        '....DBBppBBBBBBBBBBBBppBBD',
        '....DBBBBBBBoBBBBoBBBBBBBD',
        '....BDBBBBBBBooooBBBBBBBDBKK',
        'FFFABBBBBBBBBBBBBBBBBBBBKKKKK',
        'FAAFBBBBBBBBBBBBBBBBBBBBKTKKTK',
        'FFFABBBBBBBBBBBBBBBBBBBKKTKKTK',
        'FAAFDDDDDDDDDDDDDDDDDDDKTTKKTK',
        'FFFFcPPPPcPPPPcPPPPcPPPKTTKKTK',
        '....PcPPPPcPPOOOOPPPcPPKKTKKTK',
        '.....PPPPcPPOWYYYOPcPPPPKTKKTK',
        '.....cPPPPcOOYYYYOOPcPPPKKKKK',
        '......PPPcPOOYYYYOOcPPPP..KK',
        '......PPPPcPOOOOOOPPcPPP',
        '.......PPcPPPOOOOPPcPPP',
        '.........PcPPPPcPPPPc',
        '.........FPPPPcPPPPcF',
        '.......FFFFFFAAAAFFFFFF',
        '......FFFFFAA....AAFFFFF',
        '.....FFFAAAF......FAAAFFF',
        '....FFAAFF..........FFAAFF',
      ],
    },
  ],
};

/** ツブリン：滋賀県の 県の 鳥 カイツブリ。こい茶の あたま・くり色の ほお・くちばしの 根もとの 黄色、水に うかぶ す（カゼ） */
const tsuburin: MonsterDesign = {
  size: 32,
  colors: {
    B: NQ.brown,
    D: NQ.bark,
    R: NQ.brick,
    S: NQ.sand,
    T: NQ.tan,
    Q: NQ.aqua,
    M: NQ.mint,
    W: NQ.white,
    N: NQ.night,
    Y: NQ.yellow,
    p: NQ.blush,
  },
  rim: { [NQ.brown]: NQ.bark, [NQ.sand]: NQ.tan, [NQ.mint]: NQ.aqua },
  layers: [
    {
      x: 1,
      y: 4,
      rows: [
        '............DDDDDD',
        '..........DDDDDDDDDD',
        '.........DDDDDDDDDDDD',
        '........DDDDDDDDDDDDDD',
        '........BDDDDDDDDDDDDB',
        '........BBWWDDDDDDWWBB',
        '.......BBBWoBBBBBBoWBBB',
        '.......BBBWoBBBBBBoWBBB',
        '........RRRRYNNNNYRRRR',
        '........RRRRBYNNYBRRRR',
        '........RRRRBRNNRBRRRR',
        '...MM..BRRRBBRRRRBBRRRB..MM',
        '..MMW.BBBBBBBBBBBBBBBBBB.WMM',
        '.MMWWBBBBBBBBBBBBBBBBBBBBWWMM',
        'MMWWBBBBBBBSSSSSSSSBBBBBBBWWMM',
        'MWWMBBBBBSSSSSSSSSSSSBBBBBMWWM',
        'WWM.BBBBSSSSSSSSSSSSSSBBBB.MWW',
        '....BBBBSSSSSSSSSSSSSSBBBB',
        '....BBBBSSSSSSSSSSSSSSBBBB',
        '....BBBBSSSSSSSSSSSSSSBBBB',
        '.....BBBSSSSSSSSSSSSSSBBB',
        '......BBBSSSSSSSSSSSSBBB',
        '....SSSBBBBSSSSSSSSBBBBSSS',
        '...TSSTSSTBBBBBBBBBBSTSSTSS',
        '...STSSTSSTSSTSSTSSTSSTSSTS',
        '....STSSTSSTSSTSSTSSTSSTSS',
        'QQQQQ...SSSSSSSSSSSSSS...QQQQQ',
      ],
    },
  ],
};

/** ナミノリツブリ：ツブリンが しんか。琵琶湖の 波がしらに のり、つばさを V の 字に ひろげる（カゼ） */
const naminoriTsuburi: MonsterDesign = {
  size: 32,
  colors: {
    B: NQ.brown,
    D: NQ.bark,
    R: NQ.brick,
    S: NQ.sand,
    K: NQ.sky,
    Q: NQ.aqua,
    M: NQ.mint,
    W: NQ.white,
    N: NQ.night,
    Y: NQ.yellow,
    p: NQ.blush,
  },
  rim: { [NQ.brown]: NQ.bark, [NQ.mint]: NQ.aqua },
  layers: [
    {
      x: 1,
      y: 1,
      rows: [
        '...........DD....DD',
        '............DD..DD',
        'M...........DDDDDD...........M',
        'MM........DDDDDDDDDD........MM',
        'WMM......DDDDDDDDDDDD......MMW',
        'WWMM....DDDDDDDDDDDDDD....MMWW',
        'MWWMM...BoooDDDDDDoooB...MMWWM',
        '.MWWMM..BBWWoDDDDoWWBB..MMWWM',
        '.WMWWMMBBBWoBBBBBBoWBBBMMWWMW',
        '..WMWWMBBBWoBBBBBBoWBBBMWWMW',
        '...WMWWMRRRRYNNNNYRRRRMWWMW',
        '....WMWWRRRRBYNNYBRRRRWWMW',
        '.....WBRRRRRBRNNRBRRRRRBW',
        '.....BBBRRRBBRRRRBBRRRBBB',
        '....BBBBBBBBBBBBBBBBBBBBBB',
        '....BBBBBBSSBBBBBBSSBBBBBB',
        'K...BBBBBSSSSSSSSSSSSBBBBB...W',
        '....BBBBSSSSSSSSSSSSSSBBBB',
        '...WBBBBSSSSSSSSSSSSSSBBBBK',
        '.K..BBBBSSSSSSSSSSSSSSBBBB..W',
        '....KBBBSSSSSSSSSSSSSSBBBW',
        '......BBBSSSSSSSSSSSSBBB',
        '..K....BBBSSSSSSSSSSBBB....W',
        '.........YYYYSSSSYYYY',
        '.......WWWWWBBBBBBWWWWW',
        '.....WWKKKKKKKKKKKKKKKKWW',
        '...WWKQQQKKKKKKKKKKKKQQQKWW',
        '..WQQQKKKKKKKKKKKKKKKKKKQQQW',
        '.WKKKKKKKKKQQQQQQQQKKKKKKKKKW',
        'WKKKKKKKKKKKKKKKKKKKKKKKKKKKKW',
      ],
    },
  ],
};

/** イブキッコ：伊吹山の 小さな 山の せい。すその ひろい 山の からだ、てっぺんに さく 花、岩の 足（モリ） */
const ibukikko: MonsterDesign = {
  size: 32,
  colors: {
    L: NQ.leaf,
    G: NQ.green,
    M: NQ.lime,
    S: NQ.sprout,
    W: NQ.white,
    Y: NQ.yellow,
    P: NQ.berry,
    R: NQ.silver,
    g: NQ.gray,
    p: NQ.blush,
  },
  rim: { [NQ.leaf]: NQ.green, [NQ.silver]: NQ.gray },
  layers: [
    {
      x: 3,
      y: 3,
      rows: [
        '............YY',
        '...........YYYY',
        '.........P..GG..P',
        '........PPP.GG.PPP',
        '.........G..GG..G',
        '......W..G..GG..G..W',
        '.....WWW.G.MGGM.G.WWW',
        '......G..GMMGGPMG..G',
        '......GMMGMWGGMMGYMG',
        '....L.LMMMMMMMMMMMML.L',
        '.....LSGLLMMMMMMLLGLL',
        '.....SGLLLLLLLLLLLLGL',
        '....SLGLLLLLLLLLLLLGLL',
        '...LLGLWWLLLLLLLLWWLGLL',
        '...LLGLWoLLLLLLLLoWLGLL',
        '..LLGLLWoLLLLLLLLoWLLGLL',
        '..LLGppLLLLLLLLLLLLppGLL',
        '..LGLLLLLLLoLLoLLLLLLLGL',
        '.LLGLLLLLLLLooLLLLLLLLGLL',
        '.LLLLLLLLLLLLLLLLLLLLLLLL',
        '.LGLLLLLLLLLLLLLLLLLLLLGL',
        '.LRRLLLLLLLLLLLLLLLLLLRRL',
        'LRRgLLLLLLLLLLLLLLLLLLgRRL',
        'LGLLLLLLLLLLLLLLLLLLLLLLGL',
        'LGLLLLLLLLLLLLLLLLLLLLLLGL',
        'LLLLLLLLLLLLLLLLLLLLLLLLLL',
        '....RRRRRR......RRRRRR',
        '.....RRRR........RRRR',
      ],
    },
  ],
};

/** イブキノオヤマ：イブキッコが しんか。雪の ぼうし・花の おび・雲の かたかけ、岩の うでと 足（モリ） */
const ibukiNoOyama: MonsterDesign = {
  size: 32,
  colors: {
    L: NQ.leaf,
    G: NQ.green,
    M: NQ.lime,
    W: NQ.white,
    C: NQ.cloud,
    Y: NQ.yellow,
    P: NQ.berry,
    R: NQ.silver,
    g: NQ.gray,
    p: NQ.blush,
  },
  rim: { [NQ.leaf]: NQ.green, [NQ.silver]: NQ.gray },
  layers: [
    {
      x: 1,
      y: 3,
      rows: [
        '..............WW',
        '.............WWWC',
        '............WWWWWC',
        '...........CWWWWWCW',
        '..........LWWWWWWWCL',
        '..........WWWWWWWWWC',
        '.........WWWWWWWWWWCW',
        '........LWWWWWWWWWWWCL',
        '........WLWLLWLLWLLWLW',
        '.......LLLLWLLWLLLWLLLL',
        '......MPMMMWMMMPMMMWMMMP',
        '......MMMYMMMPMMMYMMMPMM',
        '.....LLLooLLLLLLLLLLooLLL',
        '..WWWCLGLLoLLLLLLLLoLLGLCWWW',
        'CWWWWWWCLWWLLLLLLLLWWLCWWWWWWC',
        'CCWWWCCCLWoLLLLLLLLoWLCCCWWWCC',
        '.RCCCCLLLWoLLLLLLLLoWLLLCCCCR',
        'RRRLLGLppLLLLLLLLLLLLppLGLLRRR',
        'RRRLGLLLLLLLoLLLLoLLLLLLLGLRRR',
        '.RLLGLLLLLLLLooooLLLLLLLLGLLR',
        '..LGLLLLLLLLLLLLLLLLLLLLLLGL',
        '..LGLLLLLLLLLLLLLLLLLLLLLLGL',
        '..LLLLRRLLLLLLLLLLLLLLRRLLLL',
        '..LLLRRgLLLLLLLLLLLLLLgRRLLL',
        '.LLLLLLLLLLLLLLLLLLLLLLLLLLLL',
        '.LLLLLLLLLLLLLLLLLLLLLLLLLLLL',
        '.....RRRRRRRR....RRRRRRRR',
        '......RRRRRR......RRRRRR',
      ],
    },
  ],
};

const asanunon: MonsterDesign = {
  size: 32,
  colors: {
    W: NQ.paper,
    C: NQ.cloud,
    Y: NQ.gold,
    p: NQ.blush,
  },
  rim: { [NQ.paper]: NQ.cloud, [NQ.cloud]: NQ.silver },
  layers: [
    {
      rows: [
        '',
        '',
        '',
        '',
        '',
        '..............WWWWW',
        '...........WWWWWWWWWWW',
        '........WWWWWWWWWWWWWWWWW',
        '.....WWWCWWWCWWWCWWWCWWWCWWW',
        '......CCCCCCCCCCCCCCCCCCCCC',
        '......WWCWWWCWWWCWWWCWWWCWW',
        '......WWCWWWCWWWCWWWCWWWCWW',
        '....YYWWCWWWCWWWCWWWCWWWCWYY',
        '....YYCCCCCCCCCCCCCCCCCCCCYY',
        '....YYWWCWWWCWWWCWWWCWWWCWYY',
        '....YYWWCWWWCWWWCWWWCWWWCWYY',
        '....YYWWCWWWCWWWCWWWCWWWCWYY',
        '....YYCCCCCCoWCCCCWoCCCCCCYY',
        '....YYWWCWWWoWWWCWWoCWWWCWYY',
        '....YYWWCWWWWWWWCWWWCWWWCWYY',
        '....YYWWCWWWCWWWCWWWCWWWCWYY',
        '......CCCpCCCCCCCCCCCCpCCCC',
        '......WWCWWWCWWoooWWCWWWCWW',
        '......WWCWWWCWWWCWWWCWWWCWW',
        '......WWCWWWCWWWCWWWCWWWCWW',
        '......CCCCCCCCCCCCCCCCCCCCC',
        '......WWCWWWCWWWCWWWCWWWCWW',
        '......WWCWWWCWWWCWWWCWWWCWW',
        '...........WWWWWWWWWWW',
        '............CCCCCCCCC',
        '............CCCCCCCCC',
        '',
      ],
    },
  ],
};

const jofuHime: MonsterDesign = {
  size: 32,
  colors: {
    W: NQ.paper,
    C: NQ.cloud,
    Y: NQ.gold,
  },
  rim: { [NQ.paper]: NQ.cloud, [NQ.cloud]: NQ.silver },
  layers: [
    {
      rows: [
        '',
        '',
        '',
        '................Y',
        '............YYYYYYYYY',
        '...........YYYYYWYYYYY',
        '..........YYYWWWWWWWYYY',
        '.........YYYWWWWWWWWWYYY',
        '...Y.....YYWWWWWWWWWWWYY....Y',
        '..YYY....YYWWWWWWWWWWWYY...YYY',
        '...Y....YYWWWWWWWWWWWWWYY...Y',
        '.........WWWWWWWWWWWWWWW',
        '.......WWWWWWWWWWWWWWWWWWW',
        '....WWWWWWWWWWWWWWWWWWWWWWWWW',
        '.....CCCCCCCCCCCCCCCCCCCCCCC',
        '.....WWWWWWWWWWWWWWWWWWWWWWW',
        '.....WWWWWoooooWWWoooooWWWWW',
        '.....WWWWWWWWWWWWWWWWWWWWWWW',
        '.....CCCCCCooWCCCCCWooCCCCCC',
        '.....WWWWWWooWWWWWWWooWWWWWW',
        '.....WWWWWWooWWWWWWWooWWWWWW',
        '.....WWWWWWWWWWWWWWWWWWWWWWW',
        '.....CCCCCCCCCCCCCCCCCCCCCCC',
        '....YWWWWWWWWWoooooWWWWWWWWY',
        '...YYYWWWWWWWWWWWWWWWWWWWWYYY',
        '....YWWWWWWWWWWWWWWWWWWWWWWY',
        '.....CCCCCCCCCCCCCCCCCCCCCCC',
        '.....WWWWWWWWWWWWWWWWWWWWWWW',
        '.........WWWWWWWWWWWWWWW',
        '.............WWWWWWW',
        '...........CCCCCCCCCCC',
        '',
      ],
    },
  ],
};

const ponpokoOyabun: MonsterDesign = {
  size: 40,
  colors: {
    B: NQ.brown,
    S: NQ.beige,
    K: NQ.bark,
    T: NQ.tan,
    W: NQ.white,
    G: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
    V: NQ.vermilion,
  },
  rim: { [NQ.brown]: NQ.bark, [NQ.tan]: NQ.brown, [NQ.beige]: NQ.sand },
  rimDepth: 2,
  layers: [
    {
      rows: [
        '',
        '................G.G.G.G.G',
        '................GGGGGGGGG',
        '................GGGRRGGGG',
        '................GGGRRGGGG........B',
        '........B..TTTTTQQQQQQQQQTTTTT..B',
        '........TTTTTTTTTTTTTTTTTTTTTTTTT',
        '.......TTTTTTTTTTTTTTTTTTTTTTTTTTT',
        '......TTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
        '.......TTTTTTTTTTTTTTTTTTTTTTTTTTT',
        '........TTTTTTTTTTTTTTTTTTTTTTTTT',
        '...........TTTTTTTTTTTTTTTTTTT',
        '...........BoooooooBTBoooooooB',
        '...........BoooooooBBBoooooooB',
        '...........BBWWWWWBBBBBWWWWWBB',
        '..........BBKooWWWKBBBKWWWooKBB',
        '...........KKooWWWKKBKKWWWooKK',
        '...........BKooWWWKBBBKWWWooKB',
        '...........BBKKKKKBBoBBKKKKKBB',
        '............BBBKBBoooooBBKBBB',
        '..........BBBBBBBBBBoBBBBBBBBBB',
        '.........BBBBBBBBSSSSSSSBBBBBBBB',
        '........BBBBBBBBBSSSSSSSBBBBBBBBB',
        '.......BBBBBBBBBSSSSBSSSSBBBBBBBBB',
        '......BBBBBBBBSSSSSSSSSSSSSBBBBBBBB',
        '......BBBBBBBSSSSSSSSSSSSSSSBBBBBBB',
        '.....BBBBBBBBBSSSSSSSSSSSSSBBBBBBBBB',
        '......BBBBBBBSSSSSSSSSSSSSSSBBBBBBB',
        '.....BBBBBBBBSSSSSSSSSSSSSSSBBBBBBBB',
        '...V..BBBBBBSSSSSSSSSSSSSSSSSBBBBBB.V',
        '..VVV.BBBBSSSSSSSSSSSSSSSSSSSSSBBBBVVV',
        '...V..BBBBBSSSSSSSSSSSSSSSSSSSBBBBB.V',
        '.......BBBBSSSSSSSSSSSSSSSSSSSBBBB',
        '.......BBBBSSSSSSSSSSSSSSSSSSSBBBB',
        '........BBBBSSSSSSSSSSSSSSSSSBBBB',
        '.........BBBBSSSSSSSSSSSSSSSBBBB',
        '..........BBBBBBBBSSSSSBBBBBBBB',
        '...........BBBBBBBSSSSSBBBBBBB',
        '...........BBBBBBBBBSBBBBBBBBB',
        '',
      ],
    },
  ],
};

const ponpokoOyabunField: MonsterDesign = {
  size: 32,
  colors: {
    B: NQ.brown,
    S: NQ.beige,
    K: NQ.bark,
    T: NQ.tan,
    W: NQ.white,
    G: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
  },
  rim: { [NQ.brown]: NQ.bark, [NQ.tan]: NQ.brown },
  rimDepth: 1,
  layers: [
    {
      rows: [
        '',
        '..............G.G.G',
        '.............GGGGGGG',
        '.............GGRRGGG......B',
        '.......BTTTTTGGRRGGGTTTTTB',
        '......TTTTTTTQQQQQQQTTTTTTT',
        '.....TTTTTTTTTTTTTTTTTTTTTTT',
        '......TTTTTTTTTTTTTTTTTTTTT',
        '........TTTTTTTTTTTTTTTTT',
        '..........BBBBBBTBBBBBB',
        '.........BoooooBBBoooooB',
        '.........BWWWWWBBBWWWWWB',
        '........BBooWWWBBBWWWooBB',
        '.........KooWWWKBKWWWooK',
        '.........BooWWWBoBWWWooB',
        '.........BBBKBoooooBKBBB',
        '........BBBBBBBBoBBBBBBBB',
        '.......BBBBBBBSSSSSBBBBBBB',
        '......BBBBBBBBSSSSSBBBBBBBB',
        '.....BBBBBBBSSSSSSSSSBBBBBBB',
        '.....BBBBBBSSSSSSSSSSSBBBBBB',
        '....BBBBBBBSSSSSSSSSSSBBBBBBB',
        '....BBBBBBSSSSSSSSSSSSSBBBBBB',
        '.....BBBBBSSSSSSSSSSSSSBBBBB',
        '.....BBBSSSSSSSSSSSSSSSSSBBB',
        '.....BBBBSSSSSSSSSSSSSSSBBBB',
        '......BBBSSSSSSSSSSSSSSSBBB',
        '.......BBBSSSSSSSSSSSSSBBB',
        '........BBBSSSSSSSSSSSBBB',
        '.........BBBBBBSSSBBBBBB',
        '.........BBBBBBBSBBBBBBB',
        '',
      ],
    },
  ],
};

const dainamazu: MonsterDesign = {
  size: 48,
  colors: {
    K: NQ.slate,
    S: NQ.gray,
    W: NQ.white,
    P: NQ.blush,
    B: NQ.blue,
    A: NQ.azure,
    G: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
    Y: NQ.yellow,
  },
  rim: { [NQ.slate]: NQ.night, [NQ.blue]: NQ.navy, [NQ.gray]: NQ.slate },
  rimDepth: 2,
  layers: [
    {
      rows: [
        '',
        '',
        '....................G.G.G.G.G',
        '....................GGGGGGGGG',
        '....................GGGRRGGGG',
        '....................GGGRRGGGG',
        '....................QQQQQQQQQ',
        '',
        '',
        '........................K',
        '..................KKSKKKKKKKKKK',
        '................SSSSSSSSSKKKKKKKK',
        '.K............SSSSSSSSSSSSSKKKKKKKK',
        '.KKK.........SSSSSSSSSSSSSSSKKKKKKKK.........KK',
        '..KKK.......KooooooooooSSSooooooooooK.......KKK',
        '....KK.....KSooooooooooSSSooooooooooKK.....KK',
        '.....KKK...KKSSWWWWWWSSSSSSSWWWWWWKKKK...KKK',
        '......KKK.KKKSSoooWWWSSSSSSSWWWoooKKKKK.KKK',
        '........KKKKKKSoooWWWSSSSSSKWWWoooKKKKKKK',
        '.........KKKKKKoooWWWSSSSKKKWWWoooKKKKKK',
        '.........KKKKKKoooWWWKKKKKKKWWWoooKKKKKK',
        '..........KKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
        '..........KKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
        '..........KKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
        '...........KKKKKKKKKKKKKKKKKKKKKKKKKKK',
        '...........KoooooooooooooooooooooooooK',
        '..K.........ooPPPPPPPPPPPPPPPPPPPPPoo',
        '..KKKKKK...KooPPPPPPPPPPPPPPPPPPPPPooK...KKKKKK',
        '..KKKKKKKKKKoooooooooooooooooooooooooKKKKKKKKKK',
        '..KSSSSSKKKKK..KKKKKKKKKKKKKKKKKKK..KKKKKSSSSSK',
        '..KKKKKKSSSSK.KKKKKKKKKKKKKKKKKKKKK.KSSSSKKKKKK',
        '..KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
        '..KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
        '.KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
        '............KKKKKKKKKKKKKKKKKKKKKKKKK',
        '.............KKKKKKKKKKKKKKKKKKKKKKK',
        '.............KKKKKKKKKKKKKKKKKKKKKKK',
        '.............KKKKKKKKKKKKKKKKKKKKKKK',
        '........A.....AKKKKKAKKKKKAKKKKKAKK...A',
        '......AAAAA.AAAAAKAAAAAKAAAAAKAAAAA.AAAAA',
        '.....AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB',
        '......AAAAABAAAAABAAAAABAAAAABAAAAABAAAAABB',
        '......BBABBBBBABBBBBABBBBBABBBBBABBBBBABBBB',
        '......BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
        '......BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
        '',
        '',
        '',
      ],
    },
  ],
};

const dainamazuP0: MonsterDesign = {
  size: 48,
  colors: {
    K: NQ.slate,
    S: NQ.gray,
    W: NQ.white,
    P: NQ.blush,
    B: NQ.blue,
    A: NQ.azure,
    G: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
    Y: NQ.yellow,
  },
  rim: { [NQ.slate]: NQ.night, [NQ.blue]: NQ.navy, [NQ.gray]: NQ.slate },
  rimDepth: 2,
  layers: [
    {
      rows: [
        '',
        '',
        '....................G.G.G.G.G',
        '....................GGGGGGGGG',
        '....................GGGRRGGGG',
        '....................GGGRRGGGG',
        '....................QQQQQQQQQ',
        '',
        '',
        '........................K',
        '..................KKSKKKKKKKKKK',
        '.....W..........SSSSSSSSSKKKKKKKK.........W',
        '.K..WWW.......SSSSSSSSSSSSSKKKKKKKK......WWW',
        '.KKK.W.......SSSSSSSSSSSSSSSKKKKKKKK......W..KK',
        '..KKK.......KooooooooooSSSooooooooooK.......KKK',
        '....KK.....KSooooooooooSSSooooooooooKK.....KK',
        '.....KKK...KKSSWWWWWWSSSSSSSWWWWWWKKKK...KKK',
        '......KKK.KKKSSoYYYYWSSSSSSSWYYYYoKKKKK.KKK',
        '........KKKKKKSoYYYYWSSSSSSKWYYYYoKKKKKKK',
        '.........KKKKKKoYYYYWSSSSKKKWYYYYoKKKKKK',
        '.........KKKKKKoooWWWKKKKKKKWWWoooKKKKKK',
        '..........KKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
        '..........KKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
        '..........KKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
        '...........KKKKKKKKKKKKKKKKKKKKKKKKKKK',
        '...........KoooooooooooooooooooooooooK',
        '..K.........ooPPPPPPPPPPPPPPPPPPPPPoo',
        '..KKKKKK...KooPPPPPPPPPPPPPPPPPPPPPooK...KKKKKK',
        '..KKKKKKKKKKoooooooooooooooooooooooooKKKKKKKKKK',
        '..KSSSSSKKKKK..KKKKKKKKKKKKKKKKKKK..KKKKKSSSSSK',
        '..KKKKKKSSSSK.KKKKKKKKKKKKKKKKKKKKK.KSSSSKKKKKK',
        '..KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
        '..KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
        '.KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK',
        '....A.....A.KKKKAKKKKKAKKKKKAKKKKKAKK...A',
        '..AAAAA.AAAAAKAAAAAKAAAAAKAAAAAKAAAAA.AAAAA',
        '.AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBB',
        '..AAAAABAAAAABAAAAABAAAAABAAAAABAAAAABAAAAABBBB',
        '..BBABBBBBABBBBBABBBBBABBBBBABBBBBABBBBBABBBBBB',
        '..BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
        '..BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
        '......AAAAABAAAAABAAAAABAAAAABAAAAABAAAAABB',
        '......BBABBBBBABBBBBABBBBBABBBBBABBBBBABBBB',
        '......BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
        '......BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
        '',
        '',
        '',
      ],
    },
  ],
};

const iiNaosuke = lord(
  [
    '.................GGGG...',
    '..................GGGG..',
    '..................GGGG..',
    '...................GGG..',
    '...................GGG..',
    '...................GGGG.',
    '....................GGG.',
    '....................GGGN',
    ...HELMET,
    ...FACE,
  ],
  {
    N: NQ.brick,
    L: NQ.red,
    G: NQ.gold,
    Y: NQ.cream,
    R: NQ.red,
    K: NQ.red,
    S: NQ.vermilion,
    T: NQ.bark,
    H: NQ.slate,
    C: NQ.brick,
    M: NQ.hairBlack,
  },
  { [NQ.red]: NQ.brick, [NQ.vermilion]: NQ.red },
);

export const SHIGA: Readonly<Record<string, MonsterDesign>> = {
  'shiga-nigoron': nigoron,
  'shiga-funazushi-maru': funazushiMaru,
  'shiga-tsuburin': tsuburin,
  'shiga-naminori-tsuburi': naminoriTsuburi,
  'shiga-ibukikko': ibukikko,
  'shiga-ibuki-no-oyama': ibukiNoOyama,
  'shiga-asanunon': asanunon,
  'shiga-jofu-hime': jofuHime,
  'shiga-midboss-ponpoko-oyabun': ponpokoOyabun,
  'shiga-midboss-ponpoko-oyabun.field': ponpokoOyabunField,
  'shiga-boss-dainamazu': dainamazu,
  'shiga-boss-dainamazu.p0': dainamazuP0,
  'shiga-lastboss-ii-naosuke': iiNaosuke,
};
