/** 島根県の モンスター（手描き。docs/06 §4・§6.3〜6.5 の 規格） */
import { NQ } from '../palette';
import type { MonsterDesign } from './design';

/** シジミン：宍道湖の しじみ。つやつやの 黒っぽい 2 まいの からに 年輪の すじ。あいだから 顔が のぞく。まわりに あわ（ミズ） */
const shijimin: MonsterDesign = {
  size: 32,
  colors: { S: NQ.slate, g: NQ.gray, H: NQ.silver, W: NQ.white, p: NQ.blush, E: NQ.beige, K: NQ.sky },
  rim: { [NQ.slate]: NQ.night, [NQ.beige]: NQ.sand },
  rimDepth: 2,
  layers: [
    {
      rows: [
        '................................',
        '................................',
        '................................',
        '...............SS...............',
        '..............SSSS..............',
        '...........................K....',
        '..........SSSSSSSSSSSS....KWK...',
        '........SSSSSSSSSSSSSSSS...K....',
        '...K...SSSHHSSSSSSSSSSSSS.......',
        '.....SSSSHHSSSSSSSSSSSgSSSS.....',
        '....SSgSSggggggggggggggSSgSSK...',
        '....SSgSSSSSSSSSSSSSSSSSSgSS....',
        '...SSgSSSSSSSSSSSSSSSSSSSSgSS...',
        '...SSggggggggggggggggggggggSS...',
        '...SSSSSSSSSSSSSSSSSSSSSSSSSS...',
        '...HHHHHHHHHHHHHHHHHHHHHHHHHH...',
        '......EEEEEWWEEEEEEWWEEEEE......',
        '.....EEEEEEWoEEEEEEoWEEEEEE.....',
        '.....EEEppEWoEEEEEEoWEppEEE.....',
        '.....EEEEEEEEEoEEoEEEEEEEEE.....',
        '......EEEEEEEEEooEEEEEEEEE......',
        '...HHHHHHHHHHHHHHHHHHHHHHHHHH...',
        '...SSSSSSSSSSSSSSSSSSSSSSSSSS...',
        '...SSgSSSSSSSSSSSSSSSSSSSSgSS...',
        '....SSSSSSSSSSSSSSSSSSSSSSSS....',
        '....SSgSSggggggggggggggSSgSS....',
        '.....SSSSgSSSSSSSSSSSSgSSSS.....',
        '.......SSSSSSSSSSSSSSSSSS.......',
        '.........gSSSSSSSSSSSSg.........',
        '............gSSSSSSg............',
        '................................',
        '................................',
      ],
    },
  ],
};

/** ユウヒシジミ：シジミンの しんか。黒っぽい 大きな からに 宍道湖の 夕日の 光の わ、ちょうつがいに 金の 夕日。足もとに うずしお（ミズ） */
const yuhiShijimi: MonsterDesign = {
  size: 32,
  colors: {
    S: NQ.slate,
    Y: NQ.gold,
    C: NQ.cream,
    A: NQ.apricot,
    V: NQ.vermilion,
    W: NQ.white,
    p: NQ.blush,
    E: NQ.beige,
    K: NQ.sky,
  },
  rim: { [NQ.slate]: NQ.night, [NQ.beige]: NQ.sand },
  rimDepth: 2,
  layers: [
    {
      rows: [
        '................................',
        '..............YYYY..............',
        '................................',
        '............ASYYYYSA........K...',
        '...K.....SSSSYYYYYYSSSS....KWK..',
        '.......SASSSYYYYYYYYSSSAS...K...',
        '......SASCCSSSSSSSSSSSVSAS......',
        '.....SASCCSSSSSSSSSSSSVVSAS.....',
        '....SSASVVVVVVVVVVVVVVVVSASS....',
        '...SSASSVVVVVVVVVVVVVVVVSSASS...',
        '...SSASSSSSSSSSSSSSSSSSSSSASS...',
        '..SSSAAAAAAAAAAAAAAAAAAAAAASSS..',
        '..SSSAAAAAAAAAAAAAAAAAAAAAASSS..',
        '..SSSSSSSSSSSSSSSSSSSSSSSSSSSS..',
        '..CCCCCCCCCCCCCCCCCCCCCCCCCCCC..',
        '......EEEEooEEEEEEEEooEEEE......',
        '.....EEEEEEWWEEEEEEWWEEEEEE.....',
        '....EEEEEEEWoEEEEEEoWEEEEEEE....',
        '....EEEEppEWoEEEEEEoWEppEEEE....',
        '.....EEEEEEEEoEEEEoEEEEEEEE.....',
        '......EEEEEEEEooooEEEEEEEE......',
        '..KKKCCCCCCCCCCCCCCCCCCCCCCKKK..',
        '.KSSSSSSSSSSSSSSSSSSSSSSSSSSSSK.',
        '.KSKKSSSSSSSSSSSSSSSSSSSSSSKKSK.',
        '.K.SKSSAAAAAAAAAAAAAAAAAASSKS.K.',
        '..KKSSSAASSSSSSSSSSSSSSAASSSKK..',
        '.....SSSASSSSSSSSSSSSSSASSS.....',
        '..KKKKK.SASSSSSSSSSSSSAS.KKKKK..',
        '.......K...SASSSSSSAS...K.......',
        '................................',
        '................................',
        '................................',
      ],
    },
  ],
};

/** ワリゴン：出雲そばの 丸い 朱ぬりの 割子を 3 だん かさねた。いちばん上に そばと もみじおろし・ねぎ・のり、葉っぱと はし（モリ） */
const warigon: MonsterDesign = {
  size: 32,
  colors: {
    R: NQ.red,
    r: NQ.brick,
    V: NQ.vermilion,
    B: NQ.brown,
    T: NQ.tan,
    A: NQ.apricot,
    L: NQ.lime,
    G: NQ.green,
    N: NQ.night,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.red]: NQ.brick },
  layers: [
    {
      rows: [
        '................................',
        '................................',
        '.........................T......',
        '........................T..T....',
        '.....GG.................T.T.....',
        '....GLG................T.T......',
        '....GG................T.T.......',
        '......G..............T..T.......',
        '...........BAAABBBBTBT.T........',
        '.......TBLBBAWABBTLBTBTBB.......',
        '.....TBNNBTBBABTBBBLTBBBBTB.....',
        '.....BBBTBBBBTBBBBTBBBNNBBB.....',
        '......VBBBBTBBBBTBBBBTBBBV......',
        '....RRRRRRRWWBTBBBBWWRRRRRRR....',
        '...RRRRRRRRWoRRRRRRoWRRRRRRRR...',
        '...RRRRRppRWoRRRRRRoWRppRRRRR...',
        '....RRRRRRRRRRoRRoRRRRRRRRRR....',
        '......rrrrrrrrroorrrrrrrrr......',
        '......VVVVVVVVVVVVVVVVVVVV......',
        '....RRRRRRRRRRRRRRRRRRRRRRRR....',
        '...RRRRRRRRRRRRRRRRRRRRRRRRRR...',
        '....RRRRRRRRRRRRRRRRRRRRRRRR....',
        '......rrrrrrrrrrrrrrrrrrrr......',
        '......VVVVVVVVVVVVVVVVVVVV......',
        '....RRRRRRRRRRRRRRRRRRRRRRRR....',
        '...RRRRRRRRRRRRRRRRRRRRRRRRRR...',
        '....RRRRRRRRRRRRRRRRRRRRRRRR....',
        '......rrrrrrrrrrrrrrrrrrrr......',
        '..........rrr......rrr..........',
        '..........rrrr....rrrr..........',
        '................................',
        '................................',
      ],
    },
  ],
};

/** ワリゴタワー：ワリゴンの しんか。割子を 5 だんに つみあげ、やくみを 山もり。はしを かぶとの かざりの ように（モリ） */
const warigoTower: MonsterDesign = {
  size: 32,
  colors: {
    R: NQ.red,
    r: NQ.brick,
    V: NQ.vermilion,
    B: NQ.brown,
    T: NQ.tan,
    A: NQ.apricot,
    L: NQ.lime,
    G: NQ.green,
    N: NQ.night,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.red]: NQ.brick },
  layers: [
    {
      rows: [
        '................................',
        '...T........................T...',
        '...GG......................T....',
        '..GLGT....................T.....',
        '..GG..T......AAAA.........T.....',
        '......T.....AAWAAA.......T......',
        '.......T.LBLAAAAAATLBLL.T.......',
        '......TBTBBTBBBBTBBBBTBTBB......',
        '....TBNNBTBBBBTBBBBTBBBNNBBB....',
        '.....BBTBBBBTBBBBTBBBBTBBBB.....',
        '.....VVBBBooBBBTBBBBooBBBVV.....',
        '...RRRRRRRRWWRRRRRRWWRRRRRRRR...',
        '...RRRRRRRRWoRRRRRRoWRRRRRRRR...',
        '...RRRRRRRRWoRRRRRRoWRRRRRRRR...',
        '.....rrrpprrrrrrrrrrrrpprrr.....',
        '.....VVVVVVVVoVVVVoVVVVVVVV.....',
        '..RRRRRRRRRRRRooooRRRRRRRRRRRR..',
        '.RRRRRRRRRRRRRRRRRRRRRRRRRRRRRR.',
        '.RR..rrrrrrrrrrrrrrrrrrrrrr..RR.',
        '.....VVVVVVVVVVVVVVVVVVVVVV.....',
        '...RRRRRRRRRRRRRRRRRRRRRRRRRR...',
        '...RRRRRRRRRRRRRRRRRRRRRRRRRR...',
        '.....rrrrrrrrrrrrrrrrrrrrrr.....',
        '.....VVVVVVVVVVVVVVVVVVVVVV.....',
        '...RRRRRRRRRRRRRRRRRRRRRRRRRR...',
        '.....rrrrrrrrrrrrrrrrrrrrrr.....',
        '.....VVVVVVVVVVVVVVVVVVVVVV.....',
        '...RRRRRRRRRRRRRRRRRRRRRRRRRR...',
        '...RRRRRRRRRRRRRRRRRRRRRRRRRR...',
        '.....rrrrrrrrrrrrrrrrrrrrrr.....',
        '...........rrr....rrr...........',
        '................................',
      ],
    },
  ],
};

/** チドリン：まるい コチドリ。茶色の せなか、黒い むねの おび、黄色い 目の わ。松江城（千鳥城）の 屋根の ぼうし（カゼ） */
const chidorin: MonsterDesign = {
  size: 32,
  colors: {
    T: NQ.tan,
    W: NQ.white,
    N: NQ.night,
    Y: NQ.yellow,
    g: NQ.gray,
    S: NQ.slate,
    M: NQ.mint,
    p: NQ.blush,
  },
  rim: { [NQ.tan]: NQ.brown, [NQ.white]: NQ.cloud },
  layers: [
    {
      rows: [
        '................................',
        '................................',
        '...........Y........Y...........',
        '..............gggg..............',
        '...........g.gggggg.g...........',
        '............SSSSSSSS............',
        '...........NNNNNNNNNN...........',
        '...........gggggggggg...........',
        '........g.gggggggggggg.g........',
        '.........SSSSSSSSSSSSSS.........',
        '................................',
        '............TTTTTTTT............',
        '..........TTTTTTTTTTTT..........',
        '........TTTTTTTTTTTTTTTT........',
        '........TNNNNTTTTTTNNNNT........',
        '.......TTTYYYTTTTTTYYYTTT.......',
        '....WWWTTTYWWTTTTTTWWYTTTWWW....',
        '...WWMWTTTYWoTTTTTToWYTTTWMWW...',
        '..WWMMWWWTYWoTTNNTToWYTWWWMMWW..',
        '.WWMMWWWppTTTTTNNTTTTTppWWWMMWW.',
        '.WMM.WWWWWWWWWTTTTWWWWWWWWW.MMW.',
        '.MM...WWWWWWWWWWWWWWWWWWWW...MM.',
        '......WWWWWWWWWWWWWWWWWWWW......',
        '......WWWWNWWWWWWWWWWNWWWW......',
        '.......WWWWNNNNNNNNNNWWWW.......',
        '........WWWWWWWWWWWWWWWW........',
        '........WWWWWWWWWWWWWWWW........',
        '..........WWWWWWWWWWWW..........',
        '............WWWWWWWW............',
        '............Y......Y............',
        '............YY....YY............',
        '................................',
      ],
    },
  ],
};

/** テンシュチドリ：チドリンの しんか。3 だんの 天守の かぶと、黒い 板の むねあて、大きく ひろげた つばさ（カゼ） */
const tenshuChidori: MonsterDesign = {
  size: 32,
  colors: {
    T: NQ.tan,
    W: NQ.white,
    N: NQ.night,
    Y: NQ.yellow,
    g: NQ.gray,
    S: NQ.slate,
    M: NQ.mint,
    p: NQ.blush,
  },
  rim: { [NQ.tan]: NQ.brown, [NQ.white]: NQ.cloud },
  layers: [
    {
      rows: [
        '................................',
        '............Y.gggg.Y............',
        '.............SSSSSS.............',
        '.............NNNNNN.............',
        '.............gggggg.............',
        '..........g.gggggggg.g..........',
        '..W........SSSSSSSSSS........W..',
        '..WT......NNNNNNNNNNNN......TW..',
        '.WTTT.....gggggggggggg.....TTTW.',
        '.MTTTT.g.gggggggggggggg.g.TTTTM.',
        '..WTTTT.SSSSSSSSSSSSSSSS.TTTTW..',
        '..WTTTTT....TTTTTTTT....TTTTTW..',
        '..WTTTTTT.TTTTTTTTTTTT.TTTTTTW..',
        '.MTTTTTTTTTTTTTTTTTTTTTTTTTTTTM.',
        '..WTTTTTTooTTTTTTTTTTooTTTTTTW..',
        '..MTTTTTTNNoNTTTTTTNoNNTTTTTTM..',
        '...WTTTTTTYYYTTTTTTYYYTTTTTTW...',
        '...WTTTWWWYWWWWWWWWWWYWWWTTTW...',
        '..MTTTTWWWYWoWWWWWWoWYWWWTTTTM..',
        '...MTTTWWWYWoWWNNWWoWYWWWTTTM...',
        '....MMTWppWWWWWWWWWWWWppWTMM....',
        '......MWWWWWWWWWWWWWWWWWWM......',
        '.......WWWWWWWWWWWWWWWWWW.......',
        '.......WWWNNNNNNNNNNNNWWW.......',
        '........WWNYNNYNNYNNYNWW........',
        '........WWNNNNNNNNNNNNWW........',
        '.........WNNNNNNNNNNNNW.........',
        '..........WWWWWWWWWWWW..........',
        '...........WWWWWWWWWW...........',
        '............Y.WWWW.Y............',
        '............YY....YY............',
        '................................',
      ],
    },
  ],
};

/**
 * シロガネモグラ（中ボス）：石見銀山の 坑道（間歩）を ほりぬく 大モグラ。
 * 肩から せなかに かけて 大きな 銀の 結晶の とげ、長く 太い つめ、細く するどい 目と 太い まゆ、
 * 頭に 王冠（金＋赤の 宝石）。まわりに 銀の きらめき（ツチ）
 */
const shiroganeMogura: MonsterDesign = {
  size: 40,
  colors: {
    g: NQ.gray,
    H: NQ.silver,
    c: NQ.cloud,
    W: NQ.white,
    N: NQ.night,
    G: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
  },
  rim: { [NQ.gray]: NQ.slate, [NQ.silver]: NQ.gray, [NQ.cloud]: NQ.silver },
  rimDepth: 2,
  layers: [
    {
      mirror: true,
      rows: [
        '....................',
        '...............G.G.G',
        '..............GGGGGG',
        '..............GGGGRR',
        '..............QQQQQQ',
        '.............ggggggg',
        '............gggggggg',
        '...........ggggggggg',
        '.........ggggggggggg',
        '........Hggggggggggg',
        '.......HHggggggggggg',
        '.....H.HHHgggggggggg',
        '....HHHHHHgggNNNNNNN',
        '...HHHHHHHgggNWWoNNN',
        '..HHHHHHHHgggNWWoNNN',
        '..HHHHHHHHggggoooggg',
        '..gHHHHHHHgggggggggg',
        '...ggHHHHgggcccccocc',
        '...gggHHHggggccccccc',
        '...ggggHHgggggcooooo',
        '..gggggggggggggWWWWW',
        '..gggggggggggggggggg',
        '.ggggggggggggggggggg',
        '.Wgggggggggggggggggg',
        '.WWggggggggggggggggg',
        '.WWWgggggggggggggggg',
        '.WWWWggggggggggggggg',
        '.oWWWWgggggggggggggg',
        '..WWWWWggggggggggggg',
        '..oWWWWggggggggggggg',
        '...WWWWggggggggggggg',
        '....gggggggggggggggg',
        '.....ggggggggggggggg',
        '......gggggggggggggg',
        '.......ggggggggggggg',
        '.......WWWgggggggggg',
        '.......WWWWggggggggg',
        '........oWWggggggggg',
        '.........ggggggggggg',
        '....................',
      ],
    },
    // 銀の きらめき
    { x: 3, y: 3, rows: ['.W.', 'WWW', '.W.'] },
    { x: 1, y: 9, rows: ['.c.', 'ccc', '.c.'] },
    { x: 34, y: 5, rows: ['.W.', 'WWW', '.W.'] },
    { x: 35, y: 9, rows: ['.c.', 'ccc', '.c.'] },
  ],
};

/** シロガネモグラ（フィールドに 立つ 32×32。戦いの すがたと 同じ かまえ） */
const shiroganeMoguraField: MonsterDesign = {
  size: 32,
  colors: {
    g: NQ.gray,
    H: NQ.silver,
    c: NQ.cloud,
    W: NQ.white,
    N: NQ.night,
    G: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
  },
  rim: { [NQ.gray]: NQ.slate, [NQ.silver]: NQ.gray, [NQ.cloud]: NQ.silver },
  rimDepth: 2,
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '...........G.G.G',
        '..........GGGGGG',
        '..........GGGGRR',
        '..........QQQQQQ',
        '..........gggggg',
        '.........ggggggg',
        '........gggggggg',
        '.......Hgggggggg',
        '.....H.HHggggggg',
        '....HHHHHggggggg',
        '...HHHHHHgNNNNNN',
        '..HHHHHHHgNWWoNN',
        '..HHHHHHHgNWWoNN',
        '..gHHHHHHggooogg',
        '..ggHHHHggcccccc',
        '..gggHHgggccccoc',
        '..ggggggggcooooo',
        '..ggggggggggWWWW',
        '.ggggggggggggggg',
        '.Wgggggggggggggg',
        '.WWggggggggggggg',
        '.WWWgggggggggggg',
        '.oWWWggggggggggg',
        '..WWWWgggggggggg',
        '..oWWWgggggggggg',
        '...WWWgggggggggg',
        '....gggggggggggg',
        '.....ggggggggggg',
        '.....WWWgggggggg',
        '......oWWggggggg',
        '................',
      ],
    },
  ],
};

/** カグラオロチ（県ボス）：石見神楽の 大蛇。金の うろこの 3 つの 頭と 長い とぐろ、まん中の 頭に 王冠、口から 炎（ヒノ） */
const kaguraOrochi: MonsterDesign = {
  size: 48,
  colors: {
    G: NQ.green,
    L: NQ.leaf,
    Y: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
    C: NQ.cream,
    W: NQ.white,
    V: NQ.vermilion,
    A: NQ.apricot,
  },
  rim: { [NQ.green]: NQ.forest, [NQ.gold]: NQ.ochre, [NQ.red]: NQ.brick },
  rimDepth: 2,
  layers: [
    {
      rows: [
        '................................................',
        '....................Y..YY..Y....................',
        '....................YYYRRYYY....................',
        '....................QQQQQQQQ....................',
        '...............Y................Y...............',
        '...............YY..............YY...............',
        '................Y..............Y................',
        '....................GGGGGGGG....................',
        '.................YYYYGGGGGGYYYY.................',
        '.................GWWWGGGGGGWWWG.................',
        '................GGWWoGGGGGGoWWGG................',
        '...............LLGWooGGGGGGooWGG................',
        '...............LGGWooGGGGGGooWGG................',
        '................GGGGGGoGGoGGGGGG................',
        '................GGGGGGGGGGGGGGGG................',
        '....YYYGGGG.....GGGooooooooooGGG......GGGYYY....',
        '....GWWGGGGG.....GGoRRRRRRRRoGG.....GGGGGWWGG...',
        '...GGWoGGGGGG.....GoWRRRRRRWoG.....GGGGGGoWGGG..',
        '...GGWoGGGGGG......GooooooooG......GGGGGGoWGGG..',
        '.ooooGGGGGGGG.......GGGGGGGG.......GGGGGGGGoooo.',
        '.RRRoGGGGGGGG.......GGCCCCGG.......GGGGGGGGoRRR.',
        '.WRRoGGGGGGG........GGGYGGGY........GGGGGGGoRRW.',
        '.ooo.GGGGGG.........GGCCCCGG.........GGGGGG.ooo.',
        '.VACGGGGGGG.........GGGGGGGG.........GGGGGGGCAV.',
        '.VVAYGGGYGG.........YGCCCCGG.........GGGYGGGAVV.',
        '..V.GGGGGGG.........GGGGGGGG.........GGGGGGG.V..',
        '....GGGGGGG.........GGCCCCGG.........GGGGGGG....',
        '....GYGGGYG.........GYGGGYGG.........YGGGYGG....',
        '.....GGGGGG.........GGCCCCGG.........GGGGGG.....',
        '.....GGGGGGG........GGGGGGGG........GGGGGGG.....',
        '.....GYGGLLG........GGCCCCYG........GGYGGGY.....',
        '.....GGGGLGGG..GGGGGGGGGGGGGGGGGG..GGGGGGGG.....',
        '......GGGGGGGGGGGGGGGGCCCCGGGGGGGGGGGGGGGG......',
        '......GYGGGYGGGYGGGYGGGYGGGYGGGYGGGYGGGYGG......',
        '.......GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.......',
        '........GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG........',
        '........YGGGYGGGYGGGYGGGYGGGYGGGYGGGYGGG........',
        '.....GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.....',
        '....GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG....',
        '...GGYGGGYGGGYGGGYGGGYGGGYGGGYGGGYGGGYGGGYGGG...',
        '..GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG..',
        '...GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG...',
        '...GGGYGGGYGGGYGGGYGGGYGGGYGGGYGGGYGGGYGGGYGG...',
        '.....GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.....',
        '.......GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.......',
        '..........GYGGGYGGGYGGGYGGGYGGGYGGGYGG..........',
        '................GGGGGGGGGGGGGGGG................',
        '................................................',
      ],
    },
  ],
};

/** 後半の 炎（からだの うしろに 重ねる） */
const OROCHI_FIRE = [
  '................................................',
  '................................................',
  '................................................',
  '..........C..........................C..........',
  '.........ACA........................ACA.........',
  '.........VAV...C................C...VAV.........',
  '..C......VVV..AC................CA..VVV.....C...',
  '.ACA.........VAA................AAV........ACA..',
  '.VAV.........VVA................AVV........VAV..',
  '.VVV..........VV................VV.........VVV..',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '....C......................................C....',
  '...AC......................................CA...',
  '...VA......................................AV...',
  '...VV......................................VV...',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
];

/** カグラオロチ 後半：からだが 明るく もえ、頭の うしろに 炎、目が 光る（2 回 こうげき） */
const kaguraOrochiP0: MonsterDesign = {
  ...kaguraOrochi,
  colors: { ...kaguraOrochi.colors, W: NQ.cream, L: NQ.lime, G: NQ.leaf },
  rim: { [NQ.leaf]: NQ.green, [NQ.gold]: NQ.ochre, [NQ.red]: NQ.brick },
  layers: [
    { rows: OROCHI_FIRE },
    ...kaguraOrochi.layers,
    { x: 1, y: 22, rows: ['CVAC', 'AVVA', 'VAV.', '.V..'] },
    { x: 43, y: 22, rows: ['CAVC', 'AVVA', '.VAV', '..V.'] },
  ],
};

/** 小泉八雲：よこわけの かみと 口ひげ、こんの はおり（金の 家紋）、赤い ちょうちんと ひらいた 本。まわりに ふわふわの ひとだま（ヤミ） */
const koizumiYakumo: MonsterDesign = {
  size: 48,
  colors: {
    F: NQ.skinLight,
    f: NQ.skinMid,
    H: NQ.hairBrown,
    N: NQ.navy,
    D: NQ.denim,
    W: NQ.white,
    c: NQ.cloud,
    G: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
    r: NQ.brick,
    A: NQ.apricot,
    L: NQ.lavender,
    V: NQ.violet,
  },
  rim: { [NQ.skinLight]: NQ.skinMid, [NQ.white]: NQ.cloud, [NQ.red]: NQ.brick },
  rimDepth: 2,
  layers: [
    {
      rows: [
        '................................................',
        '................................................',
        '................................................',
        '................................................',
        '................................................',
        '....L...............FHHHHHHH....................',
        '...LL.............HHFHHHHHHHHH..................',
        '..LWL............HHHFHHHHHHHHHH.............L...',
        '..LVL...........HHHHHHHHHHHHHHHH...........LL...',
        '...L............HHHHHHHFFFFFFFHH..........LWL...',
        '................HHHFFFFFFFFFFFHH..........LVL...',
        '................HHHHHHFFFFHHHFHH...........L....',
        '................HHFFFFFFFFFFFFHH................',
        '................HHFFWoFFFFoWFFHH................',
        '.....L..........HHFFooFffFooFFHH................',
        '....LL...........FFFFFFffFFFFFF.................',
        '...LWL............FFFFFFFFFFFF..................',
        '...LVL............FHHHHHHHHHHF................L.',
        '....L.............HHFFFFFFFFHH...............LL.',
        '...................FFFFFFFFFF...............LWL.',
        '.....................FFFFFF.................LVL.',
        '........FF.NNNNNNNNWWDDDDDWWNNNNNNNN.........L..',
        '.........QNNNNNNNNNNWWDDDWWNNNNNNNNNN...........',
        '........NQNNNNNNNNNNWWDDDWWNNNNNNNNNNNN.........',
        '.....NNNNQNNNNGNNNNNDWWDWWDNNNNNNGNNNNNNNN......',
        '....NNGGGGGGGGGGNNNNDDWDWDDNNNNNGGGNNNNNNNN.....',
        '....NNNRRRRRNNGNNNNNDDWWWDDNNNNNNGNNNNNNNNN.....',
        '....NrrrrrrrrrNNNNNDDDDWDDDDNNNNNNNNNNNNNNN.....',
        '....NNRAARRRRNNNNNNDDWWWDWWDNNNNNNNNNNNNNNN.....',
        '....NRRARRRRRRNNNNNDDDDWWDDDNNNNNWWWWWNWWWWW....',
        '....NrrrrrrrrrNNNNNDDDDDDDDDNNNNNWWWWWcWWWWW....',
        '....NRRRRRRRRRNNNNNDDDDDDDDDNNNNNWWWWWcWWWWW....',
        '....NRRRRRRRRRNNNNNDDDDDDDDDNNNNNWWWWWcWWWWW....',
        '...NNrrrrrrrrrNNNNNDDDDDDDDDNNNNNWWWWWcWWWWW....',
        '...NNNRRRRRRRNNNNNNDDDDDDDDDNNNNNccccccccccc....',
        '...NNNNRRRRRNNNNNNNDDDDDDDDDNNNNNNNFFNcNFFNN....',
        '...NNNGGGGGGGNNNNNNDDDDDDDDDNNNNNNNNNNNNNNNN....',
        '...NNNNNNNNNNNNNNNNDDDDDDDDDNNNNNNNNNNNNNNNN....',
        '...NNNNNNNNNNNNNNNNDDDDDDDDDNNNNNNNNNNNNNNNN....',
        '...NNNNNNNNNNNNNNNNDDDDDDDDDNNNNNNNNNNNNNNNN....',
        '...NNNNNNNNNNNNNNNDDDDDDDDDDDNNNNNNNNNNNNNNN....',
        '......NNNNNNNNNNNNDDDDDDDDDDDNNNNNNNNNNNN.......',
        '......NNNNNNNNNNNNDDDDDDDDDDDNNNNNNNNNNNN.......',
        '......NNNNNNNNNNNNDDDDDDDDDDDNNNNNNNNNNNN.......',
        '......NNNNNNNNNNNNDDDDDDDDDDDNNNNNNNNNNNN.......',
        '.....NNNNNNNNNNNNNDDDDDDDDDDDNNNNNNNNNNNNN......',
        '.....NNNNNNNNNNNNNDDDDDDDDDDDNNNNNNNNNNNNN......',
        '................................................',
      ],
    },
  ],
};

const rosokun: MonsterDesign = {
  size: 32,
  colors: { N: NQ.slate, K: NQ.gray, V: NQ.vermilion, A: NQ.apricot, Y: NQ.yellow, W: NQ.white, p: NQ.blush },
  rim: { [NQ.slate]: NQ.night, [NQ.vermilion]: NQ.brick },
  layers: [
    {
      mirror: true,
      y: 1,
      rows: [
        '.......Y........',
        '......AYA.......',
        '.....AVVVA......',
        '......VVV.......',
        '.......V........',
        '......NNN.......',
        '.....NNNNN......',
        '....NNNNNNN.....',
        '...NNNNNNNNN....',
        '..NNNNNWWNNNN...',
        '..NNNNNWoNNNN...',
        '..NNNNNNNNNNN...',
        '..NNNNpNNNNNN...',
        '..NNNNNNNNNNN...',
        '...NNNNNNNNN....',
        '...NNNNNNNNN....',
        '....NNNNNNN.....',
        '....NNNNNNN.....',
        '.....NNNNN......',
        '.....NNNNN......',
        '......NNN.......',
        '......NNN.......',
        '.....KKKKK......',
        '....KK...KK.....',
        '...KK.....KK....',
        '..KK.......KK...',
        '..KK.......KK...',
        '..KK.......KK...',
        '..KK.......KK...',
      ],
    },
  ],
};
const oohiRosoku: MonsterDesign = {
  ...rosokun,
  layers: [
    ...rosokun.layers,
    {
      mirror: true,
      y: 1,
      rows: ['.....YYYYY......', '....YAVVVAY.....', '...YAVVVVVAY....', '....AVVVVVA.....'],
    },
    { mirror: true, y: 14, rows: ['..NNNNNNNNNNN...', '.NNNKKKKKKKNNN..', '..NNNNNNNNNNN...'] },
  ],
};

export const SHIMANE: Readonly<Record<string, MonsterDesign>> = {
  'shimane-shijimin': shijimin,
  'shimane-yuhi-shijimi': yuhiShijimi,
  'shimane-warigon': warigon,
  'shimane-warigo-tower': warigoTower,
  'shimane-chidorin': chidorin,
  'shimane-tenshu-chidori': tenshuChidori,
  'shimane-rosokun': rosokun,
  'shimane-oohi-rosoku': oohiRosoku,
  'shimane-midboss-shirogane-mogura': shiroganeMogura,
  'shimane-midboss-shirogane-mogura.field': shiroganeMoguraField,
  'shimane-boss-kagura-orochi': kaguraOrochi,
  'shimane-boss-kagura-orochi.p0': kaguraOrochiP0,
  'shimane-lastboss-koizumi-yakumo': koizumiYakumo,
};
