/** 静岡県の モンスター（手描き。docs/06 §4・§6.3〜6.5 の 規格）。下書きは 図形で かいて 1 ドットずつ 手で なおした */
import { NQ } from '../palette';
import type { MonsterDesign } from './design';

/** チャツミン：お茶の 若葉の 子。頭に「一芯二葉（めと 2 まいの 葉）」、手に 茶つみの かご（モリ） */
const chatsumin: MonsterDesign = {
  size: 32,
  colors: {
    L: NQ.leaf,
    G: NQ.green,
    M: NQ.lime,
    s: NQ.sprout,
    S: NQ.sand,
    T: NQ.tan,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.leaf]: NQ.green, [NQ.sand]: NQ.tan },
  layers: [
    {
      rows: [
        '................................',
        '................................',
        '...............MM...............',
        '...............MM...............',
        '....LLLLL......MM......LLLLL....',
        '....LLMLLLL....MM....LLLLMLL....',
        '.....LLMMLLL...MM...LLLMMLL.....',
        '......LLLMMLL..MM..LLMMLLL......',
        '........LLLMML.GG.LMMLLL........',
        '...........LLM.GG.MLL...........',
        '............LLLGGLLL............',
        '.........LLLLLLLLLLLLLL.........',
        '........LLLLLLLLLLLLLLLL........',
        '......LMLLLLLLLLLLLLLLLLLL......',
        '.....LMLLLLLLLLLLLLLLLLLLLL.....',
        '.....LMLLLWWLLLLLLLLWWLLLLL.....',
        '....LLLLLLWoLLLLLLLLoWLLLLLL....',
        '....LLLLLLWoLLLLLLLLoWLLLLLL....',
        '....LLLLpLLLLLLLLLLLLLLpLLLL....',
        '...LLLLLLLLLLLossoLLLLLLLMLLL...',
        '....LLLLLLLssssoossssLLSSSSSSS..',
        '....LLLLLLssssssssssssLSTSTSTS..',
        '....LLLLLssssssssssssssSSSSSSS..',
        '.....LLLLssssssssssssssSTSTSTS..',
        '.....LLLLssssssssssssssLSSSSS...',
        '......LLLssssssssssssssLLL......',
        '........LLssssssssssssLL........',
        '.........LLLssssssssLLL.........',
        '..........GGGLLLLLLGGG..........',
        '..........GGG......GGG..........',
        '................................',
        '................................',
      ],
    },
  ],
};

/** チャバシラ（チャツミンの しんか）：大きな 一芯二葉の かぶと、葉の マント、たつ 茶柱の つえ（モリ） */
const chabashira: MonsterDesign = {
  size: 32,
  colors: { L: NQ.leaf, G: NQ.green, M: NQ.lime, s: NQ.sprout, W: NQ.white, p: NQ.blush },
  rim: { [NQ.leaf]: NQ.green, [NQ.lime]: NQ.leaf },
  layers: [
    {
      rows: [
        '................................',
        '...............MM...........LL..',
        '...............MM.........LLLL..',
        '..LLLLL........MM........LLLML..',
        '..LLLMLLL......MM......LLLLLLL..',
        '...LLLMMLL.....MM.....LLMMLLMG..',
        '...LLLLLMML....MM....LMMLLLLMG..',
        '....LLLLLLML...MM...LMLLLLLLMG..',
        '......LLLLLMM..GG..MMLLLLL..MG..',
        '........LLLLLM.GG.MLLLLL....MG..',
        '...........LLLLGGLLLL.......MG..',
        '.........LLLLLLGGLLLLLL.....MG..',
        '........LLLLLLLLLLLLLLLL....MG..',
        '.......MooLLLLLLLLLLLLooL...MG..',
        '......MLLLooLLLLLLLLooLLLL..MG..',
        '.....LMLLLWWLLLLLLLLWWLLLLL.MG..',
        '.....LLLLLWoLLLLLLLLoWLLLLL.MG..',
        '....GLLLLLWoLLLLLLLLoWLLLLLGMG..',
        '...GGLLLpLLLLLLLLLLLLLLpLLLGMG..',
        '...GLLLLLLLLsossssosLLLLLLLLMG..',
        '...GGLLLLLLsssoooosssLLLLLLLMG..',
        '..GGGLLLLLssssssssssssLLLLLGMG..',
        '..GGGLLLLssssssssssssssLLLLGMG..',
        '..GGGLLLLssssssssssssssLLLLGMG..',
        '..GGGGLLLssssssssssssssLLLGGMG..',
        '...GGGGLLssssssssssssssLLGGGMG..',
        '....GGG.LLssssssssssssLL.GGGMG..',
        '.....G...LLssssssssssLL...G.MG..',
        '..........GGGLssssLGGG......MG..',
        '..........GGG......GGG......MG..',
        '................................',
        '................................',
      ],
    },
  ],
};

/** ウナニョロ：浜名湖の うなぎ。S の 字に 立ち、せなかに つづく せびれ、耳のような むなびれ（ミズ） */
const unanyoro: MonsterDesign = {
  size: 32,
  colors: { D: NQ.denim, c: NQ.cloud, T: NQ.teal, A: NQ.azure, W: NQ.white, p: NQ.blush },
  rim: { [NQ.denim]: NQ.navy, [NQ.cloud]: NQ.silver, [NQ.teal]: NQ.night },
  layers: [
    {
      rows: [
        '................................',
        '.............TTTTTT.............',
        '.............TTTTTT.............',
        '.............TTTTTT.............',
        '............DDDDDDDD............',
        '..........DAADDDDDDDDD..........',
        '.........DADDDDDDDDDDDD.........',
        '.........DDDDDDDDDDDDDD.........',
        '....TTT..DDWWDDDDDDWWDD..TTT....',
        '....TTTTDDDWoDDDDDDoWDDDTTTT....',
        '....TTTT.DDWoDDDDDDoWDD.TTTT....',
        '....TTTT.DpDDccccccDDpD.TTTT....',
        '....TTT..DDDoccccccoDDD..TTT....',
        '..........DccooooooccDD.........',
        '............ccccccccDDD.........',
        '...........TTTccccDDDDD.........',
        '.........TTTTDDDDDDDDDD.........',
        '........TTDDDDDDDDcccDD.........',
        '.......TTDDDDDDDcDcccD..........',
        '.......TDDDDDcDcccDcD...........',
        '......TTDDDDcccDcDDD............',
        '......TDDDDDcccDD...............',
        '......TDDDDccDD.................',
        '.......TDDDccDDDTTTTTDD.........',
        '.......TDDDDccDDDDDDDDDDDTT.....',
        '.......TDDDcccDDDDDDDDDDTTT.....',
        '.........DDDcDDccDDcDDDDTT......',
        '..........DDDDcccDcccDDDD.......',
        '............DDDDDDDccDDDD.......',
        '.............DDDDDDDDDDD........',
        '................................',
        '................................',
      ],
    },
  ],
};

/** ウナギノボリ（ウナニョロの しんか）：水しぶきから 竜のように のぼる うなぎ。とげの せびれ、ひげ、大きな むなびれ（ミズ） */
const unagiNobori: MonsterDesign = {
  size: 32,
  colors: { D: NQ.denim, c: NQ.cloud, T: NQ.teal, A: NQ.azure, S: NQ.sky, W: NQ.white, p: NQ.blush },
  rim: { [NQ.denim]: NQ.navy, [NQ.cloud]: NQ.silver, [NQ.teal]: NQ.night, [NQ.sky]: NQ.azure },
  layers: [
    {
      rows: [
        '................................',
        '.......T....T..TT..T....T.......',
        '........TT..TTTTTTTT..TT........',
        '.........TTTDDDDDDDDTTT.........',
        '..........AADDDDDDDDDT..........',
        '...T......ooDDDDDDDDoo......T...',
        '..TTTT...DDWoDDDDDDoWDD...TTTT..',
        '..TTTTTT.DDWoDDDDDDoWDD.TTTTTT..',
        '..TTTTTT.DDWoDDDDDDoWDD.TTTTTT..',
        '..TTTTTT.DpDDDDccDDDDpD.TTTTTT..',
        '..TTTTTTWWDDoccccccoDDWWTTTTTT..',
        '...TTWWW..WDcoooooocDWD.WWWTT...',
        '...WW..WWW..ccccccccDDWWW..WW...',
        '......W........DDDDDDDD..W......',
        '....WW......DDDDDDDDDDD...WW....',
        '...........DDDDDDDDcccD.........',
        '.........DDDDDDDDcccccD.........',
        '........DDDDDDccDccDDD..........',
        '........DDDDDDccDccDD...........',
        '........DDDDccccDDD.............',
        '.......DDDDDccDDDD..............',
        '.......DDDDcccD.................',
        '.......DDDDcccDD................',
        '........DDDDcccDD...............',
        '........DDDDcccDDDD.............',
        '.....W...DDDDDcccDW.......W.....',
        '....W.WSSSDDDDcWcDDDSSSSSW.W....',
        '...SSSSSSSSDDDDDDDDDSSSSSSSSS...',
        '..AAAAAAAAAADDDDDDDAAAAAAAAAAA..',
        '...AAAAAAAAAADDDDDDAAAAAAAAAA...',
        '.....AAAAAAAAAADDAAAAAAAAAA.....',
        '................................',
      ],
    },
  ],
};

/** ソラダコ：浜松まつりの 四角い たこ。上に うなり（ゆみ）、赤い ふち、よこに 風の つばさ、下に 糸（カゼ） */
const soradako: MonsterDesign = {
  size: 32,
  colors: {
    R: NQ.red,
    P: NQ.paper,
    N: NQ.navy,
    B: NQ.brown,
    M: NQ.mint,
    A: NQ.aqua,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.red]: NQ.brick, [NQ.mint]: NQ.aqua },
  layers: [
    {
      rows: [
        '................................',
        '................................',
        '.........BBBBBBBBBBBBBB.........',
        '........B..............B........',
        '.......RRRRRRRRRRRRRRRRRR.......',
        '......BRRRRRRRRRRRRRRRRRRB......',
        '.......RRNNNNNPPPPNNNNNRR.......',
        '.......RRNNNNPPPPPPNNNNRR.......',
        '......MRRNNNPPPPPPPPNNNRRM......',
        '...MMMMRRNNPPPPPPPPPPNNRRMMMM...',
        '..MMMMMRRNPPPPPPPPPPPPNRRMMMMM..',
        '..MMMMMRRPPWWPPPPPPWWPPRRMMMMM..',
        '.MAAMMMRRPPWoPPPPPPoWPPRRMMMAAM.',
        '.MAMMMMRRPPWoPPPPPPoWPPRRMMMMAM.',
        '.MMMM..RRPpPPPPPPPPPPpPRR..MMMM.',
        '.......RRPPPPPoPPoPPPPPRR.......',
        '.......RRPPPPPPooPPPPPPRR.......',
        '.......RRPPPPPPPPPPPPPPRR.......',
        '...MM..RRPPPPPPPPPPPPPPRR.......',
        '.......RRPPPPPPPPPPPPPPRR.......',
        '.MM....RRRRRRRRRRRRRRRRRR.......',
        '.......RRRRRRRRRRRRRRRRRR.......',
        '.........RW.....B....WR.........',
        '.........RW......B...WR.........',
        '........RW.......B....WR........',
        '........RW........B...WR........',
        '........RW........B...WR........',
        '........RW.........B..WR........',
        '.......RW..........B...WR.......',
        '.......RW...........B..WR.......',
        '................................',
        '................................',
      ],
    },
  ],
};

/** カゼキリダコ（ソラダコの しんか）：ななめに 風を きる ひし形の 大だこ。金の おび、きりっと まゆ、大きな 風の つばさ、3 本の 尾（カゼ） */
const kazekiriDako: MonsterDesign = {
  size: 32,
  colors: {
    R: NQ.red,
    P: NQ.paper,
    N: NQ.navy,
    B: NQ.brown,
    M: NQ.mint,
    A: NQ.aqua,
    W: NQ.white,
    G: NQ.gold,
    p: NQ.blush,
  },
  rim: { [NQ.red]: NQ.brick, [NQ.mint]: NQ.aqua, [NQ.gold]: NQ.ochre },
  layers: [
    {
      rows: [
        '................................',
        '...............RR...............',
        '..............RRRR..............',
        '.............RRRRRR.............',
        '............RRRNNRRR............',
        '...........RRRNNNNRRR...........',
        '..........RRRNNNNNNRRR..........',
        '.M.......RRNNNNNNNNNNRR.......M.',
        '.MMMM...RRPGGGGGGGGGGPRR...MMMM.',
        '.MWWMMRRRPPPPPPPPPPPPPPRRRMMWWM.',
        '.MWWWRRRPoooPPPPPPPPoooPRRRWWWM.',
        '.MWWRRRPPPPWoPPPPPPoWPPPPRRRWWM.',
        '.MMRRRPPPPPWoPPPPPPoWPPPPPRRRMM.',
        '.MMRRRPPPPPWoPPPPPPoWPPPPPRRRMM.',
        '.MMMRRRPPPPPPPPPPPPPPPPPPRRRMMM.',
        '..MMMRRRPPpPPPPPPPPPPpPPRRRMMM..',
        '..MMMMRRRPPPPoPPPPoPPPPRRRMMMM..',
        '........RRPPPPooooPPPPRR........',
        '.........RRPPPPPPPPPPRR.........',
        '...MM.....RRRPPPPPPRRR..........',
        '...........RRRPPPBRRR.......MM..',
        '.MM.........RRRPPRBR............',
        '.............RRRRRB.............',
        '..............RRRR.B............',
        '...............RR...B...........',
        '..............RRRR..B...........',
        '.............RWRRWR..B..........',
        '............RW.RR.WR..B.........',
        '............RW.RR.WR...B........',
        '...........RW..RR..WR..B........',
        '..........RW...RR...WR..B.......',
        '................................',
      ],
    },
  ],
};

const wasabikko: MonsterDesign = {
  size: 32,
  colors: {
    G: NQ.leaf,
    L: NQ.lime,
    F: NQ.green,
    W: NQ.white,
    p: NQ.blush,
  },
  rim: { [NQ.leaf]: NQ.green, [NQ.lime]: NQ.leaf },
  layers: [
    {
      rows: [
        '',
        '',
        '',
        '................G',
        '................G......L',
        '................GG',
        '................GG',
        '...........L....GGG..L',
        '............L...GGGGL',
        '............LL..GGGLL',
        '.............LL.GGLL',
        '.............LLL.LLL',
        '',
        '',
        '................FFFFFFFF',
        '.........FFFFFFFGGGG',
        '............LLLLLGGGG',
        '...........GLLLLFFFFFFFF',
        '.........FFFFFFFLLGGGGG',
        '..........GLWWLLLLWWGGG',
        '..........GLoWLLFFWoFFFF',
        '.........FFFoWFFLLWoGGG',
        '.........GGLLLLLLLGGGGGG',
        '.........pGLLLoLFFoFFFpF',
        '.........FFFFFFoooGGGGG',
        '..........GGLLLLLGGGGGG',
        '..........GGLLLLFFFFFFFF',
        '.........FFFFFFFGGGGGG',
        '............GGGGGGGGG',
        '.............FFFFFFF',
        '.............FFFFFFF',
        '',
      ],
    },
  ],
};

const tsuunWasabi: MonsterDesign = {
  size: 32,
  colors: {
    G: NQ.leaf,
    L: NQ.lime,
    F: NQ.green,
    W: NQ.white,
    M: NQ.mint,
  },
  rim: { [NQ.leaf]: NQ.green, [NQ.lime]: NQ.leaf },
  layers: [
    {
      rows: [
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '......G...L...G...L...G',
        '......G...L...G...L...G',
        '....M..G...L...G...L...G...M',
        '...MMM.GG..LL..GG..LL..GG.MMM',
        '....M..GG..LL..GG..LL..GG..M',
        '........GG..LL..GG..LL..GG',
        '........GGG.LLL.GGG.LLL.GGG',
        '........GG..LL..GG..LL..GG',
        '',
        '................G',
        '............GLGGFFFFFFFFFF',
        '.......FFFFFFFFFLGGGGGG',
        '.........LoooooLLoooooGG',
        '........GLLWWWLLFFWWWFFFFF',
        '...M...FFFFooWFFLLWooGGGG...M',
        '..MMM...GLLooWLLLLWooGGGG..MMM',
        '...M...GGLLooWLLFFWooFFFFF..M',
        '.......FFFFFFFFFLGGGGGGGG',
        '........GGGGGoGGGGGoGGGGG',
        '........GGGGGGoooooFFFFFFF',
        '.......FFFFFFFFFGGGGGGGG',
        '..........GGGGGGGGGGGGG',
        '............FFFFFFFFF',
        '............FFFFFFFFF',
        '',
      ],
    },
  ],
};

const yoganGani: MonsterDesign = {
  size: 40,
  colors: {
    K: NQ.slate,
    N: NQ.night,
    V: NQ.vermilion,
    W: NQ.white,
    G: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
    B: NQ.blue,
    S: NQ.sky,
  },
  rim: { [NQ.slate]: NQ.night, [NQ.blue]: NQ.navy },
  rimDepth: 2,
  layers: [
    {
      rows: [
        '',
        '',
        '................G.G.G.G.G',
        '................GGGGGGGGG',
        '................GGGRRGGGG',
        '................GGGRRGGGG',
        '.KKK............QQQQQQQQQ............KK',
        '.KKKKK.............................KKKK',
        '.KKKKKK...........................KKKKK',
        '.NNNNKK...........................KNNNN',
        '.NNNNKK...........................KNNNN',
        '.NNNNKK...........................KNNNN',
        '....KKK...........................KKK',
        '.KKKK...............................KKK',
        '.KKKKKKK.........................KKKKKK',
        '.KKKKKKKK.......................KKKKKKK',
        '.KKKKKKKK.......................KKKKKKK',
        '.KVKKKKKK.......................KKKKKKV',
        '.KKVVKKKK...........K...........KKKKVVK',
        '.KKKKVVKK.....KKKKKKNKKKKKK.....KKVVKKK',
        '.KKKKKKVK...KKNNNNNNNNNNNNNKK...KVKKKKK',
        '.KKKKKKKK.KKooooooNNNNNooooooKK.KKKKKKK',
        '.KKKKKKKKVVVooooooNNNNNooooooVVVKKKKKKK',
        '...KKKKKKKNNNWWWWNNNNNNNWWWWNNNKKKKKKK',
        '.....KKKKKKNNooWWNNNNNNNWWooNNKKKKKK',
        '.......KKKKKNooWWNNNNNNNWWooNKKKKK',
        '.......KKKKKKKNNNNNNNNNNNNNKKKKKKK',
        '........KVVVVKKKKKKKNKKKKKKKVVVVK',
        '........KKKKKVVVVKKKKKKKVVVVKKKKK',
        '........KKKKKKKKKoooooooKKKKKKKKK',
        '.........KKKKKKKKKKKKKKKKKKKKKKK',
        '.........VKVVKKKKKKKKKKKKKKKVVVV',
        '........KK..KVVVVKKKKKKKVVVVK.KKK',
        '.....KKKKK...KKKKKKKKKKKKKK...KKKKKK',
        '..KKKKKK...KK.......K......KKK...KKKKK',
        '..KKK...KKKKK..............KKKKKK...KK',
        '....BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
        '....BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
        '....BBBSSSSSSSSSSSSSSSSSSSSSSSSSSSBBB',
        '',
      ],
    },
  ],
};

const yoganGaniField: MonsterDesign = {
  size: 32,
  colors: {
    K: NQ.slate,
    N: NQ.night,
    V: NQ.vermilion,
    W: NQ.white,
    G: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
    B: NQ.blue,
    S: NQ.sky,
  },
  rim: { [NQ.slate]: NQ.night },
  rimDepth: 1,
  layers: [
    {
      rows: [
        '',
        '',
        '..............G.G.G',
        '.............GGGGGGG',
        '.............GGRRGGG',
        '.KK..........GGRRGGG..........K',
        '.KKKK........QQQQQQQ........KKK',
        '.NNNKK.....................KNNN',
        '.NNNKK.....................KNNN',
        '.NNNKK.....................KNNN',
        '',
        '.KKKKK.....................KKKK',
        '.KKKKKK...................KKKKK',
        '.KKKKKK...................KKKKK',
        '.KVVKKK...................KKKVV',
        '.KKKVVK.........N.........KVVKK',
        '.KKKKKV....NNNNNNNNNNN....VKKKK',
        '.KKKKKK..NoooooNNNoooooN..KKKKK',
        '.KKKKKKVVVoooooNNNoooooVVVKKKKK',
        '...KKKKKKNooWWNNNNNWWooNKKKKKK',
        '.....KKKKKooWWNNNNNWWooKKKKK',
        '......KKKKKKKKKKNKKKKKKKKKK',
        '.......VVVVVVVKKKKKVVVVVVV',
        '.......KKKKKKKoooooKKKKKKK',
        '........KKKKKKKKKKKKKKKKK',
        '.......VKVKKKKKKKKKKKKKVVV',
        '......KK..KVVVKKKKKVVVV.KKK',
        '..KKKKK..K......K.....KK..KKKK',
        '..KKK..KKK............KKKK..KK',
        '...BBBBBBBBBBBBBBBBBBBBBBBBBBB',
        '...BBBSSSSSSSSSSSSSSSSSSSSSBBB',
        '',
      ],
    },
  ],
};

const fujimineOu: MonsterDesign = {
  size: 48,
  colors: {
    N: NQ.denim,
    W: NQ.white,
    C: NQ.ice,
    K: NQ.slate,
    g: NQ.gray,
    F: NQ.green,
    E: NQ.leaf,
    G: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
  },
  rim: { [NQ.denim]: NQ.navy, [NQ.white]: NQ.ice, [NQ.green]: NQ.forest, [NQ.slate]: NQ.night },
  rimDepth: 2,
  layers: [
    {
      rows: [
        '',
        '....................G.G.G.G.G',
        '....................GGGGGGGGG',
        '....................GGGRRGGGG',
        '....................GGGRRGGGG',
        '....................QQQQQQQQQ',
        '........................C',
        '.......................WCW',
        '......................WCCCW',
        '......................WCCCW',
        '.....................WCCCCCW',
        '....................WWWWWWWWW',
        '...................WWWWWWWWWWW',
        '...................WWWWWWWWWWW',
        '..................WWWWWWWWWWWWW',
        '.................WWWWWWWWWWWWWWW',
        '................WWWWWWWWWWWWWWWWW',
        '................WWWWWNNNNNNNWWWWW',
        '.................WWWNNNNNNNNNWWW',
        '................NWWWNNNNNNNNNWWWN',
        '................NWWWNNNNNNNNNWWWN',
        '...............NNWWWNNNNNNNNNWWWNN',
        '............ooooooooooNNNNNoooooooooo',
        '............ooooooooooNNNNNoooooooooo',
        '.............NWWWWWWNNNNNNNNNWWWWWWN',
        '..........N..NoooWWWNNNNNNNNNWWWoooN',
        '.......NNN..NNoooWWWNNNNNNNNNWWWoooNN..NNN',
        '...NNNNNNN.NNNoooWWWNNNNNNNNNWWWoooNNN.NNNNNNN',
        '..NNNNNNNN.NNNNNNNNNNNNNNNNNNNNNNNNNNN.NNNNNNNN',
        '..NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN',
        '..NNNNNNNNNNNNNNNNoooNNNNNNNoooNNNNNNNNNNNNNNNN',
        '..NNNNNNNNNNNNNNNNNNoooooooooNNNNNNNNNNNNNNNNNN',
        '..NNNNN.NNNNNNNNNNNNoooooooooNNNNNNNNNNNN.NNNNN',
        '.KKKKKKKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKKKKKK',
        '.KKKKKKKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKKKKKK',
        '.KgggggKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKggggg',
        '.KgggggKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKggggg',
        '.KKKKKKKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKKKKKK',
        '.KKKKKKKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKKKKKK',
        '.KKKKKKKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKKKKKK',
        '.KKKKKKKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKKKKKK',
        '...NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN',
        '..FFEFFFEFFFEFFFEFFFEFFFEFFFEFFFEFFFEFFFEFFFEFF',
        '..FFEFFFEFFFEFFFEFFFEFFFEFFFEFFFEFFFEFFFEFFFEFF',
        '..FFEFFFEFFFEFFFEFFFEFFFEFFFEFFFEFFFEFFFEFFFEFF',
        '..FFEFFFEFFFEFFFEFFFEFFFEFFFEFFFEFFFEFFFEFFFEFF',
        '..FFEFFFEFFFEFFFEFFFEFFFEFFFEFFFEFFFEFFFEFFFEFF',
        '',
      ],
    },
  ],
};

const fujimineOuP0: MonsterDesign = {
  size: 48,
  colors: {
    V: NQ.brick,
    W: NQ.white,
    C: NQ.cream,
    K: NQ.slate,
    g: NQ.gray,
    F: NQ.green,
    E: NQ.leaf,
    G: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
    Y: NQ.yellow,
  },
  rim: { [NQ.brick]: NQ.ink, [NQ.white]: NQ.cloud, [NQ.green]: NQ.forest, [NQ.slate]: NQ.night },
  rimDepth: 2,
  layers: [
    {
      rows: [
        '',
        '....................G.G.G.G.G',
        '....................GGGGGGGGG',
        '....................GGGRRGGGG',
        '....................GGGRRGGGG',
        '....................QQQQQQQQQ',
        '........................C',
        '.......................WCW',
        '......................WCCCW',
        '......................WCCCW',
        '.....................WCCCCCW',
        '.....Y..............WWWWWWWWW..............Y',
        '....YYY............WWWWWWWWWWW............YYY',
        '.....Y.............WWWWWWWWWWW.............Y',
        '..................WWWWWWWWWWWWW',
        '.................WWWWWWWWWWWWWWW',
        '................WWWWWWWWWWWWWWWWW',
        '................WWWWWVVVVVVVWWWWW',
        '.................WWWVVVVVVVVVWWW',
        '................VWWWVVVVVVVVVWWWV',
        '................VWWWVVVVVVVVVWWWV',
        '...............VVWWWVVVVVVVVVWWWVV',
        '............ooooooooooVVVVVoooooooooo',
        '........Y...ooooooooooVVVVVoooooooooo...Y',
        '.......YYY...VWWWWWWVVVVVVVVVWWWWWWV...YYY',
        '........Y.V..VoooWWWVVVVVVVVVWWWoooV....Y',
        '.......VVV..VVoooWWWVVVVVVVVVWWWoooVV..VVV',
        '...VVVVVVV.VVVoooWWWVVVVVVVVVWWWoooVVV.VVVVVVV',
        '..VVVVVVVV.VVVVVVVVVVVVVVVVVVVVVVVVVVV.VVVVVVVV',
        '..VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV',
        '..VVVVVVVVVVVVVVVVoooVVVVVVVoooVVVVVVVVVVVVVVVV',
        '..VVVVVVVVVVVVVVVVVVoooooooooVVVVVVVVVVVVVVVVVV',
        '..VVVVV.VVVVVVVVVVVVoooooooooVVVVVVVVVVVV.VVVVV',
        '.KKKKKKKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKKKKKK',
        '.KKKKKKKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKKKKKK',
        '.KgggggKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKggggg',
        '.KgggggKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKggggg',
        '.KKKKKKKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKKKKKK',
        '.KKKKKKKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKKKKKK',
        '.KKKKKKKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKKKKKK',
        '.KKKKKKKVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVKKKKKK',
        '...VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV',
        '..FFEFFFEFFFEFFFEFFFEFFFEFFFEFFFEFFFEFFFEFFFEFF',
        '..FFEFFFEFFFEFFFEFFFEFFFEFFFEFFFEFFFEFFFEFFFEFF',
        '..FFEFFFEFFFEFFFEFFFEFFFEFFFEFFFEFFFEFFFEFFFEFF',
        '..FFEFFFEFFFEFFFEFFFEFFFEFFFEFFFEFFFEFFFEFFFEFF',
        '..FFEFFFEFFFEFFFEFFFEFFFEFFFEFFFEFFFEFFFEFFFEFF',
        '',
      ],
    },
  ],
};

const tokugawaIeyasu: MonsterDesign = {
  size: 48,
  colors: {
    N: NQ.night,
    L: NQ.slate,
    G: NQ.gold,
    Y: NQ.cream,
    R: NQ.red,
    K: NQ.night,
    S: NQ.slate,
    T: NQ.bark,
    H: NQ.slate,
    C: NQ.forest,
    F: NQ.skinLight,
    f: NQ.skinMid,
    W: NQ.white,
    M: NQ.hairBlack,
  },
  rim: { [NQ.night]: NQ.ink, [NQ.slate]: NQ.night, [NQ.skinLight]: NQ.skinMid, [NQ.gold]: NQ.ochre, [NQ.forest]: NQ.ink },
  rimDepth: 2,
  layers: [
    {
      rows: [
        '',
        '......................GGGG',
        '......................GGGG',
        '......................GGGG',
        '...................GG.GGGG.GG',
        '....................GGGGGGGG',
        '.....................GGGGGG',
        '......................GGGG',
        '....................GNGGGGNG',
        '.................NNNNGGGGGGNNNN',
        '................NNLLLLGGGGLLLLNN',
        '...............NNLLLLLLLLLLLLLLNN',
        '...............NNNLLLLLLLLLLLLNNN',
        '..............NNNNNNNLNNNNLNNNNNNN',
        '...............NNNNNNNNNNNNNNNNNN',
        '...............NNNNNNNNNNNNNNNNNN',
        '................NNNNNNNNNNNNNNNN',
        '........GGG..GGGGGGGGGGGGGGGGGGGGGG..GGG',
        '........GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
        '........GGGGG.YYYFFFFFFFFFFFFFFYYY.GGGGG',
        '........GRRRG....FFFFFFFFFFFFFF....GRRRG',
        '........GRRRG....FFFFFFFFFFFFFF....GRRRG',
        '........GRRRG.oooooooFFFFFFooooooo.GRRRG',
        '.......GGGGRG..ooWWWoFFFFFFoWWWoo..GRGGGG',
        '.........GGGG..ooWWWFFFFFFFFWWWoo..GGGG',
        '...........GG..ooWWWFFFFFFFFWWWoo..GG',
        '.................FFFFFFFFFFFFFF',
        '............CCCCCFFFFFFFFFFFFFFCCCCC',
        '............CCCCCFFooooooooooFFCCCCC',
        '...........CKKKKMMMMMMMMMMMMMMMMKKKKC',
        '.....KSKKKKKKKKKMMMMMMMMMMMMMMMMKKKKKKKKKSK',
        '...SSSSKKKKKKKKKMMMMMMMMMMMMMMMMKKKKKKKKKSSSS',
        '...SSSSKKKKGGGGGMMMMMMMMMMMMMMMMGGGGGKKKKSSSS',
        '...SGGGGGGGKKKKKKKCGGGGGGGGGGCKKKKKKKGGGGGGGS',
        '...SSSSKKKKKKKKKKKCKKKKRRKKKKCKKKKKKKKKKKSSSS',
        '...SSSSSKKKKKKKKKKCKKKRKKRKKKCKKKKKKKKKKSSSSS',
        '...SSKKKKKKGGGGGGGCKKRKKKKRKKCGGGGGGGKKKKKKSS',
        '...CGGGGGGGKKKKKKKCKRKKKKKKRKCKKKKKKKGGGGGGGC',
        '...CNKKKKKKKKKKKKKCRKKKKKKKKRCKKKKKKKKKKKKKNC',
        '...NNKKKKKKKKKKKKKCGGGGGGGGGGCKKKKKKKKKKKKKNN',
        '...CKKKKKKKGGGGGGGCKKKKKKKKKKCGGGGGGGKKKKKKKC',
        '...CGGGGGGGKKKKKKKCKKKKKKKKKKCKKKKKKKGGGGGGGC',
        '..CCKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKCC',
        '..CCKKKKKKGGGGGGGGGGGGGGGGGGGGGGGGGGGGKKKKKKCC',
        '..CCCCCCCCTGTTTGTTTGTTTGGTTTGTTTGTTTGTCCCCCCCC',
        '..CCCCCCCCTGHHHHHHTGTTTGGTTTGTHHHHHHGTCCCCCCCC',
        '..........TGHHHHHHTGTTTGGTTTGTHHHHHHGT',
        '',
      ],
    },
  ],
};

export const SHIZUOKA: Readonly<Record<string, MonsterDesign>> = {
  'shizuoka-chatsumin': chatsumin,
  'shizuoka-chabashira': chabashira,
  'shizuoka-unanyoro': unanyoro,
  'shizuoka-unagi-nobori': unagiNobori,
  'shizuoka-soradako': soradako,
  'shizuoka-kazekiri-dako': kazekiriDako,
  'shizuoka-wasabikko': wasabikko,
  'shizuoka-tsuun-wasabi': tsuunWasabi,
  'shizuoka-midboss-yogan-gani': yoganGani,
  'shizuoka-midboss-yogan-gani.field': yoganGaniField,
  'shizuoka-boss-fujimine-ou': fujimineOu,
  'shizuoka-boss-fujimine-ou.p0': fujimineOuP0,
  'shizuoka-lastboss-tokugawa-ieyasu': tokugawaIeyasu,
};
