/** 鳥取県の モンスター（手描き。docs/06 §4・§6.3〜6.5 の 規格） */
import { NQ } from '../palette';
import type { MonsterDesign } from './design';

/** ナシコロン：うすい みどりの 皮に 小さな てんてんの ある、まるい 二十世紀梨。じくと 葉っぱ（モリ） */
const nashikoron: MonsterDesign = {
  size: 32,
  colors: {
    L: NQ.sprout,
    d: NQ.sand,
    W: NQ.white,
    p: NQ.blush,
    B: NQ.brown,
    K: NQ.bark,
    G: NQ.green,
    E: NQ.leaf,
  },
  rim: { [NQ.sprout]: NQ.lime },
  rimDepth: 2,
  layers: [
    {
      rows: [
        '................................',
        '.....................GG.........',
        '...................GGEG.........',
        '...............KK.GEEG..........',
        '...............BBGEGG...........',
        '...............BBGG.............',
        '...............BB...............',
        '..........LLLLLBBLLLLL..........',
        '........LLLLLLLLLLLLLLLL........',
        '......LWWLLLdLLLLLLdLLLLLL......',
        '.....LWLLLLLLLLLLLLLLLLLLLL.....',
        '....LLLLdLLLLLLLLLLLLLLdLLLL....',
        '...LLLLLLLLLLLLLLLLLLLLLLLLLL...',
        '..LLLdLLLLLLLLLLLLLLLLLLLLdLLL..',
        '..LLLLLLLLLLLLLLLLLLLLLLLLLLLL..',
        '..LLLLLLLLLWWLLLLLLWWLLLLLLLLL..',
        '.LLLLLLLLLLWoLLLLLLoWLLLLLLLLLL.',
        '.LLLLLLLLLLWoLLLLLLoWLLLLLLLLLL.',
        '.LLdLLLLppLLLLLLLLLLLLppLLLLdLL.',
        '..LLLLLLLLLLLLoLLoLLLLLLLLLLLL..',
        '..LLLLLLLdLLLLLooLLLLLdLLLLLLL..',
        '..LLLLLLLLLLLLLLLLLLLLLLLLLLLL..',
        '...LLLdLLLLLLLLLLLLLLLLLLdLLL...',
        '...LLLLLLLLLLLLLLLLLLLLLLLLLL...',
        '....dLLLLLLLLLLLLLLLLLLLLLLd....',
        '.....LLLLLdLLLLLLLLLLdLLLLL.....',
        '.......LLLLLLLLLLLLLLLLLL.......',
        '.........LLLLLLLLLLLLLL.........',
        '.........GGGLLLLLLLLGGG.........',
        '.........GGGG......GGGG.........',
        '................................',
        '................................',
      ],
    },
  ],
};

/** ニジッセイキシ：ナシコロンの しんか。梨の 花を かざった 梨の 騎士。葉っぱの たてと えだの やり（モリ） */
const nijisseikishi: MonsterDesign = {
  size: 32,
  colors: {
    L: NQ.sprout,
    d: NQ.sand,
    W: NQ.white,
    p: NQ.blush,
    B: NQ.brown,
    K: NQ.bark,
    G: NQ.green,
    E: NQ.leaf,
    Y: NQ.yellow,
    F: NQ.forest,
  },
  rim: { [NQ.sprout]: NQ.lime },
  rimDepth: 2,
  layers: [
    {
      rows: [
        '................................',
        '.....................GG......E..',
        '............W......GGEG.....EGE.',
        '...........WYW.KK.GEEG......EGE.',
        '............W..BBGGG.........G..',
        '...............BB............B..',
        '...............BB............B..',
        '...........LLLLBBLLLL........B..',
        '.........LLLLLLLLLLLLLL......B..',
        '.......WWLLdLLLLLLLLdLLLL....B..',
        '......WLLLLLLLLLLLLLLLLLLL...B..',
        '.....LLdLLLLLLLLLLLLLLLLdLL..B..',
        '...GGGLLLLLLLLLLLLLLLLLLLLL..B..',
        '..GEEEGLLLooLLLLLLLLooLLLLLL.B..',
        '.GEEEEEGLLLLoLLLLLLoLLLLLLLL.B..',
        '.GEEGEEGLLLWWLLLLLLWWLLLLLLL.B..',
        '.GEEGEEGLLLWoLLLLLLoWLLLLLLLLL..',
        '.GEWGWEGLLLWoLLLLLLoWLLLLLdLLL..',
        '.GEEYEEGppLLLLLLLLLLLLppLLLLLL..',
        '.GEWGWEGLLLLLoLLLLoLLLLLLLLL.B..',
        '..GEGEGLLLLLLLooooLLLLLLLLLL.B..',
        '..GEGEGLLLLLLLLLLLLLLLLLLLL..B..',
        '...GEGLLLdLLLLLLLLLLLLdLLLL..B..',
        '....G.BBBBBBBBYYYYBBBBBBBB...B..',
        '.......LLLLLLLLLLLLLLLLLL....B..',
        '.........LLLLLLLLLLLLLL......B..',
        '.........GGGGLLLLLLGGGG......B..',
        '.........GGGG......GGGG......B..',
        '.........GGGG......GGGG......B..',
        '.........FFFF......FFFF......B..',
        '................................',
        '................................',
      ],
    },
  ],
};

/** ベニガニン：境港の ベニズワイガニ。上に ひらいた 大きな はさみ、くきの 先の 目、ほそい あし。まわりに あわ（ミズ） */
const beniganin: MonsterDesign = {
  size: 32,
  colors: { R: NQ.red, A: NQ.vermilion, C: NQ.beige, W: NQ.white, p: NQ.blush, S: NQ.sky },
  rim: { [NQ.red]: NQ.brick, [NQ.beige]: NQ.sand },
  layers: [
    {
      rows: [
        '................................',
        '................................',
        '..AR..RA................AR..RA..',
        '.RRR..RRR..............RRR..RRR.',
        '.RRR..RRR..RR......RR..RRR..RRR.',
        '.RRRRRRRR.RWWR....RWWR.RRRRRRRR.',
        '.RRRRRRRR.RWoR....RoWR.RRRRRRRR.',
        '.RRRRRRRR.RWoR....RoWR.RRRRRSRR.',
        '.RRRRRRRR..RR......RR..RRRRRRRR.',
        '..RRRRRR....R......R....RRRRRR..',
        '......RR....R......R....RR.S....',
        '.......RR...R......R...RR.SWS...',
        '........RAARRRRRRRRRR.RR...S....',
        '........RARRRARRRRARRRRR........',
        '.......RRRRRRRRRRRRRRRRRR.......',
        '......RRRRRRRRRRRRRRRRRRRR......',
        '.....RRRRppRRRRRRRRRRppRRRR.....',
        '.....RRARRRRRRoRRoRRRRRRRRR.....',
        '.....RRRRRRRRRRooRRRRRRRRRR.....',
        '.....RRRRRRRRRRRRRRRRRRRRRR.....',
        '....RRRRRRRRRRRRRRRRRRRRRRRR....',
        '....RR.CCCCCCCCCCCCCCCCCC.RR....',
        '...RR...RRCCCCCCCCCCCCRR...RR...',
        '...RR..RR..RRCCCCCCRR..RR..RR...',
        '...RR..RR..RR......RR..RR..RR...',
        '...RR.RR..RR........RR..RR.RR...',
        '..RR..RR..RR........RR..RR..RR..',
        '..RR..RR..RR........RR..RR..RR..',
        '..RR..RR..RR........RR..RR..RR..',
        '..RR..RR..RR........RR..RR..RR..',
        '................................',
        '................................',
      ],
    },
  ],
};

/** ベニヨロイガニ：ベニガニンの しんか。こうらは よろいの ように かさなり、とげと 金の びょう。大きな はさみ（ミズ） */
const beniyoroigani: MonsterDesign = {
  size: 32,
  colors: {
    R: NQ.red,
    r: NQ.brick,
    A: NQ.vermilion,
    C: NQ.beige,
    Y: NQ.gold,
    W: NQ.white,
    p: NQ.blush,
    S: NQ.sky,
  },
  rim: { [NQ.red]: NQ.brick, [NQ.beige]: NQ.sand },
  layers: [
    {
      rows: [
        '................................',
        '..AAR.RR................RR.RAA..',
        '.RRRC.RRR.ooo......ooo.RRR.CRRR.',
        '.RRRR.CRR..RR......RR..RRC.RRRR.',
        '.RRRCRRRR.RWWR....RWWR.RRRRCRRR.',
        '.RRRRRRRRRRWoR....RoWRRRRRRRRRR.',
        '.RRRRRRRRRRWoR....RoWRRRRRRRRRR.',
        '.RRRRRRRRR.RR......RR.RRRRRRRRR.',
        '.RRRRRRRRR..R......R..RRRRRRRSR.',
        '..RRRRRRR.C.RC....CR.C.RRRRRRR..',
        '...RRRRRR.C.RC....CR.C.RRRRRR...',
        '.....R.RR.RRRRRRRRRRRR.RR.R.S...',
        '........AARRRRRRRRRRRRRR...SWS..',
        '......RRARRRRRRRRRRRRRRRRR..S...',
        '.....rYrrYrrYrrYYrrYrrYrrYr.....',
        '....RRRRppRRRRRRRRRRRRppRRRR....',
        '....RRRRRRRRRoRRRRoRRRRRRRRR....',
        '....RRRRRRRRRRooooRRRRRRRRRR....',
        '....rrRRrrrrrrrrrrrrrrrrRRrr....',
        '....RRRRRRRRRRRRRRRRRRRRRRRR....',
        '....RRRRRRRRRRRRRRRRRRRRRRRR....',
        '...RR.CCCCCCCCCCCCCCCCCCCC.RR...',
        '..RR....RRCCCCCCCCCCCCRR....RR..',
        '..RR...RR.CRRCCCCCCRRC.RR...RR..',
        '..RR..RR..RR........RR..RR..RR..',
        '..RR.RR...RR........RR...RR.RR..',
        '.RR..RR..RR..........RR..RR..RR.',
        '.RR..RR..RR..........RR..RR..RR.',
        '.RR..RR..RR..........RR..RR..RR.',
        '.RR..RR..RR..........RR..RR..RR.',
        '................................',
        '................................',
      ],
    },
  ],
};

/** ペラワシ：因州和紙で できた ぺらぺらの ワシ。紙を かさねた 段々の つばさに 筆の 線、むねに 赤い はんこ（カゼ） */
const perawashi: MonsterDesign = {
  size: 32,
  colors: {
    P: NQ.paper,
    W: NQ.white,
    M: NQ.mint,
    N: NQ.slate,
    Y: NQ.yellow,
    Q: NQ.ochre,
    R: NQ.red,
    p: NQ.blush,
  },
  rim: { [NQ.paper]: NQ.cloud, [NQ.mint]: NQ.aqua, [NQ.yellow]: NQ.ochre },
  layers: [
    {
      rows: [
        '................................',
        '................................',
        '................................',
        '................................',
        '...............PP...............',
        '..............PPPP..............',
        '.W..........P.PPPP.P..........W.',
        '.WW.........PPPPPPPP.........WW.',
        '.WPW..........PPPP..........WPW.',
        '.WPPW......ooPPPPPPPoo.....WPPW.',
        '.MPPPW.....PPoPPPPooP.....WPPPM.',
        '.WMPPPW...PPWWPPPPWWPP...WPPPMW.',
        '..WMPPPWW.PWWoPPPPoWPP.WWPPPMW..',
        '..MMMPPPPWPPWoYYYYoWPPWPPPPMMM..',
        '...WNNPPPPppPPYYYYPPppPPPPNNW...',
        '...WPNNPPPPPPPPYYPPPPPPPPNNPW...',
        '....MMMMPPPPPPPQQPPPPPPPMMMM....',
        '....WPPPPPPPPPPPPPPPPPPPPPPW....',
        '.....MMMMPPPPPPPPPPPPPPMMMM.....',
        '.....WPPPPPPPPPPPPPPPPPPPPW.....',
        '......MMMPPPPPRRRPPPPPPMMM......',
        '.......WPPPPPPRWRPPPPPPPW.......',
        '.........PPPPPRRRPPPPPP.........',
        '..........PPPPPPPPPPPP..........',
        '..........PPPPPPPPPPPP..........',
        '...........PPPPPPPPPP...........',
        '...........PPPPPPPPPP...........',
        '.............PWWWWP.............',
        '............YY....YY............',
        '...........YYYY..YYYY...........',
        '................................',
        '................................',
      ],
    },
  ],
};

/** スミエワシ：ペラワシの しんか。先が すみえの ように 黒い 大きな つばさ、黒い とさか、足で つかんだ 書道の 筆（カゼ） */
const sumiewashi: MonsterDesign = {
  size: 32,
  colors: {
    P: NQ.paper,
    W: NQ.white,
    M: NQ.mint,
    N: NQ.night,
    g: NQ.gray,
    Y: NQ.yellow,
    Q: NQ.ochre,
    R: NQ.red,
    p: NQ.blush,
  },
  rim: { [NQ.paper]: NQ.cloud, [NQ.mint]: NQ.aqua, [NQ.yellow]: NQ.ochre },
  layers: [
    {
      rows: [
        '................................',
        '................................',
        '.N.............NN.............N.',
        '.NN........N..gNNg..N........NN.',
        '.NNg.......gN.gPPg.Ng.......gNN.',
        '.NggP.......gNPPPPNg.......PggN.',
        '.NggPP.......PP..PP.......PPggN.',
        '.NggPPP........PP........PPPggN.',
        '.ggPPPPP..oooPPPPPPooo..PPPPPgg.',
        '..gPPPPPP..PPoPPPPoPP..PPPPPPg..',
        '..gPPPPPPPWWWPPPPPPWWPPPPPPPPg..',
        '.MPPPPPPPPPWoPPPPPPoWPPPPPPPPPM.',
        '..PPPPPPPPPWoPYYYYPoWPPPPPPPPP..',
        '..MPPPPPPPPPPPYYYYPPPPPPPPPPPM..',
        '...PPPPPPppPPPYYYYPPPppPPPPPP...',
        '...PPPPPPPPPPPPQQPPPPPPPPPPPP...',
        '...PPPPPPPPPPPPPPPPPPPPPPPPPP...',
        '...MMPPPPPPPPPPPPPPPPPPPPPPMM...',
        '.....PPPPPPPPPPPPPPPPPPPPPP.....',
        '.....PPPPPPPPPPPPPPPPPPPPPP.....',
        '.....MPPPPPPPPRRRPPPPPPPPPM.....',
        '......MMMPPPPPRWRPPPPPPMMM......',
        '.........PPPPPRRRPPPPPP.........',
        '.........PPPPPPPPPPPPPP.........',
        '..........PgPgPPPPgPgP..........',
        '..........PPPgPPPPgPPP..........',
        '...........PPPPPPPPPP...........',
        '..........YYPPPPPPPYY...........',
        '.....QQQQQYQYQQQQQQYQYQWNNN.....',
        '................................',
        '................................',
        '................................',
      ],
    },
  ],
};

/**
 * ドッシリドゾウ（中ボス）：倉吉の 白壁土蔵が 目を さました 巨大な 石垣の 守り手。
 * 大きく つきだした 赤がわらの 屋根と ひさしの かげ、細く するどい まどの 目、
 * 太い 焼き杉の 板、左右に 身がまえる 石の うで、屋根の てっぺんに 王冠（ツチ）
 */
const dosshiriDozoColors = {
  G: NQ.gold,
  Q: NQ.ochre,
  R: NQ.red,
  r: NQ.brick,
  W: NQ.white,
  c: NQ.cloud,
  N: NQ.night,
  n: NQ.slate,
  g: NQ.gray,
  s: NQ.silver,
};

const dosshiriDozo: MonsterDesign = {
  size: 40,
  colors: dosshiriDozoColors,
  rim: { [NQ.white]: NQ.cloud, [NQ.gray]: NQ.slate, [NQ.red]: NQ.brick },
  rimDepth: 2,
  layers: [
    // 王冠・大屋根・白かべ・焼き杉・石垣（左半分）
    {
      mirror: true,
      rows: [
        '....................',
        '................G..G',
        '................GGGR',
        '................QQQQ',
        '.................RrR',
        '...............rRRrR',
        '.............RRrRRrR',
        '...........RrRRrRRrR',
        '.........rRRrRRrRRrR',
        '.......RRrRRrRRrRRrR',
        '.....RrRRrRRrRRrRRrR',
        '...rRRrRRrRRrRRrRRrR',
        '.RRrRRrRRrRRrRRrRRrR',
        '.rrrrrrrrrrrrrrrrrrr',
        '..nnnnnnnnnnnnnnnnnn',
        '......NNNNNNNNNNNNNN',
        '......WWWWWWWWWWWWWW',
        '......WWWWWWWWWWWWWW',
        '......WWWNNNNNNNWWWW',
        '......WWWWNWWooNWWWW',
        '......WWWWNWoooNWWWW',
        '......WWWWNNNNNNWWWW',
        '......WWWWWWWWWWWWWW',
        '......WWWWWWWWWWWWWW',
        '......NnNNnNNnNNssss',
        '......NnNNnNNnNNccWW',
        '......NnNNnNNnNNccWW',
        '......NnNNnNNnNNccWW',
        '......NnNNnNNnNNccGG',
        '......NnNNnNNnNNccWW',
        '......NnNNnNNnNNccWW',
        '......NnNNnNNnNNssss',
        '...gsgggsgggsgggsggg',
        '...ggggggggggggggggg',
        '...ggggggggggggggggg',
        '........sssssss.....',
        '........ggggggg.....',
        '........ggggggg.....',
        '........ggggggg.....',
      ],
    },
    // 左右に つきだした 石の 太い うでと こぶし
    {
      mirror: true,
      x: 1,
      y: 15,
      rows: [
        '.ssss',
        'sssss',
        'sgggg',
        'sgggg',
        '.gggg',
        '.gggg',
        '.gggg',
        '..ggg',
        '..ggg',
        '..ggg',
        '.gggg',
        'ggggg',
        'sgggg',
        'ggggg',
        'ggggg',
        'ggggg',
        'ggggg',
      ],
    },
    // 足もとに 立つ 土ぼこり
    { mirror: true, x: 4, y: 36, rows: ['ccc', '.cc'] },
  ],
};

/** ドッシリドゾウ（フィールドに 立つ 32×32）。40 の すがたと 同じ かまえ */
const dosshiriDozoField: MonsterDesign = {
  size: 32,
  colors: dosshiriDozoColors,
  rim: { [NQ.white]: NQ.cloud, [NQ.gray]: NQ.slate, [NQ.red]: NQ.brick },
  rimDepth: 2,
  layers: [
    {
      mirror: true,
      rows: [
        '................',
        '............G..G',
        '............GGGR',
        '............QQQQ',
        '..............Rr',
        '............rRRr',
        '..........RRrRRr',
        '........RrRRrRRr',
        '.....RrRRrRRrRRr',
        '..RrRRrRRrRRrRRr',
        '.RRrRRrRRrRRrRRr',
        '.rrrrrrrrrrrrrrr',
        '..nnnnnnnnnnnnnn',
        '.....NNNNNNNNNNN',
        '.....WWWWWWWWWWW',
        '.....WWWNNNNNNWW',
        '.....WWWWNWWoNWW',
        '.....WWWWNWooNWW',
        '.....WWWWNNNNNWW',
        '.....WWWWWWWWWWW',
        '.....NnNNnNNnsss',
        '.....NnNNnNNncWW',
        '.....NnNNnNNncWW',
        '.....NnNNnNNncGG',
        '.....NnNNnNNncWW',
        '.....NnNNnNNnsss',
        '...gsgggsgggsggg',
        '...ggggggggggggg',
        '......ssssss....',
        '......gggggg....',
        '......gggggg....',
      ],
    },
    {
      mirror: true,
      x: 1,
      y: 13,
      rows: [
        '.sss',
        'ssss',
        'sggg',
        '.ggg',
        '.ggg',
        '..gg',
        '..gg',
        '.ggg',
        'gggg',
        'sggg',
        'gggg',
        'gggg',
        'gggg',
      ],
    },
  ],
};

/** サキュウマジン（県ボス）：鳥取砂丘の 砂から 立ちあがった 大マジン。力こぶの うで、金の おびと 王冠、下は 尾根と 風紋の ある 砂丘（ツチ） */
const sakyuMajin: MonsterDesign = {
  size: 48,
  colors: {
    S: NQ.sand,
    T: NQ.tan,
    B: NQ.brown,
    E: NQ.beige,
    G: NQ.gold,
    Q: NQ.ochre,
    R: NQ.red,
    C: NQ.cream,
    W: NQ.white,
    K: NQ.sky,
  },
  rim: { [NQ.sand]: NQ.tan, [NQ.beige]: NQ.sand, [NQ.gold]: NQ.ochre, [NQ.sky]: NQ.azure },
  rimDepth: 2,
  layers: [
    {
      rows: [
        '................................................',
        '....................G..GG..G....................',
        '....................GGGRRGGG....................',
        '....................GGGGGGGG....................',
        '....................QQQQQQQQ....................',
        '......................SSSS......................',
        '....................SSSSSSSS....................',
        '..................EESSSSSSSSSS..................',
        '.....SSS.........BEBSSSSSSSSBBB.........SSS.....',
        '...SSSSSS........SSSBBSSSSBBSSS........SSSSSS...',
        '...SSSSSSS.......SSCCCSSSSCCCSS.......SSSSSSS...',
        '..SBSBSBSS.......SSCCoSSSSoCCSS.......SSBSBSBS..',
        '...SSSSSSS.......SSCooSTTSooCSS.......SSSSSSS...',
        '...SSSSSSS.......SSCooSTTSooCSS.......SSSSSSS...',
        '...SSSSSS........SSSoSSSSSSoSSS.......SSSSSS....',
        '...SSSSSS.........SSSooooooSSS........SSSSSS....',
        '..SSSSSS...........SSSWSSWSSS..........SSSSSS...',
        '..SSSSSSSSSSSS.....SSSSSSSSSS.....SSSSSSSSSSS...',
        '..SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS...',
        '..SSSEESSSSSEESSSSSSSSSTTSSSSSSSSSSSSSSSSEESS...',
        '..SSEESSSSSSESSSSSSSSSSTTSSSSSSSSSSSSSSSSSEES...',
        '..SSSSSSSSSSSTSSSSSSSSSTTSSSSSSSSSTSSSSSSSSSS...',
        '..SSSSSSSSSSSSTTTTTTTSSTTSSTTTTTTTSSSSSSSSSSS...',
        '..SSSSSSSSSSSSSSSSSSSSSTTSSSSSSSSSSSSSSSSSSSS...',
        '...SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS....',
        '...........SSSSSSSSTTSSSSSSTTSSSSSSS............',
        '...........SSSSSSSSSSSSSSSSSSSSSSSSS............',
        '............SSSSSSSTTSSSSSSTTSSSSSS.............',
        '............SSSSSSSSSSSSSSSSSSSSSSS.............',
        '............SSSSSSSSSSSSSSSSSSSSSSS.............',
        '..KKKK.......GGGGGGGGQRRRRQGGGGGGGG.......KKKK..',
        '......K......GGGGGGGGQRRRRQGGGGGGGG......K......',
        '....KK............EEEEEEESSSS.............KK....',
        '................EEEEEEEEEESSSSS.................',
        '...............EEEEEEEEEEEESSSSS................',
        '...KKK.......EEEEEEEEEEEEEETTTTSSS........KKK...',
        '...........EEEEEEEEEEEEEEEEEESSTTTTS............',
        '..........TTTTTEEEEEEEEEEEEEESSSSSSTT...........',
        '.........TEEEEETTTTEEEEEEEEEEESSSSSSSS..........',
        '........EEEEEEEEEEETTTEEEEEEEEESSSSSSSS.........',
        '.......EEEEEEEEEEEEEEEEEEEEEEEETTTTSSSSS........',
        '......EEEETTTTTEEEEEEEEEEEEEEEEEESSTTTTTS.......',
        '.....EETTTEEEEETTTTEEEETTTEEEEEEEESSSSSSSS......',
        '....TTTEEEEEEEEEEEETTTTEEEEEEEEEEEESSSSSSSS.....',
        '...EEEEEEETTTTTEEEEEEEEEEEETTTEEEEEESSSSTTTS....',
        '..EEEEETTTEEEEETTTTEEEETTTTEEEEEEEETTTTTSSSSS...',
        '..TTTTTEEEEEEEEEEEETTTTEEEEEEEEEEEEEEESSSSSSSS..',
        '................................................',
      ],
    },
  ],
};

/** 砂あらし（後半の 前に 重ねる） */
const SAND_STORM = [
  '................................................',
  '..WWWW.........T................T.........WWWW..',
  '.W....W..................................W....W.',
  '.W.WW..W................................W..WW.W.',
  '.W.W.W.W................................W.W.W.W.',
  '..W..W.W................................W.W..W..',
  '...WW..W................................W..WW...',
  '......W..................................W......',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '.........KKKK......................KKKK.........',
  '.............K....................K.............',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '.WW..........................................WW.',
  '...W........................................W...',
  '.WW.W......................................W.WW.',
  '....W......................................W....',
  '..WW........................................WW..',
  '................................................',
  '................................................',
  '............T.T..................T.T............',
  '.............T....................T.............',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '..T..T....................................T..T..',
  '...T........................................T...',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
];

/** サキュウマジン 後半（カゼ）：まわりに 砂あらしの 風が うずまき、目が 白く 光る */
const sakyuMajinP0: MonsterDesign = {
  ...sakyuMajin,
  colors: { ...sakyuMajin.colors, C: NQ.white, K: NQ.mint },
  rim: { [NQ.sand]: NQ.tan, [NQ.beige]: NQ.sand, [NQ.gold]: NQ.ochre, [NQ.mint]: NQ.aqua },
  layers: [{ rows: SAND_STORM }, ...sakyuMajin.layers],
};

/** 大伴家持：黒い 冠と うしろに 立つ 纓（えい）、むらさきの ころもに 金の もよう、笏（しゃく）を もつ 奈良の 歌人。まわりに 因幡の 雪（ミズ） */
const otomoNoYakamochi: MonsterDesign = {
  size: 48,
  colors: {
    H: NQ.hairBlack,
    N: NQ.night,
    F: NQ.skinLight,
    V: NQ.violet,
    I: NQ.indigo,
    L: NQ.lavender,
    G: NQ.gold,
    R: NQ.red,
    E: NQ.beige,
    W: NQ.white,
    K: NQ.sky,
    p: NQ.blush,
  },
  rim: { [NQ.violet]: NQ.indigo, [NQ.skinLight]: NQ.skinMid, [NQ.gold]: NQ.ochre },
  rimDepth: 2,
  layers: [
    {
      rows: [
        '................................................',
        '......................HHHH......................',
        '.....................HNHHHH.....................',
        '.....................HNHHHH.....................',
        '....W................HNHHHH.....................',
        '...WKW...............HNHHHH.....................',
        '....W...............HHHHHHHH...............W....',
        '...................HHHHHHHHHH.............WKW...',
        '..................HHHHHHHHHHHH.............W....',
        '.........W.......HHHHHHHHHHHHHH.................',
        '........WKW......HHHHHHHHHHHHHH.................',
        '.........W.......GGGGGGGGGGGGGG.................',
        '...................FHHHHHHHHF..........W........',
        '..................FFFFFFFFFFFF........WKW.......',
        '..................FoFFFFFFFFoF.........W........',
        '..................FFooFFFFooFF..................',
        '...W..............FFWoFFFFoWFF..................',
        '..WKW.............pFFFFFFFFFFp...............W..',
        '...W...............FFFHFFHFFF...............WKW.',
        '..................IFFFFHHFFFFI...............W..',
        '.................IIIRFFHHFFRIII.................',
        '............VVVVIIIRRRRRRRRRRIIIVVV.............',
        '...........VVVVVVIIIRRRRRRRRIIIVVVVV............',
        '........VVVVVVVVVVIIIIWEEEIIIIVVVVVVVVV.........',
        '.....VVVVVVVVVVVVVVVVVWEEEVVVVVVVVVVVVVVVV......',
        '...VVVVVVVVVVVLLVVVVVVWEEEVVVVVVVVVVVVVVVVVV....',
        '...VVVVVVVVVVVLVVVVVVVWEEEVVVVVVVVVVVVVVVVVV....',
        '...VVLLVVVVVVVVVVVVVVVWEEEVVVVVVVVVVVVVVVVVV....',
        '...VVLVVVVVVVVVVVVVVVVWEEEVVVVVVVVVVVVVVVVVV....',
        '...VVVVVVVVVVVVVVVVVVVWEEEVVVVVVVVVVVVVVVVVV....',
        '...VVVVVGVVVVVVVVVVVFFWEEEFFVVVVVVVVVVVVVGVV....',
        '...VVVVGVGVVVVVVVVVVVFFEEFFVVVVVVVVVVVVVGVGV....',
        '...VVVVVGVVVVVVVVVVVVVWEEEVVVVVVVVVVVVVVVGVV....',
        '...VVVVVVVVVVRRRRRGRRRWEEERRRGRRRRRVVVVVVVVV....',
        '...VVVVVVVVVGRRRRRGRRRWEEERRRGRRRRRVVGVVVVVV....',
        '...VVVVVVVVGVGVVVVVVVVWEEEVVVVVVVVVVGVGVVVVV....',
        '...VVVVVVVVVGVVVVVVVVVWEEEVVVVVVVVVVVGVVVVVV....',
        '...VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV....',
        '...VVVVVGVVVVVVVVVVVVGVVVVVVGVVVVVVVVVVVVGVV....',
        '...VVVVGVGVVVVVVVVVVGVGVVVVGVGVVVVVVVVVVGVGV....',
        '...VVVVVGVVVVVVVVVVVVGVVVVVVGVVVVVVVVVVVVGVV....',
        '....VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV.....',
        '...VVVVVVVVVVVVVGVVVVVVVVVVVVVVVVGVVVVVVVVVV....',
        '...VVVVVVVVVVVVGVGVVVVVVVVVVVVVVGVGVVVVVVVVV....',
        '...VVVVVVVVGVVVVGVVVVVVVVVVVVVVVVGVVVVGVVVVV....',
        '..VVVVVVVVGVGVVHHHHHHHVVVVHHHHHHHVVVVGVGVVVVV...',
        '...........G...HHHHHHH....HHHHHHH.....G.........',
        '................................................',
      ],
    },
  ],
};

const rakkyon: MonsterDesign = {
  size: 32,
  colors: { W: NQ.white, C: NQ.cloud, T: NQ.tan, L: NQ.leaf, G: NQ.green, V: NQ.violet, p: NQ.blush },
  rim: { [NQ.white]: NQ.cloud, [NQ.leaf]: NQ.green },
  layers: [
    {
      mirror: true,
      y: 1,
      rows: [
        '.......VV.......',
        '......VVV.......',
        '.....VVVVV......',
        '......LLL.......',
        '......LLL.......',
        '.....WWWWW......',
        '....WWWWWWW.....',
        '...WWWWWWWWW....',
        '..WWWWWWWWWWW...',
        '.WWWWWWWWWWWWW..',
        '.WWWWWWoWWWWWW..',
        '.WWWWWWWWWWWWW..',
        '.WWWWWpWWWWWWW..',
        '.WWWWWWWWWWWWW..',
        '..WWWWWWWWWWW...',
        '...WWWWWWWWW....',
        '....WWWWWWW.....',
        '.....WWWWW......',
        '......WWW.......',
        '......TTT.......',
        '.....TTTTT......',
        '....TT...TT.....',
        '...TT.....TT....',
        '..TT.......TT...',
        '..TT.......TT...',
        '..TT.......TT...',
        '..TT.......TT...',
        '..TT.......TT...',
        '..TT.......TT...',
      ],
    },
  ],
};
const rakkyoMusha: MonsterDesign = {
  ...rakkyon,
  colors: { ...rakkyon.colors, Y: NQ.gold, R: NQ.red },
  layers: [
    ...rakkyon.layers,
    { mirror: true, y: 2, rows: ['....YYYYYYYY....', '...YYRRYYRRYY...', '....WWWWWWWW....'] },
    { mirror: true, y: 14, rows: ['.WCWCWCWCWCWCWC.', '..WWWWWWWWWWWW..', '...WW......WW...'] },
  ],
};

export const TOTTORI: Readonly<Record<string, MonsterDesign>> = {
  'tottori-nashikoron': nashikoron,
  'tottori-nijisseikishi': nijisseikishi,
  'tottori-beniganin': beniganin,
  'tottori-beniyoroigani': beniyoroigani,
  'tottori-perawashi': perawashi,
  'tottori-sumiewashi': sumiewashi,
  'tottori-rakkyon': rakkyon,
  'tottori-rakkyo-musha': rakkyoMusha,
  'tottori-midboss-dosshiri-dozo': dosshiriDozo,
  'tottori-midboss-dosshiri-dozo.field': dosshiriDozoField,
  'tottori-boss-sakyu-majin': sakyuMajin,
  'tottori-boss-sakyu-majin.p0': sakyuMajinP0,
  'tottori-lastboss-otomo-no-yakamochi': otomoNoYakamochi,
};
